import type { PartySeed } from "@/lib/seeds/reference/politicalParties";

/**
 * East Germany default political parties (1953/1979 presets — the National Front). The ruling
 * SED plus the four allied "bloc" parties (CDU, LDPD, NDPD, DBD), which sat on a
 * single list and never opposed the SED. Gated to the 1953 and 1979 presets. Positions -5..+5.
 */
export const ddParties: PartySeed[] = [
  {
    seedOrder: 1,
    countryId: "DD",
    name: "Sozialistische Einheitspartei Deutschlands",
    abbreviation: "SED",
    color: "#C00000",
    economicPosition: -4,
    socialPosition: 2,
    foreignPolicy: -3,
    culture: 2,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default", "1979-default"],
    regimeStatus: "ruling",
    treasury: 1_000_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 2,
    countryId: "DD",
    name: "Christlich-Demokratische Union (Ost)",
    abbreviation: "CDU",
    color: "#33508C",
    economicPosition: -3,
    socialPosition: 3,
    foreignPolicy: -2,
    culture: 3,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default", "1979-default"],
    regimeStatus: "approved",
    treasury: 300_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 3,
    countryId: "DD",
    name: "Liberal-Demokratische Partei Deutschlands",
    abbreviation: "LDPD",
    color: "#D6A300",
    economicPosition: -2,
    socialPosition: 0,
    foreignPolicy: -2,
    culture: 0,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default", "1979-default"],
    regimeStatus: "approved",
    treasury: 250_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 4,
    countryId: "DD",
    name: "National-Demokratische Partei Deutschlands",
    abbreviation: "NDPD",
    color: "#6E4B8B",
    economicPosition: -3,
    socialPosition: 3,
    foreignPolicy: -2,
    culture: 2,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default", "1979-default"],
    regimeStatus: "approved",
    treasury: 220_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 5,
    countryId: "DD",
    name: "Demokratische Bauernpartei Deutschlands",
    abbreviation: "DBD",
    color: "#2E7D32",
    economicPosition: -3,
    socialPosition: 1,
    foreignPolicy: -2,
    culture: 1,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default", "1979-default"],
    regimeStatus: "approved",
    treasury: 200_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
];

export default ddParties;
