import { describe, it, expect, beforeEach, vi } from "vitest";
import type { Db } from "mongodb";
import { createMockDb, type MockDb } from "@/lib/test-utils/mockDb";
import { processAutoDisasterSpawn, shouldSpawn, staggerHash } from "./autoDisasterSpawn";
import * as selectDisasterTemplateModule from "./selectDisasterTemplate";
import type { CrisisTemplate } from "@/lib/db/types/crisis";

const REGIONS = [
  { _id: "S1", countryId: "BR", regionType: "region", name: "A" },
  { _id: "S2", countryId: "BR", regionType: "region", name: "B" },
];

let db: MockDb;

beforeEach(() => {
  db = createMockDb();
  // Pre-instantiate collections so collectionMocks are populated
  ["countryGameStates", "crises", "states"].forEach((c) => db.collection(c));
  vi.clearAllMocks();
});

function setupHappyPath(lastDisasterTurn: number | null = 0) {
  db.collectionMocks["countryGameStates"]!.findOne.mockResolvedValue(
    lastDisasterTurn !== null ? { _id: "BR", lastDisasterTurn } : null
  );
  db.collectionMocks["crises"]!.findOne.mockResolvedValue(null);
  const cursor = { toArray: vi.fn().mockResolvedValue(REGIONS) };
  db.collectionMocks["states"]!.find.mockReturnValue(cursor);
}

describe("shouldSpawn", () => {
  it("returns false before the cadence boundary", () => {
    expect(shouldSpawn(0, 143, "BR")).toBe(false);
  });

  it("returns true exactly at the 144-turn boundary from lastDisasterTurn", () => {
    expect(shouldSpawn(0, 144, "BR")).toBe(true);
  });

  it("returns false when not yet due after a previous disaster", () => {
    expect(shouldSpawn(144, 200, "BR")).toBe(false);
  });

  it("returns true when due after a previous disaster (288 turns)", () => {
    expect(shouldSpawn(144, 288, "BR")).toBe(true);
  });

  it("fresh country (undefined lastDisasterTurn) becomes due exactly at staggerHash turn", () => {
    const hash = staggerHash("BR");
    // anchor = hash - 144; at currentTurn = hash: diff = hash - (hash - 144) = 144 >= 144 → true
    expect(shouldSpawn(undefined, hash, "BR")).toBe(true);
    // one turn before: diff = 143 → false
    expect(shouldSpawn(undefined, hash - 1, "BR")).toBe(false);
  });
});

describe("processAutoDisasterSpawn", () => {
  it("is a no-op when disabled", async () => {
    await processAutoDisasterSpawn(db as unknown as Db, "BR", 144, { enabled: false });
    expect(db.collectionMocks["countryGameStates"]!.findOne).not.toHaveBeenCalled();
    expect(db.collectionMocks["crises"]!.insertOne).not.toHaveBeenCalled();
  });

  it("is a no-op when opts is omitted", async () => {
    await processAutoDisasterSpawn(db as unknown as Db, "BR", 144);
    expect(db.collectionMocks["countryGameStates"]!.findOne).not.toHaveBeenCalled();
  });

  it("skips when not yet due (before boundary)", async () => {
    db.collectionMocks["countryGameStates"]!.findOne.mockResolvedValue({
      _id: "BR",
      lastDisasterTurn: 10,
    });
    await processAutoDisasterSpawn(db as unknown as Db, "BR", 50, { enabled: true });
    expect(db.collectionMocks["crises"]!.insertOne).not.toHaveBeenCalled();
  });

  it("inserts one region-scoped autoGenerated crisis at the 144-turn boundary", async () => {
    setupHappyPath(0);
    await processAutoDisasterSpawn(db as unknown as Db, "BR", 144, { enabled: true });

    expect(db.collectionMocks["crises"]!.insertOne).toHaveBeenCalledOnce();
    const inserted = db.collectionMocks["crises"]!.insertOne.mock.calls[0]![0] as Record<
      string,
      unknown
    >;
    expect(inserted.autoGenerated).toBe(true);
    expect(inserted.scope).toBe("region");
    expect(inserted.countryIds).toEqual(["BR"]);
    expect((inserted.regionIds as string[]).length).toBe(1);
    expect(inserted.status).toBe("active");

    const effects = inserted.effects as Array<{
      effectType: string;
      targetType: string;
      value: number;
    }>;
    const decay = effects.find((e) => e.effectType === "decay" && e.targetType === "profitMargin");
    expect(decay).toBeDefined();
    // A decaying margin shock is always applied; its magnitude depends on the
    // selected template (generic -10 for natural disasters, or a template-defined
    // value for infrastructure disasters like a bridge collapse).
    expect(decay!.value).toBeLessThan(0);
  });

  it("sets lastDisasterTurn on countryGameStates", async () => {
    setupHappyPath(0);
    await processAutoDisasterSpawn(db as unknown as Db, "BR", 144, { enabled: true });

    expect(db.collectionMocks["countryGameStates"]!.updateOne).toHaveBeenCalledWith(
      { _id: "BR" },
      { $set: { lastDisasterTurn: 144 } },
      { upsert: true }
    );
  });

  it("opens an early weather event without making earthquakes more frequent", async () => {
    setupHappyPath(0);
    const template = (name: string): CrisisTemplate => ({
      name,
      description: name,
      scope: "region",
      naturalDisaster: true,
      durationTurns: 4,
      countryIds: [],
      regionIds: [],
      effects: [],
      wireMessageOnStart: name,
      wireMessageOnEnd: null,
    });
    vi.spyOn(selectDisasterTemplateModule, "disasterTemplatesForCountry").mockReturnValue([
      { key: "earthquake", template: template("Earthquake") },
      { key: "flood", template: template("Flood") },
    ]);

    await processAutoDisasterSpawn(db as unknown as Db, "BR", 120, {
      enabled: true,
      climatePressure: 1,
    });

    expect(db.collectionMocks.crises!.insertOne).toHaveBeenCalledWith(
      expect.objectContaining({ name: "Flood" })
    );
    vi.restoreAllMocks();
  });

  it("debits a bounded weather cost once and reconciles an interrupted replay", async () => {
    setupHappyPath(0);
    db.collectionMocks.states!.find.mockReturnValue({
      toArray: vi.fn().mockResolvedValue([REGIONS[0]]),
    });
    const flood: CrisisTemplate = {
      name: "Flood",
      description: "Flood",
      scope: "region",
      naturalDisaster: true,
      durationTurns: 4,
      countryIds: [],
      regionIds: [],
      effects: [],
      wireMessageOnStart: "Flood",
      wireMessageOnEnd: null,
    };
    vi.spyOn(selectDisasterTemplateModule, "disasterTemplatesForCountry").mockReturnValue([
      { key: "flood", template: flood },
    ]);
    db.collection("stateMetrics").find.mockReturnValue({
      toArray: vi
        .fn()
        .mockResolvedValue([{ _id: "S1", environment: { climateResilience: { value: 0 } } }]),
    });
    db.collection("federalBudget").findOne.mockResolvedValue({ gdp: 1_000_000_000 });
    const charged = new Set<string>();
    let balance = 1_000_000_000;
    db.collection("federalBudget").updateOne.mockImplementation(async (filter, update) => {
      const receipt = filter.disasterFiscalReceipts.$ne as string;
      if (charged.has(receipt)) return { modifiedCount: 0 };
      charged.add(receipt);
      balance += update.$inc.treasuryBalance;
      return { modifiedCount: 1 };
    });

    await processAutoDisasterSpawn(db as unknown as Db, "BR", 144, {
      enabled: true,
      climatePressure: 0.5,
    });
    const inserted = db.collectionMocks.crises!.insertOne.mock.calls[0]![0] as {
      _id: { toString(): string };
      autoDisasterFiscalCost: number;
    };
    expect(inserted.autoDisasterFiscalCost).toBe(250_000);
    expect(balance).toBe(999_750_000);

    // A crash after crisis insertion but before the charge can replay the
    // existing event. The atomic receipt filter prevents a second debit.
    db.collectionMocks.crises!.findOne.mockResolvedValue(inserted);
    await processAutoDisasterSpawn(db as unknown as Db, "BR", 144, {
      enabled: true,
      climatePressure: 0.5,
    });
    expect(charged).toEqual(new Set([inserted._id.toString()]));
    expect(balance).toBe(999_750_000);
    expect(db.collectionMocks.crises!.insertOne).toHaveBeenCalledTimes(1);
    expect(db.collectionMocks.countryGameStates!.updateOne).toHaveBeenCalledWith(
      { _id: "BR" },
      { $max: { lastDisasterTurn: 144 } },
      { upsert: true }
    );
    vi.restoreAllMocks();
  });

  it("skips when an active auto-disaster already exists for the country", async () => {
    db.collectionMocks["countryGameStates"]!.findOne.mockResolvedValue({
      _id: "BR",
      lastDisasterTurn: 0,
    });
    db.collectionMocks["crises"]!.findOne.mockResolvedValue({
      _id: "existing",
      autoGenerated: true,
      status: "active",
      countryIds: ["BR"],
    });

    await processAutoDisasterSpawn(db as unknown as Db, "BR", 144, { enabled: true });
    expect(db.collectionMocks["crises"]!.insertOne).not.toHaveBeenCalled();
  });

  it("skips when no regions exist for the country", async () => {
    db.collectionMocks["countryGameStates"]!.findOne.mockResolvedValue({
      _id: "BR",
      lastDisasterTurn: 0,
    });
    db.collectionMocks["crises"]!.findOne.mockResolvedValue(null);
    const cursor = { toArray: vi.fn().mockResolvedValue([]) };
    db.collectionMocks["states"]!.find.mockReturnValue(cursor);

    await processAutoDisasterSpawn(db as unknown as Db, "BR", 144, { enabled: true });
    expect(db.collectionMocks["crises"]!.insertOne).not.toHaveBeenCalled();
  });

  it("falls back to AUTO_DISASTER_DEFAULT_DURATION_TURNS (24) when template duration resolves to null", async () => {
    // Stub the eligible-template set to a single no-geo template with no duration
    // info, so the candidate selector picks it for any region and the duration
    // resolves to the default.
    const nullDurationTemplate: CrisisTemplate = {
      name: "Test Flood",
      description: "A test flood",
      scope: "region",
      naturalDisaster: true,
      durationTurns: null,
      durationByScope: undefined,
      countryIds: [],
      regionIds: [],
      effects: [],
      wireMessageOnStart: "Test flood incoming",
      wireMessageOnEnd: null,
    };
    vi.spyOn(selectDisasterTemplateModule, "disasterTemplatesForCountry").mockReturnValue([
      { key: "test_flood", template: nullDurationTemplate },
    ]);

    db.collectionMocks["countryGameStates"]!.findOne.mockResolvedValue({
      _id: "BR",
      lastDisasterTurn: 0,
    });
    db.collectionMocks["crises"]!.findOne.mockResolvedValue(null);
    const cursor = { toArray: vi.fn().mockResolvedValue(REGIONS) };
    db.collectionMocks["states"]!.find.mockReturnValue(cursor);

    await processAutoDisasterSpawn(db as unknown as Db, "BR", 144, { enabled: true });

    const inserted = db.collectionMocks["crises"]!.insertOne.mock.calls[0]![0] as Record<
      string,
      unknown
    >;
    expect(inserted.durationTurns).toBe(24);

    vi.restoreAllMocks();
  });

  it("region filter excludes 'nation' rows and selects only sub-national regions", async () => {
    db.collectionMocks["countryGameStates"]!.findOne.mockResolvedValue({
      _id: "BR",
      lastDisasterTurn: 0,
    });
    db.collectionMocks["crises"]!.findOne.mockResolvedValue(null);

    // The mock .find() is called with a filter; simulate the $nin filter by returning only
    // sub-national regions (the real DB would exclude "nation" rows via $nin)
    const subNationalRegions = [
      { _id: "S1", countryId: "BR", regionType: "state", name: "A" },
      { _id: "S2", countryId: "BR", regionType: "state", name: "B" },
    ];
    const cursor = { toArray: vi.fn().mockResolvedValue(subNationalRegions) };
    db.collectionMocks["states"]!.find.mockReturnValue(cursor);

    await processAutoDisasterSpawn(db as unknown as Db, "BR", 144, { enabled: true });

    // Verify the find was called with a filter excluding null and "nation"
    const findCall = db.collectionMocks["states"]!.find.mock.calls[0]![0] as Record<
      string,
      unknown
    >;
    const regionTypeFilter = (findCall as any).regionType as Record<string, unknown>;
    expect(regionTypeFilter.$nin).toContain(null);
    expect(regionTypeFilter.$nin).toContain("nation");
    // Constituencies are sub-regional (single seats) — too small for a
    // nation-scale natural disaster, so they are excluded too.
    expect(regionTypeFilter.$nin).toContain("constituency");

    // The inserted crisis regionIds must not reference the nation row
    const inserted = db.collectionMocks["crises"]!.insertOne.mock.calls[0]![0] as Record<
      string,
      unknown
    >;
    expect((inserted.regionIds as string[])[0]).not.toBe("NATION_ROW");
    expect(["S1", "S2"]).toContain((inserted.regionIds as string[])[0]);
  });
});
