import { beforeEach, describe, expect, it, vi } from "vitest";
import { ObjectId, type Db } from "mongodb";
import { createMockDb, type MockDb } from "@/lib/test-utils/mockDb";
import type { Crisis } from "@/lib/db/types/crisis";

const { createCrisisFromTemplate, createCrisisInteraction, isCrisisInteractionEnabled } =
  vi.hoisted(() => ({
    createCrisisFromTemplate: vi.fn(),
    createCrisisInteraction: vi.fn(),
    isCrisisInteractionEnabled: vi.fn(),
  }));

vi.mock("./createCrisisFromTemplate", () => ({ createCrisisFromTemplate }));
vi.mock("./interactionEngine", () => ({ createCrisisInteraction }));
vi.mock("./featureFlag", () => ({ isCrisisInteractionEnabled }));

import {
  bankFailureResponseEventId,
  ensureBankFailureResponseWindow,
} from "./bankFailureResponseWindow";
import { canCharacterInteract, canRespondToCrisis } from "./rules/authorization";

describe("bank failure response window", () => {
  let db: MockDb;

  beforeEach(() => {
    vi.clearAllMocks();
    db = createMockDb();
    db.collection("crises");
    isCrisisInteractionEnabled.mockResolvedValue(true);
    createCrisisFromTemplate.mockResolvedValue(new ObjectId());
  });

  it("keys one response window to the bank charter epoch and exposes funded responses to domestic offices", async () => {
    const bankId = new ObjectId();
    const crisisId = await ensureBankFailureResponseWindow(db as unknown as Db, {
      bankId,
      countryId: "US",
      charteredTurn: 4,
      currentTurn: 1991,
    });

    expect(crisisId).toBeInstanceOf(ObjectId);
    expect(createCrisisFromTemplate).toHaveBeenCalledTimes(1);
    const params = createCrisisFromTemplate.mock.calls[0]![1];
    expect(params.livingConflictEventId).toBe(bankFailureResponseEventId(bankId.toString(), 4));
    expect(params.scope).toBe("country");
    expect(params.countryIds).toEqual(["US"]);
    expect(params.currentTurn).toBe(1991);
    const node = params.template.interactionDefinition.decisionTree[0];
    expect(node.requiredRoles).toEqual(["headOfState", "financeMinister", "centralBankChair"]);
    expect(node.options[0]?.optionId).toBe("decline");
    expect(
      node.options
        .filter((option: { action?: { response?: string } }) => option.action)
        .map((option: { action: { response?: string } }) => option.action.response)
    ).toEqual(["recapitalize", "guarantee", "resolve"]);
    expect(canCharacterInteract(node, ["any", "financeMinister"], "US")).toBe(true);
    expect(canCharacterInteract(node, ["any", "centralBankChair"], "US")).toBe(true);
    expect(canRespondToCrisis(params, node, "US")).toBe(true);
    expect(canRespondToCrisis(params, node, "CA")).toBe(false);
  });

  it("repairs a missing interaction after a crash between crisis insertion and interaction creation", async () => {
    const bankId = new ObjectId();
    const crisis: Crisis = {
      _id: new ObjectId(),
      name: "Domestic Bank Stress",
      description: "Stressed bank",
      heroImage: "",
      scope: "country",
      countryIds: ["US"],
      regionIds: [],
      status: "active",
      startTurn: 9,
      endTurn: null,
      durationTurns: 3,
      effects: [],
      wireMessageOnStart: "",
      wireMessageOnEnd: null,
      createdBy: null,
      createdAt: new Date(),
      resolvedAt: null,
      autoGenerated: true,
      autoSource: "condition",
      templateKey: "bank_failure_response",
      interactionDefinition: { autoResolveOnExpiry: true, decisionTree: [] },
      livingConflictEventId: bankFailureResponseEventId(bankId.toString(), 4),
    } as Crisis;
    db.collectionMocks.crises!.findOne.mockResolvedValue(crisis);

    await ensureBankFailureResponseWindow(db as unknown as Db, {
      bankId,
      countryId: "US",
      charteredTurn: 4,
      currentTurn: 10,
    });

    expect(createCrisisFromTemplate).not.toHaveBeenCalled();
    expect(createCrisisInteraction).toHaveBeenCalledWith(db, crisis);
  });

  it("does not create a crisis while crisis interactions are disabled", async () => {
    isCrisisInteractionEnabled.mockResolvedValue(false);
    await ensureBankFailureResponseWindow(db as unknown as Db, {
      bankId: new ObjectId(),
      countryId: "US",
      charteredTurn: 4,
      currentTurn: 10,
    });
    expect(createCrisisFromTemplate).not.toHaveBeenCalled();
  });
});
