import type { Db } from "mongodb";
import { ObjectId } from "mongodb";
import type { Crisis, CrisisEffect, CrisisTemplate } from "@/lib/db/types/crisis";
import { getTemplateDuration } from "./templates";
import { isCrisisInteractionEnabled } from "./featureFlag";
import { createCrisisInteraction } from "./interactionEngine";
import { floorCrisisDuration } from "./crisisDuration";
import { resolveCrisisLocationName, interpolateLocation } from "./crisisLocation";

export interface CreateCrisisParams {
  template: CrisisTemplate;
  /** The `ALL_CRISIS_TEMPLATES` key, stored on the crisis so a chained family can
   *  tell which rung just ended. Optional: unchained crises never need it. */
  templateKey?: string;
  scope: Crisis["scope"];
  countryIds: string[];
  regionIds: string[];
  currentTurn: number;
  /** Defaults to true (auto-spawned). Admin manual creation sets false. */
  autoGenerated?: boolean;
  /** Which automatic spawner produced this crisis (disaster / condition / random). */
  autoSource?: Crisis["autoSource"];
  /** Override the template's effects (the disaster spawner uses this to inject a
   *  decay margin penalty). Falls back to the template's own effects. */
  effects?: CrisisEffect[];
  /** Override resolved duration. Falls back to the template's scope-aware default. */
  durationTurns?: number | null;
}

/**
 * Insert a Crisis document from a template and, when crisis interactions are
 * enabled and the template carries a decision tree, create its interaction doc
 * immediately (so it isn't lost once the turn advances past `startTurn`).
 * Returns the new crisis `_id`.
 */
export async function createCrisisFromTemplate(
  db: Db,
  params: CreateCrisisParams
): Promise<ObjectId> {
  const { template, scope, countryIds, regionIds, currentTurn, autoGenerated = true } = params;

  const authoredDuration =
    params.durationTurns !== undefined
      ? params.durationTurns
      : (getTemplateDuration(template, scope) ?? template.durationTurns ?? null);
  // Chain rungs keep their AUTHORED duration: on a ladder the rung length IS the
  // pacing mechanic (Vietnam authors 8/10/12/14/16 escalating turns and a
  // 4-turn commitment window), and flooring every rung to 24 flattened all of
  // it into one uniform day per rung. Standalone crises keep the floor so their
  // effects have room to taper.
  const resolvedDuration = template.chain
    ? authoredDuration
    : floorCrisisDuration(authoredDuration);

  // Bake the real affected place name into flavor/wire text so notifications,
  // metadata and the detail page all read with the location, not "{location}".
  const locationName = await resolveCrisisLocationName(db, { scope, countryIds, regionIds });

  const crisis: Omit<Crisis, "_id"> = {
    name: template.name,
    description: interpolateLocation(template.description, locationName),
    heroImage: template.heroImage,
    scope,
    countryIds,
    regionIds,
    status: "active",
    startTurn: currentTurn,
    endTurn: null,
    durationTurns: resolvedDuration,
    effects: params.effects ?? template.effects,
    wireMessageOnStart: interpolateLocation(template.wireMessageOnStart, locationName),
    wireMessageOnEnd: template.wireMessageOnEnd
      ? interpolateLocation(template.wireMessageOnEnd, locationName)
      : null,
    templateKey: params.templateKey,
    chain: template.chain,
    createdBy: null,
    createdAt: new Date(),
    resolvedAt: null,
    autoGenerated,
    autoSource: params.autoSource,
    interactionDefinition: template.interactionDefinition,
  };

  const result = await db.collection<Crisis>("crises").insertOne(crisis as Crisis);

  if (crisis.interactionDefinition && (await isCrisisInteractionEnabled())) {
    await createCrisisInteraction(db, { ...(crisis as Crisis), _id: result.insertedId });
  }

  return result.insertedId;
}
