import { ObjectId } from "mongodb";
import type { Achievement } from "@/lib/db/types";

const now = new Date();

/**
 * Seed data for achievements. Each has a stable slug for lookups.
 * Order determines display order (lower = first).
 */
export const ACHIEVEMENT_SEED: Omit<Achievement, "_id">[] = [
  // Special
  {
    slug: "alpha_tester",
    name: "Founding Father",
    description: "Joined during the alpha phase of the game",
    icon: "FlaskConical",
    category: "special",
    triggerType: "character_created",
    isHidden: false,
    order: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "patreon_supporter_plus",
    name: "Patron Plus",
    description: "Reached Supporter+ on Patreon",
    icon: "Sparkles",
    category: "special",
    triggerType: "manual_only",
    isHidden: false,
    order: 1,
    createdAt: now,
    updatedAt: now,
  },
  // Action-based
  {
    slug: "first_fundraise",
    name: "Passing the Hat",
    description: "Completed your first fundraise",
    icon: "HandCoins",
    category: "action",
    triggerType: "action_count",
    triggerConfig: { actionType: "fundraise", count: 1 },
    isHidden: false,
    order: 10,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "fundraiser",
    name: "K Street Regular",
    description: "Raised funds 10 times",
    icon: "BadgeDollarSign",
    category: "action",
    triggerType: "action_count",
    triggerConfig: { actionType: "fundraise", count: 10 },
    isHidden: false,
    order: 11,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "big_fundraiser",
    name: "Money Machine",
    description: "Raised funds 50 times",
    icon: "Banknote",
    category: "action",
    triggerType: "action_count",
    triggerConfig: { actionType: "fundraise", count: 50 },
    isHidden: false,
    order: 12,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "campaigner",
    name: "Stump Speaker",
    description: "Campaigned 10 times",
    icon: "Vote",
    category: "action",
    triggerType: "action_count",
    triggerConfig: { actionType: "campaign", count: 10 },
    isHidden: false,
    order: 13,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "grassroots",
    name: "Whistle Stop",
    description: "Built donor base 5 times",
    icon: "Sprout",
    category: "action",
    triggerType: "action_count",
    triggerConfig: { actionType: "buildDonorBase", count: 5 },
    isHidden: false,
    order: 14,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "pollster",
    name: "Gallup's Ghost",
    description: "Commissioned 5 polls",
    icon: "ChartNoAxesColumnIncreasing",
    category: "action",
    triggerType: "action_count",
    triggerConfig: { actionTypes: ["poll", "pollLarge"], count: 5 },
    isHidden: false,
    order: 15,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "advertiser",
    name: "Prime Time",
    description: "Ran 3 ad campaigns",
    icon: "Tv",
    category: "action",
    triggerType: "action_count",
    triggerConfig: { actionType: "advertise", count: 3 },
    isHidden: false,
    order: 16,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "rested",
    name: "Executive Time",
    description: "Rested to recover actions",
    icon: "Bed",
    category: "action",
    triggerType: "action_count",
    triggerConfig: { actionType: "rest", count: 1 },
    isHidden: false,
    order: 17,
    createdAt: now,
    updatedAt: now,
  },
  // Election-based
  {
    slug: "first_candidate",
    name: "Throwing Your Hat In",
    description: "Entered your first election",
    icon: "Target",
    category: "election",
    triggerType: "election_entered",
    isHidden: false,
    order: 20,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "house_candidate",
    name: "Mr. Smith Goes to Washington",
    description: "Ran for the U.S. House",
    icon: "House",
    category: "election",
    triggerType: "election_entered",
    triggerConfig: { electionType: "house" },
    isHidden: false,
    order: 21,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "senate_candidate",
    name: "Senatorial Ambition",
    description: "Ran for the U.S. Senate",
    icon: "Building2",
    category: "election",
    triggerType: "election_entered",
    triggerConfig: { electionType: "senate" },
    isHidden: false,
    order: 22,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "governor_candidate",
    name: "Mansion on the Hill",
    description: "Ran for Governor",
    icon: "Star",
    category: "election",
    triggerType: "election_entered",
    triggerConfig: { electionType: "governor" },
    isHidden: false,
    order: 23,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "president_candidate",
    name: "Hail to the Chief",
    description: "Entered a presidential race",
    icon: "Flag",
    category: "election",
    triggerType: "election_entered",
    triggerConfig: { electionType: "president" },
    isHidden: false,
    order: 24,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "presidential_nominee",
    name: "The Nomination",
    description: "Won your party's presidential primary",
    icon: "Medal",
    category: "election",
    triggerType: "primary_won",
    triggerConfig: { electionType: "president" },
    isHidden: false,
    order: 25,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "house_member",
    name: "The People's Voice",
    description: "Won a U.S. House seat",
    icon: "Landmark",
    category: "election",
    triggerType: "election_won",
    triggerConfig: { electionType: "house" },
    isHidden: false,
    order: 30,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "senator",
    name: "The Upper Chamber",
    description: "Won a U.S. Senate seat",
    icon: "Scale",
    category: "election",
    triggerType: "election_won",
    triggerConfig: { electionType: "senate" },
    isHidden: false,
    order: 31,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "governor",
    name: "The Governor's Mansion",
    description: "Won a gubernatorial election",
    icon: "Badge",
    category: "election",
    triggerType: "election_won",
    triggerConfig: { electionType: "governor" },
    isHidden: false,
    order: 32,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "state_senator",
    name: "The Statehouse",
    description: "Won a state senate seat",
    icon: "ScrollText",
    category: "election",
    triggerType: "election_won",
    triggerConfig: { electionType: "stateSenate" },
    isHidden: false,
    order: 33,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "president",
    name: "Leader of the Free World",
    description: "Became President",
    icon: "Shield",
    category: "election",
    triggerType: "office_held",
    triggerConfig: { officeType: "president" },
    isHidden: false,
    order: 34,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "vice_president",
    name: "A Heartbeat Away",
    description: "Became Vice President",
    icon: "Bird",
    category: "election",
    triggerType: "office_held",
    triggerConfig: { officeType: "vicePresident" },
    isHidden: false,
    order: 35,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "three_terms",
    name: "The Incumbent",
    description: "Won 3 elections",
    icon: "ClipboardCheck",
    category: "election",
    triggerType: "election_won",
    triggerConfig: { count: 3 },
    isHidden: false,
    order: 36,
    createdAt: now,
    updatedAt: now,
  },
  // Legislation
  {
    slug: "first_bill",
    name: "The First Draft",
    description: "Sponsored your first bill",
    icon: "FileText",
    category: "legislation",
    triggerType: "bill_sponsored",
    isHidden: false,
    order: 40,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "lawmaker",
    name: "Filibuster Buster",
    description: "Had a bill pass into law",
    icon: "CircleCheck",
    category: "legislation",
    triggerType: "bill_passed",
    isHidden: false,
    order: 41,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "cosponsor",
    name: "Across the Aisle",
    description: "Cosponsored a bill",
    icon: "Handshake",
    category: "legislation",
    triggerType: "bill_cosponsored",
    isHidden: false,
    order: 42,
    createdAt: now,
    updatedAt: now,
  },
  // Influence / Social
  {
    slug: "influencer",
    name: "Pulling Strings",
    description: "Influenced another character 5 times",
    icon: "Megaphone",
    category: "social",
    triggerType: "influence_count",
    triggerConfig: { count: 5 },
    isHidden: false,
    order: 50,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "barnstormer",
    name: "Rough Rider",
    description: "Used barnstorm on a character",
    icon: "Tornado",
    category: "social",
    triggerType: "influence_type",
    triggerConfig: { actionType: "barnstorm" },
    isHidden: false,
    order: 51,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "first_subscriber",
    name: "Following the Trail",
    description: "Subscribed to another character",
    icon: "Eye",
    category: "social",
    triggerType: "subscribe",
    isHidden: false,
    order: 52,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "popular",
    name: "Beltway Buzz",
    description: "Gained 5 subscribers",
    icon: "Heart",
    category: "social",
    triggerType: "subscriber_count",
    triggerConfig: { count: 5 },
    isHidden: false,
    order: 53,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "celebrity",
    name: "Front Page News",
    description: "Gained 20 subscribers",
    icon: "Newspaper",
    category: "social",
    triggerType: "subscriber_count",
    triggerConfig: { count: 20 },
    isHidden: false,
    order: 54,
    createdAt: now,
    updatedAt: now,
  },
  // Funds
  {
    slug: "millionaire",
    name: "Fat Cat",
    description: "Reached $1,000,000 in campaign funds",
    icon: "CircleDollarSign",
    category: "milestone",
    triggerType: "funds_threshold",
    triggerConfig: { amount: 1_000_000 },
    isHidden: false,
    order: 60,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "big_spender",
    name: "Pork Barrel",
    description: "Received funds from another character",
    icon: "Gift",
    category: "milestone",
    triggerType: "fund_transfer",
    triggerConfig: { role: "receiver" },
    isHidden: false,
    order: 61,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "donor",
    name: "The Bundler",
    description: "Donated to another character's campaign",
    icon: "HandHeart",
    category: "milestone",
    triggerType: "fund_transfer",
    triggerConfig: { role: "sender" },
    isHidden: false,
    order: 62,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "speaker_candidate",
    name: "Order in the House",
    description: "Ran for Speaker of the House",
    icon: "AudioLines",
    category: "milestone",
    triggerType: "speaker_nominated",
    isHidden: false,
    order: 71,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "party_leader",
    name: "The Kingmaker",
    description: "Held a party leadership position",
    icon: "Crown",
    category: "milestone",
    triggerType: "leadership_held",
    isHidden: false,
    order: 72,
    createdAt: now,
    updatedAt: now,
  },
  // News / Engagement
  {
    slug: "first_post",
    name: "Off the Record",
    description: "Made your first news post",
    icon: "FilePenLine",
    category: "social",
    triggerType: "news_post",
    isHidden: false,
    order: 80,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "commenter",
    name: "The Pundit",
    description: "Replied to 5 news posts",
    icon: "MessageCircle",
    category: "social",
    triggerType: "news_reply",
    triggerConfig: { count: 5 },
    isHidden: false,
    order: 81,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "policy_shift",
    name: "Flip-Flopper",
    description: "Changed your policy positions",
    icon: "RefreshCw",
    category: "social",
    triggerType: "policy_shift",
    isHidden: false,
    order: 82,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "beta2_veteran",
    name: "Cold War Veteran",
    description: "Played during Beta 2, the era before the 1953 relaunch",
    icon: "History",
    category: "special",
    triggerType: "manual_only",
    isHidden: false,
    order: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "iteration4_founder",
    name: "Fourth Founding",
    description: "Joined the Fourth Founding and the 1953 relaunch",
    icon: "Landmark",
    category: "special",
    triggerType: "passive_profile",
    isHidden: false,
    order: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "wiki_contributor",
    name: "Keeper of the Record",
    description: "Contributed research, corrections, or new lore to the wiki",
    icon: "BookOpen",
    category: "special",
    triggerType: "manual_only",
    isHidden: false,
    order: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "iron_triangle",
    name: "Iron Triangle",
    description: "Held elected office, a Cabinet seat, and party leadership at once",
    icon: "Triangle",
    category: "special",
    triggerType: "passive_profile",
    isHidden: true,
    order: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "turn_one",
    name: "In at the Ground Floor",
    description: "Took an action in turn one of a brand-new era",
    icon: "Rocket",
    category: "special",
    triggerType: "action_event",
    isHidden: true,
    order: 6,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "night_shift",
    name: "Night Shift",
    description: "Took an action between midnight and 1am server time",
    icon: "Moon",
    category: "special",
    triggerType: "action_event",
    isHidden: true,
    order: 7,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "completionist",
    name: "The Completionist",
    description: "Earned every other achievement in the game",
    icon: "Gem",
    category: "special",
    triggerType: "system",
    isHidden: true,
    order: 8,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "century_club",
    name: "Century Club",
    description: "Logged 100 actions with one character",
    icon: "Award",
    category: "action",
    triggerType: "action_count",
    triggerConfig: { count: 100 },
    isHidden: false,
    order: 18,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "cabinet_seat",
    name: "At the President's Table",
    description: "Accepted an appointment to a Cabinet position",
    icon: "Users",
    category: "election",
    triggerType: "passive_profile",
    isHidden: false,
    order: 37,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "central_banker",
    name: "Master of the Mint",
    description: "Became Chair of a Central Bank",
    icon: "PiggyBank",
    category: "election",
    triggerType: "passive_profile",
    isHidden: false,
    order: 38,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "party_founder",
    name: "A Party of One",
    description: "Founded a new political party",
    icon: "FlagTriangleRight",
    category: "election",
    triggerType: "manual_only",
    isHidden: false,
    order: 39,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "corner_office",
    name: "Corner Office",
    description: "Took the CEO seat of a corporation",
    icon: "Briefcase",
    category: "milestone",
    triggerType: "passive_profile",
    isHidden: false,
    order: 63,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "bondholder",
    name: "Clip the Coupon",
    description: "Collected steady income from bonds",
    icon: "ScrollText",
    category: "milestone",
    triggerType: "passive_profile",
    isHidden: false,
    order: 64,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "dividend_day",
    name: "Dividend Day",
    description: "Collected dividend income from shares",
    icon: "Coins",
    category: "milestone",
    triggerType: "passive_profile",
    isHidden: false,
    order: 65,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "elder_statesman",
    name: "Elder Statesman",
    description: "Kept one character active for 30 real-world days",
    icon: "Hourglass",
    category: "milestone",
    triggerType: "passive_profile",
    isHidden: false,
    order: 66,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "built_different",
    name: "Built Different",
    description: "Allocated every point that makes a politician tick",
    icon: "Dumbbell",
    category: "milestone",
    triggerType: "passive_profile",
    isHidden: false,
    order: 67,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "onboarded",
    name: "Learned the Ropes",
    description: "Completed new-player onboarding",
    icon: "GraduationCap",
    category: "milestone",
    triggerType: "passive_profile",
    isHidden: false,
    order: 68,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "hall_of_famer",
    name: "Hall of Famer",
    description: "Cracked the Top 10 of the global Hall of Fame",
    icon: "Trophy",
    category: "milestone",
    triggerType: "passive_profile",
    isHidden: false,
    order: 69,
    createdAt: now,
    updatedAt: now,
  },
  {
    slug: "dealmaker",
    name: "Dealmaker",
    description: "Closed a corporate merger or acquisition",
    icon: "Handshake",
    category: "milestone",
    triggerType: "manual_only",
    isHidden: false,
    order: 70,
    createdAt: now,
    updatedAt: now,
  },
];

/** Create achievement documents with generated ObjectIds for insertion. */
export function getAchievementDocsForSeed(): (Achievement & { _id: ObjectId })[] {
  return ACHIEVEMENT_SEED.map((a) => ({
    ...a,
    _id: new ObjectId(),
  }));
}
