import type { Layer1Config } from "./stateDemographics";

/**
 * Projected January 2027 US state demographic profiles.
 *
 * Race (B03002), education among adults 25+ (B15003), household income
 * (B19001), and age among adults 18+ (B01001) use ACS 1-year estimates for
 * 2022, 2023, and 2024. Each underlying share is fitted with a least-squares
 * linear trend and evaluated at 2027, clamped at zero, then largest-remainder
 * rounded so every dimension totals 100. Income is expressed in nominal ACS
 * brackets: low below $50,000, middle $50,000 to $149,999, high $150,000+.
 *
 * Ideology is not an ACS measure. Its independent, non-additive shares are a
 * game calibration anchored to each state's certified 2024 presidential margin.
 * Regenerate with scripts/seeds/generate-state-census-2027.ts.
 */
export const stateCensusData2027: Record<string, Layer1Config> = {
  AK: {
    race: { white: 56, black: 2, hispanic: 8, asian: 6, other: 28 },
    education: { no_college: 64, college: 20, graduate: 16 },
    wealth: { low: 22, middle: 44, high: 34 },
    age: { young: 31, mid: 28, mature: 20, senior: 21 },
    ideology: {
      evangelicals: 26,
      environmentalists: 11,
      libertarians: 10,
      progressives: 11,
      patriots: 27,
      gunowners: 33,
    },
  },
  AL: {
    race: { white: 61, black: 24, hispanic: 8, asian: 2, other: 5 },
    education: { no_college: 69, college: 19, graduate: 12 },
    wealth: { low: 31, middle: 49, high: 20 },
    age: { young: 27, mid: 25, mature: 23, senior: 25 },
    ideology: {
      evangelicals: 31,
      environmentalists: 8,
      libertarians: 10,
      progressives: 6,
      patriots: 30,
      gunowners: 38,
    },
  },
  AR: {
    race: { white: 65, black: 14, hispanic: 11, asian: 2, other: 8 },
    education: { no_college: 70, college: 19, graduate: 11 },
    wealth: { low: 34, middle: 49, high: 17 },
    age: { young: 28, mid: 26, mature: 22, senior: 24 },
    ideology: {
      evangelicals: 31,
      environmentalists: 8,
      libertarians: 10,
      progressives: 6,
      patriots: 31,
      gunowners: 38,
    },
  },
  AZ: {
    race: { white: 51, black: 5, hispanic: 31, asian: 4, other: 9 },
    education: { no_college: 63, college: 21, graduate: 16 },
    wealth: { low: 24, middle: 48, high: 28 },
    age: { young: 29, mid: 24, mature: 21, senior: 26 },
    ideology: {
      evangelicals: 24,
      environmentalists: 12,
      libertarians: 10,
      progressives: 13,
      patriots: 26,
      gunowners: 31,
    },
  },
  CA: {
    race: { white: 31, black: 5, hispanic: 41, asian: 17, other: 6 },
    education: { no_college: 60, college: 24, graduate: 16 },
    wealth: { low: 22, middle: 41, high: 37 },
    age: { young: 29, mid: 27, mature: 22, senior: 22 },
    ideology: {
      evangelicals: 16,
      environmentalists: 16,
      libertarians: 10,
      progressives: 19,
      patriots: 21,
      gunowners: 25,
    },
  },
  CO: {
    race: { white: 62, black: 4, hispanic: 24, asian: 4, other: 6 },
    education: { no_college: 50, college: 29, graduate: 21 },
    wealth: { low: 19, middle: 45, high: 36 },
    age: { young: 31, mid: 27, mature: 20, senior: 22 },
    ideology: {
      evangelicals: 19,
      environmentalists: 15,
      libertarians: 10,
      progressives: 17,
      patriots: 23,
      gunowners: 27,
    },
  },
  CT: {
    race: { white: 58, black: 10, hispanic: 21, asian: 5, other: 6 },
    education: { no_college: 56, college: 24, graduate: 20 },
    wealth: { low: 22, middle: 41, high: 37 },
    age: { young: 27, mid: 24, mature: 23, senior: 26 },
    ideology: {
      evangelicals: 18,
      environmentalists: 15,
      libertarians: 10,
      progressives: 18,
      patriots: 22,
      gunowners: 26,
    },
  },
  DC: {
    race: { white: 36, black: 39, hispanic: 14, asian: 6, other: 5 },
    education: { no_college: 34, college: 28, graduate: 38 },
    wealth: { low: 25, middle: 33, high: 42 },
    age: { young: 38, mid: 30, mature: 16, senior: 16 },
    ideology: {
      evangelicals: 4,
      environmentalists: 27,
      libertarians: 9,
      progressives: 35,
      patriots: 10,
      gunowners: 9,
    },
  },
  DE: {
    race: { white: 53, black: 21, hispanic: 14, asian: 6, other: 6 },
    education: { no_college: 65, college: 19, graduate: 16 },
    wealth: { low: 23, middle: 48, high: 29 },
    age: { young: 25, mid: 23, mature: 23, senior: 29 },
    ideology: {
      evangelicals: 18,
      environmentalists: 15,
      libertarians: 10,
      progressives: 18,
      patriots: 22,
      gunowners: 26,
    },
  },
  FL: {
    race: { white: 47, black: 14, hispanic: 31, asian: 3, other: 5 },
    education: { no_college: 62, college: 23, graduate: 15 },
    wealth: { low: 25, middle: 49, high: 26 },
    age: { young: 25, mid: 25, mature: 23, senior: 27 },
    ideology: {
      evangelicals: 26,
      environmentalists: 11,
      libertarians: 10,
      progressives: 11,
      patriots: 27,
      gunowners: 33,
    },
  },
  GA: {
    race: { white: 45, black: 30, hispanic: 13, asian: 6, other: 6 },
    education: { no_college: 61, college: 23, graduate: 16 },
    wealth: { low: 27, middle: 46, high: 27 },
    age: { young: 29, mid: 26, mature: 23, senior: 22 },
    ideology: {
      evangelicals: 23,
      environmentalists: 13,
      libertarians: 10,
      progressives: 13,
      patriots: 25,
      gunowners: 31,
    },
  },
  HI: {
    race: { white: 21, black: 2, hispanic: 9, asian: 37, other: 31 },
    education: { no_college: 59, college: 26, graduate: 15 },
    wealth: { low: 17, middle: 47, high: 36 },
    age: { young: 25, mid: 25, mature: 21, senior: 29 },
    ideology: {
      evangelicals: 15,
      environmentalists: 17,
      libertarians: 10,
      progressives: 20,
      patriots: 21,
      gunowners: 24,
    },
  },
  IA: {
    race: { white: 79, black: 5, hispanic: 9, asian: 3, other: 4 },
    education: { no_college: 69, college: 20, graduate: 11 },
    wealth: { low: 28, middle: 52, high: 20 },
    age: { young: 29, mid: 25, mature: 21, senior: 25 },
    ideology: {
      evangelicals: 26,
      environmentalists: 11,
      libertarians: 10,
      progressives: 11,
      patriots: 27,
      gunowners: 33,
    },
  },
  ID: {
    race: { white: 76, black: 1, hispanic: 15, asian: 2, other: 6 },
    education: { no_college: 66, college: 22, graduate: 12 },
    wealth: { low: 23, middle: 52, high: 25 },
    age: { young: 29, mid: 25, mature: 21, senior: 25 },
    ideology: {
      evangelicals: 32,
      environmentalists: 7,
      libertarians: 11,
      progressives: 5,
      patriots: 32,
      gunowners: 39,
    },
  },
  IL: {
    race: { white: 55, black: 13, hispanic: 21, asian: 7, other: 4 },
    education: { no_college: 58, college: 25, graduate: 17 },
    wealth: { low: 27, middle: 44, high: 29 },
    age: { young: 29, mid: 25, mature: 22, senior: 24 },
    ideology: {
      evangelicals: 19,
      environmentalists: 15,
      libertarians: 10,
      progressives: 17,
      patriots: 23,
      gunowners: 27,
    },
  },
  IN: {
    race: { white: 72, black: 8, hispanic: 11, asian: 3, other: 6 },
    education: { no_college: 68, college: 20, graduate: 12 },
    wealth: { low: 29, middle: 50, high: 21 },
    age: { young: 29, mid: 25, mature: 22, senior: 24 },
    ideology: {
      evangelicals: 27,
      environmentalists: 10,
      libertarians: 10,
      progressives: 9,
      patriots: 28,
      gunowners: 35,
    },
  },
  KS: {
    race: { white: 70, black: 5, hispanic: 16, asian: 3, other: 6 },
    education: { no_college: 63, college: 23, graduate: 14 },
    wealth: { low: 26, middle: 51, high: 23 },
    age: { young: 29, mid: 25, mature: 21, senior: 25 },
    ideology: {
      evangelicals: 27,
      environmentalists: 10,
      libertarians: 10,
      progressives: 10,
      patriots: 28,
      gunowners: 34,
    },
  },
  KY: {
    race: { white: 77, black: 6, hispanic: 8, asian: 3, other: 6 },
    education: { no_college: 72, college: 16, graduate: 12 },
    wealth: { low: 34, middle: 48, high: 18 },
    age: { young: 29, mid: 25, mature: 22, senior: 24 },
    ideology: {
      evangelicals: 31,
      environmentalists: 8,
      libertarians: 10,
      progressives: 6,
      patriots: 30,
      gunowners: 38,
    },
  },
  LA: {
    race: { white: 53, black: 29, hispanic: 11, asian: 2, other: 5 },
    education: { no_college: 71, college: 18, graduate: 11 },
    wealth: { low: 36, middle: 45, high: 19 },
    age: { young: 27, mid: 27, mature: 21, senior: 25 },
    ideology: {
      evangelicals: 28,
      environmentalists: 9,
      libertarians: 10,
      progressives: 9,
      patriots: 29,
      gunowners: 36,
    },
  },
  MA: {
    race: { white: 62, black: 6, hispanic: 16, asian: 8, other: 8 },
    education: { no_college: 49, college: 26, graduate: 25 },
    wealth: { low: 20, middle: 39, high: 41 },
    age: { young: 29, mid: 25, mature: 22, senior: 24 },
    ideology: {
      evangelicals: 15,
      environmentalists: 17,
      libertarians: 10,
      progressives: 20,
      patriots: 20,
      gunowners: 24,
    },
  },
  MD: {
    race: { white: 43, black: 28, hispanic: 16, asian: 7, other: 6 },
    education: { no_college: 54, college: 23, graduate: 23 },
    wealth: { low: 20, middle: 41, high: 39 },
    age: { young: 26, mid: 27, mature: 23, senior: 24 },
    ideology: {
      evangelicals: 14,
      environmentalists: 18,
      libertarians: 10,
      progressives: 21,
      patriots: 20,
      gunowners: 23,
    },
  },
  ME: {
    race: { white: 87, black: 3, hispanic: 3, asian: 1, other: 6 },
    education: { no_college: 61, college: 23, graduate: 16 },
    wealth: { low: 26, middle: 48, high: 26 },
    age: { young: 25, mid: 22, mature: 23, senior: 30 },
    ideology: {
      evangelicals: 20,
      environmentalists: 14,
      libertarians: 10,
      progressives: 16,
      patriots: 24,
      gunowners: 28,
    },
  },
  MI: {
    race: { white: 70, black: 13, hispanic: 7, asian: 4, other: 6 },
    education: { no_college: 65, college: 21, graduate: 14 },
    wealth: { low: 30, middle: 49, high: 21 },
    age: { young: 28, mid: 23, mature: 23, senior: 26 },
    ideology: {
      evangelicals: 22,
      environmentalists: 13,
      libertarians: 10,
      progressives: 14,
      patriots: 25,
      gunowners: 30,
    },
  },
  MN: {
    race: { white: 73, black: 8, hispanic: 8, asian: 5, other: 6 },
    education: { no_college: 59, college: 27, graduate: 14 },
    wealth: { low: 23, middle: 49, high: 28 },
    age: { young: 28, mid: 26, mature: 21, senior: 25 },
    ideology: {
      evangelicals: 21,
      environmentalists: 14,
      libertarians: 10,
      progressives: 15,
      patriots: 24,
      gunowners: 29,
    },
  },
  MO: {
    race: { white: 76, black: 10, hispanic: 7, asian: 2, other: 5 },
    education: { no_college: 64, college: 21, graduate: 15 },
    wealth: { low: 28, middle: 50, high: 22 },
    age: { young: 28, mid: 25, mature: 22, senior: 25 },
    ideology: {
      evangelicals: 27,
      environmentalists: 10,
      libertarians: 10,
      progressives: 9,
      patriots: 28,
      gunowners: 35,
    },
  },
  MS: {
    race: { white: 54, black: 35, hispanic: 5, asian: 2, other: 4 },
    education: { no_college: 70, college: 18, graduate: 12 },
    wealth: { low: 38, middle: 46, high: 16 },
    age: { young: 28, mid: 24, mature: 24, senior: 24 },
    ideology: {
      evangelicals: 29,
      environmentalists: 9,
      libertarians: 10,
      progressives: 8,
      patriots: 29,
      gunowners: 36,
    },
  },
  MT: {
    race: { white: 83, black: 0, hispanic: 6, asian: 1, other: 10 },
    education: { no_college: 61, college: 26, graduate: 13 },
    wealth: { low: 25, middle: 52, high: 23 },
    age: { young: 26, mid: 25, mature: 21, senior: 28 },
    ideology: {
      evangelicals: 28,
      environmentalists: 10,
      libertarians: 10,
      progressives: 9,
      patriots: 29,
      gunowners: 35,
    },
  },
  NC: {
    race: { white: 56, black: 19, hispanic: 14, asian: 4, other: 7 },
    education: { no_college: 61, college: 22, graduate: 17 },
    wealth: { low: 28, middle: 48, high: 24 },
    age: { young: 29, mid: 25, mature: 23, senior: 23 },
    ideology: {
      evangelicals: 23,
      environmentalists: 12,
      libertarians: 10,
      progressives: 13,
      patriots: 26,
      gunowners: 31,
    },
  },
  ND: {
    race: { white: 78, black: 4, hispanic: 6, asian: 2, other: 10 },
    education: { no_college: 63, college: 25, graduate: 12 },
    wealth: { low: 27, middle: 51, high: 22 },
    age: { young: 33, mid: 25, mature: 18, senior: 24 },
    ideology: {
      evangelicals: 32,
      environmentalists: 7,
      libertarians: 11,
      progressives: 5,
      patriots: 32,
      gunowners: 39,
    },
  },
  NE: {
    race: { white: 71, black: 4, hispanic: 16, asian: 3, other: 6 },
    education: { no_college: 64, college: 22, graduate: 14 },
    wealth: { low: 25, middle: 53, high: 22 },
    age: { young: 31, mid: 26, mature: 20, senior: 23 },
    ideology: {
      evangelicals: 28,
      environmentalists: 10,
      libertarians: 10,
      progressives: 9,
      patriots: 29,
      gunowners: 35,
    },
  },
  NH: {
    race: { white: 86, black: 1, hispanic: 6, asian: 3, other: 4 },
    education: { no_college: 59, college: 25, graduate: 16 },
    wealth: { low: 21, middle: 44, high: 35 },
    age: { young: 25, mid: 23, mature: 24, senior: 28 },
    ideology: {
      evangelicals: 21,
      environmentalists: 13,
      libertarians: 10,
      progressives: 15,
      patriots: 24,
      gunowners: 29,
    },
  },
  NJ: {
    race: { white: 47, black: 12, hispanic: 26, asian: 11, other: 4 },
    education: { no_college: 54, college: 27, graduate: 19 },
    wealth: { low: 19, middle: 42, high: 39 },
    age: { young: 27, mid: 26, mature: 23, senior: 24 },
    ideology: {
      evangelicals: 20,
      environmentalists: 14,
      libertarians: 10,
      progressives: 15,
      patriots: 24,
      gunowners: 29,
    },
  },
  NM: {
    race: { white: 36, black: 2, hispanic: 47, asian: 2, other: 13 },
    education: { no_college: 66, college: 19, graduate: 15 },
    wealth: { low: 29, middle: 48, high: 23 },
    age: { young: 27, mid: 26, mature: 20, senior: 27 },
    ideology: {
      evangelicals: 20,
      environmentalists: 14,
      libertarians: 10,
      progressives: 16,
      patriots: 24,
      gunowners: 28,
    },
  },
  NV: {
    race: { white: 41, black: 9, hispanic: 31, asian: 10, other: 9 },
    education: { no_college: 69, college: 20, graduate: 11 },
    wealth: { low: 24, middle: 48, high: 28 },
    age: { young: 28, mid: 26, mature: 23, senior: 23 },
    ideology: {
      evangelicals: 23,
      environmentalists: 13,
      libertarians: 10,
      progressives: 13,
      patriots: 26,
      gunowners: 31,
    },
  },
  NY: {
    race: { white: 51, black: 13, hispanic: 21, asian: 10, other: 5 },
    education: { no_college: 57, college: 24, graduate: 19 },
    wealth: { low: 27, middle: 41, high: 32 },
    age: { young: 28, mid: 24, mature: 23, senior: 25 },
    ideology: {
      evangelicals: 18,
      environmentalists: 15,
      libertarians: 10,
      progressives: 17,
      patriots: 23,
      gunowners: 27,
    },
  },
  OH: {
    race: { white: 73, black: 12, hispanic: 6, asian: 3, other: 6 },
    education: { no_college: 67, college: 20, graduate: 13 },
    wealth: { low: 29, middle: 49, high: 22 },
    age: { young: 28, mid: 24, mature: 22, senior: 26 },
    ideology: {
      evangelicals: 25,
      environmentalists: 11,
      libertarians: 10,
      progressives: 11,
      patriots: 27,
      gunowners: 33,
    },
  },
  OK: {
    race: { white: 59, black: 6, hispanic: 15, asian: 3, other: 17 },
    education: { no_college: 70, college: 19, graduate: 11 },
    wealth: { low: 31, middle: 52, high: 17 },
    age: { young: 30, mid: 26, mature: 21, senior: 23 },
    ideology: {
      evangelicals: 31,
      environmentalists: 8,
      libertarians: 11,
      progressives: 6,
      patriots: 31,
      gunowners: 38,
    },
  },
  OR: {
    race: { white: 68, black: 2, hispanic: 17, asian: 5, other: 8 },
    education: { no_college: 60, college: 24, graduate: 16 },
    wealth: { low: 25, middle: 46, high: 29 },
    age: { young: 26, mid: 27, mature: 21, senior: 26 },
    ideology: {
      evangelicals: 18,
      environmentalists: 15,
      libertarians: 10,
      progressives: 18,
      patriots: 22,
      gunowners: 27,
    },
  },
  PA: {
    race: { white: 70, black: 10, hispanic: 11, asian: 5, other: 4 },
    education: { no_college: 62, college: 22, graduate: 16 },
    wealth: { low: 28, middle: 47, high: 25 },
    age: { young: 27, mid: 24, mature: 22, senior: 27 },
    ideology: {
      evangelicals: 22,
      environmentalists: 13,
      libertarians: 10,
      progressives: 14,
      patriots: 25,
      gunowners: 30,
    },
  },
  RI: {
    race: { white: 63, black: 5, hispanic: 21, asian: 4, other: 7 },
    education: { no_college: 62, college: 21, graduate: 17 },
    wealth: { low: 29, middle: 41, high: 30 },
    age: { young: 28, mid: 24, mature: 22, senior: 26 },
    ideology: {
      evangelicals: 18,
      environmentalists: 15,
      libertarians: 10,
      progressives: 18,
      patriots: 22,
      gunowners: 27,
    },
  },
  SC: {
    race: { white: 60, black: 21, hispanic: 10, asian: 3, other: 6 },
    education: { no_college: 66, college: 21, graduate: 13 },
    wealth: { low: 27, middle: 49, high: 24 },
    age: { young: 27, mid: 24, mature: 23, senior: 26 },
    ideology: {
      evangelicals: 27,
      environmentalists: 10,
      libertarians: 10,
      progressives: 10,
      patriots: 28,
      gunowners: 35,
    },
  },
  SD: {
    race: { white: 78, black: 2, hispanic: 5, asian: 2, other: 13 },
    education: { no_college: 62, college: 25, graduate: 13 },
    wealth: { low: 24, middle: 54, high: 22 },
    age: { young: 28, mid: 25, mature: 21, senior: 26 },
    ideology: {
      evangelicals: 30,
      environmentalists: 8,
      libertarians: 10,
      progressives: 7,
      patriots: 30,
      gunowners: 37,
    },
  },
  TN: {
    race: { white: 69, black: 14, hispanic: 10, asian: 2, other: 5 },
    education: { no_college: 66, college: 20, graduate: 14 },
    wealth: { low: 29, middle: 49, high: 22 },
    age: { young: 29, mid: 25, mature: 23, senior: 23 },
    ideology: {
      evangelicals: 30,
      environmentalists: 8,
      libertarians: 10,
      progressives: 7,
      patriots: 30,
      gunowners: 37,
    },
  },
  TX: {
    race: { white: 36, black: 13, hispanic: 40, asian: 7, other: 4 },
    education: { no_college: 63, college: 23, graduate: 14 },
    wealth: { low: 25, middle: 47, high: 28 },
    age: { young: 31, mid: 28, mature: 22, senior: 19 },
    ideology: {
      evangelicals: 26,
      environmentalists: 11,
      libertarians: 10,
      progressives: 11,
      patriots: 27,
      gunowners: 33,
    },
  },
  UT: {
    race: { white: 69, black: 1, hispanic: 20, asian: 3, other: 7 },
    education: { no_college: 59, college: 26, graduate: 15 },
    wealth: { low: 19, middle: 50, high: 31 },
    age: { young: 37, mid: 27, mature: 19, senior: 17 },
    ideology: {
      evangelicals: 28,
      environmentalists: 10,
      libertarians: 10,
      progressives: 9,
      patriots: 29,
      gunowners: 35,
    },
  },
  VA: {
    race: { white: 56, black: 17, hispanic: 13, asian: 7, other: 7 },
    education: { no_college: 55, college: 25, graduate: 20 },
    wealth: { low: 22, middle: 45, high: 33 },
    age: { young: 27, mid: 27, mature: 22, senior: 24 },
    ideology: {
      evangelicals: 20,
      environmentalists: 14,
      libertarians: 10,
      progressives: 15,
      patriots: 24,
      gunowners: 29,
    },
  },
  VT: {
    race: { white: 88, black: 1, hispanic: 3, asian: 2, other: 6 },
    education: { no_college: 54, college: 28, graduate: 18 },
    wealth: { low: 22, middle: 51, high: 27 },
    age: { young: 23, mid: 24, mature: 23, senior: 30 },
    ideology: {
      evangelicals: 13,
      environmentalists: 18,
      libertarians: 10,
      progressives: 22,
      patriots: 19,
      gunowners: 22,
    },
  },
  WA: {
    race: { white: 58, black: 4, hispanic: 17, asian: 12, other: 9 },
    education: { no_college: 57, college: 25, graduate: 18 },
    wealth: { low: 20, middle: 44, high: 36 },
    age: { young: 30, mid: 27, mature: 20, senior: 23 },
    ideology: {
      evangelicals: 17,
      environmentalists: 16,
      libertarians: 10,
      progressives: 19,
      patriots: 22,
      gunowners: 25,
    },
  },
  WI: {
    race: { white: 76, black: 6, hispanic: 10, asian: 3, other: 5 },
    education: { no_college: 64, college: 24, graduate: 12 },
    wealth: { low: 26, middle: 51, high: 23 },
    age: { young: 28, mid: 24, mature: 22, senior: 26 },
    ideology: {
      evangelicals: 22,
      environmentalists: 13,
      libertarians: 10,
      progressives: 14,
      patriots: 25,
      gunowners: 30,
    },
  },
  WV: {
    race: { white: 87, black: 3, hispanic: 3, asian: 1, other: 6 },
    education: { no_college: 77, college: 14, graduate: 9 },
    wealth: { low: 35, middle: 49, high: 16 },
    age: { young: 26, mid: 23, mature: 23, senior: 28 },
    ideology: {
      evangelicals: 34,
      environmentalists: 6,
      libertarians: 11,
      progressives: 4,
      patriots: 33,
      gunowners: 40,
    },
  },
  WY: {
    race: { white: 79, black: 1, hispanic: 12, asian: 1, other: 7 },
    education: { no_college: 64, college: 24, graduate: 12 },
    wealth: { low: 27, middle: 48, high: 25 },
    age: { young: 27, mid: 25, mature: 20, senior: 28 },
    ideology: {
      evangelicals: 35,
      environmentalists: 6,
      libertarians: 11,
      progressives: 4,
      patriots: 33,
      gunowners: 41,
    },
  },
};
