import type { State } from "@/lib/db/types";

/**
 * UK regions, 1991 Census population + 1991 nominal regional GVA (GBP millions).
 *
 * Population: 1991 Census of England + 1991 NI Census + 1991 GROS Scotland.
 * GDP: ONS Workplace-Based Gross Value Added 1991 (approximate; ONS revised
 * the regional series in 2004 and 2010 — figures here are pre-revision).
 * House district counts follow the 1992 GE constituency boundaries (651 total
 * across 12 game regions).
 * stateSenateSeats follow the modern Regional Council configuration —
 * regional councils didn't exist in 1992 (anachronistic compromise).
 */
export const ukRegions1991: State[] = [
  {
    _id: "LON",
    countryId: "UK",
    regionType: "constituency",
    parentRegionId: "ENG",
    name: "London",
    population: 6_889_000,
    gdp: 80_000,
    houseDistricts: 84,
    stateSenateSeats: 32,
    region: "London",
    votingSystem: "fptp",
  },
  {
    _id: "SEE",
    countryId: "UK",
    regionType: "constituency",
    parentRegionId: "ENG",
    name: "South East England",
    population: 7_550_000,
    gdp: 65_000,
    houseDistricts: 91,
    stateSenateSeats: 67,
    region: "South East",
    votingSystem: "fptp",
  },
  {
    _id: "SWE",
    countryId: "UK",
    regionType: "constituency",
    parentRegionId: "ENG",
    name: "South West England",
    population: 4_682_000,
    gdp: 32_000,
    houseDistricts: 51,
    stateSenateSeats: 39,
    region: "South West",
    votingSystem: "fptp",
  },
  {
    _id: "EAE",
    countryId: "UK",
    regionType: "constituency",
    parentRegionId: "ENG",
    name: "East of England",
    population: 5_106_000,
    gdp: 39_000,
    houseDistricts: 54,
    stateSenateSeats: 39,
    region: "East",
    votingSystem: "fptp",
  },
  {
    _id: "EMI",
    countryId: "UK",
    regionType: "constituency",
    parentRegionId: "ENG",
    name: "East Midlands",
    population: 4_032_000,
    gdp: 28_000,
    houseDistricts: 42,
    stateSenateSeats: 39,
    region: "East Midlands",
    votingSystem: "fptp",
  },
  {
    _id: "WMI",
    countryId: "UK",
    regionType: "constituency",
    parentRegionId: "ENG",
    name: "West Midlands",
    population: 5_265_000,
    gdp: 36_000,
    houseDistricts: 58,
    stateSenateSeats: 18,
    region: "West Midlands",
    votingSystem: "fptp",
  },
  {
    _id: "YHU",
    countryId: "UK",
    regionType: "constituency",
    parentRegionId: "ENG",
    name: "Yorkshire & the Humber",
    population: 4_983_000,
    gdp: 32_000,
    houseDistricts: 54,
    stateSenateSeats: 21,
    region: "Yorkshire & the Humber",
    votingSystem: "fptp",
  },
  {
    _id: "NWE",
    countryId: "UK",
    regionType: "constituency",
    parentRegionId: "ENG",
    name: "North West England",
    population: 6_834_000,
    gdp: 44_000,
    houseDistricts: 74,
    stateSenateSeats: 27,
    region: "North West",
    votingSystem: "fptp",
  },
  {
    _id: "NEE",
    countryId: "UK",
    regionType: "constituency",
    parentRegionId: "ENG",
    name: "North East England",
    population: 2_603_000,
    gdp: 16_500,
    houseDistricts: 30,
    stateSenateSeats: 17,
    region: "North East",
    votingSystem: "fptp",
  },
  {
    _id: "SCO",
    countryId: "UK",
    regionType: "constituency",
    parentRegionId: "GBN",
    name: "Scotland",
    population: 5_102_000,
    gdp: 36_000,
    houseDistricts: 72,
    stateSenateSeats: 129,
    region: "Scotland",
    votingSystem: "fptp",
  },
  {
    _id: "WAL",
    countryId: "UK",
    regionType: "constituency",
    parentRegionId: "GBN",
    name: "Wales",
    population: 2_891_000,
    gdp: 17_000,
    houseDistricts: 38,
    stateSenateSeats: 60,
    region: "Wales",
    votingSystem: "fptp",
  },
  {
    _id: "NIR",
    countryId: "UK",
    regionType: "constituency",
    parentRegionId: "GBN",
    name: "Northern Ireland",
    population: 1_577_000,
    gdp: 7_500,
    houseDistricts: 17,
    stateSenateSeats: 90,
    region: "Northern Ireland",
    votingSystem: "fptp",
  },
];
