import { describe, expect, it, vi } from "vitest";
import type { Db } from "mongodb";
import { createInMemoryDb } from "@/lib/test-utils/inMemoryDb";
import { migration } from "./2026-10-09-subhour-wiki-cadence";

function setup() {
  const memory = createInMemoryDb();
  memory.seed("wikiPages", [
    {
      _id: "authored",
      slug: "stock-market",
      content:
        "A player's trading notes.\nShare prices are computed each turn from three fundamental components:\nKeep these notes.",
    },
    {
      _id: "bank",
      slug: "central-banks",
      content: "On top of macro drift, two additional forces apply each turn:",
    },
    {
      _id: "generated",
      slug: "national-metrics",
      isAutoGenerated: true,
      content: "Inflation is recalculated **every turn** (not just annually), incorporating:",
    },
  ]);
  return { memory, db: memory as unknown as Db };
}

describe("sub-hour wiki timing migration", () => {
  it("preserves authored notes, skips generated pages, and is safe to run again", async () => {
    const { memory, db } = setup();
    expect((await migration.execute(db, { dryRun: false })).documentsUpdated).toBe(2);
    const docs = structuredClone(memory.collection("wikiPages").docs);
    expect(docs.find((doc) => doc._id === "authored")?.content).toBe(
      "A player's trading notes.\nIn multiplayer, share prices are recomputed every 15 minutes from three fundamental components. Earnings update on the hourly turn:\nKeep these notes."
    );
    expect(docs.find((doc) => doc._id === "generated")?.content).toContain("**every turn**");
    expect((await migration.execute(db, { dryRun: false })).documentsUpdated).toBe(0);
  });

  it("does not mutate pages during a dry run", async () => {
    const { memory, db } = setup();
    const before = structuredClone(memory.collection("wikiPages").docs);
    await migration.execute(db, { dryRun: true });
    expect(structuredClone(memory.collection("wikiPages").docs)).toEqual(before);
  });

  it("keeps a concurrent edit and leaves the migration eligible for retry", async () => {
    const { memory, db } = setup();
    const collection = memory.collection("wikiPages");
    const original = collection.updateOne.bind(collection);
    vi.spyOn(collection, "updateOne").mockImplementationOnce(async (filter, update) => {
      await original({ _id: "authored" }, { $set: { content: "A newer human edit" } });
      return original(filter, update);
    });
    await expect(migration.execute(db, { dryRun: false })).rejects.toThrow("raced with an edit");
    expect(
      structuredClone(memory.collection("wikiPages").docs).find((doc) => doc._id === "authored")
        ?.content
    ).toBe("A newer human edit");
  });
});
