import type { WikiPage } from "@/lib/db/types";
import type { Migration } from "../types";

// Replace only legacy clock descriptions, preserving authored content around them.
const replacements: Record<string, readonly (readonly [string, string])[]> = {
  "stock-market": [
    [
      "Share prices are computed each turn from three fundamental components:",
      "In multiplayer, share prices are recomputed every 15 minutes from three fundamental components. Earnings update on the hourly turn:",
    ],
    [
      "**Speculation:** Share prices react to economic events each turn via the fundamental formula. If you anticipate a subsidy bill passing or a major sector entering a state, position before the turn processes.",
      "**Speculation:** Share prices react to changing cash, bonds, rates, trading and sentiment every 15 minutes via the fundamental formula. Earnings and sector production still update on the hourly turn.",
    ],
  ],
  "national-metrics": [
    [
      "Inflation is recalculated **every turn** (not just annually), incorporating:",
      "In multiplayer, inflation advances halfway at half past each hour, with the hourly turn applying the rest of the step. The model incorporates:",
    ],
  ],
  "central-banks": [
    [
      "The prime rate is one of four macro factors that drive the exchange rate target each turn. The full macro target formula is:",
      "The prime rate is one of four macro factors that drive the exchange rate target. In multiplayer, floating rates advance halfway at half past each hour, with the hourly turn applying the rest of the step. The full macro target formula is:",
    ],
    [
      "On top of macro drift, two additional forces apply each turn:",
      "The half-hour update exposes half of this step; the hourly turn completes it. On top of macro drift, two additional forces apply each turn:",
    ],
    [
      "This relationship is captured in the per-turn inflation recalculation, which feeds GDP growth data and prime rate into an inflation model that updates every turn.",
      "The inflation model uses GDP growth data and the prime rate, advances halfway at half past each hour, and completes the step on the hourly turn.",
    ],
  ],
};

export const migration: Migration = {
  id: "2026-10-09-subhour-wiki-cadence",
  description:
    "Update legacy wiki timing descriptions for the sub-hour clock, preserving other edits.",
  idempotent: true,
  async execute(db, ctx) {
    const pages = db.collection<WikiPage>("wikiPages");
    const docs = await pages
      .find(
        { slug: { $in: Object.keys(replacements) }, isAutoGenerated: { $ne: true } },
        { projection: { _id: 1, slug: 1, content: 1 } }
      )
      .toArray();
    let documentsUpdated = 0;
    for (const doc of docs) {
      let content = doc.content;
      for (const [oldText, newText] of replacements[doc.slug] ?? []) {
        // The new half-hour sentence contains this legacy fragment as well.
        if (!content.includes(newText)) content = content.replaceAll(oldText, newText);
      }
      if (content === doc.content) continue;
      if (ctx.dryRun) continue;
      const result = await pages.updateOne(
        { _id: doc._id, content: doc.content },
        { $set: { content, updatedAt: new Date() } }
      );
      // Retry on next boot rather than overwriting a concurrent human edit.
      if (!result.matchedCount) throw new Error("Wiki cadence update raced with an edit; retry");
      documentsUpdated += result.modifiedCount;
    }
    return { documentsScanned: docs.length, documentsUpdated };
  },
};
