/** 1991 v1 program levels. Unlisted programs retain their reviewed institutional level. */
export const BASELINE_LEVEL_OVERRIDES_1991: Record<string, 0 | 1 | 2 | 3 | 4> = {
  "us.economy.workerSecurity.primary": 2,
  "us.economy.productivity.primary": 2,
  "us.education.universalSchooling.primary": 2,
  "us.education.teacherCorps.primary": 2,
  "us.health.universalCare.primary": 2,
  "us.society.integration.primary": 3,
  "us.society.womensOpportunity.primary": 3,
  "us.governance.openness.primary": 2,
  "us.governance.participation.primary": 3,
  "us.sec.civilRightsEnforcement": 3,
  "us.sec.votingRightsStandards": 3,
  "us.sec.federalAidSchools": 2,
  "us.sec.medicalResearchInstitutes": 2,
  "uk.economy.householdIncome.primary": 1,
  "uk.economy.stability.primary": 1,
  "uk.economy.competition.primary": 2,
  "uk.economy.workerSecurity.primary": 1,
  "uk.education.choice.primary": 3,
  "uk.society.womensOpportunity.primary": 3,
  "uk.sec.assistedPlaces": 2,
  "ru.economy.stability.primary": 2,
  "ru.economy.productivity.primary": 2,
  "ru.economy.competition.primary": 2,
  "ru.economy.fiscal.primary": 2,
  "ru.governance.participation.primary": 3,
  "ru.governance.openness.primary": 2,
  "ru.governance.localAutonomy.primary": 3,
  "ru.governance.decisiveness.primary": 2,
  "ru.governance.centralAuthority.primary": 1,
};
