import type { Db, ObjectId } from "mongodb";
import { unstable_cache } from "next/cache";
import { getDb } from "@/lib/mongodb";
import { COUNTRY_CONFIGS, getExecutiveOfficeKey, type CountryId } from "@/lib/constants/countries";
import { getCabinetPositions } from "@/lib/constants/cabinetMechanics";
import { LEADERSHIP_ROLES } from "@/lib/congress/leadershipRoles";
import { resolveElectionYear } from "@/lib/utils/formatters";
import { buildCharacterHref, buildNppHref } from "@/lib/utils/profileUrls";
import { getAllSeatSlugs } from "@/lib/wiki/seatData";
import { getAllPartySlugs } from "@/lib/wiki/partyData";
import { getEnabledCountryIds } from "@/lib/countryAccess";
import type { GameIteration } from "@/lib/db/types/gameState";
import { getGameState } from "@/lib/gameState";
import { realDateToTurn, type GameDateAnchor } from "@/lib/utils/gameDate";
import { STARTING_YEAR } from "@/lib/constants/turnTime";
import {
  iterationLabel,
  iterationKey,
  orderIterations,
  weekYearFromTurn,
} from "@/lib/wiki/officeIteration";
import { loadManualOfficeHistory, manualEntryToTenure } from "@/lib/wiki/manualOfficeHistory";
import type {
  CabinetNomination,
  CongressLeader,
  CountryHistoryEvent,
  ElectedOfficial,
  Election,
  HouseLeadershipNomination,
  PoliticalParty,
  SenateLeadershipNomination,
  SpeakerNomination,
  State,
  UnifiedCabinetMember,
  WikiPage,
} from "@/lib/db/types";

export type AutoGeneratedPageKind =
  "election" | "office" | "cabinet" | "leadership" | "seat" | "party";

export interface AutoGeneratedWikiPageSummary {
  slug: string;
  title: string;
  description: string;
  href: string;
  kind: AutoGeneratedPageKind;
  /**
   * Optional recency signal for sorting. Elections set this to `endTime` (or
   * `startTime` when the result hasn't resolved yet). Office/seat/party pages
   * are static and leave this undefined; the consumer should fall back to
   * alphabetical for those.
   */
  sortDate?: Date;
}

export type GeneratedOfficeKind = "executive" | "cabinet" | "leadership";

export interface GeneratedOfficeDefinition {
  slug: string;
  aliases?: string[];
  title: string;
  description: string;
  countryId: CountryId;
  kind: GeneratedOfficeKind;
  officeType?: string;
  positionId?: string;
  leadershipRole?: CongressLeader["role"];
  chamber?: "house" | "senate";
  actionBonus?: number;
  termYears?: number;
}

export interface OfficeTenureEntry {
  name: string;
  party?: string;
  partyLabel?: string;
  /** Iteration this tenure belongs to (auto entries resolve to current when unstamped). */
  iteration?: GameIteration;
  /** Rendered in-game tenure, "Week N, YYYY". */
  startWeekYear?: string;
  /** Rendered end tenure, or null ⇒ "Incumbent". */
  endWeekYear?: string | null;
  // Numeric sort keys (not rendered) used to order entries within an iteration.
  startYear?: number;
  startWeek?: number;
  order?: number;
  startDate?: Date;
  endDate?: Date;
  startTurn?: number;
  endTurn?: number;
  profileHref?: string | null;
  source:
    "country-history" | "elected-official" | "cabinet" | "nomination" | "leadership" | "manual";
  isManual?: boolean;
  /** `manualOfficeHistory` document id, for admin edit/delete of curated rows. */
  manualId?: string;
  /** Raw editable fields for manual rows, used to pre-fill the admin edit form. */
  manualData?: {
    startWeek?: number;
    startYear?: number;
    endWeek?: number;
    endYear?: number;
    /** Real-world dates as "YYYY-MM-DD" for date inputs. */
    startDate?: string;
    endDate?: string;
    isIncumbent?: boolean;
  };
  isCurrent?: boolean;
}

export interface OfficeTenureGroup {
  iteration: GameIteration;
  label: string;
  entries: OfficeTenureEntry[];
}

export interface GeneratedOfficePageData {
  definition: GeneratedOfficeDefinition;
  currentHolder: OfficeTenureEntry | null;
  /** Every known iteration (registry ∪ current), oldest first; empty groups included. */
  tenureGroups: OfficeTenureGroup[];
  hasEditableContent: boolean;
}

// ── Dynamic country list ──────────────────────────────────────────────────
//
// Previously a hardcoded list `["US", "UK", "DE", "JP", "IE"]`. Now resolved
// dynamically from `getEnabledCountryIds()` (DB-driven admin panel toggles).
// The US is always included even when not explicitly enabled (it has no
// `countryGameStates` document by default but should always have wiki pages).
async function getOfficeCountries(): Promise<CountryId[]> {
  const enabled = await getEnabledCountryIds();
  if (!enabled.includes("US" as CountryId)) enabled.push("US" as CountryId);
  return enabled;
}

const LEADERSHIP_SLUGS: Partial<Record<CongressLeader["role"], string>> = {
  speaker_of_the_house: "speaker-of-the-house",
  majority_leader_house: "house-majority-leader",
  minority_leader_house: "house-minority-leader",
  majority_whip_house: "house-majority-whip",
  minority_whip_house: "house-minority-whip",
  president_pro_tempore: "president-pro-tempore",
  majority_leader_senate: "senate-majority-leader",
  minority_leader_senate: "senate-minority-leader",
  majority_whip_senate: "senate-majority-whip",
  minority_whip_senate: "senate-minority-whip",
};

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function titleWithCountry(title: string, countryId: CountryId): string {
  const config = COUNTRY_CONFIGS[countryId];
  const country = config?.executiveRealmPhrase ?? config?.name ?? countryId;
  return `${title} of ${country}`;
}

function officeSlug(title: string, countryId: CountryId): string {
  const fullTitle = titleWithCountry(title, countryId);
  return slugify(fullTitle);
}

export async function getGeneratedOfficeDefinitions(): Promise<GeneratedOfficeDefinition[]> {
  const officeCountries = await getOfficeCountries();
  const definitions: GeneratedOfficeDefinition[] = [];

  for (const countryId of officeCountries) {
    const config = COUNTRY_CONFIGS[countryId];
    const executiveKey = getExecutiveOfficeKey(countryId);
    const executive = config.officeTypes.find((office) => office.key === executiveKey);
    const executiveTitle = executive?.label ?? config.executiveTitle;
    const executiveSlug = officeSlug(executiveTitle, countryId);
    const legacyExecutiveSlug = slugify(`${executiveTitle} of ${config.name}`);

    definitions.push({
      slug: executiveSlug,
      aliases: legacyExecutiveSlug !== executiveSlug ? [legacyExecutiveSlug] : undefined,
      title: titleWithCountry(executiveTitle, countryId),
      description: `${config.executiveTitle} office history for ${config.name}, including current holder and recorded transitions.`,
      countryId,
      kind: "executive",
      officeType: executiveKey,
      actionBonus: executive?.actionBonus,
      termYears: executive?.termYears,
    });

    if (countryId === COUNTRY_CONFIGS.US.id) {
      const vicePresident = config.officeTypes.find((office) => office.key === "vicePresident");
      definitions.push({
        slug: "vice-president-of-the-united-states",
        title: "Vice President of the United States",
        description:
          "Vice presidential office history, running mate succession, and current holder.",
        countryId,
        kind: "executive",
        officeType: "vicePresident",
        actionBonus: vicePresident?.actionBonus,
        termYears: vicePresident?.termYears,
      });
    }

    for (const position of getCabinetPositions(countryId)) {
      const slug =
        countryId === COUNTRY_CONFIGS.US.id
          ? slugify(`united-states-${position.name}`)
          : slugify(`${COUNTRY_CONFIGS[countryId].name}-${position.name}`);
      definitions.push({
        slug,
        title: `${position.name}, ${COUNTRY_CONFIGS[countryId].name}`,
        description:
          position.description ??
          `${position.name} is a cabinet-level office in ${COUNTRY_CONFIGS[countryId].name}.`,
        countryId,
        kind: "cabinet",
        positionId: position.id,
      });
    }
  }

  for (const role of LEADERSHIP_ROLES) {
    const chamberPrefix = role.chamber === "house" ? "House" : "Senate";
    definitions.push({
      slug: LEADERSHIP_SLUGS[role.role] ?? slugify(`${chamberPrefix} ${role.label}`),
      title:
        role.role === "speaker_of_the_house"
          ? "Speaker of the House"
          : `${chamberPrefix} ${role.label}`,
      description: `${chamberPrefix} leadership office history in the United States Congress.`,
      countryId: "US",
      kind: "leadership",
      leadershipRole: role.role,
      chamber: role.chamber,
    });
  }

  return definitions;
}

export async function getGeneratedOfficeDefinition(
  slug: string
): Promise<GeneratedOfficeDefinition | null> {
  return (
    (await getGeneratedOfficeDefinitions()).find(
      (definition) => definition.slug === slug || definition.aliases?.includes(slug)
    ) ?? null
  );
}

export async function getGeneratedOfficeDefinitionForOffice(
  countryId: CountryId | undefined,
  officeType: string | undefined
): Promise<GeneratedOfficeDefinition | null> {
  if (!officeType) return null;
  const resolvedCountryId = countryId ?? COUNTRY_CONFIGS.US.id;
  return (
    (await getGeneratedOfficeDefinitions()).find(
      (definition) =>
        definition.kind === "executive" &&
        definition.countryId === resolvedCountryId &&
        definition.officeType === officeType
    ) ?? null
  );
}

export async function getGeneratedOfficeHrefForOffice(
  countryId: CountryId | undefined,
  officeType: string | undefined
): Promise<string | null> {
  const definition = await getGeneratedOfficeDefinitionForOffice(countryId, officeType);
  return definition ? `/wiki/${definition.slug}` : null;
}

function electionTypeLabel(election: Pick<Election, "electionType" | "senateClass">): string {
  switch (election.electionType) {
    case "president":
      return "President";
    case "governor":
      return "Governor";
    case "senate":
      return `Senate Class ${election.senateClass ?? "?"}`;
    case "house":
      return "House";
    case "stateSenate":
      return "State Senate";
    case "commons":
    case "snap_commons":
      return "Parliamentary";
    case "regionalCouncil":
      return "Regional Council";
    case "primeMinister":
      return "Prime Minister";
    case "shugiin":
    case "snap_shugiin":
      return "Shūgiin";
    case "sangiin":
      return "Sangiin";
    case "bundestag":
    case "snap_bundestag":
      return "Bundestag";
    case "landtag":
      return "Landtag";
    case "ministerPresident":
      return "Minister-President";
    case "chancellor":
      return "Chancellor";
    case "npcDelegate":
      return "NPC Delegate";
    case "peoplesCongress":
      return "People's Congress";
    case "landAssembly":
      return "Landtag";
    case "dail":
      return "Dáil Éireann";
    case "seanad":
      return "Seanad Éireann";
    case "uachtaran":
      return "Uachtarán na hÉireann";
    case "localCouncil":
      return "Local Council";
    default:
      return String(election.electionType);
  }
}

function electionStateName(election: Election, states: Map<string, State>): string {
  if (election.electionType === "president") {
    return COUNTRY_CONFIGS[election.countryId ?? "US"]?.name ?? "United States";
  }
  if (election.electionType === "uachtaran") {
    return COUNTRY_CONFIGS[election.countryId ?? "IE"]?.name ?? "Ireland";
  }
  return states.get(election.state)?.name ?? election.state;
}

function electionSummary(
  election: Election,
  states: Map<string, State>
): AutoGeneratedWikiPageSummary {
  const stateName = electionStateName(election, states);
  const year = resolveElectionYear(election);
  const typeLabel = electionTypeLabel(election);
  const title = `${year} ${stateName} ${typeLabel}`;
  return {
    slug: `election-${election._id.toString()}`,
    title,
    description: `Generated election results page for ${title}.`,
    href: `/wiki/elections/${election._id.toString()}`,
    kind: "election" as const,
    sortDate: election.endTime ?? election.startTime ?? undefined,
  };
}

export async function getGeneratedOfficePageSummaries(): Promise<AutoGeneratedWikiPageSummary[]> {
  return (await getGeneratedOfficeDefinitions()).map((definition) => ({
    slug: definition.slug,
    title: definition.title,
    description: definition.description,
    href: `/wiki/${definition.slug}`,
    kind:
      definition.kind === "executive"
        ? "office"
        : definition.kind === "leadership"
          ? "leadership"
          : "cabinet",
  }));
}

export async function getElectionPageSummaries(): Promise<AutoGeneratedWikiPageSummary[]> {
  const db = await getDb();
  const enabledCountries = await getOfficeCountries();
  const [elections, states] = await Promise.all([
    db
      .collection<Election>("elections")
      .find(
        {
          status: { $in: ["completed", "resolved"] },
          countryId: { $in: enabledCountries },
        },
        {
          projection: {
            electionType: 1,
            electionYear: 1,
            state: 1,
            countryId: 1,
            startTime: 1,
            endTime: 1,
            cycle: 1,
          },
        }
      )
      .sort({ endTime: -1, cycle: -1 })
      .toArray(),
    db
      .collection<State>("states")
      .find({}, { projection: { name: 1 } })
      .toArray(),
  ]);
  const stateMap = new Map(states.map((state) => [state._id, state]));
  return elections.map((election) => electionSummary(election, stateMap));
}

async function getSeatPageSummaries(db: Db): Promise<AutoGeneratedWikiPageSummary[]> {
  const [seatSlugs, states] = await Promise.all([
    getAllSeatSlugs(),
    db.collection<State>("states").find({}).project({ _id: 1, name: 1 }).toArray(),
  ]);
  const stateMap = new Map(states.map((state) => [state._id, state.name]));
  return seatSlugs.map((seat) => {
    const stateName = stateMap.get(seat.stateId) ?? seat.stateId;
    const title =
      seat.type === "governor"
        ? `${stateName} Governor`
        : seat.type === "senate"
          ? `${stateName} Senate Class ${seat.senateClass ?? "?"}`
          : `${stateName} House Delegation`;
    return {
      slug: `seat-${seat.slug}`,
      title,
      description: `Generated seat page for ${title}.`,
      href: `/wiki/seat/${seat.slug}`,
      kind: "seat" as const,
    };
  });
}

async function getPartyPageSummaries(db: Db): Promise<AutoGeneratedWikiPageSummary[]> {
  const enabledCountries = await getOfficeCountries();
  const [partySlugs, parties] = await Promise.all([
    getAllPartySlugs(),
    db
      .collection<PoliticalParty>("politicalParties")
      .find({ countryId: { $in: enabledCountries } })
      .project({ countryId: 1, sequentialId: 1, name: 1, abbreviation: 1 })
      .toArray(),
  ]);
  const partyMap = new Map(
    parties.map((party) => [`${party.countryId ?? "US"}:${party.sequentialId}`, party])
  );
  // Filter party slugs to only those in enabled countries
  const enabledSet = new Set(enabledCountries);
  return partySlugs
    .filter((party) => enabledSet.has(party.countryId))
    .map((party) => {
      const record = partyMap.get(`${party.countryId}:${party.id}`);
      const title = record?.name ?? `Party ${party.id}`;
      return {
        slug: `party-${party.countryId.toLowerCase()}-${party.id}`,
        title,
        description: `Generated political party page for ${title}.`,
        href: `/wiki/party/${party.id}?country=${party.countryId.toLowerCase()}`,
        kind: "party" as const,
      };
    });
}

// Cached like the sibling wiki loaders (getAllWikiPagesForDisplay): the index
// otherwise reloads every completed election + all states per render. Dates
// round-trip as ISO strings through the cache; the only consumer re-parses via
// new Date(sortDate).
export const getAutoGeneratedWikiPagesForDisplay = unstable_cache(
  loadAutoGeneratedWikiPagesForDisplay,
  ["wiki-auto-generated-pages"],
  { revalidate: 120 }
);

async function loadAutoGeneratedWikiPagesForDisplay(): Promise<AutoGeneratedWikiPageSummary[]> {
  const db = await getDb();
  const [elections, seats, parties, officeSummaries] = await Promise.all([
    getElectionPageSummaries(),
    getSeatPageSummaries(db),
    getPartyPageSummaries(db),
    getGeneratedOfficePageSummaries(),
  ]);

  return [
    {
      slug: "elections",
      title: "Election History",
      description: "Generated index of completed election results.",
      href: "/wiki/elections",
      kind: "election" as const,
    },
    ...officeSummaries,
    ...elections,
    ...seats,
    ...parties,
  ].sort((a, b) => a.title.localeCompare(b.title));
}

function officialFilter(countryId: CountryId, officeType: string): Record<string, unknown> {
  if (countryId === COUNTRY_CONFIGS.US.id) {
    return {
      officeType,
      $or: [{ countryId: "US" }, { countryId: { $exists: false } }],
    };
  }
  return { countryId, officeType };
}

function currentOfficialToTenure(official: ElectedOfficial | null): OfficeTenureEntry | null {
  if (!official) return null;
  const entityId = (official.characterId ?? official.nppId)?.toString();
  return {
    name: official.characterName ?? "Vacant",
    party: official.party,
    startDate: official.electedAt ?? official.createdAt,
    profileHref: entityId
      ? official.isNPP
        ? buildNppHref({ _id: entityId })
        : buildCharacterHref({ _id: entityId })
      : null,
    source: "elected-official",
    isCurrent: true,
  };
}

function cabinetMemberToTenure(member: UnifiedCabinetMember | null): OfficeTenureEntry | null {
  if (!member) return null;
  return {
    name: member.characterName ?? "Vacant",
    party: member.party,
    startDate: member.confirmedAt ?? member.appointedAt ?? member.createdAt,
    profileHref: member.characterId ? buildCharacterHref({ _id: member.characterId }) : null,
    source: "cabinet",
    isCurrent: true,
  };
}

function leadershipToTenure(leader: CongressLeader | null): OfficeTenureEntry | null {
  if (!leader?.characterId) return null;
  return {
    name: leader.characterName,
    party: leader.party,
    startDate: leader.electedAt ?? leader.createdAt,
    profileHref: buildCharacterHref({ _id: leader.characterId }),
    source: "leadership",
    isCurrent: true,
  };
}

async function loadPartyLabels(db: Db, countryId: CountryId): Promise<Map<string, string>> {
  const parties = await db
    .collection<PoliticalParty>("politicalParties")
    .find({ countryId })
    .project({ sequentialId: 1, name: 1, abbreviation: 1 })
    .toArray();
  return new Map(
    parties.map((party) => [
      String(party.sequentialId),
      party.abbreviation ? `${party.name} (${party.abbreviation})` : party.name,
    ])
  );
}

function applyPartyLabels(
  entries: OfficeTenureEntry[],
  partyLabels: Map<string, string>
): OfficeTenureEntry[] {
  return entries.map((entry) => ({
    ...entry,
    partyLabel: entry.party ? (partyLabels.get(entry.party) ?? entry.party) : undefined,
  }));
}

interface IterationContext {
  current: GameIteration;
  startingYear: number;
  anchor: GameDateAnchor;
}

/** Resolve an auto record's iteration + its preset starting year, defaulting to current. */
function resolveEntryIteration(
  record: { iteration?: GameIteration; iterationStartingYear?: number },
  ctx: IterationContext
): { iteration: GameIteration; startingYear: number } {
  return {
    iteration: record.iteration ?? ctx.current,
    startingYear: record.iterationStartingYear ?? ctx.startingYear,
  };
}

/**
 * Stamp an entry with its iteration + Week/Year + numeric sort keys. `endTurn`
 * is only honored when the end falls in the same iteration (turns reset each
 * iteration, so a cross-boundary end would render backwards); otherwise the
 * entry is treated as open ("Incumbent").
 */
function finalizeEntry(
  entry: OfficeTenureEntry,
  turn: number,
  iteration: GameIteration,
  startingYear: number,
  endTurn: number | null
): void {
  entry.iteration = iteration;
  entry.startWeekYear = weekYearFromTurn(turn, startingYear);
  entry.startYear = startingYear + Math.floor((turn - 1) / 48);
  entry.startWeek = ((turn - 1) % 48) + 1;
  entry.endWeekYear = endTurn != null ? weekYearFromTurn(endTurn, startingYear) : null;
}

/**
 * Confirmation turn for a cabinet/leadership record: the stamped `confirmedTurn`
 * (set at freeze time, correct across iterations) or, for not-yet-frozen
 * current-run records, derived from the timestamp via the current anchor.
 */
function confirmationTurn(
  record: { confirmedTurn?: number },
  timestamp: Date | undefined,
  ctx: IterationContext
): number {
  if (typeof record.confirmedTurn === "number") return record.confirmedTurn;
  return timestamp ? realDateToTurn(timestamp, ctx.anchor) : ctx.anchor.currentTurn;
}

/**
 * Finalize a live-incumbent entry (no recorded turn): place it in the current
 * iteration with a Week/Year derived from its start date and an open end.
 */
function finalizeCurrentEntry(entry: OfficeTenureEntry, ctx: IterationContext): void {
  const turn = entry.startDate
    ? realDateToTurn(entry.startDate, ctx.anchor)
    : ctx.anchor.currentTurn;
  finalizeEntry(entry, turn, ctx.current, ctx.startingYear, null);
}

/**
 * Group tenure entries by iteration. Every registry iteration (∪ the current
 * one) gets a group — even if empty — ordered Alpha < Beta < Iteration then by
 * number ascending (oldest first). Entries within a group are ordered
 * oldest→newest by (year, week, order).
 */
export function buildTenureGroups(
  entries: OfficeTenureEntry[],
  registry: GameIteration[],
  currentIteration: GameIteration
): OfficeTenureGroup[] {
  const referenced = entries
    .map((e) => e.iteration)
    .filter((it): it is GameIteration => Boolean(it));
  const ordered = orderIterations([...registry, currentIteration], referenced);
  const byKey = new Map<string, OfficeTenureEntry[]>();
  for (const e of entries) {
    if (!e.iteration) continue;
    const key = iterationKey(e.iteration);
    const list = byKey.get(key) ?? [];
    list.push(e);
    byKey.set(key, list);
  }
  return ordered.map((it) => {
    const list = (byKey.get(iterationKey(it)) ?? [])
      .slice()
      .sort(
        (a, b) =>
          (a.startYear ?? 0) - (b.startYear ?? 0) ||
          (a.startWeek ?? 0) - (b.startWeek ?? 0) ||
          (a.order ?? 0) - (b.order ?? 0)
      );
    return { iteration: it, label: iterationLabel(it), entries: list };
  });
}

async function getExecutiveHistory(
  db: Db,
  definition: GeneratedOfficeDefinition,
  ctx: IterationContext
): Promise<OfficeTenureEntry[]> {
  if (!definition.officeType) return [];
  const currentOfficial = await db
    .collection<ElectedOfficial>("electedOfficials")
    .findOne(officialFilter(definition.countryId, definition.officeType));
  const current = currentOfficialToTenure(currentOfficial);
  if (current) finalizeCurrentEntry(current, ctx);

  const events = await db
    .collection<CountryHistoryEvent>("countryHistory")
    .find({
      countryId: definition.countryId,
      eventType: "leader_change",
      officeType: definition.officeType,
    })
    .sort({ timestamp: 1 })
    .toArray();

  const history = events.map((event, index): OfficeTenureEntry => {
    const next = events[index + 1];
    const characterId = event.characterId?.toString();
    const nppId = typeof event.details?.nppId === "string" ? event.details.nppId : null;
    const { iteration, startingYear } = resolveEntryIteration(event, ctx);
    const sameIterationNext =
      next && iterationKey(resolveEntryIteration(next, ctx).iteration) === iterationKey(iteration);
    const entry: OfficeTenureEntry = {
      name: event.characterName ?? "Unknown",
      party: event.party,
      startDate: event.timestamp,
      endDate: next?.timestamp,
      startTurn: event.turn,
      endTurn: next?.turn,
      profileHref: characterId
        ? buildCharacterHref({ _id: characterId })
        : nppId
          ? buildNppHref({ _id: nppId })
          : null,
      source: "country-history",
      isCurrent: index === events.length - 1,
    };
    finalizeEntry(
      entry,
      event.turn,
      iteration,
      startingYear,
      sameIterationNext ? (next!.turn ?? null) : null
    );
    return entry;
  });

  if (history.length === 0 && current) return [current];
  if (current && history.length > 0) {
    const latest = history[history.length - 1];
    if (latest.name !== current.name) {
      history.push(current);
    }
  }
  return history;
}

async function getCabinetHistory(
  db: Db,
  definition: GeneratedOfficeDefinition,
  ctx: IterationContext
): Promise<OfficeTenureEntry[]> {
  if (!definition.positionId) return [];
  const [currentMember, nominations] = await Promise.all([
    db.collection<UnifiedCabinetMember>("cabinetMembers").findOne({
      countryId: definition.countryId,
      positionId: definition.positionId,
    }),
    db
      .collection<CabinetNomination>("cabinetNominations")
      .find({
        countryId: definition.countryId,
        positionId: definition.positionId,
        status: "confirmed",
      })
      .sort({ confirmedAt: 1, updatedAt: 1 })
      .toArray(),
  ]);

  const history = nominations.map((nomination, index): OfficeTenureEntry => {
    const next = nominations[index + 1];
    const start = nomination.confirmedAt ?? nomination.updatedAt ?? nomination.createdAt;
    const end = next ? (next.confirmedAt ?? next.updatedAt ?? next.createdAt) : undefined;
    const entry: OfficeTenureEntry = {
      name: nomination.nomineeCharacterName,
      party: nomination.nomineeParty,
      startDate: start,
      endDate: end,
      profileHref: nomination.nomineeCharacterId
        ? buildCharacterHref({ _id: nomination.nomineeCharacterId })
        : null,
      source: "nomination",
      isCurrent: index === nominations.length - 1,
    };
    const { iteration, startingYear } = resolveEntryIteration(nomination, ctx);
    const turn = confirmationTurn(nomination, start, ctx);
    const nextResolved = next ? resolveEntryIteration(next, ctx) : null;
    const sameIterationNext =
      nextResolved && iterationKey(nextResolved.iteration) === iterationKey(iteration);
    const endTurn = sameIterationNext
      ? confirmationTurn(next!, next!.confirmedAt ?? next!.updatedAt ?? next!.createdAt, ctx)
      : null;
    finalizeEntry(entry, turn, iteration, startingYear, endTurn);
    return entry;
  });

  const current = cabinetMemberToTenure(currentMember);
  if (current) finalizeCurrentEntry(current, ctx);
  if (history.length === 0 && current) return [current];
  if (current && history.length > 0) {
    const latest = history[history.length - 1];
    if (latest.name !== current.name) {
      history.push(current);
    }
  }
  return history;
}

type NominationWithSharedFields = {
  nomineeId: ObjectId;
  nomineeName: string;
  nomineeParty?: string;
  status: string;
  createdAt: Date;
  updatedAt: Date;
  iteration?: GameIteration;
  iterationStartingYear?: number;
  confirmedTurn?: number;
};

async function getLeadershipNominations(
  db: Db,
  role: CongressLeader["role"]
): Promise<NominationWithSharedFields[]> {
  if (role === "speaker_of_the_house") {
    return db
      .collection<SpeakerNomination>("speakerNominations")
      .find({ status: "confirmed" })
      .sort({ updatedAt: 1 })
      .toArray();
  }

  const houseRole =
    role === "majority_leader_house"
      ? "majority_leader"
      : role === "minority_leader_house"
        ? "minority_leader"
        : null;
  if (houseRole) {
    return db
      .collection<HouseLeadershipNomination>("houseLeadershipNominations")
      .find({ role: houseRole, status: "confirmed" })
      .sort({ updatedAt: 1 })
      .toArray();
  }

  const senateRole =
    role === "president_pro_tempore"
      ? "pro_tempore"
      : role === "majority_leader_senate"
        ? "majority_leader"
        : role === "minority_leader_senate"
          ? "minority_leader"
          : null;
  if (senateRole) {
    return db
      .collection<SenateLeadershipNomination>("senateLeadershipNominations")
      .find({ role: senateRole, status: "confirmed" })
      .sort({ updatedAt: 1 })
      .toArray();
  }

  return [];
}

async function getLeadershipHistory(
  db: Db,
  definition: GeneratedOfficeDefinition,
  ctx: IterationContext
): Promise<OfficeTenureEntry[]> {
  if (!definition.leadershipRole) return [];
  const [currentLeader, nominations] = await Promise.all([
    db.collection<CongressLeader>("congressLeaders").findOne({ role: definition.leadershipRole }),
    getLeadershipNominations(db, definition.leadershipRole),
  ]);

  const history = nominations.map((nomination, index): OfficeTenureEntry => {
    const next = nominations[index + 1];
    const start = nomination.updatedAt ?? nomination.createdAt;
    const entry: OfficeTenureEntry = {
      name: nomination.nomineeName,
      party: nomination.nomineeParty,
      startDate: start,
      endDate: next ? (next.updatedAt ?? next.createdAt) : undefined,
      profileHref: nomination.nomineeId ? buildCharacterHref({ _id: nomination.nomineeId }) : null,
      source: "leadership",
      isCurrent: index === nominations.length - 1,
    };
    const { iteration, startingYear } = resolveEntryIteration(nomination, ctx);
    const turn = confirmationTurn(nomination, start, ctx);
    const nextResolved = next ? resolveEntryIteration(next, ctx) : null;
    const sameIterationNext =
      nextResolved && iterationKey(nextResolved.iteration) === iterationKey(iteration);
    const endTurn = sameIterationNext
      ? confirmationTurn(next!, next!.updatedAt ?? next!.createdAt, ctx)
      : null;
    finalizeEntry(entry, turn, iteration, startingYear, endTurn);
    return entry;
  });

  const current = leadershipToTenure(currentLeader);
  if (current) finalizeCurrentEntry(current, ctx);
  if (history.length === 0 && current) return [current];
  if (current && history.length > 0) {
    const latest = history[history.length - 1];
    if (latest.name !== current.name) {
      history.push(current);
    }
  }
  return history;
}

export function generatedOfficeDefaultContent(definition: GeneratedOfficeDefinition): string {
  const country = COUNTRY_CONFIGS[definition.countryId];
  const termText =
    definition.termYears != null
      ? ` The standard term length is ${definition.termYears} game year${definition.termYears === 1 ? "" : "s"}.`
      : "";
  const actionText =
    definition.actionBonus != null
      ? ` The office grants a +${definition.actionBonus} action bonus while held.`
      : "";

  if (definition.kind === "cabinet") {
    return `${definition.description}\n\nIn *A House Divided*, this cabinet office is part of ${country.name}'s executive administration. The office page is generated from live appointment records, so the holder table updates as confirmations and appointments happen. Editors can add narrative context by creating a wiki page with this slug; the generated holder history remains attached below the article text.`;
  }

  if (definition.kind === "leadership") {
    return `${definition.description}\n\nThis page tracks the office as a living institutional record. The holder table is generated from congressional leadership records and confirmed leadership nominations where available, preserving a running list of speakers, floor leaders, whips, and Senate officers as the simulation develops.`;
  }

  return `${definition.title} is the senior executive office of ${country.name}.${termText}${actionText}\n\nThis generated article records the office's incumbent and known tenure history. Leader transitions are pulled from country history events where available, with current office records used as a fallback until a full transition history accumulates.`;
}

export async function getGeneratedOfficePageData(
  slug: string
): Promise<GeneratedOfficePageData | null> {
  const definition = await getGeneratedOfficeDefinition(slug);
  if (!definition) return null;

  // Step 5: If the office's country is not enabled, return null to prevent
  // rendering office pages for disabled countries.
  const enabledCountries = await getOfficeCountries();
  if (!enabledCountries.includes(definition.countryId)) return null;

  const db = await getDb();
  const gameState = await getGameState(db);
  const currentIteration: GameIteration = gameState?.iteration ?? { type: "Beta", number: 2 };
  const startingYear = gameState?.startingYear ?? STARTING_YEAR;
  const ctx: IterationContext = {
    current: currentIteration,
    startingYear,
    anchor: {
      currentTurn: gameState?.currentTurn ?? 1,
      lastTurnProcessed: gameState?.lastTurnProcessed ?? new Date(),
      startingYear,
    },
  };
  const registry = gameState?.iterationHistory ?? [currentIteration];

  const [editablePage, partyLabels, history, manual] = await Promise.all([
    db
      .collection<WikiPage>("wikiPages")
      .findOne({ slug, status: "published", private: { $ne: true } }, { projection: { _id: 1 } }),
    loadPartyLabels(db, definition.countryId),
    definition.kind === "cabinet"
      ? getCabinetHistory(db, definition, ctx)
      : definition.kind === "leadership"
        ? getLeadershipHistory(db, definition, ctx)
        : getExecutiveHistory(db, definition, ctx),
    loadManualOfficeHistory(db, definition),
  ]);

  const labeledHistory = applyPartyLabels(history, partyLabels);
  const currentHolder = labeledHistory.find((entry) => entry.isCurrent) ?? null;
  const labeledManual = applyPartyLabels(manual.map(manualEntryToTenure), partyLabels);
  const allEntries = [...labeledHistory, ...labeledManual];

  return {
    definition,
    currentHolder,
    tenureGroups: buildTenureGroups(allEntries, registry, currentIteration),
    hasEditableContent: Boolean(editablePage),
  };
}
