import { describe, it, expect } from "vitest";
import { buildTenureGroups, type OfficeTenureEntry } from "./autoGeneratedPages";

const A1 = { type: "Alpha", number: 1 } as const;
const B1 = { type: "Beta", number: 1 } as const;
const B2 = { type: "Beta", number: 2 } as const;

function entry(partial: Partial<OfficeTenureEntry>): OfficeTenureEntry {
  return { name: "x", source: "manual", ...partial } as OfficeTenureEntry;
}

describe("buildTenureGroups", () => {
  it("creates a group per registry iteration (even empty), oldest first", () => {
    const groups = buildTenureGroups([], [A1, B1, B2], B2);
    expect(groups.map((g) => g.label)).toEqual(["Alpha 1", "Beta 1", "Beta 2"]);
    expect(groups.every((g) => g.entries.length === 0)).toBe(true);
  });

  it("places entries into their iteration group, oldest→newest within", () => {
    const e1 = entry({ name: "A", iteration: B2, startYear: 2019, startWeek: 2 });
    const e2 = entry({ name: "B", iteration: B2, startYear: 2019, startWeek: 10 });
    const groups = buildTenureGroups([e2, e1], [B2], B2);
    expect(groups[0].entries.map((e) => e.name)).toEqual(["A", "B"]);
  });

  it("includes the current iteration even if absent from the registry", () => {
    const groups = buildTenureGroups([], [A1], B2);
    expect(groups.map((g) => g.label)).toContain("Beta 2");
  });

  it("orders mixed iterations Alpha < Beta and by number", () => {
    const eA = entry({ name: "old", iteration: A1, startYear: 2010, startWeek: 1 });
    const eB = entry({ name: "new", iteration: B2, startYear: 2019, startWeek: 1 });
    const groups = buildTenureGroups([eB, eA], [A1, B1, B2], B2);
    expect(groups.map((g) => g.label)).toEqual(["Alpha 1", "Beta 1", "Beta 2"]);
    expect(groups[0].entries.map((e) => e.name)).toEqual(["old"]);
    expect(groups[2].entries.map((e) => e.name)).toEqual(["new"]);
  });
});
