/**
 * Backfills gameIteration and gameStartDate onto user-created wiki pages that
 * predate the fields. Seeded pages (whose first editHistory entry carries a
 * "Reseed" note) and auto-generated pages are excluded.
 */
import type { Db } from "mongodb";
import type { WikiPage } from "@/lib/db/types";
import { getGameStamp } from "@/lib/wiki/gameConfig";

export interface BackfillGameStampResult {
  stamped: number;
  skippedNoEnv: boolean;
}

export async function backfillGameStamp(db: Db): Promise<BackfillGameStampResult> {
  const stamp = getGameStamp();

  if (!stamp.gameIteration && !stamp.gameStartDate) {
    return { stamped: 0, skippedNoEnv: true };
  }

  const result = await db.collection<WikiPage>("wikiPages").updateMany(
    {
      gameIteration: { $exists: false },
      isAutoGenerated: { $ne: true },
      // First editHistory entry with a "Reseed" note means seeder-created — skip those.
      "editHistory.0.note": { $not: { $regex: /^Reseed/ } },
    },
    { $set: stamp }
  );

  return { stamped: result.modifiedCount, skippedNoEnv: false };
}
