import { cache } from "react";
import { unstable_cache } from "next/cache";
import { getDb } from "@/lib/mongodb";
import type { WikiPage, WikiPageDifficulty, WikiPageContentType } from "@/lib/db/types";
import { isCustomWikiPage, resolveWikiCategory } from "@/lib/wiki/pageClassification";
import { getAllCountryAccess } from "@/lib/countryAccess";

export interface WikiPageData {
  slug: string;
  title: string;
  description: string;
  href?: string;
  featured?: boolean;
  category?: string;
  tags?: string[];
  difficulty?: WikiPageDifficulty;
  contentType?: WikiPageContentType;
  estimatedReadTime?: number;
  updatedAt?: Date;
  gameIteration?: string;
  gameStartDate?: string;
  isCustomPage?: boolean;
  isAutoGenerated?: boolean;
}

function projectWikiPage(dbPage: WikiPage): WikiPageData {
  return {
    slug: dbPage.slug,
    title: dbPage.title,
    description: dbPage.description,
    featured: dbPage.featured,
    category: resolveWikiCategory(dbPage.tags, dbPage.category),
    tags: dbPage.tags,
    difficulty: dbPage.difficulty,
    contentType: dbPage.contentType,
    estimatedReadTime: dbPage.estimatedReadTime,
    updatedAt: dbPage.updatedAt,
    gameIteration: dbPage.gameIteration,
    gameStartDate: dbPage.gameStartDate,
    isCustomPage: isCustomWikiPage(dbPage),
    isAutoGenerated: dbPage.isAutoGenerated ?? false,
  };
}

/**
 * Get wiki page metadata from DB.
 *
 * `cache()` dedupes within a single request, so generateMetadata + the page
 * render share one Mongo round-trip.
 */
export const getWikiPageData = cache(async (slug: string): Promise<WikiPageData | null> => {
  const db = await getDb();
  const dbPage = await db.collection<WikiPage>("wikiPages").findOne({
    slug,
    status: "published",
    private: { $ne: true },
  });
  if (!dbPage) return null;
  return projectWikiPage(dbPage);
});

/**
 * Batch lookup for related-pages-style footers. Replaces N sequential findOne
 * calls with a single $in query.
 */
export async function getWikiPagesBySlugs(
  slugs: readonly string[]
): Promise<Map<string, WikiPageData>> {
  if (slugs.length === 0) return new Map();
  const db = await getDb();
  const dbPages = await db
    .collection<WikiPage>("wikiPages")
    .find({
      slug: { $in: [...slugs] },
      status: "published",
      private: { $ne: true },
    })
    .toArray();
  const out = new Map<string, WikiPageData>();
  for (const p of dbPages) out.set(p.slug, projectWikiPage(p));
  return out;
}

/**
 * Get all wiki page slugs from DB.
 */
async function loadAllWikiSlugs(): Promise<string[]> {
  const db = await getDb();
  const dbPages = await db
    .collection<WikiPage>("wikiPages")
    .find({ status: "published", private: { $ne: true } }, { projection: { slug: 1 } })
    .toArray();
  return dbPages.map((p) => p.slug).sort();
}

/** Cached slug list — revalidates every 5 minutes. */
export const getAllWikiSlugsAsync = unstable_cache(loadAllWikiSlugs, ["wiki-all-slugs"], {
  revalidate: 300,
});

/**
 * Get all published wiki pages for display (uncached; use export below).
 */
async function loadAllWikiPagesForDisplay(): Promise<WikiPageData[]> {
  const db = await getDb();
  const dbPages = await db
    .collection<WikiPage>("wikiPages")
    .find(
      { status: "published", private: { $ne: true } },
      {
        projection: {
          slug: 1,
          title: 1,
          description: 1,
          featured: 1,
          tags: 1,
          category: 1,
          difficulty: 1,
          contentType: 1,
          estimatedReadTime: 1,
          updatedAt: 1,
          isAutoGenerated: 1,
          gameIteration: 1,
          gameStartDate: 1,
          submittedBy: 1,
          reviewedBy: 1,
          editHistory: 1,
          countryId: 1,
        },
      }
    )
    .toArray();

  const accessMap = await getAllCountryAccess();
  const visiblePages = dbPages.filter(
    (p) => !p.countryId || (accessMap[p.countryId]?.enabledForPlayers ?? false)
  );

  return visiblePages
    .map((p) => ({
      slug: p.slug,
      title: p.title,
      description: p.description,
      href: `/wiki/${p.slug}`,
      featured: p.featured,
      category: resolveWikiCategory(p.tags, p.category),
      tags: p.tags,
      difficulty: p.difficulty,
      contentType: p.contentType,
      estimatedReadTime: p.estimatedReadTime,
      updatedAt: p.updatedAt,
      gameIteration: p.gameIteration,
      gameStartDate: p.gameStartDate,
      isCustomPage: isCustomWikiPage(p),
      isAutoGenerated: p.isAutoGenerated ?? false,
    }))
    .sort((a, b) => a.title.localeCompare(b.title));
}

/**
 * Published wiki index for overview / category listings — cached to reduce Mongo load and TTFB.
 */
export const getAllWikiPagesForDisplay = unstable_cache(
  loadAllWikiPagesForDisplay,
  ["wiki-all-published-pages"],
  { revalidate: 120 }
);

export interface WikiPageSpotlight {
  slug: string;
  title: string;
  category?: string;
  createdAt: Date | string;
  viewCount?: number;
}

async function loadRecentWikiPages(): Promise<WikiPageSpotlight[]> {
  const db = await getDb();
  const pages = await db
    .collection<WikiPage>("wikiPages")
    .find(
      { status: "published", isAutoGenerated: { $ne: true }, private: { $ne: true } },
      { projection: { slug: 1, title: 1, tags: 1, category: 1, createdAt: 1, countryId: 1 } }
    )
    .sort({ createdAt: -1 })
    .limit(5)
    .toArray();
  const accessMap = await getAllCountryAccess();
  return pages
    .filter((p) => !p.countryId || (accessMap[p.countryId]?.enabledForPlayers ?? false))
    .map((p) => ({
      slug: p.slug,
      title: p.title,
      category: resolveWikiCategory(p.tags, p.category),
      createdAt: p.createdAt,
    }));
}

export const getRecentWikiPages = unstable_cache(loadRecentWikiPages, ["wiki-recent-pages"], {
  revalidate: 120,
});

async function loadMostViewedWikiPages(): Promise<WikiPageSpotlight[]> {
  const db = await getDb();
  const pages = await db
    .collection<WikiPage>("wikiPages")
    .find(
      { status: "published", viewCount: { $gt: 0 }, private: { $ne: true } },
      {
        projection: {
          slug: 1,
          title: 1,
          tags: 1,
          category: 1,
          viewCount: 1,
          createdAt: 1,
          countryId: 1,
        },
      }
    )
    .sort({ viewCount: -1 })
    .limit(5)
    .toArray();
  const accessMap = await getAllCountryAccess();
  return pages
    .filter((p) => !p.countryId || (accessMap[p.countryId]?.enabledForPlayers ?? false))
    .map((p) => ({
      slug: p.slug,
      title: p.title,
      category: resolveWikiCategory(p.tags, p.category),
      createdAt: p.createdAt,
      viewCount: p.viewCount,
    }));
}

export const getMostViewedWikiPages = unstable_cache(
  loadMostViewedWikiPages,
  ["wiki-most-viewed-pages"],
  { revalidate: 120 }
);
