import { describe, it, expect } from "vitest";
import { deriveOfficeKey, manualEntryToTenure } from "./manualOfficeHistory";
import type { GeneratedOfficeDefinition } from "./autoGeneratedPages";
import type { ManualOfficeHistoryEntry } from "@/lib/db/types/manualOfficeHistory";

function def(partial: Partial<GeneratedOfficeDefinition>): GeneratedOfficeDefinition {
  return {
    slug: "x",
    title: "x",
    description: "x",
    countryId: "US",
    kind: "executive",
    ...partial,
  } as GeneratedOfficeDefinition;
}

describe("deriveOfficeKey", () => {
  it("executive", () => {
    expect(deriveOfficeKey(def({ kind: "executive", officeType: "president" }))).toBe(
      "US:executive:president"
    );
  });
  it("cabinet", () => {
    expect(deriveOfficeKey(def({ kind: "cabinet", positionId: "sos" }))).toBe("US:cabinet:sos");
  });
  it("leadership", () => {
    expect(
      deriveOfficeKey(def({ kind: "leadership", leadershipRole: "speaker_of_the_house" }))
    ).toBe("US:leadership:speaker_of_the_house");
  });
});

describe("manualEntryToTenure", () => {
  it("maps fields and marks incumbent", () => {
    const e = manualEntryToTenure({
      iteration: { type: "Beta", number: 1 },
      name: "X",
      party: "1",
      startWeek: 4,
      startYear: 2019,
      isIncumbent: true,
    } as ManualOfficeHistoryEntry);
    expect(e.startWeekYear).toBe("Week 4, 2019");
    expect(e.endWeekYear).toBeNull();
    expect(e.isManual).toBe(true);
    expect(e.source).toBe("manual");
    expect(e.startYear).toBe(2019);
    expect(e.startWeek).toBe(4);
  });

  it("maps explicit end week/year when not incumbent", () => {
    const e = manualEntryToTenure({
      iteration: { type: "Alpha", number: 1 },
      name: "Y",
      startWeek: 1,
      startYear: 2018,
      endWeek: 20,
      endYear: 2019,
    } as ManualOfficeHistoryEntry);
    expect(e.endWeekYear).toBe("Week 20, 2019");
  });

  it("passes through real-world dates and leaves week/year blank when absent", () => {
    const e = manualEntryToTenure({
      iteration: { type: "Alpha", number: 1 },
      name: "Z",
      startDate: new Date("2026-06-16T12:00:00.000Z"),
      endDate: new Date("2026-06-19T12:00:00.000Z"),
    } as ManualOfficeHistoryEntry);
    expect(e.startWeekYear).toBeUndefined();
    expect(e.startDate).toEqual(new Date("2026-06-16T12:00:00.000Z"));
    expect(e.endDate).toEqual(new Date("2026-06-19T12:00:00.000Z"));
    // sort key falls back to the real date's year when no game year is set
    expect(e.startYear).toBe(2026);
  });

  it("drops the real-world end date when incumbent", () => {
    const e = manualEntryToTenure({
      iteration: { type: "Beta", number: 1 },
      name: "Inc",
      startDate: new Date("2026-06-16T12:00:00.000Z"),
      endDate: new Date("2026-06-19T12:00:00.000Z"),
      isIncumbent: true,
    } as ManualOfficeHistoryEntry);
    expect(e.endDate).toBeUndefined();
  });
});
