import type { Db } from "mongodb";
import type { GeneratedOfficeDefinition, OfficeTenureEntry } from "./autoGeneratedPages";
import type { ManualOfficeHistoryEntry } from "@/lib/db/types/manualOfficeHistory";
import { weekYearFromFields } from "./officeIteration";

/** Render a stored Date as a "YYYY-MM-DD" string (UTC) for date inputs. */
function toISODate(date?: Date): string | undefined {
  if (!date) return undefined;
  return new Date(date).toISOString().slice(0, 10);
}

/**
 * Stable office identity shared by the generated office definition and the
 * curated `manualOfficeHistory` documents:
 * `${countryId}:${kind}:${officeType|positionId|leadershipRole}`.
 */
export function deriveOfficeKey(def: GeneratedOfficeDefinition): string {
  const id = def.officeType ?? def.positionId ?? def.leadershipRole ?? "unknown";
  return `${def.countryId}:${def.kind}:${id}`;
}

/** Map a curated manual entry into the shared tenure-entry shape. */
export function manualEntryToTenure(entry: ManualOfficeHistoryEntry): OfficeTenureEntry {
  const hasWeekYear = entry.startWeek != null && entry.startYear != null;
  const startDate = entry.startDate ? new Date(entry.startDate) : undefined;
  // Sort keys prefer the in-game year/week; fall back to the real start date so
  // date-only entries still order sensibly within their iteration.
  const sortYear = entry.startYear ?? startDate?.getUTCFullYear();
  const sortWeek = entry.startWeek ?? (startDate ? startDate.getUTCMonth() * 4 + 1 : undefined);
  return {
    name: entry.name,
    party: entry.party,
    iteration: entry.iteration,
    startWeekYear: hasWeekYear ? weekYearFromFields(entry.startWeek!, entry.startYear!) : undefined,
    endWeekYear:
      entry.isIncumbent || entry.endWeek == null || entry.endYear == null
        ? null
        : weekYearFromFields(entry.endWeek, entry.endYear),
    startDate,
    endDate: entry.isIncumbent || !entry.endDate ? undefined : new Date(entry.endDate),
    startYear: sortYear,
    startWeek: sortWeek,
    order: entry.order,
    profileHref: entry.profileHref ?? null,
    source: "manual",
    isManual: true,
    manualId: entry._id?.toString(),
    manualData: {
      startWeek: entry.startWeek,
      startYear: entry.startYear,
      endWeek: entry.endWeek,
      endYear: entry.endYear,
      startDate: toISODate(entry.startDate),
      endDate: toISODate(entry.endDate),
      isIncumbent: entry.isIncumbent,
    },
    isCurrent: false,
  };
}

/** Load all curated entries for an office, ready to merge into the grouped view. */
export async function loadManualOfficeHistory(
  db: Db,
  def: GeneratedOfficeDefinition
): Promise<ManualOfficeHistoryEntry[]> {
  return db
    .collection<ManualOfficeHistoryEntry>("manualOfficeHistory")
    .find({ officeKey: deriveOfficeKey(def) })
    .toArray();
}
