import { createHash } from "node:crypto";
import type { AnyBulkWriteOperation, Db } from "mongodb";
import type { GameIteration } from "@/lib/db/types/gameState";
import { iterationKey } from "@/lib/wiki/officeIteration";
import type { OfficeTenureEntry } from "@/lib/wiki/autoGeneratedPages";

/**
 * Office tenures from finished worlds, kept for the wiki's generated office
 * pages. The live office tables (`countryHistory`, `cabinetNominations`, the
 * leadership nominations, `cabinetMembers`, `congressLeaders`,
 * `electedOfficials`) are world state and are dropped on reset, so each page's
 * tenure list is computed one last time before the sweep and written here,
 * already labelled, dated and closed. Preserved across resets.
 */
export const OFFICE_HISTORY_ARCHIVE_COLLECTION = "officeHistoryArchive";

export interface ArchivedOfficeTenure {
  /** Hash of `archivedTenureKey`, so a retried reset rewrites the same rows. */
  _id: string;
  slug: string;
  iteration: GameIteration;
  entry: OfficeTenureEntry;
  archivedAt: Date;
}

/**
 * Identity of one tenure. Two worlds can share an iteration label (a reset
 * keeps the label unless the operator sets a new one), so the start and end
 * are part of the key: a second world's tenure never overwrites the first's.
 */
export function archivedTenureKey(slug: string, entry: OfficeTenureEntry): string {
  const startDate = entry.startDate ? new Date(entry.startDate).toISOString() : "";
  return [
    slug,
    entry.iteration ? iterationKey(entry.iteration) : "",
    entry.source,
    entry.name,
    entry.startWeekYear ?? "",
    startDate,
    entry.endWeekYear ?? "",
  ].join("|");
}

function archiveId(slug: string, entry: OfficeTenureEntry): string {
  return createHash("sha256").update(archivedTenureKey(slug, entry)).digest("hex");
}

/** Upsert a finished world's tenures for one office page. Returns rows written. */
export async function writeArchivedOfficeHistory(
  db: Db,
  slug: string,
  entries: OfficeTenureEntry[],
  archivedAt: Date
): Promise<number> {
  const ops: AnyBulkWriteOperation<ArchivedOfficeTenure>[] = [];
  for (const entry of entries) {
    if (!entry.iteration) continue;
    const _id = archiveId(slug, entry);
    ops.push({
      replaceOne: {
        filter: { _id },
        // An upsert takes `_id` from the equality filter.
        replacement: { slug, iteration: entry.iteration, entry, archivedAt },
        upsert: true,
      },
    });
  }
  if (ops.length === 0) return 0;
  await db
    .collection<ArchivedOfficeTenure>(OFFICE_HISTORY_ARCHIVE_COLLECTION)
    .bulkWrite(ops, { ordered: false });
  return ops.length;
}

export async function loadArchivedOfficeHistory(
  db: Db,
  slug: string
): Promise<OfficeTenureEntry[]> {
  const rows = await db
    .collection<ArchivedOfficeTenure>(OFFICE_HISTORY_ARCHIVE_COLLECTION)
    .find({ slug })
    .toArray();
  return rows.map((row) => row.entry);
}

/**
 * Archived tenures that the live tables do not already show. They only
 * overlap if a reset failed between archiving and the sweep.
 */
export function mergeArchivedTenures(
  slug: string,
  live: OfficeTenureEntry[],
  archived: OfficeTenureEntry[]
): OfficeTenureEntry[] {
  const liveKeys = new Set(live.map((entry) => archivedTenureKey(slug, entry)));
  return archived.filter((entry) => !liveKeys.has(archivedTenureKey(slug, entry)));
}
