import { describe, it, expect, beforeEach } from "vitest";
import type { Db } from "mongodb";
import { createMockDb, type MockDb } from "@/lib/test-utils/mockDb";
import {
  buildTenureGroups,
  closeOutgoingTenures,
  iterationContextFor,
  type OfficeTenureEntry,
} from "./autoGeneratedPages";
import { weekYearFromTurn } from "./officeIteration";
import {
  archivedTenureKey,
  loadArchivedOfficeHistory,
  mergeArchivedTenures,
  OFFICE_HISTORY_ARCHIVE_COLLECTION,
  writeArchivedOfficeHistory,
} from "./officeHistoryArchive";

const B2 = { type: "Beta", number: 2 } as const;
const B3 = { type: "Beta", number: 3 } as const;
const SLUG = "president-of-the-united-states";

function tenure(partial: Partial<OfficeTenureEntry>): OfficeTenureEntry {
  return { name: "Holder", source: "country-history", iteration: B2, ...partial };
}

let db: MockDb;

beforeEach(() => {
  db = createMockDb();
});

describe("closeOutgoingTenures", () => {
  const ctx = {
    current: B2,
    startingYear: 1953,
    anchor: { currentTurn: 97, lastTurnProcessed: new Date(), startingYear: 1953 },
  };

  it("closes the incumbent at the final turn and drops its profile link", () => {
    const [closed] = closeOutgoingTenures(
      [
        tenure({
          name: "Incumbent",
          startWeekYear: "Week 1, 1953",
          endWeekYear: null,
          isCurrent: true,
          profileHref: "/character/abc",
        }),
      ],
      ctx
    );
    expect(closed.isCurrent).toBe(false);
    expect(closed.endTurn).toBe(97);
    expect(closed.endWeekYear).toBe(weekYearFromTurn(97, 1953));
    expect(closed.endWeekYear).toContain("1955");
    expect(closed.profileHref).toBeNull();
  });

  it("dates the close on the founding-phase calendar, not a year ahead of it", () => {
    const foundedWorld = iterationContextFor({
      iteration: B2,
      startingYear: 1953,
      currentTurn: 1329,
      lastTurnProcessed: new Date(),
      preIteration: { active: false, startedTurn: 1, completedTurn: 49 },
      preIterationTurns: 48,
    });
    const [closed] = closeOutgoingTenures([tenure({ endWeekYear: null })], foundedWorld);
    expect(closed.endWeekYear).toBe(weekYearFromTurn(1329, 1953, { preIterationTurns: 48 }));
    expect(closed.endWeekYear).toContain("1979");
  });

  it("keeps a tenure that already ended, and only the outgoing iteration's rows", () => {
    const closed = closeOutgoingTenures(
      [
        tenure({ name: "Ended", endWeekYear: "Week 20, 1954", endTurn: 68 }),
        tenure({ name: "Other world", iteration: B3 }),
      ],
      ctx
    );
    expect(closed.map((e) => e.name)).toEqual(["Ended"]);
    expect(closed[0].endWeekYear).toBe("Week 20, 1954");
    expect(closed[0].endTurn).toBe(68);
  });
});

describe("archivedTenureKey", () => {
  it("separates two worlds that reused an iteration label", () => {
    const first = tenure({ startWeekYear: "Week 1, 1953", endWeekYear: "Week 1, 1955" });
    const second = tenure({ startWeekYear: "Week 1, 1953", endWeekYear: "Week 30, 1953" });
    expect(archivedTenureKey(SLUG, first)).not.toBe(archivedTenureKey(SLUG, second));
  });

  it("is stable for the same tenure, so a retried reset rewrites rather than duplicates", () => {
    const a = tenure({ startDate: new Date("2026-08-09T00:00:00Z"), endWeekYear: "Week 1, 1955" });
    const b = { ...a, startDate: new Date("2026-08-09T00:00:00Z") };
    expect(archivedTenureKey(SLUG, a)).toBe(archivedTenureKey(SLUG, b));
  });
});

describe("writeArchivedOfficeHistory", () => {
  it("upserts each tenure under a deterministic id", async () => {
    const archivedAt = new Date("2026-10-03T00:00:00Z");
    const written = await writeArchivedOfficeHistory(
      db as unknown as Db,
      SLUG,
      [
        tenure({ name: "A", endWeekYear: "Week 2, 1953" }),
        tenure({ name: "B", endWeekYear: null }),
      ],
      archivedAt
    );
    expect(written).toBe(2);
    const [ops] = db.collectionMocks[OFFICE_HISTORY_ARCHIVE_COLLECTION].bulkWrite.mock.calls[0];
    expect(ops).toHaveLength(2);
    for (const op of ops) {
      expect(op.replaceOne.upsert).toBe(true);
      expect(op.replaceOne.filter._id).toMatch(/^[0-9a-f]{64}$/);
      expect(op.replaceOne.replacement).not.toHaveProperty("_id");
      expect(op.replaceOne.replacement).toMatchObject({ slug: SLUG, iteration: B2, archivedAt });
    }
  });

  it("writes nothing for an office with no tenures", async () => {
    expect(await writeArchivedOfficeHistory(db as unknown as Db, SLUG, [], new Date())).toBe(0);
    expect(db.collection).not.toHaveBeenCalledWith(OFFICE_HISTORY_ARCHIVE_COLLECTION);
  });
});

describe("archived tenures on the office page", () => {
  it("adds earlier worlds' tenures as their own iteration group", async () => {
    const archived = tenure({ name: "Earlier", endWeekYear: "Week 1, 1955", startYear: 1953 });
    db.collection(OFFICE_HISTORY_ARCHIVE_COLLECTION);
    db.collectionMocks[OFFICE_HISTORY_ARCHIVE_COLLECTION].find.mockReturnValue({
      toArray: async () => [{ _id: "x", slug: SLUG, iteration: B2, entry: archived }],
    });
    const live = [tenure({ name: "Now", iteration: B3, isCurrent: true, endWeekYear: null })];

    const earlier = mergeArchivedTenures(
      SLUG,
      live,
      await loadArchivedOfficeHistory(db as unknown as Db, SLUG)
    );
    const groups = buildTenureGroups([...live, ...earlier], [B2, B3], B3);

    expect(groups.map((g) => [g.label, g.entries.map((e) => e.name)])).toEqual([
      ["Beta 2", ["Earlier"]],
      ["Beta 3", ["Now"]],
    ]);
  });

  it("does not repeat a tenure the live tables still hold after a half-finished reset", () => {
    const shared = tenure({ name: "Both", endWeekYear: "Week 9, 1954" });
    expect(mergeArchivedTenures(SLUG, [shared], [{ ...shared }])).toEqual([]);
  });
});
