import { describe, expect, it } from "vitest";
import {
  isClaimManagedWikiSlug,
  isCustomWikiPage,
  resolveWikiCategory,
} from "./pageClassification";

describe("resolveWikiCategory", () => {
  it("prefers the stored category over free-form tags", () => {
    expect(resolveWikiCategory(["economy", "campaign"], "events")).toBe("events");
  });

  it("prefers a known category tag when present", () => {
    expect(resolveWikiCategory(["economy", "bonds"], undefined)).toBe("economy");
  });

  it("falls back to the legacy category when tags do not contain a category id", () => {
    expect(resolveWikiCategory(["player", "biography"], "characters")).toBe("characters");
  });

  it("defaults to reference when no category metadata exists", () => {
    expect(resolveWikiCategory(undefined, undefined)).toBe("reference");
  });
});

describe("isClaimManagedWikiSlug", () => {
  it("matches reserved profile slug patterns", () => {
    expect(isClaimManagedWikiSlug("player-12")).toBe(true);
    expect(isClaimManagedWikiSlug("corp-48")).toBe(true);
    expect(isClaimManagedWikiSlug("party-us-3")).toBe(true);
    expect(isClaimManagedWikiSlug("my-custom-event")).toBe(false);
  });
});

describe("isCustomWikiPage", () => {
  it("treats player-submitted pages with game provenance as custom pages", () => {
    expect(
      isCustomWikiPage({
        slug: "the-boston-accord",
        isAutoGenerated: false,
        category: "events",
        submittedBy: { toString: () => "507f1f77bcf86cd799439011" } as never,
        reviewedBy: { toString: () => "507f1f77bcf86cd799439012" } as never,
        editHistory: undefined,
        gameIteration: "A6",
        gameStartDate: "2026-01-01",
      })
    ).toBe(true);
  });

  it("excludes claim-managed profile stubs", () => {
    expect(
      isCustomWikiPage({
        slug: "player-77",
        isAutoGenerated: false,
        category: "characters",
        submittedBy: { toString: () => "507f1f77bcf86cd799439011" } as never,
        reviewedBy: { toString: () => "507f1f77bcf86cd799439012" } as never,
        editHistory: undefined,
        gameIteration: "A6",
        gameStartDate: "2026-01-01",
      })
    ).toBe(false);
  });

  it("excludes official pages without player provenance", () => {
    expect(
      isCustomWikiPage({
        slug: "getting-started",
        isAutoGenerated: false,
        category: "reference",
        submittedBy: undefined,
        reviewedBy: undefined,
        editHistory: undefined,
        gameIteration: undefined,
        gameStartDate: undefined,
      })
    ).toBe(false);
  });

  it("includes legacy player-written scratch pages without game stamps", () => {
    expect(
      isCustomWikiPage({
        slug: "the-boston-accord",
        isAutoGenerated: false,
        category: "events",
        submittedBy: { toString: () => "507f1f77bcf86cd799439011" } as never,
        reviewedBy: { toString: () => "507f1f77bcf86cd799439012" } as never,
        editHistory: [
          {
            userId: { toString: () => "507f1f77bcf86cd799439011" } as never,
            timestamp: new Date("2026-01-01T00:00:00Z"),
            action: "created",
          },
        ],
        gameIteration: undefined,
        gameStartDate: undefined,
      })
    ).toBe(true);
  });

  it("excludes seeded pages even if they are unstamped", () => {
    expect(
      isCustomWikiPage({
        slug: "official-event-page",
        isAutoGenerated: false,
        category: "events",
        submittedBy: { toString: () => "507f1f77bcf86cd799439011" } as never,
        reviewedBy: undefined,
        editHistory: [
          {
            userId: { toString: () => "507f1f77bcf86cd799439011" } as never,
            timestamp: new Date("2026-01-01T00:00:00Z"),
            action: "created",
            note: "Reseed - initial insert",
          },
        ],
        gameIteration: undefined,
        gameStartDate: undefined,
      })
    ).toBe(false);
  });

  it("excludes unstamped moderator-published pages that never passed through review", () => {
    expect(
      isCustomWikiPage({
        slug: "official-reference-addendum",
        isAutoGenerated: false,
        category: "reference",
        submittedBy: { toString: () => "507f1f77bcf86cd799439011" } as never,
        reviewedBy: undefined,
        editHistory: [
          {
            userId: { toString: () => "507f1f77bcf86cd799439011" } as never,
            timestamp: new Date("2026-01-01T00:00:00Z"),
            action: "created",
          },
        ],
        gameIteration: undefined,
        gameStartDate: undefined,
      })
    ).toBe(false);
  });
});
