// src/lib/wiki/wikiSearchSources.ts
import { getAutoGeneratedWikiPagesForDisplay } from "@/lib/wiki/autoGeneratedPages";
import { WIKI_CATEGORIES } from "@/lib/wiki/categories";
import { getVisibleLearningPaths } from "@/lib/wiki/learningPaths";
import type { WikiSearchCandidate } from "@/lib/wiki/wikiSearch";

/**
 * Every wiki surface that is NOT an authored `wikiPages` document: parties,
 * seats, offices, cabinet and leadership pages, elections, category indexes and
 * learning paths. These are linked from the wiki home page but have no document
 * in `wikiPages`, so a search that only queries that collection cannot find any
 * of them.
 *
 * `getAutoGeneratedWikiPagesForDisplay` is already cached (120s revalidate), so
 * this is not a per-request database sweep.
 */
export async function getNonPageWikiSearchCandidates(): Promise<WikiSearchCandidate[]> {
  const [autoGenerated, learningPaths] = await Promise.all([
    getAutoGeneratedWikiPagesForDisplay(),
    getVisibleLearningPaths(),
  ]);

  const candidates: WikiSearchCandidate[] = autoGenerated.map((summary) => ({
    slug: summary.slug,
    title: summary.title,
    description: summary.description,
    href: summary.href,
    kind: summary.kind,
  }));

  // The category route resolves its param with `getCategoryBySlug`, so the href
  // must carry the slug rather than the id.
  for (const category of WIKI_CATEGORIES) {
    candidates.push({
      slug: category.slug,
      title: category.name,
      description: category.description,
      href: `/wiki/category/${category.slug}`,
      kind: "category",
    });
  }

  for (const path of learningPaths) {
    candidates.push({
      slug: path.slug,
      title: path.title,
      description: path.description,
      href: `/wiki/paths/${path.slug}`,
      kind: "path",
    });
  }

  return candidates;
}
