import { beforeEach, describe, expect, it, vi } from "vitest";
import type { Db } from "mongodb";
import { createMockDb, type MockDb } from "@/lib/test-utils/mockDb";

vi.mock("next/cache", () => ({ unstable_cache: (load: () => Promise<unknown>) => load }));
vi.mock("@/lib/mongodb", () => ({ getDb: vi.fn() }));

type Page = {
  slug: string;
  title: string;
  description: string;
  countryId?: string;
  tags?: string[];
  createdAt: Date;
  viewCount?: number;
};

const pages: Page[] = Array.from({ length: 6 }, (_, index) => ({
  slug: `page-${index + 1}`,
  title: `Page ${index + 1}`,
  description: "A published page",
  countryId: index === 1 ? "UK" : "US",
  tags: ["getting-started"],
  createdAt: new Date(Date.UTC(2026, 0, index + 1)),
  viewCount: 60 - index,
}));

describe("wiki index page aggregation", () => {
  let db: MockDb;
  let enabled: boolean;
  let recentSort: unknown;
  let viewedSort: unknown;
  const limits: number[] = [];

  beforeEach(async () => {
    db = createMockDb();
    enabled = true;
    recentSort = undefined;
    viewedSort = undefined;
    limits.length = 0;

    db.collection("countryGameStates");
    db.collection("gameState");
    db.collection("wikiPages");
    db.collectionMocks.countryGameStates.find.mockImplementation(() => ({
      toArray: async () => [
        { _id: "US", status: enabled ? "active" : "coming-soon", enabledForPlayers: enabled },
        { _id: "UK", status: "coming-soon", enabledForPlayers: false },
      ],
    }));
    db.collectionMocks.gameState.findOne.mockResolvedValue(null);
    db.collectionMocks.wikiPages.find.mockImplementation((_query: Record<string, unknown>) => {
      let result = [...pages];
      const cursor = {
        sort: vi.fn((sort: unknown) => {
          const ordering = sort as Record<string, number>;
          if ("createdAt" in ordering) {
            recentSort = sort;
            result.sort(
              (left, right) =>
                ordering.createdAt * (left.createdAt.getTime() - right.createdAt.getTime())
            );
          }
          if ("viewCount" in ordering) {
            viewedSort = sort;
            result.sort(
              (left, right) => ordering.viewCount * ((left.viewCount ?? 0) - (right.viewCount ?? 0))
            );
          }
          return cursor;
        }),
        limit: vi.fn((count: number) => {
          limits.push(count);
          result = result.slice(0, count);
          return cursor;
        }),
        toArray: vi.fn(async () => result),
      };
      return cursor;
    });

    const { getDb } = await import("@/lib/mongodb");
    vi.mocked(getDb).mockResolvedValue(db as unknown as Db);
  });

  it("shares one access read across all panels and refreshes eligibility on the next rebuild", async () => {
    const { loadWikiIndexData } = await import("./getWikiPageData");

    const first = await loadWikiIndexData();

    expect(db.collectionMocks.countryGameStates.find).toHaveBeenCalledTimes(1);
    expect(first.pages.map((page) => page.slug)).toEqual([
      "page-1",
      "page-3",
      "page-4",
      "page-5",
      "page-6",
    ]);
    expect(first.recentPages.map((page) => page.slug)).toEqual([
      "page-6",
      "page-5",
      "page-4",
      "page-3",
    ]);
    expect(first.mostViewedPages.map((page) => page.slug)).toEqual([
      "page-1",
      "page-3",
      "page-4",
      "page-5",
    ]);
    expect(recentSort).toEqual({ createdAt: -1 });
    expect(viewedSort).toEqual({ viewCount: -1 });
    expect(limits).toEqual([5, 5]);

    const findQueries = db.collectionMocks.wikiPages.find.mock.calls.map(([query]) => query);
    expect(findQueries).toContainEqual({ status: "published", private: { $ne: true } });
    expect(findQueries).toContainEqual({
      status: "published",
      isAutoGenerated: { $ne: true },
      private: { $ne: true },
    });
    expect(findQueries).toContainEqual({
      status: "published",
      viewCount: { $gt: 0 },
      private: { $ne: true },
    });

    enabled = false;
    const refreshed = await loadWikiIndexData();

    expect(db.collectionMocks.countryGameStates.find).toHaveBeenCalledTimes(2);
    expect(refreshed.pages).toEqual([]);
    expect(refreshed.recentPages).toEqual([]);
    expect(refreshed.mostViewedPages).toEqual([]);
  });
});
