// src/lib/wiki/wikiSearch.ts
import type { AutoGeneratedPageKind } from "@/lib/wiki/autoGeneratedPages";

/**
 * Every surface the wiki search can return. `page` is an authored wiki page
 * from the `wikiPages` collection; the rest are generated or static surfaces
 * that live under /wiki but have no `wikiPages` document behind them.
 */
export type WikiSearchKind = "page" | AutoGeneratedPageKind | "category" | "path";

/** A searchable wiki surface before ranking. Match-only fields are stripped from the result. */
export interface WikiSearchCandidate {
  slug: string;
  title: string;
  description?: string;
  href: string;
  kind: WikiSearchKind;
  tags?: string[];
  featured?: boolean;
  /**
   * The source already confirmed the query matched this candidate's body.
   *
   * The database query matches title/description/content itself, so a document
   * it returned whose title and description do not match must have matched on
   * content. Carrying that as a flag lets a body hit rank correctly without
   * projecting whole page bodies over the wire just to re-derive it.
   */
  matchedBody?: boolean;
}

/** A ranked hit as returned to the client. */
export type WikiSearchResult = Omit<WikiSearchCandidate, "matchedBody">;

/**
 * Match tiers, best first. A title hit must always outrank a body hit: searching
 * "filibuster" should surface the Filibuster page, not every page that happens
 * to mention the word.
 */
const SCORE_TITLE_EXACT = 100;
const SCORE_TITLE_PREFIX = 80;
const SCORE_TITLE_SUBSTRING = 60;
const SCORE_DESCRIPTION = 40;
const SCORE_CONTENT = 20;
const SCORE_NO_MATCH = 0;

/**
 * Score one candidate against the query. Returns 0 when nothing matches, which
 * the caller treats as "exclude".
 */
export function scoreWikiSearchCandidate(query: string, candidate: WikiSearchCandidate): number {
  const q = query.trim().toLowerCase();
  if (!q) return SCORE_TITLE_EXACT;

  const title = candidate.title.toLowerCase();
  if (title === q) return SCORE_TITLE_EXACT;
  if (title.startsWith(q)) return SCORE_TITLE_PREFIX;
  if (title.includes(q)) return SCORE_TITLE_SUBSTRING;
  if (candidate.description?.toLowerCase().includes(q)) return SCORE_DESCRIPTION;
  if (candidate.matchedBody) return SCORE_CONTENT;
  return SCORE_NO_MATCH;
}

/**
 * Rank candidates by match quality, then alphabetically, and only then apply
 * the limit. Applying the limit first (as an unsorted `find().limit()` does)
 * makes the cutoff arbitrary — an exact title match can be dropped in favour of
 * whichever documents the database happened to return first.
 */
export function rankWikiSearchCandidates(
  query: string,
  candidates: WikiSearchCandidate[],
  limit: number
): WikiSearchResult[] {
  const scored: Array<{ score: number; candidate: WikiSearchCandidate }> = [];

  for (const candidate of candidates) {
    const score = scoreWikiSearchCandidate(query, candidate);
    if (score === SCORE_NO_MATCH) continue;
    scored.push({ score, candidate });
  }

  scored.sort((a, b) => {
    if (b.score !== a.score) return b.score - a.score;
    return a.candidate.title.localeCompare(b.candidate.title);
  });

  return scored.slice(0, limit).map(({ candidate }) => {
    const { matchedBody: _matchedBody, ...result } = candidate;
    void _matchedBody;
    return result;
  });
}
