import type { CountryId } from "@/lib/constants/countries";
import type { Condition } from "@/lib/utils/approvalModifiers";

export interface CountryModifierPatch {
  suppress?: boolean;
  conditions?: Condition[];
  marginFactor?: number;
}

type CountryPatchMap = Partial<Record<CountryId, Record<string, CountryModifierPatch>>>;

const c = (category: string, metric: string, op: Condition["op"], value: number): Condition => ({
  category,
  metric,
  op,
  value,
});

/**
 * Per-country threshold overrides and suppressions. Applied after global (and
 * era1991) defs. Suppress modifiers whose seed inputs are nationally flat —
 * they cannot differentiate regions in that country.
 */
export const COUNTRY_MODIFIER_PATCHES: CountryPatchMap = {
  UK: {
    high_poverty: { conditions: [c("economic", "povertyRate", ">=", 20)] },
    low_poverty: { conditions: [c("economic", "povertyRate", "<=", 11)] },
    crime_wave: {
      conditions: [
        c("publicSafety", "violentCrimeRate", ">=", 380),
        c("publicSafety", "publicSafetyConfidence", "<=", 52),
      ],
    },
    high_violent_crime: { conditions: [c("publicSafety", "violentCrimeRate", ">=", 400)] },
    affordable_housing: { conditions: [c("social", "housingAffordability", "<=", 8)] },
    housing_stress: { conditions: [c("social", "housingAffordability", ">=", 12)] },
    corruption_concerns: { conditions: [c("governance", "corruptionIndex", ">=", 34)] },
    free_press: { conditions: [c("mediaInformation", "pressFreedom", ">=", 80)] },
    heavy_public_debt: { conditions: [c("governance", "debtToGdp", ">=", 100)] },
    research_hub: { conditions: [c("economic", "rdIntensity", ">=", 2.0)] },
  },

  JP: {
    // Nationally low / flat baselines — only fire on meaningful regional spread.
    universal_healthcare: { suppress: true },
    low_unemployment: { suppress: true },
    heavy_public_debt: { suppress: true },
    high_broadband: { suppress: true },
    low_broadband: { suppress: true },
    infrastructure_boom: { suppress: true },
    balanced_budget: { suppress: true },
    corruption_concerns: { suppress: true },
    high_corruption: { suppress: true },
    high_life_expectancy: { suppress: true },
    longevity: { suppress: true },
    aging_population: { suppress: true },
    safe_streets: {
      conditions: [
        c("publicSafety", "violentCrimeRate", "<=", 18),
        c("publicSafety", "publicSafetyConfidence", ">=", 72),
      ],
    },
    falling_crime: { conditions: [c("publicSafety", "violentCrimeRate", "<=", 17)] },
    crime_wave: {
      conditions: [
        c("publicSafety", "violentCrimeRate", ">=", 26),
        c("publicSafety", "publicSafetyConfidence", "<=", 58),
      ],
    },
    high_violent_crime: { conditions: [c("publicSafety", "violentCrimeRate", ">=", 27)] },
    poor_air_quality: { conditions: [c("environment", "airQuality", ">=", 84)] },
    slow_growth: { conditions: [c("economic", "gdpGrowth", "<=", 0.2)] },
    research_hub: { conditions: [c("economic", "rdIntensity", ">=", 3.45)] },
    housing_stress: { conditions: [c("social", "housingAffordability", ">=", 75)] },
    affordable_housing: { conditions: [c("social", "housingAffordability", "<=", 52)] },
    high_poverty: { conditions: [c("economic", "povertyRate", ">=", 15)] },
    green_transition: { conditions: [c("environment", "renewableEnergy", ">=", 32)] },
    free_press: { conditions: [c("mediaInformation", "pressFreedom", ">=", 74)] },
    innovation_economy: {
      conditions: [
        c("economic", "smallBusinessFormation", ">=", 6),
        c("education", "workforceSkill", ">=", 82),
      ],
    },
  },

  DE: {
    universal_healthcare: { suppress: true },
    safe_streets: { suppress: true },
    falling_crime: { suppress: true },
    high_broadband: { suppress: true },
    low_broadband: { suppress: true },
    infrastructure_boom: { suppress: true },
    free_press: { suppress: true },
    poor_air_quality: { suppress: true },
    corruption_concerns: { suppress: true },
    high_corruption: { suppress: true },
    balanced_budget: { suppress: true },
    high_voter_turnout: { suppress: true },
    good_recycling: { suppress: true },
    innovation_economy: { suppress: true },
    high_immigration: { suppress: true },
    brain_gain: { suppress: true },
    crime_wave: { suppress: true },
    high_violent_crime: { suppress: true },
    heavy_public_debt: { conditions: [c("governance", "debtToGdp", ">=", 70)] },
    high_poverty: { conditions: [c("economic", "povertyRate", ">=", 20)] },
    low_poverty: { conditions: [c("economic", "povertyRate", "<=", 14)] },
    housing_stress: { conditions: [c("social", "housingAffordability", ">=", 68)] },
    affordable_housing: { conditions: [c("social", "housingAffordability", "<=", 48)] },
    research_hub: { conditions: [c("economic", "rdIntensity", ">=", 3.5)] },
    green_transition: { conditions: [c("environment", "renewableEnergy", ">=", 75)] },
    slow_growth: { conditions: [c("economic", "gdpGrowth", "<=", 0.8)] },
    strong_growth: { conditions: [c("economic", "gdpGrowth", ">=", 1.8)] },
    government_deficit: { suppress: true },
    aging_population: { suppress: true },
  },

  IE: {
    universal_healthcare: { suppress: true },
    safe_streets: { suppress: true },
    falling_crime: { suppress: true },
    high_life_expectancy: { suppress: true },
    longevity: { suppress: true },
    low_unemployment: { suppress: true },
    poor_air_quality: { suppress: true },
    corruption_concerns: { suppress: true },
    high_corruption: { suppress: true },
    free_press: { suppress: true },
    balanced_budget: { suppress: true },
    strong_safety_net: { suppress: true },
    clean_water: { suppress: true },
    green_transition: { suppress: true },
    educated_workforce: { suppress: true },
    innovation_economy: { suppress: true },
    high_immigration: { suppress: true },
    population_boom: { suppress: true },
    brain_gain: { suppress: true },
    youth_surge: { suppress: true },
    crime_wave: { suppress: true },
    high_violent_crime: { suppress: true },
    housing_stress: { conditions: [c("social", "housingAffordability", ">=", 80)] },
    affordable_housing: { conditions: [c("social", "housingAffordability", "<=", 55)] },
    research_hub: { conditions: [c("economic", "rdIntensity", ">=", 2.4)] },
    strong_growth: { conditions: [c("economic", "gdpGrowth", ">=", 3.8)] },
    slow_growth: { conditions: [c("economic", "gdpGrowth", "<=", 1.5)] },
    heavy_public_debt: { conditions: [c("governance", "debtToGdp", ">=", 50)] },
  },

  BR: {
    universal_healthcare: { suppress: true },
    crime_wave: { suppress: true },
    high_violent_crime: { suppress: true },
    poor_air_quality: { suppress: true },
    corruption_concerns: { suppress: true },
    high_corruption: { suppress: true },
    low_public_trust: { suppress: true },
    government_deficit: { suppress: true },
    fiscal_crisis: { suppress: true },
    green_transition: { suppress: true },
    high_voter_turnout: { suppress: true },
    civic_flourishing: { suppress: true },
    information_disorder: { suppress: true },
    media_polarization: { suppress: true },
    free_press: { suppress: true },
    high_poverty: { conditions: [c("economic", "povertyRate", ">=", 40)] },
    low_poverty: { conditions: [c("economic", "povertyRate", "<=", 18)] },
    housing_stress: { conditions: [c("social", "housingAffordability", ">=", 55)] },
    affordable_housing: { conditions: [c("social", "housingAffordability", "<=", 42)] },
    research_hub: { conditions: [c("economic", "rdIntensity", ">=", 1.6)] },
    strong_growth: { conditions: [c("economic", "gdpGrowth", ">=", 4.0)] },
    slow_growth: { conditions: [c("economic", "gdpGrowth", "<=", 2.5)] },
    low_social_mobility: { suppress: true },
    income_inequality: { suppress: true },
    food_insecurity: { suppress: true },
    social_breakdown: { suppress: true },
    youth_surge: { suppress: true },
    low_life_expectancy: { suppress: true },
  },

  CN: {
    low_poverty: { suppress: true },
    universal_healthcare: { suppress: true },
    safe_streets: { suppress: true },
    falling_crime: { suppress: true },
    low_recidivism: { suppress: true },
    crime_wave: { suppress: true },
    high_violent_crime: { suppress: true },
    poor_air_quality: { suppress: true },
    corruption_concerns: { suppress: true },
    high_corruption: { suppress: true },
    high_public_trust: { suppress: true },
    high_voter_turnout: { suppress: true },
    social_cohesion: { suppress: true },
    strong_safety_net: { suppress: true },
    civic_flourishing: { suppress: true },
    declining_population: { suppress: true },
    government_deficit: { suppress: true },
    press_suppression: { suppress: true },
    informed_society: { suppress: true },
    free_press: { suppress: true },
    strong_growth: { conditions: [c("economic", "gdpGrowth", ">=", 6.0)] },
    slow_growth: { conditions: [c("economic", "gdpGrowth", "<=", 3.5)] },
    housing_stress: { conditions: [c("social", "housingAffordability", ">=", 82)] },
    affordable_housing: { conditions: [c("social", "housingAffordability", "<=", 62)] },
    research_hub: { conditions: [c("economic", "rdIntensity", ">=", 3.3)] },
    green_transition: { conditions: [c("environment", "renewableEnergy", ">=", 45)] },
    heavy_public_debt: { conditions: [c("governance", "debtToGdp", ">=", 90)] },
    low_social_mobility: { suppress: true },
    high_social_mobility: { conditions: [c("social", "socialMobility", ">=", 82)] },
    high_broadband: { suppress: true },
    low_broadband: { suppress: true },
    infrastructure_boom: { suppress: true },
    infrastructure_crisis: { suppress: true },
    educated_workforce: {
      conditions: [
        c("education", "highSchoolGradRate", ">=", 92),
        c("education", "workforceSkill", ">=", 78),
      ],
    },
  },

  NG: {
    // Crisis baselines are high nationally — suppress flat metrics, keep spread.
    universal_healthcare: { suppress: true },
    crime_wave: { suppress: true },
    high_violent_crime: { suppress: true },
    poor_air_quality: { suppress: true },
    corruption_concerns: { suppress: true },
    high_corruption: { suppress: true },
    low_public_trust: { suppress: true },
    government_deficit: { suppress: true },
    fiscal_crisis: { suppress: true },
    information_disorder: { suppress: true },
    media_polarization: { suppress: true },
    free_press: { suppress: true },
    low_broadband: { suppress: true },
    healthcare_crisis: { suppress: true },
    high_preventable_mortality: { suppress: true },
    weak_healthcare_capacity: { suppress: true },
    low_life_expectancy: { suppress: true },
    high_unemployment: { suppress: true },
    skills_gap: { suppress: true },
    infrastructure_crisis: { suppress: true },
    high_poverty: { conditions: [c("economic", "povertyRate", ">=", 50)] },
    low_poverty: { conditions: [c("economic", "povertyRate", "<=", 30)] },
    housing_stress: { conditions: [c("social", "housingAffordability", ">=", 58)] },
    affordable_housing: { conditions: [c("social", "housingAffordability", "<=", 48)] },
    research_hub: { conditions: [c("economic", "rdIntensity", ">=", 0.28)] },
    strong_growth: { conditions: [c("economic", "gdpGrowth", ">=", 3.8)] },
    slow_growth: { conditions: [c("economic", "gdpGrowth", "<=", 2.2)] },
    food_insecurity: { suppress: true },
    low_social_mobility: { suppress: true },
    income_inequality: { suppress: true },
    social_breakdown: { suppress: true },
    youth_surge: { suppress: true },
  },
};
