import type { Metadata } from "next";
import Link from "next/link";
import { wikiPublicPageMetadata } from "@/lib/siteMetadata";
import {
  getAllWikiPagesForDisplay,
  getRecentWikiPages,
  getMostViewedWikiPages,
} from "@/lib/wiki/getWikiPageData";
import type { WikiPageSpotlight } from "@/lib/wiki/getWikiPageData";
import {
  getAutoGeneratedWikiPagesForDisplay,
  type AutoGeneratedWikiPageSummary,
} from "@/lib/wiki/autoGeneratedPages";
import { WIKI_CATEGORIES } from "@/lib/wiki/categories";
import { getAuthUser } from "@/lib/auth";
import { AdSenseUnit } from "@/components/AdSenseUnit";

export const metadata: Metadata = wikiPublicPageMetadata({
  title: "Wiki | A House Divided",
  description:
    "Official wiki for A House Divided: onboarding, elections, legislation, parties, corporations, forex, and country-specific rules for the US, UK, Germany, and Japan.",
  pathname: "/wiki",
});

const PLAYER_CATEGORIES = new Set(["characters", "corporations", "player-parties"]);
const COMMUNITY_CATEGORY_IDS = new Set([
  "characters",
  "corporations",
  "player-parties",
  "events",
  "custom-pages",
]);

function formatRelativeDate(date: Date | string): string {
  const d = date instanceof Date ? date : new Date(date);
  const diffDays = Math.floor((Date.now() - d.getTime()) / 86_400_000);
  if (diffDays === 0) return "today";
  if (diffDays === 1) return "yesterday";
  if (diffDays < 30) return `${diffDays}d ago`;
  const months = Math.floor(diffDays / 30);
  if (months < 12) return `${months}mo ago`;
  return `${Math.floor(months / 12)}y ago`;
}

function formatViewCount(n: number): string {
  return n >= 1000 ? `${(n / 1000).toFixed(1)}k` : String(n);
}

function IconBookOpen() {
  return (
    <svg className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"
      />
    </svg>
  );
}

function IconClipboard() {
  return (
    <svg className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4"
      />
    </svg>
  );
}

function IconStar() {
  return (
    <svg className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z"
      />
    </svg>
  );
}

const CATEGORY_ICON_PATHS: Record<string, React.ReactNode> = {
  "getting-started": (
    <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
      />
    </svg>
  ),
  elections: (
    <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4"
      />
    </svg>
  ),
  legislatures: (
    <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3"
      />
    </svg>
  ),
  countries: (
    <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7"
      />
    </svg>
  ),
  parties: (
    <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"
      />
    </svg>
  ),
  economy: (
    <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M3 17l6-6 4 4 8-8M17 7h4v4" />
    </svg>
  ),
  commodities: (
    <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"
      />
    </svg>
  ),
  resources: (
    <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M14 10l-2 1m0 0l-2-1m2 1v2.5M20 7l-2 1m2-1l-2-1m2 1v2.5M14 4l-2-1-2 1M4 7l2-1M4 7l2 1M4 7v2.5M12 21l-2-1m2 1l2-1m-2 1v-2.5M6 18l-2-1v-2.5M18 18l2-1v-2.5"
      />
    </svg>
  ),
  advanced: (
    <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z"
      />
    </svg>
  ),
  reference: (
    <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"
      />
    </svg>
  ),
  iterations: (
    <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M12 8v4l3 2m6-2a9 9 0 11-18 0 9 9 0 0118 0z"
      />
    </svg>
  ),
  "custom-pages": (
    <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5M16.5 3.5a2.121 2.121 0 113 3L12 14l-4 1 1-4 7.5-7.5z"
      />
    </svg>
  ),
  characters: (
    <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"
      />
    </svg>
  ),
  corporations: (
    <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4"
      />
    </svg>
  ),
  "player-parties": (
    <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M3 21v-2a4 4 0 014-4h10a4 4 0 014 4v2M12 11a4 4 0 100-8 4 4 0 000 8z"
      />
    </svg>
  ),
  events: (
    <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M19 20H5a2 2 0 01-2-2V6a2 2 0 012-2h10a2 2 0 012 2v1m2 13a2 2 0 01-2-2V7m2 13a2 2 0 002-2V9a2 2 0 00-2-2h-2m-4-3H9M7 16h6M7 8h6v4H7V8z"
      />
    </svg>
  ),
};

const DEFAULT_ICON = (
  <svg className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
    />
  </svg>
);

function SpotlightRow({ page, showViews }: { page: WikiPageSpotlight; showViews?: boolean }) {
  return (
    <Link
      href={`/wiki/${page.slug}`}
      className="flex items-center justify-between gap-2 rounded-md px-2 py-1.5 text-sm transition-colors hover:bg-card-elevated group"
    >
      <span className="truncate text-foreground group-hover:text-primary">{page.title}</span>
      <span className="shrink-0 text-xs text-muted/60 tabular-nums">
        {showViews && page.viewCount != null
          ? `${formatViewCount(page.viewCount)} views`
          : formatRelativeDate(page.createdAt)}
      </span>
    </Link>
  );
}

type WikiListEntry = {
  slug: string;
  title: string;
  description?: string;
  href: string;
  kind?: AutoGeneratedWikiPageSummary["kind"];
  /** Optional recency signal — auto-gen elections set this so the consumer can sort newest first. */
  sortDate?: Date;
};

const FULL_LIST_PAGE_SIZE = 10;

type FullListSectionKey = "auto" | "player" | "system";

interface FullListPageState {
  auto: number;
  player: number;
  system: number;
}

function parsePageParam(value: string | string[] | undefined): number {
  const raw = Array.isArray(value) ? value[0] : value;
  if (typeof raw !== "string") return 1;
  const n = Number.parseInt(raw, 10);
  return Number.isFinite(n) && n > 0 ? n : 1;
}

function buildPageHref(
  state: FullListPageState,
  section: FullListSectionKey,
  page: number,
  hash: string
): string {
  const qs = new URLSearchParams();
  (Object.keys(state) as FullListSectionKey[]).forEach((key) => {
    const target = key === section ? page : state[key];
    if (target > 1) qs.set(key, String(target));
  });
  const qsStr = qs.toString();
  return `${qsStr ? `?${qsStr}` : ""}${hash}`;
}

function getCondensedPageNumbers(current: number, total: number): (number | "ellipsis")[] {
  if (total <= 7) return Array.from({ length: total }, (_, i) => i + 1);
  const anchors = new Set<number>([1, 2, total - 1, total, current - 1, current, current + 1]);
  const sorted = [...anchors].filter((p) => p >= 1 && p <= total).sort((a, b) => a - b);
  const out: (number | "ellipsis")[] = [];
  let prev = 0;
  for (const p of sorted) {
    if (p - prev > 1) out.push("ellipsis");
    out.push(p);
    prev = p;
  }
  return out;
}

function PaginationNav({
  state,
  section,
  totalPages,
  hash,
}: {
  state: FullListPageState;
  section: FullListSectionKey;
  totalPages: number;
  hash: string;
}) {
  if (totalPages <= 1) return null;
  const current = Math.min(state[section], totalPages);
  const pages = getCondensedPageNumbers(current, totalPages);
  const navLinkClasses = "rounded-md px-3 py-1.5 transition-colors";
  const inactiveClasses = "text-muted hover:bg-card-elevated hover:text-foreground";
  const disabledClasses = "pointer-events-none text-muted/40";
  return (
    <nav
      aria-label={`${section} pagination`}
      className="mt-4 flex flex-wrap items-center justify-center gap-1 text-sm"
    >
      {current > 1 ? (
        <Link
          href={buildPageHref(state, section, current - 1, hash)}
          className={`${navLinkClasses} ${inactiveClasses}`}
        >
          ‹ Prev
        </Link>
      ) : (
        <span className={`${navLinkClasses} ${disabledClasses}`}>‹ Prev</span>
      )}
      {pages.map((p, i) =>
        p === "ellipsis" ? (
          <span key={`ellipsis-${i}`} className="px-2 text-muted/50">
            …
          </span>
        ) : p === current ? (
          <span
            key={p}
            aria-current="page"
            className="rounded-md bg-primary px-3 py-1.5 font-semibold text-primary-foreground"
          >
            {p}
          </span>
        ) : (
          <Link
            key={p}
            href={buildPageHref(state, section, p, hash)}
            className={`${navLinkClasses} ${inactiveClasses}`}
          >
            {p}
          </Link>
        )
      )}
      {current < totalPages ? (
        <Link
          href={buildPageHref(state, section, current + 1, hash)}
          className={`${navLinkClasses} ${inactiveClasses}`}
        >
          Next ›
        </Link>
      ) : (
        <span className={`${navLinkClasses} ${disabledClasses}`}>Next ›</span>
      )}
    </nav>
  );
}

function WikiFullListSection({
  id,
  hash,
  title,
  description,
  pages,
  state,
  section,
}: {
  id: string;
  hash: string;
  title: string;
  description: string;
  pages: WikiListEntry[];
  state: FullListPageState;
  section: FullListSectionKey;
}) {
  const total = pages.length;
  const totalPages = Math.max(1, Math.ceil(total / FULL_LIST_PAGE_SIZE));
  const currentPage = Math.min(Math.max(state[section], 1), totalPages);
  const startIdx = (currentPage - 1) * FULL_LIST_PAGE_SIZE;
  const endIdx = Math.min(startIdx + FULL_LIST_PAGE_SIZE, total);
  const visible = pages.slice(startIdx, endIdx);

  return (
    <section id={id} className="scroll-mt-24">
      <div className="mb-3 flex items-end justify-between gap-3 border-b border-card-border pb-2">
        <div>
          <h3 className="font-serif text-lg font-bold text-foreground">{title}</h3>
          <p className="mt-1 text-sm text-muted">{description}</p>
        </div>
        <span className="shrink-0 text-xs text-muted tabular-nums">
          {total > 0 ? `${startIdx + 1}–${endIdx} of ${total}` : "0 pages"}
        </span>
      </div>
      {visible.length > 0 ? (
        <div className="columns-1 gap-8 space-y-1 sm:columns-2 lg:columns-3">
          {visible.map((page) => (
            <Link
              key={`${page.kind ?? "page"}-${page.slug}`}
              href={page.href}
              title={page.description}
              className="block break-inside-avoid py-1 text-sm text-muted decoration-primary/30 underline-offset-2 hover:text-primary hover:underline"
            >
              {page.title}
            </Link>
          ))}
        </div>
      ) : (
        <p className="rounded-lg border border-card-border bg-card/40 p-4 text-sm text-muted">
          No pages in this group yet.
        </p>
      )}
      <PaginationNav state={state} section={section} totalPages={totalPages} hash={hash} />
    </section>
  );
}

export default async function WikiOverviewPage({
  searchParams,
}: {
  searchParams: Promise<{
    auto?: string | string[];
    player?: string | string[];
    system?: string | string[];
  }>;
}) {
  const sp = await searchParams;
  const pageState: FullListPageState = {
    auto: parsePageParam(sp.auto),
    player: parsePageParam(sp.player),
    system: parsePageParam(sp.system),
  };

  const [allPages, autoGeneratedPages, recentPages, mostViewedPages, user] = await Promise.all([
    getAllWikiPagesForDisplay(),
    getAutoGeneratedWikiPagesForDisplay(),
    getRecentWikiPages(),
    getMostViewedWikiPages(),
    getAuthUser().catch(() => null),
  ]);

  const canPublishDirectly = !!(user?.isAdmin || user?.isModerator);

  const playerPages = allPages.filter(
    (p) => PLAYER_CATEGORIES.has(p.category ?? "") || p.isCustomPage
  );
  const customPages = allPages.filter((p) => p.isCustomPage);
  const dbAutoGeneratedPages: WikiListEntry[] = allPages
    .filter((p) => p.isAutoGenerated)
    .map((p) => ({
      slug: p.slug,
      title: p.title,
      description: p.description,
      href: p.href ?? `/wiki/${p.slug}`,
      sortDate: p.updatedAt,
    }));
  // Sort auto-generated newest-first using sortDate (election endTime / db
  // updatedAt). Static office/seat/party entries have no sortDate and fall
  // through to alphabetical AFTER all dated entries.
  const autoGeneratedList: WikiListEntry[] = [...autoGeneratedPages, ...dbAutoGeneratedPages].sort(
    (a, b) => {
      const aTime = a.sortDate ? new Date(a.sortDate).getTime() : Number.NEGATIVE_INFINITY;
      const bTime = b.sortDate ? new Date(b.sortDate).getTime() : Number.NEGATIVE_INFINITY;
      if (bTime !== aTime) return bTime - aTime;
      return a.title.localeCompare(b.title);
    }
  );
  const playerList: WikiListEntry[] = playerPages
    .map((p) => ({
      slug: p.slug,
      title: p.title,
      description: p.description,
      href: p.href ?? `/wiki/${p.slug}`,
    }))
    .sort((a, b) => a.title.localeCompare(b.title));
  const systemPages: WikiListEntry[] = allPages
    .filter(
      (p) => !p.isAutoGenerated && !p.isCustomPage && !PLAYER_CATEGORIES.has(p.category ?? "")
    )
    .map((p) => ({
      slug: p.slug,
      title: p.title,
      description: p.description,
      href: p.href ?? `/wiki/${p.slug}`,
    }))
    .sort((a, b) => a.title.localeCompare(b.title));

  const categoryPageCounts = new Map<string, number>();
  allPages.forEach((page) => {
    if (page.category) {
      categoryPageCounts.set(page.category, (categoryPageCounts.get(page.category) || 0) + 1);
    }
  });
  if (customPages.length > 0) {
    categoryPageCounts.set("custom-pages", customPages.length);
  }

  const populatedCategories = WIKI_CATEGORIES.filter(
    (category) => (categoryPageCounts.get(category.id) || 0) > 0
  );
  const officialCategories = populatedCategories.filter((c) => !COMMUNITY_CATEGORY_IDS.has(c.id));
  const communityCategories = populatedCategories.filter((c) => COMMUNITY_CATEGORY_IDS.has(c.id));

  return (
    <div className="min-h-screen bg-background pb-12">
      <main className="mx-auto max-w-7xl px-4 sm:px-6 py-8">
        <div className="grid gap-8 lg:grid-cols-[240px_1fr]">
          {/* Left Sidebar */}
          <aside className="hidden lg:block space-y-6">
            <div className="sticky top-20 space-y-6">
              <nav className="space-y-1">
                <h3 className="mb-3 px-3 text-xs font-bold uppercase tracking-wider text-muted">
                  Game Content
                </h3>
                {officialCategories.map((category) => (
                  <Link
                    key={category.id}
                    href={`/wiki/category/${category.slug}`}
                    className="flex items-center gap-3 rounded-md px-3 py-2 text-sm font-medium text-muted transition-colors hover:bg-card-elevated hover:text-foreground"
                  >
                    <span className="flex h-5 w-5 shrink-0 items-center justify-center text-muted">
                      {CATEGORY_ICON_PATHS[category.id] ?? DEFAULT_ICON}
                    </span>
                    <span>{category.name}</span>
                    <span className="ml-auto font-mono text-xs text-muted/50">
                      {categoryPageCounts.get(category.id) || 0}
                    </span>
                  </Link>
                ))}

                {communityCategories.length > 0 && (
                  <>
                    <div className="pt-3 pb-1">
                      <h3 className="px-3 text-xs font-bold uppercase tracking-wider text-muted">
                        Community
                      </h3>
                    </div>
                    {communityCategories.map((category) => (
                      <Link
                        key={category.id}
                        href={`/wiki/category/${category.slug}`}
                        className="flex items-center gap-3 rounded-md px-3 py-2 text-sm font-medium text-muted transition-colors hover:bg-card-elevated hover:text-foreground"
                      >
                        <span className="flex h-5 w-5 shrink-0 items-center justify-center text-muted">
                          {CATEGORY_ICON_PATHS[category.id] ?? DEFAULT_ICON}
                        </span>
                        <span>{category.name}</span>
                        <span className="ml-auto font-mono text-xs text-muted/50">
                          {categoryPageCounts.get(category.id) || 0}
                        </span>
                      </Link>
                    ))}
                  </>
                )}
              </nav>

              <AdSenseUnit slot="ahd-wiki-sidebar" format="auto" className="min-h-[250px]" />
            </div>
          </aside>

          {/* Main Content */}
          <div className="space-y-8">
            {/* Header */}
            <div className="rounded-xl border border-card-border bg-card p-8 shadow-sm">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <p className="section-label mb-3">Documentation</p>
                  <h1 className="mb-2 font-serif text-3xl font-bold tracking-tight text-foreground">
                    Game Wiki
                  </h1>
                </div>
                {user && (
                  <Link
                    href="/wiki/new"
                    className="shrink-0 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
                  >
                    {canPublishDirectly ? "Create page" : "Submit page"}
                  </Link>
                )}
              </div>
              <p className="text-body-lg max-w-3xl text-muted">
                Official documentation for <em>A House Divided</em>. These pages explain how the
                live simulation works — turns, elections, bills, parties, and country-specific
                legislatures across the United States, United Kingdom, Germany, and Japan. Start
                with the new player guide, then browse by category for deeper mechanics, economy
                systems, and strategy.
              </p>
            </div>

            {/* Spotlight */}
            <div className="rounded-xl border border-card-border bg-card p-6 shadow-sm">
              <h2 className="mb-4 font-serif text-base font-bold text-foreground">Spotlight</h2>
              <div className="grid gap-6 sm:grid-cols-2">
                {/* Recently Added */}
                <div>
                  <p className="mb-2 text-xs font-bold uppercase tracking-wider text-muted">
                    Recently Added
                  </p>
                  {recentPages.length > 0 ? (
                    <div className="space-y-0.5">
                      {recentPages.map((page) => (
                        <SpotlightRow key={page.slug} page={page} />
                      ))}
                    </div>
                  ) : (
                    <p className="text-sm text-muted/60">No pages yet.</p>
                  )}
                </div>

                {/* Most Viewed */}
                <div>
                  <p className="mb-2 text-xs font-bold uppercase tracking-wider text-muted">
                    Most Viewed
                  </p>
                  {mostViewedPages.length > 0 ? (
                    <div className="space-y-0.5">
                      {mostViewedPages.map((page) => (
                        <SpotlightRow key={page.slug} page={page} showViews />
                      ))}
                    </div>
                  ) : (
                    <p className="text-sm text-muted/60">
                      View counts will appear here as pages are visited.
                    </p>
                  )}
                </div>
              </div>
            </div>

            {/* Player/Corporation page CTA */}
            <div className="rounded-xl border border-primary/40 bg-primary/5 p-6 shadow-sm">
              <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <p className="section-label mb-1 text-primary">Your pages</p>
                  <h2 className="mb-1 font-serif text-xl font-bold text-foreground">
                    Write a wiki page for yourself or your corporation
                  </h2>
                  <p className="max-w-2xl text-sm text-muted">
                    Use the in-app editor — full markdown, inline image uploads, wiki-style links,
                    and embedded widgets. Perfect for biographies, company histories, and campaign
                    platforms.
                  </p>
                </div>
                <div className="flex flex-wrap gap-2">
                  <Link
                    href="/wiki/my"
                    className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90"
                  >
                    My pages
                  </Link>
                  <Link
                    href="/wiki/new"
                    className="rounded-md border border-primary/40 bg-card px-4 py-2 text-sm font-medium text-foreground hover:bg-muted"
                  >
                    New article
                  </Link>
                </div>
              </div>
            </div>

            {/* Quick Links */}
            <div className="grid gap-4 sm:grid-cols-3">
              <Link
                href="/wiki/getting-started"
                className="group relative rounded-xl border border-card-border bg-card p-5 transition-all hover:-translate-y-px hover:border-primary/40 hover:shadow-md"
              >
                <div className="mb-3 flex h-9 w-9 items-center justify-center rounded-lg bg-primary/10 border border-primary/30 text-primary">
                  <IconBookOpen />
                </div>
                <h3 className="font-semibold text-foreground transition-colors group-hover:text-primary">
                  New Player Guide
                </h3>
                <p className="mt-1 text-sm text-muted">
                  Learn the basics — campaigns, elections, influence, and the turn cycle.
                </p>
              </Link>

              <Link
                href="/wiki/category/elections"
                className="group relative rounded-xl border border-card-border bg-card p-5 transition-all hover:-translate-y-px hover:border-primary/40 hover:shadow-md"
              >
                <div className="mb-3 flex h-9 w-9 items-center justify-center rounded-lg bg-secondary/10 border border-secondary/30 text-secondary">
                  <IconClipboard />
                </div>
                <h3 className="font-semibold text-foreground transition-colors group-hover:text-primary">
                  Election Mechanics
                </h3>
                <p className="mt-1 text-sm text-muted">
                  Primaries, general elections, snap elections, and voter behavior.
                </p>
              </Link>

              <Link
                href="/wiki/category/reference"
                className="group relative rounded-xl border border-card-border bg-card p-5 transition-all hover:-translate-y-px hover:border-primary/40 hover:shadow-md"
              >
                <div className="mb-3 flex h-9 w-9 items-center justify-center rounded-lg bg-card-elevated border border-card-border text-muted">
                  <IconStar />
                </div>
                <h3 className="font-semibold text-foreground transition-colors group-hover:text-primary">
                  Reference
                </h3>
                <p className="mt-1 text-sm text-muted">
                  Formulas, tables, and technical details for advanced play.
                </p>
              </Link>
            </div>

            {/* Browse Topics */}
            <div>
              <h2 className="mb-4 font-serif text-lg font-bold text-foreground border-b border-card-border pb-2">
                Browse Topics
              </h2>
              <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                {officialCategories.map((category) => (
                  <Link
                    key={category.id}
                    href={`/wiki/category/${category.slug}`}
                    className="flex items-start gap-3 rounded-lg border border-card-border bg-card/50 p-3 transition-all hover:-translate-y-px hover:bg-card-elevated hover:border-primary/30"
                  >
                    <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded text-muted mt-0.5">
                      {CATEGORY_ICON_PATHS[category.id] ?? DEFAULT_ICON}
                    </span>
                    <div className="min-w-0">
                      <h3 className="font-semibold text-sm text-foreground truncate">
                        {category.name}
                      </h3>
                      <p className="text-xs text-muted line-clamp-1">{category.description}</p>
                    </div>
                  </Link>
                ))}
              </div>
            </div>

            {/* Full Page Index */}
            <div className="space-y-8">
              <div className="border-b border-card-border pb-2">
                <h2 className="font-serif text-lg font-bold text-foreground">Full Page List</h2>
                <p className="mt-1 text-sm text-muted">
                  Every wiki entry grouped by how it is maintained.
                </p>
              </div>

              <WikiFullListSection
                id="auto-generated-pages"
                hash="#auto-generated-pages"
                title="Auto Generated Pages"
                description="Live pages built from election results, offices, seats, parties, and holder records. Newest first."
                pages={autoGeneratedList}
                state={pageState}
                section="auto"
              />

              <WikiFullListSection
                id="player-pages"
                hash="#player-pages"
                title="Player Pages"
                description="Biographies, corporations, party profiles, events, and other player-authored articles."
                pages={playerList}
                state={pageState}
                section="player"
              />

              <WikiFullListSection
                id="system-pages"
                hash="#system-pages"
                title="System Pages"
                description="Seeded rules, mechanics, reference material, and strategy documentation."
                pages={systemPages}
                state={pageState}
                section="system"
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
