/**
 * SEED INDEPENDENCE — DO NOT DERIVE FROM ANOTHER ERA.
 * Each era seed is self-contained. This file MUST NOT import and transform
 * another era's region data. All values are authored for 2007 directly.
 * Type-only imports are allowed.
 *
 * German Bundesländer for the 2007-default preset (16th Bundestag, the first
 * Merkel CDU/CSU–SPD grand coalition). All 16 states are structurally stable;
 * the era-specific values are 2007 population and ~2007 nominal state GDP
 * (EUR millions; the East still materially poorer mid-convergence).
 * `houseDistricts` (Bundestag Wahlkreise, sum 299) and `stateSenateSeats`
 * (Landtag) are structural and held constant across eras (feed germanyAMS.ts).
 */
import type { State } from "@/lib/db/types";

export const deRegions2007: State[] = [
  // ── Süden ────────────────────────────────────────────────────────────────
  {
    _id: "BW",
    countryId: "DE",
    regionType: "state",
    name: "Baden-Württemberg",
    population: 10_750_000,
    gdp: 394_000,
    houseDistricts: 38,
    stateSenateSeats: 154,
    region: "Süden",
    votingSystem: "fptp",
  },
  {
    _id: "BY",
    countryId: "DE",
    regionType: "state",
    name: "Bayern",
    population: 12_520_000,
    gdp: 487_000,
    houseDistricts: 47,
    stateSenateSeats: 203,
    region: "Süden",
    votingSystem: "fptp",
  },
  // ── Westen ───────────────────────────────────────────────────────────────
  {
    _id: "NW",
    countryId: "DE",
    regionType: "state",
    name: "Nordrhein-Westfalen",
    population: 17_990_000,
    gdp: 526_000,
    houseDistricts: 64,
    stateSenateSeats: 195,
    region: "Westen",
    votingSystem: "fptp",
  },
  {
    _id: "HE",
    countryId: "DE",
    regionType: "state",
    name: "Hessen",
    population: 6_070_000,
    gdp: 218_000,
    houseDistricts: 22,
    stateSenateSeats: 137,
    region: "Westen",
    votingSystem: "fptp",
  },
  {
    _id: "RP",
    countryId: "DE",
    regionType: "state",
    name: "Rheinland-Pfalz",
    population: 4_050_000,
    gdp: 116_000,
    houseDistricts: 15,
    stateSenateSeats: 101,
    region: "Westen",
    votingSystem: "fptp",
  },
  {
    _id: "SL",
    countryId: "DE",
    regionType: "state",
    name: "Saarland",
    population: 1_040_000,
    gdp: 25_000,
    houseDistricts: 4,
    stateSenateSeats: 51,
    region: "Westen",
    votingSystem: "fptp",
  },
  // ── Norden ───────────────────────────────────────────────────────────────
  {
    _id: "NI",
    countryId: "DE",
    regionType: "state",
    name: "Niedersachsen",
    population: 7_980_000,
    gdp: 235_000,
    houseDistricts: 30,
    stateSenateSeats: 146,
    region: "Norden",
    votingSystem: "fptp",
  },
  {
    _id: "SH",
    countryId: "DE",
    regionType: "state",
    name: "Schleswig-Holstein",
    population: 2_840_000,
    gdp: 73_000,
    houseDistricts: 11,
    stateSenateSeats: 73,
    region: "Norden",
    votingSystem: "fptp",
  },
  {
    _id: "HH",
    countryId: "DE",
    regionType: "state",
    name: "Hamburg",
    population: 1_770_000,
    gdp: 97_000,
    houseDistricts: 6,
    stateSenateSeats: 123,
    region: "Norden",
    votingSystem: "fptp",
  },
  {
    _id: "BRE",
    countryId: "DE",
    regionType: "state",
    name: "Bremen",
    population: 660_000,
    gdp: 24_000,
    houseDistricts: 2,
    stateSenateSeats: 87,
    region: "Norden",
    votingSystem: "fptp",
  },
  // ── Osten ────────────────────────────────────────────────────────────────
  {
    _id: "BE",
    countryId: "DE",
    regionType: "state",
    name: "Berlin",
    population: 3_420_000,
    gdp: 122_000,
    houseDistricts: 12,
    stateSenateSeats: 159,
    region: "Osten",
    votingSystem: "fptp",
  },
  {
    _id: "BB",
    countryId: "DE",
    regionType: "state",
    name: "Brandenburg",
    population: 2_540_000,
    gdp: 43_000,
    houseDistricts: 10,
    stateSenateSeats: 88,
    region: "Osten",
    votingSystem: "fptp",
  },
  {
    _id: "MV",
    countryId: "DE",
    regionType: "state",
    name: "Mecklenburg-Vorpommern",
    population: 1_680_000,
    gdp: 26_000,
    houseDistricts: 6,
    stateSenateSeats: 79,
    region: "Osten",
    votingSystem: "fptp",
  },
  {
    _id: "SN",
    countryId: "DE",
    regionType: "state",
    name: "Sachsen",
    population: 4_220_000,
    gdp: 73_000,
    houseDistricts: 16,
    stateSenateSeats: 120,
    region: "Osten",
    votingSystem: "fptp",
  },
  {
    _id: "ST",
    countryId: "DE",
    regionType: "state",
    name: "Sachsen-Anhalt",
    population: 2_410_000,
    gdp: 37_000,
    houseDistricts: 8,
    stateSenateSeats: 97,
    region: "Osten",
    votingSystem: "fptp",
  },
  {
    _id: "TH",
    countryId: "DE",
    regionType: "state",
    name: "Thüringen",
    population: 2_310_000,
    gdp: 34_000,
    houseDistricts: 8,
    stateSenateSeats: 88,
    region: "Osten",
    votingSystem: "fptp",
  },
];

export default deRegions2007;
