import type { State } from "@/lib/db/types";

/**
 * German Bundesländer, 1991 post-reunification snapshot.
 *
 * Population: 1991 mid-year Land population estimates (Destatis).
 * GDP: 1991 Land GDP in millions of DM (treated as game-EUR-equivalent for
 *   consistency with the modern bundle's currency).
 *   Source: Statistische Ämter des Bundes und der Länder, Volkswirtschaftliche
 *   Gesamtrechnungen 1991 (eastern Länder shown as separate units post-3-Oct-1990).
 * Bundestag Wahlkreise: 1990 allocation (328 direct mandates expanded by the
 *   then-applied list overhang). Modern 299-seat allocation used here for game
 *   consistency.
 * stateSenateSeats: Landtag seat counts as of late-1990/1991 elections.
 *   Eastern Länder reconstituted Oct 1990; new Landtag sessions seated.
 */
export const deRegions1991: State[] = [
  {
    _id: "BW",
    countryId: "DE",
    regionType: "state",
    name: "Baden-Württemberg",
    population: 9_822_000,
    gdp: 240_000,
    houseDistricts: 38,
    stateSenateSeats: 146, // 1988 Landtag
    region: "Süden",
    votingSystem: "fptp",
  },
  {
    _id: "BY",
    countryId: "DE",
    regionType: "state",
    name: "Bayern",
    population: 11_449_000,
    gdp: 230_000,
    houseDistricts: 47,
    stateSenateSeats: 204,
    region: "Süden",
    votingSystem: "fptp",
  },
  {
    _id: "NW",
    countryId: "DE",
    regionType: "state",
    name: "Nordrhein-Westfalen",
    population: 17_400_000,
    gdp: 350_000,
    houseDistricts: 64,
    stateSenateSeats: 201,
    region: "Westen",
    votingSystem: "fptp",
  },
  {
    _id: "HE",
    countryId: "DE",
    regionType: "state",
    name: "Hessen",
    population: 5_792_000,
    gdp: 140_000,
    houseDistricts: 22,
    stateSenateSeats: 110,
    region: "Westen",
    votingSystem: "fptp",
  },
  {
    _id: "RP",
    countryId: "DE",
    regionType: "state",
    name: "Rheinland-Pfalz",
    population: 3_763_000,
    gdp: 75_000,
    houseDistricts: 15,
    stateSenateSeats: 101,
    region: "Westen",
    votingSystem: "fptp",
  },
  {
    _id: "SL",
    countryId: "DE",
    regionType: "state",
    name: "Saarland",
    population: 1_073_000,
    gdp: 20_000,
    houseDistricts: 4,
    stateSenateSeats: 51,
    region: "Westen",
    votingSystem: "fptp",
  },
  {
    _id: "NI",
    countryId: "DE",
    regionType: "state",
    name: "Niedersachsen",
    population: 7_388_000,
    gdp: 130_000,
    houseDistricts: 30,
    stateSenateSeats: 155,
    region: "Norden",
    votingSystem: "fptp",
  },
  {
    _id: "SH",
    countryId: "DE",
    regionType: "state",
    name: "Schleswig-Holstein",
    population: 2_626_000,
    gdp: 50_000,
    houseDistricts: 11,
    stateSenateSeats: 89,
    region: "Norden",
    votingSystem: "fptp",
  },
  {
    _id: "HH",
    countryId: "DE",
    regionType: "state",
    name: "Hamburg",
    population: 1_661_000,
    gdp: 50_000,
    houseDistricts: 6,
    stateSenateSeats: 121,
    region: "Norden",
    votingSystem: "fptp",
  },
  {
    _id: "BRE",
    countryId: "DE",
    regionType: "state",
    name: "Bremen",
    population: 685_000,
    gdp: 19_000,
    houseDistricts: 3,
    stateSenateSeats: 100,
    region: "Norden",
    votingSystem: "fptp",
  },
  {
    _id: "BE",
    countryId: "DE",
    regionType: "state",
    name: "Berlin",
    population: 3_433_000, // reunified Berlin Dec 1990
    gdp: 60_000,
    houseDistricts: 12,
    stateSenateSeats: 200, // 1990 reunified Abgeordnetenhaus
    region: "Osten",
    votingSystem: "fptp",
  },
  {
    _id: "BB",
    countryId: "DE",
    regionType: "state",
    name: "Brandenburg",
    population: 2_578_000,
    gdp: 18_000,
    houseDistricts: 10,
    stateSenateSeats: 88, // 1990 Landtag
    region: "Osten",
    votingSystem: "fptp",
  },
  {
    _id: "MV",
    countryId: "DE",
    regionType: "state",
    name: "Mecklenburg-Vorpommern",
    population: 1_924_000,
    gdp: 12_000,
    houseDistricts: 7,
    stateSenateSeats: 66,
    region: "Osten",
    votingSystem: "fptp",
  },
  {
    _id: "SN",
    countryId: "DE",
    regionType: "state",
    name: "Sachsen",
    population: 4_771_000,
    gdp: 30_000,
    houseDistricts: 17,
    stateSenateSeats: 160,
    region: "Osten",
    votingSystem: "fptp",
  },
  {
    _id: "ST",
    countryId: "DE",
    regionType: "state",
    name: "Sachsen-Anhalt",
    population: 2_873_000,
    gdp: 18_000,
    houseDistricts: 10,
    stateSenateSeats: 106,
    region: "Osten",
    votingSystem: "fptp",
  },
  {
    _id: "TH",
    countryId: "DE",
    regionType: "state",
    name: "Thüringen",
    population: 2_611_000,
    gdp: 16_000,
    houseDistricts: 9,
    stateSenateSeats: 89,
    region: "Osten",
    votingSystem: "fptp",
  },
];
