/**
 * Category groups for the cabinet-office position rail. Kept as a standalone
 * positionId → group map (rather than a field on the per-country position
 * arrays) so the arrays keep inferring their literal `CabinetPositionId` types
 * and to avoid an import cycle with cabinetMechanics. Mirrors the grouping in
 * the "Cabinet Office" design prototype.
 */
export type CabinetGroup =
  "Centre" | "Economy" | "Security & Foreign" | "Society" | "Domestic" | "Nations";

const GROUPS: Record<string, Record<string, CabinetGroup>> = {
  US: {
    secretary_of_state: "Security & Foreign",
    secretary_of_defense: "Security & Foreign",
    attorney_general: "Security & Foreign",
    secretary_of_homeland: "Security & Foreign",
    secretary_of_treasury: "Economy",
    secretary_of_commerce: "Economy",
    secretary_of_labor: "Economy",
    secretary_of_agriculture: "Economy",
    secretary_of_health: "Society",
    secretary_of_education: "Society",
    secretary_of_hud: "Society",
    secretary_of_veterans: "Society",
    secretary_of_energy: "Domestic",
    secretary_of_interior: "Domestic",
    secretary_of_transportation: "Domestic",
  },
  UK: {
    deputy_prime_minister: "Centre",
    first_secretary_of_state: "Centre",
    chancellor: "Economy",
    business_secretary: "Economy",
    work_secretary: "Economy",
    foreign_secretary: "Security & Foreign",
    home_secretary: "Security & Foreign",
    defence_secretary: "Security & Foreign",
    justice_secretary: "Security & Foreign",
    health_secretary: "Society",
    education_secretary: "Society",
    levelling_secretary: "Society",
    transport_secretary: "Domestic",
    agriculture_secretary: "Domestic",
    environment_secretary: "Domestic",
    northern_ireland: "Nations",
    scotland: "Nations",
    wales: "Nations",
  },
  JP: {
    chief_cabinet_secretary: "Centre",
    finance_minister: "Economy",
    economy_minister: "Economy",
    foreign_affairs_minister: "Security & Foreign",
    justice_minister: "Security & Foreign",
    defense_minister: "Security & Foreign",
    health_minister: "Society",
    education_minister: "Society",
    land_minister: "Domestic",
    environment_minister: "Domestic",
    internal_affairs_minister: "Domestic",
  },
  IE: {
    taoiseach: "Centre",
    tanaiste: "Centre",
    minister_for_finance: "Economy",
    minister_for_public_expenditure: "Economy",
    minister_for_enterprise: "Economy",
    minister_for_social_protection: "Economy",
    minister_for_agriculture: "Economy",
    minister_for_foreign_affairs: "Security & Foreign",
    minister_for_justice: "Security & Foreign",
    minister_for_defence: "Security & Foreign",
    minister_for_health: "Society",
    minister_for_education: "Society",
    minister_for_further_higher_education: "Society",
    minister_for_housing: "Society",
    minister_for_children: "Society",
    minister_for_tourism_culture: "Society",
    minister_for_environment_climate: "Domestic",
    minister_for_transport: "Domestic",
    minister_for_rural_community: "Domestic",
  },
  DE: {
    finance_minister: "Economy",
    economy_minister: "Economy",
    labour_minister: "Economy",
    foreign_minister: "Security & Foreign",
    interior_minister: "Security & Foreign",
    defense_minister: "Security & Foreign",
    justice_minister: "Security & Foreign",
    health_minister: "Society",
    education_minister: "Society",
    transport_minister: "Domestic",
    environment_minister: "Domestic",
  },
  CN: {
    premier: "Centre",
    vice_premier: "Centre",
    state_councillor: "Centre",
    minister_of_finance: "Economy",
    pboc_governor: "Economy",
    minister_of_commerce: "Economy",
    minister_of_human_resources_social_security: "Economy",
    minister_of_agriculture_rural_affairs: "Economy",
    minister_of_foreign_affairs: "Security & Foreign",
    minister_of_defense: "Security & Foreign",
    minister_of_public_security: "Security & Foreign",
    minister_of_education: "Society",
    minister_of_health: "Society",
    minister_of_housing_urban_rural: "Society",
    minister_of_ecology_environment: "Domestic",
    minister_of_transport: "Domestic",
  },
  RU: {
    premier: "Centre",
    first_deputy_premier: "Centre",
    chairman_of_gosplan: "Centre",
    minister_of_finance: "Economy",
    gosbank_liaison: "Economy",
    minister_of_foreign_trade: "Economy",
    minister_of_internal_trade: "Economy",
    minister_of_agriculture: "Economy",
    minister_of_machine_building: "Economy",
    minister_of_foreign_affairs: "Security & Foreign",
    minister_of_defence: "Security & Foreign",
    minister_of_internal_affairs: "Security & Foreign",
    minister_of_culture: "Society",
    minister_of_health: "Society",
    minister_of_higher_education: "Society",
    minister_of_railways: "Domestic",
  },
  NG: {
    secretary_to_government: "Centre",
    minister_of_finance: "Economy",
    minister_of_petroleum_resources: "Economy",
    minister_of_power: "Economy",
    minister_of_trade_industry: "Economy",
    minister_of_labour: "Economy",
    minister_of_agriculture: "Economy",
    minister_of_defence: "Security & Foreign",
    minister_of_foreign_affairs: "Security & Foreign",
    minister_of_interior: "Security & Foreign",
    minister_of_justice: "Security & Foreign",
    minister_of_health: "Society",
    minister_of_education: "Society",
    minister_of_works_housing: "Society",
    minister_of_information: "Society",
    minister_of_environment: "Domestic",
  },
};

export function getCabinetPositionGroup(countryId: string, positionId: string): CabinetGroup {
  return GROUPS[countryId]?.[positionId] ?? "Centre";
}
