import type { PartySeed } from "@/lib/seeds/reference/politicalParties";

/**
 * Italy default political parties (First Republic).
 * The five pillars — DC, PCI, PSI, MSI, PRI — all existed by 1953 and remain
 * the core landscape through the historic-compromise era of 1979 and into
 * the last pentapartito parliament of 1991 (the First Republic held until
 * the 1992-94 Tangentopoli collapse). Gated to all three presets.
 * Positions -5..+5.
 */
export const itParties: PartySeed[] = [
  {
    seedOrder: 1,
    countryId: "IT",
    name: "Democrazia Cristiana",
    abbreviation: "DC",
    color: "#FFFFFF",
    economicPosition: 1,
    socialPosition: 2,
    foreignPolicy: 1,
    culture: 2,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default", "1979-default", "1991-default"],
    regimeStatus: "approved",
    treasury: 900_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 2,
    countryId: "IT",
    name: "Partito Comunista Italiano",
    abbreviation: "PCI",
    color: "#CC0000",
    economicPosition: -4,
    socialPosition: -1,
    foreignPolicy: -1,
    culture: -1,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default", "1979-default", "1991-default"],
    regimeStatus: "approved",
    treasury: 850_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 3,
    countryId: "IT",
    name: "Partito Socialista Italiano",
    abbreviation: "PSI",
    color: "#FF3366",
    economicPosition: -2,
    socialPosition: -1,
    foreignPolicy: 0,
    culture: -1,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default", "1979-default", "1991-default"],
    regimeStatus: "approved",
    treasury: 600_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 4,
    countryId: "IT",
    name: "Movimento Sociale Italiano",
    abbreviation: "MSI",
    color: "#1A1A6E",
    economicPosition: 2,
    socialPosition: 4,
    foreignPolicy: 1,
    culture: 4,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default", "1979-default", "1991-default"],
    regimeStatus: "approved",
    treasury: 400_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 5,
    countryId: "IT",
    name: "Partito Repubblicano Italiano",
    abbreviation: "PRI",
    color: "#1E90FF",
    economicPosition: 1,
    socialPosition: -1,
    foreignPolicy: 1,
    culture: -1,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default", "1979-default", "1991-default"],
    regimeStatus: "approved",
    treasury: 350_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
];

export default itParties;
