import { writeFileSync } from "node:fs";
import { quotePropForexFee } from "../../src/lib/banking/rules/propForexFees";

const rows = [1_000_000, 100_000_000, 10_000_000_000, 100_000_000_000].map((markLocal) => {
  const quote = quotePropForexFee({
    markLocal,
    currencyCode: "USD",
    homeRate: 1,
    priorAnchor: 0,
    homeVolumeAnchor: 1_000_000_000,
    foreignVolumeAnchor: 1_000_000_000,
  });
  return `| ${markLocal.toLocaleString("en-US")} | ${(quote.feeRate * 100).toFixed(3)}% | ${quote.feeLocal.toFixed(2)} | ${quote.revenueLocal.toFixed(2)} | ${quote.reserveLocal.toFixed(2)} | ${quote.burnLocal.toFixed(2)} |`;
});
writeFileSync(
  "scripts/sim/reports/bank-prop-forex-fees.md",
  `# Bank forex fee qualification

Generated by \`npx tsx scripts/sim/bank-prop-forex-fees.ts\` using the production forex size/liquidity curve and currency rounding. Fees reduce cash equity immediately; marked position value excludes fees. Both buys and sells contribute to the bank's 24-turn anchor-volume lookback. The fee revenue and reserve shares reach the bank's home-currency central bank from guarded escrow; the remainder is the published fee burn.

| Gross USD value | Fee rate | Fee USD | CB revenue USD | Currency reserve USD | Burn USD |
| ---: | ---: | ---: | ---: | ---: | ---: |
${rows.join("\n")}

These are quotes, not permissions to trade these amounts: per-currency forex caps and leverage still refuse an over-sized position. Splitting a fixed large volume gives the same size fee within minor-unit rounding. Prices and liquidity are held fixed for this deterministic report. No world simulation or production turn was run.
`
);
