#!/usr/bin/env bash
#
# One-command setup for running the headless world sim on your OWN machine.
#
# What it does, in order:
#   1. checks prerequisites (node, and either docker or a native mongod)
#   2. starts a sandbox MongoDB on port 27018 — isolated, nothing to do with
#      the live game
#   3. writes .env.sim.local  (config for the worker)
#   4. registers the local worldsim MCP in .mcp.json  (config for Claude Code)
#
# It is safe to re-run: every step checks before it acts, and the .mcp.json
# edit merges rather than overwrites.
#
# Usage:  npm run sim:setup
#
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_DIR"

PORT="${SIM_MONGO_PORT:-27018}"
CONTAINER="ahd-sim-mongo"
ENV_FILE="$REPO_DIR/.env.sim.local"
MCP_FILE="$REPO_DIR/.mcp.json"

say()  { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
ok()   { printf '    \033[1;32mok\033[0m  %s\n' "$*"; }
warn() { printf '    \033[1;33m!\033[0m   %s\n' "$*"; }
die()  { printf '\n\033[1;31mx   %s\033[0m\n\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
say "1/4  Checking prerequisites"

command -v node >/dev/null 2>&1 || die "node is not installed. Install Node 20+ and re-run."
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
[ "$NODE_MAJOR" -ge 20 ] || die "node $NODE_MAJOR is too old — this repo needs Node 20 or newer."
ok "node $(node -v)"

[ -d "$REPO_DIR/node_modules" ] || die "Dependencies are not installed. Run:  npm install"
ok "node_modules present"

MONGO_MODE=""
if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
  MONGO_MODE="docker"; ok "docker is available (will run mongo in a container)"
elif command -v mongod >/dev/null 2>&1; then
  MONGO_MODE="native"; ok "native mongod is available"
else
  die "Neither docker nor mongod found. Install Docker Desktop (easiest) or MongoDB Community, then re-run."
fi

# ---------------------------------------------------------------------------
say "2/4  Starting the sandbox MongoDB on port $PORT"

# A plain standalone mongod is deliberate and sufficient: the sim never opens a
# multi-document transaction, so there is no reason to make a laptop run a
# single-node replica set. This mirrors the ops box, which runs the sandbox the
# same way.
mongo_is_up() {
  if command -v mongosh >/dev/null 2>&1; then
    mongosh "mongodb://127.0.0.1:$PORT" --quiet --eval 'db.runCommand({ping:1})' >/dev/null 2>&1
  else
    # No mongosh on the host (normal when mongo runs in docker): a TCP connect
    # is enough to know something is listening.
    node -e "
      const net=require('net');const s=net.connect($PORT,'127.0.0.1');
      s.on('connect',()=>{s.end();process.exit(0)});
      s.on('error',()=>process.exit(1));
      setTimeout(()=>process.exit(1),2000);
    " >/dev/null 2>&1
  fi
}

if mongo_is_up; then
  ok "something is already listening on $PORT — reusing it"
elif [ "$MONGO_MODE" = "docker" ]; then
  if docker ps -a --format '{{.Names}}' | grep -qx "$CONTAINER"; then
    docker start "$CONTAINER" >/dev/null
    ok "restarted existing container $CONTAINER"
  else
    docker run -d --name "$CONTAINER" \
      -p "127.0.0.1:$PORT:$PORT" \
      -v ahd-sim-mongo-data:/data/db \
      mongo:7 --port "$PORT" --bind_ip_all --wiredTigerCacheSizeGB 1 >/dev/null
    ok "created container $CONTAINER (named volume ahd-sim-mongo-data)"
  fi
  # The container is up before mongod inside it is ready to answer.
  for _ in $(seq 1 30); do mongo_is_up && break; sleep 1; done
  mongo_is_up || die "mongo container started but never answered on $PORT. Check: docker logs $CONTAINER"
else
  DATA_DIR="$REPO_DIR/.sim-mongo/data"
  mkdir -p "$DATA_DIR"
  mongod --dbpath "$DATA_DIR" --port "$PORT" --bind_ip 127.0.0.1 \
    --wiredTigerCacheSizeGB 1 --fork --logpath "$REPO_DIR/.sim-mongo/mongod.log"
  ok "started native mongod (data in .sim-mongo/data)"
fi
ok "sandbox mongo listening on 127.0.0.1:$PORT"

# ---------------------------------------------------------------------------
say "3/4  Writing $ENV_FILE"

# One mongod serves both roles here: the sim_control db holds the job queue,
# the ahd_sim_* dbs hold the worlds. On the ops box those are separate servers
# and worker.ts refuses to start when the two URIs match — SIM_ALLOW_SHARED_MONGO
# is the explicit local opt-out. It is safe here only because nothing on this
# machine can reach production.
cat > "$ENV_FILE" <<EOF
# Generated by scripts/sim/local-setup.sh — safe to edit, safe to delete and regenerate.
# LOCAL SANDBOX ONLY. Never point any of these at a production database.
OPS_MONGODB_URI=mongodb://127.0.0.1:$PORT
OPS_DB_NAME=sim_control
SIM_MONGODB_URI=mongodb://127.0.0.1:$PORT
SIM_ALLOW_SHARED_MONGO=1
GAME_REPO_DIR=$REPO_DIR
EOF
ok "wrote control-plane + sandbox config"

if ! grep -qxF '.env.sim.local' "$REPO_DIR/.gitignore" 2>/dev/null; then
  printf '\n# local headless-sim config (scripts/sim/local-setup.sh)\n.env.sim.local\n.sim-mongo/\n' >> "$REPO_DIR/.gitignore"
  ok "added .env.sim.local and .sim-mongo/ to .gitignore"
fi

# ---------------------------------------------------------------------------
say "4/4  Registering the local worldsim MCP in .mcp.json"

# Merged with node rather than overwritten: .mcp.json may already carry other
# servers, and clobbering someone's MCP config to add one entry is rude.
node - "$MCP_FILE" "$REPO_DIR" "$PORT" <<'NODE'
const fs = require("fs");
const [file, repo, port] = process.argv.slice(2);
let cfg = {};
if (fs.existsSync(file)) {
  try {
    cfg = JSON.parse(fs.readFileSync(file, "utf8"));
  } catch {
    console.error("    !   .mcp.json exists but is not valid JSON — leaving it alone.");
    console.error("        Add this server manually:  local-worldsim");
    process.exit(0);
  }
}
cfg.mcpServers = cfg.mcpServers || {};
cfg.mcpServers["local-worldsim"] = {
  command: "npx",
  args: ["tsx", "scripts/sim/localWorldsimMcp.ts"],
  cwd: repo,
  env: { SIM_CONTROL_URI: `mongodb://127.0.0.1:${port}`, SIM_CONTROL_DB: "sim_control" },
};
fs.writeFileSync(file, JSON.stringify(cfg, null, 2) + "\n");
console.log("    ok  local-worldsim registered");
NODE

# ---------------------------------------------------------------------------
cat <<EOF

$(printf '\033[1;32mSetup complete.\033[0m')

Two things need to be running, and they are different:

  1. The WORKER — does the actual simulating. Start it in its own terminal
     and leave it open:

         npm run sim:worker

  2. Claude Code — picks up the MCP from .mcp.json when it starts. If it is
     already open, restart it, then check the tools are there:

         /mcp

Then just ask Claude, in plain English:

     "Run a 1953 world sim, 200 turns, seed mytest, market mode capital,
      autonomy v4. Tell me when it's done."

Notes:
  * The worker runs ONE job at a time. A second run waits its turn.
  * A few hundred turns can take hours. You can close Claude Code; the worker
    keeps going. You cannot close the worker.
  * Nothing here touches the live game. It is a separate database on your own
    machine.

EOF
