import { tickManufacturingProject } from "../../src/lib/products/rules/manufacturingRules";
import type { ManufacturingLifecycleStage } from "../../src/lib/products/rules/manufacturingRules";

function lifecycle(paidAnchor: number) {
  let project = {
    _id: "report-product",
    stage: "development" as ManufacturingLifecycleStage,
    stageStartedTurn: 1,
    startedTurn: 1,
    lastProcessedTurn: 0,
    lastDevelopmentReceiptTurn: 0,
    developmentPaidAnchor: paidAnchor,
    paidThresholdAnchor: 1000,
    elapsedDevelopmentTurns: 0,
    elapsedThresholdTurns: 12,
  };
  const transitions: { turn: number; stage: ManufacturingLifecycleStage; paidAnchor: number }[] =
    [];
  for (let completedTurn = 1; completedTurn <= 260; completedTurn++) {
    const progress = tickManufacturingProject({ project, completedTurn });
    if (!progress) throw new Error("Expected completed-turn progress");
    if (progress.stage !== project.stage)
      transitions.push({
        turn: completedTurn,
        stage: progress.stage,
        paidAnchor: progress.developmentPaidAnchor,
      });
    project = { ...project, ...progress };
    if (tickManufacturingProject({ project, completedTurn }) !== null)
      throw new Error("Repeated completed turn advanced twice");
    if (project.stage === "retired") break;
  }
  return { project, transitions };
}

const funded = lifecycle(1000);
const unfunded = lifecycle(0);
const lines = [
  "# Manufacturing lifecycle clock report",
  "",
  "Generated by scripts/sim/manufacturingLifecycleClockReport.ts using the production completed-turn lifecycle rules. No database or world simulation is used.",
  "",
  "The project begins with its 1,000-anchor development cost already paid and requires 12 completed development turns. No additional cash receipts or debits occur during this report. Repeated calls for each completed turn must be neutral.",
  "",
  "<!-- prettier-ignore -->",
  "| Completed turn | Stage entered | Total paid development (anchor) |",
  "| --- | --- | ---: |",
  ...funded.transitions.map((row) => `| ${row.turn} | ${row.stage} | ${row.paidAnchor} |`),
  "",
  `Unfunded control after 260 completed turns: ${unfunded.project.stage}, paid development ${unfunded.project.developmentPaidAnchor} anchor. Passing time alone never fulfills the monetary requirement.`,
  "",
  "The live persistence adapter now feeds these zero-cash completed turns into the same rule. Integration tests separately exercise actual project writes, delayed paid receipts, concurrent writes, retirement slot release and crash recovery between project acknowledgment and cash receipt removal.",
  "",
];
process.stdout.write(lines.join("\n"));
