import { mkdirSync, writeFileSync } from "node:fs";
import {
  bankingSeparationDefault,
  bankingWorldYear,
  playerInvestmentBankingSeedFlags,
} from "../../src/lib/banking/rules/charterAccess";
import { getEraUnitScale } from "../../src/lib/constants/sectorSeedEra";
import { TURNS_PER_YEAR } from "../../src/lib/constants/turnTime";
import { computePropEquityBase } from "../../src/lib/banking/rules/propLeverage";

const rows = [1991, 1998, 1999, 2001].map((year) => {
  const state = { preset: "1991-default", currentTurn: 1 + (year - 1991) * TURNS_PER_YEAR };
  const separation = bankingSeparationDefault({
    countryId: "US",
    year: bankingWorldYear(state),
    eraUnitScale: getEraUnitScale(state.preset),
  });
  return `| ${year} | ${state.currentTurn} | ${separation} | ${separation === "separated" ? "retail, investment" : "retail, investment, universal"} |`;
});
const flags = playerInvestmentBankingSeedFlags(1991);
const equityExample = {
  totalLoans: 80_000,
  propBookMarkValue: 90_000,
  npcDeposits: 100_000,
  playerDeposits: 80_000,
  interbankDebt: 20_000,
  cbMarginDebt: 10_000,
  discountWindowDebt: 40_000,
  discountWindowArrears: 3_000,
  cbMarginArrears: 2_000,
};
const pointerEquity = computePropEquityBase(150_000, equityExample);
const authoritativeEquity = computePropEquityBase(150_000, equityExample, undefined, {
  playerDepositsAreLiabilities: true,
});
mkdirSync("scripts/sim/reports", { recursive: true });
writeFileSync(
  "scripts/sim/reports/player-investment-banking-access.md",
  `# Player investment banking access

Generated by \`npx tsx scripts/sim/player-investment-banking-access.ts\` using the production charter-access rules. A legacy 1991 save without a maintained year still advances its US separation default from the live turn. An enacted law overrides the default in the runtime resolver.

| Live year | Turn in a 1991 world | US default | Legal charter types with access enabled |
| ---: | ---: | --- | --- |
${rows.join("\n")}

Fresh/reset 1991 flags: \`${JSON.stringify(flags)}\`. Existing top-ups preserve all four existing settings, including absent and explicitly disabled flags. Other preset inserts retain their previous defaults.

The existing CEO conversion returns deposits through the funded deposit waterfall and keeps posted capital and the original loan epoch. Forex trading retains the per-currency cap and leverage on equity net of liabilities; its fee curve and recovery qualification are documented in \`bank-prop-forex-fees.md\`.

The risk limit uses the shared bank balance sheet plus marked prop assets. In a worked example with 150,000 cash, 80,000 funded loans, 90,000 prop marks, 100,000 NPC deposits and 75,000 total borrowing obligations, equity is ${pointerEquity.toLocaleString("en-US")} with 80,000 player pointer savings and ${authoritativeEquity.toLocaleString("en-US")} when those same 80,000 are authoritative cash-backed deposits. Posted capital adds no second cash asset. Flat-mark sales preserve equity while reducing marked risk assets. Corporations carry no central-bank savings asset.

No world simulation or production turn was run.
`
);
