import type { Db } from "mongodb";
import { COUNTRY_CONFIGS } from "@/lib/constants/countries";
import type {
  Crisis,
  CrisisDecisionNode,
  CrisisTemplate,
  GlobalResponseRole,
} from "@/lib/db/types/crisis";
import { createCrisisFromTemplate } from "@/lib/crises/createCrisisFromTemplate";
import { logWireEvent } from "@/lib/wireEvent";
import { allLivingConflictDefs } from "./registry";
import { loadConflictState } from "./driver";
import { normalizeCampaignState } from "./campaign";
import { migrateLegacyVietnamState } from "./vietnamCompat";
import {
  allParticipants,
  driveConflictTurn,
  type ConflictParticipants,
  type DrivenEvent,
} from "./driver";

function roleMapForEvent(
  def: ReturnType<typeof allLivingConflictDefs>[number],
  participants: ConflictParticipants,
  driven: DrivenEvent
): Record<string, GlobalResponseRole> {
  const playable = new Set(Object.keys(COUNTRY_CONFIGS));
  const affected = new Set(driven.affectedNations);
  const roleByCountry: Record<string, GlobalResponseRole> = {};
  for (const countryId of allParticipants(participants)) {
    if (!playable.has(countryId) || !affected.has(countryId)) continue;
    const role = def.roleResolver({ countryId, ...participants });
    if (!driven.fired.event.response?.decisionTrees[role]) continue;
    roleByCountry[countryId] = role;
  }
  return roleByCountry;
}

function responseNode(driven: DrivenEvent): CrisisDecisionNode {
  const response = driven.fired.event.response!;
  const optionsByRole = Object.fromEntries(
    Object.entries(response.decisionTrees).map(([role, node]) => [role, node?.options ?? []])
  );
  return {
    nodeId: `${driven.fired.event.key}_global_response`,
    type: "choice",
    title: driven.fired.event.headline,
    description: driven.fired.event.body,
    options: [],
    optionsByRole,
    requiredRoles: ["headOfState"],
    timeLimitMinutes: response.windowTurns * 60,
  };
}

function eventTemplate(driven: DrivenEvent, countryIds: string[]): CrisisTemplate {
  const event = driven.fired.event;
  const windowTurns = event.response?.windowTurns ?? 1;
  return {
    name: event.headline,
    description: event.body,
    scope: "country",
    countryIds,
    regionIds: [],
    durationTurns: windowTurns,
    durationByScope: { country: windowTurns },
    effects: [],
    wireMessageOnStart: event.headline,
    wireMessageOnEnd: `The international response window for ${event.headline.toLowerCase()} has closed.`,
    autoGenerated: true,
    interactionDefinition: event.response
      ? { decisionTree: [responseNode(driven)], autoResolveOnExpiry: true }
      : undefined,
  };
}

async function materializeEvent(
  db: Db,
  def: ReturnType<typeof allLivingConflictDefs>[number],
  participants: ConflictParticipants,
  driven: DrivenEvent,
  currentTurn: number
): Promise<boolean> {
  const existing = await db
    .collection<Crisis>("crises")
    .findOne({ livingConflictEventId: driven.fired.id }, { projection: { _id: 1 } });
  if (existing) return false;
  const activeWindow = await db
    .collection<Crisis>("crises")
    .findOne(
      { "globalResponse.conflictKey": def.key, status: "active" },
      { projection: { _id: 1, startTurn: 1, durationTurns: 1 } }
    );
  // Crisis lifecycle closure happens later in the same turn. Do not let a
  // response whose authored duration ends now suppress the next cadence event.
  const activeWindowExpiresAfterThisTurn =
    activeWindow &&
    (activeWindow.durationTurns === null ||
      currentTurn < activeWindow.startTurn + activeWindow.durationTurns);
  if (activeWindowExpiresAfterThisTurn) return false;

  const response = driven.fired.event.response;
  if (!response) {
    await logWireEvent("crisis_start", driven.fired.event.headline);
    return true;
  }
  const roleByCountry = roleMapForEvent(def, participants, driven);
  const countryIds = Object.keys(roleByCountry);
  if (countryIds.length === 0) return false;
  const campaign = normalizeCampaignState((await loadConflictState(db, def.key)).campaign);

  await createCrisisFromTemplate(db, {
    template: eventTemplate(driven, countryIds),
    scope: "country",
    countryIds,
    regionIds: [],
    currentTurn,
    autoSource: "condition",
    livingConflictEventId: driven.fired.id,
    globalResponse: {
      conflictKey: def.key,
      eventKey: driven.fired.event.key,
      roleByCountry,
      defaultOptionIdByRole: response.defaultOptionIdByRole,
      outcomes: response.outcomes,
      defaultOutcomeId: response.defaultOutcomeId,
      campaign: {
        stage: campaign.stage,
        cycle: campaign.cycle,
        consequences: { ...campaign.consequences },
      },
    },
  });
  return true;
}

export interface LivingConflictTurnResult {
  conflictsProcessed: number;
  eventsOpened: number;
}

/** Advance and materialize every 1.3 living conflict for one turn. */
export async function processLivingConflictsTurn(
  db: Db,
  currentTurn: number,
  currentYear: number | null | undefined,
  enabled: boolean
): Promise<LivingConflictTurnResult> {
  if (!enabled) return { conflictsProcessed: 0, eventsOpened: 0 };
  await migrateLegacyVietnamState(db);
  let eventsOpened = 0;
  const defs = allLivingConflictDefs().filter((def) => def.autoOpen !== false);
  for (const def of defs) {
    const participants: ConflictParticipants = def.participants;
    const result = await driveConflictTurn(db, def, participants, currentTurn, currentYear);
    for (const event of result.events) {
      if (await materializeEvent(db, def, participants, event, currentTurn)) eventsOpened++;
    }
  }
  return { conflictsProcessed: defs.length, eventsOpened };
}
