import type { Db } from "mongodb";
import { COUNTRY_CONFIGS } from "@/lib/constants/countries";
import type {
  Crisis,
  CrisisDecisionNode,
  CrisisTemplate,
  GlobalResponseRole,
} from "@/lib/db/types/crisis";
import { createCrisisFromTemplate } from "@/lib/crises/createCrisisFromTemplate";
import { logWireEvent } from "@/lib/wireEvent";
import { listNuclearPrograms } from "@/lib/db/collections/nuclearPrograms";
import { getConflictsCollection } from "@/lib/db/collections/conflicts";
import { nuclearStandoffPossible } from "@/lib/military/nuclearProgram";
import { allLivingConflictDefs } from "./registry";
import { loadConflictState, saveConflictState } from "./driver";
import { normalizeCampaignState } from "./campaign";
import { migrateLegacyVietnamState } from "./vietnamCompat";
import { vietnamWorldPressure } from "./worldPressure";
import { resolveConflictParticipants } from "./engine";
import { reconcileNorthernIrelandRatification } from "./northernIrelandRatification";
import {
  allParticipants,
  driveConflictTurn,
  type ConflictParticipants,
  type DrivenEvent,
} from "./driver";
import { GLOBAL_FINANCIAL_CRISIS_KEY, loadFinancialCrisisSignal } from "./financialCrisisPressure";

function roleMapForEvent(
  def: ReturnType<typeof allLivingConflictDefs>[number],
  participants: ConflictParticipants,
  driven: DrivenEvent
): Record<string, GlobalResponseRole> {
  const playable = new Set(Object.keys(COUNTRY_CONFIGS));
  const affected = new Set(driven.affectedNations);
  const roleByCountry: Record<string, GlobalResponseRole> = {};
  for (const countryId of allParticipants(participants)) {
    if (!playable.has(countryId) || !affected.has(countryId)) continue;
    const role = def.roleResolver({ countryId, ...participants });
    if (!driven.fired.event.response?.decisionTrees[role]) continue;
    roleByCountry[countryId] = role;
  }
  return roleByCountry;
}

function responseNode(driven: DrivenEvent): CrisisDecisionNode {
  const response = driven.fired.event.response!;
  const optionsByRole = Object.fromEntries(
    Object.entries(response.decisionTrees).map(([role, node]) => [role, node?.options ?? []])
  );
  return {
    nodeId: `${driven.fired.event.key}_global_response`,
    type: "choice",
    title: driven.fired.event.headline,
    description: driven.fired.event.body,
    options: [],
    optionsByRole,
    requiredRoles: ["headOfState"],
    timeLimitMinutes: response.windowTurns * 60,
  };
}

function eventTemplate(driven: DrivenEvent, countryIds: string[]): CrisisTemplate {
  const event = driven.fired.event;
  const windowTurns = event.response?.windowTurns ?? event.negotiation?.windowTurns ?? 1;
  return {
    name: event.headline,
    description: event.body,
    scope: "country",
    countryIds,
    regionIds: [],
    durationTurns: windowTurns,
    durationByScope: { country: windowTurns },
    effects: [],
    wireMessageOnStart: event.headline,
    wireMessageOnEnd: `The international response window for ${event.headline.toLowerCase()} has closed.`,
    autoGenerated: true,
    interactionDefinition: event.response
      ? { decisionTree: [responseNode(driven)], autoResolveOnExpiry: true }
      : event.negotiation
        ? { decisionTree: event.negotiation.decisionTree, autoResolveOnExpiry: true }
        : undefined,
  };
}

async function materializeEvent(
  db: Db,
  def: ReturnType<typeof allLivingConflictDefs>[number],
  participants: ConflictParticipants,
  driven: DrivenEvent,
  currentTurn: number
): Promise<{ opened: boolean; blockedByActiveWindow: boolean }> {
  const existing = await db
    .collection<Crisis>("crises")
    .findOne({ livingConflictEventId: driven.fired.id }, { projection: { _id: 1 } });
  if (existing) return { opened: false, blockedByActiveWindow: false };
  const activeGlobalWindow = await db
    .collection<Crisis>("crises")
    .findOne(
      { "globalResponse.conflictKey": def.key, status: "active" },
      { projection: { _id: 1, startTurn: 1, durationTurns: 1 } }
    );
  const activeNegotiationWindow = driven.fired.event.negotiation
    ? await db
        .collection<Crisis>("crises")
        .findOne(
          { livingConflictEventId: { $regex: `^${def.key}:` }, status: "active" },
          { projection: { _id: 1, startTurn: 1, durationTurns: 1 } }
        )
    : null;
  const activeWindow = activeGlobalWindow ?? activeNegotiationWindow;
  // Crisis lifecycle closure happens later in the same turn. Do not let a
  // response whose authored duration ends now suppress the next cadence event.
  const activeWindowExpiresAfterThisTurn =
    activeWindow &&
    (activeWindow.durationTurns === null ||
      currentTurn < activeWindow.startTurn + activeWindow.durationTurns);
  if (activeWindowExpiresAfterThisTurn) {
    return { opened: false, blockedByActiveWindow: true };
  }

  const { response, negotiation } = driven.fired.event;
  if (!response && !negotiation) {
    await logWireEvent("crisis_start", driven.fired.event.headline);
    return { opened: true, blockedByActiveWindow: false };
  }
  const roleByCountry = response ? roleMapForEvent(def, participants, driven) : {};
  const countryIds = response
    ? Object.keys(roleByCountry)
    : [...new Set(negotiation!.decisionTree.flatMap((node) => node.requiredCountryIds ?? []))];
  if (countryIds.length === 0) return { opened: false, blockedByActiveWindow: false };
  const campaign = normalizeCampaignState((await loadConflictState(db, def.key)).campaign);

  await createCrisisFromTemplate(db, {
    template: eventTemplate(driven, countryIds),
    scope: "country",
    countryIds,
    regionIds: [],
    currentTurn,
    autoSource: "condition",
    livingConflictEventId: driven.fired.id,
    globalResponse: response
      ? {
          conflictKey: def.key,
          eventKey: driven.fired.event.key,
          roleByCountry,
          defaultOptionIdByRole: response.defaultOptionIdByRole,
          outcomes: response.outcomes,
          defaultOutcomeId: response.defaultOutcomeId,
          campaign: {
            stage: campaign.stage,
            cycle: campaign.cycle,
            consequences: { ...campaign.consequences },
          },
        }
      : undefined,
  });
  return { opened: true, blockedByActiveWindow: false };
}

export interface LivingConflictTurnResult {
  conflictsProcessed: number;
  eventsOpened: number;
}

/** Advance and materialize every 1.3 living conflict for one turn. */
export async function processLivingConflictsTurn(
  db: Db,
  currentTurn: number,
  currentYear: number | null | undefined,
  enabled: boolean
): Promise<LivingConflictTurnResult> {
  if (!enabled) return { conflictsProcessed: 0, eventsOpened: 0 };
  await migrateLegacyVietnamState(db);
  const [tension, activeWars] = await Promise.all([
    db.collection<{ _id: string; value?: number }>("coldWarTension").findOne({ _id: "current" }),
    getConflictsCollection(db).find({ status: "active" }).toArray(),
  ]);
  const countryRows = await db
    .collection<{ countryId?: string }>("states")
    .find({}, { projection: { countryId: 1 } })
    .toArray();
  const availableCountryIds = new Set(
    countryRows.length > 0
      ? countryRows.map((row) => row.countryId).filter((id): id is string => Boolean(id))
      : Object.keys(COUNTRY_CONFIGS)
  );
  const vietnamExternalPressure = vietnamWorldPressure(tension?.value ?? 0, activeWars);
  let eventsOpened = 0;
  const defs = allLivingConflictDefs().filter((def) => def.autoOpen !== false);
  let nuclearPrograms: Awaited<ReturnType<typeof listNuclearPrograms>> | null = null;
  let conflictsProcessed = 0;
  for (const def of defs) {
    if (def.key === "nuclear_incident") {
      const existing = await loadConflictState(db, def.key);
      if (!existing.hasOpened) {
        nuclearPrograms ??= await listNuclearPrograms(db);
        if (!nuclearStandoffPossible(nuclearPrograms)) continue;
      }
    }
    conflictsProcessed++;
    const participants: ConflictParticipants = resolveConflictParticipants(
      def,
      availableCountryIds
    );
    let externalPressure =
      def.key === "vietnam" && typeof currentYear === "number" ? vietnamExternalPressure : 0;
    let openingTrackDeltas: Record<string, number> = {};
    if (def.key === GLOBAL_FINANCIAL_CRISIS_KEY) {
      const signal = await loadFinancialCrisisSignal(db, currentTurn);
      externalPressure = signal.pressure;
      openingTrackDeltas = signal.openingTrackDeltas;
    }
    const result = await driveConflictTurn(
      db,
      def,
      participants,
      currentTurn,
      currentYear,
      externalPressure,
      openingTrackDeltas
    );
    if (def.key === "northern_ireland") {
      result.state = await reconcileNorthernIrelandRatification(
        db,
        def,
        result.state,
        currentYear ?? undefined
      );
    }
    let retryPhaseEntry = false;
    for (const event of result.events) {
      const materialized = await materializeEvent(db, def, participants, event, currentTurn);
      if (materialized.opened) eventsOpened++;
      if (materialized.blockedByActiveWindow && event.fired.event.trigger?.onPhaseEnter) {
        retryPhaseEntry = true;
      }
    }
    if (retryPhaseEntry) {
      await saveConflictState(db, { ...result.state, emitPhaseEntryNextTurn: true });
    }
  }
  return { conflictsProcessed, eventsOpened };
}
