/**
 * Insert the canonical Snap Elections wiki seed into worlds where the page is
 * missing. Existing rows are always preserved, including drafts,
 * auto-generated rows, and human-edited pages.
 *
 * Usage:
 *   npx tsx scripts/migrations/2026-09-30-seed-snap-election-wiki-page.ts --live
 *   npx tsx scripts/migrations/2026-09-30-seed-snap-election-wiki-page.ts --live --apply
 *
 * The default target is MONGODB_URI. Pass --live to select MONGODB_URI_LIVE.
 * Nothing is written unless --apply is present.
 */
import path from "node:path";
import dotenv from "dotenv";
import { MongoClient, ObjectId, type Db } from "mongodb";
import type { WikiPage } from "@/lib/db/types";
import type { WikiSeedPage } from "../../src/lib/seeds/wiki/types";
import type { MigrationResult } from "../../src/lib/migrations/types";
import { WIKI_SEED_PAGES } from "../../src/lib/seeds/wiki/pages";
import { wikiPageDocForSeed } from "../../src/lib/seeds/wiki/seeder";

const SNAP_ELECTIONS_SLUG = "snap-elections";
const CLI_SEED_USER_ID = new ObjectId("000000000000000000000000");

function requireSnapElectionsSeed(): WikiSeedPage {
  const seed = WIKI_SEED_PAGES.find((page) => page.slug === SNAP_ELECTIONS_SLUG);
  if (!seed) {
    throw new Error(`Wiki seed ${SNAP_ELECTIONS_SLUG} is missing from WIKI_SEED_PAGES`);
  }
  return seed;
}

const SNAP_ELECTIONS_SEED = requireSnapElectionsSeed();

export async function runSeedSnapElectionWikiPage(
  db: Db,
  opts: { dryRun?: boolean; now?: Date } = {}
): Promise<MigrationResult> {
  const collection = db.collection<WikiPage>("wikiPages");
  const existing = await collection.findOne(
    { slug: SNAP_ELECTIONS_SLUG },
    {
      projection: {
        _id: 1,
        content: 1,
        status: 1,
        private: 1,
        isAutoGenerated: 1,
        editHistory: 1,
      },
    }
  );

  if (existing) {
    const existingContent = typeof existing.content === "string" ? existing.content : "";
    const hasHumanEdits = (existing.editHistory ?? []).some(
      (entry) => entry.action !== "created" && !entry.note?.startsWith("Reseed")
    );
    return {
      documentsScanned: 1,
      documentsInserted: 0,
      notes: [
        `Existing ${SNAP_ELECTIONS_SLUG} page preserved unchanged: ` +
          `status=${existing.status ?? "unset"}, private=${existing.private === true}, ` +
          `contentChars=${existingContent.length}, ` +
          `canonicalContent=${existingContent === SNAP_ELECTIONS_SEED.content}, ` +
          `humanEdits=${hasHumanEdits}.`,
      ],
    };
  }

  if (opts.dryRun) {
    return {
      documentsScanned: 1,
      documentsInserted: 0,
      notes: [`Dry run: would insert the ${SNAP_ELECTIONS_SLUG} seed page.`],
    };
  }

  const result = await collection.updateOne(
    { slug: SNAP_ELECTIONS_SLUG },
    {
      $setOnInsert: wikiPageDocForSeed(
        SNAP_ELECTIONS_SEED,
        CLI_SEED_USER_ID,
        opts.now ?? new Date()
      ),
    },
    { upsert: true }
  );
  const inserted = result.upsertedCount ?? 0;

  return {
    documentsScanned: 1,
    documentsInserted: inserted,
    notes: [
      inserted === 1
        ? `Inserted the ${SNAP_ELECTIONS_SLUG} seed page.`
        : `The ${SNAP_ELECTIONS_SLUG} page was created concurrently; preserved it unchanged.`,
    ],
  };
}

async function main(): Promise<void> {
  const args = new Set(process.argv.slice(2));
  const useLive = args.has("--live");
  const apply = args.has("--apply");
  const envFileArgument = process.argv.find((argument) => argument.startsWith("--env-file="));
  const envFile = envFileArgument?.slice("--env-file=".length);
  dotenv.config({
    path: envFile ? path.resolve(envFile) : path.resolve(process.cwd(), ".env.local"),
  });

  const uriKey = useLive ? "MONGODB_URI_LIVE" : "MONGODB_URI";
  const uri = process.env[uriKey];
  if (!uri) throw new Error(`${uriKey} is not set`);

  const client = new MongoClient(uri, {
    directConnection: !uri.startsWith("mongodb+srv://"),
  });
  await client.connect();
  try {
    const db = client.db();
    const result = await runSeedSnapElectionWikiPage(db, { dryRun: !apply });
    console.log(
      JSON.stringify(
        {
          target: useLive ? "live" : "local",
          database: db.databaseName,
          mode: apply ? "apply" : "dry-run",
          ...result,
        },
        null,
        2
      )
    );
  } finally {
    await client.close();
  }
}

if (require.main === module) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
