/**
 * Backfill game provenance onto legacy custom wiki pages that were created
 * before GAME_ITERATION / GAME_START_DATE stamping shipped.
 *
 * Targets `MONGODB_URI_LIVE` only and is safe to dry-run by default.
 * Pass `--apply` to persist the stamp.
 *
 * A page qualifies when all of the following are true:
 * - published
 * - not auto-generated
 * - not one of the claim-managed profile slugs (`player-*`, `corp-*`, `party-*-*`)
 * - category is one of the player-submittable categories
 * - has both `submittedBy` and `reviewedBy` (legacy reviewed player submission)
 * - does not look seed-managed (`editHistory.0.note` does not start with `Reseed`)
 * - is still missing at least one provenance field
 */
import { MongoClient, type Filter } from "mongodb";
import * as dotenv from "dotenv";
import path from "path";
import type { WikiPage } from "../../src/lib/db/types";
import { PLAYER_SUBMITTABLE_CATEGORY_IDS } from "../../src/lib/wiki/categories";
import { getGameStamp } from "../../src/lib/wiki/gameConfig";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const uri = process.env.MONGODB_URI_LIVE;
if (!uri) {
  console.error("MONGODB_URI_LIVE not set in .env.local");
  process.exit(1);
}

const APPLY = process.argv.includes("--apply");
const MARKER_ID = "backfill-legacy-custom-wiki-pages";
const CLAIM_MANAGED_SLUG_PATTERNS = [/^player-\d+$/, /^corp-\d+$/, /^party-[a-z]{2}-\d+$/];
const stamp = getGameStamp();
const liveUri = uri;

if (!stamp.gameIteration && !stamp.gameStartDate) {
  console.error("GAME_ITERATION and/or GAME_START_DATE must be set in .env.local");
  process.exit(1);
}

function isClaimManagedSlug(slug: string): boolean {
  return CLAIM_MANAGED_SLUG_PATTERNS.some((pattern) => pattern.test(slug));
}

async function main() {
  const client = new MongoClient(liveUri);
  await client.connect();

  try {
    const db = client.db("a-house-divided");
    const migrationsRun = db.collection<{
      _id: string;
      completedAt: Date;
      matched: number;
      modified: number;
    }>("migrationsRun");
    const marker = await migrationsRun.findOne({ _id: MARKER_ID });

    if (marker) {
      console.log(
        `[${MARKER_ID}] already ran at ${marker.completedAt.toISOString()} (matched=${marker.matched}, modified=${marker.modified}).`
      );
      return;
    }

    const baseFilter: Filter<WikiPage> = {
      status: "published",
      isAutoGenerated: { $ne: true },
      category: { $in: [...PLAYER_SUBMITTABLE_CATEGORY_IDS] },
      submittedBy: { $exists: true },
      reviewedBy: { $exists: true },
      "editHistory.0.note": { $not: { $regex: /^Reseed/ } },
      $or: [{ gameIteration: { $exists: false } }, { gameStartDate: { $exists: false } }],
    };

    const candidates = await db
      .collection<WikiPage>("wikiPages")
      .find(baseFilter, {
        projection: {
          _id: 1,
          slug: 1,
          title: 1,
          category: 1,
          gameIteration: 1,
          gameStartDate: 1,
          submittedBy: 1,
          reviewedBy: 1,
          editHistory: 1,
        },
      })
      .toArray();

    const matches = candidates.filter((page) => !isClaimManagedSlug(page.slug));

    console.log(`[${MARKER_ID}] mode=${APPLY ? "APPLY" : "DRY-RUN"}`);
    console.log(
      `[${MARKER_ID}] stamp=${JSON.stringify(stamp)} candidates=${candidates.length} matches=${matches.length}`
    );

    if (matches.length > 0) {
      console.log("");
      for (const page of matches) {
        console.log(
          `- ${page.slug} | ${page.title} | category=${page.category ?? "(none)"} | gameIteration=${page.gameIteration ?? "(missing)"} | gameStartDate=${page.gameStartDate ?? "(missing)"}`
        );
      }
      console.log("");
    }

    if (!APPLY) {
      console.log("Dry run complete. Re-run with --apply to persist the stamp.");
      return;
    }

    if (matches.length === 0) {
      await migrationsRun.insertOne({
        _id: MARKER_ID,
        completedAt: new Date(),
        matched: 0,
        modified: 0,
      });
      console.log(`[${MARKER_ID}] nothing to update.`);
      return;
    }

    const result = await db.collection<WikiPage>("wikiPages").updateMany(
      {
        _id: { $in: matches.map((page) => page._id) },
      },
      {
        $set: stamp,
      }
    );

    await migrationsRun.insertOne({
      _id: MARKER_ID,
      completedAt: new Date(),
      matched: result.matchedCount,
      modified: result.modifiedCount,
    });

    console.log(
      `[${MARKER_ID}] applied successfully. matched=${result.matchedCount} modified=${result.modifiedCount}`
    );
  } finally {
    await client.close();
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
