import type { State } from "@/lib/db/types";
/** Romania regions (1979; Ceaușescu era) — the seven historic provinces:
 *  Bucharest, Muntenia, Oltenia, Transylvania proper, the Banat & Crișana-
 *  Maramureș west, Moldavia, and Dobruja. pop ≈ 22M; gdp in millions of lei.
 *  houseDistricts = Grand National Assembly seats, apportioned by population
 *  (sum = 369, matching the country config's lowerChamber seats). */
export const roRegions: State[] = [
  {
    _id: "RO_BUC",
    countryId: "RO",
    regionType: "state",
    name: "Bucharest",
    population: 2_100_000,
    gdp: 130_000,
    houseDistricts: 35,
    stateSenateSeats: 0,
    region: "Bucharest",
    votingSystem: "fptp",
  },
  {
    _id: "RO_MUN",
    countryId: "RO",
    regionType: "state",
    name: "Muntenia",
    population: 4_700_000,
    gdp: 150_000,
    houseDistricts: 78,
    stateSenateSeats: 0,
    region: "Wallachia",
    votingSystem: "fptp",
  },
  {
    _id: "RO_OLT",
    countryId: "RO",
    regionType: "state",
    name: "Oltenia",
    population: 2_400_000,
    gdp: 75_000,
    houseDistricts: 40,
    stateSenateSeats: 0,
    region: "Wallachia",
    votingSystem: "fptp",
  },
  {
    _id: "RO_TRA",
    countryId: "RO",
    regionType: "state",
    name: "Transylvania",
    population: 4_600_000,
    gdp: 190_000,
    houseDistricts: 77,
    stateSenateSeats: 0,
    region: "Transylvania",
    votingSystem: "fptp",
  },
  {
    _id: "RO_VST",
    countryId: "RO",
    regionType: "state",
    name: "Banat & Crișana",
    population: 3_000_000,
    gdp: 120_000,
    houseDistricts: 50,
    stateSenateSeats: 0,
    region: "Transylvania",
    votingSystem: "fptp",
  },
  {
    _id: "RO_MOL",
    countryId: "RO",
    regionType: "state",
    name: "Moldavia",
    population: 4_400_000,
    gdp: 105_000,
    houseDistricts: 74,
    stateSenateSeats: 0,
    region: "Moldavia",
    votingSystem: "fptp",
  },
  {
    _id: "RO_DOB",
    countryId: "RO",
    regionType: "state",
    name: "Dobruja",
    population: 800_000,
    gdp: 30_000,
    houseDistricts: 15,
    stateSenateSeats: 0,
    region: "Dobruja",
    votingSystem: "fptp",
  },
];
export default roRegions;
