import type { ObjectId } from "mongodb";

export interface PoliticianElectionEntry {
  electionId: string;
  electionType: string;
  state: string;
  stateName?: string;
  year: number;
  result: "won" | "lost" | "primary_lost";
  votes?: number;
  votesPct?: number;
  party: string;
  officeLabel: string;
  completedAt: Date;
}

export interface PoliticianOverride {
  _id: ObjectId;
  politicianId: string;
  customBio?: string;
  customSections?: Array<{ title: string; content: string }>;
  sectionOrder?: string[];
  /** Auto-generated flavor bio (overridden by customBio when set). */
  autoGeneratedBio?: string;
  /** Election history for Wikipedia-style display. Updated when elections resolve. */
  electionHistory?: PoliticianElectionEntry[];
  /** True if character has ever held Congress leadership (Speaker, House/Senate leader). */
  hasHeldCongressLeadership?: boolean;
  updatedAt: Date;
}
