import type { ObjectId } from "mongodb";
import type { CountryId } from "@/lib/constants/countries";

export type WikiPageStatus = "draft" | "pending_review" | "published" | "archived";
export type WikiPageContentType = "guide" | "reference" | "mechanics" | "strategy";
export type WikiPageDifficulty = "beginner" | "intermediate" | "advanced";

export interface EditHistoryEntry {
  userId: ObjectId;
  timestamp: Date;
  action: "created" | "edited" | "approved" | "rejected" | "archived";
  note?: string;
}

export interface AutoGenerateConfig {
  type: "party" | "leadership" | "seat" | "politician" | "office" | "election";
  entityId: string;
  widgetComponents?: string[];
}

export interface WikiPage {
  _id: ObjectId;
  slug: string; // unique index
  title: string;
  description: string;
  content: string; // markdown

  // Status & Review (optional during migration)
  status?: WikiPageStatus;
  submittedBy?: ObjectId;
  reviewedBy?: ObjectId;

  // Organization
  tags?: string[];
  templateType?: string;
  featured?: boolean;

  // Metadata
  category?: string; // Legacy field, will be replaced by tags
  contentType?: WikiPageContentType; // Legacy field
  difficulty?: WikiPageDifficulty;
  estimatedReadTime?: number;

  // Visibility
  /** Admin-only: when true, page is only readable by admins */
  private?: boolean;

  /** Country this page documents (e.g. "US", "UK"). Optional — only set for country-specific pages. */
  countryId?: CountryId;

  // Auto-generated pages
  isAutoGenerated?: boolean;
  autoGenerateConfig?: AutoGenerateConfig;

  // Game provenance — stamped at creation time from GAME_ITERATION / GAME_START_DATE env vars
  gameIteration?: string;
  gameStartDate?: string;

  // Analytics
  viewCount?: number;

  // Audit
  createdAt: Date;
  updatedAt: Date;
  editHistory?: EditHistoryEntry[];
}
