import { beforeEach, describe, expect, it, vi } from "vitest";
import { ObjectId, type Db } from "mongodb";
import { captureWorldDepthPosthog } from "./worldDepthAnalytics";

const capture = vi.hoisted(() => vi.fn().mockResolvedValue(undefined));
vi.mock("./serverPosthog", () => ({
  captureServerGameEvent: capture,
  getServerPosthogClient: () => ({}),
}));

function fixture(rows: Record<string, unknown[]>) {
  const reads = vi.fn((name: string, filter: unknown, options: unknown) => {
    void filter;
    void options;
    return { toArray: async () => rows[name] ?? [] };
  });
  const db = {
    collection: (name: string) => ({
      find: (filter: unknown, options: unknown) => reads(name, filter, options),
    }),
  } as unknown as Db;
  return { db, reads };
}

describe("committed world depth telemetry", () => {
  beforeEach(() => vi.clearAllMocks());

  it("emits party, corporate, market, battle, diplomatic and crisis server outcomes without display text", async () => {
    const entityId = new ObjectId();
    const { db, reads } = fixture({
      partyHistory: [
        {
          _id: "US:1:42",
          countryId: "US",
          partyId: "1",
          organization: 15,
          playerCount: 2,
          nppCount: 10,
          memberCount: 12,
          name: "private name",
        },
      ],
      partyMembershipEvents: [
        {
          _id: entityId,
          countryId: "US",
          oldPartyId: "1",
          newPartyId: "2",
          reason: "join",
          actorRole: "self",
          characterName: "private name",
        },
      ],
      corporationHistory: [
        {
          _id: entityId,
          corporationId: entityId,
          currencyCode: "USD",
          income: -5,
          revenue: 10,
          totalCosts: 15,
        },
      ],
      corporations: [{ _id: entityId, countryId: "US" }],
      shareTradeHistory: [
        {
          _id: entityId,
          corporationId: entityId,
          turn: 41,
          kind: "limit_fill",
          shares: 3,
          totalAnchor: 15,
          note: "private note",
        },
      ],
      marketCapHistory: [{ turn: 42, globalMarketCap: 500, listingUniverse: "public-only" }],
      tradeHistory: [
        { fromCurrency: "USD", toCurrency: "GBP", amount: 5, spread: 0.1, source: "limit_order" },
        { fromCurrency: "USD", toCurrency: "GBP", amount: 10, spread: 0.2, source: "limit_order" },
      ],
      battleReports: [
        {
          _id: entityId,
          declarerCountry: "US",
          targetCountry: "UK",
          result: {
            win: true,
            margin: 4,
            attacker: { loss: 20 },
            defender: { loss: 30 },
            verdict: "private text",
          },
        },
      ],
      crises: [
        {
          _id: entityId,
          scope: "country",
          countryIds: ["US"],
          status: "resolved",
          startTurn: 40,
          endTurn: 42,
          autoGenerated: true,
          autoSource: "condition",
          name: "private name",
        },
      ],
      organizationMembershipProposals: [
        { _id: entityId, organizationId: "nato", proposingCountryId: "US", status: "approved" },
      ],
      organizationLegislation: [
        {
          _id: entityId,
          organizationId: "nato",
          proposingCountryId: "US",
          type: "free_trade_agreement",
          status: "active",
        },
      ],
    });
    await captureWorldDepthPosthog({ db, turn: 42, iteration: { type: "Alpha", number: 1 } });
    expect(capture.mock.calls.map(([input]) => input.event)).toEqual([
      "party_snapshot",
      "party_membership_changed",
      "corporation_snapshot",
      "share_trade_settled",
      "market_snapshot",
      "currency_trade_settled",
      "battle_resolved",
      "crisis_resolved",
      "diplomacy_resolved",
      "diplomacy_resolved",
    ]);
    expect(capture).toHaveBeenCalledWith(
      expect.objectContaining({
        event: "currency_trade_settled",
        properties: expect.objectContaining({
          trade_count: 2,
          total_amount: 15,
          execution_source: "limit_order",
        }),
      })
    );
    expect(capture).toHaveBeenCalledWith(
      expect.objectContaining({
        event: "battle_resolved",
        nationId: "US",
        properties: expect.objectContaining({
          outcome: "attacker_won",
          attacker_casualties: 20,
          defender_casualties: 30,
        }),
      })
    );
    expect(capture).toHaveBeenCalledWith(
      expect.objectContaining({
        event: "corporation_snapshot",
        nationId: "US",
        properties: expect.objectContaining({ income: -5 }),
      })
    );
    for (const [input] of capture.mock.calls) {
      expect(input.distinctId).toBe("system:turn-processor");
      expect(input.insertId).toMatch(/:(41|42)$/);
      expect(JSON.stringify(input.properties)).not.toContain("private");
      expect(
        Object.values(input.properties).every((value) =>
          ["string", "number", "boolean"].includes(typeof value)
        )
      ).toBe(true);
    }
    expect(reads).toHaveBeenCalledTimes(13);
    for (const [, , options] of reads.mock.calls) expect(options).toHaveProperty("projection");
  });

  it("reports crisis start and same-turn resolution separately and excludes maintenance membership changes", async () => {
    const { db } = fixture({
      crises: [
        {
          _id: new ObjectId(),
          scope: "global",
          countryIds: [],
          status: "resolved",
          startTurn: 42,
          endTurn: 42,
        },
      ],
      partyMembershipEvents: [{ _id: new ObjectId(), reason: "cleanup" }],
    });
    await captureWorldDepthPosthog({ db, turn: 42 });
    expect(capture.mock.calls.map(([input]) => input.event)).toEqual([
      "crisis_started",
      "crisis_resolved",
    ]);
  });

  it("contains a failed telemetry read", async () => {
    const db = {
      collection: () => ({
        find: () => ({
          toArray: async () => {
            throw new Error("database unavailable");
          },
        }),
      }),
    } as unknown as Db;
    await expect(captureWorldDepthPosthog({ db, turn: 42 })).resolves.toBeUndefined();
    expect(capture).not.toHaveBeenCalled();
  });
});
