import type { NotificationType } from "@/lib/db/types/notifications";

export type InboxCategory =
  "crisis" | "legislation" | "election" | "party" | "standing" | "treasury" | "system";

export const PLAYER_FACING_CATEGORIES: InboxCategory[] = [
  "crisis",
  "legislation",
  "election",
  "party",
  "standing",
  "treasury",
];

// Total map — the Record<NotificationType, …> type forces every type to be present;
// adding a new NotificationType without a category here is a compile error.
export const CATEGORY_OF: Record<NotificationType, InboxCategory> = {
  // crisis
  crisis: "crisis",
  player_attack: "crisis",
  corp_sector_sold: "treasury",
  corp_sector_attacked: "crisis",
  corp_nationalization_notice: "crisis",
  corp_nationalization_risk: "crisis",
  corp_hostile_takeover_available: "crisis",
  // A war you did not choose is a crisis, not a standing-office notice.
  treaty_defence_invoked: "crisis",
  // legislation
  bill_vote_open: "legislation",
  bill_passed_chamber: "legislation",
  bill_failed_chamber: "legislation",
  bill_enrolled: "legislation",
  bill_signed: "legislation",
  bill_vetoed: "legislation",
  party_whip_issued: "legislation",
  // election
  primary_win: "election",
  primary_loss: "election",
  general_win: "election",
  general_loss: "election",
  impeachment_filed: "legislation",
  impeachment_convicted: "crisis",
  election_opened: "election",
  leadership_election_opened: "election",
  leadership_candidacy: "election",
  national_leadership_election_opened: "election",
  national_leadership_candidacy: "election",
  committee_election_opened: "election",
  committee_candidacy: "election",
  caucus_chair_election_opened: "election",
  // party
  party_kicked: "party",
  party_join_request: "party",
  party_join_accepted: "party",
  party_join_declined: "party",
  player_support: "party",
  new_post: "party",
  charter_invited: "party",
  charter_replacement_needed: "party",
  charter_ratified: "party",
  coalition_invite_received: "party",
  coalition_invite_accepted: "party",
  coalition_invite_declined: "party",
  coalition_join_request: "party",
  coalition_join_accepted: "party",
  coalition_join_declined: "party",
  coalition_kicked: "party",
  coalition_disband_vote_started: "party",
  coalition_disbanded: "party",
  coalition_chair_transferred: "party",
  // standing
  leadership_elected: "standing",
  leadership_lost: "standing",
  union_leader_offer: "standing",
  union_busting_attempted: "crisis",
  bargaining_dispute_lapsed: "crisis",
  overtime_ban_defunded: "crisis",
  bargaining_ratification_open: "standing",
  bargaining_ratification_closed: "standing",
  leadership_appointed: "standing",
  command_appointed: "standing",
  leadership_removed: "standing",
  national_leadership_elected: "standing",
  national_leadership_lost: "standing",
  national_leadership_appointed: "standing",
  national_leadership_removed: "standing",
  committee_elected: "standing",
  committee_lost: "standing",
  committee_removed: "standing",
  caucus_chair_elected: "standing",
  caucus_chair_lost: "standing",
  caucus_chair_removed: "standing",
  resource_income: "standing",
  // treasury
  wire_received: "treasury",
  corp_credit_rating_change: "treasury",
  corp_bond_due_soon: "treasury",
  corp_bond_repaid: "treasury",
  corp_bond_auto_refinanced: "treasury",
  corp_bond_auto_restructured: "treasury",
  corp_inactive_ceo_share_release_warning: "treasury",
  corp_nationalization_cancelled: "treasury",
  corp_privatization_offered: "treasury",
  corp_privatization_resolved: "treasury",
  ceo_vote_offer: "treasury",
  ceo_resigned: "treasury",
  ceo_elected: "treasury",
  share_listing_offer_received: "treasury",
  share_offer_accepted: "treasury",
  share_offer_expired: "treasury",
  share_invite_received: "treasury",
  share_invite_cancelled: "treasury",
  share_invite_declined: "treasury",
  share_invite_accepted: "treasury",
  corp_vote_opened: "treasury",
  corp_vote_reminder: "treasury",
  corp_vote_passed: "treasury",
  corp_vote_failed: "treasury",
  corp_vote_cancelled: "treasury",
  rd_breakthrough: "treasury",
  prospect_succeeded: "treasury",
  prospect_failed: "treasury",
  contract_offered: "treasury",
  defence_contract_offered: "treasury",
  defence_contract_cancelled: "treasury",
  contract_royalty_missed: "treasury",
  contract_defaulted: "treasury",
  contract_expired: "treasury",
  merger_review_opened: "treasury",
  merger_review_decided: "treasury",
  merger_remedy_overdue: "treasury",
  transfer_pricing_assessed: "treasury",
  bank_supervision_breach: "treasury",
  bank_supervision_cleared: "treasury",
  // system (folded into "All" but not a player-facing chip)
  welcome: "system",
  system: "system",
  feedback_status_changed: "system",
  new_feedback: "system",
  new_player_suggestion: "system",
  player_suggestion_status_changed: "system",
  player_suggestion_new_comment: "system",
  player_suggestion_merged: "system",
  turn_advance: "system",
  wiki_submission_pending: "system",
  wiki_submission_approved: "system",
  wiki_submission_rejected: "system",
  supporter_request_pending: "system",
  supporter_request_approved: "system",
  supporter_request_rejected: "system",
  player_event: "system",
  player_event_resolved: "system",
  extraction_capacity_bound: "treasury",
  corp_supply_agreement_damages: "treasury",
  world_event_offered: "system",
  world_event_resolved: "system",
};

export function categoryOf(type: NotificationType): InboxCategory {
  return CATEGORY_OF[type] ?? "system";
}
