import { connectDb, closeDb } from "../utils/db";
import { getDb } from "@/lib/mongodb";
import { ObjectId } from "mongodb";
import { readFile } from "fs/promises";
import { join } from "path";
import type { WikiPage, SystemTag, WikiTemplate } from "@/lib/db/types";
import { WIKI_PAGES } from "@/lib/wiki/config";
import { WIKI_CATEGORIES } from "@/lib/wiki/categories";

const SYSTEM_USER_ID = new ObjectId("000000000000000000000000"); // Placeholder

async function main() {
  await connectDb();
  const db = await getDb();

  console.log("Starting wiki migration...");

  // Phase 1: Import markdown files
  console.log("\n[1/4] Importing markdown files...");
  await importMarkdownFiles(db);

  // Phase 2: Generate auto-generated pages
  console.log("\n[2/4] Generating auto-generated pages...");
  await generateAutoPages(db);

  // Phase 3: Seed system tags
  console.log("\n[3/4] Seeding system tags...");
  await seedSystemTags(db);

  // Phase 4: Seed templates
  console.log("\n[4/4] Seeding templates...");
  await seedTemplates(db);

  console.log("\n✅ Migration complete!");
  await closeDb();
}

async function importMarkdownFiles(db: any) {
  const wikiPages = db.collection("wikiPages");
  const designDir = join(process.cwd(), "docs", "design");

  let imported = 0;
  let skipped = 0;

  for (const configPage of WIKI_PAGES) {
    const fileName = `${configPage.slug}.md`;
    const filePath = join(designDir, fileName);

    try {
      const content = await readFile(filePath, "utf-8");

      const wikiPage: Omit<WikiPage, "_id"> = {
        slug: configPage.slug,
        title: configPage.title,
        description: configPage.description,
        content,
        status: "published",
        submittedBy: SYSTEM_USER_ID,
        tags: "category" in configPage && configPage.category ? [configPage.category] : [],
        featured: "featured" in configPage ? configPage.featured : false,
        isAutoGenerated: false,
        createdAt: new Date(),
        updatedAt: new Date(),
        editHistory: [
          {
            userId: SYSTEM_USER_ID,
            timestamp: new Date(),
            action: "created",
            note: "Migrated from docs/design/",
          },
        ],
      };

      await wikiPages.insertOne(wikiPage as any);
      imported++;
      console.log(`  ✓ Imported: ${configPage.slug}`);
    } catch (_error) {
      skipped++;
      console.log(`  ⊘ Skipped: ${configPage.slug} (file not found)`);
    }
  }

  console.log(`  Imported: ${imported}, Skipped: ${skipped}`);
}

async function generateAutoPages(db: any) {
  const wikiPages = db.collection("wikiPages");
  const parties = await db.collection("politicalParties").find({}).toArray();

  let generated = 0;

  for (const party of parties) {
    const slug = `party-${party._id}`;

    // Skip if already exists
    const existing = await wikiPages.findOne({ slug });
    if (existing) {
      console.log(`  ⊘ Skipped: ${slug} (already exists)`);
      continue;
    }

    const content = `# ${party.name}

${party.description || `${party.name} is a political party in the United States.`}

## Current Leadership

{{PartyLeaderCard}}

## Party Statistics

{{PartyStatsWidget}}

## Members

{{PartyMembersTable}}

## Platform

*This section can be edited by admins to describe the party's platform and positions.*
`;

    const wikiPage: Omit<WikiPage, "_id"> = {
      slug,
      title: `${party.name} - Party Profile`,
      description: `Official party page for ${party.name}`,
      content,
      status: "published",
      submittedBy: SYSTEM_USER_ID,
      tags: ["parties", "reference"],
      featured: false,
      isAutoGenerated: true,
      autoGenerateConfig: {
        type: "party",
        entityId: party._id,
        widgetComponents: ["PartyLeaderCard", "PartyStatsWidget", "PartyMembersTable"],
      },
      createdAt: new Date(),
      updatedAt: new Date(),
      editHistory: [
        {
          userId: SYSTEM_USER_ID,
          timestamp: new Date(),
          action: "created",
          note: "Auto-generated party page",
        },
      ],
    };

    await wikiPages.insertOne(wikiPage as any);
    generated++;
    console.log(`  ✓ Generated: ${slug}`);
  }

  console.log(`  Generated: ${generated} party pages`);
}

async function seedSystemTags(db: any) {
  const systemTagsCol = db.collection("systemTags");

  const systemTags: SystemTag[] = WIKI_CATEGORIES.map((cat, index) => ({
    _id: cat.id,
    name: cat.name,
    description: cat.description,
    icon: cat.icon,
    color: cat.color,
    isSystem: true,
    order: index + 1,
  }));

  // Clear existing
  await systemTagsCol.deleteMany({});

  // Insert new
  await systemTagsCol.insertMany(systemTags as any);

  console.log(`  ✓ Seeded ${systemTags.length} system tags`);
}

async function seedTemplates(db: any) {
  const templatesCol = db.collection("wikiTemplates");

  const templates: WikiTemplate[] = [
    {
      _id: "game-mechanic",
      name: "Game Mechanic",
      description: "Explain how a game system works",
      icon: "⚙️",
      fields: [
        {
          id: "overview",
          label: "Overview",
          placeholder: "Brief summary of this mechanic",
          type: "textarea",
          required: true,
          order: 1,
        },
        {
          id: "how-it-works",
          label: "How It Works",
          placeholder: "Detailed explanation",
          type: "markdown",
          required: true,
          order: 2,
        },
        {
          id: "examples",
          label: "Examples",
          placeholder: "Real scenarios",
          type: "markdown",
          required: false,
          order: 3,
        },
        {
          id: "related",
          label: "Related Mechanics",
          placeholder: "Links to related pages",
          type: "text",
          required: false,
          order: 4,
        },
      ],
    },
    {
      _id: "strategy-guide",
      name: "Strategy Guide",
      description: "Tactical advice for players",
      icon: "🎯",
      fields: [
        {
          id: "prerequisites",
          label: "Prerequisites",
          placeholder: "What you need to know first",
          type: "text",
          required: false,
          order: 1,
        },
        {
          id: "steps",
          label: "Step-by-Step Guide",
          placeholder: "Detailed walkthrough",
          type: "markdown",
          required: true,
          order: 2,
        },
        {
          id: "tips",
          label: "Tips & Tricks",
          placeholder: "Pro tips",
          type: "markdown",
          required: false,
          order: 3,
        },
        {
          id: "mistakes",
          label: "Common Mistakes",
          placeholder: "Pitfalls to avoid",
          type: "markdown",
          required: false,
          order: 4,
        },
      ],
    },
    {
      _id: "reference",
      name: "Reference",
      description: "Data, formulas, technical details",
      icon: "📊",
      fields: [
        {
          id: "summary",
          label: "Quick Summary",
          placeholder: "TL;DR",
          type: "textarea",
          required: true,
          order: 1,
        },
        {
          id: "details",
          label: "Detailed Explanation",
          placeholder: "In-depth info",
          type: "markdown",
          required: true,
          order: 2,
        },
        {
          id: "formulas",
          label: "Formulas/Data",
          placeholder: "Tables, equations",
          type: "markdown",
          required: false,
          order: 3,
        },
      ],
    },
  ];

  // Clear existing
  await templatesCol.deleteMany({});

  // Insert new
  await templatesCol.insertMany(templates as any);

  console.log(`  ✓ Seeded ${templates.length} templates`);
}

main().catch(console.error);
