import {
  POLITICAL_METRIC_CATEGORIES,
  type PoliticalMetricCategoryId,
  type PoliticalMetricId,
  type PoliticalMetricsCountryId,
} from "./types";

/**
 * Per-country display names for every metric family — the country "flavoring"
 * over the shared backend catalog. Transcribed verbatim from the approved
 * design catalog (docs/superpowers/specs/assets/2026-07-16-metrics-mock-data.js
 * FAMILIES names: {us, uk, su}). `satisfies Record<PoliticalMetricId, string>`
 * makes a missing or extra entry a compile error.
 */

export const US_METRIC_NAMES = {
  "economy.workerSecurity": "Worker Security and Bargaining Power",
  "economy.mobility": "Economic Mobility and Poverty Reduction",
  "economy.householdIncome": "Real Household Income and Wage Growth",
  "economy.stability": "Inflation and Macroeconomic Stability",
  "economy.productivity": "Productivity, Investment and Business Formation",
  "economy.fiscal": "Tax Competitiveness and Fiscal Sustainability",
  "economy.competition": "Market Competition and Regulatory Flexibility",
  "education.universalSchooling": "Universal Public Schooling and Equity",
  "education.teacherCorps": "Public School Funding and Teacher Corps",
  "education.adultSkills": "Adult Skills and Vocational Training",
  "education.attainment": "Educational Attainment and Literacy",
  "education.research": "Scientific Research and University Excellence",
  "education.standards": "Academic Standards and School Accountability",
  "education.choice": "School Choice and Educational Markets",
  "health.universalCare": "Public Health Coverage and Safety Net",
  "health.socialInsurance": "Social Insurance and Benefit Adequacy",
  "health.prevention": "Preventive Care and Community Health",
  "health.outcomes": "Population Health Outcomes",
  "health.responsibility": "Personal Responsibility and Cost Sharing",
  "health.providerChoice": "Private Coverage Quality and Choice",
  "health.systemEfficiency": "Healthcare Market Efficiency and Innovation",
  "infrastructure.publicHousing": "Public Housing and Rent Protections",
  "infrastructure.transit": "Public Transit and Rail Investment",
  "infrastructure.utilities": "Universal Utility and Communications Access",
  "infrastructure.condition": "Infrastructure Condition and Reliability",
  "infrastructure.highways": "Highway Network and Freight Logistics",
  "infrastructure.ownership": "Homeownership and Suburban Development",
  "infrastructure.development": "Private Development and Land-Use Flexibility",
  "order.dueProcess": "Civil Liberties in Policing and Rehabilitation",
  "order.legalAid": "Equal Justice and Legal Aid Access",
  "order.communityTrust": "Community Trust in Law Enforcement",
  "order.safety": "Crime Rates and Public Safety",
  "order.courts": "Court Capacity and Case Resolution",
  "order.policeStrength": "Police Strength and Enforcement Capability",
  "order.deterrence": "Sentencing Severity and Deterrence",
  "environment.conservation": "Conservation and Pollution Control",
  "environment.stewardship": "Public Lands and Water Stewardship",
  "environment.urbanAir": "Urban Air Quality and Livability",
  "environment.energySecurity": "Energy Security and Grid Reliability",
  "environment.resourceDev": "Domestic Resource Development",
  "environment.affordability": "Energy Affordability and Fuel Markets",
  "environment.extraction": "Extraction Rights and Regulatory Relief",
  "society.integration": "Civil Rights and Racial Integration",
  "society.womensOpportunity": "Women's Opportunity and Family Support",
  "society.socialMobility": "Social Mobility and Opportunity",
  "society.demography": "Birth Rates and Demographic Balance",
  "society.civicLife": "Civic Institutions and Volunteerism",
  "society.familyStability": "Family Formation and Stability",
  "society.tradition": "Religious Institutions and Traditional Values",
  "governance.participation": "Voting Access and Popular Participation",
  "governance.openness": "Press Freedom and Government Transparency",
  "governance.localAutonomy": "Federalism and Local Self-Government",
  "governance.integrity": "Corruption Control and State Capacity",
  "governance.administration": "Administrative Efficiency and Rule of Law",
  "governance.decisiveness": "Executive Decisiveness and Stability",
  "governance.centralAuthority": "Constitutional Order and Institutional Authority",
  "defense.diplomacy": "Diplomacy, Alliances and Arms Control",
  "defense.institutions": "International Institutions and Foreign Aid",
  "defense.softPower": "Cultural Standing and Soft Power",
  "defense.security": "National Security and Threat Readiness",
  "defense.defenseIndustry": "Defense Industry and Technological Edge",
  "defense.armedForces": "Armed Forces Strength and Readiness",
  "defense.projection": "Strategic Deterrence and Power Projection",
} as const satisfies Record<PoliticalMetricId, string>;

export const UK_METRIC_NAMES = {
  "economy.workerSecurity": "Trade Union Strength and Worker Protections",
  "economy.mobility": "Regional Equality and Poverty Reduction",
  "economy.householdIncome": "Real Household Earnings and Living Standards",
  "economy.stability": "Sterling Stability and Price Control",
  "economy.productivity": "Industrial Productivity and Capital Investment",
  "economy.fiscal": "Fiscal Discipline and Tax Efficiency",
  "economy.competition": "Enterprise Freedom and Market Openness",
  "education.universalSchooling": "Comprehensive Schooling and Equal Access",
  "education.teacherCorps": "State Education Funding and Teaching Profession",
  "education.adultSkills": "Technical Colleges and Apprenticeships",
  "education.attainment": "Attainment and Basic Literacy",
  "education.research": "University Research and Scientific Standing",
  "education.standards": "Grammar Standards and Selective Excellence",
  "education.choice": "Independent Schools and Parental Choice",
  "health.universalCare": "Universal NHS Access",
  "health.socialInsurance": "Social-Insurance and Benefit Adequacy",
  "health.prevention": "Preventive Care and Public-Health Capacity",
  "health.outcomes": "Population Health Outcomes",
  "health.responsibility": "Personal Responsibility and Benefit Targeting",
  "health.providerChoice": "Patient Choice and Provider Autonomy",
  "health.systemEfficiency": "NHS Efficiency and Fiscal Control",
  "infrastructure.publicHousing": "Council Housing and Rent Security",
  "infrastructure.transit": "British Rail and Public Transport",
  "infrastructure.utilities": "Universal Utility and Communications Access",
  "infrastructure.condition": "Infrastructure Condition and Reliability",
  "infrastructure.highways": "Road Network and Freight Capacity",
  "infrastructure.ownership": "Property Ownership and Private Building",
  "infrastructure.development": "Private Development and Planning Flexibility",
  "order.dueProcess": "Rehabilitation and Civil-Liberty Safeguards",
  "order.legalAid": "Legal Aid and Equal Access to Justice",
  "order.communityTrust": "Policing by Consent and Public Trust",
  "order.safety": "Crime Rates and Public Safety",
  "order.courts": "Court Capacity and Case Resolution",
  "order.policeStrength": "Police Strength and Enforcement Capability",
  "order.deterrence": "Sentencing Severity and Deterrence",
  "environment.conservation": "Countryside Protection and Clean Air",
  "environment.stewardship": "National Parks and Water Stewardship",
  "environment.urbanAir": "Urban Smog Abatement and Livability",
  "environment.energySecurity": "Energy Security and Grid Reliability",
  "environment.resourceDev": "Coal and Domestic Resource Development",
  "environment.affordability": "Fuel Affordability and Supply Markets",
  "environment.extraction": "Extraction Licensing and Regulatory Relief",
  "society.integration": "Commonwealth Integration and Race Relations",
  "society.womensOpportunity": "Women's Opportunity and Family Support",
  "society.socialMobility": "Class Mobility and Opportunity",
  "society.demography": "Birth Rates and Demographic Balance",
  "society.civicLife": "Civic Institutions and Voluntary Bodies",
  "society.familyStability": "Family Formation and Stability",
  "society.tradition": "Church, Crown and Traditional Values",
  "governance.participation": "Franchise Access and Popular Participation",
  "governance.openness": "Press Freedom and Official Transparency",
  "governance.localAutonomy": "Local Government and Devolved Powers",
  "governance.integrity": "Corruption Control and State Capacity",
  "governance.administration": "Civil Service Efficiency and Rule of Law",
  "governance.decisiveness": "Cabinet Stability and Decisive Government",
  "governance.centralAuthority": "Parliamentary Sovereignty and Institutional Authority",
  "defense.diplomacy": "Diplomacy, Commonwealth and Arms Control",
  "defense.institutions": "UN Standing and Overseas Development",
  "defense.softPower": "Cultural Standing and Soft Power",
  "defense.security": "National Security and Threat Readiness",
  "defense.defenseIndustry": "Defence Industry and Technological Edge",
  "defense.armedForces": "Armed Forces Strength and Readiness",
  "defense.projection": "Imperial Commitments and Power Projection",
} as const satisfies Record<PoliticalMetricId, string>;

/** Soviet-era names. Post-reform renames live on family.reformName and are applied by future gameplay events. */
export const RU_METRIC_NAMES = {
  "economy.workerSecurity": "Guaranteed Employment and Labour Rights",
  "economy.mobility": "Income Levelling and Basic Provision",
  "economy.householdIncome": "Worker Consumption and Real Wages",
  "economy.stability": "Plan Fulfilment and Price Stability",
  "economy.productivity": "Industrial Output and Capital Formation",
  "economy.fiscal": "State Budget Discipline and Resource Allocation",
  "economy.competition": "Enterprise Autonomy and Incentive Flexibility",
  "education.universalSchooling": "Universal Polytechnic Education",
  "education.teacherCorps": "Teacher Cadres and School Investment",
  "education.adultSkills": "Worker Retraining and Technical Institutes",
  "education.attainment": "Literacy and Educational Attainment",
  "education.research": "Academy of Sciences and Research Output",
  "education.standards": "Examination Rigour and Academic Discipline",
  "education.choice": "Special Schools and Merit Streaming",
  "health.universalCare": "Universal Healthcare Access",
  "health.socialInsurance": "Pension and Invalid Provision",
  "health.prevention": "Sanitary Services and Epidemic Control",
  "health.outcomes": "Population Health Outcomes",
  "health.responsibility": "Workplace Fitness and Labour Capacity",
  "health.providerChoice": "Clinic Autonomy and Specialist Access",
  "health.systemEfficiency": "Health Service Efficiency and Cost Discipline",
  "infrastructure.publicHousing": "State Housing Allocation",
  "infrastructure.transit": "Rail Network and Urban Transit",
  "infrastructure.utilities": "Electrification and Communications Access",
  "infrastructure.condition": "Infrastructure Condition and Reliability",
  "infrastructure.highways": "Freight Corridors and Transport Plan",
  "infrastructure.ownership": "Cooperative Housing and Private Plots",
  "infrastructure.development": "Enterprise Construction Autonomy",
  "order.dueProcess": "Socialist Legality and Due Process",
  "order.legalAid": "Citizen Petitions and Procuracy Oversight",
  "order.communityTrust": "Militia-Public Relations",
  "order.safety": "Public Order and Crime Control",
  "order.courts": "People's Courts Throughput",
  "order.policeStrength": "Militia Strength and Internal Security",
  "order.deterrence": "State Security Vigilance and Deterrence",
  "environment.conservation": "Nature Protection and Pollution Control",
  "environment.stewardship": "Land Reclamation and Water Management",
  "environment.urbanAir": "Industrial City Air and Sanitation",
  "environment.energySecurity": "Energy Security and Grid Reliability",
  "environment.resourceDev": "Resource Extraction and Siberian Development",
  "environment.affordability": "Fuel Allocation Efficiency",
  "environment.extraction": "Production Quota Flexibility",
  "society.integration": "Nationalities Equality and Republic Rights",
  "society.womensOpportunity": "Women in Labour Force and Childcare",
  "society.socialMobility": "Worker Advancement and Social Mobility",
  "society.demography": "Birth Rates and Demographic Balance",
  "society.civicLife": "Komsomol and Mass Organisations",
  "society.familyStability": "Family Stability and Moral Education",
  "society.tradition": "Union Cohesion and Patriotic Identity",
  "governance.participation": "Worker and Republic Participation",
  "governance.openness": "Civil, Cultural and Information Openness",
  "governance.localAutonomy": "Local Soviet and Republic Autonomy",
  "governance.integrity": "Corruption Control and State Capacity",
  "governance.administration": "Managerial Hierarchy and Administrative Control",
  "governance.decisiveness": "Leadership Continuity and Central Decision Speed",
  "governance.centralAuthority": "Central Authority and Party Discipline",
  "defense.diplomacy": "Peace Offensive and Fraternal Diplomacy",
  "defense.institutions": "Comecon Integration and Foreign Aid",
  "defense.softPower": "Socialist Prestige and Cultural Influence",
  "defense.security": "National Security and Threat Readiness",
  "defense.defenseIndustry": "Defence Industry and Military Science",
  "defense.armedForces": "Soviet Army Strength and Readiness",
  "defense.projection": "Strategic Forces and Sphere Security",
} as const satisfies Record<PoliticalMetricId, string>;

/** DDR-era names (SED state; FDGB, Volkspolizei, polyclinics, Wismut, the National Front). */
export const DD_METRIC_NAMES = {
  "economy.workerSecurity": "Guaranteed Work and Trade Union Rights",
  "economy.mobility": "Wage Levelling and Social Provision",
  "economy.householdIncome": "Household Consumption and Real Wages",
  "economy.stability": "Plan Discipline and Price Stability",
  "economy.productivity": "Industrial Output and Plant Modernization",
  "economy.fiscal": "State Budget Discipline and Plan Finance",
  "economy.competition": "Enterprise Autonomy and Private Trades",
  "education.universalSchooling": "Unified Polytechnic Schooling",
  "education.teacherCorps": "Teacher Cadres and School Investment",
  "education.adultSkills": "Vocational Training and Works Academies",
  "education.attainment": "Literacy and Educational Attainment",
  "education.research": "Academy of Sciences and Research Output",
  "education.standards": "Examination Rigour and Academic Discipline",
  "education.choice": "Special Schools and Talent Streaming",
  "health.universalCare": "Universal Polyclinic Access",
  "health.socialInsurance": "Social Insurance and Pension Provision",
  "health.prevention": "Hygiene Services and Epidemic Control",
  "health.outcomes": "Population Health Outcomes",
  "health.responsibility": "Workplace Health and Labour Capacity",
  "health.providerChoice": "Clinic Autonomy and Specialist Access",
  "health.systemEfficiency": "Health Service Efficiency and Cost Discipline",
  "infrastructure.publicHousing": "State Housing Construction and Allocation",
  "infrastructure.transit": "Reichsbahn and Urban Transit",
  "infrastructure.utilities": "Electrification and Communications Access",
  "infrastructure.condition": "Infrastructure Condition and Reliability",
  "infrastructure.highways": "Freight Corridors and Transport Plan",
  "infrastructure.ownership": "Cooperative Housing and Garden Plots",
  "infrastructure.development": "Enterprise Construction Autonomy",
  "order.dueProcess": "Socialist Legality and Due Process",
  "order.legalAid": "Citizen Petitions and Complaint Offices",
  "order.communityTrust": "People's Police-Public Relations",
  "order.safety": "Public Order and Crime Control",
  "order.courts": "District Courts Throughput",
  "order.policeStrength": "People's Police Strength and Internal Security",
  "order.deterrence": "State Security Vigilance and Deterrence",
  "environment.conservation": "Nature Protection and Pollution Control",
  "environment.stewardship": "Land Improvement and Water Management",
  "environment.urbanAir": "Industrial City Air and Sanitation",
  "environment.energySecurity": "Energy Security and Grid Reliability",
  "environment.resourceDev": "Lignite Extraction and Ore Development",
  "environment.affordability": "Fuel Allocation Efficiency",
  "environment.extraction": "Production Quota Flexibility",
  "society.integration": "Resettler Integration and Social Equality",
  "society.womensOpportunity": "Women in the Workforce and Childcare",
  "society.socialMobility": "Worker Advancement and Cadre Promotion",
  "society.demography": "Birth Rates and Demographic Balance",
  "society.civicLife": "Youth League and Mass Organisations",
  "society.familyStability": "Family Stability and Moral Education",
  "society.tradition": "National Identity and Socialist Patriotism",
  "governance.participation": "Bloc Participation and the National Front",
  "governance.openness": "Civil, Cultural and Information Openness",
  "governance.localAutonomy": "District and Municipal Administration",
  "governance.integrity": "Corruption Control and State Capacity",
  "governance.administration": "State Apparatus Efficiency and Administrative Control",
  "governance.decisiveness": "Leadership Continuity and Central Decision Speed",
  "governance.centralAuthority": "Central Authority and Party Discipline",
  "defense.diplomacy": "Peace Policy and Fraternal Diplomacy",
  "defense.institutions": "Comecon Integration and Socialist Cooperation",
  "defense.softPower": "Socialist Culture and International Standing",
  "defense.security": "National Security and Border Readiness",
  "defense.defenseIndustry": "Defence Industry and Military Science",
  "defense.armedForces": "People's Armed Forces Strength and Readiness",
  "defense.projection": "Alliance Contribution and Forward Defence",
} as const satisfies Record<PoliticalMetricId, string>;

const NAMES_BY_COUNTRY: Record<PoliticalMetricsCountryId, Record<PoliticalMetricId, string>> = {
  US: US_METRIC_NAMES,
  UK: UK_METRIC_NAMES,
  RU: RU_METRIC_NAMES,
  DD: DD_METRIC_NAMES,
};

export function getMetricDisplayName(
  countryId: PoliticalMetricsCountryId,
  id: PoliticalMetricId
): string {
  return NAMES_BY_COUNTRY[countryId][id];
}

const baseCategoryNames = () =>
  Object.fromEntries(POLITICAL_METRIC_CATEGORIES.map((c) => [c.id, c.displayName])) as Record<
    PoliticalMetricCategoryId,
    string
  >;

/** Category display names per country (UK uses its spelling variants from the category table). */
const CATEGORY_NAMES_BY_COUNTRY: Record<
  PoliticalMetricsCountryId,
  Record<PoliticalMetricCategoryId, string>
> = {
  US: baseCategoryNames(),
  UK: Object.fromEntries(
    POLITICAL_METRIC_CATEGORIES.map((c) => [
      c.id,
      ("ukDisplayName" in c && c.ukDisplayName) || c.displayName,
    ])
  ) as Record<PoliticalMetricCategoryId, string>,
  RU: baseCategoryNames(),
  DD: baseCategoryNames(),
};

export function getCategoryDisplayName(
  countryId: PoliticalMetricsCountryId,
  categoryId: PoliticalMetricCategoryId
): string {
  const name = CATEGORY_NAMES_BY_COUNTRY[countryId][categoryId];
  if (!name) throw new Error(`Unknown category: ${categoryId}`);
  return name;
}

/** Masthead chrome per country (from the approved mock's COUNTRIES). */
export const COUNTRY_CHROME: Record<
  PoliticalMetricsCountryId,
  { registry: string; seal: string; glyph: string }
> = {
  US: {
    registry: "Executive Office · National Situation Registry",
    seal: "DEPT OF NATIONAL STATISTICS",
    glyph: "US",
  },
  UK: {
    registry: "Cabinet Office · Central Statistical Office",
    seal: "CENTRAL STATISTICAL OFFICE",
    glyph: "UK",
  },
  RU: {
    registry: "Council of Ministers · Central Statistical Administration",
    seal: "ЦСУ · CENTRAL STATISTICAL ADMIN",
    glyph: "СССР",
  },
  DD: {
    registry: "Council of Ministers · State Central Administration for Statistics",
    seal: "SZS · STATE STATISTICS ADMIN",
    glyph: "DDR",
  },
};
