/**
 * Era-Aware Legislation catalog (Spec A). Single source of truth for WHEN a
 * legislation type may exist. Inert while `eraSystemEnabled` is off: every
 * resolver treats a null year as "legacy" (all types active), so flag-off
 * behavior is byte-identical.
 *
 * EVERY seed legislation type appears here explicitly — windowed types as a
 * number (first fileable year), era-universal types as the literal "always".
 * No silent gaps: legislationCatalog.validation.test.ts asserts the key set
 * equals the live seed catalog exactly, so adding a type without classifying
 * it fails CI.
 *
 * Spec: docs/superpowers/specs/2026-07-06-era-legislation-design.md (Appendix A).
 */

export const LEGISLATION_ERA: Record<string, number | "always"> = {
  // ── Windowed (74) — numbers are the first fileable calendar year ──────────
  // US (8)
  us_broadband_energy: 1998,
  us_state_utilities: 1998,
  us_clean_energy: 1974,
  us_state_environment: 1974,
  us_medicaid: 1965,
  us_medicaid_expansion: 1965,
  us_drug_pricing_medicare: 1965,
  us_paid_family_leave: 1993,
  // UK (6)
  uk_digital_broadband: 1998,
  uk_climate_net_zero: 1990,
  uk_north_sea_energy: 1974,
  uk_mental_health: 1970,
  uk_devolution_local_powers: 1999,
  uk_trident_defence: 1956,
  // DE (18)
  de_digital_infrastructure: 1998,
  de_cybersecurity: 1998,
  de_digital_governance: 1998,
  de_renewable_energy_target: 1974,
  de_carbon_pricing: 1990,
  de_climate_targets: 1990,
  de_nuclear_energy: 1961,
  de_mental_health: 1970,
  de_solidarity_surcharge: 1991,
  de_eu_integration: 1993,
  de_defense_posture: 1956,
  de_bundeswehr_funding: 1956,
  de_wehrpflicht: 1956,
  de_family_policy: 1996,
  de_robotics_ai: 1980,
  de_payroll_social_insurance: 1957,
  de_pension_system: 1957,
  de_integration_programs: 1961,
  // JP (12)
  jp_digital_infrastructure: 1998,
  jp_digital_governance: 1998,
  jp_cybersecurity: 1998,
  jp_nuclear_energy: 1966,
  jp_climate_emissions: 1990,
  jp_renewable_energy: 1974,
  jp_mental_health: 1970,
  jp_foreign_worker_policy: 1990,
  jp_visa_residency: 1990,
  jp_integration_programs: 1990,
  jp_robotics_ai: 1980,
  jp_rd_investment: 1980,
  // IE (9)
  ie_digital_infrastructure: 1998,
  ie_cybersecurity: 1998,
  ie_climate_policy: 1990,
  ie_renewable_energy_target: 1974,
  ie_mental_health: 1970,
  ie_work_visas: 1960,
  ie_integration_programs: 1990,
  ie_immigration_asylum: 2000,
  ie_regional_health: 2005,
  // CN (17)
  cn_common_prosperity: 2021,
  cn_belt_and_road: 2013,
  cn_cybersecurity: 2014,
  cn_internet_governance: 1998,
  cn_hukou_reform: 1958,
  cn_hk_macao_affairs: 1997,
  cn_ai_strategy: 2015,
  cn_semiconductor_strategy: 1986,
  cn_emissions_trading_scheme: 1997,
  cn_climate_targets: 2000,
  cn_nuclear_energy: 1991,
  cn_renewable_energy_target: 1974,
  cn_digital_infrastructure: 1998,
  cn_mental_health: 1970,
  cn_gaokao_reform: 1977,
  cn_pension_system: 1957,
  cn_social_insurance_contribution: 1957,
  // NG (4)
  ng_renewable_energy: 1974,
  ng_digital_economy: 1998,
  ng_petroleum_sector_reform: 1958,
  ng_petroleum_profit_tax: 1959,

  // ── Era-universal (478) — every remaining seed type, explicit "always" ────
  bal_defense_appropriations: "always",
  bal_economic_system: "always",
  bal_enterprise_levy: "always",
  bal_foreign_trade: "always",
  bal_income_tax: "always",
  bal_infrastructure_investment: "always",
  bal_political_system: "always",
  bal_price_controls: "always",
  bal_product_tax: "always",
  bal_public_health_service: "always",
  bal_regional_investment_grants: "always",
  bal_social_insurance: "always",
  bal_social_security_fund: "always",
  bal_state_administration: "always",
  bal_universal_education: "always",
  bg_defense_appropriations: "always",
  bg_economic_system: "always",
  bg_enterprise_levy: "always",
  bg_foreign_trade: "always",
  bg_income_tax: "always",
  bg_infrastructure_investment: "always",
  bg_political_system: "always",
  bg_price_controls: "always",
  bg_product_tax: "always",
  bg_public_health_service: "always",
  bg_regional_investment_grants: "always",
  bg_social_insurance: "always",
  bg_social_security_fund: "always",
  bg_state_administration: "always",
  bg_universal_education: "always",
  blr_defense_appropriations: "always",
  blr_economic_system: "always",
  blr_enterprise_levy: "always",
  blr_foreign_trade: "always",
  blr_income_tax: "always",
  blr_infrastructure_investment: "always",
  blr_political_system: "always",
  blr_price_controls: "always",
  blr_product_tax: "always",
  blr_public_health_service: "always",
  blr_regional_investment_grants: "always",
  blr_social_insurance: "always",
  blr_social_security_fund: "always",
  blr_state_administration: "always",
  blr_universal_education: "always",
  br_corporate_tax: "always",
  br_customs_tariff: "always",
  br_defense_policy: "always",
  br_education_funding: "always",
  br_general_administration: "always",
  br_iap_contribution: "always",
  br_income_tax_rate: "always",
  br_infrastructure_investment: "always",
  br_ivc: "always",
  br_labor_law: "always",
  br_public_health: "always",
  br_social_security_benefits: "always",
  br_state_enterprises: "always",
  br_state_grants: "always",
  cn_academic_pressure_reform: "always",
  cn_agricultural_subsidies: "always",
  cn_anticorruption_campaign: "always",
  cn_conscription: "always",
  cn_criminal_justice: "always",
  cn_customs_tariff: "always",
  cn_diaspora_engagement: "always",
  cn_education_funding: "always",
  cn_elder_care: "always",
  cn_enterprise_income_tax: "always",
  cn_family_policy: "always",
  cn_fiscal_stimulus: "always",
  cn_food_security: "always",
  cn_gender_equality: "always",
  cn_housing: "always",
  cn_individual_income_tax: "always",
  cn_industrial_strategy: "always",
  cn_land_value_added_tax: "always",
  cn_medical_insurance: "always",
  cn_minimum_wage: "always",
  cn_npc_reform: "always",
  cn_pla_modernization: "always",
  cn_press_freedom: "always",
  cn_provincial_culture_propaganda: "always",
  cn_provincial_economic_development: "always",
  cn_provincial_education: "always",
  cn_provincial_environmental_policy: "always",
  cn_provincial_health_services: "always",
  cn_provincial_infrastructure_investment: "always",
  cn_provincial_public_security: "always",
  cn_provincial_resource_tax: "always",
  cn_public_health: "always",
  cn_public_security: "always",
  cn_rail_transport: "always",
  cn_research_science: "always",
  cn_rural_revitalization: "always",
  cn_skilled_immigration: "always",
  cn_stamp_duty: "always",
  cn_state_enterprises: "always",
  cn_state_media_funding: "always",
  cn_taiwan_strait_doctrine: "always",
  cn_un_security_council_posture: "always",
  cn_urban_maintenance_construction_tax: "always",
  cn_us_china_relations: "always",
  cn_value_added_tax: "always",
  cs_defense_appropriations: "always",
  cs_economic_system: "always",
  cs_enterprise_levy: "always",
  cs_foreign_trade: "always",
  cs_income_tax: "always",
  cs_infrastructure_investment: "always",
  cs_political_system: "always",
  cs_price_controls: "always",
  cs_product_tax: "always",
  cs_public_health_service: "always",
  cs_regional_investment_grants: "always",
  cs_social_insurance: "always",
  cs_social_security_fund: "always",
  cs_state_administration: "always",
  cs_universal_education: "always",
  dd_civil_liberties: "always",
  dd_economic_system: "always",
  dd_enterprise_levy: "always",
  dd_foreign_trade: "always",
  dd_housing: "always",
  dd_income_tax: "always",
  dd_political_system: "always",
  dd_price_controls: "always",
  dd_product_tax: "always",
  dd_social_insurance: "always",
  de_academic_reform: "always",
  de_agricultural_subsidies: "always",
  de_animal_welfare: "always",
  de_asylum_policy: "always",
  de_constitutional_protection: "always",
  de_criminal_justice: "always",
  de_customs_tariff_rate: "always",
  de_domestic_corporate_tax_rate: "always",
  de_education_funding: "always",
  de_elder_care: "always",
  de_electoral_reform: "always",
  de_fiscal_stimulus_act: "always",
  de_food_security: "always",
  de_foreign_aid_diplomacy: "always",
  de_foreign_corporate_tax_rate: "always",
  de_gender_equality: "always",
  de_government_ethics: "always",
  de_grundgesetz_reform: "always",
  de_health_insurance: "always",
  de_housing: "always",
  de_immigration_policy: "always",
  de_income_tax_rate: "always",
  de_labor_reform: "always",
  de_land_culture: "always",
  de_land_economic_development: "always",
  de_land_education: "always",
  de_land_health_services: "always",
  de_land_municipal_grants: "always",
  de_land_police: "always",
  de_minimum_wage: "always",
  de_policing_public_safety: "always",
  de_press_freedom: "always",
  de_public_broadcasting: "always",
  de_public_health: "always",
  de_rail_transport: "always",
  de_research_science: "always",
  de_sme_mittelstand: "always",
  de_trade_agreements: "always",
  de_trade_tax: "always",
  de_unemployment_welfare: "always",
  de_university_tuition: "always",
  de_vat_rate: "always",
  es_consumption_tax: "always",
  es_corporate_tax: "always",
  es_customs_tariff: "always",
  es_income_tax: "always",
  es_labor_law: "always",
  es_social_charges: "always",
  es_state_holdings: "always",
  es_welfare_state: "always",
  fr_corporate_tax: "always",
  fr_customs_tariff: "always",
  fr_defense_appropriations: "always",
  fr_economic_subsidies: "always",
  fr_education_funding: "always",
  fr_health_insurance: "always",
  fr_income_tax: "always",
  fr_infrastructure_investment: "always",
  fr_labor_law: "always",
  fr_local_grants: "always",
  fr_nationalization: "always",
  fr_social_charges: "always",
  fr_vat: "always",
  fr_welfare_state: "always",
  hu_defense_appropriations: "always",
  hu_economic_system: "always",
  hu_enterprise_levy: "always",
  hu_foreign_trade: "always",
  hu_income_tax: "always",
  hu_infrastructure_investment: "always",
  hu_political_system: "always",
  hu_price_controls: "always",
  hu_product_tax: "always",
  hu_public_health_service: "always",
  hu_regional_investment_grants: "always",
  hu_social_insurance: "always",
  hu_social_security_fund: "always",
  hu_state_administration: "always",
  hu_universal_education: "always",
  ie_agricultural_subsidies: "always",
  ie_capital_gains_tax: "always",
  ie_childcare_policy: "always",
  ie_corporate_tax_rate: "always",
  ie_criminal_justice: "always",
  ie_curriculum_reform: "always",
  ie_customs_tariff_rate: "always",
  ie_defence_recruitment: "always",
  ie_defence_spending: "always",
  ie_drug_policy: "always",
  ie_education_funding: "always",
  ie_elder_care: "always",
  ie_electoral_reform: "always",
  ie_excise_duty: "always",
  ie_fiscal_stimulus: "always",
  ie_food_security: "always",
  ie_foreign_aid_diplomacy: "always",
  ie_foreign_corporate_tax_rate: "always",
  ie_garda_policing: "always",
  ie_gender_equality: "always",
  ie_government_ethics: "always",
  ie_healthcare_policy: "always",
  ie_higher_education: "always",
  ie_housing_policy: "always",
  ie_income_tax_rate: "always",
  ie_local_property_tax: "always",
  ie_media_press: "always",
  ie_minimum_wage: "always",
  ie_neutrality_posture: "always",
  ie_parental_leave: "always",
  ie_peat_bog_policy: "always",
  ie_prsi: "always",
  ie_public_health: "always",
  ie_regional_economic_development: "always",
  ie_regional_housing: "always",
  ie_regional_skills: "always",
  ie_regional_transport: "always",
  ie_research_science: "always",
  ie_rural_development: "always",
  ie_sme_support: "always",
  ie_stamp_duty: "always",
  ie_state_pensions: "always",
  ie_transport_rail: "always",
  ie_unemployment_benefits: "always",
  ie_usc: "always",
  ie_vat_rate: "always",
  ie_workers_rights: "always",
  ie_workforce_development: "always",
  ie_working_family_payment: "always",
  it_corporate_tax: "always",
  it_customs_tariff: "always",
  it_defense_appropriations: "always",
  it_economic_subsidies: "always",
  it_education_funding: "always",
  it_health_insurance: "always",
  it_income_tax: "always",
  it_infrastructure_investment: "always",
  it_labor_law: "always",
  it_local_grants: "always",
  it_social_charges: "always",
  it_state_holdings: "always",
  it_vat: "always",
  it_welfare_state: "always",
  jp_academic_reform: "always",
  jp_agricultural_subsidies: "always",
  jp_article9_sdf: "always",
  jp_constitutional_reform: "always",
  jp_consumption_tax: "always",
  jp_criminal_justice: "always",
  jp_customs_tariff: "always",
  jp_defense_spending: "always",
  jp_disaster_preparedness: "always",
  jp_domestic_corporation_tax: "always",
  jp_education_funding: "always",
  jp_elder_care: "always",
  jp_electoral_reform: "always",
  jp_family_policy: "always",
  jp_fiscal_stimulus: "always",
  jp_fixed_asset_tax: "always",
  jp_food_security: "always",
  jp_foreign_aid_diplomacy: "always",
  jp_foreign_corporation_tax: "always",
  jp_gender_equality: "always",
  jp_income_tax_rate: "always",
  jp_jsdf_recruitment: "always",
  jp_labor_reform: "always",
  jp_local_allocation_tax: "always",
  jp_media_press: "always",
  jp_minimum_wage: "always",
  jp_national_health_insurance: "always",
  jp_pension: "always",
  jp_policing_public_safety: "always",
  jp_public_health: "always",
  jp_rail_transport: "always",
  jp_regional_agriculture: "always",
  jp_regional_autonomy: "always",
  jp_regional_economic_development: "always",
  jp_regional_education: "always",
  jp_regional_environment: "always",
  jp_regional_governance: "always",
  jp_regional_health: "always",
  jp_regional_policing: "always",
  jp_regional_skills: "always",
  jp_regional_social_services: "always",
  jp_regional_transport: "always",
  jp_regional_utilities: "always",
  jp_research_science: "always",
  jp_resident_tax: "always",
  jp_rural_development: "always",
  jp_sme_support: "always",
  jp_social_insurance: "always",
  jp_trade_agreements: "always",
  jp_university_tuition: "always",
  jp_work_culture_reform: "always",
  ng_agriculture_policy: "always",
  ng_anti_corruption: "always",
  ng_basic_education: "always",
  ng_capital_gains_tax: "always",
  ng_civil_service_reform: "always",
  ng_companies_income_tax: "always",
  ng_counterinsurgency: "always",
  ng_criminal_justice: "always",
  ng_customs_tariff: "always",
  ng_defense_policy: "always",
  ng_disability_inclusion: "always",
  ng_electoral_reform: "always",
  ng_environmental_protection: "always",
  ng_excise_duty: "always",
  ng_federalism: "always",
  ng_fiscal_framework: "always",
  ng_foreign_policy: "always",
  ng_gender_equality: "always",
  ng_health_insurance: "always",
  ng_housing_policy: "always",
  ng_immigration_policy: "always",
  ng_industrial_policy: "always",
  ng_infrastructure_investment: "always",
  ng_judiciary_reform: "always",
  ng_labor_rights: "always",
  ng_land_reform: "always",
  ng_local_government: "always",
  ng_maternal_child_health: "always",
  // Matches its five peers (uk/de/jp/ie/cn_mental_health, all 1970). Mental
  // health as a distinct statutory policy area is a post-1959-Act phenomenon;
  // Nigeria was the only country in the set left on "always", which is an
  // inconsistency rather than a considered exception.
  ng_mental_health: 1970,
  ng_minimum_wage: "always",
  ng_paye: "always",
  ng_pension_system: "always",
  ng_personal_income_tax: "always",
  ng_policing_reform: "always",
  ng_population_policy: "always",
  ng_power_sector_reform: "always",
  ng_press_freedom: "always",
  ng_primary_healthcare: "always",
  ng_public_health: "always",
  ng_regional_integration: "always",
  ng_sme_support: "always",
  ng_social_safety_net: "always",
  ng_solid_minerals: "always",
  ng_stamp_duty: "always",
  ng_technical_education: "always",
  ng_telecommunications: "always",
  ng_tertiary_education: "always",
  ng_trade_promotion: "always",
  ng_vat_rate: "always",
  ng_water_sanitation: "always",
  ng_youth_employment: "always",
  pl_defense_appropriations: "always",
  pl_economic_system: "always",
  pl_enterprise_levy: "always",
  pl_foreign_trade: "always",
  pl_income_tax: "always",
  pl_infrastructure_investment: "always",
  pl_political_system: "always",
  pl_price_controls: "always",
  pl_product_tax: "always",
  pl_public_health_service: "always",
  pl_regional_investment_grants: "always",
  pl_social_insurance: "always",
  pl_social_security_fund: "always",
  pl_state_administration: "always",
  pl_universal_education: "always",
  ro_defense_appropriations: "always",
  ro_economic_system: "always",
  ro_enterprise_levy: "always",
  ro_foreign_trade: "always",
  ro_income_tax: "always",
  ro_infrastructure_investment: "always",
  ro_political_system: "always",
  ro_price_controls: "always",
  ro_product_tax: "always",
  ro_public_health_service: "always",
  ro_regional_investment_grants: "always",
  ro_social_insurance: "always",
  ro_social_security_fund: "always",
  ro_state_administration: "always",
  ro_universal_education: "always",
  se_corporate_tax: "always",
  se_customs_tariff: "always",
  se_defense_appropriations: "always",
  se_economic_subsidies: "always",
  se_education_funding: "always",
  se_health_insurance: "always",
  se_income_tax: "always",
  se_infrastructure_investment: "always",
  se_labor_law: "always",
  se_local_grants: "always",
  se_social_charges: "always",
  se_vat: "always",
  resource_extraction_authority: "always",
  se_wage_earner_funds: "always",
  se_welfare_state: "always",
  senate_filibuster_rules: "always",
  su_agriculture: "always",
  su_civil_liberties: "always",
  su_customs_tariff: "always",
  su_defense_spending: "always",
  su_economic_system: "always",
  su_enterprise_levy: "always",
  su_housing: "always",
  su_individual_income_tax: "always",
  su_political_system: "always",
  su_price_controls: "always",
  su_social_insurance: "always",
  su_turnover_tax: "always",
  at_corporate_tax: "always",
  at_customs_tariff: "always",
  at_defense_appropriations: "always",
  at_economic_subsidies: "always",
  at_education_funding: "always",
  at_health_insurance: "always",
  at_income_tax: "always",
  at_infrastructure_investment: "always",
  at_labor_law: "always",
  at_local_grants: "always",
  at_sales_tax: "always",
  at_social_charges: "always",
  at_state_enterprises: "always",
  at_welfare_state: "always",
  fi_corporate_tax: "always",
  fi_customs_tariff: "always",
  fi_defense_appropriations: "always",
  fi_economic_subsidies: "always",
  fi_education_funding: "always",
  fi_health_insurance: "always",
  fi_income_tax: "always",
  fi_infrastructure_investment: "always",
  fi_labor_law: "always",
  fi_local_grants: "always",
  fi_sales_tax: "always",
  fi_social_charges: "always",
  fi_state_enterprises: "always",
  fi_welfare_state: "always",
  gr_corporate_tax: "always",
  gr_customs_tariff: "always",
  gr_defense_appropriations: "always",
  gr_economic_subsidies: "always",
  gr_education_funding: "always",
  gr_health_insurance: "always",
  gr_income_tax: "always",
  gr_infrastructure_investment: "always",
  gr_labor_law: "always",
  gr_local_grants: "always",
  gr_sales_tax: "always",
  gr_social_charges: "always",
  gr_state_enterprises: "always",
  gr_welfare_state: "always",
  tr_corporate_tax: "always",
  tr_customs_tariff: "always",
  tr_defense_appropriations: "always",
  tr_economic_subsidies: "always",
  tr_education_funding: "always",
  tr_health_insurance: "always",
  tr_income_tax: "always",
  tr_infrastructure_investment: "always",
  tr_labor_law: "always",
  tr_local_grants: "always",
  tr_sales_tax: "always",
  tr_social_charges: "always",
  tr_state_enterprises: "always",
  tr_welfare_state: "always",
  uk_agriculture_policy: "always",
  uk_bbc_public_media: "always",
  uk_business_rates: "always",
  uk_childcare: "always",
  uk_council_tax: "always",
  uk_defence_spending: "always",
  uk_domestic_corporation_tax: "always",
  uk_drug_policy: "always",
  uk_education_funding: "always",
  uk_education_standards: "always",
  uk_electoral_reform: "always",
  uk_energy_grid: "always",
  uk_excise_customs: "always",
  uk_fiscal_spending: "always",
  uk_foreign_corporation_tax: "always",
  uk_foreign_policy: "always",
  uk_government_ethics: "always",
  uk_housing_planning: "always",
  uk_immigration_asylum: "always",
  uk_income_tax_rate: "always",
  uk_leasehold_reform: "always",
  uk_local_government_funding: "always",
  uk_national_insurance: "always",
  uk_national_service: "always",
  uk_nhs_funding: "always",
  uk_policing_crime: "always",
  uk_prison_rehabilitation: "always",
  uk_public_health: "always",
  uk_regional_agriculture: "always",
  uk_regional_economic_development: "always",
  uk_regional_education: "always",
  uk_regional_emergency_services: "always",
  uk_regional_environment: "always",
  uk_regional_governance: "always",
  uk_regional_health: "always",
  uk_regional_housing_development: "always",
  uk_regional_housing_support: "always",
  uk_regional_justice: "always",
  uk_regional_labour: "always",
  uk_regional_policing: "always",
  uk_regional_skills: "always",
  uk_regional_technology: "always",
  uk_regional_transport: "always",
  uk_regional_utilities: "always",
  uk_research_science: "always",
  uk_social_care: "always",
  uk_state_pensions: "always",
  uk_surveillance_privacy: "always",
  uk_technology_policy: "always",
  uk_transport_rail: "always",
  uk_tuition_fees: "always",
  uk_universal_credit: "always",
  uk_vat: "always",
  uk_work_visas: "always",
  uk_workers_rights: "always",
  uk_workforce_development: "always",
  ukr_defense_appropriations: "always",
  ukr_economic_system: "always",
  ukr_enterprise_levy: "always",
  ukr_foreign_trade: "always",
  ukr_income_tax: "always",
  ukr_infrastructure_investment: "always",
  ukr_political_system: "always",
  ukr_price_controls: "always",
  ukr_product_tax: "always",
  ukr_public_health_service: "always",
  ukr_regional_investment_grants: "always",
  ukr_social_insurance: "always",
  ukr_social_security_fund: "always",
  ukr_state_administration: "always",
  ukr_universal_education: "always",
  us_border_security_enforcement: "always",
  us_civics_voting_rights: "always",
  us_conservation: "always",
  us_defense_spending: "always",
  us_emergency_services: "always",
  us_federal_domestic_corporate_tax_rate: "always",
  us_federal_education_funding: "always",
  us_federal_foreign_corporate_tax_rate: "always",
  us_federal_healthcare_funding: "always",
  us_federal_income_tax_rate: "always",
  us_federal_payroll_tax_rate: "always",
  us_federal_sales_tax_rate: "always",
  us_federal_science_funding: "always",
  us_federal_spending_stimulus: "always",
  us_federal_tariff_rate: "always",
  us_food_nutrition: "always",
  us_foreign_policy: "always",
  us_government_ethics: "always",
  us_gun_control: "always",
  us_housing: "always",
  us_law_enforcement_criminal_justice: "always",
  us_legal_immigration_visas: "always",
  us_media_communications: "always",
  us_minimum_wage: "always",
  us_national_service: "always",
  us_prison_rehabilitation: "always",
  us_public_health: "always",
  us_reproductive_rights: "always",
  us_school_standards: "always",
  us_social_security: "always",
  us_state_business_regulation: "always",
  us_state_compactness: "always",
  us_state_domestic_corporate_tax_rate: "always",
  us_state_education_funding: "always",
  us_state_fairness: "always",
  us_state_food_assistance: "always",
  us_state_foreign_corporate_tax_rate: "always",
  us_state_government_ethics: "always",
  us_state_healthcare: "always",
  us_state_higher_education: "always",
  us_state_housing: "always",
  us_state_income_tax_rate: "always",
  us_state_labor: "always",
  us_state_media_communications: "always",
  us_state_minimum_wage: "always",
  us_state_policing: "always",
  us_state_prison_rehabilitation: "always",
  us_state_property_tax_rate: "always",
  us_state_public_health: "always",
  us_state_redistricting_authority: "always",
  us_state_sales_tax_rate: "always",
  us_state_spending_stimulus: "always",
  us_state_transportation: "always",
  us_state_voting_rights: "always",
  us_state_workforce_development: "always",
  us_transportation: "always",
  us_workforce_development: "always",
  yu_defense_appropriations: "always",
  yu_economic_system: "always",
  yu_enterprise_levy: "always",
  yu_foreign_trade: "always",
  yu_income_tax: "always",
  yu_infrastructure_investment: "always",
  yu_political_system: "always",
  yu_price_controls: "always",
  yu_product_tax: "always",
  yu_public_health_service: "always",
  yu_regional_investment_grants: "always",
  yu_social_insurance: "always",
  yu_social_security_fund: "always",
  yu_state_administration: "always",
  yu_universal_education: "always",
};

/**
 * Types whose classification predates their windowed PRIMARY metric — either
 * "always"-shaped (era-universal domain, windowed primary ticks no-op pre-window)
 * or windowed EARLIER than the primary (cn_internet_governance 1998 < socialCredit
 * 2014). Validation rule #2 exempts these; each is a Spec B/C retarget candidate.
 */
export const WINDOW_CONSTRAINT_WAIVERS = new Set<string>([
  "ie_excise_duty",
  "ie_peat_bog_policy",
  "ng_excise_duty",
  "cn_un_security_council_posture",
  "cn_diaspora_engagement",
  "cn_provincial_resource_tax",
  "cn_provincial_environmental_policy",
  "cn_internet_governance",
]);

/** Windowed tax types whose revenue line is consciously gated (vanishes pre-window). */
export const GATED_REVENUE_ACK = new Set<string>([
  "de_solidarity_surcharge",
  "de_payroll_social_insurance",
  "cn_social_insurance_contribution",
  "ng_petroleum_profit_tax",
]);

/** In-game years a freshly-unlocked type wears the "New this era" badge. */
export const NEW_BADGE_YEARS = 2;

/**
 * True if the type may exist at `year`. Null year (flag off / legacy) ⇒ true.
 * "always" ⇒ true. Unknown typeId ⇒ true (fail-open; validation forbids it).
 */
export function isLegislationTypeActive(typeId: string, year: number | null): boolean {
  if (year == null || !Number.isFinite(year)) return true;
  const from = LEGISLATION_ERA[typeId];
  if (from === undefined || from === "always") return true;
  return year >= from;
}

/** True while `from <= year <= from + NEW_BADGE_YEARS`. Null year / "always" ⇒ false. */
export function isNewThisEra(typeId: string, year: number | null): boolean {
  if (year == null || !Number.isFinite(year)) return false;
  const from = LEGISLATION_ERA[typeId];
  if (from === undefined || from === "always") return false;
  return year >= from && year - from <= NEW_BADGE_YEARS;
}
