import type { PartySeed } from "@/lib/seeds/reference/politicalParties";

/**
 * Sweden default political parties.
 *
 *  - 1953: period names — SAP, Högerpartiet, Bondeförbundet, Folkpartiet, SKP.
 *  - 1979: SAP, Moderata samlingspartiet, Centerpartiet, Folkpartiet, VPK
 *    (post-rename landscape of the Swedish model).
 *  - 1991: the seven-party Riksdag elected Sept 1991 — SAP, M, C, FP
 *    continuous from 1979, plus Vänsterpartiet (VPK's 1990 rename),
 *    Kristdemokratiska samhällspartiet (first parliamentary entry) and the
 *    one-election Ny Demokrati insurgency.
 *
 * SAP, Moderaterna, Centerpartiet and Folkpartiet keep the same name across
 * 1979/1991 and are multi-gated. Positions -5..+5.
 */
export const seParties: PartySeed[] = [
  {
    seedOrder: 1,
    countryId: "SE",
    name: "Sveriges socialdemokratiska arbetareparti",
    abbreviation: "SAP",
    color: "#E8112D",
    economicPosition: -2,
    socialPosition: -1,
    foreignPolicy: 0,
    culture: -1,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default", "1979-default", "1991-default"],
    regimeStatus: "approved",
    treasury: 900_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    // Pre-1969 name of today's Moderate party (1979: Moderata samlingspartiet).
    seedOrder: 10,
    countryId: "SE",
    name: "Högerpartiet",
    abbreviation: "H",
    color: "#1B49A2",
    economicPosition: 3,
    socialPosition: 2,
    foreignPolicy: 1,
    culture: 2,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default"],
    regimeStatus: "approved",
    treasury: 650_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 2,
    countryId: "SE",
    name: "Moderata samlingspartiet",
    abbreviation: "M",
    color: "#1B49A2",
    economicPosition: 3,
    socialPosition: 1,
    foreignPolicy: 1,
    culture: 1,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1979-default", "1991-default"],
    regimeStatus: "approved",
    treasury: 650_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    // Pre-1957 name of Centerpartiet.
    seedOrder: 11,
    countryId: "SE",
    name: "Bondeförbundet",
    abbreviation: "BF",
    color: "#009933",
    economicPosition: 0,
    socialPosition: 1,
    foreignPolicy: 0,
    culture: 1,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default"],
    regimeStatus: "approved",
    treasury: 600_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 3,
    countryId: "SE",
    name: "Centerpartiet",
    abbreviation: "C",
    color: "#009933",
    economicPosition: 0,
    socialPosition: 0,
    foreignPolicy: 0,
    culture: 0,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1979-default", "1991-default"],
    regimeStatus: "approved",
    treasury: 600_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 4,
    countryId: "SE",
    name: "Folkpartiet",
    abbreviation: "FP",
    color: "#0066B3",
    economicPosition: 1,
    socialPosition: -1,
    foreignPolicy: 1,
    culture: -1,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default", "1979-default", "1991-default"],
    regimeStatus: "approved",
    treasury: 450_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    // Pre-1967 name of Vänsterpartiet kommunisterna (VPK).
    seedOrder: 12,
    countryId: "SE",
    name: "Sveriges Kommunistiska Parti",
    abbreviation: "SKP",
    color: "#AF0000",
    economicPosition: -4,
    socialPosition: -2,
    foreignPolicy: -2,
    culture: -2,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default"],
    regimeStatus: "approved",
    treasury: 350_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 5,
    countryId: "SE",
    name: "Vänsterpartiet kommunisterna",
    abbreviation: "VPK",
    color: "#AF0000",
    economicPosition: -4,
    socialPosition: -2,
    foreignPolicy: -1,
    culture: -2,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1979-default"],
    regimeStatus: "approved",
    treasury: 350_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  // ─── 1991 Riksdag additions ─────────────────────────────────────────────
  {
    // VPK renamed itself Vänsterpartiet in 1990, dropping "kommunisterna".
    seedOrder: 6,
    countryId: "SE",
    name: "Vänsterpartiet",
    abbreviation: "V",
    color: "#AF0000",
    economicPosition: -4,
    socialPosition: -2,
    foreignPolicy: -1,
    culture: -2,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1991-default"],
    regimeStatus: "approved",
    treasury: 300_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    // First cleared the 4% threshold in the Sept 1991 election.
    seedOrder: 7,
    countryId: "SE",
    name: "Kristdemokratiska samhällspartiet",
    abbreviation: "KDS",
    color: "#0A6E45",
    economicPosition: 1,
    socialPosition: 3,
    foreignPolicy: 1,
    culture: 3,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1991-default"],
    regimeStatus: "approved",
    treasury: 200_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    // Bert Karlsson/Ian Wachtmeister's populist-protest insurgency; entered
    // the Riksdag Sept 1991, gone by 1994.
    seedOrder: 8,
    countryId: "SE",
    name: "Ny Demokrati",
    abbreviation: "NyD",
    color: "#F6A800",
    economicPosition: 3,
    socialPosition: 3,
    foreignPolicy: 1,
    culture: 3,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1991-default"],
    regimeStatus: "approved",
    treasury: 150_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
];

export default seParties;
