import { beforeEach, describe, expect, it, vi } from "vitest";
import type { Db } from "mongodb";
import { createMockDb, type MockDb } from "@/lib/test-utils/mockDb";
import { GET } from "./route";

vi.mock("@/lib/mongodb", () => ({ getDb: vi.fn() }));
vi.mock("@/lib/auth", () => ({ getAuthUser: vi.fn() }));
vi.mock("@/lib/utils/network", () => ({ getClientIp: vi.fn() }));
vi.mock("@/lib/countryAccess", () => ({ getEnabledCountryIds: vi.fn() }));
vi.mock("@/lib/wiki/autoGeneratedPages", () => ({
  getGeneratedOfficeDefinitions: vi.fn(),
  getGeneratedOfficePageSummaries: vi.fn(),
}));

let db: MockDb;

function req(rawQuery: string) {
  return new Request(`http://localhost/api/search/universal?${rawQuery}`);
}

async function getDbMock() {
  const { getDb } = await import("@/lib/mongodb");
  return vi.mocked(getDb);
}

beforeEach(async () => {
  vi.clearAllMocks();
  db = createMockDb();
  (await getDbMock()).mockResolvedValue(db as unknown as Db);
  const { getAuthUser } = await import("@/lib/auth");
  vi.mocked(getAuthUser).mockResolvedValue(null);
  const { getClientIp } = await import("@/lib/utils/network");
  vi.mocked(getClientIp).mockResolvedValue("127.0.0.1");
  const { getEnabledCountryIds } = await import("@/lib/countryAccess");
  vi.mocked(getEnabledCountryIds).mockResolvedValue([] as never);
  const { getGeneratedOfficeDefinitions, getGeneratedOfficePageSummaries } =
    await import("@/lib/wiki/autoGeneratedPages");
  vi.mocked(getGeneratedOfficeDefinitions).mockResolvedValue([]);
  vi.mocked(getGeneratedOfficePageSummaries).mockResolvedValue([]);
});

describe("GET /api/search/universal query length limits", () => {
  it("rejects a 201-character query with HTTP 400", async () => {
    const res = await GET(req(`q=${"a".repeat(201)}`));

    expect(res.status).toBe(400);
    await expect(res.json()).resolves.toEqual({ error: expect.any(String) });
  });

  it("rejects an overlong query before touching the database", async () => {
    await GET(req(`q=${"a".repeat(1000)}`));

    expect(await getDbMock()).not.toHaveBeenCalled();
  });

  it("accepts a query of exactly 200 characters", async () => {
    const res = await GET(req(`q=${"a".repeat(200)}`));

    expect(res.status).toBe(200);
    await expect(res.json()).resolves.toEqual({ results: [] });
    expect(await getDbMock()).toHaveBeenCalled();
  });

  it("measures the cap after trimming, like the minimum length", async () => {
    const res = await GET(req(`q=${" ".repeat(4)}${"a".repeat(200)}${" ".repeat(4)}`));

    expect(res.status).toBe(200);
  });

  it("preserves the minimum-length behavior for short queries", async () => {
    for (const rawQuery of ["q=", "q=x"]) {
      const res = await GET(req(rawQuery));
      expect(res.status).toBe(200);
      await expect(res.json()).resolves.toEqual({ results: [] });
    }
    expect(await getDbMock()).not.toHaveBeenCalled();
  });
});
