import { NextResponse } from "next/server";
import { getDb } from "@/lib/mongodb";
import { getGameStateCollection } from "@/lib/db/collections";
import { handleRouteError } from "@/lib/api/errors";
import { getAuthUser } from "@/lib/auth";
import { checkRateLimit, rateLimitResponse } from "@/lib/api/rateLimit";
import { getClientIp } from "@/lib/utils/network";
import { getEnabledCountryIds } from "@/lib/countryAccess";
import { COUNTRY_CONFIGS, type CountryId } from "@/lib/constants/countries";
import { formatElectionTypeLabel } from "@/lib/utils/electionLabels";
import {
  getGeneratedOfficeDefinitions,
  getGeneratedOfficePageSummaries,
  type GeneratedOfficeDefinition,
} from "@/lib/wiki/autoGeneratedPages";
import { regionUrl } from "@/lib/urls";
import type {
  Character,
  NPP,
  ElectedOfficial,
  Election,
  User,
  Corporation,
  Bill,
  StateBill,
  WikiPage,
  Bond,
} from "@/lib/db/types";
import { BOND_MATURITY_LABELS } from "@/lib/db/types/bond";

export interface SearchResult {
  type:
    | "politician"
    | "seat"
    | "region"
    | "election"
    | "corporation"
    | "bill"
    | "page"
    | "commodity"
    | "currency"
    | "bond"
    | "admin";
  id: string;
  title: string;
  subtitle: string;
  href: string;
  icon: string;
}

/**
 * Pure resolver: takes the already-loaded generated-office definitions rather
 * than fetching per official. `getGeneratedOfficeDefinitionForOffice` rebuilds
 * the whole definition list behind an uncached `getEnabledCountryIds()` DB read,
 * so calling it once per official made this an N+1 over the result page.
 */
function resolveOfficialSearchTarget(
  official: ElectedOfficial,
  officeDefinitions: GeneratedOfficeDefinition[]
): {
  type: SearchResult["type"];
  title: string;
  subtitle: string;
  href: string;
} | null {
  const countryId = (official.countryId ?? "US") as CountryId;
  const countryName = COUNTRY_CONFIGS[countryId]?.name ?? countryId;
  const generatedOffice = official.officeType
    ? (officeDefinitions.find(
        (definition) =>
          definition.kind === "executive" &&
          definition.countryId === countryId &&
          definition.officeType === official.officeType
      ) ?? null)
    : null;
  if (generatedOffice) {
    return {
      type: "page",
      title: generatedOffice.title,
      subtitle: `Office history · ${countryName}`,
      href: `/wiki/${generatedOffice.slug}`,
    };
  }

  const state = official.state?.toLowerCase();
  if (countryId === COUNTRY_CONFIGS.US.id && state) {
    if (official.officeType === "senate" && official.senateClass) {
      return {
        type: "seat",
        title: `${official.state} ${formatElectionTypeLabel("senate", countryId)} (Class ${official.senateClass})`,
        subtitle: `Federal Office · ${official.state}`,
        href: `/wiki/seat/${state}-senate-class-${official.senateClass}`,
      };
    }
    if (official.officeType === "house") {
      return {
        type: "seat",
        title: `${official.state} ${formatElectionTypeLabel("house", countryId)} Delegation`,
        subtitle: `Federal Office · ${official.state}`,
        href: `/wiki/seat/${state}-house`,
      };
    }
    if (official.officeType === "governor") {
      return {
        type: "seat",
        title: `${official.state} Governor`,
        subtitle: `State Office · ${official.state}`,
        href: `/wiki/seat/${state}-governor`,
      };
    }
  }

  if (official.state) {
    const officeLabel =
      COUNTRY_CONFIGS[countryId]?.officeTypes.find((office) => office.key === official.officeType)
        ?.label ?? official.officeType;
    return {
      type: "region",
      title: `${official.state} ${officeLabel}`,
      subtitle: `${countryName} regional office`,
      href: regionUrl(countryId, official.state),
    };
  }

  return null;
}

// GET /api/search/universal — Searches across politicians, NPPs, elected seats, and active elections by query string.
// Auth: public
// Errors: (none)
export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const query = searchParams.get("q")?.trim() || "";

    // Return empty results for empty or too-short queries. A 1-character query
    // forces a near-full scan of every searched collection.
    if (query.length < 2) {
      return NextResponse.json({ results: [] });
    }

    const authUser = await getAuthUser();
    const isAdmin = authUser?.isAdmin === true;
    const isModerator = authUser?.isModerator === true;

    // Rate limit: this endpoint runs case-insensitive regex across many large
    // collections (an expensive scan), so cap requests per user — or per IP when
    // unauthenticated — to prevent DoS amplification.
    const rateLimitKey = authUser?.userId ?? `ip:${await getClientIp()}`;
    const searchRate = checkRateLimit(`search:${rateLimitKey}`, 30, 60_000);
    if (!searchRate.ok) {
      return rateLimitResponse(searchRate.retryAfter);
    }

    const enabledCountries = isAdmin ? undefined : await getEnabledCountryIds();

    const db = await getDb();
    const results: SearchResult[] = [];

    // Escape special regex characters to prevent ReDoS
    const escapedQuery = query.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const searchRegex = new RegExp(escapedQuery, "i");

    // Search player characters (excluding banned users)
    const characterQuery: Record<string, unknown> = {
      $or: [{ name: searchRegex }, { party: searchRegex }, { homeState: searchRegex }],
    };
    if (enabledCountries) {
      characterQuery.countryId = { $in: enabledCountries };
    }
    const characters = await db
      .collection<Character>("characters")
      .find(characterQuery)
      .limit(5)
      .toArray();

    // Get user IDs to check ban status
    const userIds = characters.map((c) => c.userId);
    const users = await db
      .collection<User>("users")
      .find({ _id: { $in: userIds } })
      .toArray();
    const bannedUserIds = new Set(users.filter((u) => u.isBanned).map((u) => u._id.toString()));

    // Filter out banned users and add to results
    for (const character of characters) {
      if (!bannedUserIds.has(character.userId.toString())) {
        results.push({
          type: "politician",
          id: character._id.toString(),
          title: character.name,
          subtitle: `${character.party} · ${character.homeState}`,
          href: `/character/${character.sequentialId ?? character._id.toString()}`,
          icon: "👤",
        });
      }
    }

    // Search users by discordUsername — when someone types a Discord handle,
    // find their characters and surface them in results (unless already found by name).
    const discordUsers = await db
      .collection<User>("users")
      .find({
        $and: [{ discordUsername: { $exists: true, $ne: "" } }, { discordUsername: searchRegex }],
      })
      .project<User>({ _id: 1 })
      .limit(5)
      .toArray();

    if (discordUsers.length > 0) {
      const discordUserIds = discordUsers.map((u) => u._id);
      const existingCharIds = new Set(characters.map((c) => c._id.toString()));

      const discordChars = await db
        .collection<Character>("characters")
        .find({ userId: { $in: discordUserIds } })
        .limit(5)
        .toArray();

      // Fetch users for newly discovered characters to check ban status
      const newUserIds = discordChars
        .map((c) => c.userId)
        .filter((uid) => !userIds.some((existing) => existing.equals(uid)));

      if (newUserIds.length > 0) {
        const bannedCheck = await db
          .collection<User>("users")
          .find({ _id: { $in: newUserIds }, isBanned: true })
          .project<User>({ _id: 1 })
          .toArray();
        for (const u of bannedCheck) {
          bannedUserIds.add(u._id.toString());
        }
      }

      for (const character of discordChars) {
        if (existingCharIds.has(character._id.toString())) continue;
        if (!bannedUserIds.has(character.userId.toString())) {
          results.push({
            type: "politician",
            id: character._id.toString(),
            title: character.name,
            subtitle: `${character.party} · ${character.homeState}`,
            href: `/character/${character.sequentialId ?? character._id.toString()}`,
            icon: "👤",
          });
        }
      }
    }

    // Search elected officials (seats)
    const officialsQuery: Record<string, unknown> = {
      $or: [{ state: searchRegex }, { officeType: searchRegex }],
    };
    if (enabledCountries) {
      officialsQuery.countryId = { $in: enabledCountries };
    }
    const officials = await db
      .collection<ElectedOfficial>("electedOfficials")
      .find(officialsQuery)
      .limit(5)
      .toArray();

    // Loaded once for the whole result page — the resolver below is pure.
    const officeDefinitions = officials.length > 0 ? await getGeneratedOfficeDefinitions() : [];
    for (const official of officials) {
      const target = resolveOfficialSearchTarget(official, officeDefinitions);
      if (target) {
        results.push({
          type: target.type,
          id: official._id.toString(),
          title: target.title,
          subtitle: target.subtitle,
          href: target.href,
          icon: "🏛️",
        });
      }
    }

    // Search elections
    const electionsQuery: Record<string, unknown> = {
      status: { $in: ["active", "upcoming"] },
      $or: [{ state: searchRegex }, { electionType: searchRegex }],
    };
    if (enabledCountries) {
      electionsQuery.countryId = { $in: enabledCountries };
    }
    const elections = await db
      .collection<Election>("elections")
      .find(electionsQuery)
      .limit(5)
      .toArray();

    for (const election of elections) {
      let electionTitle = "";
      let electionSubtitle = "";

      if (election.electionType === "president") {
        electionTitle = "Presidential Election";
        electionSubtitle = `${election.status === "active" ? "Active" : "Upcoming"} · President`;
      } else if (election.electionType === "senate") {
        electionTitle = `${election.state} ${formatElectionTypeLabel("senate", (election.countryId ?? "US") as CountryId)} Election`;
        electionSubtitle = `${election.status === "active" ? "Active" : "Upcoming"} · Senate`;
      } else if (election.electionType === "house") {
        electionTitle = `${election.state} ${formatElectionTypeLabel("house", (election.countryId ?? "US") as CountryId)} Election`;
        electionSubtitle = `${election.status === "active" ? "Active" : "Upcoming"} · House`;
      } else if (election.electionType === "governor") {
        electionTitle = `${election.state} Governor Election`;
        electionSubtitle = `${election.status === "active" ? "Active" : "Upcoming"} · Governor`;
      } else if (election.electionType === "stateSenate") {
        electionTitle = `${election.state} State Senate Election`;
        electionSubtitle = `${election.status === "active" ? "Active" : "Upcoming"} · State Senate`;
      }

      if (electionTitle) {
        results.push({
          type: "election",
          id: election._id.toString(),
          title: electionTitle,
          subtitle: electionSubtitle,
          href: `/elections/${election._id.toString()}`,
          icon: "🗳️",
        });
      }
    }

    // Search corporations
    const corpQuery: Record<string, unknown> = {};
    if (enabledCountries) {
      corpQuery.countryId = { $in: enabledCountries };
    }
    const corporationQuery: Record<string, unknown> = {
      $or: [{ name: searchRegex }, { description: searchRegex }],
      ...corpQuery,
    };
    const corporations = await db
      .collection<Corporation>("corporations")
      .find(corporationQuery)
      .limit(5)
      .toArray();

    // Batched CEO name lookup — avoids one findOne per corp.
    const ceoIds = corporations.map((c) => c.ceoId).filter((id): id is typeof id & {} => !!id);
    const ceoChars = ceoIds.length
      ? await db
          .collection<Character>("characters")
          .find({ _id: { $in: ceoIds } })
          .project<{ _id: (typeof ceoIds)[number]; name: string }>({ name: 1 })
          .toArray()
      : [];
    const ceoNameById = new Map(ceoChars.map((c) => [c._id.toString(), c.name]));

    for (const corp of corporations) {
      const ceoName = corp.ceoId ? (ceoNameById.get(corp.ceoId.toString()) ?? "") : "";
      results.push({
        type: "corporation",
        id: corp._id.toString(),
        title: corp.name,
        subtitle: `${corp.type} · ${ceoName ? `CEO: ${ceoName}` : corp.headquartersState}`,
        href: `/corporation/${corp.sequentialId ?? corp._id.toString()}`,
        icon: "🏢",
      });
    }

    // Search federal bills (legislation collection)
    const billQuery: Record<string, unknown> = {
      $or: [{ title: searchRegex }, { summary: searchRegex }, { sponsorName: searchRegex }],
    };
    if (enabledCountries) {
      billQuery.countryId = { $in: enabledCountries };
    }
    const bills = await db.collection<Bill>("legislation").find(billQuery).limit(5).toArray();

    for (const bill of bills) {
      const statusLabel = bill.status.replace(/_/g, " ");
      results.push({
        type: "bill",
        id: bill._id.toString(),
        title: bill.title,
        subtitle: `${statusLabel} · Sponsor: ${bill.sponsorName}`,
        href: `/congress/bills/${bill._id.toString()}`,
        icon: "📜",
      });
    }

    // Search state bills
    const stateBillQuery: Record<string, unknown> = {
      $or: [{ title: searchRegex }, { summary: searchRegex }, { sponsorName: searchRegex }],
    };
    if (enabledCountries) {
      stateBillQuery.countryId = { $in: enabledCountries };
    }
    const stateBills = await db
      .collection<StateBill>("stateBills")
      .find(stateBillQuery)
      .limit(5)
      .toArray();

    for (const bill of stateBills) {
      const statusLabel = bill.status.replace(/_/g, " ");
      results.push({
        type: "bill",
        id: bill._id.toString(),
        title: bill.title,
        subtitle: `${statusLabel} · ${bill.stateId || "State"} · Sponsor: ${bill.sponsorName}`,
        href: `/country/us/region/${bill.stateId || "national"}/legislature/bills/${bill._id.toString()}`,
        icon: "📜",
      });
    }

    // Search wiki pages (static pages like UK parliament, commodity info, etc.).
    // When the wiki is globally disabled, only admins/moderators can reach it,
    // so suppress results for everyone else to avoid dead links that redirect away.
    const gameStateCol = await getGameStateCollection(db);
    const gameState = await gameStateCol.findOne({ _id: "current" });
    const wikiDisabled = gameState?.wikiDisabled === true;
    if (!wikiDisabled || isAdmin || isModerator) {
      const wikiQuery: Record<string, unknown> = {
        status: "published",
        $or: [{ title: searchRegex }, { description: searchRegex }, { content: searchRegex }],
      };
      // Private pages are only visible to admins and moderators.
      if (!isAdmin && !isModerator) {
        (wikiQuery as Record<string, unknown>).private = { $ne: true };
      }
      const wikiPages = await db
        .collection<WikiPage>("wikiPages")
        .find(wikiQuery)
        .limit(5)
        .toArray();

      for (const page of wikiPages) {
        results.push({
          type: "page",
          id: page._id.toString(),
          title: page.title,
          subtitle: page.description || "Wiki page",
          href: `/wiki/${page.slug}`,
          icon: "📄",
        });
      }

      const generatedOfficeQuery = query.toLowerCase();
      for (const page of await getGeneratedOfficePageSummaries()) {
        if (
          page.title.toLowerCase().includes(generatedOfficeQuery) ||
          page.description.toLowerCase().includes(generatedOfficeQuery)
        ) {
          if (results.some((result) => result.href === page.href)) continue;
          results.push({
            type: "page",
            id: `generated-office-${page.slug}`,
            title: page.title,
            subtitle: page.description,
            href: page.href,
            icon: "📄",
          });
        }
      }
    }

    const lowerQuery = query.toLowerCase();

    // Search commodities
    const { COMMODITY_TYPES, COMMODITY_LABELS } = await import("@/lib/constants/commodities");
    const matchedCommodities = COMMODITY_TYPES.filter(
      (type) =>
        (COMMODITY_LABELS[type] ?? "").toLowerCase().includes(lowerQuery) ||
        type.toLowerCase().includes(lowerQuery)
    );

    for (const commodityType of matchedCommodities.slice(0, 5)) {
      results.push({
        type: "commodity",
        id: commodityType,
        title: COMMODITY_LABELS[commodityType],
        subtitle: "Market & price data",
        href: `/commodity/${commodityType}`,
        icon: "📦",
      });
    }

    // Search currencies — no CURRENCY_CONFIGS export exists; build from active list.
    const { FOREX_ACTIVE_CURRENCIES, CURRENCY_ANCHOR_COUNTRY } =
      await import("@/lib/constants/currencies");
    const { UK_REGIONS } = await import("@/lib/constants/uk");
    const { JP_REGIONS } = await import("@/lib/constants/japan");
    const CURRENCY_NAMES: Record<string, string> = {
      USD: "US Dollar",
      GBP: "British Pound",
      JPY: "Japanese Yen",
      EUR: "Euro",
      CAD: "Canadian Dollar",
    };
    // Currency → anchor country (GBP→UK, EUR→DE) — NOT a reverse of
    // COUNTRY_CURRENCY_MAP, whose last-wins entry would mis-resolve shared
    // currencies (GBP is held by UK/SCO/WAL) to a latent/non-anchor country.
    const countryIdByCurrency = new Map(
      (Object.entries(CURRENCY_ANCHOR_COUNTRY) as [string, keyof typeof COUNTRY_CONFIGS][]).map(
        ([ccy, cid]) => [ccy, cid]
      )
    );
    const matchedCurrencies = FOREX_ACTIVE_CURRENCIES.filter((code) => {
      const name = CURRENCY_NAMES[code] ?? code;
      const countryId = countryIdByCurrency.get(code);
      const countryName = countryId ? COUNTRY_CONFIGS[countryId].name : "";
      return (
        code.toLowerCase().includes(lowerQuery) ||
        name.toLowerCase().includes(lowerQuery) ||
        countryName.toLowerCase().includes(lowerQuery)
      );
    });

    for (const currencyCode of matchedCurrencies.slice(0, 5)) {
      const name = CURRENCY_NAMES[currencyCode] ?? currencyCode;
      const countryId = countryIdByCurrency.get(currencyCode);
      const countryName = countryId ? COUNTRY_CONFIGS[countryId].name : "Forex";
      results.push({
        type: "currency",
        id: currencyCode,
        title: `${name} (${currencyCode})`,
        subtitle: countryName,
        href: `/forex/global?filter=${currencyCode}`,
        icon: "💱",
      });
    }

    // Search national country pages
    const countryPageMap: Record<string, string> = {
      US: "/country/us",
      UK: "/country/uk",
      DE: "/country/de",
      JP: "/country/jp",
    };
    for (const [cid, cconfig] of Object.entries(COUNTRY_CONFIGS)) {
      if (!countryPageMap[cid]) continue;
      if (enabledCountries && !enabledCountries.includes(cid as (typeof enabledCountries)[number]))
        continue;
      if (cconfig.name.toLowerCase().includes(lowerQuery) || cid.toLowerCase() === lowerQuery) {
        results.push({
          type: "page",
          id: `country-${cid}`,
          title: cconfig.name,
          subtitle: "National Overview",
          href: countryPageMap[cid],
          icon: "🌍",
        });
      }
    }

    // Search US states (regions)
    const STATE_MAP: Record<string, string> = {
      AL: "Alabama",
      AK: "Alaska",
      AZ: "Arizona",
      AR: "Arkansas",
      CA: "California",
      CO: "Colorado",
      CT: "Connecticut",
      DE: "Delaware",
      FL: "Florida",
      GA: "Georgia",
      HI: "Hawaii",
      ID: "Idaho",
      IL: "Illinois",
      IN: "Indiana",
      IA: "Iowa",
      KS: "Kansas",
      KY: "Kentucky",
      LA: "Louisiana",
      ME: "Maine",
      MD: "Maryland",
      MA: "Massachusetts",
      MI: "Michigan",
      MN: "Minnesota",
      MS: "Mississippi",
      MO: "Missouri",
      MT: "Montana",
      NE: "Nebraska",
      NV: "Nevada",
      NH: "New Hampshire",
      NJ: "New Jersey",
      NM: "New Mexico",
      NY: "New York",
      NC: "North Carolina",
      ND: "North Dakota",
      OH: "Ohio",
      OK: "Oklahoma",
      OR: "Oregon",
      PA: "Pennsylvania",
      RI: "Rhode Island",
      SC: "South Carolina",
      SD: "South Dakota",
      TN: "Tennessee",
      TX: "Texas",
      UT: "Utah",
      VT: "Vermont",
      VA: "Virginia",
      WA: "Washington",
      WV: "West Virginia",
      WI: "Wisconsin",
      WY: "Wyoming",
    };
    for (const [abbr, sname] of Object.entries(STATE_MAP)) {
      if (sname.toLowerCase().includes(lowerQuery) || abbr.toLowerCase().includes(lowerQuery)) {
        results.push({
          type: "region",
          id: `region-${abbr}`,
          title: sname,
          subtitle: "US State",
          href: `/country/us/region/${abbr}`,
          icon: "📍",
        });
      }
    }

    // Search UK regions
    if (!enabledCountries || enabledCountries.includes("UK")) {
      for (const region of UK_REGIONS) {
        if (
          region.name.toLowerCase().includes(lowerQuery) ||
          region.id.toLowerCase() === lowerQuery
        ) {
          results.push({
            type: "region",
            id: `uk-region-${region.id}`,
            title: region.name,
            subtitle: "UK Region",
            href: `/country/uk/region/${region.id}`,
            icon: "📍",
          });
        }
      }
    }

    // Search JP regions
    if (!enabledCountries || enabledCountries.includes("JP")) {
      for (const region of JP_REGIONS) {
        if (
          region.name.toLowerCase().includes(lowerQuery) ||
          region.id.toLowerCase() === lowerQuery
        ) {
          results.push({
            type: "region",
            id: `jp-region-${region.id}`,
            title: region.name,
            subtitle: "Japan Region",
            href: `/country/jp/region/${region.id}`,
            icon: "📍",
          });
        }
      }
    }

    // Search DE states (Bundesländer)
    if (!enabledCountries || enabledCountries.includes("DE")) {
      const DE_STATE_MAP: Record<string, string> = {
        BW: "Baden-Württemberg",
        BY: "Bayern",
        NW: "Nordrhein-Westfalen",
        HE: "Hessen",
        RP: "Rheinland-Pfalz",
        SL: "Saarland",
        NI: "Niedersachsen",
        SH: "Schleswig-Holstein",
        HH: "Hamburg",
        HB: "Bremen",
        BE: "Berlin",
        BB: "Brandenburg",
        MV: "Mecklenburg-Vorpommern",
        SN: "Sachsen",
        ST: "Sachsen-Anhalt",
        TH: "Thüringen",
      };
      for (const [abbr, sname] of Object.entries(DE_STATE_MAP)) {
        if (sname.toLowerCase().includes(lowerQuery) || abbr.toLowerCase() === lowerQuery) {
          results.push({
            type: "region",
            id: `de-region-${abbr}`,
            title: sname,
            subtitle: "German State",
            href: `/country/de/region/${abbr}`,
            icon: "📍",
          });
        }
      }
    }

    // Search bonds — match by corporation name or ticker, not "first 5 bonds".
    const bondCorpMatchQuery: Record<string, unknown> = {
      $or: [{ name: searchRegex }, { ticker: searchRegex }],
    };
    if (enabledCountries) {
      bondCorpMatchQuery.countryId = { $in: enabledCountries };
    }
    const bondCorpMatches = await db
      .collection<Corporation>("corporations")
      .find(bondCorpMatchQuery)
      .project<{ _id: Corporation["_id"]; name: string; ticker?: string }>({ name: 1, ticker: 1 })
      .limit(10)
      .toArray();

    if (bondCorpMatches.length > 0) {
      const matchedCorpIds = bondCorpMatches.map((c) => c._id);
      const bondQuery: Record<string, unknown> = { corporationId: { $in: matchedCorpIds } };
      if (enabledCountries) {
        bondQuery.countryId = { $in: enabledCountries };
      }
      const bonds = await db.collection<Bond>("bonds").find(bondQuery).limit(5).toArray();
      const corpNameById = new Map(bondCorpMatches.map((c) => [c._id.toString(), c.name]));

      for (const bond of bonds) {
        const corpName = corpNameById.get(bond.corporationId.toString()) || "Unknown Corp";
        results.push({
          type: "bond",
          id: bond._id.toString(),
          title: `${corpName} Bond`,
          subtitle: `${BOND_MATURITY_LABELS[bond.maturityTurns]} · ${bond.currencyCode || "₳"}${(bond.faceValue / 1000).toFixed(1)}K`,
          href: `/bond/${bond._id.toString()}`,
          icon: "📊",
        });
      }
    }

    // NPPs appended last — player characters, corps, seats, elections, bills, commodities,
    // currencies, and bonds always rank above autonomous NPCs in the unified result list.
    const nppQuery: Record<string, unknown> = {
      retiredAt: null,
      $or: [{ name: searchRegex }, { party: searchRegex }, { homeState: searchRegex }],
    };
    if (enabledCountries) {
      nppQuery.countryId = { $in: enabledCountries };
    }
    const npps = await db.collection<NPP>("npps").find(nppQuery).limit(5).toArray();

    for (const npp of npps) {
      results.push({
        type: "politician",
        id: npp._id.toString(),
        title: npp.name,
        subtitle: `${npp.party} · ${npp.homeState} · NPP`,
        href: `/politicians/npp/${npp._id.toString()}`,
        icon: "👤",
      });
    }

    // Admin search results — only visible to admins
    if (isAdmin) {
      const adminTabs: Array<{
        name: string;
        label: string;
        icon: string;
        subtabs?: Array<{ name: string; label: string }>;
      }> = [
        { name: "dashboard", label: "Dashboard", icon: "📊" },
        { name: "traffic", label: "Traffic", icon: "📈" },
        {
          name: "politics",
          label: "Politics",
          icon: "🏛️",
          subtabs: [
            { name: "elections", label: "Elections" },
            { name: "parties", label: "Parties" },
            { name: "legislation", label: "Legislation" },
            { name: "law-types", label: "Law Types" },
          ],
        },
        {
          name: "economy",
          label: "Economy",
          icon: "💰",
          subtabs: [
            { name: "central-banks", label: "Central Banks" },
            { name: "stock-market", label: "Stock Market" },
            { name: "forex", label: "Forex" },
            { name: "corporations", label: "Corporations" },
            { name: "bonds", label: "Bonds" },
            { name: "commodities", label: "Commodities" },
            { name: "resource-capacity", label: "Resource Capacity" },
            { name: "budgets", label: "Budgets" },
            { name: "npp-economy", label: "NPP Economy" },
          ],
        },
        {
          name: "world",
          label: "World",
          icon: "🌍",
          subtabs: [
            { name: "demographics", label: "Demographics" },
            { name: "npps", label: "NPPs" },
            { name: "politicians", label: "Politicians" },
            { name: "crises", label: "Crises" },
            { name: "countries", label: "Countries" },
          ],
        },
        {
          name: "players",
          label: "Players",
          icon: "👥",
          subtabs: [
            { name: "users", label: "Users" },
            { name: "resources", label: "Resources" },
            { name: "achievements", label: "Achievements" },
            { name: "patreon", label: "Patreon" },
            { name: "characters", label: "Characters" },
            { name: "activity-log", label: "Activity Log" },
            { name: "suspicious", label: "Suspicious Activity" },
            { name: "moderators", label: "Moderators" },
            { name: "mod-audit-log", label: "Mod Audit Log" },
            { name: "ip-bans", label: "IP Bans" },
          ],
        },
        {
          name: "content",
          label: "Content",
          icon: "📄",
          subtabs: [
            { name: "wiki", label: "Wiki" },
            { name: "wiki-review", label: "Wiki Review" },
            { name: "roadmap", label: "Roadmap" },
          ],
        },
        {
          name: "support",
          label: "Support",
          icon: "🆘",
          subtabs: [
            { name: "suggestions", label: "Suggestions" },
            { name: "feedback", label: "Feedback" },
            { name: "logs", label: "Logs" },
            { name: "debug", label: "Debug" },
            { name: "migrations", label: "Migrations" },
            { name: "mail-reports", label: "Mail Reports" },
          ],
        },
        {
          name: "system",
          label: "System",
          icon: "⚙️",
          subtabs: [
            { name: "seed", label: "Seed" },
            { name: "universal-seeder", label: "Universal Seeder" },
            { name: "reset", label: "Reset" },
            { name: "heal", label: "Heal" },
            { name: "game-health", label: "Game Health" },
            { name: "code-quality", label: "Code Quality" },
            { name: "integrations", label: "Integrations" },
          ],
        },
      ];

      for (const tab of adminTabs) {
        // Match main tab name and label
        if (
          tab.label.toLowerCase().includes(lowerQuery) ||
          tab.name.toLowerCase().includes(lowerQuery)
        ) {
          results.push({
            type: "admin",
            id: tab.name,
            title: tab.label,
            subtitle: "Admin Panel",
            href: `/admin?tab=${tab.name}`,
            icon: tab.icon,
          });
        }

        // Match subtabs if present
        if (tab.subtabs) {
          for (const subtab of tab.subtabs) {
            if (
              subtab.label.toLowerCase().includes(lowerQuery) ||
              subtab.name.toLowerCase().includes(lowerQuery)
            ) {
              results.push({
                type: "admin",
                id: `${tab.name}-${subtab.name}`,
                title: subtab.label,
                subtitle: `${tab.label}`,
                href: `/admin?tab=${tab.name}&sub=${subtab.name}`,
                icon: tab.icon,
              });
            }
          }
        }
      }
    }

    // Relevance ranking: title exact/prefix matches outrank substring matches,
    // so a query like "steel" surfaces the Steel commodity over unrelated names.
    const scoreResult = (r: SearchResult): number => {
      const title = r.title.toLowerCase();
      if (title === lowerQuery) return 0;
      if (title.startsWith(lowerQuery)) return 1;
      const idx = title.indexOf(lowerQuery);
      if (idx !== -1) return 2 + idx / 100;
      return 5;
    };
    const rankedResults = [...results].sort((a, b) => scoreResult(a) - scoreResult(b));
    const limitedResults = rankedResults.slice(0, 10);

    return NextResponse.json({ results: limitedResults });
  } catch (error) {
    return handleRouteError(error);
  }
}
