import type { PartySeed } from "@/lib/seeds/reference/politicalParties";

/**
 * Turkey default political parties.
 *
 *  - 1953: Demokrat Parti (DP, Menderes government since 1950) + CHP.
 *  - 1979: AP, CHP, MSP, MHP — late-1970s deadlock before the 1980 coup.
 *  - 1991: the 1980 coup banned every pre-coup party and its leadership, so
 *    the October 1991 election was contested entirely by post-1983 vehicles —
 *    DYP / ANAP / SHP / RP / DSP. None of these are the same legal entity as
 *    their 1979 namesakes even where a lineage is claimed (e.g. RP vs MSP,
 *    DSP vs CHP), so they are new entries rather than extensions.
 *
 * Positions -5..+5. Each entry is gated via `validForPresets`.
 */
export const trParties: PartySeed[] = [
  // ─── 1953 DP era ───────────────────────────────────────────────────────
  {
    seedOrder: 10,
    countryId: "TR",
    name: "Demokrat Parti",
    abbreviation: "DP",
    color: "#C8102E",
    economicPosition: 2, // liberalizing, pro-private enterprise vs CHP étatism
    socialPosition: 2, // conservative, rural/religious appeal
    foreignPolicy: 2, // NATO member (1952), pro-US Cold War alignment
    culture: 2,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default"],
    regimeStatus: "approved",
    treasury: 850_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  // ─── 1979 pre-coup ─────────────────────────────────────────────────────
  {
    seedOrder: 1,
    countryId: "TR",
    name: "Adalet Partisi",
    abbreviation: "AP",
    color: "#0A4DA2",
    economicPosition: 2,
    socialPosition: 2,
    foreignPolicy: 1,
    culture: 2,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1979-default"],
    regimeStatus: "approved",
    treasury: 800_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 2,
    countryId: "TR",
    name: "Cumhuriyet Halk Partisi",
    abbreviation: "CHP",
    color: "#E30613",
    economicPosition: -2,
    socialPosition: -1,
    foreignPolicy: 0,
    culture: -2,
    memberCount: 0,
    isDefault: true,
    // CHP continuous from single-party era through multiparty republic.
    validForPresets: ["1953-default", "1979-default"],
    regimeStatus: "approved",
    treasury: 750_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 3,
    countryId: "TR",
    name: "Milli Selamet Partisi",
    abbreviation: "MSP",
    color: "#1F7A33",
    economicPosition: 0,
    socialPosition: 4,
    foreignPolicy: 0,
    culture: 4,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1979-default"],
    regimeStatus: "approved",
    treasury: 450_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 4,
    countryId: "TR",
    name: "Milliyetçi Hareket Partisi",
    abbreviation: "MHP",
    color: "#B71C1C",
    economicPosition: 1,
    socialPosition: 4,
    foreignPolicy: 2,
    culture: 4,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1979-default"],
    regimeStatus: "approved",
    treasury: 400_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  // ─── 1991 post-coup Third Republic ─────────────────────────────────────
  {
    // Demirel's centre-right liberal successor vehicle; won the Oct 1991
    // election and formed government.
    seedOrder: 5,
    countryId: "TR",
    name: "Doğru Yol Partisi",
    abbreviation: "DYP",
    color: "#0A4DA2",
    economicPosition: 2,
    socialPosition: 1,
    foreignPolicy: 1,
    culture: 1,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1991-default"],
    regimeStatus: "approved",
    treasury: 700_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    // Özal's party; governed 1983-91, market-liberalisation architects.
    seedOrder: 6,
    countryId: "TR",
    name: "Anavatan Partisi",
    abbreviation: "ANAP",
    color: "#00529B",
    economicPosition: 3,
    socialPosition: 1,
    foreignPolicy: 2,
    culture: 1,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1991-default"],
    regimeStatus: "approved",
    treasury: 650_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    // Social-democratic successor tradition to the banned CHP; junior
    // partner in the 1991 DYP-SHP coalition government.
    seedOrder: 7,
    countryId: "TR",
    name: "Sosyaldemokrat Halkçı Parti",
    abbreviation: "SHP",
    color: "#E30613",
    economicPosition: -2,
    socialPosition: -1,
    foreignPolicy: 0,
    culture: -2,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1991-default"],
    regimeStatus: "approved",
    treasury: 550_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    // Erbakan's post-ban Islamist vehicle, refounded 1983; MSP's
    // ideological but not legal successor.
    seedOrder: 8,
    countryId: "TR",
    name: "Refah Partisi",
    abbreviation: "RP",
    color: "#1F7A33",
    economicPosition: 0,
    socialPosition: 4,
    foreignPolicy: 0,
    culture: 4,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1991-default"],
    regimeStatus: "approved",
    treasury: 400_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    // Ecevit's post-ban vehicle, refounded 1985; the CHP-legacy left's other
    // wing alongside SHP.
    seedOrder: 9,
    countryId: "TR",
    name: "Demokratik Sol Parti",
    abbreviation: "DSP",
    color: "#C8102E",
    economicPosition: -2,
    socialPosition: 0,
    foreignPolicy: 1,
    culture: -1,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1991-default"],
    regimeStatus: "approved",
    treasury: 350_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
];

export default trParties;
