import type { CollectionEntry } from "./seedManifestTypes";

// ─── Runtime collections ─────────────────────────────────────────────────────
// Wiped on reset; regenerated by gameplay/turns/actions.

export const RUNTIME: CollectionEntry[] = [
  { name: "demographicFlowReceipts", category: "runtime" },
  { name: "demographicFlowProjections", category: "runtime" },
  // Federation decisions and their applied world state belong to one world.
  { name: "federationPoliticalProposals", category: "runtime" },
  { name: "russianConstitutionalProposals", category: "runtime" },
  { name: "russianPresidentialElectionResults", category: "runtime" },
  { name: "russianPresidentialOfficeArchives", category: "runtime" },
  { name: "russianDumaElectionResults", category: "runtime" },
  { name: "russianDumaRepeatOpenings", category: "runtime" },
  { name: "russianCouncilElectionOpenings", category: "runtime" },
  { name: "russianCouncilElectionResults", category: "runtime" },
  { name: "russianAssemblySeatings", category: "runtime" },
  { name: "russianDumaConvocations", category: "runtime" },
  { name: "russianCouncilFormationProposals", category: "runtime" },
  { name: "russianDumaLawProposals", category: "runtime" },
  { name: "russianRegionalAuthorities", category: "runtime" },
  { name: "russianCouncilCompositionSeatings", category: "runtime" },
  { name: "bgOrdinaryElectionPlans", category: "runtime" },
  { name: "bgFoundingAssemblyCounts", category: "runtime" },
  { name: "bgFoundingAssemblyFilingLocks", category: "runtime" },
  { name: "bgFoundingAssemblyOfficeArchives", category: "runtime" },
  { name: "bg1991ListReplacements", category: "runtime" },
  { name: "bgGrandConstituencyByElections", category: "runtime" },
  { name: "bgAssemblyOfficeArchives", category: "runtime" },
  { name: "russianAssemblyOfficeArchives", category: "runtime" },
  { name: "federationRatifications", category: "runtime" },
  { name: "federationSettlementIntents", category: "runtime" },
  { name: "federationFacilityClaims", category: "runtime" },
  { name: "federationFacilityPaymentTurns", category: "runtime" },
  { name: "federationRelocations", category: "runtime" },
  { name: "federationPublicationPreparations", category: "runtime" },
  { name: "federationPreparedEffects", category: "runtime" },
  { name: "federationArchivedRegionRows", category: "runtime" },
  { name: "federationArchivedPoliticalRows", category: "runtime" },
  { name: "federationCustodyRecords", category: "runtime" },
  { name: "federationArchivedPublicCorporations", category: "runtime" },
  { name: "federationPublicCorporationRebases", category: "runtime" },
  { name: "federationPrivateFirmHolds", category: "runtime" },
  { name: "federationResidentHolds", category: "runtime" },
  { name: "federationFiscalAccounts", category: "runtime" },
  { name: "federationLegacyServiceTurns", category: "runtime" },
  { name: "federationContinuingServiceTurns", category: "runtime" },
  { name: "federationSettlementApplications", category: "runtime" },
  { name: "worldEntityStates", category: "runtime" },
  {
    name: "resetMetricSnapshots",
    category: "runtime",
    notes:
      "World-bound 1991 v2 primary-metric boards for US, UK, and JP. Wiped on every reset; populated and read back only when the metrics v2 opening is selected. Never replaces v1 working stores in place.",
  },
  {
    name: "resetLawOpeningBoards",
    category: "runtime",
    notes:
      "World-bound 1991 source-law crosswalk for US, UK, and JP, including regional boards. Wiped on every reset and reseeded only for a verified legislation-v2 opening. It records current law, not reviewed enactment options.",
  },
  {
    name: "resetRegionalOpeningBoards",
    category: "runtime",
    notes:
      "World-bound 1991 regional source-pool allocation for 71 US, UK, and JP regions. The proportional allocation is a provisional opening claim against each regional budget, not a Cabinet account or enactment price.",
  },
  {
    name: "resetDepartmentOpeningBoards",
    category: "runtime",
    notes:
      "World-bound reconciled 1991 Cabinet operating claims for US, UK, and JP. Wiped on reset; these are opening claims, not spendable cash or a live department treasury.",
  },
  {
    name: "resetDepartmentAccounts",
    category: "runtime",
    notes:
      "World-bound v2 Cabinet accounts derived once from reconciled 1991 claims after reserving regional grants. Ordinary departments receive no opening cash; Defense and intelligence retain their specialized settlement shell. Wiped on every reset.",
  },
  {
    name: "resetDepartmentContinuity",
    category: "runtime",
    notes:
      "World-bound v2 existing-service continuity and unattributed grant reserve. It is not spendable Cabinet cash and is wiped on every reset.",
  },
  {
    name: "resetNationalTreasuries",
    category: "runtime",
    notes:
      "World-bound v2 national cash, arrears, bond debt, and emergency-advance opening. Kept apart from the legacy signed budget balance and wiped on reset.",
  },
  {
    name: "resetLawPrograms",
    category: "runtime",
    notes:
      "World-bound enacted v2 national and regional law programs. Replaced by family, linked to the enacting bill, and wiped on every reset.",
  },
  {
    name: "resetLawEnactmentReceipts",
    category: "runtime",
    notes:
      "Exactly-once receipts for v2 law fiscal transitions. The turn reconciliation phase uses them to retry a failed enactment hook safely. Wiped on reset.",
  },
  {
    name: "resetCabinetActionStates",
    category: "runtime",
    notes:
      "World-bound cooldown and active-effect state for v2 ministerial actions. Wiped on reset.",
  },
  {
    name: "ukPartyLeadership",
    category: "runtime",
    notes:
      "Per-party Westminster leadership rules, committee history, and active challenge pointer.",
  },
  {
    name: "ukLeadershipChallenges",
    category: "runtime",
    notes: "Westminster leadership challenge gathering, ballot, and resolution state.",
  },
  {
    name: "sentNewsDedup",
    category: "runtime",
    notes:
      "Short-lived Discord news delivery claims. Wiped with the game world and rebuilt on demand.",
  },
  {
    name: "bondMarketPools",
    category: "runtime",
    notes:
      "One bond market pool per currency: the cash side of every bond's publicFloat, with lifetime flow counters. Seeded by migration from a share of M2; wiped with the world.",
  },
  {
    name: "bankTreasuryTrades",
    category: "runtime",
    notes:
      "Durable frozen intents and recovery receipts for funded bank sovereign treasury trades. Wiped with the game world.",
  },
  {
    name: "equityMarketPools",
    category: "runtime",
    notes:
      "One equity market pool per currency: finite cash backing every corporation's publicFloat, with lifetime flow counters. Seeded from a share of M2; wiped with the world.",
  },
  {
    name: "moneySupplySnapshots",
    category: "runtime",
    notes: "Per-turn M1/M2, credit, sovereign-debt, and central-bank holdings by issuing currency.",
  },
  {
    name: "economicVitalSigns",
    category: "runtime",
    notes:
      "Versioned per-turn aggregate market, production, distribution, money, and reconciliation indicators for economic evaluation.",
  },
  {
    name: "nppMarketEntryFunnels",
    category: "runtime",
    notes:
      "Current and 48-turn retained NPP market-entry outcomes with one exclusive reason per corporation.",
  },
  {
    name: "ledgerTurnoverByTurn",
    category: "runtime",
    notes:
      "Cached per-turn, per-account primary-leg ledger turnover for completed turns, summed for the economic vital signs window. Keyed by turn; wiped with the world.",
  },
  {
    name: "ledgerReconciliations",
    category: "runtime",
    notes:
      "Per-turn shadow-ledger trial-balance, stock-flow, and money-supply reconciliation reports.",
  },
  {
    name: "ledgerEntries",
    category: "runtime",
    notes:
      "Shadow double-entry ledger rows retained for audit, reconciliation, and velocity analysis.",
  },
  {
    name: "balanceSnapshots",
    category: "runtime",
    notes:
      "Per-turn anchor-valued account balances used for stock-flow and money-activity analysis.",
  },
  // Elections + officials
  { name: "elections", category: "runtime" },
  { name: "electionCandidates", category: "runtime" },
  { name: "hu1991AssemblyCounts", category: "runtime" },
  { name: "hu1991AssemblyOfficeArchives", category: "runtime" },
  { name: "hu1991ConstituencyByElections", category: "runtime" },
  { name: "hu1991AssemblyFilingLocks", category: "runtime" },
  { name: "hu1991ListReplacements", category: "runtime" },
  { name: "hu1994ElectoralProposals", category: "runtime" },
  { name: "hu2011ElectoralProposals", category: "runtime" },
  { name: "ro1992ElectoralProposals", category: "runtime" },
  { name: "bg1991ConstitutionalProposals", category: "runtime" },
  { name: "bg1991ConstitutionalInitiatives", category: "runtime" },
  { name: "hu2011AssemblyCounts", category: "runtime" },
  { name: "hu2011ConstituencyByElections", category: "runtime" },
  { name: "hu2011AssemblyOfficeArchives", category: "runtime" },
  { name: "electionVoteTallies", category: "runtime" },
  {
    name: "electionResultSnapshots",
    category: "runtime",
    notes:
      "Frozen results for ended races. Tied to the world election records, wiped on reset, and rebuilt by the migration or by election resolution.",
  },
  { name: "ukCommonsVacancies", category: "runtime" },
  { name: "ukRecallPetitions", category: "runtime" },
  { name: "ukPartyConferences", category: "runtime" },
  { name: "ukPartyPlatforms", category: "runtime" },
  {
    name: "electedOfficials",
    category: "runtime",
    notes: "Seeded by bootstrap (historical or vacant), then driven by elections.",
  },
  {
    name: "officials",
    category: "runtime",
    notes: "Legacy synonym of electedOfficials; left in place for older code paths.",
  },

  // NPPs
  { name: "npps", category: "runtime" },
  { name: "nppInfluenceAttempts", category: "runtime" },
  { name: "nppRelationships", category: "runtime" },
  { name: "nppEndorsements", category: "runtime" },
  { name: "nppVoteCommitments", category: "runtime" },
  { name: "nppVotePredictions", category: "runtime" },
  {
    name: "nppForeignPolicyDecisions",
    category: "runtime",
    notes:
      "One auditable autonomous foreign-policy intent per country and turn. Shadow-mode rows are wiped on reset and never mutate gameplay state.",
  },
  { name: "playerEndorsements", category: "runtime" },
  { name: "playerEndorsementLocks", category: "runtime" },

  // Bills + legislation runtime
  { name: "bills", category: "runtime" },
  { name: "stateBills", category: "runtime" },
  { name: "billWhips", category: "runtime" },
  { name: "enactedLaws", category: "runtime" },
  { name: "tariffs", category: "runtime" },
  { name: "subsidies", category: "runtime" },
  {
    name: "legislation",
    category: "runtime",
    notes: "Legacy bills collection retained for older code paths.",
  },

  // Caucuses + coalitions
  { name: "coalitions", category: "runtime" },
  { name: "caucuses", category: "runtime" },
  { name: "caucusMemberships", category: "runtime" },
  { name: "caucusPolicyPositions", category: "runtime" },
  { name: "caucusChairCandidates", category: "runtime" },
  { name: "caucusChairElections", category: "runtime" },
  { name: "caucusChairVotes", category: "runtime" },

  // Recruitment + slates
  { name: "recruitmentSlates", category: "runtime" },
  { name: "slateCandidates", category: "runtime" },

  // Treasury + political capital
  { name: "treasuryTransactions", category: "runtime" },
  { name: "politicalCapitalBalances", category: "runtime" },
  { name: "capitalActionLogs", category: "runtime" },

  // State-party elections
  { name: "statePartyElections", category: "runtime" },
  { name: "statePartyVotes", category: "runtime" },
  { name: "statePartyCandidates", category: "runtime" },

  // National party / committee elections
  { name: "nationalPartyCandidates", category: "runtime" },
  { name: "nationalPartyElections", category: "runtime" },
  { name: "nationalPartyVotes", category: "runtime" },
  { name: "nationalCommitteeCandidates", category: "runtime" },
  { name: "nationalCommitteeElections", category: "runtime" },
  { name: "nationalCommitteeVotes", category: "runtime" },
  {
    name: "nationalPartyLeadership",
    category: "runtime",
    notes: "Per-party national leadership (chair/treasurer). Per-game state; cleared on reset.",
  },

  // Legislative leadership
  { name: "leadershipElections", category: "runtime" },
  { name: "houseLeadershipBallots", category: "runtime" },
  { name: "houseLeadershipNominations", category: "runtime" },
  { name: "senateLeadershipNominations", category: "runtime" },
  { name: "speakerElections", category: "runtime" },
  { name: "speakerNominations", category: "runtime" },
  { name: "pmAppointmentVotes", category: "runtime" },
  { name: "noConfidenceVotes", category: "runtime" },
  { name: "confidenceVotes", category: "runtime" },
  { name: "congressLeaders", category: "runtime" },

  // Cabinet + government
  { name: "cabinetMembers", category: "runtime" },
  { name: "cabinetNominations", category: "runtime" },
  { name: "cabinetSettings", category: "runtime" },
  // Spent acting-appointment charges (one per seat, per presidency). Runtime:
  // written only when a President installs an acting secretary, and it must
  // outlive the cabinetMembers row it authorised, which is deleted on expiry.
  { name: "actingAppointmentCharges", category: "runtime" },

  // SCOTUS (#3598) — Justice office stored off-currentOffice (mirrors
  // centralBanks); Senate-confirmation lifecycle mirrors cabinetNominations.
  { name: "supremeCourtSeats", category: "runtime" },
  { name: "scotusNominations", category: "runtime" },

  // FOMC — committee seats live on centralBanks.fomcBoard; the President's
  // per-seat nomination → Senate-confirmation lifecycle mirrors cabinetNominations.
  { name: "fomcNominations", category: "runtime" },
  { name: "docketCases", category: "runtime" },
  { name: "committeeProposals", category: "runtime" },
  { name: "ministerialOrders", category: "runtime" },
  { name: "governmentApprovals", category: "runtime" },
  { name: "governmentFormations", category: "runtime" },
  { name: "governmentAccountability", category: "runtime" },
  { name: "parliamentaryGovernments", category: "runtime" },
  { name: "ukCabinetCooldowns", category: "runtime" },
  { name: "ukGovernment", category: "runtime" },
  { name: "ukDevolution", category: "runtime" },

  // Corporations + markets
  { name: "corporations", category: "runtime" },
  { name: "corporationCeoVotes", category: "runtime" },
  { name: "corporationHistory", category: "runtime" },
  { name: "corporationPortfolioHistory", category: "runtime" },
  { name: "corporationPrivatizationVotes", category: "runtime" },
  { name: "corporationVotes", category: "runtime" },
  { name: "corporateSectors", category: "runtime" },
  {
    name: "manufacturingProductProjectsV2",
    category: "runtime",
    notes:
      "Active product development projects, including paid progress and plant allocations. Reset with corporations and sectors; per-turn development receipts are embedded on corporations and are wiped with those rows.",
  },
  {
    name: "mediaProductProjectsV1",
    category: "runtime",
    notes:
      "Media product slates and their paid development state belong to the current world. Reset with their corporations and sectors.",
  },
  {
    name: "productVentures",
    category: "runtime",
    notes:
      "Funded product ventures (development, released boost windows). Reset with their corporations; per-turn debit receipts are embedded on corporations and wiped with those rows.",
  },
  {
    name: "pendingNationalizations",
    category: "runtime",
    notes: "Legislative takings in their notice window; resolved/cleared in the corp turn.",
  },
  {
    name: "nationalizationAuctions",
    category: "runtime",
    notes: "Privatization auctions on spun-out corps; opened/resolved by gameplay.",
  },
  {
    name: "nationalizationLedger",
    category: "runtime",
    notes: "Append-only record of each nationalization taking (acquisition register).",
  },
  { name: "extractionContracts", category: "runtime" },
  {
    name: "prospectingSurveys",
    category: "runtime",
    notes:
      "Geological surveys (resource prospecting). Launched by corps/governments, resolved by the prospectingResolution turn phase. Regenerated by gameplay; wiped on reset.",
  },
  { name: "investorRankingSnapshots", category: "runtime" },
  { name: "marketCapHistory", category: "runtime" },
  { name: "marketIndexIntraday", category: "runtime" },
  { name: "marketCapTicks", category: "runtime" },
  { name: "shareListings", category: "runtime" },
  { name: "shareOffers", category: "runtime" },
  { name: "shareOrders", category: "runtime" },
  { name: "shareTradeHistory", category: "runtime" },
  { name: "stockExchangeSnapshots", category: "runtime" },

  // Bonds
  { name: "bonds", category: "runtime" },
  { name: "bondHistory", category: "runtime" },

  // Private banking (1.1)
  { name: "bankLoans", category: "runtime" },
  { name: "financialCrisisFiscalActions", category: "runtime" },
  { name: "financialCrisisCreditHistory", category: "runtime" },
  { name: "bankMoneyMoves", category: "runtime" },
  { name: "sovereignCouponClaims", category: "runtime" },
  { name: "bankLiquidityOperations", category: "runtime" },
  { name: "monetaryOperationCommands", category: "runtime" },
  { name: "reservePoolTransferCommands", category: "runtime" },
  {
    name: "savingsAccounts",
    category: "runtime",
    notes:
      "Authoritative savings accounts, one per owner and currency; legacy character savings fields are projections of these.",
  },
  { name: "bankCharterHistory", category: "runtime" },
  {
    name: "bankGuarantees",
    category: "runtime",
    notes:
      "Government guarantees created during financial-crisis responses. Tied to the current world's banks and treasury commitments; wiped on reset.",
  },
  {
    name: "financialCrisisBankActions",
    category: "runtime",
    notes:
      "Idempotency records for crisis recapitalization, guarantee, and resolution actions. Wiped with the crisis and bank state they reference.",
  },
  { name: "depositInsuranceFunds", category: "runtime" },
  {
    name: "bankFailurePoliticalEvents",
    category: "runtime",
    notes:
      "Funded bank-failure political receipts belong to the current world and are wiped on reset.",
  },
  {
    name: "interbankLoans",
    category: "runtime",
    notes: "Retail/universal banks lending non-reserved cash to investment/universal banks.",
  },
  {
    name: "bankingLaws",
    category: "runtime",
    notes: "Per-country banking separation law and rate corridors, enacted by bill or chair.",
  },

  // Forex + commodities runtime
  { name: "currencyOrders", category: "runtime" },
  { name: "tradeHistory", category: "runtime" },
  { name: "commodityPriceHistory", category: "runtime" },
  {
    name: "commodityFlows",
    category: "runtime",
    notes:
      "Per-turn global supply/demand/clearing ledger rows (one per commodity per turn), written by commodityPriceTurn. Regenerated by turns.",
  },
  {
    name: "commoditySourcingFlows",
    category: "runtime",
    notes:
      "Record-only landed-price sourcing ledger (one doc per commodity per turn, state-level flows), written by commodityPriceTurn. Regenerated by turns, 48-turn retention.",
  },
  {
    name: "sourcingNetworkLoad",
    category: "runtime",
    notes:
      "Per-turn per-state freight capacity consumed by the sourcing pass (bulk/special). Regenerated by turns, 48-turn retention.",
  },
  {
    name: "commodityQuality",
    category: "runtime",
    notes:
      "Per-commodity aggregate quality state (sector-quality system), recomputed in the corp turn.",
  },
  {
    name: "supplyListings",
    category: "runtime",
    notes: "Nonbinding supply offers; tied to corporations, which are wiped on reset.",
  },
  {
    name: "supplyAgreements",
    category: "runtime",
    notes: "Player corp-to-corp supply agreements; tied to corporations, which are wiped on reset.",
  },
  {
    name: "advertisingAgreements",
    category: "runtime",
    notes:
      "Coverage-backed corp-to-corp advertising agreements (allocation shares of buyer marketing budgets); tied to corporations, which are wiped on reset.",
  },
  {
    name: "advertisingSettlements",
    category: "runtime",
    notes:
      "Recent per-turn advertising attribution for buyers with agreements (settled, contracted, spot, effective spend); regenerated by turns, wiped on reset.",
  },
  {
    name: "commodityPrice",
    category: "runtime",
    notes:
      "Legacy singular-named collection. Production data lives in commodityPrices (plural). Flagged in KNOWN_INCONSISTENCIES.",
  },

  // Financial ledgers
  { name: "financialTxLog", category: "runtime" },
  {
    name: "nonAtomicMoneyFlowReceipts",
    category: "runtime",
    notes:
      "Crash-recovery receipts for standalone-Mongo money flows. Each receipt belongs to this world and must be wiped with its balances on reset.",
  },
  { name: "locLedger", category: "runtime" },
  { name: "savingsLedger", category: "runtime" },
  { name: "portfolioHistory", category: "runtime" },

  // Counters + snapshots
  {
    name: "counters",
    category: "runtime",
    notes:
      "Sequential ID counters. Wiped on reset so newly-seeded entities start at 1 (otherwise the unique sequentialId index collides with deleted-then-respawned defaults).",
  },
  { name: "federalBudgetSnapshots", category: "runtime" },
  { name: "primarySnapshots", category: "runtime" },
  {
    name: "primarySnapshot",
    category: "runtime",
    notes: "Legacy singular-named twin of primarySnapshots. Flagged in KNOWN_INCONSISTENCIES.",
  },
  { name: "gameHealthSnapshots", category: "runtime" },
  {
    name: "stateDemographicsBackup",
    category: "runtime",
    notes:
      "Pre-reseed snapshots of stateDemographics written by /api/admin/demographics/reseed (last 3 per country+era kept).",
  },

  // Game state
  {
    name: "gameState",
    category: "runtime",
    notes:
      "Singleton (_id: 'current'). Reset re-initializes to turn 1; not deleted, just updated in place.",
  },
  { name: "countryGameStates", category: "runtime" },
  { name: "countryHistory", category: "runtime" },
  {
    name: "countryState",
    category: "runtime",
    notes:
      "Per-country runtime mutable fields (governmentType, rulingPartyId, opsVoteMultipliers, hasLeaderConfidenceModel) promoted out of COUNTRY_CONFIGS. Seeded by runCoreSeed via seedAllCountryStates (idempotent). Wiped on reset so mid-game regime mutations (Stage-4 conversions, convention ratifications) don't survive a fresh world.",
  },
  {
    name: "regimeEscalation",
    category: "runtime",
    notes:
      "Per-country one-party-state escalation state (currentStage, dwellCounters, decision queue, transition history). Driven by the per-turn regimeEscalationTurn from popularLegitimacy + partyConfidence. Wiped on reset so mid-game crises don't survive a fresh world; the per-turn driver self-heals a 'stable' row on first tick.",
  },

  // Sovereign / crisis
  { name: "crises", category: "runtime" },
  {
    name: "climateFeedbackState",
    category: "runtime",
    notes:
      "Accumulated world climate pressure derived from regional emissions. Wiped with the world and rebuilt annually during play.",
  },
  {
    name: "livingConflicts",
    category: "runtime",
    notes:
      "Release 1.3 persistent phased world-conflict state. One row per authored definition; wiped on reset so phase, pressure, intensity, and clocks cannot leak into a new world.",
  },
  {
    name: "coldWarTension",
    category: "runtime",
    notes:
      "Release 1.3 shared tension value and event ledger. Wiped on reset and recreated at the era-appropriate arsenal pressure floor.",
  },
  {
    name: "nuclearPrograms",
    category: "runtime",
    notes:
      "Per-country nuclear research, stockpile, and production orders. Wiped on reset and recreated from game-scaled historical baselines without automatic production.",
  },
  {
    name: "covertNuclearPrograms",
    category: "runtime",
    notes:
      "Per-country covert nuclear programme: stage, progress, funding, suspicion, exposure count and breakout turn. Runtime — wiped on reset, rebuilt by play. Omitting it here meant `resetGameWorld` (which sweeps `getRuntimeCollectionNames()`) left every prior campaign's covert programme standing, so a fresh world could open with a country already mid-breakout.",
  },
  {
    name: "intelligenceAgencies",
    category: "runtime",
    notes:
      "One intelligence agency per country: director, tradecraft, counter-intelligence posture, budget, and the lazily refreshed per-turn operation slots. Runtime — wiped on reset, rebuilt by play.",
  },
  {
    name: "intelligenceNetworks",
    category: "runtime",
    notes:
      "One row per (owner, target) pair: network level, build progress, suspicion, and burn cooldown. This is an operator's ACCESS to a target country. Runtime — wiped on reset, rebuilt by play.",
  },
  {
    name: "intelligenceCoverage",
    category: "runtime",
    notes:
      "One row per (owner, target, domain). Stores the reading at collection time; the live value is derived on read from lastCollectedTurn, so nothing rewrites these rows each turn. Runtime — wiped on reset, rebuilt by play.",
  },
  {
    name: "intelligenceOpLog",
    category: "runtime",
    notes:
      "Append-only record of resolved intelligence operations, carrying both the outcome and compromise axes plus the roll detail for audit and simulation reports. Runtime — wiped on reset, rebuilt by play.",
  },
  { name: "sovereignCrisisDecisions", category: "runtime" },
  { name: "globalAlerts", category: "runtime" },
  { name: "wireEvents", category: "runtime" },
  { name: "sentimentPulses", category: "runtime" },

  // News + campaign + comms
  { name: "newsPosts", category: "runtime" },
  { name: "newsReactions", category: "runtime" },
  { name: "campaigns", category: "runtime" },
  { name: "notifications", category: "runtime" },
  { name: "eventInstances", category: "runtime" },
  { name: "eventCooldownLedger", category: "runtime" },
  {
    name: "countryModifiers",
    category: "runtime",
    notes:
      "Temporary event-sourced country modifiers (e.g. world-event sector demand boosts); expire by turn number. Regenerated by gameplay; must not survive resets.",
  },
  {
    name: "playerMail",
    category: "runtime",
    notes:
      "Character-to-character mail. World state, wiped on reset. A reported message survives as the snapshot on its playerMailReports row.",
  },
  { name: "posts", category: "runtime" },
  { name: "partyDiscussionPosts", category: "runtime" },
  { name: "partyHistory", category: "runtime" },
  { name: "influenceHistory", category: "runtime" },

  // IMF / org runtime
  { name: "organizationLeadership", category: "runtime" },
  { name: "organizationLegislation", category: "runtime" },
  { name: "organizationMemberships", category: "runtime" },
  { name: "organizationWithdrawals", category: "runtime" },

  // Misc gameplay
  { name: "blackjackPendingWagers", category: "runtime" },
  { name: "actionLogs", category: "runtime" },
  {
    name: "activityLog",
    category: "runtime",
    notes:
      "Mixed collection. World rows (turn_summary, game_action, fund_event, party_change) are read by turn number and recent-activity windows, so they are wiped on reset. Login/logout rows (IP, user agent, fingerprint, tracking id) and character_deleted markers are account history that alt detection and the moderation dossier read; reset keeps them. Partial delete in resetGameWorld (PRESERVED_ACTIVITY_LOG_TYPES); the 30-day TTL still bounds everything.",
  },
  { name: "turnLogs", category: "runtime" },
  {
    name: "singleplayerRuntime",
    category: "runtime",
    notes: "Local pause state resets with the world.",
  },

  // ── 2026-06 manifest-completeness backfill ─────────────────────────────────
  // Collections that existed in code but were never classified, so they
  // silently survived resets. Grouped by subsystem. Added alongside the move to
  // a manifest-driven reset wipe (resetGameWorld now wipes every runtime entry).

  // Governor's / Presidential Office (derived executive state; reset re-seeds
  // office-state rows via seedOfficeStates).
  { name: "governorOfficeState", category: "runtime" },
  { name: "governorAddresses", category: "runtime" },
  { name: "governorExecutiveOrders", category: "runtime" },
  { name: "governorEndorsements", category: "runtime" },
  { name: "governorLegislationQueue", category: "runtime" },
  { name: "executiveEndorsements", category: "runtime" },
  { name: "partyGroupFavorability", category: "runtime" },

  // Party runtime (charters, agendas, strength ledgers, treasury approvals).
  {
    name: "partyCharters",
    category: "runtime",
    notes:
      "Player-party charters. resetGameWorld handles cleanup specially (preset-aware: drop-all vs. keep-default) rather than via the blanket sweep.",
  },
  { name: "partyAgendas", category: "runtime" },
  { name: "partyPoliticalStrengthLedger", category: "runtime" },
  { name: "partyStrengthPressure", category: "runtime" },
  { name: "pendingTreasuryTransactions", category: "runtime" },
  { name: "treasuryOperations", category: "runtime" },
  {
    name: "partyMembers",
    category: "runtime",
    notes:
      "Party membership state (read by gameHealthSnapshot). No in-repo writer found — may be bot-populated; must not carry across worlds, so wiped on reset.",
  },
  { name: "orgRegLedger", category: "runtime" },

  // Legislature leadership elections (US House/Senate + DE/CN chairs).
  { name: "houseLeadershipElections", category: "runtime" },
  { name: "senateLeadershipElections", category: "runtime" },
  { name: "bundestagspraesidentElections", category: "runtime" },
  { name: "bundestagspraesidentNominations", category: "runtime" },
  { name: "cppccChairElections", category: "runtime" },
  { name: "cppccChairNominations", category: "runtime" },
  { name: "npcscChairElections", category: "runtime" },
  { name: "npcscChairNominations", category: "runtime" },
  {
    name: "governmentFormationVotes",
    category: "runtime",
    notes:
      "Companion of governmentFormations; appears dormant (only referenced by name propagation).",
  },
  {
    name: "unifiedCabinetMembers",
    category: "runtime",
    notes: "Sibling of cabinetMembers; appears dormant (only referenced by name propagation).",
  },
  {
    name: "committeeAssignments",
    category: "runtime",
    notes:
      "Gameplay committee assignments (carry characterId); previously only dropped by seedLegislationTypes.",
  },

  // Cabinet-governed asset rosters. Bootstrap re-seeds these via zero-count-
  // guarded seeders (seedMilitaryUnits/seedCabinetEstates/…), so they were
  // surviving resets and blocking the fresh-preset roster from seeding.
  { name: "militaryUnits", category: "runtime" },
  { name: "cabinetEstates", category: "runtime" },
  { name: "energyPlants", category: "runtime" },
  { name: "infraProjects", category: "runtime" },

  // ── Conflicts subsystem (WIRE W1–W6; gated behind conflictsEnabled) ─────────
  // All per-world military state, siblings of militaryUnits (already runtime
  // above). Every one is built by gameplay in a specific world and must not
  // outlive it — a command roster or half-fought battle carried into a fresh
  // world is exactly the drift this manifest exists to prevent.
  {
    name: "nationalArsenal",
    category: "runtime",
    notes:
      "Per-country materiel stock and grade by unit domain. Delivered by defence contracts, drawn by recruitment and by the refit step. RUNTIME: no seeder writes it — every nation starts with an empty store and builds up, so an absent document and an empty one are the same thing.",
  },
  {
    name: "defenceContracts",
    category: "runtime",
    notes:
      "Procurement contracts between a country's defence seat and one of its own defence sectors. RUNTIME: awarded by players, paid per delivered lot out of the defence appropriation. Wiped with the militaryUnits and corporateSectors they sit between.",
  },
  {
    name: "defenceProcurementAllocations",
    category: "runtime",
    notes:
      "Race-safe per-window contracting quotas. RUNTIME: derived from player-awarded defence contracts and must not survive a world reset.",
  },
  {
    name: "militaryCommands",
    category: "runtime",
    notes:
      "Per-country theater command org (regions, roster, assigned units), built by the defense holder. Wiped with the militaryUnits it references.",
  },
  {
    name: "militaryFormations",
    category: "runtime",
    notes:
      "Per-country combat org: unit formations + their general, and per-unit role assignments. Wiped with the militaryUnits it references.",
  },
  {
    name: "battleDeclarations",
    category: "runtime",
    notes:
      "Declared offensives awaiting resolution on the following turn. Purely in-flight turn state.",
  },
  {
    name: "battleReports",
    category: "runtime",
    notes: "Resolved/fizzled offensive records read by both nations' War Rooms. Per-world history.",
  },
  {
    name: "theaterState",
    category: "runtime",
    notes: "Per-country per-theater situation/CP pool. Regenerated by gameplay.",
  },
  {
    name: "navairEngagements",
    category: "runtime",
    notes:
      "Log of surface actions: which side held the water in a region on a turn, by what margin, and what was wrecked. Shown to players so the naval war is legible; nothing reads it back into the engine. Per-world history, wiped on reset.",
  },
  {
    name: "navairChannels",
    category: "runtime",
    notes:
      "Per-country per-region air superiority, sea control and detection, advanced every turn by the navairOperations phase. Runtime: a region nobody has contested has no row at all, and an absent row reads as zero control, so a fresh world writes nothing here until a fleet or an air wing is stationed somewhere. Wiped with the militaryUnits it is derived from.",
  },
  {
    name: "nationalDoctrine",
    category: "runtime",
    notes:
      "Per-country doctrine tree selections. Chosen by the defense holder at runtime (era-gated), not seeded reference data.",
  },
  {
    name: "characterGenerals",
    category: "runtime",
    notes:
      "Per-character general profile (spec, level, xp, trained traits). Runtime rather than preserved: the level/xp is earned fighting this world's battles, and a soft reset retires every character while wiping militaryUnits/formations — so a surviving profile would be orphaned progression keyed to a retired character.",
  },

  // An indexFunds document mixes the seeded definition with world-bound cash,
  // units, holdings, baskets, and rebalance state. It must be rebuilt with its
  // position/transaction collections or old corporation ids survive a reset.
  {
    name: "indexFunds",
    category: "runtime",
    notes:
      "Dropped with the world and recreated by the forced idempotent fund bootstrap migrations; definitions and runtime accounting cannot safely survive independently.",
  },
  { name: "indexFundPositions", category: "runtime" },
  {
    name: "fundFloatSettlements",
    category: "runtime",
    notes:
      "Archived float settlement plans reference this world's funds and corporations; reset them with fund positions so prior-world recovery and undo records cannot survive.",
  },
  {
    name: "fundWritedownCompensationLedger",
    category: "runtime",
    notes:
      "Retired fund compensation receipts belong to the outgoing characters and wallets. Keep legacy databases covered by the reset sweep.",
  },
  { name: "indexFundRedemptionQueue", category: "runtime" },
  { name: "indexFundSnapshots", category: "runtime" },
  { name: "indexFundTransactions", category: "runtime" },
  {
    name: "indexFundCommands",
    category: "runtime",
    notes:
      "Player order receipts and audit outboxes belong to the same world as fund cash, positions and transactions. Never expire within an active world.",
  },
  {
    name: "pensionSchemes",
    category: "runtime",
    notes:
      "Per-world pension balances, holdings, liabilities, and sponsor state. Rebuilt through gameplay and must not survive a world reset.",
  },

  // Trade / diplomacy / international-org runtime.
  { name: "tradeEmbargoes", category: "runtime" },
  {
    name: "embargoCooldowns",
    category: "runtime",
    notes:
      "Trade-embargo cooldown ledger. Previously survived resets, leaking cooldowns into the new world.",
  },
  { name: "tradeFlowSnapshots", category: "runtime" },
  { name: "diplomaticActions", category: "runtime" },
  { name: "customInternationalOrganizations", category: "runtime" },
  { name: "organizationFunds", category: "runtime" },
  { name: "organizationLeadershipElections", category: "runtime" },
  { name: "organizationMembershipProposals", category: "runtime" },
  { name: "organizationPostures", category: "runtime" },
  // Seeded at reset from the authored alignment tables, then advanced by the
  // alignment turn phase — runtime world state, wiped and reseeded like the
  // org collections above.
  { name: "countryAlignments", category: "runtime" },
  {
    name: "sphereMemberships",
    category: "runtime",
    notes: "Seeded sphere membership and influence state for the current world iteration.",
  },

  // Queued influence plays, consumed by the alignment turn phase. Player
  // actions against runtime world state, so wiped and reseeded with it.
  { name: "alignmentPlays", category: "runtime" },

  // Flashpoints blocs bid over. Runtime world state like the rows they move.
  { name: "alignmentCrises", category: "runtime" },

  // The German Question and any later settlement crisis: a standing contest
  // over one nation's constitutional settlement, opened per iteration and
  // advanced by the settlement turn phase. Runtime world state — wiped and
  // reopened on reset, exactly like the alignment rows it sits beside.
  { name: "settlementCrises", category: "runtime" },

  // Queued and resolved plays against a settlement crisis. Player actions
  // against runtime world state, so wiped with it. Resolved rows are stamped
  // rather than deleted during a world's life (they are the audit trail for
  // what a player's money bought), but they do not outlive the world.
  { name: "settlementPlays", category: "runtime" },

  // Crises / referendums / debates / discussions.
  { name: "crisisAidCommitments", category: "runtime" },
  { name: "crisisInteractions", category: "runtime" },
  { name: "refugeeReceptionHistory", category: "runtime" },
  { name: "conflictCivilianLossHistory", category: "runtime" },
  { name: "conflictCapacityObligations", category: "runtime" },
  {
    name: "crisisAutoCooldowns",
    category: "runtime",
    notes:
      "Auto-crisis spawn cooldown (turn-based lastSpawnTurn). Previously survived resets, suppressing crisis spawns in the new world.",
  },
  { name: "referendums", category: "runtime" },
  { name: "referendumWire", category: "runtime" },
  { name: "debateSessions", category: "runtime" },
  { name: "billDiscussions", category: "runtime" },
  { name: "billDiscussionReactions", category: "runtime" },

  // Per-country / per-state runtime + histories.
  { name: "countryLeaderStates", category: "runtime" },
  { name: "characterStateOrg", category: "runtime" },
  {
    name: "primaryStateActions",
    category: "runtime",
    notes:
      "One row per act a presidential primary candidate has running against a rival in a state. Rows carry their own expiry, so a reset that drops them simply clears every live attack.",
  },
  { name: "rulingPartyPurgeEvents", category: "runtime" },
  { name: "redistrictLedger", category: "runtime" },
  { name: "stateApprovalHistory", category: "runtime" },
  { name: "stateMetricHistory", category: "runtime" },
  {
    name: "macroMetricsHistory",
    category: "runtime",
    notes:
      "SP5: the macro slice of the per-turn metric history (formerly stateMetricHistory's economic/population series). Wiped on reset, rebuilt by play.",
  },
  {
    name: "approvalTelemetry",
    category: "runtime",
    notes:
      "Durable long-horizon approval series (#2099): one doc per (world, country, region, turn), every turn retained under the world-raw-full policy. Wiped on reset, rebuilt by play.",
  },
  {
    name: "macroTelemetry",
    category: "runtime",
    notes:
      "Durable long-horizon GDP/population series (#2100): one doc per (world, country, region, metric, turn), every turn retained under the world-raw-full policy. Wiped on reset, rebuilt by play.",
  },
  {
    name: "countryTurnTelemetry",
    category: "runtime",
    notes:
      "Research country-turn macro, monetary and fiscal panel (#2331, #2336): one doc per (world, country, turn) under the world-raw-full policy. Wiped on reset, rebuilt by play.",
  },
  {
    name: "securityTelemetry",
    category: "runtime",
    notes:
      "Research securities panel (#2332): one doc per (world, turn) holding every listed equity and live bond observed that turn. Wiped on reset, rebuilt by play.",
  },
  {
    name: "parliamentSeatsHistory",
    category: "runtime",
    notes: "Per-turn parliament composition snapshots (capped history), written by the turn phase.",
  },
  {
    name: "corporationCountryHistory",
    category: "runtime",
    notes: "Per-turn per-country corporation aggregate snapshots (capped history).",
  },
  { name: "voteTallies", category: "runtime" },
  { name: "corporationShareInvites", category: "runtime" },
  { name: "wealthListHistory", category: "runtime" },
  { name: "wealthListSnapshots", category: "runtime" },
  {
    name: "analyticsRecords",
    category: "runtime",
    notes: "Current world wealth high-water mark for PostHog.",
  },
  {
    name: "seedDiagnostics",
    category: "runtime",
    notes:
      "Seed self-diagnostic reports (conformance + drift). Wiped on reset; re-populated in Phase 4 after bootstrap. Capped to last 50 docs on insert.",
  },
  {
    name: "seedDiagnosticBaselines",
    category: "runtime",
    notes:
      "Singleton baseline snapshot ({_id:'current'}) captured post-reset after conformance. Wiped on reset; re-captured in Phase 4b when conformance has no criticals.",
  },

  // ── 2026-07 backfill: gameplay state added since the last manifest sweep ──
  {
    name: "acquisitionOffers",
    category: "runtime",
    notes: "Corporate acquisition offers (corporations/[id]/deals). Owned by gameplay.",
  },
  {
    name: "impeachments",
    category: "runtime",
    notes: "Impeachment articles and votes. Owned by gameplay.",
  },
  {
    name: "speakerVacateMotions",
    category: "runtime",
    notes: "Motions to vacate the Speaker's chair. Owned by gameplay.",
  },
  {
    name: "ukJudicialReviewCases",
    category: "runtime",
    notes: "UK judicial-review cases spawned by the turn pipeline (ukJrSurpriseTurn).",
  },
  {
    name: "manifestos",
    category: "runtime",
    notes:
      "Westminster party manifestos (#901). Owned by gameplay; no seeder writes them. Accessed via db/collections/manifestos.ts.",
  },
  {
    name: "ukBudgets",
    category: "runtime",
    notes:
      "UK Westminster Budgets (#901). Owned by gameplay; no seeder writes them. Accessed via db/collections/ukBudgets.ts. Distinct from the regional ukBudget budget rows.",
  },
  {
    name: "ukNhsState",
    category: "runtime",
    notes:
      "UK NHS state (#901). Owned by gameplay and the turn pipeline; no seeder writes it. Accessed via uk/nhs/nhsStore.ts.",
  },
  // 2026-10 backfill: world state omitted from the reset inventory
  {
    name: "procurementRestrictions",
    category: "runtime",
    notes: "Peace-term procurement restrictions belong to one world.",
  },
  {
    name: "truces",
    category: "runtime",
    notes: "Turn-expiring bilateral war restrictions belong to one world.",
  },
  {
    name: "vietnamEscalation",
    category: "runtime",
    notes: "Vietnam crisis singleton state belongs to one world.",
  },
  {
    name: "appliedWorldTransitions",
    category: "runtime",
    notes: "Idempotency ledger for world-specific transition rules.",
  },
  {
    name: "sphereFlowLedger",
    category: "runtime",
    notes: "Foreign-aid and tribute history is scoped to one world.",
  },
  {
    name: "bankingTelemetry",
    category: "runtime",
    notes: "Turn-keyed banking health telemetry belongs to one world.",
  },
  {
    name: "acquisitionSettlements",
    category: "runtime",
    notes: "Settlement receipts reference world-specific offers and corporations.",
  },
  {
    name: "mergerReviews",
    category: "runtime",
    notes: "Merger decisions reference world-specific corporations.",
  },
  {
    name: "corporationExits",
    category: "runtime",
    notes: "Exit records reference world-specific corporations that were deleted.",
  },
  {
    name: "indexListingPetitions",
    category: "runtime",
    notes: "Listing decisions reference world-specific corporations and characters.",
  },
  {
    name: "speakerLeadershipBallots",
    category: "runtime",
    notes: "Leadership ballots reference world-specific nominations and characters.",
  },
  {
    name: "senateLeadershipBallots",
    category: "runtime",
    notes: "Leadership ballots reference world-specific nominations and characters.",
  },
  {
    name: "bargainingRatificationBallots",
    category: "runtime",
    notes: "Ratification ballots reference world-specific campaigns and characters.",
  },
  {
    name: "balanceSnapshotCheckpoints",
    category: "runtime",
    notes: "Turn-keyed balance checkpoints belong to one world.",
  },
  {
    name: "equityLiquidityFacilitySnapshots",
    category: "runtime",
    notes: "Turn-keyed facility snapshots belong to one world.",
  },
  {
    name: "nppOperatorDiagnostics",
    category: "runtime",
    notes: "Turn-keyed operator diagnostics belong to one world.",
  },
  {
    name: "capacityDecisionFunnels",
    category: "runtime",
    notes: "Turn-keyed capacity diagnostics belong to one world.",
  },
  {
    name: "bondSaleIntents",
    category: "runtime",
    notes: "In-flight bond sale recovery state belongs to one world.",
  },
  {
    name: "ngChamberLeadershipElections",
    category: "runtime",
    notes: "Nigerian chamber leadership elections belong to one world.",
  },
  {
    name: "ngChamberLeadershipNominations",
    category: "runtime",
    notes: "Nigerian chamber nominations belong to one world.",
  },
];
