/**
 * Seed Nigeria-specific wiki/guide pages.
 *
 * In-game documentation so players understand Nigeria's federal presidential
 * system and its six-geopolitical-zone structure.
 */

import type { Db } from "mongodb";
import { ObjectId } from "mongodb";
import type { WikiPage } from "@/lib/db/types";

const NG_WIKI_PAGES: Array<
  Pick<WikiPage, "slug" | "title" | "description" | "content" | "tags" | "category">
> = [
  {
    slug: "nigeria-overview",
    title: "Nigeria Overview",
    description: "How Nigeria works in A House Divided.",
    category: "Country Guide",
    tags: ["nigeria", "country", "overview", "presidential", "federal"],
    content: `## Nigeria in A House Divided

Nigeria is a **federal presidential republic**. A directly elected **President** is both head of state and head of government, serving alongside a bicameral **National Assembly**. Executive power is independent of the legislature — there is no prime minister, and no confidence vote can collapse the government mid-term.

### Key features

- **Directly elected President.** Wins a national mandate, runs with a Vice President, and is capped at **two terms**.
- **Bicameral National Assembly.** A **Senate** (109 seats) and a **House of Representatives** (360 seats). Both chambers are elected.
- **Six geopolitical zones.** Nigeria is played as six macro-regions, each electing senators, representatives, and a Governor.
- **Central Bank of Nigeria (CBN).** The monetary authority; its Governor sets the prime rate. The currency is the Naira (NGN).
- **Federal Allocations.** Central government revenue is distributed to the zones.
`,
  },
  {
    slug: "nigeria-federal-system",
    title: "Nigeria's Federal System",
    description: "Zones, seats, and offices in the Nigerian federation.",
    category: "Country Guide",
    tags: ["nigeria", "federal", "zones", "senate", "house", "governor"],
    content: `## The Nigerian Federation

Nigeria is played as **six geopolitical zones**. Each zone elects representatives to both chambers of the National Assembly and a Governor for its executive.

| Zone | Notes |
|------|-------|
| North-West | Sahelian north; the most populous zone |
| North-East | Lake Chad basin |
| North-Central | The Middle Belt; religiously and ethnically mixed |
| South-West | Atlantic coast; home to the largest metropolis |
| South-South | The Niger Delta; oil-producing |
| South-East | Lower Niger heartland |

### Offices

- **President & Vice President** — national executive, four-year terms, two-term limit.
- **Senators** — upper chamber of the National Assembly.
- **Representatives** — lower chamber (House of Representatives).
- **Governors** — zone-level executives.
- **Governor of the CBN** — central bank chair.
`,
  },
  {
    slug: "nigeria-economy",
    title: "Nigeria's Economy",
    description: "Oil, the CBN, and the Naira.",
    category: "Country Guide",
    tags: ["nigeria", "economy", "oil", "cbn", "naira"],
    content: `## Nigeria's Economy

Nigeria is one of Africa's largest economies, heavily shaped by **petroleum**. Oil and gas dominate export earnings and government revenue, which makes fiscal policy sensitive to global energy prices.

### Levers

- **Central Bank of Nigeria (CBN).** Sets the prime rate; manages the Naira (NGN) and inflation.
- **Petroleum sector.** A central driver of Federal Allocations and the trade balance.
- **Diversification.** Agriculture, services, and power-sector reform are perennial policy themes.
`,
  },
];

export async function seedNGWiki(db: Db) {
  const coll = db.collection<WikiPage>("wikiPages");
  const now = new Date();

  for (const page of NG_WIKI_PAGES) {
    await coll.updateOne(
      { slug: page.slug },
      {
        $set: {
          ...page,
          status: "published",
          featured: false,
          isAutoGenerated: false,
          viewCount: 0,
          createdAt: now,
          updatedAt: now,
        },
        $setOnInsert: {
          _id: new ObjectId(),
        },
      },
      { upsert: true }
    );
  }

  return { inserted: NG_WIKI_PAGES.length };
}
