/**
 * Seed manifest — source of truth for which MongoDB collections are seeded,
 * wiped, or preserved by reset/bootstrap.
 *
 * Consumed by:
 *   - `resetGameWorld` (which collections to wipe on a reset)
 *   - `bootstrapGameWorld` (which collections to seed on a fresh start)
 *   - Admin seeder UI (`UniversalSeeder`) and `/api/admin/seed`
 *   - CLI scripts (`scripts/reset-and-bootstrap.ts`, `scripts/bootstrap-full.ts`)
 *   - Contract tests (`bootstrapGameWorld.contract.test.ts`)
 *
 * Companion doc: `docs/reset-and-seed-contract.md`.
 *
 * If you add a new MongoDB collection, add it here so reset/bootstrap behaviour
 * stays explicit. An unclassified collection is a latent bug — it will quietly
 * survive resets and quietly miss out on bootstrap.
 */

/**
 * Lifecycle category for a MongoDB collection.
 *
 * - `reference`: Seeded on every fresh start. Drives game-world structure
 *   (states, parties, baselines, legislation types, …). Idempotent seeders
 *   re-upsert these.
 *
 * - `runtime`: Wiped on a soft world reset (`deleteProfiles: false`) and on
 *   a full reset. Regenerated by gameplay (turns, actions, elections, …).
 *   Bootstrap may pre-populate some of these to a starting state (e.g. seed
 *   elections), but their steady-state owner is gameplay, not the seeder.
 *
 * - `preserved`: Survives reset by default. Player accounts, admin metadata,
 *   community content, audit trails, migration registry. A *full* reset
 *   (`deleteProfiles: true`) may still nuke some of these (e.g. non-admin
 *   users), but the default is "keep".
 *
 * - `migration-only`: Touched only by one-off live-data migrations
 *   (`scripts/migrations/`). Never required to exist for a brand-new game.
 *
 * - `incident-only`: Touched only by incident-response scripts
 *   (`scripts/heal-*`, etc.). Never part of the normal bootstrap or reset
 *   path.
 */
export type CollectionCategory =
  "reference" | "runtime" | "preserved" | "migration-only" | "incident-only";

export interface CollectionEntry {
  /** MongoDB collection name. */
  name: string;
  category: CollectionCategory;
  /** Free-form note explaining why this collection lives in its category. */
  notes?: string;
  /**
   * For `reference` collections, the seeder module that owns it (relative path
   * under `src/lib/admin/seed/`). Used by the admin seeder UI to surface a
   * "re-seed this" button and by contract tests to verify coverage.
   */
  seededBy?: string;
}

// ─── Reference collections ───────────────────────────────────────────────────
// Seeded every fresh start; idempotent re-runs.

const REFERENCE: CollectionEntry[] = [
  { name: "states", category: "reference", seededBy: "runCoreSeed" },
  { name: "policies", category: "reference", seededBy: "runCoreSeed" },
  { name: "demographicCategories", category: "reference", seededBy: "runCoreSeed" },
  { name: "stateDemographics", category: "reference", seededBy: "runCoreSeed" },
  { name: "demographicDefaults", category: "reference", seededBy: "runCoreSeed" },
  { name: "stateDemographicTurnout", category: "reference", seededBy: "runCoreSeed" },
  { name: "gameConfig", category: "reference", seededBy: "runCoreSeed" },
  {
    name: "politicalParties",
    category: "reference",
    seededBy: "seedParties",
    notes:
      "Default parties (isDefault: true) are reference. Player-created parties are runtime and wiped on reset.",
  },
  {
    name: "statePartyOrg",
    category: "reference",
    seededBy: "seedParties",
    notes:
      "Default-party rows are reference. Rows tied to player-created parties are runtime. Seeded for US/UK/JP/DE/BR/IE/CN via seedParties; the Cold-War one-party states have their own seeders — seedRuStatePartyOrg (CPSU), seedDdStatePartyOrg (National Front), seedCnStatePartyOrg (advisory parties), and seedEasternBlocStatePartyOrg (the six satellites' ruling parties plus the republican parties of UKR/BLR/BAL).",
  },
  {
    name: "macroMetrics",
    category: "reference",
    seededBy: "seedRegionMetrics",
    notes:
      "The economy engine's working state (economic.* + population.* + independenceDesire + the objective fiscal pair + economicModel) for EVERY country's regions. Extracted from the legacy-shaped seed docs at each seeder's write site (writeSplitMetrics). This is the ONLY region-metrics store now — the political half lives on politicalMetrics.",
  },
  {
    name: "stateMetrics",
    category: "reference",
    seededBy: "seedRegionMetrics",
    notes:
      "Legacy-shaped per-region metrics doc (economic.* / population.* / political.*), keyed by stateId. The split stores above (macroMetrics + politicalMetrics) are the working state; this remains the read surface for consumers that want one doc per region — e.g. the P3a capacity build price, which reads economic.costOfLiving to index construction cost by host state.",
  },
  {
    name: "politicalMetrics",
    category: "reference",
    seededBy: "seedPoliticalMetrics",
    notes:
      "Political Metrics (new domain, separate from stateMetrics). One doc per US/UK/RU/DD region; values drifted each turn by the SP2 dynamics phase; residuals set at reset by seedPoliticalMetricsResiduals.",
  },
  {
    name: "politicalMetricsHistory",
    category: "runtime",
    notes:
      "SP2 trend history: one doc per country, national aggregate appended every 24 turns by processPoliticalMetricsDynamics, capped at 365 entries. Runtime — wiped on reset, rebuilt by play.",
  },
  {
    name: "politicalCabinetContribution",
    category: "runtime",
    notes:
      "Per-country snapshot of the standing cabinet contribution to political metrics (PoliticalMetricId → points/turn nationally, plus optional per-region extras from sited estates/orders), written each turn by processMinisterialOrders and folded into region cabinetResiduals by processPoliticalMetricsDynamics. Runtime — wiped on reset, rebuilt by play.",
  },
  {
    name: "conflicts",
    category: "runtime",
    notes:
      "Dynamic conflicts (the generalized-theater model, replacing the 4 static theaters). Created during play by player declarations / events; the world starts empty. Units/generals/battles run on these via unit.theaterId = a conflict id. Runtime — wiped on reset, rebuilt by play.",
  },
  {
    name: "nationalManpower",
    category: "runtime",
    seededBy: "runCoreSeed",
    notes:
      "Per-country replacement-manpower pool + reinforcement mode. Regenerates each turn from population × the conscription stance and is drawn down to refill under-strength units. Runtime — wiped on reset, then re-seeded by runCoreSeed (seedNationalManpower) at 25% of each nation's ceiling and maintained by play. Before that seeder existed the collection started empty and the turn loop won the race to create it, leaving every nation at one turn's regeneration.",
  },
  { name: "stateBaselines", category: "reference", seededBy: "runCoreSeed" },
  {
    name: "stateMetricBaselines",
    category: "reference",
    notes:
      "Legacy parallel of stateBaselines. JP/DE/IE/BR/CN seeders used to write here even though runtime (policyEffects.ts) only reads stateBaselines — Phase 5 of the reset/seed cleanup pointed all seeders at stateBaselines. The legacy collection is kept in the manifest so live databases with stragglers stay classified; once production is purged of these rows the entry can be removed.",
  },
  { name: "legislationTypes", category: "reference", seededBy: "seedLegislationTypes" },
  { name: "achievements", category: "reference", seededBy: "seedAchievements" },
  { name: "federalBudget", category: "reference", seededBy: "seedBudgets" },
  { name: "stateBudgets", category: "reference", seededBy: "seedBudgets" },
  {
    name: "regionalBudgets",
    category: "runtime",
    notes:
      "RUNTIME, not reference: no seeder writes this. Every row is produced by the per-turn regional-budget processors (regionalBudget/cnRegionalBudget/deRegionalBudget/jpRegionalBudget/ruRegionalBudget). It was classified `reference` with seededBy: seedUkBudgets, which writes nothing here — so the runtime sweep skipped it AND the reference drop list skipped it, and rows accumulated across resets. That is why stale orphans from the pre-rename CN region ids (NORTHEAST/EAST/...) are still in production, worked around downstream in budget/spending.ts rather than cleaned up.",
  },
  { name: "formulaGrants", category: "reference", seededBy: "seedBudgets" },
  { name: "stateResourceCapacity", category: "reference", seededBy: "seedStateResourceCapacity" },
  {
    name: "stateSectorSpecializations",
    category: "reference",
    seededBy: "seedStateSectorSpecializations",
  },
  { name: "partyBudget", category: "reference", seededBy: "seedPartyBudgets" },
  { name: "unownedSectors", category: "reference", seededBy: "seedUnownedSectors" },
  {
    name: "unions",
    category: "runtime",
    seededBy: "seedUnions",
    notes:
      "One vacant-head union per (countryId, sectorType). Wiped on reset; re-seeded at bootstrap with era-appropriate names.",
  },
  { name: "unionEndorsements", category: "runtime" },
  { name: "unionLeaderVotes", category: "runtime" },
  { name: "unionOrganizers", category: "runtime" },
  {
    name: "bargainingCampaigns",
    category: "runtime",
    notes: "Release 1.1 union-employer negotiation history; tied to unions and corporations.",
  },
  {
    name: "collectiveAgreements",
    category: "runtime",
    notes: "Release 1.1 enforceable wage and labor-peace terms; tied to campaign locals.",
  },
  { name: "seats", category: "reference", seededBy: "seedSeats" },
  { name: "statePolicies", category: "reference", seededBy: "seedStatePolicies" },
  {
    name: "internationalOrganizations",
    category: "reference",
    seededBy: "seedInternationalOrganizations",
  },
  {
    name: "centralBanks",
    category: "reference",
    seededBy: "seedForex",
    notes:
      "One row per forex-active country with day-one prime rate, empty rate history, and the bookkeeping fields the turn processor expects. WIPED on reset and re-seeded by seedForex: `resetGameWorld` deletes this collection explicitly alongside statePolicies/commodityPrices/exchangeRates, because the seeder is $setOnInsert-only and would otherwise leave the previous world's accumulated CB state (prime rate, rate history) in place. (This note previously claimed CB state survives reset — it does not.)",
  },
  {
    name: "exchangeRates",
    category: "reference",
    seededBy: "seedForex",
    notes:
      "One row per forex-active currency at its starting rate. Rates float at runtime via forexTurn.ts; the seed sets the starting point.",
  },
  {
    name: "commodityPrices",
    category: "reference",
    seededBy: "seedCommodityPrices",
    notes:
      "Current price is reference seed (one row per commodity at base price); price ticks accumulate in commodityPriceHistory at runtime.",
  },
  {
    name: "macroCountries",
    category: "reference",
    seededBy: "seedMacroCountries",
    notes:
      "Tier-2 sphere-macro aggregate state + held market contribution (#3716/#3719/#3720/#3721). Seeded for European (AT oracle + FI/GR/IE), Asian/ME (JO/AF/YE/MM/LA/KH/TH), and African/American (ET/ZA/CU/GT/PA/NI/CL/AR/MX/VE) 1953 rosters; kernel refreshes every six turns. Planned Eastern-bloc CountryId countries (PL/CS/HU/RO/BG/YU plus the union republics UKR/BLR/BAL) were promoted to full-autonomous Tier-1 — their dormant macro specs are not seeded. Planned economies never seed market corporations.",
  },
  {
    name: "landeslisten",
    category: "runtime",
    notes:
      "RUNTIME, not reference: seedDE does not write this. Lists are generated in-game by autoGenerateLandesliste from party members, keyed by cycle, and can carry chair edits until lockedAt. Classified `reference` it survived resets, leaving a fresh world holding the previous world's lists keyed to parties and characters that no longer exist.",
  },
  {
    name: "strategicSectorDesignations",
    category: "reference",
    seededBy: "seedStrategicSectors",
    notes:
      "Per-country default strategic sectors (arms the strategic nationalization trigger). Idempotent upsert per (countryId, sectorType). Head-of-government designations at runtime upsert into the same collection.",
  },
  {
    name: "congressionalDistricts",
    category: "reference",
    seededBy: "seedCongressionalDistricts",
    notes:
      "Idempotent upsert from runCoreSeed; redistricting mutates rows at runtime, refreshed when bootstrap re-seeds reference (resetReference:true).",
  },
  {
    name: "regionDemographics",
    category: "reference",
    seededBy: "seedCohortVectors",
    notes:
      "Idempotent upsert from bootstrap's seedCohortVectors; demographics phase mutates at runtime.",
  },
  {
    name: "stateRegistrationPool",
    category: "reference",
    seededBy: "seedRegistrationLanes",
    notes:
      "Idempotent upsert from bootstrap's seedRegistrationLanes; per-turn registration drift mutates it like stateMetrics.",
  },
  {
    name: "indexFunds",
    category: "reference",
    notes:
      "Index-fund definitions re-seeded on every fresh start via idempotent bootstrap migrations (index-fund-foundation/seed). Holder state lives in the runtime indexFund* collections.",
  },
];

// ─── Runtime collections ─────────────────────────────────────────────────────
// Wiped on reset; regenerated by gameplay/turns/actions.

const RUNTIME: CollectionEntry[] = [
  {
    name: "moneySupplySnapshots",
    category: "runtime",
    notes: "Per-turn M1/M2, credit, sovereign-debt, and central-bank holdings by issuing currency.",
  },
  {
    name: "economicVitalSigns",
    category: "runtime",
    notes:
      "Versioned per-turn aggregate market, production, distribution, money, and reconciliation indicators for economic evaluation.",
  },
  // Elections + officials
  { name: "elections", category: "runtime" },
  { name: "electionCandidates", category: "runtime" },
  { name: "electionVoteTallies", category: "runtime" },
  {
    name: "electedOfficials",
    category: "runtime",
    notes: "Seeded by bootstrap (historical or vacant), then driven by elections.",
  },
  {
    name: "officials",
    category: "runtime",
    notes: "Legacy synonym of electedOfficials; left in place for older code paths.",
  },

  // NPPs
  { name: "npps", category: "runtime" },
  { name: "nppInfluenceAttempts", category: "runtime" },
  { name: "nppRelationships", category: "runtime" },
  { name: "nppEndorsements", category: "runtime" },
  { name: "nppVoteCommitments", category: "runtime" },
  { name: "nppVotePredictions", category: "runtime" },
  { name: "playerEndorsements", category: "runtime" },

  // Bills + legislation runtime
  { name: "bills", category: "runtime" },
  { name: "stateBills", category: "runtime" },
  { name: "billWhips", category: "runtime" },
  { name: "enactedLaws", category: "runtime" },
  { name: "tariffs", category: "runtime" },
  { name: "subsidies", category: "runtime" },
  {
    name: "legislation",
    category: "runtime",
    notes: "Legacy bills collection retained for older code paths.",
  },

  // Caucuses + coalitions
  { name: "coalitions", category: "runtime" },
  { name: "caucuses", category: "runtime" },
  { name: "caucusMemberships", category: "runtime" },
  { name: "caucusPolicyPositions", category: "runtime" },
  { name: "caucusChairCandidates", category: "runtime" },
  { name: "caucusChairElections", category: "runtime" },
  { name: "caucusChairVotes", category: "runtime" },

  // Recruitment + slates
  { name: "recruitmentSlates", category: "runtime" },
  { name: "slateCandidates", category: "runtime" },

  // Treasury + political capital
  { name: "treasuryTransactions", category: "runtime" },
  { name: "politicalCapitalBalances", category: "runtime" },
  { name: "capitalActionLogs", category: "runtime" },

  // State-party elections
  { name: "statePartyElections", category: "runtime" },
  { name: "statePartyVotes", category: "runtime" },
  { name: "statePartyCandidates", category: "runtime" },

  // National party / committee elections
  { name: "nationalPartyCandidates", category: "runtime" },
  { name: "nationalPartyElections", category: "runtime" },
  { name: "nationalPartyVotes", category: "runtime" },
  { name: "nationalCommitteeCandidates", category: "runtime" },
  { name: "nationalCommitteeElections", category: "runtime" },
  { name: "nationalCommitteeVotes", category: "runtime" },
  {
    name: "nationalPartyLeadership",
    category: "runtime",
    notes: "Per-party national leadership (chair/treasurer). Per-game state; cleared on reset.",
  },

  // Legislative leadership
  { name: "leadershipElections", category: "runtime" },
  { name: "houseLeadershipBallots", category: "runtime" },
  { name: "houseLeadershipNominations", category: "runtime" },
  { name: "senateLeadershipNominations", category: "runtime" },
  { name: "speakerElections", category: "runtime" },
  { name: "speakerNominations", category: "runtime" },
  { name: "pmAppointmentVotes", category: "runtime" },
  { name: "noConfidenceVotes", category: "runtime" },
  { name: "confidenceVotes", category: "runtime" },
  { name: "congressLeaders", category: "runtime" },

  // Cabinet + government
  { name: "cabinetMembers", category: "runtime" },
  { name: "cabinetNominations", category: "runtime" },
  { name: "cabinetSettings", category: "runtime" },

  // SCOTUS (#3598) — Justice office stored off-currentOffice (mirrors
  // centralBanks); Senate-confirmation lifecycle mirrors cabinetNominations.
  { name: "supremeCourtSeats", category: "runtime" },
  { name: "scotusNominations", category: "runtime" },

  // FOMC — committee seats live on centralBanks.fomcBoard; the President's
  // per-seat nomination → Senate-confirmation lifecycle mirrors cabinetNominations.
  { name: "fomcNominations", category: "runtime" },
  { name: "docketCases", category: "runtime" },
  { name: "committeeProposals", category: "runtime" },
  { name: "ministerialOrders", category: "runtime" },
  { name: "governmentApprovals", category: "runtime" },
  { name: "governmentFormations", category: "runtime" },
  { name: "parliamentaryGovernments", category: "runtime" },
  { name: "ukCabinetCooldowns", category: "runtime" },
  { name: "ukGovernment", category: "runtime" },

  // Corporations + markets
  { name: "corporations", category: "runtime" },
  { name: "corporationCeoVotes", category: "runtime" },
  { name: "corporationHistory", category: "runtime" },
  { name: "corporationPortfolioHistory", category: "runtime" },
  { name: "corporationPrivatizationVotes", category: "runtime" },
  { name: "corporationVotes", category: "runtime" },
  { name: "corporateSectors", category: "runtime" },
  {
    name: "pendingNationalizations",
    category: "runtime",
    notes: "Legislative takings in their notice window; resolved/cleared in the corp turn.",
  },
  {
    name: "nationalizationAuctions",
    category: "runtime",
    notes: "Privatization auctions on spun-out corps; opened/resolved by gameplay.",
  },
  {
    name: "nationalizationLedger",
    category: "runtime",
    notes: "Append-only record of each nationalization taking (acquisition register).",
  },
  { name: "extractionContracts", category: "runtime" },
  {
    name: "prospectingSurveys",
    category: "runtime",
    notes:
      "Geological surveys (resource prospecting). Launched by corps/governments, resolved by the prospectingResolution turn phase. Regenerated by gameplay; wiped on reset.",
  },
  { name: "investorRankingSnapshots", category: "runtime" },
  { name: "marketCapHistory", category: "runtime" },
  { name: "shareListings", category: "runtime" },
  { name: "shareOffers", category: "runtime" },
  { name: "shareOrders", category: "runtime" },
  { name: "shareTradeHistory", category: "runtime" },
  { name: "stockExchangeSnapshots", category: "runtime" },

  // Bonds
  { name: "bonds", category: "runtime" },
  { name: "bondHistory", category: "runtime" },

  // Private banking (1.1)
  { name: "bankLoans", category: "runtime" },
  { name: "bankCharterHistory", category: "runtime" },
  { name: "depositInsuranceFunds", category: "runtime" },
  {
    name: "interbankLoans",
    category: "runtime",
    notes: "Retail/universal banks lending non-reserved cash to investment/universal banks.",
  },
  {
    name: "bankingLaws",
    category: "runtime",
    notes: "Per-country banking separation law and rate corridors, enacted by bill or chair.",
  },

  // Forex + commodities runtime
  { name: "currencyOrders", category: "runtime" },
  { name: "tradeHistory", category: "runtime" },
  { name: "commodityPriceHistory", category: "runtime" },
  {
    name: "commodityFlows",
    category: "runtime",
    notes:
      "Per-turn global supply/demand/clearing ledger rows (one per commodity per turn), written by commodityPriceTurn. Regenerated by turns.",
  },
  {
    name: "commoditySourcingFlows",
    category: "runtime",
    notes:
      "Record-only landed-price sourcing ledger (one doc per commodity per turn, state-level flows), written by commodityPriceTurn. Regenerated by turns, 48-turn retention.",
  },
  {
    name: "sourcingNetworkLoad",
    category: "runtime",
    notes:
      "Per-turn per-state freight capacity consumed by the sourcing pass (bulk/special). Regenerated by turns, 48-turn retention.",
  },
  {
    name: "commodityQuality",
    category: "runtime",
    notes:
      "Per-commodity aggregate quality state (sector-quality system), recomputed in the corp turn.",
  },
  {
    name: "supplyAgreements",
    category: "runtime",
    notes: "Player corp-to-corp supply agreements; tied to corporations, which are wiped on reset.",
  },
  {
    name: "commodityPrice",
    category: "runtime",
    notes:
      "Legacy singular-named collection. Production data lives in commodityPrices (plural). Flagged in KNOWN_INCONSISTENCIES.",
  },

  // Financial ledgers
  { name: "financialTxLog", category: "runtime" },
  { name: "locLedger", category: "runtime" },
  { name: "savingsLedger", category: "runtime" },
  { name: "portfolioHistory", category: "runtime" },

  // Counters + snapshots
  {
    name: "counters",
    category: "runtime",
    notes:
      "Sequential ID counters. Wiped on reset so newly-seeded entities start at 1 (otherwise the unique sequentialId index collides with deleted-then-respawned defaults).",
  },
  { name: "federalBudgetSnapshots", category: "runtime" },
  { name: "primarySnapshots", category: "runtime" },
  {
    name: "primarySnapshot",
    category: "runtime",
    notes: "Legacy singular-named twin of primarySnapshots. Flagged in KNOWN_INCONSISTENCIES.",
  },
  { name: "gameHealthSnapshots", category: "runtime" },
  { name: "codeQualitySnapshots", category: "runtime" },
  { name: "siteTrafficPageviews", category: "runtime" },
  {
    name: "stateDemographicsBackup",
    category: "runtime",
    notes:
      "Pre-reseed snapshots of stateDemographics written by /api/admin/demographics/reseed (last 3 per country+era kept).",
  },

  // Game state
  {
    name: "gameState",
    category: "runtime",
    notes:
      "Singleton (_id: 'current'). Reset re-initializes to turn 1; not deleted, just updated in place.",
  },
  { name: "countryGameStates", category: "runtime" },
  { name: "countryHistory", category: "runtime" },
  {
    name: "countryState",
    category: "runtime",
    notes:
      "Per-country runtime mutable fields (governmentType, rulingPartyId, opsVoteMultipliers, hasLeaderConfidenceModel) promoted out of COUNTRY_CONFIGS. Seeded by runCoreSeed via seedAllCountryStates (idempotent). Wiped on reset so mid-game regime mutations (Stage-4 conversions, convention ratifications) don't survive a fresh world.",
  },
  {
    name: "regimeEscalation",
    category: "runtime",
    notes:
      "Per-country one-party-state escalation state (currentStage, dwellCounters, decision queue, transition history). Driven by the per-turn regimeEscalationTurn from popularLegitimacy + partyConfidence. Wiped on reset so mid-game crises don't survive a fresh world; the per-turn driver self-heals a 'stable' row on first tick.",
  },

  // Sovereign / crisis
  { name: "crises", category: "runtime" },
  {
    name: "livingConflicts",
    category: "runtime",
    notes:
      "Release 1.3 persistent phased world-conflict state. One row per authored definition; wiped on reset so phase, pressure, intensity, and clocks cannot leak into a new world.",
  },
  {
    name: "coldWarTension",
    category: "runtime",
    notes:
      "Release 1.3 shared tension value and event ledger. Wiped on reset and recreated at the era-appropriate arsenal pressure floor.",
  },
  {
    name: "nuclearPrograms",
    category: "runtime",
    notes:
      "Per-country nuclear research, stockpile, and production orders. Wiped on reset and recreated from game-scaled historical baselines without automatic production.",
  },
  { name: "sovereignCrisisDecisions", category: "runtime" },
  { name: "globalAlerts", category: "runtime" },
  { name: "wireEvents", category: "runtime" },
  { name: "sentimentPulses", category: "runtime" },

  // News + campaign + comms
  { name: "newsPosts", category: "runtime" },
  { name: "newsReactions", category: "runtime" },
  { name: "campaigns", category: "runtime" },
  { name: "notifications", category: "runtime" },
  { name: "eventDefinitions", category: "runtime" },
  { name: "eventInstances", category: "runtime" },
  { name: "eventCooldownLedger", category: "runtime" },
  {
    name: "countryModifiers",
    category: "runtime",
    notes:
      "Temporary event-sourced country modifiers (e.g. world-event sector demand boosts); expire by turn number. Regenerated by gameplay; must not survive resets.",
  },
  { name: "playerMail", category: "runtime" },
  { name: "playerMailReports", category: "runtime" },
  { name: "policyReactions", category: "runtime" },
  { name: "posts", category: "runtime" },
  { name: "partyDiscussionPosts", category: "runtime" },
  { name: "partyHistory", category: "runtime" },
  { name: "influenceHistory", category: "runtime" },
  { name: "politicianOverrides", category: "runtime" },

  // IMF / org runtime
  { name: "organizationLeadership", category: "runtime" },
  { name: "organizationLegislation", category: "runtime" },
  { name: "organizationMemberships", category: "runtime" },
  { name: "organizationWithdrawals", category: "runtime" },

  // Misc gameplay
  { name: "blackjackPendingWagers", category: "runtime" },
  { name: "actionLogs", category: "runtime" },
  { name: "activityLog", category: "runtime" },
  { name: "turnLogs", category: "runtime" },

  // ── 2026-06 manifest-completeness backfill ─────────────────────────────────
  // Collections that existed in code but were never classified, so they
  // silently survived resets. Grouped by subsystem. Added alongside the move to
  // a manifest-driven reset wipe (resetGameWorld now wipes every runtime entry).

  // Governor's / Presidential Office (derived executive state; reset re-seeds
  // office-state rows via seedOfficeStates).
  { name: "governorOfficeState", category: "runtime" },
  { name: "governorAddresses", category: "runtime" },
  { name: "governorExecutiveOrders", category: "runtime" },
  { name: "governorEndorsements", category: "runtime" },
  { name: "governorLegislationQueue", category: "runtime" },
  { name: "executiveEndorsements", category: "runtime" },
  { name: "partyGroupFavorability", category: "runtime" },

  // Party runtime (charters, agendas, strength ledgers, treasury approvals).
  {
    name: "partyCharters",
    category: "runtime",
    notes:
      "Player-party charters. resetGameWorld handles cleanup specially (preset-aware: drop-all vs. keep-default) rather than via the blanket sweep.",
  },
  { name: "partyAgendas", category: "runtime" },
  { name: "partyPoliticalStrengthLedger", category: "runtime" },
  { name: "partyStrengthPressure", category: "runtime" },
  { name: "pendingTreasuryTransactions", category: "runtime" },
  { name: "treasuryOperations", category: "runtime" },
  {
    name: "partyMembers",
    category: "runtime",
    notes:
      "Party membership state (read by gameHealthSnapshot). No in-repo writer found — may be bot-populated; must not carry across worlds, so wiped on reset.",
  },
  { name: "orgRegLedger", category: "runtime" },

  // Legislature leadership elections (US House/Senate + DE/CN chairs).
  { name: "houseLeadershipElections", category: "runtime" },
  { name: "senateLeadershipElections", category: "runtime" },
  { name: "bundestagspraesidentElections", category: "runtime" },
  { name: "bundestagspraesidentNominations", category: "runtime" },
  { name: "cppccChairElections", category: "runtime" },
  { name: "cppccChairNominations", category: "runtime" },
  { name: "npcscChairElections", category: "runtime" },
  { name: "npcscChairNominations", category: "runtime" },
  {
    name: "governmentFormationVotes",
    category: "runtime",
    notes:
      "Companion of governmentFormations; appears dormant (only referenced by name propagation).",
  },
  {
    name: "unifiedCabinetMembers",
    category: "runtime",
    notes: "Sibling of cabinetMembers; appears dormant (only referenced by name propagation).",
  },
  {
    name: "committeeAssignments",
    category: "runtime",
    notes:
      "Gameplay committee assignments (carry characterId); previously only dropped by seedLegislationTypes.",
  },

  // Cabinet-governed asset rosters. Bootstrap re-seeds these via zero-count-
  // guarded seeders (seedMilitaryUnits/seedCabinetEstates/…), so they were
  // surviving resets and blocking the fresh-preset roster from seeding.
  { name: "militaryUnits", category: "runtime" },
  { name: "cabinetEstates", category: "runtime" },
  { name: "energyPlants", category: "runtime" },
  { name: "infraProjects", category: "runtime" },

  // ── Conflicts subsystem (WIRE W1–W6; gated behind conflictsEnabled) ─────────
  // All per-world military state, siblings of militaryUnits (already runtime
  // above). Every one is built by gameplay in a specific world and must not
  // outlive it — a command roster or half-fought battle carried into a fresh
  // world is exactly the drift this manifest exists to prevent.
  {
    name: "nationalArsenal",
    category: "runtime",
    notes:
      "Per-country materiel stock and grade by unit domain. Delivered by defence contracts, drawn by recruitment and by the refit step. RUNTIME: no seeder writes it — every nation starts with an empty store and builds up, so an absent document and an empty one are the same thing.",
  },
  {
    name: "defenceContracts",
    category: "runtime",
    notes:
      "Procurement contracts between a country's defence seat and one of its own defence sectors. RUNTIME: awarded by players, paid per delivered lot out of the defence appropriation. Wiped with the militaryUnits and corporateSectors they sit between.",
  },
  {
    name: "defenceProcurementAllocations",
    category: "runtime",
    notes:
      "Race-safe per-window contracting quotas. RUNTIME: derived from player-awarded defence contracts and must not survive a world reset.",
  },
  {
    name: "militaryCommands",
    category: "runtime",
    notes:
      "Per-country theater command org (regions, roster, assigned units), built by the defense holder. Wiped with the militaryUnits it references.",
  },
  {
    name: "militaryFormations",
    category: "runtime",
    notes:
      "Per-country combat org: unit formations + their general, and per-unit role assignments. Wiped with the militaryUnits it references.",
  },
  {
    name: "battleDeclarations",
    category: "runtime",
    notes:
      "Declared offensives awaiting resolution on the following turn. Purely in-flight turn state.",
  },
  {
    name: "battleReports",
    category: "runtime",
    notes: "Resolved/fizzled offensive records read by both nations' War Rooms. Per-world history.",
  },
  {
    name: "theaterState",
    category: "runtime",
    notes: "Per-country per-theater situation/CP pool. Regenerated by gameplay.",
  },
  {
    name: "nationalDoctrine",
    category: "runtime",
    notes:
      "Per-country doctrine tree selections. Chosen by the defense holder at runtime (era-gated), not seeded reference data.",
  },
  {
    name: "characterGenerals",
    category: "runtime",
    notes:
      "Per-character general profile (spec, level, xp, trained traits). Runtime rather than preserved: the level/xp is earned fighting this world's battles, and a soft reset retires every character while wiping militaryUnits/formations — so a surviving profile would be orphaned progression keyed to a retired character.",
  },

  // Index-fund holder/runtime state (definitions are reference; see indexFunds).
  { name: "indexFundPositions", category: "runtime" },
  { name: "indexFundRedemptionQueue", category: "runtime" },
  { name: "indexFundSnapshots", category: "runtime" },
  { name: "indexFundTransactions", category: "runtime" },

  // Trade / diplomacy / international-org runtime.
  { name: "tradeEmbargoes", category: "runtime" },
  {
    name: "embargoCooldowns",
    category: "runtime",
    notes:
      "Trade-embargo cooldown ledger. Previously survived resets, leaking cooldowns into the new world.",
  },
  { name: "tradeFlowSnapshots", category: "runtime" },
  { name: "diplomaticActions", category: "runtime" },
  { name: "customInternationalOrganizations", category: "runtime" },
  { name: "organizationFunds", category: "runtime" },
  { name: "organizationLeadershipElections", category: "runtime" },
  { name: "organizationMembershipProposals", category: "runtime" },
  { name: "organizationPostures", category: "runtime" },
  // Seeded at reset from the authored alignment tables, then advanced by the
  // alignment turn phase — runtime world state, wiped and reseeded like the
  // org collections above.
  { name: "countryAlignments", category: "runtime" },

  // Queued influence plays, consumed by the alignment turn phase. Player
  // actions against runtime world state, so wiped and reseeded with it.
  { name: "alignmentPlays", category: "runtime" },

  // Flashpoints blocs bid over. Runtime world state like the rows they move.
  { name: "alignmentCrises", category: "runtime" },

  // The German Question and any later settlement crisis: a standing contest
  // over one nation's constitutional settlement, opened per iteration and
  // advanced by the settlement turn phase. Runtime world state — wiped and
  // reopened on reset, exactly like the alignment rows it sits beside.
  { name: "settlementCrises", category: "runtime" },

  // Queued and resolved plays against a settlement crisis. Player actions
  // against runtime world state, so wiped with it. Resolved rows are stamped
  // rather than deleted during a world's life (they are the audit trail for
  // what a player's money bought), but they do not outlive the world.
  { name: "settlementPlays", category: "runtime" },

  // Crises / referendums / debates / discussions.
  { name: "crisisAidCommitments", category: "runtime" },
  { name: "crisisInteractions", category: "runtime" },
  {
    name: "crisisAutoCooldowns",
    category: "runtime",
    notes:
      "Auto-crisis spawn cooldown (turn-based lastSpawnTurn). Previously survived resets, suppressing crisis spawns in the new world.",
  },
  { name: "referendums", category: "runtime" },
  { name: "referendumWire", category: "runtime" },
  { name: "debateSessions", category: "runtime" },
  { name: "billDiscussions", category: "runtime" },
  { name: "billDiscussionReactions", category: "runtime" },

  // Per-country / per-state runtime + histories.
  { name: "countryLeaderStates", category: "runtime" },
  { name: "characterStateOrg", category: "runtime" },
  { name: "rulingPartyPurgeEvents", category: "runtime" },
  { name: "redistrictLedger", category: "runtime" },
  { name: "stateApprovalHistory", category: "runtime" },
  { name: "stateMetricHistory", category: "runtime" },
  {
    name: "macroMetricsHistory",
    category: "runtime",
    notes:
      "SP5: the macro slice of the per-turn metric history (formerly stateMetricHistory's economic/population series). Wiped on reset, rebuilt by play.",
  },
  {
    name: "parliamentSeatsHistory",
    category: "runtime",
    notes: "Per-turn parliament composition snapshots (capped history), written by the turn phase.",
  },
  {
    name: "corporationCountryHistory",
    category: "runtime",
    notes: "Per-turn per-country corporation aggregate snapshots (capped history).",
  },
  { name: "voteTallies", category: "runtime" },
  { name: "corporationShareInvites", category: "runtime" },
  { name: "wealthListHistory", category: "runtime" },
  { name: "wealthListSnapshots", category: "runtime" },
  {
    name: "seedDiagnostics",
    category: "runtime",
    notes:
      "Seed self-diagnostic reports (conformance + drift). Wiped on reset; re-populated in Phase 4 after bootstrap. Capped to last 50 docs on insert.",
  },
  {
    name: "seedDiagnosticBaselines",
    category: "runtime",
    notes:
      "Singleton baseline snapshot ({_id:'current'}) captured post-reset after conformance. Wiped on reset; re-captured in Phase 4b when conformance has no criticals.",
  },

  // ── 2026-07 backfill: gameplay state added since the last manifest sweep ──
  {
    name: "acquisitionOffers",
    category: "runtime",
    notes: "Corporate acquisition offers (corporations/[id]/deals). Owned by gameplay.",
  },
  {
    name: "impeachments",
    category: "runtime",
    notes: "Impeachment articles and votes. Owned by gameplay.",
  },
  {
    name: "speakerVacateMotions",
    category: "runtime",
    notes: "Motions to vacate the Speaker's chair. Owned by gameplay.",
  },
  {
    name: "ukJudicialReviewCases",
    category: "runtime",
    notes: "UK judicial-review cases spawned by the turn pipeline (ukJrSurpriseTurn).",
  },
  {
    name: "manifestos",
    category: "runtime",
    notes:
      "Westminster party manifestos (#901). Owned by gameplay; no seeder writes them. Accessed via db/collections/manifestos.ts.",
  },
  {
    name: "ukBudgets",
    category: "runtime",
    notes:
      "UK Westminster Budgets (#901). Owned by gameplay; no seeder writes them. Accessed via db/collections/ukBudgets.ts. Distinct from the regional ukBudget budget rows.",
  },
  {
    name: "ukNhsState",
    category: "runtime",
    notes:
      "UK NHS state (#901). Owned by gameplay and the turn pipeline; no seeder writes it. Accessed via uk/nhs/nhsStore.ts.",
  },
];

// ─── Preserved collections ───────────────────────────────────────────────────
// Survive reset by default. Some (users, characters) have an opt-in "full
// reset" mode that nukes them; that path is documented in resetGameWorld.

const PRESERVED: CollectionEntry[] = [
  {
    name: "users",
    category: "preserved",
    notes:
      "Admin users (isAdmin: true) always preserved. Non-admin users are also preserved on a soft reset; deleted when deleteProfiles: true is passed.",
  },
  {
    name: "characters",
    category: "preserved",
    notes:
      "Soft reset retires every character (preserving history). Full reset (deleteProfiles: true) deletes the documents.",
  },
  { name: "retiredCharacters", category: "preserved" },
  { name: "characterAchievements", category: "preserved" },
  {
    name: "imperialCharacters",
    category: "preserved",
    notes:
      "Heads-of-state for monarchies (e.g. JP Emperor). Reset clears the user-side activeImperialCharacterId pointer but leaves the imperial-character documents in place so they survive across worlds.",
  },
  {
    name: "adminLogs",
    category: "preserved",
    notes: "Audit trail. Reset writes a new game_reset entry but never wipes the collection.",
  },
  {
    name: "migrations",
    category: "preserved",
    notes: "Registry of which deploy migrations have run. MUST NOT be reset.",
  },
  { name: "bannedIps", category: "preserved" },
  { name: "botApiKeys", category: "preserved" },
  { name: "botApiRequestLog", category: "preserved" },
  { name: "userApiKeys", category: "preserved" },
  { name: "discordBotFunds", category: "preserved" },
  { name: "userSubscriptions", category: "preserved", notes: "Patreon tier records." },
  { name: "feedback", category: "preserved" },
  {
    name: "tickets",
    category: "preserved",
    notes:
      "Discord-bot support tickets (triage pipeline). Community/support content — must survive resets like feedback/suggestions.",
  },
  { name: "modAuditLog", category: "preserved" },
  {
    name: "partyMembershipEvents",
    category: "preserved",
    notes: "Append-only party join/leave/purge audit trail for moderation investigations.",
  },
  { name: "comments", category: "preserved" },
  { name: "suggestions", category: "preserved" },
  { name: "suggestionComments", category: "preserved" },
  { name: "suggestionReactions", category: "preserved" },
  { name: "suggestionReads", category: "preserved" },
  { name: "suspiciousCharacters", category: "preserved", notes: "Mod tooling state." },
  {
    name: "wikiReports",
    category: "preserved",
    notes: "Player-filed wiki page issue reports; feedback, survives world resets.",
  },
  { name: "systemSettings", category: "preserved" },
  { name: "systemTags", category: "preserved" },
  { name: "tasks", category: "preserved", notes: "Admin task tracker." },
  { name: "taskComments", category: "preserved" },
  { name: "taskLessons", category: "preserved" },
  { name: "roadmapCategories", category: "preserved" },
  { name: "roadmapItems", category: "preserved" },
  { name: "wikiPages", category: "preserved" },
  { name: "wikiTemplates", category: "preserved" },
  { name: "changelogSentHistory", category: "preserved" },
  { name: "remediations", category: "preserved", notes: "Incident-script registry." },

  // ── 2026-06 backfill: infra / audit / admin-config that must survive reset ──
  { name: "apiAccessLog", category: "preserved", notes: "API access audit log." },
  { name: "apiAbuseScans", category: "preserved", notes: "API-abuse detection audit." },
  { name: "rateLimitBuckets", category: "preserved", notes: "Rate-limit infra." },
  { name: "ipGeoCache", category: "preserved", notes: "IP-geo lookup cache." },
  { name: "playerBannerAds", category: "preserved", notes: "Banner-ad infra/content." },
  {
    name: "manualOfficeHistory",
    category: "preserved",
    notes: "Wiki/community-authored office history.",
  },
  {
    name: "migrationsRun",
    category: "preserved",
    notes: "Migration-run registry (twin of `migrations`). MUST NOT be reset.",
  },
  {
    name: "demographicConfigOverrides",
    category: "preserved",
    notes:
      "Admin-authored era/position overrides (written by the position editor, consumed by the seed pipeline). Persists across resets as authored config.",
  },

  // ── 2026-07 backfill: moderation / audit surfaces that must survive reset ──
  {
    name: "altLinks",
    category: "preserved",
    notes: "Alt-account link evidence. Moderation history — must outlive a world reset.",
  },
  {
    name: "altClusters",
    category: "preserved",
    notes: "Alt-account clusters derived from altLinks. Moderation history.",
  },
  {
    name: "altDigestState",
    category: "preserved",
    notes: "Alt-detection digest cursor/state. Resetting it would replay old alerts.",
  },
  {
    name: "altScoringRuns",
    category: "preserved",
    notes:
      "Per-run alt-scoring telemetry (candidate volume, confidence distribution, per-signal firing trends). Staff operational history, not world state — its whole value is the longitudinal trend that shows a signal going silent, so a world reset must not erase it. Self-bounding via a 90-day TTL index.",
  },
  {
    name: "actionAuditLog",
    category: "preserved",
    notes: "Append-only player-action audit trail consumed by alt detection.",
  },
  {
    name: "auditAnomalies",
    category: "preserved",
    notes: "Forensic anomaly findings. Audit trail.",
  },
  {
    name: "watchlist",
    category: "preserved",
    notes: "Admin watchlist entries. Admin metadata.",
  },
  {
    name: "supporterRequests",
    category: "preserved",
    notes: "Player supporter/perk requests. User-linked community content.",
  },
  {
    name: "simRuns",
    category: "preserved",
    notes:
      "Offline election-balance sim harness run records (src/lib/sim). Analysis artifact, not gameplay state — never needed for a fresh game.",
  },
];

// ─── Known inconsistencies ───────────────────────────────────────────────────
// Collections that look like typos or duplicates. Surface these here so we
// don't silently classify them away — fix the underlying issue, then prune
// the entry.

export const KNOWN_INCONSISTENCIES: ReadonlyArray<{ collection: string; issue: string }> = [
  {
    collection: "commodityPrice",
    issue:
      "Singular form. Production uses commodityPrices (plural). Audit reads/writes and consolidate.",
  },
  {
    collection: "primarySnapshot",
    issue: "Singular form. Production uses primarySnapshots (plural). Audit and consolidate.",
  },
  {
    collection: "officials",
    issue: "Legacy synonym of electedOfficials. Migrate residual readers/writers and drop.",
  },
  {
    collection: "legislation",
    issue: "Legacy collection. Production uses bills + stateBills. Audit and drop.",
  },
  {
    collection: "stateMetricBaselines",
    issue: "Legacy parallel to stateBaselines. Phase 5 of the reset/seed cleanup folds this away.",
  },
];

// ─── The manifest ────────────────────────────────────────────────────────────

export const SEED_MANIFEST: ReadonlyArray<CollectionEntry> = [
  ...REFERENCE,
  ...RUNTIME,
  ...PRESERVED,
];

const BY_NAME: ReadonlyMap<string, CollectionEntry> = new Map(
  SEED_MANIFEST.map((entry) => [entry.name, entry])
);

/** Returns every collection in the given category. */
export function getCollectionsByCategory(category: CollectionCategory): CollectionEntry[] {
  return SEED_MANIFEST.filter((entry) => entry.category === category);
}

/** Returns the classification for a collection name, or undefined if unknown. */
export function getCollectionCategory(name: string): CollectionCategory | undefined {
  return BY_NAME.get(name)?.category;
}

/** Names of every runtime collection — the set wiped on reset. */
export function getRuntimeCollectionNames(): string[] {
  return RUNTIME.map((entry) => entry.name);
}

/** Names of every reference collection — the set seeded on bootstrap. */
export function getReferenceCollectionNames(): string[] {
  return REFERENCE.map((entry) => entry.name);
}

/** Names of every preserved collection — the set that survives reset. */
export function getPreservedCollectionNames(): string[] {
  return PRESERVED.map((entry) => entry.name);
}

/**
 * Returns collection names present in the live database that are NOT in the
 * manifest. Use this in contract tests / admin diagnostics to surface drift.
 */
export function findUnclassifiedCollections(liveCollectionNames: ReadonlyArray<string>): string[] {
  return liveCollectionNames.filter((name) => !BY_NAME.has(name));
}
