/**
 * Seed manifest — source of truth for which MongoDB collections are seeded,
 * wiped, or preserved by reset/bootstrap.
 *
 * Consumed by:
 *   - `resetGameWorld` (which collections to wipe on a reset)
 *   - `bootstrapGameWorld` (which collections to seed on a fresh start)
 *   - Admin seeder UI (`UniversalSeeder`) and `/api/admin/seed`
 *   - CLI scripts (`scripts/reset-and-bootstrap.ts`, `scripts/bootstrap-full.ts`)
 *   - Contract tests (`bootstrapGameWorld.contract.test.ts`)
 *
 * Companion doc: `docs/reset-and-seed-contract.md`.
 *
 * If you add a new MongoDB collection, add it here so reset/bootstrap behaviour
 * stays explicit. An unclassified collection is a latent bug — it will quietly
 * survive resets and quietly miss out on bootstrap.
 */

/**
 * Lifecycle category for a MongoDB collection.
 *
 * - `reference`: Seeded on every fresh start. Drives game-world structure
 *   (states, parties, baselines, legislation types, …). Idempotent seeders
 *   re-upsert these.
 *
 * - `runtime`: Wiped on a soft world reset (`deleteProfiles: false`) and on
 *   a full reset. Regenerated by gameplay (turns, actions, elections, …).
 *   Bootstrap may pre-populate some of these to a starting state (e.g. seed
 *   elections), but their steady-state owner is gameplay, not the seeder.
 *
 * - `preserved`: Survives reset by default. Player accounts, admin metadata,
 *   community content, audit trails, migration registry. A *full* reset
 *   (`deleteProfiles: true`) may still nuke some of these (e.g. non-admin
 *   users), but the default is "keep".
 *
 * - `migration-only`: Touched only by one-off live-data migrations
 *   (`scripts/migrations/`). Never required to exist for a brand-new game.
 *
 * - `incident-only`: Touched only by incident-response scripts
 *   (`scripts/heal-*`, etc.). Never part of the normal bootstrap or reset
 *   path.
 */
import type { CollectionEntry } from "./seedManifestTypes";
import { RUNTIME } from "./seedManifestRuntime";
import { PRESERVED } from "./seedManifestPreserved";

export type { CollectionCategory, CollectionEntry } from "./seedManifestTypes";

// ─── Reference collections ───────────────────────────────────────────────────
// Seeded every fresh start; idempotent re-runs.

const REFERENCE: CollectionEntry[] = [
  { name: "states", category: "reference", seededBy: "runCoreSeed" },
  { name: "policies", category: "reference", seededBy: "runCoreSeed" },
  { name: "demographicCategories", category: "reference", seededBy: "runCoreSeed" },
  { name: "stateDemographics", category: "reference", seededBy: "runCoreSeed" },
  { name: "demographicDefaults", category: "reference", seededBy: "runCoreSeed" },
  { name: "stateDemographicTurnout", category: "reference", seededBy: "runCoreSeed" },
  { name: "gameConfig", category: "reference", seededBy: "runCoreSeed" },
  {
    name: "politicalParties",
    category: "reference",
    seededBy: "seedParties",
    notes:
      "Default parties (isDefault: true) are reference. Player-created parties are runtime and wiped on reset.",
  },
  {
    name: "statePartyOrg",
    category: "reference",
    seededBy: "seedParties",
    notes:
      "Default-party rows are reference. Rows tied to player-created parties are runtime. Seeded for US/UK/JP/DE/BR/IE/CN via seedParties; the Cold-War one-party states have their own seeders — seedRuStatePartyOrg (CPSU), seedDdStatePartyOrg (National Front), seedCnStatePartyOrg (advisory parties), and seedEasternBlocStatePartyOrg (the six satellites' ruling parties plus the republican parties of UKR/BLR/BAL).",
  },
  {
    name: "macroMetrics",
    category: "reference",
    seededBy: "seedRegionMetrics",
    notes:
      "The economy engine's working state (economic.* + population.* + independenceDesire + the objective fiscal pair + economicModel) for EVERY country's regions. Extracted from the legacy-shaped seed docs at each seeder's write site (writeSplitMetrics). This is the ONLY region-metrics store now — the political half lives on politicalMetrics.",
  },
  {
    name: "stateMetrics",
    category: "reference",
    seededBy: "seedRegionMetrics",
    notes:
      "Legacy-shaped per-region metrics doc (economic.* / population.* / political.*), keyed by stateId. The split stores above (macroMetrics + politicalMetrics) are the working state; this remains the read surface for consumers that want one doc per region — e.g. the P3a capacity build price, which reads economic.costOfLiving to index construction cost by host state.",
  },
  {
    name: "politicalMetrics",
    category: "reference",
    seededBy: "seedPoliticalMetrics",
    notes:
      "Political Metrics (new domain, separate from stateMetrics). One doc per US/UK/RU/DD region; values drifted each turn by the SP2 dynamics phase; residuals set at reset by seedPoliticalMetricsResiduals.",
  },
  {
    name: "politicalMetricsHistory",
    category: "runtime",
    notes:
      "SP2 trend history: one doc per country, national aggregate appended every 24 turns by processPoliticalMetricsDynamics, capped at 365 entries. Runtime — wiped on reset, rebuilt by play.",
  },
  {
    name: "politicalMetricsRegionHistory",
    category: "runtime",
    notes:
      "Per-region trend history (issue #1322): one doc per REGION, that region's own post-drift board appended every 24 turns by processPoliticalMetricsDynamics, capped at 90 entries. One doc per region rather than per country because a country doc holding all 51 US regions at the cap approaches the 16MB BSON ceiling. Runtime — wiped on reset, rebuilt by play; there is no backfill, so the region trend tiles read 'series begins this campaign' until two entries exist.",
  },
  {
    name: "politicalCabinetContribution",
    category: "runtime",
    notes:
      "Per-country snapshot of the standing cabinet contribution to political metrics (PoliticalMetricId → points/turn nationally, plus optional per-region extras from sited estates/orders), written each turn by processMinisterialOrders and folded into region cabinetResiduals by processPoliticalMetricsDynamics. Runtime — wiped on reset, rebuilt by play.",
  },
  {
    name: "conflicts",
    category: "runtime",
    notes:
      "Dynamic conflicts (the generalized-theater model, replacing the 4 static theaters). Created during play by player declarations / events; the world starts empty. Units/generals/battles run on these via unit.theaterId = a conflict id. Runtime — wiped on reset, rebuilt by play.",
  },
  {
    name: "peaceOffers",
    category: "runtime",
    notes:
      "Pending and resolved country peace proposals for dynamic conflicts. Runtime data is wiped on reset and rebuilt by play.",
  },
  {
    name: "nationalManpower",
    category: "runtime",
    seededBy: "runCoreSeed",
    notes:
      "Per-country replacement-manpower pool + reinforcement mode. Regenerates each turn from population × the conscription stance and is drawn down to refill under-strength units. Runtime — wiped on reset, then re-seeded by runCoreSeed (seedNationalManpower) at 25% of each nation's ceiling and maintained by play. Before that seeder existed the collection started empty and the turn loop won the race to create it, leaving every nation at one turn's regeneration.",
  },
  { name: "stateBaselines", category: "reference", seededBy: "runCoreSeed" },
  {
    name: "stateMetricBaselines",
    category: "reference",
    notes:
      "Legacy parallel of stateBaselines. JP/DE/IE/BR/CN seeders used to write here even though runtime (policyEffects.ts) only reads stateBaselines — Phase 5 of the reset/seed cleanup pointed all seeders at stateBaselines. The legacy collection is kept in the manifest so live databases with stragglers stay classified; once production is purged of these rows the entry can be removed.",
  },
  { name: "legislationTypes", category: "reference", seededBy: "seedLegislationTypes" },
  { name: "achievements", category: "reference", seededBy: "seedAchievements" },
  { name: "federalBudget", category: "reference", seededBy: "seedBudgets" },
  { name: "stateBudgets", category: "reference", seededBy: "seedBudgets" },
  {
    name: "regionalBudgets",
    category: "runtime",
    notes:
      "RUNTIME, not reference: no seeder writes this. Every row is produced by the per-turn regional-budget processors (regionalBudget/cnRegionalBudget/deRegionalBudget/jpRegionalBudget/ruRegionalBudget). It was classified `reference` with seededBy: seedUkBudgets, which writes nothing here — so the runtime sweep skipped it AND the reference drop list skipped it, and rows accumulated across resets. That is why stale orphans from the pre-rename CN region ids (NORTHEAST/EAST/...) are still in production, worked around downstream in budget/spending.ts rather than cleaned up.",
  },
  { name: "formulaGrants", category: "reference", seededBy: "seedBudgets" },
  { name: "stateResourceCapacity", category: "reference", seededBy: "seedStateResourceCapacity" },
  {
    name: "stateSectorSpecializations",
    category: "reference",
    seededBy: "seedStateSectorSpecializations",
  },
  { name: "partyBudget", category: "reference", seededBy: "seedPartyBudgets" },
  { name: "unownedSectors", category: "reference", seededBy: "seedUnownedSectors" },
  {
    name: "unions",
    category: "runtime",
    seededBy: "seedUnions",
    notes:
      "One vacant-head union per (countryId, sectorType). Wiped on reset; re-seeded at bootstrap with era-appropriate names.",
  },
  { name: "unionEndorsements", category: "runtime" },
  { name: "unionLeaderVotes", category: "runtime" },
  { name: "unionOrganizers", category: "runtime" },
  {
    name: "bargainingCampaigns",
    category: "runtime",
    notes: "Release 1.1 union-employer negotiation history; tied to unions and corporations.",
  },
  {
    name: "collectiveAgreements",
    category: "runtime",
    notes: "Release 1.1 enforceable wage and labor-peace terms; tied to campaign locals.",
  },
  { name: "seats", category: "reference", seededBy: "seedSeats" },
  { name: "statePolicies", category: "reference", seededBy: "seedStatePolicies" },
  {
    name: "internationalOrganizations",
    category: "reference",
    seededBy: "seedInternationalOrganizations",
  },
  {
    name: "centralBanks",
    category: "reference",
    seededBy: "seedForex",
    notes:
      "One row per preset-scoped country with both an active currency and an authored national fiscal model. Currency-only exclusions remain in exchangeRates and are exposed by the seed diagnostic's monetaryCoverage manifest. WIPED on reset and re-seeded by seedForex: `resetGameWorld` deletes this collection explicitly alongside statePolicies/commodityPrices/exchangeRates, because the seeder is $setOnInsert-only and would otherwise leave the previous world's accumulated CB state (prime rate, rate history) in place. (This note previously claimed CB state survives reset — it does not.)",
  },
  {
    name: "exchangeRates",
    category: "reference",
    seededBy: "seedForex",
    notes:
      "One row per forex-active currency at its starting rate. Rates float at runtime via forexTurn.ts; the seed sets the starting point.",
  },
  {
    name: "commodityPrices",
    category: "reference",
    seededBy: "seedCommodityPrices",
    notes:
      "Current price is reference seed (one row per commodity at base price); price ticks accumulate in commodityPriceHistory at runtime.",
  },
  {
    name: "macroCountries",
    category: "reference",
    seededBy: "seedMacroCountries",
    notes:
      "Tier-2 sphere-macro aggregate state + held market contribution (#3716/#3719/#3720/#3721). Seeded for European (AT oracle + FI/GR/IE), Asian/ME (JO/AF/YE/MM/LA/KH/TH), and African/American (ET/ZA/CU/GT/PA/NI/CL/AR/MX/VE) 1953 rosters; kernel refreshes every six turns. Planned Eastern-bloc CountryId countries (PL/CS/HU/RO/BG/YU plus the union republics UKR/BLR/BAL) were promoted to full-autonomous Tier-1 — their dormant macro specs are not seeded. Planned economies never seed market corporations.",
  },
  {
    name: "landeslisten",
    category: "runtime",
    notes:
      "RUNTIME, not reference: seedDE does not write this. Lists are generated in-game by autoGenerateLandesliste from party members, keyed by cycle, and can carry chair edits until lockedAt. Classified `reference` it survived resets, leaving a fresh world holding the previous world's lists keyed to parties and characters that no longer exist.",
  },
  {
    name: "strategicSectorDesignations",
    category: "reference",
    seededBy: "seedStrategicSectors",
    notes:
      "Per-country default strategic sectors (arms the strategic nationalization trigger). Idempotent upsert per (countryId, sectorType). Head-of-government designations at runtime upsert into the same collection.",
  },
  {
    name: "congressionalDistricts",
    category: "reference",
    seededBy: "seedCongressionalDistricts",
    notes:
      "Idempotent upsert from runCoreSeed; redistricting mutates rows at runtime, refreshed when bootstrap re-seeds reference (resetReference:true).",
  },
  {
    name: "regionDemographics",
    category: "reference",
    seededBy: "seedCohortVectors",
    notes:
      "Idempotent upsert from bootstrap's seedCohortVectors; demographics phase mutates at runtime.",
  },
  {
    name: "stateRegistrationPool",
    category: "reference",
    seededBy: "seedRegistrationLanes",
    notes:
      "Idempotent upsert from bootstrap's seedRegistrationLanes; per-turn registration drift mutates it like stateMetrics.",
  },
];

// ─── Known inconsistencies ───────────────────────────────────────────────────
// Collections that look like typos or duplicates. Surface these here so we
// don't silently classify them away — fix the underlying issue, then prune
// the entry.

export const KNOWN_INCONSISTENCIES: ReadonlyArray<{ collection: string; issue: string }> = [
  {
    collection: "commodityPrice",
    issue:
      "Singular form. Production uses commodityPrices (plural). Audit reads/writes and consolidate.",
  },
  {
    collection: "primarySnapshot",
    issue: "Singular form. Production uses primarySnapshots (plural). Audit and consolidate.",
  },
  {
    collection: "officials",
    issue: "Legacy synonym of electedOfficials. Migrate residual readers/writers and drop.",
  },
  {
    collection: "legislation",
    issue: "Legacy collection. Production uses bills + stateBills. Audit and drop.",
  },
  {
    collection: "stateMetricBaselines",
    issue: "Legacy parallel to stateBaselines. Phase 5 of the reset/seed cleanup folds this away.",
  },
];

// ─── The manifest ────────────────────────────────────────────────────────────

export const SEED_MANIFEST: ReadonlyArray<CollectionEntry> = [
  ...REFERENCE,
  ...RUNTIME,
  ...PRESERVED,
];

const BY_NAME: ReadonlyMap<string, CollectionEntry> = new Map(
  SEED_MANIFEST.map((entry) => [entry.name, entry])
);

/** Returns every collection in the given category. */
export function getCollectionsByCategory(category: CollectionCategory): CollectionEntry[] {
  return SEED_MANIFEST.filter((entry) => entry.category === category);
}

/** Returns the classification for a collection name, or undefined if unknown. */
export function getCollectionCategory(name: string): CollectionCategory | undefined {
  return BY_NAME.get(name)?.category;
}

/** Names of every runtime collection — the set wiped on reset. */
export function getRuntimeCollectionNames(): string[] {
  return getCollectionsByCategory("runtime").map((entry) => entry.name);
}

/** Names of every reference collection — the set seeded on bootstrap. */
export function getReferenceCollectionNames(): string[] {
  return getCollectionsByCategory("reference").map((entry) => entry.name);
}

/** Names of every preserved collection — the set that survives reset. */
export function getPreservedCollectionNames(): string[] {
  return getCollectionsByCategory("preserved").map((entry) => entry.name);
}

/**
 * Returns collection names present in the live database that are NOT in the
 * manifest. Use this in contract tests / admin diagnostics to surface drift.
 */
export function findUnclassifiedCollections(liveCollectionNames: ReadonlyArray<string>): string[] {
  return liveCollectionNames.filter((name) => !BY_NAME.has(name));
}
