import type { Metadata } from "next";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import {
  getAllWikiSlugsAsync,
  getWikiPageData,
  getWikiPagesBySlugs,
} from "@/lib/wiki/getWikiPageData";
import { loadWikiContent } from "@/lib/wiki/loadContent";
import { getRedirectTarget } from "@/lib/wiki/redirects";
import {
  generatedOfficeDefaultContent,
  getGeneratedOfficeDefinition,
  getGeneratedOfficePageData,
  type GeneratedOfficePageData,
  type OfficeTenureEntry,
} from "@/lib/wiki/autoGeneratedPages";
import { MarkdownContent } from "@/components/wiki/MarkdownContent";
import { OfficeHistoryAdmin } from "@/components/wiki/OfficeHistoryAdmin";
import { WikiTableOfContents } from "@/components/wiki/WikiTableOfContents";
import { Breadcrumbs } from "@/components/wiki/layout/Breadcrumbs";
import { PageMetadata } from "@/components/wiki/layout/PageMetadata";
import { getAuthUserWithCharacter } from "@/lib/auth";
import { getDb } from "@/lib/mongodb";
import { getWikiCanonicalUrl } from "@/lib/siteMetadata";

interface WikiPageProps {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: WikiPageProps): Promise<Metadata> {
  const { slug } = await params;
  if (getRedirectTarget(slug)) return { title: "Redirect" };
  const page = await getWikiPageData(slug);
  const generatedDefinition = await getGeneratedOfficeDefinition(slug);
  if (!page && !generatedDefinition)
    return { title: "Not Found", robots: { index: false, follow: false } };
  if (!page && generatedDefinition) {
    const title = `${generatedDefinition.title} | Game Wiki | A House Divided`;
    const description = generatedDefinition.description;
    const canonical = getWikiCanonicalUrl(`/wiki/${slug}`);
    return {
      title,
      description,
      alternates: { canonical },
      openGraph: {
        title,
        description,
        url: canonical,
        type: "article",
        siteName: "A House Divided",
      },
      twitter: {
        card: "summary",
        title,
        description,
      },
    };
  }
  if (!page) return { title: "Not Found", robots: { index: false, follow: false } };
  const title = `${page.title} | Game Wiki | A House Divided`;
  const description = page.description;
  const canonical = getWikiCanonicalUrl(`/wiki/${slug}`);
  return {
    title,
    description,
    alternates: { canonical },
    openGraph: {
      title,
      description,
      url: canonical,
      type: "article",
      siteName: "A House Divided",
    },
    twitter: {
      card: "summary",
      title,
      description,
    },
  };
}

function extractHeadings(content: string): { id: string; text: string; level: number }[] {
  const headings: { id: string; text: string; level: number }[] = [];
  for (const line of content.split("\n")) {
    const h2 = line.match(/^##\s+(.+)$/);
    const h3 = line.match(/^###\s+(.+)$/);
    if (h2) {
      const text = h2[1].trim();
      headings.push({
        id: text
          .toLowerCase()
          .replace(/\s+/g, "-")
          .replace(/[^a-z0-9-]/g, ""),
        text,
        level: 2,
      });
    } else if (h3) {
      const text = h3[1].trim();
      headings.push({
        id: text
          .toLowerCase()
          .replace(/\s+/g, "-")
          .replace(/[^a-z0-9-]/g, ""),
        text,
        level: 3,
      });
    }
  }
  return headings;
}

export default async function WikiPage({ params }: WikiPageProps) {
  const { slug } = await params;
  const redirectTo = getRedirectTarget(slug);
  if (redirectTo) redirect(redirectTo);
  if (slug === "elections") notFound();

  const generatedOfficePage = await getGeneratedOfficePageData(slug);
  if (generatedOfficePage) {
    const user = await getAuthUserWithCharacter();
    const editableContent = generatedOfficePage.hasEditableContent
      ? await loadWikiContent(slug)
      : null;
    return (
      <GeneratedOfficeWikiPage
        slug={slug}
        page={generatedOfficePage}
        editableContent={editableContent}
        canEdit={Boolean(user && generatedOfficePage.hasEditableContent)}
        isAdmin={user?.isAdmin === true}
      />
    );
  }

  const page = await getWikiPageData(slug);
  if (!page) notFound();

  const content = await loadWikiContent(slug);
  if (!content) notFound();

  const headings = extractHeadings(content);
  const user = await getAuthUserWithCharacter();

  // Fire-and-forget view count increment
  getDb()
    .then((db) => db.collection("wikiPages").updateOne({ slug }, { $inc: { viewCount: 1 } }))
    .catch(() => {});

  // Track wiki visit for onboarding checklist
  if (slug === "getting-started" && user?.character) {
    getDb()
      .then((db) =>
        db
          .collection("characters")
          .updateOne(
            { _id: user.character!._id, hasReadWiki: { $ne: true } },
            { $set: { hasReadWiki: true } }
          )
      )
      .catch(() => {});
  }

  return (
    <div className="mx-auto max-w-4xl min-w-0 overflow-x-hidden px-4 py-8">
      <Breadcrumbs items={[{ label: "Wiki", href: "/wiki" }, { label: page.title }]} />

      {user && (
        <div className="mb-4 flex justify-end">
          <Link
            href={`/wiki/${slug}/edit`}
            className="rounded-md border border-card-border bg-card/40 px-4 py-2 text-sm text-muted transition-colors hover:border-primary/40 hover:text-primary"
          >
            Edit page
          </Link>
        </div>
      )}

      <PageMetadata
        category={page.category}
        contentType={page.contentType}
        difficulty={page.difficulty}
        estimatedReadTime={page.estimatedReadTime}
        lastUpdated={page.lastUpdated ?? page.updatedAt}
        designDocUrl={page.designDocUrl}
        gameIteration={page.gameIteration}
        gameStartDate={page.gameStartDate}
        reportSlug={slug}
      />

      {headings.length > 0 && <WikiTableOfContents headings={headings} className="mb-8" />}

      <article className="prose prose-invert max-w-none overflow-x-hidden">
        <MarkdownContent content={content} headings={headings} />
      </article>

      <RelatedPagesFooter
        currentSlug={slug}
        currentCategory={page.category}
        currentTags={page.tags}
      />
    </div>
  );
}

function formatRealLifeDate(date?: Date): string {
  if (!date) return "";
  return new Intl.DateTimeFormat("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  }).format(new Date(date));
}

/**
 * Real-world (wall-clock) date range a holder served, e.g.
 * "June 16, 2026 - Present" or "June 16, 2026 - June 19, 2026". Manually
 * curated entries carry no real service date, so they render "—".
 */
function realLifeDateRange(entry: OfficeTenureEntry): string {
  if (!entry.startDate) return "—";
  const start = formatRealLifeDate(entry.startDate);
  const end = entry.endDate ? formatRealLifeDate(entry.endDate) : "Present";
  return `${start} - ${end}`;
}

function tenureRangeWeekYear(entry: OfficeTenureEntry): string {
  if (!entry.startWeekYear) return "—";
  const end = entry.endWeekYear ?? "Incumbent";
  return `${entry.startWeekYear} - ${end}`;
}

function GeneratedOfficeWikiPage({
  slug,
  page,
  editableContent,
  canEdit,
  isAdmin,
}: {
  slug: string;
  page: GeneratedOfficePageData;
  editableContent: string | null;
  canEdit: boolean;
  isAdmin: boolean;
}) {
  const content = editableContent ?? generatedOfficeDefaultContent(page.definition);
  const headings = extractHeadings(content);
  const current = page.currentHolder;

  return (
    <div className="mx-auto max-w-4xl min-w-0 overflow-x-hidden px-4 py-8">
      <Breadcrumbs
        items={[
          { label: "Wiki", href: "/wiki" },
          { label: "Auto-generated pages", href: "/wiki#auto-generated-pages" },
          { label: page.definition.title },
        ]}
      />

      {canEdit && (
        <div className="mb-4 flex justify-end">
          <Link
            href={`/wiki/${slug}/edit`}
            className="rounded-md border border-card-border bg-card/40 px-4 py-2 text-sm text-muted transition-colors hover:border-primary/40 hover:text-primary"
          >
            Edit article text
          </Link>
        </div>
      )}

      <header className="mb-6 border-b border-card-border pb-5">
        <p className="section-label mb-2">Generated office page</p>
        <h1 className="text-3xl font-bold tracking-tight text-foreground">
          {page.definition.title}
        </h1>
        <p className="mt-2 max-w-3xl text-muted">{page.definition.description}</p>
      </header>

      <PageMetadata
        category="reference"
        contentType="reference"
        lastUpdated={new Date()}
        reportSlug={slug}
      />

      {headings.length > 0 && <WikiTableOfContents headings={headings} className="mb-8" />}

      <article className="prose prose-invert max-w-none overflow-x-hidden">
        <MarkdownContent content={content} headings={headings} />
      </article>

      <section className="mt-8 rounded-xl border border-card-border bg-card/60 p-6">
        <h2 className="mb-4 text-xl font-semibold text-foreground">Current Holder</h2>
        {current ? (
          <div className="rounded-lg border border-card-border bg-card/40 p-4">
            <div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between">
              <div>
                {current.profileHref ? (
                  <Link
                    href={current.profileHref}
                    className="font-semibold text-foreground hover:text-primary"
                  >
                    {current.name}
                  </Link>
                ) : (
                  <span className="font-semibold text-foreground">{current.name}</span>
                )}
                {current.partyLabel && (
                  <span className="ml-2 text-sm text-muted">({current.partyLabel})</span>
                )}
              </div>
              <div className="font-mono text-xs text-muted">{tenureRangeWeekYear(current)}</div>
            </div>
          </div>
        ) : (
          <div className="rounded-lg border border-dashed border-card-border bg-card/40 p-6 text-center">
            <p className="font-medium text-muted">Vacant or not yet recorded</p>
            <p className="mt-1 text-sm text-muted">
              The live history table will populate when the office is filled or when transition
              records are written.
            </p>
          </div>
        )}
      </section>

      <section className="mt-8 rounded-xl border border-card-border bg-card/60 p-6">
        <h2 className="mb-4 text-xl font-semibold text-foreground">Office Holder History</h2>
        <div className="space-y-8">
          {page.tenureGroups.map((group) => (
            <div key={`${group.iteration.type}-${group.iteration.number}`}>
              <h3 className="mb-3 text-sm font-semibold uppercase tracking-wider text-primary">
                {group.label}
              </h3>
              {group.entries.length > 0 ? (
                <div className="overflow-x-auto">
                  <table className="w-full min-w-[680px] text-sm">
                    <thead>
                      <tr className="border-b border-card-border text-left text-xs uppercase tracking-wider text-muted">
                        <th className="pb-2 pr-4 font-semibold">Holder</th>
                        <th className="pb-2 pr-4 font-semibold">Party</th>
                        <th className="pb-2 pr-4 font-semibold">Tenure</th>
                        <th className="pb-2 pr-4 font-semibold">Dates</th>
                        <th className="pb-2 font-semibold">Source</th>
                      </tr>
                    </thead>
                    <tbody>
                      {group.entries.map((entry, index) => (
                        <tr
                          key={`${entry.name}-${entry.startWeekYear ?? entry.manualId ?? index}`}
                          className="border-b border-card-border/50 last:border-0"
                        >
                          <td className="py-3 pr-4 font-medium text-foreground">
                            {entry.profileHref ? (
                              <Link href={entry.profileHref} className="hover:text-primary">
                                {entry.name}
                              </Link>
                            ) : (
                              entry.name
                            )}
                            {entry.isCurrent && (
                              <span className="ml-2 rounded-full bg-primary/15 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-primary">
                                Incumbent
                              </span>
                            )}
                          </td>
                          <td className="py-3 pr-4 text-muted">
                            {entry.partyLabel ?? entry.party ?? "-"}
                          </td>
                          <td className="py-3 pr-4 font-mono text-xs text-muted">
                            {tenureRangeWeekYear(entry)}
                          </td>
                          <td className="py-3 pr-4 text-xs text-muted">
                            {realLifeDateRange(entry)}
                          </td>
                          <td className="py-3 text-muted">{entry.source.replace(/-/g, " ")}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              ) : (
                <p className="rounded-lg border border-dashed border-card-border bg-card/40 px-4 py-3 text-sm text-muted">
                  No recorded holders yet.
                </p>
              )}
              {isAdmin && (
                <OfficeHistoryAdmin
                  officeIdentity={{
                    countryId: page.definition.countryId,
                    officeKind: page.definition.kind,
                    officeType: page.definition.officeType,
                    positionId: page.definition.positionId,
                    leadershipRole: page.definition.leadershipRole,
                  }}
                  iteration={group.iteration}
                  manualRows={group.entries
                    .filter((e) => e.isManual && e.manualId && e.manualData)
                    .map((e) => ({
                      id: e.manualId!,
                      name: e.name,
                      party: e.party,
                      startWeek: e.manualData!.startWeek,
                      startYear: e.manualData!.startYear,
                      endWeek: e.manualData!.endWeek,
                      endYear: e.manualData!.endYear,
                      startDate: e.manualData!.startDate,
                      endDate: e.manualData!.endDate,
                      isIncumbent: e.manualData!.isIncumbent,
                    }))}
                />
              )}
            </div>
          ))}
        </div>
      </section>

      <RelatedPagesFooter currentSlug={slug} currentCategory="reference" />
    </div>
  );
}

async function RelatedPagesFooter({
  currentSlug,
  currentCategory,
  currentTags,
}: {
  currentSlug: string;
  currentCategory?: string;
  currentTags?: string[];
}) {
  const allSlugs = await getAllWikiSlugsAsync();
  const candidateSlugs = allSlugs.filter((s) => s !== currentSlug && s !== "elections");
  const pageMap = await getWikiPagesBySlugs(candidateSlugs);

  const currentTagSet = new Set(currentTags ?? []);
  const currentCat = currentCategory;

  // Score each candidate: shared category = +3, shared tag = +1 each.
  // Sort by score descending, then title ascending. Take top 8.
  const scored = candidateSlugs
    .map((slug) => {
      const pageData = pageMap.get(slug);
      if (!pageData) return null;
      let score = 0;
      if (currentCat && pageData.category && pageData.category === currentCat) {
        score += 3;
      }
      if (currentTagSet.size > 0 && pageData.tags) {
        for (const tag of pageData.tags) {
          if (currentTagSet.has(tag)) score += 1;
        }
      }
      return { slug, title: pageData.title, score };
    })
    .filter((x): x is { slug: string; title: string; score: number } => x !== null)
    .sort((a, b) => {
      if (b.score !== a.score) return b.score - a.score;
      return a.title.localeCompare(b.title);
    })
    .slice(0, 8);

  return (
    <footer className="mt-12 border-t border-card-border pt-6">
      <h3 className="mb-3 text-xs font-semibold uppercase tracking-[0.1em] text-muted">
        Related pages
      </h3>
      <div className="flex flex-wrap gap-2">
        {scored.map(({ slug, title }) => (
          <Link
            key={slug}
            href={`/wiki/${slug}`}
            className="rounded-lg border border-card-border bg-card/40 px-3 py-1.5 text-sm text-muted transition-all hover:-translate-y-px hover:border-primary/40 hover:text-primary"
          >
            {title}
          </Link>
        ))}
      </div>
    </footer>
  );
}
