"use client";

import { useState, useEffect, useCallback } from "react";
import Link from "next/link";

interface PoliticianOverrideItem {
  _id: string;
  politicianId: string;
  customBio?: string;
  customSections?: Array<{ title: string; content: string }>;
  autoGeneratedBio?: string;
  electionHistory?: unknown[];
  hasHeldCongressLeadership?: boolean;
  updatedAt: string;
}

interface PoliticianData {
  id: string;
  sequentialId?: number;
  name: string;
}

export function PoliticianPagesTab() {
  const [overrides, setOverrides] = useState<PoliticianOverrideItem[]>([]);
  const [politicians, setPoliticians] = useState<PoliticianData[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [generating, setGenerating] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [formBio, setFormBio] = useState("");
  const [formSections, setFormSections] = useState<Array<{ title: string; content: string }>>([]);
  const [saving, setSaving] = useState(false);

  const fetchData = useCallback(async () => {
    try {
      const [overridesRes, usPoliticiansRes, ukPoliticiansRes] = await Promise.all([
        fetch("/api/politician-overrides"),
        fetch("/api/country/us/politicians"),
        fetch("/api/country/uk/politicians"),
      ]);
      if (!overridesRes.ok) throw new Error("Failed to load overrides");
      const overridesData = await overridesRes.json();
      const usPoliticians = usPoliticiansRes.ok
        ? ((await usPoliticiansRes.json()).politicians ?? [])
        : [];
      const ukPoliticians = ukPoliticiansRes.ok
        ? ((await ukPoliticiansRes.json()).politicians ?? [])
        : [];
      const allPoliticians = [...usPoliticians, ...ukPoliticians];
      setOverrides(overridesData);
      setPoliticians(
        allPoliticians
          .filter((p: { isNPP?: boolean }) => !p.isNPP)
          .map((p: { id: string; sequentialId?: number; name: string }) => ({
            id: p.id,
            sequentialId: p.sequentialId,
            name: p.name,
          }))
      );
      setError("");
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to load");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const startEdit = (override: PoliticianOverrideItem) => {
    setEditingId(override.politicianId);
    setFormBio(override.customBio ?? "");
    setFormSections(override.customSections ?? []);
  };

  const startCreate = (politicianId: string) => {
    setEditingId(politicianId);
    setFormBio("");
    setFormSections([]);
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!editingId) return;
    setSaving(true);
    try {
      const res = await fetch(`/api/politician-overrides/${encodeURIComponent(editingId)}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          customBio: formBio.trim() || undefined,
          customSections:
            formSections.filter((s) => s.title.trim()).length > 0 ? formSections : undefined,
        }),
      });
      if (!res.ok) throw new Error("Failed to save");
      await fetchData();
      setEditingId(null);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to save");
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async (politicianId: string) => {
    if (!confirm("Remove all customizations for this politician?")) return;
    try {
      const res = await fetch(`/api/politician-overrides/${encodeURIComponent(politicianId)}`, {
        method: "DELETE",
      });
      if (!res.ok) throw new Error("Failed to delete");
      await fetchData();
      if (editingId === politicianId) setEditingId(null);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to delete");
    }
  };

  const addSection = () => {
    setFormSections([...formSections, { title: "", content: "" }]);
  };

  const updateSection = (i: number, field: "title" | "content", value: string) => {
    const next = [...formSections];
    next[i] = { ...next[i], [field]: value };
    setFormSections(next);
  };

  const removeSection = (i: number) => {
    setFormSections(formSections.filter((_, j) => j !== i));
  };

  const handleGenerate = async () => {
    setGenerating(true);
    setError("");
    try {
      const res = await fetch("/api/admin/politician-pages/backfill", { method: "POST" });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed to generate");
      await fetchData();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to generate");
    } finally {
      setGenerating(false);
    }
  };

  const overrideMap = new Map(overrides.map((o) => [o.politicianId, o]));

  return (
    <div className="space-y-8">
      <div className="flex items-start justify-between gap-4">
        <div>
          <p className="text-sm text-muted">
            Manage Wikipedia-style pages for player characters only (NPPs use
            /politicians/npp/[id]). Generate to backfill bios, election history, and leadership
            flags.
          </p>
        </div>
        <button
          type="button"
          onClick={handleGenerate}
          disabled={generating}
          className="shrink-0 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
        >
          {generating ? "Generating…" : "Generate All Pages"}
        </button>
      </div>

      {error && (
        <div className="rounded-lg border border-red-500/30 bg-red-500/10 px-4 py-3 text-red-400">
          {error}
        </div>
      )}

      {editingId && (
        <form
          onSubmit={handleSave}
          className="rounded-xl border border-card-border bg-card p-6 space-y-4"
        >
          <h3 className="font-semibold">
            Customize: {politicians.find((p) => p.id === editingId)?.name ?? editingId}
          </h3>
          <div>
            <label className="mb-1 block text-sm font-medium">Custom Bio (overrides default)</label>
            <textarea
              value={formBio}
              onChange={(e) => setFormBio(e.target.value)}
              rows={4}
              className="w-full rounded-lg border border-card-border bg-background px-3 py-2 text-sm"
              placeholder="Leave empty to use default bio"
            />
          </div>
          <div>
            <div className="mb-2 flex items-center justify-between">
              <label className="text-sm font-medium">Custom Sections</label>
              <button
                type="button"
                onClick={addSection}
                className="text-sm text-primary hover:underline"
              >
                + Add section
              </button>
            </div>
            {formSections.map((s, i) => (
              <div key={i} className="mb-3 rounded-lg border border-card-border p-3">
                <input
                  type="text"
                  value={s.title}
                  onChange={(e) => updateSection(i, "title", e.target.value)}
                  placeholder="Section title"
                  className="mb-2 w-full rounded border border-card-border bg-background px-2 py-1 text-sm"
                />
                <textarea
                  value={s.content}
                  onChange={(e) => updateSection(i, "content", e.target.value)}
                  placeholder="Section content"
                  rows={2}
                  className="mb-2 w-full rounded border border-card-border bg-background px-2 py-1 text-sm"
                />
                <button
                  type="button"
                  onClick={() => removeSection(i)}
                  className="text-xs text-red-400 hover:underline"
                >
                  Remove
                </button>
              </div>
            ))}
          </div>
          <div className="flex gap-2">
            <button
              type="submit"
              disabled={saving}
              className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
            >
              {saving ? "Saving…" : "Save"}
            </button>
            <button
              type="button"
              onClick={() => setEditingId(null)}
              className="rounded-lg border border-card-border px-4 py-2 text-sm hover:bg-card"
            >
              Cancel
            </button>
          </div>
        </form>
      )}

      <div className="rounded-xl border border-card-border bg-card overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-card-elevated">
              <tr>
                <th className="px-4 py-3 text-left font-medium">Politician</th>
                <th className="px-4 py-3 text-left font-medium">Generated</th>
                <th className="px-4 py-3 text-left font-medium">Leadership</th>
                <th className="px-4 py-3 text-left font-medium">Customized</th>
                <th className="px-4 py-3 text-right font-medium">Actions</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr>
                  <td colSpan={5} className="px-4 py-8 text-center text-muted">
                    Loading…
                  </td>
                </tr>
              ) : (
                politicians.slice(0, 50).map((p) => {
                  const ov = overrideMap.get(p.id);
                  return (
                    <tr key={p.id} className="border-t border-card-border">
                      <td className="px-4 py-3">
                        <Link
                          href={`/character/${p.sequentialId ?? p.id}`}
                          target="_blank"
                          className="text-primary hover:underline"
                        >
                          {p.name}
                        </Link>
                      </td>
                      <td className="px-4 py-3 text-muted">
                        {ov?.autoGeneratedBio || (ov?.electionHistory?.length ?? 0) > 0
                          ? "Yes"
                          : "—"}
                      </td>
                      <td className="px-4 py-3 text-muted">
                        {ov?.hasHeldCongressLeadership ? "Yes" : "—"}
                      </td>
                      <td className="px-4 py-3 text-muted">
                        {ov?.customBio || (ov?.customSections?.length ?? 0) > 0 ? "Yes" : "—"}
                      </td>
                      <td className="px-4 py-3 text-right">
                        <button
                          type="button"
                          onClick={() => (ov ? startEdit(ov) : startCreate(p.id))}
                          className="text-primary hover:underline mr-2"
                        >
                          {ov ? "Edit" : "Customize"}
                        </button>
                        {ov && (
                          <button
                            type="button"
                            onClick={() => handleDelete(p.id)}
                            className="text-red-400 hover:underline"
                          >
                            Reset
                          </button>
                        )}
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
        {!loading && politicians.length > 50 && (
          <p className="px-4 py-2 text-xs text-muted">
            Showing first 50. Use search to find others.
          </p>
        )}
      </div>
    </div>
  );
}
