/**
 * SEED INDEPENDENCE - DO NOT DERIVE FROM ANOTHER ERA.
 * Each era seed is self-contained. This file MUST NOT import and transform
 * another era's seed data (e.g. the 2019 `states` array). All values are
 * authored for 2027 directly. Changing the 2019 (or any other) seed must never
 * alter 2027. Same-era imports (states2027 for region IDs) and type-only
 * imports are allowed.
 */
import type { State } from "@/lib/db/types";

/**
 * US state seed for the 2027-default preset (January 2027 snapshot). Population
 * uses Census Vintage 2025 estimates (July 1, 2025), the latest completed
 * annual state estimates available during authoring. GDP uses BEA SAGDP2 2025
 * current-dollar all-industry totals (millions USD), rounded to the nearest
 * $100 million. Congressional districts retain the 2020 Census apportionment.
 *
 * Sources:
 * https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/state/totals/NST-EST2025-ALLDATA.csv
 * https://apps.bea.gov/regional/zip/SAGDP.zip
 */
export const states2027: State[] = [
  // Northeast
  {
    _id: "CT",
    countryId: "US",
    name: "Connecticut",
    population: 3688496,
    gdp: 376500,
    houseDistricts: 5,
    stateSenateSeats: 36,
    region: "Northeast",
  },
  {
    _id: "DE",
    countryId: "US",
    name: "Delaware",
    population: 1059952,
    gdp: 117200,
    houseDistricts: 1,
    stateSenateSeats: 21,
    region: "Northeast",
  },
  {
    _id: "MA",
    countryId: "US",
    name: "Massachusetts",
    population: 7154084,
    gdp: 820100,
    houseDistricts: 9,
    stateSenateSeats: 40,
    region: "Northeast",
  },
  {
    _id: "MD",
    countryId: "US",
    name: "Maryland",
    population: 6265347,
    gdp: 568100,
    houseDistricts: 8,
    stateSenateSeats: 47,
    region: "Northeast",
  },
  {
    _id: "ME",
    countryId: "US",
    name: "Maine",
    population: 1414874,
    gdp: 102800,
    houseDistricts: 2,
    stateSenateSeats: 35,
    region: "Northeast",
  },
  {
    _id: "NH",
    countryId: "US",
    name: "New Hampshire",
    population: 1415342,
    gdp: 125500,
    houseDistricts: 2,
    stateSenateSeats: 24,
    region: "Northeast",
  },
  {
    _id: "NJ",
    countryId: "US",
    name: "New Jersey",
    population: 9548215,
    gdp: 887200,
    houseDistricts: 12,
    stateSenateSeats: 40,
    region: "Northeast",
  },
  {
    _id: "NY",
    countryId: "US",
    name: "New York",
    population: 20002427,
    gdp: 2467700,
    houseDistricts: 26,
    stateSenateSeats: 63,
    region: "Northeast",
  },
  {
    _id: "PA",
    countryId: "US",
    name: "Pennsylvania",
    population: 13059432,
    gdp: 1056400,
    houseDistricts: 17,
    stateSenateSeats: 50,
    region: "Northeast",
  },
  {
    _id: "RI",
    countryId: "US",
    name: "Rhode Island",
    population: 1114521,
    gdp: 84000,
    houseDistricts: 2,
    stateSenateSeats: 38,
    region: "Northeast",
  },
  {
    _id: "VT",
    countryId: "US",
    name: "Vermont",
    population: 644663,
    gdp: 48400,
    houseDistricts: 1,
    stateSenateSeats: 30,
    region: "Northeast",
  },

  // Southeast
  {
    _id: "AL",
    countryId: "US",
    name: "Alabama",
    population: 5193088,
    gdp: 341200,
    houseDistricts: 7,
    stateSenateSeats: 35,
    region: "Southeast",
  },
  {
    _id: "AR",
    countryId: "US",
    name: "Arkansas",
    population: 3114791,
    gdp: 198400,
    houseDistricts: 4,
    stateSenateSeats: 35,
    region: "Southeast",
  },
  {
    _id: "FL",
    countryId: "US",
    name: "Florida",
    population: 23462518,
    gdp: 1834600,
    houseDistricts: 28,
    stateSenateSeats: 40,
    region: "Southeast",
  },
  {
    _id: "GA",
    countryId: "US",
    name: "Georgia",
    population: 11302748,
    gdp: 924800,
    houseDistricts: 14,
    stateSenateSeats: 56,
    region: "Southeast",
  },
  {
    _id: "KY",
    countryId: "US",
    name: "Kentucky",
    population: 4606864,
    gdp: 306900,
    houseDistricts: 6,
    stateSenateSeats: 38,
    region: "Southeast",
  },
  {
    _id: "LA",
    countryId: "US",
    name: "Louisiana",
    population: 4618189,
    gdp: 340100,
    houseDistricts: 6,
    stateSenateSeats: 39,
    region: "Southeast",
  },
  {
    _id: "MS",
    countryId: "US",
    name: "Mississippi",
    population: 2954160,
    gdp: 165100,
    houseDistricts: 4,
    stateSenateSeats: 52,
    region: "Southeast",
  },
  {
    _id: "NC",
    countryId: "US",
    name: "North Carolina",
    population: 11197968,
    gdp: 893800,
    houseDistricts: 14,
    stateSenateSeats: 50,
    region: "Southeast",
  },
  {
    _id: "SC",
    countryId: "US",
    name: "South Carolina",
    population: 5570274,
    gdp: 378800,
    houseDistricts: 7,
    stateSenateSeats: 46,
    region: "Southeast",
  },
  {
    _id: "TN",
    countryId: "US",
    name: "Tennessee",
    population: 7315076,
    gdp: 589800,
    houseDistricts: 9,
    stateSenateSeats: 33,
    region: "Southeast",
  },
  {
    _id: "VA",
    countryId: "US",
    name: "Virginia",
    population: 8880107,
    gdp: 798400,
    houseDistricts: 11,
    stateSenateSeats: 40,
    region: "Southeast",
  },
  {
    _id: "WV",
    countryId: "US",
    name: "West Virginia",
    population: 1766147,
    gdp: 109300,
    houseDistricts: 2,
    stateSenateSeats: 34,
    region: "Southeast",
  },

  // Midwest
  {
    _id: "IA",
    countryId: "US",
    name: "Iowa",
    population: 3238387,
    gdp: 277100,
    houseDistricts: 4,
    stateSenateSeats: 50,
    region: "Midwest",
  },
  {
    _id: "IL",
    countryId: "US",
    name: "Illinois",
    population: 12719141,
    gdp: 1202000,
    houseDistricts: 17,
    stateSenateSeats: 59,
    region: "Midwest",
  },
  {
    _id: "IN",
    countryId: "US",
    name: "Indiana",
    population: 6973333,
    gdp: 545200,
    houseDistricts: 9,
    stateSenateSeats: 50,
    region: "Midwest",
  },
  {
    _id: "KS",
    countryId: "US",
    name: "Kansas",
    population: 2977220,
    gdp: 241400,
    houseDistricts: 4,
    stateSenateSeats: 40,
    region: "Midwest",
  },
  {
    _id: "MI",
    countryId: "US",
    name: "Michigan",
    population: 10127884,
    gdp: 730100,
    houseDistricts: 13,
    stateSenateSeats: 38,
    region: "Midwest",
  },
  {
    _id: "MN",
    countryId: "US",
    name: "Minnesota",
    population: 5830405,
    gdp: 531500,
    houseDistricts: 8,
    stateSenateSeats: 67,
    region: "Midwest",
  },
  {
    _id: "MO",
    countryId: "US",
    name: "Missouri",
    population: 6270541,
    gdp: 468500,
    houseDistricts: 8,
    stateSenateSeats: 34,
    region: "Midwest",
  },
  {
    _id: "ND",
    countryId: "US",
    name: "North Dakota",
    population: 799358,
    gdp: 81900,
    houseDistricts: 1,
    stateSenateSeats: 47,
    region: "Midwest",
  },
  {
    _id: "NE",
    countryId: "US",
    name: "Nebraska",
    population: 2018006,
    gdp: 198100,
    houseDistricts: 3,
    stateSenateSeats: 49,
    region: "Midwest",
  },
  {
    _id: "OH",
    countryId: "US",
    name: "Ohio",
    population: 11900510,
    gdp: 966800,
    houseDistricts: 15,
    stateSenateSeats: 33,
    region: "Midwest",
  },
  {
    _id: "SD",
    countryId: "US",
    name: "South Dakota",
    population: 935094,
    gdp: 80700,
    houseDistricts: 1,
    stateSenateSeats: 35,
    region: "Midwest",
  },
  {
    _id: "WI",
    countryId: "US",
    name: "Wisconsin",
    population: 5972787,
    gdp: 473000,
    houseDistricts: 8,
    stateSenateSeats: 33,
    region: "Midwest",
  },

  // Southwest
  {
    _id: "AZ",
    countryId: "US",
    name: "Arizona",
    population: 7623818,
    gdp: 598200,
    houseDistricts: 9,
    stateSenateSeats: 30,
    region: "Southwest",
  },
  {
    _id: "NM",
    countryId: "US",
    name: "New Mexico",
    population: 2125498,
    gdp: 152800,
    houseDistricts: 3,
    stateSenateSeats: 42,
    region: "Southwest",
  },
  {
    _id: "NV",
    countryId: "US",
    name: "Nevada",
    population: 3282188,
    gdp: 281500,
    houseDistricts: 4,
    stateSenateSeats: 21,
    region: "Southwest",
  },
  {
    _id: "OK",
    countryId: "US",
    name: "Oklahoma",
    population: 4123288,
    gdp: 274400,
    houseDistricts: 5,
    stateSenateSeats: 48,
    region: "Southwest",
  },
  {
    _id: "TX",
    countryId: "US",
    name: "Texas",
    population: 31709821,
    gdp: 2904400,
    houseDistricts: 38,
    stateSenateSeats: 31,
    region: "Southwest",
  },
  {
    _id: "UT",
    countryId: "US",
    name: "Utah",
    population: 3538904,
    gdp: 316000,
    houseDistricts: 4,
    stateSenateSeats: 29,
    region: "Southwest",
  },

  // West
  {
    _id: "AK",
    countryId: "US",
    name: "Alaska",
    population: 737270,
    gdp: 75000,
    houseDistricts: 1,
    stateSenateSeats: 20,
    region: "West",
  },
  {
    _id: "CA",
    countryId: "US",
    name: "California",
    population: 39355309,
    gdp: 4250800,
    houseDistricts: 52,
    stateSenateSeats: 40,
    region: "West",
  },
  {
    _id: "CO",
    countryId: "US",
    name: "Colorado",
    population: 6012561,
    gdp: 584300,
    houseDistricts: 8,
    stateSenateSeats: 35,
    region: "West",
  },
  {
    _id: "HI",
    countryId: "US",
    name: "Hawaii",
    population: 1432820,
    gdp: 124600,
    houseDistricts: 2,
    stateSenateSeats: 25,
    region: "West",
  },
  {
    _id: "ID",
    countryId: "US",
    name: "Idaho",
    population: 2029733,
    gdp: 135600,
    houseDistricts: 2,
    stateSenateSeats: 35,
    region: "West",
  },
  {
    _id: "MT",
    countryId: "US",
    name: "Montana",
    population: 1144694,
    gdp: 82400,
    houseDistricts: 2,
    stateSenateSeats: 50,
    region: "West",
  },
  {
    _id: "OR",
    countryId: "US",
    name: "Oregon",
    population: 4273586,
    gdp: 342900,
    houseDistricts: 6,
    stateSenateSeats: 30,
    region: "West",
  },
  {
    _id: "WA",
    countryId: "US",
    name: "Washington",
    population: 8001020,
    gdp: 895000,
    houseDistricts: 10,
    stateSenateSeats: 49,
    region: "West",
  },
  {
    _id: "WY",
    countryId: "US",
    name: "Wyoming",
    population: 588753,
    gdp: 52600,
    houseDistricts: 1,
    stateSenateSeats: 30,
    region: "West",
  },
  // ─── Federal District ────────────────────────────────────────────────────
  // The District of Columbia is not a state but holds 3 electoral votes per
  // the 23rd Amendment and votes in presidential elections. It has 0 House
  // districts (Eleanor Holmes Norton is a non-voting delegate) and 0 state
  // senate seats (the DC Council is a 13-seat unicameral body - modeled
  // here as `stateSenateSeats: 0` so cross-state seat tallies stay honest).
  {
    _id: "DC",
    countryId: "US",
    name: "District of Columbia",
    population: 693645,
    gdp: 192600,
    houseDistricts: 0,
    stateSenateSeats: 0,
    region: "Northeast",
  },
];

export default states2027;
