/**
 * SEED INDEPENDENCE — DO NOT DERIVE FROM ANOTHER ERA.
 * Each era seed is self-contained. This file MUST NOT import and transform
 * another era's seed data. All values are authored for 1979 directly.
 * Type-only imports are allowed.
 *
 * US state seed for the 1979-default preset (Carter / 96th Congress snapshot —
 * stagflation, energy crisis, the New Deal coalition fraying on the eve of the
 * 1980 Reagan realignment). population = 1980 Census (April 1, 1980); gdp = BEA
 * 1979 nominal Gross State Product (millions USD).
 *
 * houseDistricts = **1970-Census apportionment** — the map used for the 93rd–97th
 * Congresses (1973–1983). This is one cycle EARLIER than states1991's 1990 map:
 * the 1980 Census did not reapportion the House until the 1983 (98th) Congress,
 * so a 1979/1980 world runs on the 1970 seat allocation (CA 43, NY 39, PA 25 —
 * pre-Sun-Belt shift). They sum to 435 across the 50 states; DC = 0.
 * stateSenateSeats/region are era-invariant.
 * National anchors: US 1980 pop ≈ 226.5M; nominal GDP 1979 ≈ $2.63T.
 */
import type { State } from "@/lib/db/types";

export const states1979: State[] = [
  // Northeast
  {
    _id: "CT",
    countryId: "US",
    name: "Connecticut",
    population: 3107576,
    gdp: 42000,
    houseDistricts: 6,
    stateSenateSeats: 36,
    region: "Northeast",
  },
  {
    _id: "DE",
    countryId: "US",
    name: "Delaware",
    population: 594338,
    gdp: 8000,
    houseDistricts: 1,
    stateSenateSeats: 21,
    region: "Northeast",
  },
  {
    _id: "MA",
    countryId: "US",
    name: "Massachusetts",
    population: 5737037,
    gdp: 68000,
    houseDistricts: 12,
    stateSenateSeats: 40,
    region: "Northeast",
  },
  {
    _id: "MD",
    countryId: "US",
    name: "Maryland",
    population: 4216975,
    gdp: 48000,
    houseDistricts: 8,
    stateSenateSeats: 47,
    region: "Northeast",
  },
  {
    _id: "ME",
    countryId: "US",
    name: "Maine",
    population: 1124660,
    gdp: 10000,
    houseDistricts: 2,
    stateSenateSeats: 35,
    region: "Northeast",
  },
  {
    _id: "NH",
    countryId: "US",
    name: "New Hampshire",
    population: 920610,
    gdp: 9000,
    houseDistricts: 2,
    stateSenateSeats: 24,
    region: "Northeast",
  },
  {
    _id: "NJ",
    countryId: "US",
    name: "New Jersey",
    population: 7364823,
    gdp: 90000,
    houseDistricts: 15,
    stateSenateSeats: 40,
    region: "Northeast",
  },
  {
    _id: "NY",
    countryId: "US",
    name: "New York",
    population: 17558072,
    gdp: 215000,
    houseDistricts: 39,
    stateSenateSeats: 61,
    region: "Northeast",
  },
  {
    _id: "PA",
    countryId: "US",
    name: "Pennsylvania",
    population: 11863895,
    gdp: 125000,
    houseDistricts: 25,
    stateSenateSeats: 50,
    region: "Northeast",
  },
  {
    _id: "RI",
    countryId: "US",
    name: "Rhode Island",
    population: 947154,
    gdp: 9000,
    houseDistricts: 2,
    stateSenateSeats: 38,
    region: "Northeast",
  },
  {
    _id: "VT",
    countryId: "US",
    name: "Vermont",
    population: 511456,
    gdp: 4500,
    houseDistricts: 1,
    stateSenateSeats: 30,
    region: "Northeast",
  },

  // Southeast
  {
    _id: "AL",
    countryId: "US",
    name: "Alabama",
    population: 3893888,
    gdp: 34000,
    houseDistricts: 7,
    stateSenateSeats: 35,
    region: "Southeast",
  },
  {
    _id: "AR",
    countryId: "US",
    name: "Arkansas",
    population: 2286435,
    gdp: 19000,
    houseDistricts: 4,
    stateSenateSeats: 35,
    region: "Southeast",
  },
  {
    _id: "FL",
    countryId: "US",
    name: "Florida",
    population: 9746324,
    gdp: 95000,
    houseDistricts: 15,
    stateSenateSeats: 40,
    region: "Southeast",
  },
  {
    _id: "GA",
    countryId: "US",
    name: "Georgia",
    population: 5463105,
    gdp: 55000,
    houseDistricts: 10,
    stateSenateSeats: 56,
    region: "Southeast",
  },
  {
    _id: "KY",
    countryId: "US",
    name: "Kentucky",
    population: 3660777,
    gdp: 34000,
    houseDistricts: 7,
    stateSenateSeats: 38,
    region: "Southeast",
  },
  {
    _id: "LA",
    countryId: "US",
    name: "Louisiana",
    population: 4205900,
    gdp: 48000,
    houseDistricts: 8,
    stateSenateSeats: 39,
    region: "Southeast",
  },
  {
    _id: "MS",
    countryId: "US",
    name: "Mississippi",
    population: 2520638,
    gdp: 20000,
    houseDistricts: 5,
    stateSenateSeats: 52,
    region: "Southeast",
  },
  {
    _id: "NC",
    countryId: "US",
    name: "North Carolina",
    population: 5881766,
    gdp: 55000,
    houseDistricts: 11,
    stateSenateSeats: 50,
    region: "Southeast",
  },
  {
    _id: "SC",
    countryId: "US",
    name: "South Carolina",
    population: 3121820,
    gdp: 27000,
    houseDistricts: 6,
    stateSenateSeats: 46,
    region: "Southeast",
  },
  {
    _id: "TN",
    countryId: "US",
    name: "Tennessee",
    population: 4591120,
    gdp: 42000,
    houseDistricts: 8,
    stateSenateSeats: 33,
    region: "Southeast",
  },
  {
    _id: "VA",
    countryId: "US",
    name: "Virginia",
    population: 5346818,
    gdp: 55000,
    houseDistricts: 10,
    stateSenateSeats: 40,
    region: "Southeast",
  },
  {
    _id: "WV",
    countryId: "US",
    name: "West Virginia",
    population: 1949644,
    gdp: 18000,
    houseDistricts: 4,
    stateSenateSeats: 34,
    region: "Southeast",
  },

  // Midwest
  {
    _id: "IA",
    countryId: "US",
    name: "Iowa",
    population: 2913808,
    gdp: 33000,
    houseDistricts: 6,
    stateSenateSeats: 50,
    region: "Midwest",
  },
  {
    _id: "IL",
    countryId: "US",
    name: "Illinois",
    population: 11426518,
    gdp: 135000,
    houseDistricts: 24,
    stateSenateSeats: 59,
    region: "Midwest",
  },
  {
    _id: "IN",
    countryId: "US",
    name: "Indiana",
    population: 5490224,
    gdp: 60000,
    houseDistricts: 11,
    stateSenateSeats: 50,
    region: "Midwest",
  },
  {
    _id: "KS",
    countryId: "US",
    name: "Kansas",
    population: 2363679,
    gdp: 27000,
    houseDistricts: 5,
    stateSenateSeats: 40,
    region: "Midwest",
  },
  {
    _id: "MI",
    countryId: "US",
    name: "Michigan",
    population: 9262078,
    gdp: 105000,
    houseDistricts: 19,
    stateSenateSeats: 38,
    region: "Midwest",
  },
  {
    _id: "MN",
    countryId: "US",
    name: "Minnesota",
    population: 4075970,
    gdp: 45000,
    houseDistricts: 8,
    stateSenateSeats: 67,
    region: "Midwest",
  },
  {
    _id: "MO",
    countryId: "US",
    name: "Missouri",
    population: 4916686,
    gdp: 52000,
    houseDistricts: 10,
    stateSenateSeats: 34,
    region: "Midwest",
  },
  {
    _id: "ND",
    countryId: "US",
    name: "North Dakota",
    population: 652717,
    gdp: 8000,
    houseDistricts: 1,
    stateSenateSeats: 47,
    region: "Midwest",
  },
  {
    _id: "NE",
    countryId: "US",
    name: "Nebraska",
    population: 1569825,
    gdp: 18000,
    houseDistricts: 3,
    stateSenateSeats: 49,
    region: "Midwest",
  },
  {
    _id: "OH",
    countryId: "US",
    name: "Ohio",
    population: 10797630,
    gdp: 120000,
    houseDistricts: 23,
    stateSenateSeats: 33,
    region: "Midwest",
  },
  {
    _id: "SD",
    countryId: "US",
    name: "South Dakota",
    population: 690768,
    gdp: 7000,
    houseDistricts: 2,
    stateSenateSeats: 35,
    region: "Midwest",
  },
  {
    _id: "WI",
    countryId: "US",
    name: "Wisconsin",
    population: 4705767,
    gdp: 50000,
    houseDistricts: 9,
    stateSenateSeats: 33,
    region: "Midwest",
  },

  // Southwest
  {
    _id: "AZ",
    countryId: "US",
    name: "Arizona",
    population: 2718215,
    gdp: 28000,
    houseDistricts: 4,
    stateSenateSeats: 30,
    region: "Southwest",
  },
  {
    _id: "NM",
    countryId: "US",
    name: "New Mexico",
    population: 1302894,
    gdp: 13000,
    houseDistricts: 2,
    stateSenateSeats: 42,
    region: "Southwest",
  },
  {
    _id: "NV",
    countryId: "US",
    name: "Nevada",
    population: 800493,
    gdp: 10000,
    houseDistricts: 1,
    stateSenateSeats: 21,
    region: "Southwest",
  },
  {
    _id: "OK",
    countryId: "US",
    name: "Oklahoma",
    population: 3025290,
    gdp: 33000,
    houseDistricts: 6,
    stateSenateSeats: 48,
    region: "Southwest",
  },
  {
    _id: "TX",
    countryId: "US",
    name: "Texas",
    population: 14229191,
    gdp: 170000,
    houseDistricts: 24,
    stateSenateSeats: 31,
    region: "Southwest",
  },
  {
    _id: "UT",
    countryId: "US",
    name: "Utah",
    population: 1461037,
    gdp: 14000,
    houseDistricts: 2,
    stateSenateSeats: 29,
    region: "Southwest",
  },

  // West
  {
    _id: "AK",
    countryId: "US",
    name: "Alaska",
    population: 401851,
    gdp: 12000,
    houseDistricts: 1,
    stateSenateSeats: 20,
    region: "West",
  },
  {
    _id: "CA",
    countryId: "US",
    name: "California",
    population: 23667902,
    gdp: 285000,
    houseDistricts: 43,
    stateSenateSeats: 40,
    region: "West",
  },
  {
    _id: "CO",
    countryId: "US",
    name: "Colorado",
    population: 2889964,
    gdp: 34000,
    houseDistricts: 5,
    stateSenateSeats: 35,
    region: "West",
  },
  {
    _id: "HI",
    countryId: "US",
    name: "Hawaii",
    population: 964691,
    gdp: 11000,
    houseDistricts: 2,
    stateSenateSeats: 25,
    region: "West",
  },
  {
    _id: "ID",
    countryId: "US",
    name: "Idaho",
    population: 943935,
    gdp: 9000,
    houseDistricts: 2,
    stateSenateSeats: 35,
    region: "West",
  },
  {
    _id: "MT",
    countryId: "US",
    name: "Montana",
    population: 786690,
    gdp: 8000,
    houseDistricts: 2,
    stateSenateSeats: 50,
    region: "West",
  },
  {
    _id: "OR",
    countryId: "US",
    name: "Oregon",
    population: 2633105,
    gdp: 30000,
    houseDistricts: 4,
    stateSenateSeats: 30,
    region: "West",
  },
  {
    _id: "WA",
    countryId: "US",
    name: "Washington",
    population: 4132156,
    gdp: 48000,
    houseDistricts: 7,
    stateSenateSeats: 49,
    region: "West",
  },
  {
    _id: "WY",
    countryId: "US",
    name: "Wyoming",
    population: 469557,
    gdp: 7000,
    houseDistricts: 1,
    stateSenateSeats: 30,
    region: "West",
  },

  // Federal District — 0 House districts (non-voting delegate), 0 state senate seats.
  {
    _id: "DC",
    countryId: "US",
    name: "District of Columbia",
    population: 638333,
    gdp: 13000,
    houseDistricts: 0,
    stateSenateSeats: 0,
    region: "Northeast",
  },
];

export default states1979;
