/**
 * SEED INDEPENDENCE — DO NOT DERIVE FROM ANOTHER ERA.
 * Each era seed is self-contained. This file MUST NOT import and transform
 * another era's seed data. All values are authored for 1999 directly.
 * Type-only imports are allowed.
 *
 * US state seed for the 1999-default preset (late-1999 / 106th Congress snapshot,
 * Clinton 2nd term, dot-com boom, budget surplus). population = Census July-1999
 * estimates; gdp = BEA 1999 nominal state GDP (millions USD). houseDistricts =
 * **1990 apportionment** (the 103rd–107th Congresses, 1993–2003) and sum to 435
 * across the 50 states; DC = 0. stateSenateSeats/region are era-invariant.
 * National anchors: US 1999 pop ≈ 279.0M; nominal GDP ≈ $9.66T.
 */
import type { State } from "@/lib/db/types";

export const states1999: State[] = [
  // Northeast
  {
    _id: "CT",
    countryId: "US",
    name: "Connecticut",
    population: 3282031,
    gdp: 150000,
    houseDistricts: 6,
    stateSenateSeats: 36,
    region: "Northeast",
  },
  {
    _id: "DE",
    countryId: "US",
    name: "Delaware",
    population: 753538,
    gdp: 37000,
    houseDistricts: 1,
    stateSenateSeats: 21,
    region: "Northeast",
  },
  {
    _id: "MA",
    countryId: "US",
    name: "Massachusetts",
    population: 6175169,
    gdp: 270000,
    houseDistricts: 10,
    stateSenateSeats: 40,
    region: "Northeast",
  },
  {
    _id: "MD",
    countryId: "US",
    name: "Maryland",
    population: 5171634,
    gdp: 180000,
    houseDistricts: 8,
    stateSenateSeats: 47,
    region: "Northeast",
  },
  {
    _id: "ME",
    countryId: "US",
    name: "Maine",
    population: 1253040,
    gdp: 33000,
    houseDistricts: 2,
    stateSenateSeats: 35,
    region: "Northeast",
  },
  {
    _id: "NH",
    countryId: "US",
    name: "New Hampshire",
    population: 1201134,
    gdp: 42000,
    houseDistricts: 2,
    stateSenateSeats: 24,
    region: "Northeast",
  },
  {
    _id: "NJ",
    countryId: "US",
    name: "New Jersey",
    population: 8143412,
    gdp: 330000,
    houseDistricts: 13,
    stateSenateSeats: 40,
    region: "Northeast",
  },
  {
    _id: "NY",
    countryId: "US",
    name: "New York",
    population: 18196601,
    gdp: 770000,
    houseDistricts: 31,
    stateSenateSeats: 61,
    region: "Northeast",
  },
  {
    _id: "PA",
    countryId: "US",
    name: "Pennsylvania",
    population: 12009361,
    gdp: 390000,
    houseDistricts: 21,
    stateSenateSeats: 50,
    region: "Northeast",
  },
  {
    _id: "RI",
    countryId: "US",
    name: "Rhode Island",
    population: 1048319,
    gdp: 33000,
    houseDistricts: 2,
    stateSenateSeats: 38,
    region: "Northeast",
  },
  {
    _id: "VT",
    countryId: "US",
    name: "Vermont",
    population: 593740,
    gdp: 17000,
    houseDistricts: 1,
    stateSenateSeats: 30,
    region: "Northeast",
  },

  // Southeast
  {
    _id: "AL",
    countryId: "US",
    name: "Alabama",
    population: 4369862,
    gdp: 110000,
    houseDistricts: 7,
    stateSenateSeats: 35,
    region: "Southeast",
  },
  {
    _id: "AR",
    countryId: "US",
    name: "Arkansas",
    population: 2551373,
    gdp: 62000,
    houseDistricts: 4,
    stateSenateSeats: 35,
    region: "Southeast",
  },
  {
    _id: "FL",
    countryId: "US",
    name: "Florida",
    population: 15322040,
    gdp: 470000,
    houseDistricts: 23,
    stateSenateSeats: 40,
    region: "Southeast",
  },
  {
    _id: "GA",
    countryId: "US",
    name: "Georgia",
    population: 7788240,
    gdp: 280000,
    houseDistricts: 11,
    stateSenateSeats: 56,
    region: "Southeast",
  },
  {
    _id: "KY",
    countryId: "US",
    name: "Kentucky",
    population: 3960825,
    gdp: 110000,
    houseDistricts: 6,
    stateSenateSeats: 38,
    region: "Southeast",
  },
  {
    _id: "LA",
    countryId: "US",
    name: "Louisiana",
    population: 4372035,
    gdp: 130000,
    houseDistricts: 7,
    stateSenateSeats: 39,
    region: "Southeast",
  },
  {
    _id: "MS",
    countryId: "US",
    name: "Mississippi",
    population: 2768619,
    gdp: 62000,
    houseDistricts: 5,
    stateSenateSeats: 52,
    region: "Southeast",
  },
  {
    _id: "NC",
    countryId: "US",
    name: "North Carolina",
    population: 7650789,
    gdp: 270000,
    houseDistricts: 12,
    stateSenateSeats: 50,
    region: "Southeast",
  },
  {
    _id: "SC",
    countryId: "US",
    name: "South Carolina",
    population: 3885736,
    gdp: 100000,
    houseDistricts: 6,
    stateSenateSeats: 46,
    region: "Southeast",
  },
  {
    _id: "TN",
    countryId: "US",
    name: "Tennessee",
    population: 5483535,
    gdp: 170000,
    houseDistricts: 9,
    stateSenateSeats: 33,
    region: "Southeast",
  },
  {
    _id: "VA",
    countryId: "US",
    name: "Virginia",
    population: 6872912,
    gdp: 250000,
    houseDistricts: 11,
    stateSenateSeats: 40,
    region: "Southeast",
  },
  {
    _id: "WV",
    countryId: "US",
    name: "West Virginia",
    population: 1806928,
    gdp: 40000,
    houseDistricts: 3,
    stateSenateSeats: 34,
    region: "Southeast",
  },

  // Midwest
  {
    _id: "IA",
    countryId: "US",
    name: "Iowa",
    population: 2869413,
    gdp: 85000,
    houseDistricts: 5,
    stateSenateSeats: 50,
    region: "Midwest",
  },
  {
    _id: "IL",
    countryId: "US",
    name: "Illinois",
    population: 12226498,
    gdp: 440000,
    houseDistricts: 20,
    stateSenateSeats: 59,
    region: "Midwest",
  },
  {
    _id: "IN",
    countryId: "US",
    name: "Indiana",
    population: 6004304,
    gdp: 180000,
    houseDistricts: 10,
    stateSenateSeats: 50,
    region: "Midwest",
  },
  {
    _id: "KS",
    countryId: "US",
    name: "Kansas",
    population: 2654052,
    gdp: 80000,
    houseDistricts: 4,
    stateSenateSeats: 40,
    region: "Midwest",
  },
  {
    _id: "MI",
    countryId: "US",
    name: "Michigan",
    population: 9863775,
    gdp: 310000,
    houseDistricts: 16,
    stateSenateSeats: 38,
    region: "Midwest",
  },
  {
    _id: "MN",
    countryId: "US",
    name: "Minnesota",
    population: 4775508,
    gdp: 180000,
    houseDistricts: 8,
    stateSenateSeats: 67,
    region: "Midwest",
  },
  {
    _id: "MO",
    countryId: "US",
    name: "Missouri",
    population: 5468338,
    gdp: 170000,
    houseDistricts: 9,
    stateSenateSeats: 34,
    region: "Midwest",
  },
  {
    _id: "ND",
    countryId: "US",
    name: "North Dakota",
    population: 633666,
    gdp: 17000,
    houseDistricts: 1,
    stateSenateSeats: 47,
    region: "Midwest",
  },
  {
    _id: "NE",
    countryId: "US",
    name: "Nebraska",
    population: 1666028,
    gdp: 52000,
    houseDistricts: 3,
    stateSenateSeats: 49,
    region: "Midwest",
  },
  {
    _id: "OH",
    countryId: "US",
    name: "Ohio",
    population: 11256654,
    gdp: 360000,
    houseDistricts: 19,
    stateSenateSeats: 33,
    region: "Midwest",
  },
  {
    _id: "SD",
    countryId: "US",
    name: "South Dakota",
    population: 733133,
    gdp: 24000,
    houseDistricts: 1,
    stateSenateSeats: 35,
    region: "Midwest",
  },
  {
    _id: "WI",
    countryId: "US",
    name: "Wisconsin",
    population: 5250446,
    gdp: 160000,
    houseDistricts: 9,
    stateSenateSeats: 33,
    region: "Midwest",
  },

  // Southwest
  {
    _id: "AZ",
    countryId: "US",
    name: "Arizona",
    population: 4778332,
    gdp: 140000,
    houseDistricts: 6,
    stateSenateSeats: 30,
    region: "Southwest",
  },
  {
    _id: "NM",
    countryId: "US",
    name: "New Mexico",
    population: 1739844,
    gdp: 50000,
    houseDistricts: 3,
    stateSenateSeats: 42,
    region: "Southwest",
  },
  {
    _id: "NV",
    countryId: "US",
    name: "Nevada",
    population: 1809253,
    gdp: 70000,
    houseDistricts: 2,
    stateSenateSeats: 21,
    region: "Southwest",
  },
  {
    _id: "OK",
    countryId: "US",
    name: "Oklahoma",
    population: 3358044,
    gdp: 85000,
    houseDistricts: 6,
    stateSenateSeats: 48,
    region: "Southwest",
  },
  {
    _id: "TX",
    countryId: "US",
    name: "Texas",
    population: 20044141,
    gdp: 720000,
    houseDistricts: 30,
    stateSenateSeats: 31,
    region: "Southwest",
  },
  {
    _id: "UT",
    countryId: "US",
    name: "Utah",
    population: 2129836,
    gdp: 65000,
    houseDistricts: 3,
    stateSenateSeats: 29,
    region: "Southwest",
  },

  // West
  {
    _id: "AK",
    countryId: "US",
    name: "Alaska",
    population: 619500,
    gdp: 26000,
    houseDistricts: 1,
    stateSenateSeats: 20,
    region: "West",
  },
  {
    _id: "CA",
    countryId: "US",
    name: "California",
    population: 33499204,
    gdp: 1300000,
    houseDistricts: 52,
    stateSenateSeats: 40,
    region: "West",
  },
  {
    _id: "CO",
    countryId: "US",
    name: "Colorado",
    population: 4226018,
    gdp: 150000,
    houseDistricts: 6,
    stateSenateSeats: 35,
    region: "West",
  },
  {
    _id: "HI",
    countryId: "US",
    name: "Hawaii",
    population: 1185497,
    gdp: 42000,
    houseDistricts: 2,
    stateSenateSeats: 25,
    region: "West",
  },
  {
    _id: "ID",
    countryId: "US",
    name: "Idaho",
    population: 1251700,
    gdp: 33000,
    houseDistricts: 2,
    stateSenateSeats: 35,
    region: "West",
  },
  {
    _id: "MT",
    countryId: "US",
    name: "Montana",
    population: 882779,
    gdp: 20000,
    houseDistricts: 1,
    stateSenateSeats: 50,
    region: "West",
  },
  {
    _id: "OR",
    countryId: "US",
    name: "Oregon",
    population: 3316154,
    gdp: 110000,
    houseDistricts: 5,
    stateSenateSeats: 30,
    region: "West",
  },
  {
    _id: "WA",
    countryId: "US",
    name: "Washington",
    population: 5756361,
    gdp: 220000,
    houseDistricts: 9,
    stateSenateSeats: 49,
    region: "West",
  },
  {
    _id: "WY",
    countryId: "US",
    name: "Wyoming",
    population: 479602,
    gdp: 18000,
    houseDistricts: 1,
    stateSenateSeats: 30,
    region: "West",
  },

  // Federal District — 0 House districts (non-voting delegate), 0 state senate seats.
  {
    _id: "DC",
    countryId: "US",
    name: "District of Columbia",
    population: 519000,
    gdp: 57000,
    houseDistricts: 0,
    stateSenateSeats: 0,
    region: "Northeast",
  },
];

export default states1999;
