/**
 * SEED INDEPENDENCE — DO NOT DERIVE FROM ANOTHER ERA.
 * Each era seed is self-contained. This file MUST NOT import and transform
 * another era's seed data (e.g. the 2019/2023 `states` arrays). All values are
 * authored for 2007 directly. Changing another era's seed must never alter 2007.
 * Type-only imports are allowed.
 *
 * US state seed for the 2007-default preset (mid-2007 / 110th Congress snapshot,
 * pre-Great-Recession). population = Census July-1-2007 estimates; gdp = BEA 2007
 * nominal state GDP (millions USD). houseDistricts = **2000 apportionment**
 * (the 108th–112th Congresses, in force 2003–2013) and sum to 435 across the 50
 * states; DC = 0. stateSenateSeats/region are era-invariant (copied convention).
 * National anchors: US 2007 pop ≈ 301.2M; nominal GDP ≈ $14.45T.
 */
import type { State } from "@/lib/db/types";

export const states2007: State[] = [
  // Northeast
  {
    _id: "CT",
    countryId: "US",
    name: "Connecticut",
    population: 3502309,
    gdp: 216000,
    houseDistricts: 5,
    stateSenateSeats: 36,
    region: "Northeast",
  },
  {
    _id: "DE",
    countryId: "US",
    name: "Delaware",
    population: 864764,
    gdp: 60000,
    houseDistricts: 1,
    stateSenateSeats: 21,
    region: "Northeast",
  },
  {
    _id: "MA",
    countryId: "US",
    name: "Massachusetts",
    population: 6449755,
    gdp: 365000,
    houseDistricts: 10,
    stateSenateSeats: 40,
    region: "Northeast",
  },
  {
    _id: "MD",
    countryId: "US",
    name: "Maryland",
    population: 5618344,
    gdp: 273000,
    houseDistricts: 8,
    stateSenateSeats: 47,
    region: "Northeast",
  },
  {
    _id: "ME",
    countryId: "US",
    name: "Maine",
    population: 1317207,
    gdp: 49000,
    houseDistricts: 2,
    stateSenateSeats: 35,
    region: "Northeast",
  },
  {
    _id: "NH",
    countryId: "US",
    name: "New Hampshire",
    population: 1315828,
    gdp: 59000,
    houseDistricts: 2,
    stateSenateSeats: 24,
    region: "Northeast",
  },
  {
    _id: "NJ",
    countryId: "US",
    name: "New Jersey",
    population: 8685920,
    gdp: 465000,
    houseDistricts: 13,
    stateSenateSeats: 40,
    region: "Northeast",
  },
  {
    _id: "NY",
    countryId: "US",
    name: "New York",
    population: 19297729,
    gdp: 1114000,
    houseDistricts: 29,
    stateSenateSeats: 63,
    region: "Northeast",
  },
  {
    _id: "PA",
    countryId: "US",
    name: "Pennsylvania",
    population: 12432792,
    gdp: 531000,
    houseDistricts: 19,
    stateSenateSeats: 50,
    region: "Northeast",
  },
  {
    _id: "RI",
    countryId: "US",
    name: "Rhode Island",
    population: 1057832,
    gdp: 47000,
    houseDistricts: 2,
    stateSenateSeats: 38,
    region: "Northeast",
  },
  {
    _id: "VT",
    countryId: "US",
    name: "Vermont",
    population: 621254,
    gdp: 25000,
    houseDistricts: 1,
    stateSenateSeats: 30,
    region: "Northeast",
  },

  // Southeast
  {
    _id: "AL",
    countryId: "US",
    name: "Alabama",
    population: 4627851,
    gdp: 166000,
    houseDistricts: 7,
    stateSenateSeats: 35,
    region: "Southeast",
  },
  {
    _id: "AR",
    countryId: "US",
    name: "Arkansas",
    population: 2834797,
    gdp: 92000,
    houseDistricts: 4,
    stateSenateSeats: 35,
    region: "Southeast",
  },
  {
    _id: "FL",
    countryId: "US",
    name: "Florida",
    population: 18251243,
    gdp: 744000,
    houseDistricts: 25,
    stateSenateSeats: 40,
    region: "Southeast",
  },
  {
    _id: "GA",
    countryId: "US",
    name: "Georgia",
    population: 9544750,
    gdp: 397000,
    houseDistricts: 13,
    stateSenateSeats: 56,
    region: "Southeast",
  },
  {
    _id: "KY",
    countryId: "US",
    name: "Kentucky",
    population: 4241474,
    gdp: 154000,
    houseDistricts: 6,
    stateSenateSeats: 38,
    region: "Southeast",
  },
  {
    _id: "LA",
    countryId: "US",
    name: "Louisiana",
    population: 4293204,
    gdp: 217000,
    houseDistricts: 7,
    stateSenateSeats: 39,
    region: "Southeast",
  },
  {
    _id: "MS",
    countryId: "US",
    name: "Mississippi",
    population: 2918785,
    gdp: 91000,
    houseDistricts: 4,
    stateSenateSeats: 52,
    region: "Southeast",
  },
  {
    _id: "NC",
    countryId: "US",
    name: "North Carolina",
    population: 9061032,
    gdp: 399000,
    houseDistricts: 13,
    stateSenateSeats: 50,
    region: "Southeast",
  },
  {
    _id: "SC",
    countryId: "US",
    name: "South Carolina",
    population: 4407709,
    gdp: 153000,
    houseDistricts: 6,
    stateSenateSeats: 46,
    region: "Southeast",
  },
  {
    _id: "TN",
    countryId: "US",
    name: "Tennessee",
    population: 6156719,
    gdp: 247000,
    houseDistricts: 9,
    stateSenateSeats: 33,
    region: "Southeast",
  },
  {
    _id: "VA",
    countryId: "US",
    name: "Virginia",
    population: 7712091,
    gdp: 383000,
    houseDistricts: 11,
    stateSenateSeats: 40,
    region: "Southeast",
  },
  {
    _id: "WV",
    countryId: "US",
    name: "West Virginia",
    population: 1812035,
    gdp: 57000,
    houseDistricts: 3,
    stateSenateSeats: 34,
    region: "Southeast",
  },

  // Midwest
  {
    _id: "IA",
    countryId: "US",
    name: "Iowa",
    population: 2988046,
    gdp: 130000,
    houseDistricts: 5,
    stateSenateSeats: 50,
    region: "Midwest",
  },
  {
    _id: "IL",
    countryId: "US",
    name: "Illinois",
    population: 12852548,
    gdp: 609000,
    houseDistricts: 19,
    stateSenateSeats: 59,
    region: "Midwest",
  },
  {
    _id: "IN",
    countryId: "US",
    name: "Indiana",
    population: 6345289,
    gdp: 254000,
    houseDistricts: 9,
    stateSenateSeats: 50,
    region: "Midwest",
  },
  {
    _id: "KS",
    countryId: "US",
    name: "Kansas",
    population: 2775997,
    gdp: 117000,
    houseDistricts: 4,
    stateSenateSeats: 40,
    region: "Midwest",
  },
  {
    _id: "MI",
    countryId: "US",
    name: "Michigan",
    population: 10071822,
    gdp: 384000,
    houseDistricts: 15,
    stateSenateSeats: 38,
    region: "Midwest",
  },
  {
    _id: "MN",
    countryId: "US",
    name: "Minnesota",
    population: 5197621,
    gdp: 255000,
    houseDistricts: 8,
    stateSenateSeats: 67,
    region: "Midwest",
  },
  {
    _id: "MO",
    countryId: "US",
    name: "Missouri",
    population: 5878415,
    gdp: 230000,
    houseDistricts: 9,
    stateSenateSeats: 34,
    region: "Midwest",
  },
  {
    _id: "ND",
    countryId: "US",
    name: "North Dakota",
    population: 639715,
    gdp: 28000,
    houseDistricts: 1,
    stateSenateSeats: 47,
    region: "Midwest",
  },
  {
    _id: "NE",
    countryId: "US",
    name: "Nebraska",
    population: 1774571,
    gdp: 80000,
    houseDistricts: 3,
    stateSenateSeats: 49,
    region: "Midwest",
  },
  {
    _id: "OH",
    countryId: "US",
    name: "Ohio",
    population: 11466917,
    gdp: 466000,
    houseDistricts: 18,
    stateSenateSeats: 33,
    region: "Midwest",
  },
  {
    _id: "SD",
    countryId: "US",
    name: "South Dakota",
    population: 796214,
    gdp: 34000,
    houseDistricts: 1,
    stateSenateSeats: 35,
    region: "Midwest",
  },
  {
    _id: "WI",
    countryId: "US",
    name: "Wisconsin",
    population: 5601640,
    gdp: 232000,
    houseDistricts: 8,
    stateSenateSeats: 33,
    region: "Midwest",
  },

  // Southwest
  {
    _id: "AZ",
    countryId: "US",
    name: "Arizona",
    population: 6338755,
    gdp: 247000,
    houseDistricts: 8,
    stateSenateSeats: 30,
    region: "Southwest",
  },
  {
    _id: "NM",
    countryId: "US",
    name: "New Mexico",
    population: 1969915,
    gdp: 77000,
    houseDistricts: 3,
    stateSenateSeats: 42,
    region: "Southwest",
  },
  {
    _id: "NV",
    countryId: "US",
    name: "Nevada",
    population: 2565382,
    gdp: 124000,
    houseDistricts: 3,
    stateSenateSeats: 21,
    region: "Southwest",
  },
  {
    _id: "OK",
    countryId: "US",
    name: "Oklahoma",
    population: 3617316,
    gdp: 140000,
    houseDistricts: 5,
    stateSenateSeats: 48,
    region: "Southwest",
  },
  {
    _id: "TX",
    countryId: "US",
    name: "Texas",
    population: 23904380,
    gdp: 1141000,
    houseDistricts: 32,
    stateSenateSeats: 31,
    region: "Southwest",
  },
  {
    _id: "UT",
    countryId: "US",
    name: "Utah",
    population: 2645330,
    gdp: 105000,
    houseDistricts: 3,
    stateSenateSeats: 29,
    region: "Southwest",
  },

  // West
  {
    _id: "AK",
    countryId: "US",
    name: "Alaska",
    population: 683478,
    gdp: 44000,
    houseDistricts: 1,
    stateSenateSeats: 20,
    region: "West",
  },
  {
    _id: "CA",
    countryId: "US",
    name: "California",
    population: 36553215,
    gdp: 1801000,
    houseDistricts: 53,
    stateSenateSeats: 40,
    region: "West",
  },
  {
    _id: "CO",
    countryId: "US",
    name: "Colorado",
    population: 4861515,
    gdp: 236000,
    houseDistricts: 7,
    stateSenateSeats: 35,
    region: "West",
  },
  {
    _id: "HI",
    countryId: "US",
    name: "Hawaii",
    population: 1283388,
    gdp: 61000,
    houseDistricts: 2,
    stateSenateSeats: 25,
    region: "West",
  },
  {
    _id: "ID",
    countryId: "US",
    name: "Idaho",
    population: 1499402,
    gdp: 51000,
    houseDistricts: 2,
    stateSenateSeats: 35,
    region: "West",
  },
  {
    _id: "MT",
    countryId: "US",
    name: "Montana",
    population: 957861,
    gdp: 34000,
    houseDistricts: 1,
    stateSenateSeats: 50,
    region: "West",
  },
  {
    _id: "OR",
    countryId: "US",
    name: "Oregon",
    population: 3747455,
    gdp: 158000,
    houseDistricts: 5,
    stateSenateSeats: 30,
    region: "West",
  },
  {
    _id: "WA",
    countryId: "US",
    name: "Washington",
    population: 6468424,
    gdp: 311000,
    houseDistricts: 9,
    stateSenateSeats: 49,
    region: "West",
  },
  {
    _id: "WY",
    countryId: "US",
    name: "Wyoming",
    population: 522830,
    gdp: 33000,
    houseDistricts: 1,
    stateSenateSeats: 30,
    region: "West",
  },

  // Federal District — 0 House districts (non-voting delegate), 0 state senate seats.
  {
    _id: "DC",
    countryId: "US",
    name: "District of Columbia",
    population: 588292,
    gdp: 93000,
    houseDistricts: 0,
    stateSenateSeats: 0,
    region: "Northeast",
  },
];

export default states2007;
