/**
 * US states, 1990 Census + 1991 nominal Gross State Product baseline.
 *
 * Population values are 1990 US Census apportionment counts.
 *   Source: US Census Bureau, 1990 Census of Population, Table 1.
 * GDP figures are 1991 nominal Gross State Product in millions of USD.
 *   Source: Bureau of Economic Analysis, GSP by State, 1991 (approximate;
 *   the modern GDP series is consistent with the BEA's 1997 revision).
 * House districts reflect the 1990 reapportionment, effective for the
 *   103rd Congress (1993-1995). For a 1991 game start the 102nd Congress
 *   uses the 1980 apportionment — but the game's chamber sizing follows
 *   the 1990 numbers because the 102nd's apportionment is irrelevant
 *   after the first cycle. Total = 435 in both apportionments.
 * State senate seat counts use the modern configured chamber sizes
 *   because 1990 state senate seat counts are not material to gameplay.
 *
 * DC is included as a federal-district entity with 0 House districts
 * and 0 state senate seats. 1990 DC population 606,900 from the
 * 1990 Census.
 */

import type { State } from "@/lib/db/types";

export const states1991: State[] = [
  // Northeast
  {
    _id: "CT",
    countryId: "US",
    name: "Connecticut",
    population: 3287116,
    gdp: 92500,
    houseDistricts: 6,
    stateSenateSeats: 36,
    region: "Northeast",
  },
  {
    _id: "DE",
    countryId: "US",
    name: "Delaware",
    population: 666168,
    gdp: 17500,
    houseDistricts: 1,
    stateSenateSeats: 21,
    region: "Northeast",
  },
  {
    _id: "MA",
    countryId: "US",
    name: "Massachusetts",
    population: 6016425,
    gdp: 153000,
    houseDistricts: 10,
    stateSenateSeats: 40,
    region: "Northeast",
  },
  {
    _id: "MD",
    countryId: "US",
    name: "Maryland",
    population: 4781468,
    gdp: 117000,
    houseDistricts: 8,
    stateSenateSeats: 47,
    region: "Northeast",
  },
  {
    _id: "ME",
    countryId: "US",
    name: "Maine",
    population: 1227928,
    gdp: 24000,
    houseDistricts: 2,
    stateSenateSeats: 35,
    region: "Northeast",
  },
  {
    _id: "NH",
    countryId: "US",
    name: "New Hampshire",
    population: 1109252,
    gdp: 24000,
    houseDistricts: 2,
    stateSenateSeats: 24,
    region: "Northeast",
  },
  {
    _id: "NJ",
    countryId: "US",
    name: "New Jersey",
    population: 7730188,
    gdp: 209000,
    houseDistricts: 13,
    stateSenateSeats: 40,
    region: "Northeast",
  },
  {
    _id: "NY",
    countryId: "US",
    name: "New York",
    population: 17990455,
    gdp: 460000,
    houseDistricts: 31,
    stateSenateSeats: 63,
    region: "Northeast",
  },
  {
    _id: "PA",
    countryId: "US",
    name: "Pennsylvania",
    population: 11881643,
    gdp: 234000,
    houseDistricts: 21,
    stateSenateSeats: 50,
    region: "Northeast",
  },
  {
    _id: "RI",
    countryId: "US",
    name: "Rhode Island",
    population: 1003464,
    gdp: 20000,
    houseDistricts: 2,
    stateSenateSeats: 38,
    region: "Northeast",
  },
  {
    _id: "VT",
    countryId: "US",
    name: "Vermont",
    population: 562758,
    gdp: 11500,
    houseDistricts: 1,
    stateSenateSeats: 30,
    region: "Northeast",
  },
  // South
  {
    _id: "AL",
    countryId: "US",
    name: "Alabama",
    population: 4040587,
    gdp: 67000,
    houseDistricts: 7,
    stateSenateSeats: 35,
    region: "South",
  },
  {
    _id: "AR",
    countryId: "US",
    name: "Arkansas",
    population: 2350725,
    gdp: 35000,
    houseDistricts: 4,
    stateSenateSeats: 35,
    region: "South",
  },
  {
    _id: "FL",
    countryId: "US",
    name: "Florida",
    population: 12937926,
    gdp: 235000,
    houseDistricts: 23,
    stateSenateSeats: 40,
    region: "South",
  },
  {
    _id: "GA",
    countryId: "US",
    name: "Georgia",
    population: 6478216,
    gdp: 124000,
    houseDistricts: 11,
    stateSenateSeats: 56,
    region: "South",
  },
  {
    _id: "KY",
    countryId: "US",
    name: "Kentucky",
    population: 3685296,
    gdp: 62000,
    houseDistricts: 6,
    stateSenateSeats: 38,
    region: "South",
  },
  {
    _id: "LA",
    countryId: "US",
    name: "Louisiana",
    population: 4219973,
    gdp: 80000,
    houseDistricts: 7,
    stateSenateSeats: 39,
    region: "South",
  },
  {
    _id: "MS",
    countryId: "US",
    name: "Mississippi",
    population: 2573216,
    gdp: 35000,
    houseDistricts: 5,
    stateSenateSeats: 52,
    region: "South",
  },
  {
    _id: "NC",
    countryId: "US",
    name: "North Carolina",
    population: 6628637,
    gdp: 124000,
    houseDistricts: 12,
    stateSenateSeats: 50,
    region: "South",
  },
  {
    _id: "OK",
    countryId: "US",
    name: "Oklahoma",
    population: 3145585,
    gdp: 57000,
    houseDistricts: 6,
    stateSenateSeats: 48,
    region: "South",
  },
  {
    _id: "SC",
    countryId: "US",
    name: "South Carolina",
    population: 3486703,
    gdp: 55000,
    houseDistricts: 6,
    stateSenateSeats: 46,
    region: "South",
  },
  {
    _id: "TN",
    countryId: "US",
    name: "Tennessee",
    population: 4877185,
    gdp: 92000,
    houseDistricts: 9,
    stateSenateSeats: 33,
    region: "South",
  },
  {
    _id: "TX",
    countryId: "US",
    name: "Texas",
    population: 16986510,
    gdp: 350000,
    houseDistricts: 30,
    stateSenateSeats: 31,
    region: "South",
  },
  {
    _id: "VA",
    countryId: "US",
    name: "Virginia",
    population: 6187358,
    gdp: 138000,
    houseDistricts: 11,
    stateSenateSeats: 40,
    region: "South",
  },
  {
    _id: "WV",
    countryId: "US",
    name: "West Virginia",
    population: 1793477,
    gdp: 26000,
    houseDistricts: 3,
    stateSenateSeats: 34,
    region: "South",
  },
  // Midwest
  {
    _id: "IL",
    countryId: "US",
    name: "Illinois",
    population: 11430602,
    gdp: 275000,
    houseDistricts: 20,
    stateSenateSeats: 59,
    region: "Midwest",
  },
  {
    _id: "IN",
    countryId: "US",
    name: "Indiana",
    population: 5544159,
    gdp: 110000,
    houseDistricts: 10,
    stateSenateSeats: 50,
    region: "Midwest",
  },
  {
    _id: "IA",
    countryId: "US",
    name: "Iowa",
    population: 2776755,
    gdp: 56000,
    houseDistricts: 5,
    stateSenateSeats: 50,
    region: "Midwest",
  },
  {
    _id: "KS",
    countryId: "US",
    name: "Kansas",
    population: 2477574,
    gdp: 53000,
    houseDistricts: 4,
    stateSenateSeats: 40,
    region: "Midwest",
  },
  {
    _id: "MI",
    countryId: "US",
    name: "Michigan",
    population: 9295297,
    gdp: 200000,
    houseDistricts: 16,
    stateSenateSeats: 38,
    region: "Midwest",
  },
  {
    _id: "MN",
    countryId: "US",
    name: "Minnesota",
    population: 4375099,
    gdp: 110000,
    houseDistricts: 8,
    stateSenateSeats: 67,
    region: "Midwest",
  },
  {
    _id: "MO",
    countryId: "US",
    name: "Missouri",
    population: 5117073,
    gdp: 105000,
    houseDistricts: 9,
    stateSenateSeats: 34,
    region: "Midwest",
  },
  {
    _id: "NE",
    countryId: "US",
    name: "Nebraska",
    population: 1578385,
    gdp: 33000,
    houseDistricts: 3,
    stateSenateSeats: 49,
    region: "Midwest",
  },
  {
    _id: "ND",
    countryId: "US",
    name: "North Dakota",
    population: 638800,
    gdp: 12000,
    houseDistricts: 1,
    stateSenateSeats: 47,
    region: "Midwest",
  },
  {
    _id: "OH",
    countryId: "US",
    name: "Ohio",
    population: 10847115,
    gdp: 230000,
    houseDistricts: 19,
    stateSenateSeats: 33,
    region: "Midwest",
  },
  {
    _id: "SD",
    countryId: "US",
    name: "South Dakota",
    population: 696004,
    gdp: 13000,
    houseDistricts: 1,
    stateSenateSeats: 35,
    region: "Midwest",
  },
  {
    _id: "WI",
    countryId: "US",
    name: "Wisconsin",
    population: 4891769,
    gdp: 105000,
    houseDistricts: 9,
    stateSenateSeats: 33,
    region: "Midwest",
  },
  // West
  {
    _id: "AK",
    countryId: "US",
    name: "Alaska",
    population: 550043,
    gdp: 24000,
    houseDistricts: 1,
    stateSenateSeats: 20,
    region: "West",
  },
  {
    _id: "AZ",
    countryId: "US",
    name: "Arizona",
    population: 3665228,
    gdp: 70000,
    houseDistricts: 6,
    stateSenateSeats: 30,
    region: "West",
  },
  {
    _id: "CA",
    countryId: "US",
    name: "California",
    population: 29760021,
    gdp: 740000,
    houseDistricts: 52,
    stateSenateSeats: 40,
    region: "West",
  },
  {
    _id: "CO",
    countryId: "US",
    name: "Colorado",
    population: 3294394,
    gdp: 70000,
    houseDistricts: 6,
    stateSenateSeats: 35,
    region: "West",
  },
  {
    _id: "HI",
    countryId: "US",
    name: "Hawaii",
    population: 1108229,
    gdp: 30000,
    houseDistricts: 2,
    stateSenateSeats: 25,
    region: "West",
  },
  {
    _id: "ID",
    countryId: "US",
    name: "Idaho",
    population: 1006749,
    gdp: 16000,
    houseDistricts: 2,
    stateSenateSeats: 35,
    region: "West",
  },
  {
    _id: "MT",
    countryId: "US",
    name: "Montana",
    population: 799065,
    gdp: 13000,
    houseDistricts: 1,
    stateSenateSeats: 50,
    region: "West",
  },
  {
    _id: "NV",
    countryId: "US",
    name: "Nevada",
    population: 1201833,
    gdp: 30000,
    houseDistricts: 2,
    stateSenateSeats: 21,
    region: "West",
  },
  {
    _id: "NM",
    countryId: "US",
    name: "New Mexico",
    population: 1515069,
    gdp: 26000,
    houseDistricts: 3,
    stateSenateSeats: 42,
    region: "West",
  },
  {
    _id: "OR",
    countryId: "US",
    name: "Oregon",
    population: 2842321,
    gdp: 55000,
    houseDistricts: 5,
    stateSenateSeats: 30,
    region: "West",
  },
  {
    _id: "UT",
    countryId: "US",
    name: "Utah",
    population: 1722850,
    gdp: 30000,
    houseDistricts: 3,
    stateSenateSeats: 29,
    region: "West",
  },
  {
    _id: "WA",
    countryId: "US",
    name: "Washington",
    population: 4866692,
    gdp: 115000,
    houseDistricts: 9,
    stateSenateSeats: 49,
    region: "West",
  },
  {
    _id: "WY",
    countryId: "US",
    name: "Wyoming",
    population: 453588,
    gdp: 12000,
    houseDistricts: 1,
    stateSenateSeats: 30,
    region: "West",
  },
  // Federal District
  {
    _id: "DC",
    countryId: "US",
    name: "District of Columbia",
    population: 606900,
    gdp: 38000,
    houseDistricts: 0,
    stateSenateSeats: 0,
    region: "Northeast",
  },
];
