/**
 * SEED INDEPENDENCE — DO NOT DERIVE FROM ANOTHER ERA.
 * Each era seed is self-contained. This file MUST NOT import and transform
 * another era's seed data (e.g. the 2019 `states` array). All values are
 * authored for 2023 directly. Changing the 2019 (or any other) seed must never
 * alter 2023. Same-era imports (states2023 for region IDs) and type-only
 * imports are allowed.
 */
import type { State } from "@/lib/db/types";

/**
 * US state seed for the 2023-default preset (Jan 2023 / 118th Congress snapshot).
 * Structure mirrors states.ts (2019-default); population uses 2023 Census
 * estimates (July 2023 vintage) and gdp uses 2023 nominal BEA state GDP
 * (millions USD). houseDistricts/stateSenateSeats/region copied verbatim
 * (2022 apportionment). National anchors: US 2023 pop ≈ 334.9M; GDP ≈ $27.4T.
 */
export const states2023: State[] = [
  // Northeast
  {
    _id: "CT",
    countryId: "US",
    name: "Connecticut",
    population: 3617176,
    gdp: 323800,
    houseDistricts: 5,
    stateSenateSeats: 36,
    region: "Northeast",
  },
  {
    _id: "DE",
    countryId: "US",
    name: "Delaware",
    population: 1031890,
    gdp: 90900,
    houseDistricts: 1,
    stateSenateSeats: 21,
    region: "Northeast",
  },
  {
    _id: "MA",
    countryId: "US",
    name: "Massachusetts",
    population: 7001399,
    gdp: 741700,
    houseDistricts: 9,
    stateSenateSeats: 40,
    region: "Northeast",
  },
  {
    _id: "MD",
    countryId: "US",
    name: "Maryland",
    population: 6180253,
    gdp: 484800,
    houseDistricts: 8,
    stateSenateSeats: 47,
    region: "Northeast",
  },
  {
    _id: "ME",
    countryId: "US",
    name: "Maine",
    population: 1395722,
    gdp: 83000,
    houseDistricts: 2,
    stateSenateSeats: 35,
    region: "Northeast",
  },
  {
    _id: "NH",
    countryId: "US",
    name: "New Hampshire",
    population: 1402054,
    gdp: 107000,
    houseDistricts: 2,
    stateSenateSeats: 24,
    region: "Northeast",
  },
  {
    _id: "NJ",
    countryId: "US",
    name: "New Jersey",
    population: 9290841,
    gdp: 789600,
    houseDistricts: 12,
    stateSenateSeats: 40,
    region: "Northeast",
  },
  {
    _id: "NY",
    countryId: "US",
    name: "New York",
    population: 19571216,
    gdp: 2053900,
    houseDistricts: 26,
    stateSenateSeats: 63,
    region: "Northeast",
  },
  {
    _id: "PA",
    countryId: "US",
    name: "Pennsylvania",
    population: 12961683,
    gdp: 963400,
    houseDistricts: 17,
    stateSenateSeats: 50,
    region: "Northeast",
  },
  {
    _id: "RI",
    countryId: "US",
    name: "Rhode Island",
    population: 1112308,
    gdp: 79000,
    houseDistricts: 2,
    stateSenateSeats: 38,
    region: "Northeast",
  },
  {
    _id: "VT",
    countryId: "US",
    name: "Vermont",
    population: 647818,
    gdp: 42200,
    houseDistricts: 1,
    stateSenateSeats: 30,
    region: "Northeast",
  },

  // Southeast
  {
    _id: "AL",
    countryId: "US",
    name: "Alabama",
    population: 5108468,
    gdp: 289700,
    houseDistricts: 7,
    stateSenateSeats: 35,
    region: "Southeast",
  },
  {
    _id: "AR",
    countryId: "US",
    name: "Arkansas",
    population: 3067732,
    gdp: 165200,
    houseDistricts: 4,
    stateSenateSeats: 35,
    region: "Southeast",
  },
  {
    _id: "FL",
    countryId: "US",
    name: "Florida",
    population: 22610726,
    gdp: 1551600,
    houseDistricts: 28,
    stateSenateSeats: 40,
    region: "Southeast",
  },
  {
    _id: "GA",
    countryId: "US",
    name: "Georgia",
    population: 11029227,
    gdp: 800600,
    houseDistricts: 14,
    stateSenateSeats: 56,
    region: "Southeast",
  },
  {
    _id: "KY",
    countryId: "US",
    name: "Kentucky",
    population: 4526154,
    gdp: 269500,
    houseDistricts: 6,
    stateSenateSeats: 38,
    region: "Southeast",
  },
  {
    _id: "LA",
    countryId: "US",
    name: "Louisiana",
    population: 4573749,
    gdp: 286000,
    houseDistricts: 6,
    stateSenateSeats: 39,
    region: "Southeast",
  },
  {
    _id: "MS",
    countryId: "US",
    name: "Mississippi",
    population: 2939690,
    gdp: 143700,
    houseDistricts: 4,
    stateSenateSeats: 52,
    region: "Southeast",
  },
  {
    _id: "NC",
    countryId: "US",
    name: "North Carolina",
    population: 10835491,
    gdp: 741900,
    houseDistricts: 14,
    stateSenateSeats: 50,
    region: "Southeast",
  },
  {
    _id: "SC",
    countryId: "US",
    name: "South Carolina",
    population: 5373555,
    gdp: 307600,
    houseDistricts: 7,
    stateSenateSeats: 46,
    region: "Southeast",
  },
  {
    _id: "TN",
    countryId: "US",
    name: "Tennessee",
    population: 7126489,
    gdp: 492800,
    houseDistricts: 9,
    stateSenateSeats: 33,
    region: "Southeast",
  },
  {
    _id: "VA",
    countryId: "US",
    name: "Virginia",
    population: 8715698,
    gdp: 691400,
    houseDistricts: 11,
    stateSenateSeats: 40,
    region: "Southeast",
  },
  {
    _id: "WV",
    countryId: "US",
    name: "West Virginia",
    population: 1775156,
    gdp: 95100,
    houseDistricts: 2,
    stateSenateSeats: 34,
    region: "Southeast",
  },

  // Midwest
  {
    _id: "IA",
    countryId: "US",
    name: "Iowa",
    population: 3207004,
    gdp: 243200,
    houseDistricts: 4,
    stateSenateSeats: 50,
    region: "Midwest",
  },
  {
    _id: "IL",
    countryId: "US",
    name: "Illinois",
    population: 12549689,
    gdp: 1049800,
    houseDistricts: 17,
    stateSenateSeats: 59,
    region: "Midwest",
  },
  {
    _id: "IN",
    countryId: "US",
    name: "Indiana",
    population: 6862199,
    gdp: 467200,
    houseDistricts: 9,
    stateSenateSeats: 50,
    region: "Midwest",
  },
  {
    _id: "KS",
    countryId: "US",
    name: "Kansas",
    population: 2940865,
    gdp: 211000,
    houseDistricts: 4,
    stateSenateSeats: 40,
    region: "Midwest",
  },
  {
    _id: "MI",
    countryId: "US",
    name: "Michigan",
    population: 10037261,
    gdp: 663700,
    houseDistricts: 13,
    stateSenateSeats: 38,
    region: "Midwest",
  },
  {
    _id: "MN",
    countryId: "US",
    name: "Minnesota",
    population: 5737915,
    gdp: 459300,
    houseDistricts: 8,
    stateSenateSeats: 67,
    region: "Midwest",
  },
  {
    _id: "MO",
    countryId: "US",
    name: "Missouri",
    population: 6177957,
    gdp: 410500,
    houseDistricts: 8,
    stateSenateSeats: 34,
    region: "Midwest",
  },
  {
    _id: "ND",
    countryId: "US",
    name: "North Dakota",
    population: 783926,
    gdp: 73200,
    houseDistricts: 1,
    stateSenateSeats: 47,
    region: "Midwest",
  },
  {
    _id: "NE",
    countryId: "US",
    name: "Nebraska",
    population: 1978379,
    gdp: 170900,
    houseDistricts: 3,
    stateSenateSeats: 49,
    region: "Midwest",
  },
  {
    _id: "OH",
    countryId: "US",
    name: "Ohio",
    population: 11785935,
    gdp: 831800,
    houseDistricts: 15,
    stateSenateSeats: 33,
    region: "Midwest",
  },
  {
    _id: "SD",
    countryId: "US",
    name: "South Dakota",
    population: 919318,
    gdp: 71500,
    houseDistricts: 1,
    stateSenateSeats: 35,
    region: "Midwest",
  },
  {
    _id: "WI",
    countryId: "US",
    name: "Wisconsin",
    population: 5955474,
    gdp: 421100,
    houseDistricts: 8,
    stateSenateSeats: 33,
    region: "Midwest",
  },

  // Southwest
  {
    _id: "AZ",
    countryId: "US",
    name: "Arizona",
    population: 7431344,
    gdp: 497300,
    houseDistricts: 9,
    stateSenateSeats: 30,
    region: "Southwest",
  },
  {
    _id: "NM",
    countryId: "US",
    name: "New Mexico",
    population: 2114371,
    gdp: 122700,
    houseDistricts: 3,
    stateSenateSeats: 42,
    region: "Southwest",
  },
  {
    _id: "NV",
    countryId: "US",
    name: "Nevada",
    population: 3194176,
    gdp: 233200,
    houseDistricts: 4,
    stateSenateSeats: 21,
    region: "Southwest",
  },
  {
    _id: "OK",
    countryId: "US",
    name: "Oklahoma",
    population: 4053824,
    gdp: 246100,
    houseDistricts: 5,
    stateSenateSeats: 48,
    region: "Southwest",
  },
  {
    _id: "TX",
    countryId: "US",
    name: "Texas",
    population: 30503301,
    gdp: 2563700,
    houseDistricts: 38,
    stateSenateSeats: 31,
    region: "Southwest",
  },
  {
    _id: "UT",
    countryId: "US",
    name: "Utah",
    population: 3417734,
    gdp: 274100,
    houseDistricts: 4,
    stateSenateSeats: 29,
    region: "Southwest",
  },

  // West
  {
    _id: "AK",
    countryId: "US",
    name: "Alaska",
    population: 733583,
    gdp: 66100,
    houseDistricts: 1,
    stateSenateSeats: 20,
    region: "West",
  },
  {
    _id: "CA",
    countryId: "US",
    name: "California",
    population: 38965193,
    gdp: 3985600,
    houseDistricts: 52,
    stateSenateSeats: 40,
    region: "West",
  },
  {
    _id: "CO",
    countryId: "US",
    name: "Colorado",
    population: 5877610,
    gdp: 496000,
    houseDistricts: 8,
    stateSenateSeats: 35,
    region: "West",
  },
  {
    _id: "HI",
    countryId: "US",
    name: "Hawaii",
    population: 1435138,
    gdp: 107800,
    houseDistricts: 2,
    stateSenateSeats: 25,
    region: "West",
  },
  {
    _id: "ID",
    countryId: "US",
    name: "Idaho",
    population: 1964726,
    gdp: 122600,
    houseDistricts: 2,
    stateSenateSeats: 35,
    region: "West",
  },
  {
    _id: "MT",
    countryId: "US",
    name: "Montana",
    population: 1132812,
    gdp: 72800,
    houseDistricts: 2,
    stateSenateSeats: 50,
    region: "West",
  },
  {
    _id: "OR",
    countryId: "US",
    name: "Oregon",
    population: 4233358,
    gdp: 313300,
    houseDistricts: 6,
    stateSenateSeats: 30,
    region: "West",
  },
  {
    _id: "WA",
    countryId: "US",
    name: "Washington",
    population: 7812880,
    gdp: 818800,
    houseDistricts: 10,
    stateSenateSeats: 49,
    region: "West",
  },
  {
    _id: "WY",
    countryId: "US",
    name: "Wyoming",
    population: 584057,
    gdp: 54400,
    houseDistricts: 1,
    stateSenateSeats: 30,
    region: "West",
  },
  // ─── Federal District ────────────────────────────────────────────────────
  // The District of Columbia is not a state but holds 3 electoral votes per
  // the 23rd Amendment and votes in presidential elections. It has 0 House
  // districts (Eleanor Holmes Norton is a non-voting delegate) and 0 state
  // senate seats (the DC Council is a 13-seat unicameral body — modeled
  // here as `stateSenateSeats: 0` so cross-state seat tallies stay honest).
  {
    _id: "DC",
    countryId: "US",
    name: "District of Columbia",
    population: 678972,
    gdp: 174300,
    houseDistricts: 0,
    stateSenateSeats: 0,
    region: "Northeast",
  },
];

export default states2023;
