import type { HistoricalSeat } from "@/lib/constants/historicalSeats";

/**
 * Projected US House composition for the January 2027 seed.
 *
 * Call the Map's 2026-09-09 district favorites aggregate to 224 Democratic
 * and 211 Republican seats. The site's national median is 228 Democratic and
 * 207 Republican, which is the product's frozen composition assumption.
 * Reconciliation assigns the four closest Republican-favorite districts to
 * Democrats: FL-22 (even), PA-08 (R+0.7), NY-17 (R+0.9), and OH-09 (R+1.0).
 *
 * Source: https://www.callthemap.com/house
 */
export const US_HOUSE_2027: HistoricalSeat[] = [
  { state: "AK", officeType: "house", party: "republican", seatsHeld: 1 },
  { state: "AL", officeType: "house", party: "democrat", seatsHeld: 1 },
  { state: "AL", officeType: "house", party: "republican", seatsHeld: 6 },
  { state: "AR", officeType: "house", party: "republican", seatsHeld: 4 },
  { state: "AZ", officeType: "house", party: "democrat", seatsHeld: 5 },
  { state: "AZ", officeType: "house", party: "republican", seatsHeld: 4 },
  { state: "CA", officeType: "house", party: "democrat", seatsHeld: 48 },
  { state: "CA", officeType: "house", party: "republican", seatsHeld: 4 },
  { state: "CO", officeType: "house", party: "democrat", seatsHeld: 5 },
  { state: "CO", officeType: "house", party: "republican", seatsHeld: 3 },
  { state: "CT", officeType: "house", party: "democrat", seatsHeld: 5 },
  { state: "DE", officeType: "house", party: "democrat", seatsHeld: 1 },
  { state: "FL", officeType: "house", party: "democrat", seatsHeld: 7 },
  { state: "FL", officeType: "house", party: "republican", seatsHeld: 21 },
  { state: "GA", officeType: "house", party: "democrat", seatsHeld: 5 },
  { state: "GA", officeType: "house", party: "republican", seatsHeld: 9 },
  { state: "HI", officeType: "house", party: "democrat", seatsHeld: 2 },
  { state: "IA", officeType: "house", party: "democrat", seatsHeld: 1 },
  { state: "IA", officeType: "house", party: "republican", seatsHeld: 3 },
  { state: "ID", officeType: "house", party: "republican", seatsHeld: 2 },
  { state: "IL", officeType: "house", party: "democrat", seatsHeld: 14 },
  { state: "IL", officeType: "house", party: "republican", seatsHeld: 3 },
  { state: "IN", officeType: "house", party: "democrat", seatsHeld: 2 },
  { state: "IN", officeType: "house", party: "republican", seatsHeld: 7 },
  { state: "KS", officeType: "house", party: "democrat", seatsHeld: 1 },
  { state: "KS", officeType: "house", party: "republican", seatsHeld: 3 },
  { state: "KY", officeType: "house", party: "democrat", seatsHeld: 1 },
  { state: "KY", officeType: "house", party: "republican", seatsHeld: 5 },
  { state: "LA", officeType: "house", party: "democrat", seatsHeld: 1 },
  { state: "LA", officeType: "house", party: "republican", seatsHeld: 5 },
  { state: "MA", officeType: "house", party: "democrat", seatsHeld: 9 },
  { state: "MD", officeType: "house", party: "democrat", seatsHeld: 7 },
  { state: "MD", officeType: "house", party: "republican", seatsHeld: 1 },
  { state: "ME", officeType: "house", party: "democrat", seatsHeld: 1 },
  { state: "ME", officeType: "house", party: "republican", seatsHeld: 1 },
  { state: "MI", officeType: "house", party: "democrat", seatsHeld: 7 },
  { state: "MI", officeType: "house", party: "republican", seatsHeld: 6 },
  { state: "MN", officeType: "house", party: "democrat", seatsHeld: 4 },
  { state: "MN", officeType: "house", party: "republican", seatsHeld: 4 },
  { state: "MO", officeType: "house", party: "democrat", seatsHeld: 2 },
  { state: "MO", officeType: "house", party: "republican", seatsHeld: 6 },
  { state: "MS", officeType: "house", party: "democrat", seatsHeld: 1 },
  { state: "MS", officeType: "house", party: "republican", seatsHeld: 3 },
  { state: "MT", officeType: "house", party: "republican", seatsHeld: 2 },
  { state: "NC", officeType: "house", party: "democrat", seatsHeld: 4 },
  { state: "NC", officeType: "house", party: "republican", seatsHeld: 10 },
  { state: "ND", officeType: "house", party: "republican", seatsHeld: 1 },
  { state: "NE", officeType: "house", party: "democrat", seatsHeld: 1 },
  { state: "NE", officeType: "house", party: "republican", seatsHeld: 2 },
  { state: "NH", officeType: "house", party: "democrat", seatsHeld: 2 },
  { state: "NJ", officeType: "house", party: "democrat", seatsHeld: 10 },
  { state: "NJ", officeType: "house", party: "republican", seatsHeld: 2 },
  { state: "NM", officeType: "house", party: "democrat", seatsHeld: 3 },
  { state: "NV", officeType: "house", party: "democrat", seatsHeld: 3 },
  { state: "NV", officeType: "house", party: "republican", seatsHeld: 1 },
  { state: "NY", officeType: "house", party: "democrat", seatsHeld: 20 },
  { state: "NY", officeType: "house", party: "republican", seatsHeld: 6 },
  { state: "OH", officeType: "house", party: "democrat", seatsHeld: 6 },
  { state: "OH", officeType: "house", party: "republican", seatsHeld: 9 },
  { state: "OK", officeType: "house", party: "republican", seatsHeld: 5 },
  { state: "OR", officeType: "house", party: "democrat", seatsHeld: 5 },
  { state: "OR", officeType: "house", party: "republican", seatsHeld: 1 },
  { state: "PA", officeType: "house", party: "democrat", seatsHeld: 10 },
  { state: "PA", officeType: "house", party: "republican", seatsHeld: 7 },
  { state: "RI", officeType: "house", party: "democrat", seatsHeld: 2 },
  { state: "SC", officeType: "house", party: "democrat", seatsHeld: 1 },
  { state: "SC", officeType: "house", party: "republican", seatsHeld: 6 },
  { state: "SD", officeType: "house", party: "republican", seatsHeld: 1 },
  { state: "TN", officeType: "house", party: "republican", seatsHeld: 9 },
  { state: "TX", officeType: "house", party: "democrat", seatsHeld: 11 },
  { state: "TX", officeType: "house", party: "republican", seatsHeld: 27 },
  { state: "UT", officeType: "house", party: "democrat", seatsHeld: 1 },
  { state: "UT", officeType: "house", party: "republican", seatsHeld: 3 },
  { state: "VA", officeType: "house", party: "democrat", seatsHeld: 7 },
  { state: "VA", officeType: "house", party: "republican", seatsHeld: 4 },
  { state: "VT", officeType: "house", party: "democrat", seatsHeld: 1 },
  { state: "WA", officeType: "house", party: "democrat", seatsHeld: 8 },
  { state: "WA", officeType: "house", party: "republican", seatsHeld: 2 },
  { state: "WI", officeType: "house", party: "democrat", seatsHeld: 3 },
  { state: "WI", officeType: "house", party: "republican", seatsHeld: 5 },
  { state: "WV", officeType: "house", party: "republican", seatsHeld: 2 },
  { state: "WY", officeType: "house", party: "republican", seatsHeld: 1 },
];
