import type { HistoricalSeat } from "@/lib/constants/historicalSeats";

/**
 * January 2027 modern legislature snapshot. UK rows reproduce the official
 * 2024 result by region. German 2025 and Japanese 2026/2025 national party
 * totals are apportioned to game regions using the preceding regional pattern.
 * Sources: commonslibrary.parliament.uk/research-briefings/cbp-10009/
 * bundeswahlleiterin.de/bundestagswahlen/2025/ergebnisse/bund-99.html
 * shugiin.go.jp/internet/itdb_english.nsf/html/statics/english/strength.htm
 * sangiin.go.jp/japanese/joho1/kousei/eng/strength/index.htm
 */
export const UK_COMMONS_2027: HistoricalSeat[] = [
  {
    state: "EAE",
    officeType: "commons",
    party: "uk_labour",
    seatsHeld: 27,
  },
  {
    state: "EAE",
    officeType: "commons",
    party: "uk_conservative",
    seatsHeld: 23,
  },
  {
    state: "EAE",
    officeType: "commons",
    party: "uk_libdem",
    seatsHeld: 7,
  },
  {
    state: "EAE",
    officeType: "commons",
    party: "uk_reform",
    seatsHeld: 3,
  },
  {
    state: "EAE",
    officeType: "commons",
    party: "uk_green",
    seatsHeld: 1,
  },
  {
    state: "EMI",
    officeType: "commons",
    party: "uk_labour",
    seatsHeld: 29,
  },
  {
    state: "EMI",
    officeType: "commons",
    party: "uk_conservative",
    seatsHeld: 15,
  },
  {
    state: "EMI",
    officeType: "commons",
    party: "uk_reform",
    seatsHeld: 2,
  },
  {
    state: "LON",
    officeType: "commons",
    party: "uk_labour",
    seatsHeld: 59,
  },
  {
    state: "LON",
    officeType: "commons",
    party: "uk_conservative",
    seatsHeld: 9,
  },
  {
    state: "LON",
    officeType: "commons",
    party: "uk_libdem",
    seatsHeld: 6,
  },
  {
    state: "NEE",
    officeType: "commons",
    party: "uk_labour",
    seatsHeld: 26,
  },
  {
    state: "NEE",
    officeType: "commons",
    party: "uk_conservative",
    seatsHeld: 1,
  },
  {
    state: "NWE",
    officeType: "commons",
    party: "uk_labour",
    seatsHeld: 65,
  },
  {
    state: "NWE",
    officeType: "commons",
    party: "uk_conservative",
    seatsHeld: 3,
  },
  {
    state: "NWE",
    officeType: "commons",
    party: "uk_libdem",
    seatsHeld: 3,
  },
  {
    state: "SEE",
    officeType: "commons",
    party: "uk_labour",
    seatsHeld: 36,
  },
  {
    state: "SEE",
    officeType: "commons",
    party: "uk_conservative",
    seatsHeld: 30,
  },
  {
    state: "SEE",
    officeType: "commons",
    party: "uk_libdem",
    seatsHeld: 24,
  },
  {
    state: "SEE",
    officeType: "commons",
    party: "uk_green",
    seatsHeld: 1,
  },
  {
    state: "SWE",
    officeType: "commons",
    party: "uk_labour",
    seatsHeld: 24,
  },
  {
    state: "SWE",
    officeType: "commons",
    party: "uk_conservative",
    seatsHeld: 11,
  },
  {
    state: "SWE",
    officeType: "commons",
    party: "uk_libdem",
    seatsHeld: 22,
  },
  {
    state: "SWE",
    officeType: "commons",
    party: "uk_green",
    seatsHeld: 1,
  },
  {
    state: "WMI",
    officeType: "commons",
    party: "uk_labour",
    seatsHeld: 38,
  },
  {
    state: "WMI",
    officeType: "commons",
    party: "uk_conservative",
    seatsHeld: 15,
  },
  {
    state: "WMI",
    officeType: "commons",
    party: "uk_libdem",
    seatsHeld: 2,
  },
  {
    state: "WMI",
    officeType: "commons",
    party: "uk_green",
    seatsHeld: 1,
  },
  {
    state: "YHU",
    officeType: "commons",
    party: "uk_labour",
    seatsHeld: 43,
  },
  {
    state: "YHU",
    officeType: "commons",
    party: "uk_conservative",
    seatsHeld: 9,
  },
  {
    state: "YHU",
    officeType: "commons",
    party: "uk_libdem",
    seatsHeld: 1,
  },
  {
    state: "EMI",
    officeType: "commons",
    party: "uk_independent",
    seatsHeld: 1,
  },
  {
    state: "LON",
    officeType: "commons",
    party: "uk_independent",
    seatsHeld: 1,
  },
  {
    state: "NWE",
    officeType: "commons",
    party: "uk_speaker",
    seatsHeld: 1,
  },
  {
    state: "NWE",
    officeType: "commons",
    party: "uk_independent",
    seatsHeld: 1,
  },
  {
    state: "WMI",
    officeType: "commons",
    party: "uk_independent",
    seatsHeld: 1,
  },
  {
    state: "YHU",
    officeType: "commons",
    party: "uk_independent",
    seatsHeld: 1,
  },
  {
    state: "SCO",
    officeType: "commons",
    party: "uk_labour",
    seatsHeld: 37,
  },
  {
    state: "SCO",
    officeType: "commons",
    party: "uk_conservative",
    seatsHeld: 5,
  },
  {
    state: "SCO",
    officeType: "commons",
    party: "uk_libdem",
    seatsHeld: 6,
  },
  {
    state: "SCO",
    officeType: "commons",
    party: "uk_snp",
    seatsHeld: 9,
  },
  {
    state: "WAL",
    officeType: "commons",
    party: "uk_labour",
    seatsHeld: 27,
  },
  {
    state: "WAL",
    officeType: "commons",
    party: "uk_libdem",
    seatsHeld: 1,
  },
  {
    state: "WAL",
    officeType: "commons",
    party: "uk_plaid",
    seatsHeld: 4,
  },
  {
    state: "NIR",
    officeType: "commons",
    party: "uk_sf",
    seatsHeld: 7,
  },
  {
    state: "NIR",
    officeType: "commons",
    party: "uk_dup",
    seatsHeld: 5,
  },
  {
    state: "NIR",
    officeType: "commons",
    party: "uk_sdlp",
    seatsHeld: 2,
  },
  {
    state: "NIR",
    officeType: "commons",
    party: "uk_alliance",
    seatsHeld: 1,
  },
  {
    state: "NIR",
    officeType: "commons",
    party: "uk_uup",
    seatsHeld: 1,
  },
  {
    state: "NIR",
    officeType: "commons",
    party: "uk_independent",
    seatsHeld: 2,
  },
];

export const DE_BUNDESTAG_2027: HistoricalSeat[] = [
  {
    state: "BW",
    officeType: "bundestag",
    party: "de_spd",
    seatsHeld: 5,
  },
  {
    state: "BY",
    officeType: "bundestag",
    party: "de_spd",
    seatsHeld: 5,
  },
  {
    state: "BE",
    officeType: "bundestag",
    party: "de_spd",
    seatsHeld: 1,
  },
  {
    state: "BB",
    officeType: "bundestag",
    party: "de_spd",
    seatsHeld: 1,
  },
  {
    state: "BRE",
    officeType: "bundestag",
    party: "de_spd",
    seatsHeld: 1,
  },
  {
    state: "HH",
    officeType: "bundestag",
    party: "de_spd",
    seatsHeld: 1,
  },
  {
    state: "HE",
    officeType: "bundestag",
    party: "de_spd",
    seatsHeld: 3,
  },
  {
    state: "MV",
    officeType: "bundestag",
    party: "de_spd",
    seatsHeld: 1,
  },
  {
    state: "NI",
    officeType: "bundestag",
    party: "de_spd",
    seatsHeld: 4,
  },
  {
    state: "NW",
    officeType: "bundestag",
    party: "de_spd",
    seatsHeld: 9,
  },
  {
    state: "RP",
    officeType: "bundestag",
    party: "de_spd",
    seatsHeld: 2,
  },
  {
    state: "SL",
    officeType: "bundestag",
    party: "de_spd",
    seatsHeld: 1,
  },
  {
    state: "SN",
    officeType: "bundestag",
    party: "de_spd",
    seatsHeld: 1,
  },
  {
    state: "ST",
    officeType: "bundestag",
    party: "de_spd",
    seatsHeld: 1,
  },
  {
    state: "SH",
    officeType: "bundestag",
    party: "de_spd",
    seatsHeld: 1,
  },
  {
    state: "TH",
    officeType: "bundestag",
    party: "de_spd",
    seatsHeld: 1,
  },
  {
    state: "BW",
    officeType: "bundestag",
    party: "de_cdu",
    seatsHeld: 9,
  },
  {
    state: "BE",
    officeType: "bundestag",
    party: "de_cdu",
    seatsHeld: 3,
  },
  {
    state: "BB",
    officeType: "bundestag",
    party: "de_cdu",
    seatsHeld: 1,
  },
  {
    state: "HH",
    officeType: "bundestag",
    party: "de_cdu",
    seatsHeld: 1,
  },
  {
    state: "HE",
    officeType: "bundestag",
    party: "de_cdu",
    seatsHeld: 5,
  },
  {
    state: "MV",
    officeType: "bundestag",
    party: "de_cdu",
    seatsHeld: 1,
  },
  {
    state: "NI",
    officeType: "bundestag",
    party: "de_cdu",
    seatsHeld: 6,
  },
  {
    state: "NW",
    officeType: "bundestag",
    party: "de_cdu",
    seatsHeld: 14,
  },
  {
    state: "RP",
    officeType: "bundestag",
    party: "de_cdu",
    seatsHeld: 4,
  },
  {
    state: "SL",
    officeType: "bundestag",
    party: "de_cdu",
    seatsHeld: 1,
  },
  {
    state: "SN",
    officeType: "bundestag",
    party: "de_cdu",
    seatsHeld: 2,
  },
  {
    state: "ST",
    officeType: "bundestag",
    party: "de_cdu",
    seatsHeld: 1,
  },
  {
    state: "SH",
    officeType: "bundestag",
    party: "de_cdu",
    seatsHeld: 3,
  },
  {
    state: "TH",
    officeType: "bundestag",
    party: "de_cdu",
    seatsHeld: 1,
  },
  {
    state: "BW",
    officeType: "bundestag",
    party: "de_greens",
    seatsHeld: 5,
  },
  {
    state: "BY",
    officeType: "bundestag",
    party: "de_greens",
    seatsHeld: 4,
  },
  {
    state: "BE",
    officeType: "bundestag",
    party: "de_greens",
    seatsHeld: 2,
  },
  {
    state: "BB",
    officeType: "bundestag",
    party: "de_greens",
    seatsHeld: 1,
  },
  {
    state: "BRE",
    officeType: "bundestag",
    party: "de_greens",
    seatsHeld: 1,
  },
  {
    state: "HH",
    officeType: "bundestag",
    party: "de_greens",
    seatsHeld: 1,
  },
  {
    state: "HE",
    officeType: "bundestag",
    party: "de_greens",
    seatsHeld: 1,
  },
  {
    state: "NI",
    officeType: "bundestag",
    party: "de_greens",
    seatsHeld: 2,
  },
  {
    state: "NW",
    officeType: "bundestag",
    party: "de_greens",
    seatsHeld: 7,
  },
  {
    state: "RP",
    officeType: "bundestag",
    party: "de_greens",
    seatsHeld: 1,
  },
  {
    state: "SN",
    officeType: "bundestag",
    party: "de_greens",
    seatsHeld: 1,
  },
  {
    state: "SH",
    officeType: "bundestag",
    party: "de_greens",
    seatsHeld: 1,
  },
  {
    state: "BW",
    officeType: "bundestag",
    party: "de_afd",
    seatsHeld: 7,
  },
  {
    state: "BY",
    officeType: "bundestag",
    party: "de_afd",
    seatsHeld: 7,
  },
  {
    state: "BE",
    officeType: "bundestag",
    party: "de_afd",
    seatsHeld: 2,
  },
  {
    state: "BB",
    officeType: "bundestag",
    party: "de_afd",
    seatsHeld: 2,
  },
  {
    state: "HE",
    officeType: "bundestag",
    party: "de_afd",
    seatsHeld: 4,
  },
  {
    state: "MV",
    officeType: "bundestag",
    party: "de_afd",
    seatsHeld: 2,
  },
  {
    state: "NI",
    officeType: "bundestag",
    party: "de_afd",
    seatsHeld: 4,
  },
  {
    state: "NW",
    officeType: "bundestag",
    party: "de_afd",
    seatsHeld: 7,
  },
  {
    state: "RP",
    officeType: "bundestag",
    party: "de_afd",
    seatsHeld: 2,
  },
  {
    state: "SN",
    officeType: "bundestag",
    party: "de_afd",
    seatsHeld: 6,
  },
  {
    state: "ST",
    officeType: "bundestag",
    party: "de_afd",
    seatsHeld: 2,
  },
  {
    state: "SH",
    officeType: "bundestag",
    party: "de_afd",
    seatsHeld: 2,
  },
  {
    state: "TH",
    officeType: "bundestag",
    party: "de_afd",
    seatsHeld: 2,
  },
  {
    state: "BY",
    officeType: "bundestag",
    party: "de_csu",
    seatsHeld: 14,
  },
  {
    state: "BW",
    officeType: "bundestag",
    party: "de_linke",
    seatsHeld: 2,
  },
  {
    state: "BE",
    officeType: "bundestag",
    party: "de_linke",
    seatsHeld: 2,
  },
  {
    state: "HE",
    officeType: "bundestag",
    party: "de_linke",
    seatsHeld: 2,
  },
  {
    state: "MV",
    officeType: "bundestag",
    party: "de_linke",
    seatsHeld: 2,
  },
  {
    state: "NI",
    officeType: "bundestag",
    party: "de_linke",
    seatsHeld: 2,
  },
  {
    state: "NW",
    officeType: "bundestag",
    party: "de_linke",
    seatsHeld: 3,
  },
  {
    state: "RP",
    officeType: "bundestag",
    party: "de_linke",
    seatsHeld: 2,
  },
  {
    state: "SN",
    officeType: "bundestag",
    party: "de_linke",
    seatsHeld: 2,
  },
  {
    state: "ST",
    officeType: "bundestag",
    party: "de_linke",
    seatsHeld: 2,
  },
  {
    state: "TH",
    officeType: "bundestag",
    party: "de_linke",
    seatsHeld: 1,
  },
  {
    state: "NW",
    officeType: "bundestag",
    party: "de_independent",
    seatsHeld: 1,
  },
];

export const JP_SHUGIIN_2027: HistoricalSeat[] = [
  {
    state: "HOK",
    officeType: "shugiin",
    party: "jp_ldp",
    seatsHeld: 7,
  },
  {
    state: "TOH",
    officeType: "shugiin",
    party: "jp_ldp",
    seatsHeld: 26,
  },
  {
    state: "KAN",
    officeType: "shugiin",
    party: "jp_ldp",
    seatsHeld: 100,
  },
  {
    state: "CHU",
    officeType: "shugiin",
    party: "jp_ldp",
    seatsHeld: 57,
  },
  {
    state: "KNS",
    officeType: "shugiin",
    party: "jp_ldp",
    seatsHeld: 49,
  },
  {
    state: "CGK",
    officeType: "shugiin",
    party: "jp_ldp",
    seatsHeld: 23,
  },
  {
    state: "SHI",
    officeType: "shugiin",
    party: "jp_ldp",
    seatsHeld: 11,
  },
  {
    state: "KYU",
    officeType: "shugiin",
    party: "jp_ldp",
    seatsHeld: 43,
  },
  {
    state: "HOK",
    officeType: "shugiin",
    party: "jp_cdp",
    seatsHeld: 2,
  },
  {
    state: "TOH",
    officeType: "shugiin",
    party: "jp_cdp",
    seatsHeld: 4,
  },
  {
    state: "KAN",
    officeType: "shugiin",
    party: "jp_cdp",
    seatsHeld: 18,
  },
  {
    state: "CHU",
    officeType: "shugiin",
    party: "jp_cdp",
    seatsHeld: 7,
  },
  {
    state: "KNS",
    officeType: "shugiin",
    party: "jp_cdp",
    seatsHeld: 7,
  },
  {
    state: "CGK",
    officeType: "shugiin",
    party: "jp_cdp",
    seatsHeld: 2,
  },
  {
    state: "SHI",
    officeType: "shugiin",
    party: "jp_cdp",
    seatsHeld: 2,
  },
  {
    state: "KYU",
    officeType: "shugiin",
    party: "jp_cdp",
    seatsHeld: 6,
  },
  {
    state: "TOH",
    officeType: "shugiin",
    party: "jp_ishin",
    seatsHeld: 3,
  },
  {
    state: "KAN",
    officeType: "shugiin",
    party: "jp_ishin",
    seatsHeld: 7,
  },
  {
    state: "CHU",
    officeType: "shugiin",
    party: "jp_ishin",
    seatsHeld: 7,
  },
  {
    state: "KNS",
    officeType: "shugiin",
    party: "jp_ishin",
    seatsHeld: 13,
  },
  {
    state: "KYU",
    officeType: "shugiin",
    party: "jp_ishin",
    seatsHeld: 6,
  },
  {
    state: "HOK",
    officeType: "shugiin",
    party: "jp_dpfp",
    seatsHeld: 1,
  },
  {
    state: "TOH",
    officeType: "shugiin",
    party: "jp_dpfp",
    seatsHeld: 3,
  },
  {
    state: "KAN",
    officeType: "shugiin",
    party: "jp_dpfp",
    seatsHeld: 10,
  },
  {
    state: "CHU",
    officeType: "shugiin",
    party: "jp_dpfp",
    seatsHeld: 6,
  },
  {
    state: "KNS",
    officeType: "shugiin",
    party: "jp_dpfp",
    seatsHeld: 3,
  },
  {
    state: "CGK",
    officeType: "shugiin",
    party: "jp_dpfp",
    seatsHeld: 1,
  },
  {
    state: "SHI",
    officeType: "shugiin",
    party: "jp_dpfp",
    seatsHeld: 1,
  },
  {
    state: "KYU",
    officeType: "shugiin",
    party: "jp_dpfp",
    seatsHeld: 3,
  },
  {
    state: "KAN",
    officeType: "shugiin",
    party: "jp_jcp",
    seatsHeld: 1,
  },
  {
    state: "CHU",
    officeType: "shugiin",
    party: "jp_jcp",
    seatsHeld: 1,
  },
  {
    state: "KNS",
    officeType: "shugiin",
    party: "jp_jcp",
    seatsHeld: 1,
  },
  {
    state: "KYU",
    officeType: "shugiin",
    party: "jp_jcp",
    seatsHeld: 1,
  },
  {
    state: "KAN",
    officeType: "shugiin",
    party: "jp_independent",
    seatsHeld: 8,
  },
  {
    state: "CHU",
    officeType: "shugiin",
    party: "jp_independent",
    seatsHeld: 4,
  },
  {
    state: "KNS",
    officeType: "shugiin",
    party: "jp_independent",
    seatsHeld: 20,
  },
  {
    state: "KYU",
    officeType: "shugiin",
    party: "jp_independent",
    seatsHeld: 1,
  },
];

export const JP_SANGIIN_2027: HistoricalSeat[] = [
  {
    state: "HOK",
    officeType: "sangiin",
    party: "jp_ldp",
    seatsHeld: 3,
  },
  {
    state: "TOH",
    officeType: "sangiin",
    party: "jp_ldp",
    seatsHeld: 9,
  },
  {
    state: "KAN",
    officeType: "sangiin",
    party: "jp_ldp",
    seatsHeld: 32,
  },
  {
    state: "CHU",
    officeType: "sangiin",
    party: "jp_ldp",
    seatsHeld: 18,
  },
  {
    state: "KNS",
    officeType: "sangiin",
    party: "jp_ldp",
    seatsHeld: 16,
  },
  {
    state: "CGK",
    officeType: "sangiin",
    party: "jp_ldp",
    seatsHeld: 7,
  },
  {
    state: "SHI",
    officeType: "sangiin",
    party: "jp_ldp",
    seatsHeld: 3,
  },
  {
    state: "KYU",
    officeType: "sangiin",
    party: "jp_ldp",
    seatsHeld: 13,
  },
  {
    state: "HOK",
    officeType: "sangiin",
    party: "jp_cdp",
    seatsHeld: 2,
  },
  {
    state: "TOH",
    officeType: "sangiin",
    party: "jp_cdp",
    seatsHeld: 5,
  },
  {
    state: "KAN",
    officeType: "sangiin",
    party: "jp_cdp",
    seatsHeld: 14,
  },
  {
    state: "CHU",
    officeType: "sangiin",
    party: "jp_cdp",
    seatsHeld: 6,
  },
  {
    state: "KNS",
    officeType: "sangiin",
    party: "jp_cdp",
    seatsHeld: 5,
  },
  {
    state: "CGK",
    officeType: "sangiin",
    party: "jp_cdp",
    seatsHeld: 2,
  },
  {
    state: "SHI",
    officeType: "sangiin",
    party: "jp_cdp",
    seatsHeld: 1,
  },
  {
    state: "KYU",
    officeType: "sangiin",
    party: "jp_cdp",
    seatsHeld: 5,
  },
  {
    state: "TOH",
    officeType: "sangiin",
    party: "jp_dpfp",
    seatsHeld: 2,
  },
  {
    state: "KAN",
    officeType: "sangiin",
    party: "jp_dpfp",
    seatsHeld: 8,
  },
  {
    state: "CHU",
    officeType: "sangiin",
    party: "jp_dpfp",
    seatsHeld: 6,
  },
  {
    state: "KNS",
    officeType: "sangiin",
    party: "jp_dpfp",
    seatsHeld: 4,
  },
  {
    state: "CGK",
    officeType: "sangiin",
    party: "jp_dpfp",
    seatsHeld: 1,
  },
  {
    state: "SHI",
    officeType: "sangiin",
    party: "jp_dpfp",
    seatsHeld: 1,
  },
  {
    state: "KYU",
    officeType: "sangiin",
    party: "jp_dpfp",
    seatsHeld: 3,
  },
  {
    state: "HOK",
    officeType: "sangiin",
    party: "jp_komeito",
    seatsHeld: 1,
  },
  {
    state: "TOH",
    officeType: "sangiin",
    party: "jp_komeito",
    seatsHeld: 1,
  },
  {
    state: "KAN",
    officeType: "sangiin",
    party: "jp_komeito",
    seatsHeld: 7,
  },
  {
    state: "CHU",
    officeType: "sangiin",
    party: "jp_komeito",
    seatsHeld: 4,
  },
  {
    state: "KNS",
    officeType: "sangiin",
    party: "jp_komeito",
    seatsHeld: 3,
  },
  {
    state: "CGK",
    officeType: "sangiin",
    party: "jp_komeito",
    seatsHeld: 1,
  },
  {
    state: "SHI",
    officeType: "sangiin",
    party: "jp_komeito",
    seatsHeld: 1,
  },
  {
    state: "KYU",
    officeType: "sangiin",
    party: "jp_komeito",
    seatsHeld: 3,
  },
  {
    state: "TOH",
    officeType: "sangiin",
    party: "jp_ishin",
    seatsHeld: 1,
  },
  {
    state: "KAN",
    officeType: "sangiin",
    party: "jp_ishin",
    seatsHeld: 7,
  },
  {
    state: "CHU",
    officeType: "sangiin",
    party: "jp_ishin",
    seatsHeld: 3,
  },
  {
    state: "KNS",
    officeType: "sangiin",
    party: "jp_ishin",
    seatsHeld: 7,
  },
  {
    state: "KYU",
    officeType: "sangiin",
    party: "jp_ishin",
    seatsHeld: 1,
  },
  {
    state: "HOK",
    officeType: "sangiin",
    party: "jp_jcp",
    seatsHeld: 1,
  },
  {
    state: "KAN",
    officeType: "sangiin",
    party: "jp_jcp",
    seatsHeld: 2,
  },
  {
    state: "CHU",
    officeType: "sangiin",
    party: "jp_jcp",
    seatsHeld: 1,
  },
  {
    state: "KNS",
    officeType: "sangiin",
    party: "jp_jcp",
    seatsHeld: 1,
  },
  {
    state: "CGK",
    officeType: "sangiin",
    party: "jp_jcp",
    seatsHeld: 1,
  },
  {
    state: "KYU",
    officeType: "sangiin",
    party: "jp_jcp",
    seatsHeld: 1,
  },
  {
    state: "KNS",
    officeType: "sangiin",
    party: "jp_sdp",
    seatsHeld: 2,
  },
  {
    state: "KAN",
    officeType: "sangiin",
    party: "jp_independent",
    seatsHeld: 6,
  },
  {
    state: "CHU",
    officeType: "sangiin",
    party: "jp_independent",
    seatsHeld: 10,
  },
  {
    state: "KNS",
    officeType: "sangiin",
    party: "jp_independent",
    seatsHeld: 13,
  },
  {
    state: "KYU",
    officeType: "sangiin",
    party: "jp_independent",
    seatsHeld: 3,
  },
];
