import type { RosterMap } from "../historicalRosters";

export const ROSTER_1991_IE: RosterMap = {
  "IE|dail|COR|ie_ff|0": {
    name: "Micheal Martin",
    birthYear: 1960,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|COR|ie_fg|0": {
    name: "Bernard Allen",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
    portraitId: "ie-bernard-allen",
  },
  "IE|dail|COR|ie_labour|0": {
    name: "Gerry O'Sullivan",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|COR|ie_pd|0": {
    name: "Mairin Quill",
    birthYear: 1940,
    gender: "female",
    ethnicity: "white",
  },
  "IE|dail|DON|ie_ff|0": {
    name: "Jim McDaid",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
    portraitId: "ie-jim-mcdaid",
  },
  "IE|dail|DON|ie_fg|0": {
    name: "Dinny McGinley",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|DON|ie_ind|0": {
    name: "Neil Blaney",
    birthYear: 1922,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|DON|ie_labour|0": {
    name: "Dick Spring",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|DON|ie_wp|0": {
    name: "Joe Sherlock",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|DUB|ie_ff|0": {
    name: "Charles Haughey",
    birthYear: 1925,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|DUB|ie_fg|0": {
    name: "Garret FitzGerald",
    birthYear: 1926,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|DUB|ie_ind|0": {
    name: "Tony Gregory",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|DUB|ie_labour|0": {
    name: "Ruairi Quinn",
    birthYear: 1946,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|DUB|ie_pd|0": {
    name: "Mary Harney",
    birthYear: 1953,
    gender: "female",
    ethnicity: "white",
  },
  "IE|dail|DUB|ie_wp|0": {
    name: "Proinsias De Rossa",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|GAL|ie_ff|0": {
    name: "Frank Fahey",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
    portraitId: "ie-frank-fahey",
  },
  "IE|dail|GAL|ie_fg|0": {
    name: "Padraic McCormack",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|GAL|ie_ind|0": {
    name: "Sean Treacy",
    birthYear: 1923,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|GAL|ie_labour|0": {
    name: "Michael D. Higgins",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|KIL|ie_ff|0": {
    name: "Brian Cowen",
    birthYear: 1960,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|KIL|ie_fg|0": {
    name: "Bernard Durkan",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
    portraitId: "ie-bernard-durkan",
  },
  "IE|dail|KIL|ie_labour|0": {
    name: "Emmet Stagg",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|KIL|ie_pd|0": {
    name: "Peadar Clohessy",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|LIM|ie_ff|0": {
    name: "Gerry Collins",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|LIM|ie_fg|0": {
    name: "Michael Noonan",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|LIM|ie_labour|0": {
    name: "Jim Kemmy",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|LIM|ie_pd|0": {
    name: "Desmond O'Malley",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|MID|ie_ff|0": {
    name: "Noel Dempsey",
    birthYear: 1953,
    gender: "male",
    ethnicity: "white",
    portraitId: "ie-noel-dempsey",
  },
  "IE|dail|MID|ie_fg|0": {
    name: "John Bruton",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|MID|ie_labour|0": {
    name: "Michael Bell",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|WEX|ie_ff|0": {
    name: "John Browne",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|WEX|ie_fg|0": {
    name: "Ivan Yates",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|WEX|ie_labour|0": {
    name: "Brendan Howlin",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|WEX|ie_pd|0": {
    name: "Pearse Wyse",
    birthYear: 1923,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|COR|ie_ff|0": {
    name: "Batt O'Keeffe",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|COR|ie_fg|0": {
    name: "Tom Raftery",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|COR|ie_labour|0": {
    name: "Brian O'Shea",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|COR|ie_pd|0": {
    name: "Martin Cullen",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|DON|ie_ff|0": {
    name: "Patrick McGowan",
    birthYear: 1926,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|DON|ie_fg|0": {
    name: "Pol O Foighil",
    birthYear: 1928,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|DON|ie_independent|0": {
    name: "Joe O'Toole",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|DON|ie_labour|0": {
    name: "John Ryan",
    birthYear: 1927,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|DUB|ie_ff|0": {
    name: "Sean Doherty",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|DUB|ie_fg|0": {
    name: "Maurice Manning",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|DUB|ie_labour|0": {
    name: "Joe Costello",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|DUB|ie_pd|0": {
    name: "Helen Keogh",
    birthYear: 1951,
    gender: "female",
    ethnicity: "white",
  },
  "IE|seanad|DUB|ie_wp|0": {
    name: "Eric Byrne",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|GAL|ie_ff|0": {
    name: "Eamon O Cuiv",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|GAL|ie_fg|0": {
    name: "Myles Staunton",
    birthYear: 1935,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|GAL|ie_pd|0": {
    name: "Bobby Molloy",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|KIL|ie_ff|0": {
    name: "Mick Lanigan",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|KIL|ie_fg|0": {
    name: "Charles McDonald",
    birthYear: 1935,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|KIL|ie_pd|0": {
    name: "John Dardis",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|LIM|ie_ff|0": {
    name: "Rory Kiely",
    birthYear: 1934,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|LIM|ie_fg|0": {
    name: "Richard Hourigan",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|LIM|ie_labour|0": {
    name: "Jack Harte",
    birthYear: 1920,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|MID|ie_ff|0": {
    name: "Donie Cassidy",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|MID|ie_fg|0": {
    name: "Liam Naughten",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|MID|ie_labour|0": {
    name: "Pat Upton",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|WEX|ie_ff|0": {
    name: "Tras Honan",
    birthYear: 1930,
    gender: "female",
    ethnicity: "white",
    portraitId: "ie-tras-honan",
  },
  "IE|seanad|WEX|ie_fg|0": {
    name: "Avril Doyle",
    birthYear: 1949,
    gender: "female",
    ethnicity: "white",
  },
  "IE|seanad|WEX|ie_pd|0": { name: "Pat Cox", birthYear: 1952, gender: "male", ethnicity: "white" },
};
