import type { RosterMap } from "../historicalRosters";

export const ROSTER_1991_JP: RosterMap = {
  "JP|governor|CGK|jp_ldp|0": {
    name: "Toranosuke Takeshita",
    birthYear: 1924,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|governor|CHU|jp_ldp|0": {
    name: "Reiji Suzuki",
    birthYear: 1928,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|governor|HOK|jp_ldp|0": {
    name: "Takahiro Yokomichi",
    birthYear: 1941,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|governor|KAN|jp_ldp|0": {
    name: "Shunichi Suzuki",
    birthYear: 1910,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|governor|KNS|jp_ldp|0": {
    name: "Toshitami Kaihara",
    birthYear: 1933,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|governor|KYU|jp_ldp|0": {
    name: "Hachiji Okuda",
    birthYear: 1920,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|governor|SHI|jp_ldp|0": {
    name: "Sadayuki Iga",
    birthYear: 1925,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|governor|TOH|jp_ldp|0": {
    name: "Shuntaro Honma",
    birthYear: 1940,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CGK|jp_dsp|0": {
    name: "Minoru Yanagida",
    birthYear: 1954,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-minoru-yanagida-1991",
  },
  "JP|regionalCouncil|CGK|jp_independent|0": {
    name: "Junji Ichii",
    birthYear: 1936,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CGK|jp_jcp|0": {
    name: "Shin'ichi Noritake",
    birthYear: 1931,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CGK|jp_jsp|0": {
    name: "Ken'ichi Yamada",
    birthYear: 1946,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CGK|jp_komeito|0": {
    name: "Kazuyoshi Endo",
    birthYear: 1943,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-kazuyoshi-endo-1991",
  },
  "JP|regionalCouncil|CGK|jp_ldp|0": {
    name: "Yūzan Fujita",
    birthYear: 1949,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CHU|jp_dsp|0": {
    name: "Eisei Itō",
    birthYear: 1941,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CHU|jp_independent|0": {
    name: "Kazunobu Takai",
    birthYear: 1940,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CHU|jp_jcp|0": {
    name: "Hiroko Hatta",
    birthYear: 1946,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CHU|jp_jsp|0": {
    name: "Toshio Inamura",
    birthYear: 1928,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CHU|jp_komeito|0": {
    name: "Yoneo Hirata",
    birthYear: 1948,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CHU|jp_ldp|0": {
    name: "Yoshio Yoshikawa",
    birthYear: 1931,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|HOK|jp_dsp|0": {
    name: "Tadamasa Kodaira",
    birthYear: 1942,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-tadamasa-kodaira-1991",
  },
  "JP|regionalCouncil|HOK|jp_independent|0": {
    name: "Yasuko Takemura",
    birthYear: 1933,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|HOK|jp_jcp|0": {
    name: "Ikuko Yamanaka",
    birthYear: 1932,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|HOK|jp_jsp|0": {
    name: "Hideko Ito",
    birthYear: 1943,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|HOK|jp_komeito|0": {
    name: "Nobuaki Futami",
    birthYear: 1935,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|HOK|jp_ldp|0": {
    name: "Muneo Suzuki",
    birthYear: 1948,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KAN|jp_dsp|0": {
    name: "Atsushi Kanda",
    birthYear: 1941,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KAN|jp_independent|0": {
    name: "Yukio Aoshima",
    birthYear: 1932,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-yukio-aoshima-1991",
  },
  "JP|regionalCouncil|KAN|jp_jcp|0": {
    name: "Sukehiro Satō",
    birthYear: 1933,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KAN|jp_jsp|0": {
    name: "Akihiro Ohata",
    birthYear: 1947,
    gender: "male",
    ethnicity: "asian",
    portraitId: "jp-akihiro-ohata",
  },
  "JP|regionalCouncil|KAN|jp_komeito|0": {
    name: "Tadao Miki",
    birthYear: 1935,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KAN|jp_ldp|0": {
    name: "Akio Kanō",
    birthYear: 1934,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KNS|jp_dsp|0": {
    name: "Kansei Nakano",
    birthYear: 1940,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-kansei-nakano-1991",
  },
  "JP|regionalCouncil|KNS|jp_independent|0": {
    name: "Kiyoshi Nishikawa",
    birthYear: 1946,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-kiyoshi-nishikawa-1991",
  },
  "JP|regionalCouncil|KNS|jp_jcp|0": {
    name: "Hidekatsu Yoshii",
    birthYear: 1942,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KNS|jp_jsp|0": {
    name: "Takumi Ueda",
    birthYear: 1938,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KNS|jp_komeito|0": {
    name: "Tetsuzo Fuyushiba",
    birthYear: 1936,
    gender: "male",
    ethnicity: "asian",
    portraitId: "jp-tetsuzo-fuyushiba",
  },
  "JP|regionalCouncil|KNS|jp_ldp|0": {
    name: "Katsuyuki Hikasa",
    birthYear: 1945,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KYU|jp_dsp|0": {
    name: "Takashi Yonezawa",
    birthYear: 1940,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-takashi-yonezawa-1991",
  },
  "JP|regionalCouncil|KYU|jp_independent|0": {
    name: "Teiko Kihira",
    birthYear: 1928,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-teiko-kihira-1991",
  },
  "JP|regionalCouncil|KYU|jp_jcp|0": {
    name: "Toshiko Hayashi",
    birthYear: 1940,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KYU|jp_jsp|0": {
    name: "Toshiko Shinozaki",
    birthYear: 1918,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KYU|jp_komeito|0": {
    name: "Yoshiharu Kuwana",
    birthYear: 1930,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KYU|jp_ldp|0": {
    name: "Takao Jinnouchi",
    birthYear: 1933,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|SHI|jp_dsp|0": {
    name: "Tokio Nakamura",
    birthYear: 1915,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|SHI|jp_independent|0": {
    name: "Osamu Ikeda",
    birthYear: 1931,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|SHI|jp_jcp|0": {
    name: "Kenjirō Yamahara",
    birthYear: 1920,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|SHI|jp_jsp|0": {
    name: "Mayumi Utsunomiya",
    birthYear: 1949,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|SHI|jp_komeito|0": {
    name: "Katsuyasu Tsunematsu",
    birthYear: 1933,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|SHI|jp_ldp|0": {
    name: "Mamoru Nishida",
    birthYear: 1928,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|TOH|jp_dsp|0": {
    name: "Akihisa Terasaki",
    birthYear: 1936,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|TOH|jp_independent|0": {
    name: "Takao Mikami",
    birthYear: 1933,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|TOH|jp_jcp|0": {
    name: "Miyako Sutō",
    birthYear: 1935,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|TOH|jp_jsp|0": {
    name: "Kazuo Kurimura",
    birthYear: 1924,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|TOH|jp_komeito|0": {
    name: "Eimatsu Takakuwa",
    birthYear: 1919,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|TOH|jp_ldp|0": {
    name: "Masamitsu Iwamoto",
    birthYear: 1929,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|CGK|jp_independent|0": {
    name: "Tatsuo Yoshida",
    birthYear: 1935,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|CGK|jp_jcp|0": {
    name: "Kenji Miyamoto",
    birthYear: 1908,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-kenji-miyamoto-1991",
  },
  "JP|sangiin|CGK|jp_jsp|0": {
    name: "Manso Hamamoto",
    birthYear: 1920,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|CGK|jp_jsp|1": {
    name: "Nobuko Mori",
    birthYear: 1932,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|sangiin|CGK|jp_komeito|0": {
    name: "Kōjin Katakami",
    birthYear: 1939,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|CGK|jp_komeito|1": {
    name: "Yoshimi Nakagawa",
    birthYear: 1933,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|CGK|jp_ldp|0": {
    name: "Hiroshi Miyazawa",
    birthYear: 1921,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|CGK|jp_ldp|1": {
    name: "Toranosuke Katayama",
    birthYear: 1935,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-toranosuke-katayama-1991",
  },
  "JP|sangiin|CHU|jp_dsp|0": {
    name: "Kei Inoue",
    birthYear: 1919,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|CHU|jp_independent|0": {
    name: "Hajime Akiyama",
    birthYear: 1931,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|CHU|jp_independent|1": {
    name: "Tasaburō Furukawa",
    birthYear: 1933,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|CHU|jp_jcp|0": {
    name: "Yoshinori Yoshioka",
    birthYear: 1928,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|CHU|jp_jcp|1": {
    name: "Shōichi Ichikawa",
    birthYear: 1923,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|CHU|jp_jsp|0": {
    name: "Sachiko Maehata",
    birthYear: 1937,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|sangiin|CHU|jp_jsp|1": {
    name: "Maki Murasawa",
    birthYear: 1924,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|sangiin|CHU|jp_komeito|0": {
    name: "Junrō Oikawa",
    birthYear: 1937,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|CHU|jp_komeito|1": {
    name: "Teiko Karita",
    birthYear: 1932,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|sangiin|CHU|jp_ldp|0": {
    name: "Hiroshi Yoshikawa",
    birthYear: 1923,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|CHU|jp_ldp|1": {
    name: "Shin'ichirō Shimojō",
    birthYear: 1920,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|HOK|jp_jcp|0": {
    name: "Yuko Takasaki",
    birthYear: 1948,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|sangiin|HOK|jp_jsp|0": {
    name: "Hisamitsu Sugano",
    birthYear: 1928,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-hisamitsu-sugano-1991",
  },
  "JP|sangiin|HOK|jp_jsp|1": {
    name: "Hisae Mitsuishi",
    birthYear: 1927,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|sangiin|HOK|jp_komeito|0": {
    name: "Tetsuzō Nakano",
    birthYear: 1927,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|HOK|jp_ldp|0": {
    name: "Shuji Kita",
    birthYear: 1925,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|HOK|jp_ldp|1": {
    name: "Tomoo Ie",
    birthYear: 1921,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KAN|jp_dsp|0": {
    name: "Kōichirō Hashimoto",
    birthYear: 1926,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KAN|jp_dsp|1": {
    name: "Kazuhito Wada",
    birthYear: 1924,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KAN|jp_independent|0": {
    name: "Chinpei Nozue",
    birthYear: 1932,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KAN|jp_independent|1": {
    name: "Yoshihiko Tsuchiya",
    birthYear: 1926,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-yoshihiko-tsuchiya-1991",
  },
  "JP|sangiin|KAN|jp_jcp|0": {
    name: "Koichiro Ueda",
    birthYear: 1927,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KAN|jp_jcp|1": {
    name: "Mitsuhiro Kaneko",
    birthYear: 1924,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KAN|jp_jsp|0": {
    name: "Keiko Chiba",
    birthYear: 1948,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|sangiin|KAN|jp_jsp|1": {
    name: "Yūbun Ueno",
    birthYear: 1927,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KAN|jp_komeito|0": {
    name: "Wakako Hironaka",
    birthYear: 1934,
    gender: "female",
    ethnicity: "asian",
    portraitId: "jp-wakako-hironaka",
  },
  "JP|sangiin|KAN|jp_komeito|1": {
    name: "Akira Kuroyanagi",
    birthYear: 1931,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KAN|jp_ldp|0": {
    name: "Bunbee Hara",
    birthYear: 1913,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KAN|jp_ldp|1": {
    name: "Kiyoko Ono",
    birthYear: 1936,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|sangiin|KNS|jp_dsp|0": {
    name: "Shigenobu Sanji",
    birthYear: 1917,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KNS|jp_independent|0": {
    name: "Kōzaburō Yamada",
    birthYear: 1917,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KNS|jp_independent|1": {
    name: "Eiichi Nakamura",
    birthYear: 1930,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-eiichi-nakamura-1991",
  },
  "JP|sangiin|KNS|jp_jcp|0": {
    name: "Takeko Kutsunugi",
    birthYear: 1922,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|sangiin|KNS|jp_jcp|1": {
    name: "Atsushi Hashimoto",
    birthYear: 1928,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KNS|jp_jsp|0": {
    name: "Takashi Tanihata",
    birthYear: 1947,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KNS|jp_jsp|1": {
    name: "Nanryō Kyokudō IV",
    birthYear: 1949,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KNS|jp_komeito|0": {
    name: "Kazuyoshi Shirahama",
    birthYear: 1947,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KNS|jp_komeito|1": {
    name: "Hideo Yahara",
    birthYear: 1930,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KNS|jp_ldp|0": {
    name: "Ichiji Ishii",
    birthYear: 1936,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KNS|jp_ldp|1": {
    name: "Masataka Sekō",
    birthYear: 1923,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KYU|jp_dsp|0": {
    name: "Hiroyuki Konishi",
    birthYear: 1936,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KYU|jp_independent|0": {
    name: "Mitsuhiro Uesugi",
    birthYear: 1942,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-mitsuhiro-uesugi-1991",
  },
  "JP|sangiin|KYU|jp_independent|1": {
    name: "Shin'ei Kyan",
    birthYear: 1912,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KYU|jp_jcp|0": {
    name: "Kazuaki Ozawa",
    birthYear: 1931,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KYU|jp_jcp|1": {
    name: "Hisashi Miura",
    birthYear: 1931,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KYU|jp_jsp|0": {
    name: "Wataru Kubo",
    birthYear: 1929,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KYU|jp_jsp|1": {
    name: "Akira Ono",
    birthYear: 1920,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KYU|jp_komeito|0": {
    name: "Kentaro Koba",
    birthYear: 1952,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KYU|jp_komeito|1": {
    name: "Tamako Nakanishi",
    birthYear: 1919,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|sangiin|KYU|jp_ldp|0": {
    name: "Kei Oma",
    birthYear: 1937,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KYU|jp_ldp|1": {
    name: "Kaname Kamada",
    birthYear: 1921,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|SHI|jp_jcp|0": {
    name: "Haruko Yoshikawa",
    birthYear: 1940,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|sangiin|SHI|jp_jsp|0": {
    name: "Jun Kioka",
    birthYear: 1952,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|SHI|jp_jsp|1": {
    name: "Ruriko Nishioka",
    birthYear: 1934,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|sangiin|SHI|jp_komeito|0": {
    name: "Keisuke Shiode",
    birthYear: 1933,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|SHI|jp_ldp|0": {
    name: "Kanzo Tanigawa",
    birthYear: 1920,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|SHI|jp_ldp|1": {
    name: "Shōhei Inoue",
    birthYear: 1929,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|TOH|jp_dsp|0": {
    name: "Kenji Katsuki",
    birthYear: 1943,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|TOH|jp_dsp|1": {
    name: "Ryōhei Adachi",
    birthYear: 1935,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|TOH|jp_jcp|0": {
    name: "Sadako Ogasawara",
    birthYear: 1920,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|sangiin|TOH|jp_jsp|0": {
    name: "Jinichi Ogawa",
    birthYear: 1918,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|TOH|jp_jsp|1": {
    name: "Chōei Aita",
    birthYear: 1928,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|TOH|jp_komeito|0": {
    name: "Atsuo Ōta",
    birthYear: 1934,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|TOH|jp_komeito|1": {
    name: "Takayoshi Wada",
    birthYear: 1919,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|TOH|jp_ldp|0": {
    name: "Teibin Suzuki",
    birthYear: 1925,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|TOH|jp_ldp|1": {
    name: "Kentaro Ishihara",
    birthYear: 1937,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CGK|jp_independent|0": {
    name: "Hisato Iwamoto",
    birthYear: 1943,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CGK|jp_jcp|0": {
    name: "Masahiro Nakaji",
    birthYear: 1926,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CGK|jp_jsp|0": {
    name: "Tadatoshi Akiba",
    birthYear: 1942,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CGK|jp_komeito|0": {
    name: "Mitsuteru Yoshii",
    birthYear: 1931,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CGK|jp_ldp|0": {
    name: "Kiichi Miyazawa",
    birthYear: 1919,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CHU|jp_dsp|0": {
    name: "Saburō Tsukamoto",
    birthYear: 1927,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CHU|jp_independent|0": {
    name: "Shozo Kusagawa",
    birthYear: 1928,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CHU|jp_jcp|0": {
    name: "Hideo Kijima",
    birthYear: 1946,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CHU|jp_jsp|0": {
    name: "Hirotaka Akamatsu",
    birthYear: 1948,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CHU|jp_komeito|0": {
    name: "Koshiro Ishida",
    birthYear: 1930,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CHU|jp_ldp|0": {
    name: "Toshiki Kaifu",
    birthYear: 1931,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|HOK|jp_independent|0": {
    name: "Yoshio Hachiro",
    birthYear: 1948,
    gender: "male",
    ethnicity: "asian",
    portraitId: "jp-yoshio-hachiro",
  },
  "JP|shugiin|HOK|jp_jcp|0": {
    name: "Kenji Kodama",
    birthYear: 1933,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-kenji-kodama-1991",
  },
  "JP|shugiin|HOK|jp_jsp|0": {
    name: "Hidenori Sasaki",
    birthYear: 1934,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|HOK|jp_komeito|0": {
    name: "Fusao Fujiwara",
    birthYear: 1929,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|HOK|jp_ldp|0": {
    name: "Nobutaka Machimura",
    birthYear: 1944,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KAN|jp_dsp|0": {
    name: "Keigo Ouchi",
    birthYear: 1930,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-keigo-ouchi-1991",
  },
  "JP|shugiin|KAN|jp_independent|0": {
    name: "Hideo Den",
    birthYear: 1923,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KAN|jp_jcp|0": {
    name: "Tetsuzo Fuwa",
    birthYear: 1930,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-tetsuzo-fuwa-1991",
  },
  "JP|shugiin|KAN|jp_jsp|0": {
    name: "Makoto Tanabe",
    birthYear: 1922,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KAN|jp_komeito|0": {
    name: "Yoshihisa Inoue",
    birthYear: 1947,
    gender: "male",
    ethnicity: "asian",
    portraitId: "jp-yoshihisa-inoue",
  },
  "JP|shugiin|KAN|jp_ldp|0": {
    name: "Junichiro Koizumi",
    birthYear: 1942,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KNS|jp_dsp|0": {
    name: "Eiichi Nagasue",
    birthYear: 1918,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-eiichi-nagasue-1991",
  },
  "JP|shugiin|KNS|jp_independent|0": {
    name: "Kohki Chuma",
    birthYear: 1936,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-kohki-chuma-1991",
  },
  "JP|shugiin|KNS|jp_jcp|0": {
    name: "Etsuko Sugano",
    birthYear: 1942,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|shugiin|KNS|jp_jsp|0": {
    name: "Takako Doi",
    birthYear: 1928,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|shugiin|KNS|jp_komeito|0": {
    name: "Junya Yano",
    birthYear: 1932,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KNS|jp_ldp|0": {
    name: "Taro Nakayama",
    birthYear: 1924,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KYU|jp_dsp|0": {
    name: "Yoshiaki Takaki",
    birthYear: 1945,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-yoshiaki-takaki-1991",
  },
  "JP|shugiin|KYU|jp_independent|0": {
    name: "Teiko Kihara",
    birthYear: 1928,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|shugiin|KYU|jp_jcp|0": {
    name: "Saneyoshi Furuken",
    birthYear: 1929,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-saneyoshi-furuken-1991",
  },
  "JP|shugiin|KYU|jp_jsp|0": {
    name: "Tomiichi Murayama",
    birthYear: 1924,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KYU|jp_komeito|0": {
    name: "Takenori Kanzaki",
    birthYear: 1943,
    gender: "male",
    ethnicity: "asian",
    portraitId: "jp-takenori-kanzaki",
  },
  "JP|shugiin|KYU|jp_ldp|0": {
    name: "Taku Yamasaki",
    birthYear: 1936,
    gender: "male",
    ethnicity: "asian",
    portraitId: "jp-taku-yamasaki",
  },
  "JP|shugiin|SHI|jp_independent|0": {
    name: "Harumi Inui",
    birthYear: 1934,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|shugiin|SHI|jp_jsp|0": {
    name: "Yoshito Sengoku",
    birthYear: 1946,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|SHI|jp_komeito|0": {
    name: "Noritoshi Ishida",
    birthYear: 1951,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|SHI|jp_ldp|0": {
    name: "Masaharu Gotoda",
    birthYear: 1914,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|TOH|jp_dsp|0": {
    name: "Kijūrō Sugahara",
    birthYear: 1926,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|TOH|jp_independent|0": {
    name: "Tatsuo Yamazaki",
    birthYear: 1922,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|TOH|jp_jcp|0": {
    name: "Kōsuke Shōji",
    birthYear: 1918,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|TOH|jp_jsp|0": {
    name: "Tomiko Okazaki",
    birthYear: 1944,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|shugiin|TOH|jp_komeito|0": {
    name: "Otohiko Endo",
    birthYear: 1947,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|TOH|jp_ldp|0": {
    name: "Ichiro Ozawa",
    birthYear: 1942,
    gender: "male",
    ethnicity: "asian",
  },
};
