import type { RosterMap } from "../historicalRosters";

export const ROSTER_1991_US: RosterMap = {
  "US|governor|AK|independent|0": {
    name: "Wally Hickel",
    birthYear: 1919,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-wally-hickel-1991",
  },
  "US|governor|AL|republican|0": {
    name: "Guy Hunt",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-guy-hunt-1991",
  },
  "US|governor|AR|democrat|0": {
    name: "Bill Clinton",
    birthYear: 1946,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-bill-clinton-1991",
  },
  "US|governor|AZ|republican|0": {
    name: "Rose Mofford",
    birthYear: 1922,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-rose-mofford-1991",
  },
  "US|governor|CA|republican|0": {
    name: "Pete Wilson",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-pete-wilson-1991",
  },
  "US|governor|CO|democrat|0": {
    name: "Roy Romer",
    birthYear: 1928,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-roy-romer-1991",
  },
  "US|governor|CT|independent|0": {
    name: "Lowell Weicker",
    birthYear: 1931,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-lowell-weicker-1991",
  },
  "US|governor|DE|republican|0": {
    name: "Mike Castle",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-mike-castle-1991",
  },
  "US|governor|FL|democrat|0": {
    name: "Lawton Chiles",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-lawton-chiles-1991",
  },
  "US|governor|GA|democrat|0": {
    name: "Zell Miller",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-zell-miller-1991",
  },
  "US|governor|HI|democrat|0": {
    name: "John Waihee",
    birthYear: 1946,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-john-waihee-1991",
  },
  "US|governor|IA|republican|0": {
    name: "Terry Branstad",
    birthYear: 1946,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-terry-branstad-1991",
  },
  "US|governor|ID|democrat|0": {
    name: "Cecil Andrus",
    birthYear: 1931,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-cecil-andrus-1991",
  },
  "US|governor|IL|republican|0": {
    name: "Jim Edgar",
    birthYear: 1946,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-jim-edgar-1991",
  },
  "US|governor|IN|democrat|0": {
    name: "Evan Bayh",
    birthYear: 1955,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-evan-bayh-1991",
  },
  "US|governor|KS|democrat|0": {
    name: "Joan Finney",
    birthYear: 1925,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-joan-finney-1991",
  },
  "US|governor|KY|democrat|0": {
    name: "Wallace Wilkinson",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-wallace-wilkinson-1991",
  },
  "US|governor|LA|democrat|0": {
    name: "Buddy Roemer",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-buddy-roemer-1991",
  },
  "US|governor|MA|republican|0": {
    name: "Bill Weld",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-bill-weld-1991",
  },
  "US|governor|MD|democrat|0": {
    name: "William Donald Schaefer",
    birthYear: 1921,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-william-donald-schaefer-1991",
  },
  "US|governor|ME|republican|0": {
    name: "John McKernan",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-john-mckernan-1991",
  },
  "US|governor|MI|republican|0": {
    name: "John Engler",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-john-engler-1991",
  },
  "US|governor|MN|republican|0": {
    name: "Arne Carlson",
    birthYear: 1934,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-arne-carlson-1991",
  },
  "US|governor|MO|republican|0": {
    name: "John Ashcroft",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-john-ashcroft-1991",
  },
  "US|governor|MS|republican|0": {
    name: "Ray Mabus",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-ray-mabus-1991",
  },
  "US|governor|MT|republican|0": {
    name: "Stan Stephens",
    birthYear: 1929,
    gender: "male",
    ethnicity: "white",
  },
  "US|governor|NC|republican|0": {
    name: "Jim Martin",
    birthYear: 1935,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-jim-martin-1991",
  },
  "US|governor|ND|democrat|0": {
    name: "George Sinner",
    birthYear: 1928,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-george-sinner-1991",
  },
  "US|governor|NE|democrat|0": {
    name: "Ben Nelson",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-ben-nelson-1991",
  },
  "US|governor|NH|republican|0": {
    name: "Judd Gregg",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-judd-gregg-1991",
  },
  "US|governor|NJ|democrat|0": {
    name: "James Florio",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-james-florio-1991",
  },
  "US|governor|NM|democrat|0": {
    name: "Bruce King",
    birthYear: 1924,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-bruce-king-1991",
  },
  "US|governor|NV|democrat|0": {
    name: "Bob Miller",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-bob-miller-1991",
  },
  "US|governor|NY|democrat|0": {
    name: "Mario Cuomo",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-mario-cuomo-1991",
  },
  "US|governor|OH|republican|0": {
    name: "George Voinovich",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-george-voinovich-1991",
  },
  "US|governor|OK|democrat|0": {
    name: "David Walters",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-david-walters-1991",
  },
  "US|governor|OR|democrat|0": {
    name: "Barbara Roberts",
    birthYear: 1936,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-barbara-roberts-1991",
  },
  "US|governor|PA|democrat|0": {
    name: "Bob Casey",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-bob-casey-1991",
  },
  "US|governor|RI|democrat|0": {
    name: "Bruce Sundlun",
    birthYear: 1920,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-bruce-sundlun-1991",
  },
  "US|governor|SC|republican|0": {
    name: "Carroll Campbell",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-carroll-campbell-1991",
  },
  "US|governor|SD|republican|0": {
    name: "George Mickelson",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-george-mickelson-1991",
  },
  "US|governor|TN|democrat|0": {
    name: "Ned McWherter",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-ned-mcwherter-1991",
  },
  "US|governor|TX|democrat|0": {
    name: "Ann Richards",
    birthYear: 1933,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-ann-richards-1991",
  },
  "US|governor|UT|republican|0": {
    name: "Norman Bangerter",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-norman-bangerter-1991",
  },
  "US|governor|VA|democrat|0": {
    name: "Douglas Wilder",
    birthYear: 1931,
    gender: "male",
    ethnicity: "black",
    portraitId: "hist-douglas-wilder-1991",
  },
  "US|governor|VT|democrat|0": {
    name: "Richard Snelling",
    birthYear: 1927,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-richard-snelling-1991",
  },
  "US|governor|WA|democrat|0": {
    name: "Booth Gardner",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-booth-gardner-1991",
  },
  "US|governor|WI|republican|0": {
    name: "Tommy Thompson",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-tommy-thompson-1991",
  },
  "US|governor|WV|democrat|0": {
    name: "Gaston Caperton",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-gaston-caperton-1991",
  },
  "US|governor|WY|democrat|0": {
    name: "Mike Sullivan",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-mike-sullivan-1991",
  },
  "US|house|AK|republican|0": {
    name: "Don Young",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|AL|democrat|0": {
    name: "Tom Bevill",
    birthYear: 1921,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|AL|republican|0": {
    name: "Bill Dickinson",
    birthYear: 1925,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|AR|democrat|0": {
    name: "Bill Alexander",
    birthYear: 1934,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|AR|republican|0": {
    name: "John Paul Hammerschmidt",
    birthYear: 1922,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|AZ|democrat|0": {
    name: "Mo Udall",
    birthYear: 1922,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|AZ|republican|0": {
    name: "Bob Stump",
    birthYear: 1927,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|CA|democrat|0": {
    name: "Don Edwards",
    birthYear: 1915,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|CA|republican|0": {
    name: "Carlos Moorhead",
    birthYear: 1922,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|CO|democrat|0": {
    name: "Pat Schroeder",
    birthYear: 1940,
    gender: "female",
    ethnicity: "white",
  },
  "US|house|CO|republican|0": {
    name: "Dan Schaefer",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|CT|democrat|0": {
    name: "Sam Gejdenson",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|CT|republican|0": {
    name: "Nancy Johnson",
    birthYear: 1935,
    gender: "female",
    ethnicity: "white",
  },
  "US|house|DE|democrat|0": {
    name: "Tom Carper",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|FL|democrat|0": {
    name: "Charles E. Bennett",
    birthYear: 1910,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|FL|republican|0": {
    name: "Bill Young",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|GA|democrat|0": {
    name: "Ed Jenkins",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|GA|republican|0": {
    name: "Newt Gingrich",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|HI|democrat|0": {
    name: "Patsy Mink",
    birthYear: 1927,
    gender: "female",
    ethnicity: "asian",
  },
  "US|house|IA|democrat|0": {
    name: "Neal Smith",
    birthYear: 1920,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|IA|republican|0": {
    name: "Jim Leach",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|ID|democrat|0": {
    name: "Richard Stallings",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|IL|democrat|0": {
    name: "Sidney Yates",
    birthYear: 1909,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|IL|republican|0": {
    name: "Bob Michel",
    birthYear: 1923,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|IN|democrat|0": {
    name: "Lee Hamilton",
    birthYear: 1931,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|IN|republican|0": {
    name: "John Myers",
    birthYear: 1927,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|KS|democrat|0": {
    name: "Dan Glickman",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|KS|republican|0": {
    name: "Pat Roberts",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|KY|democrat|0": {
    name: "William Natcher",
    birthYear: 1909,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|KY|republican|0": {
    name: "Larry Hopkins",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|LA|democrat|0": {
    name: "Jerry Huckaby",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|LA|republican|0": {
    name: "Bob Livingston",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|MA|democrat|0": {
    name: "Joe Moakley",
    birthYear: 1927,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|MD|democrat|0": {
    name: "Beverly Byron",
    birthYear: 1932,
    gender: "female",
    ethnicity: "white",
  },
  "US|house|MD|republican|0": {
    name: "Helen Delich Bentley",
    birthYear: 1923,
    gender: "female",
    ethnicity: "white",
  },
  "US|house|ME|democrat|0": {
    name: "Tom Andrews",
    birthYear: 1953,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|ME|republican|0": {
    name: "Olympia Snowe",
    birthYear: 1947,
    gender: "female",
    ethnicity: "white",
  },
  "US|house|MI|democrat|0": {
    name: "John Dingell",
    birthYear: 1926,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|MI|republican|0": {
    name: "William Broomfield",
    birthYear: 1922,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|MN|democrat|0": {
    name: "Bruce Vento",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|MN|republican|0": {
    name: "Vin Weber",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|MO|democrat|0": {
    name: "Dick Gephardt",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|MO|republican|0": {
    name: "Tom Coleman",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|MS|democrat|0": {
    name: "Jamie Whitten",
    birthYear: 1910,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|MT|democrat|0": {
    name: "Pat Williams",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|MT|republican|0": {
    name: "Ron Marlenee",
    birthYear: 1935,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|NC|democrat|0": {
    name: "Walter B. Jones Sr.",
    birthYear: 1913,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|NC|republican|0": {
    name: "Howard Coble",
    birthYear: 1931,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|ND|democrat|0": {
    name: "Byron Dorgan",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|NE|democrat|0": {
    name: "Peter Hoagland",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|NE|republican|0": {
    name: "Doug Bereuter",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|NH|democrat|0": {
    name: "Dick Swett",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|NH|republican|0": {
    name: "Bill Zeliff",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|NJ|democrat|0": {
    name: "Robert A. Roe",
    birthYear: 1924,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|NJ|republican|0": {
    name: "Matthew Rinaldo",
    birthYear: 1931,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|NM|democrat|0": {
    name: "Bill Richardson",
    birthYear: 1947,
    gender: "male",
    ethnicity: "hispanic",
  },
  "US|house|NM|republican|0": {
    name: "Joe Skeen",
    birthYear: 1927,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|NV|democrat|0": {
    name: "James Bilbray",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|NV|republican|0": {
    name: "Barbara Vucanovich",
    birthYear: 1921,
    gender: "female",
    ethnicity: "white",
  },
  "US|house|NY|democrat|0": {
    name: "Charles Rangel",
    birthYear: 1930,
    gender: "male",
    ethnicity: "black",
  },
  "US|house|NY|republican|0": {
    name: "Hamilton Fish IV",
    birthYear: 1926,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|OH|democrat|0": {
    name: "Louis Stokes",
    birthYear: 1925,
    gender: "male",
    ethnicity: "black",
  },
  "US|house|OH|republican|0": {
    name: "Clarence Miller",
    birthYear: 1917,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|OK|democrat|0": {
    name: "Glenn English",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|OK|republican|0": {
    name: "Mickey Edwards",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|OR|democrat|0": {
    name: "Les AuCoin",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|OR|republican|0": {
    name: "Robert Freeman Smith",
    birthYear: 1931,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|PA|democrat|0": {
    name: "William H. Gray III",
    birthYear: 1941,
    gender: "male",
    ethnicity: "black",
  },
  "US|house|PA|republican|0": {
    name: "Joseph McDade",
    birthYear: 1931,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|RI|democrat|0": {
    name: "Jack Reed",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|RI|republican|0": {
    name: "Ron Machtley",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|SC|democrat|0": {
    name: "Butler Derrick",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|SC|republican|0": {
    name: "Floyd Spence",
    birthYear: 1928,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|SD|democrat|0": {
    name: "Tim Johnson",
    birthYear: 1946,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|TN|democrat|0": {
    name: "Marilyn Lloyd",
    birthYear: 1929,
    gender: "female",
    ethnicity: "white",
  },
  "US|house|TN|republican|0": {
    name: "Jimmy Quillen",
    birthYear: 1916,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|TX|democrat|0": {
    name: "Jack Brooks",
    birthYear: 1922,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|TX|republican|0": {
    name: "Bill Archer",
    birthYear: 1928,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|UT|democrat|0": {
    name: "Wayne Owens",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|UT|republican|0": {
    name: "Jim Hansen",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|VA|democrat|0": {
    name: "Norman Sisisky",
    birthYear: 1927,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|VA|republican|0": {
    name: "Tom Bliley",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|VT|independent|0": {
    name: "Bernie Sanders",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
    portraitId: "bernie-sanders",
  },
  "US|house|WA|democrat|0": {
    name: "Tom Foley",
    birthYear: 1929,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|WA|republican|0": {
    name: "Sid Morrison",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|WI|democrat|0": {
    name: "David Obey",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|WI|republican|0": {
    name: "Jim Sensenbrenner",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|WV|democrat|0": {
    name: "Nick Rahall",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|WY|republican|0": {
    name: "Craig Thomas",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|AK|republican|0": {
    name: "Ted Stevens",
    birthYear: 1923,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|AK|republican|1": {
    name: "Frank Murkowski",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|AL|democrat|0": {
    name: "Howell Heflin",
    birthYear: 1921,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|AL|democrat|1": {
    name: "Richard Shelby",
    birthYear: 1934,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|AR|democrat|0": {
    name: "David Pryor",
    birthYear: 1934,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|AR|democrat|1": {
    name: "Dale Bumpers",
    birthYear: 1925,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|AZ|democrat|0": {
    name: "Dennis DeConcini",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|AZ|republican|0": {
    name: "John McCain",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|CA|democrat|0": {
    name: "Alan Cranston",
    birthYear: 1914,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|CA|republican|0": {
    name: "John Seymour",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|CO|democrat|0": {
    name: "Tim Wirth",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|CO|republican|0": {
    name: "Hank Brown",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|CT|democrat|0": {
    name: "Joe Lieberman",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|CT|democrat|1": {
    name: "Chris Dodd",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|DE|democrat|0": {
    name: "Joe Biden",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
    portraitId: "joe-biden",
  },
  "US|senate|DE|republican|0": {
    name: "William Roth",
    birthYear: 1921,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|FL|democrat|0": {
    name: "Bob Graham",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|FL|republican|0": {
    name: "Connie Mack III",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|GA|democrat|0": {
    name: "Sam Nunn",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|GA|democrat|1": {
    name: "Wyche Fowler",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|HI|democrat|0": {
    name: "Daniel Akaka",
    birthYear: 1924,
    gender: "male",
    ethnicity: "other",
  },
  "US|senate|HI|democrat|1": {
    name: "Daniel Inouye",
    birthYear: 1924,
    gender: "male",
    ethnicity: "asian",
  },
  "US|senate|IA|democrat|0": {
    name: "Tom Harkin",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|IA|republican|0": {
    name: "Chuck Grassley",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|ID|republican|0": {
    name: "Larry Craig",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|ID|republican|1": {
    name: "Steve Symms",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|IL|democrat|0": {
    name: "Paul Simon",
    birthYear: 1928,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|IL|democrat|1": {
    name: "Alan Dixon",
    birthYear: 1927,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|IN|republican|0": {
    name: "Richard Lugar",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|IN|republican|1": {
    name: "Dan Coats",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|KS|republican|0": {
    name: "Nancy Kassebaum",
    birthYear: 1932,
    gender: "female",
    ethnicity: "white",
  },
  "US|senate|KS|republican|1": {
    name: "Bob Dole",
    birthYear: 1923,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|KY|democrat|0": {
    name: "Wendell Ford",
    birthYear: 1924,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|KY|republican|0": {
    name: "Mitch McConnell",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
    portraitId: "mitch-mcconnell",
  },
  "US|senate|LA|democrat|0": {
    name: "J. Bennett Johnston",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|LA|democrat|1": {
    name: "John Breaux",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MA|democrat|0": {
    name: "Ted Kennedy",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MA|democrat|1": {
    name: "John Kerry",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MD|democrat|0": {
    name: "Paul Sarbanes",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MD|democrat|1": {
    name: "Barbara Mikulski",
    birthYear: 1936,
    gender: "female",
    ethnicity: "white",
  },
  "US|senate|ME|democrat|0": {
    name: "George Mitchell",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|ME|republican|0": {
    name: "William Cohen",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MI|democrat|0": {
    name: "Donald Riegle",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MI|democrat|1": {
    name: "Carl Levin",
    birthYear: 1934,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MN|democrat|0": {
    name: "Paul Wellstone",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MN|republican|0": {
    name: "Dave Durenberger",
    birthYear: 1934,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MO|republican|0": {
    name: "John Danforth",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MO|republican|1": {
    name: "Kit Bond",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MS|republican|0": {
    name: "Trent Lott",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MS|republican|1": {
    name: "Thad Cochran",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MT|democrat|0": {
    name: "Max Baucus",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MT|republican|0": {
    name: "Conrad Burns",
    birthYear: 1935,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NC|democrat|0": {
    name: "Terry Sanford",
    birthYear: 1917,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NC|republican|0": {
    name: "Jesse Helms",
    birthYear: 1921,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|ND|democrat|0": {
    name: "Quentin Burdick",
    birthYear: 1908,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|ND|democrat|1": {
    name: "Kent Conrad",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NE|democrat|0": {
    name: "Bob Kerrey",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NE|democrat|1": {
    name: "James Exon",
    birthYear: 1921,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NH|republican|0": {
    name: "Robert C. Smith",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NH|republican|1": {
    name: "Warren Rudman",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NJ|democrat|0": {
    name: "Frank Lautenberg",
    birthYear: 1924,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NJ|democrat|1": {
    name: "Bill Bradley",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NM|democrat|0": {
    name: "Jeff Bingaman",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NM|republican|0": {
    name: "Pete Domenici",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NV|democrat|0": {
    name: "Richard Bryan",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NV|democrat|1": {
    name: "Harry Reid",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NY|democrat|0": {
    name: "Daniel Patrick Moynihan",
    birthYear: 1927,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NY|republican|0": {
    name: "Al D'Amato",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|OH|democrat|0": {
    name: "Howard Metzenbaum",
    birthYear: 1917,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|OH|democrat|1": {
    name: "John Glenn",
    birthYear: 1921,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|OK|democrat|0": {
    name: "David Boren",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|OK|republican|0": {
    name: "Don Nickles",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|OR|republican|0": {
    name: "Mark Hatfield",
    birthYear: 1922,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|OR|republican|1": {
    name: "Bob Packwood",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|PA|republican|0": {
    name: "Harris Wofford",
    birthYear: 1926,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|PA|republican|1": {
    name: "Arlen Specter",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|RI|democrat|0": {
    name: "Claiborne Pell",
    birthYear: 1918,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|RI|republican|0": {
    name: "John Chafee",
    birthYear: 1922,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|SC|democrat|0": {
    name: "Ernest Hollings",
    birthYear: 1922,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|SC|republican|0": {
    name: "Strom Thurmond",
    birthYear: 1902,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|SD|democrat|0": {
    name: "Tom Daschle",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|SD|republican|0": {
    name: "Larry Pressler",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|TN|democrat|0": {
    name: "Jim Sasser",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|TN|democrat|1": {
    name: "Al Gore",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|TX|democrat|0": {
    name: "Lloyd Bentsen",
    birthYear: 1921,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|TX|republican|0": {
    name: "Phil Gramm",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|UT|republican|0": {
    name: "Orrin Hatch",
    birthYear: 1934,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|UT|republican|1": {
    name: "Jake Garn",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|VA|democrat|0": {
    name: "Chuck Robb",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|VA|republican|0": {
    name: "John Warner",
    birthYear: 1927,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|VT|democrat|0": {
    name: "Patrick Leahy",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|VT|republican|0": {
    name: "Jim Jeffords",
    birthYear: 1934,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|WA|democrat|0": {
    name: "Brock Adams",
    birthYear: 1927,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|WA|republican|0": {
    name: "Slade Gorton",
    birthYear: 1928,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|WI|democrat|0": {
    name: "Herb Kohl",
    birthYear: 1935,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|WI|republican|0": {
    name: "Bob Kasten",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|WV|democrat|0": {
    name: "Robert Byrd",
    birthYear: 1917,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|WV|democrat|1": {
    name: "Jay Rockefeller",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|WY|republican|0": {
    name: "Malcolm Wallop",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|WY|republican|1": {
    name: "Alan Simpson",
    birthYear: 1931,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|AK|democrat|0": {
    name: "Jay Kerttula",
    birthYear: 1928,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|AK|republican|0": {
    name: "Dick Eliason",
    birthYear: 1925,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|AL|democrat|0": {
    name: "Ryan deGraffenried Jr.",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|AL|republican|0": {
    name: "J. T. Waggoner",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|AR|democrat|0": {
    name: "Jerry Bookout",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|AR|republican|0": {
    name: "Bill Walters",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|AZ|democrat|0": {
    name: "Pete Rios",
    birthYear: 1949,
    gender: "male",
    ethnicity: "hispanic",
  },
  "US|stateSenate|AZ|republican|0": {
    name: "Bob Usdane",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|CA|democrat|0": {
    name: "David Roberti",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|CA|republican|0": {
    name: "Ken Maddy",
    birthYear: 1934,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|CO|democrat|0": {
    name: "Ted Strickland",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|CO|republican|0": {
    name: "Sam Cassidy",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|CT|democrat|0": {
    name: "John Larson",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|CT|republican|0": {
    name: "M. Adela Eads",
    birthYear: 1920,
    gender: "female",
    ethnicity: "white",
  },
  "US|stateSenate|DE|democrat|0": {
    name: "Richard S. Cordrey",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|DE|republican|0": {
    name: "Myrna Bair",
    birthYear: 1940,
    gender: "female",
    ethnicity: "white",
  },
  "US|stateSenate|FL|democrat|0": {
    name: "Gwen Margolis",
    birthYear: 1934,
    gender: "female",
    ethnicity: "white",
  },
  "US|stateSenate|FL|republican|0": {
    name: "Ander Crenshaw",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|GA|democrat|0": {
    name: "Nathan Deal",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|GA|republican|0": {
    name: "Jim Tysinger",
    birthYear: 1921,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|HI|democrat|0": {
    name: "Richard S. H. Wong",
    birthYear: 1933,
    gender: "male",
    ethnicity: "asian",
  },
  "US|stateSenate|HI|republican|0": {
    name: "Mary George",
    birthYear: 1916,
    gender: "female",
    ethnicity: "white",
  },
  "US|stateSenate|IA|democrat|0": {
    name: "Bill Hutchins",
    birthYear: 1931,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|IA|republican|0": {
    name: "Jack Rife",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|ID|democrat|0": {
    name: "Mike Burkett",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|ID|republican|0": {
    name: "Mike Crapo",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|IL|democrat|0": {
    name: "Philip Rock",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|IL|republican|0": {
    name: "Pate Philip",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|IN|democrat|0": {
    name: "Vi Simpson",
    birthYear: 1946,
    gender: "female",
    ethnicity: "white",
  },
  "US|stateSenate|IN|republican|0": {
    name: "Robert Garton",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|KS|democrat|0": {
    name: "Mike Johnston",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|KS|republican|0": {
    name: "Fred Kerr",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|KY|democrat|0": {
    name: "John 'Eck' Rose",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|KY|republican|0": {
    name: "John D. Rogers",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|LA|democrat|0": {
    name: "Sammy Nunez",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|LA|republican|0": {
    name: "Gerry Hinton",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|MA|democrat|0": {
    name: "William Bulger",
    birthYear: 1934,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|MA|republican|0": {
    name: "David H. Locke",
    birthYear: 1927,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|MD|democrat|0": {
    name: "Mike Miller",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|MD|republican|0": {
    name: "John A. Cade",
    birthYear: 1929,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|ME|democrat|0": {
    name: "Charles Pray",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|ME|republican|0": {
    name: "Pamela Cahill",
    birthYear: 1952,
    gender: "female",
    ethnicity: "white",
  },
  "US|stateSenate|MI|democrat|0": {
    name: "Dick Posthumus",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|MI|republican|0": {
    name: "John D. Cherry",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|MN|democrat|0": {
    name: "Roger Moe",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|MN|republican|0": {
    name: "Dean Johnson",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|MO|democrat|0": {
    name: "James Mathewson",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|MO|republican|0": {
    name: "John Russell",
    birthYear: 1931,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|MS|democrat|0": {
    name: "Glen Deweese",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|MS|republican|0": {
    name: "Roger Wicker",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|MT|democrat|0": {
    name: "Fred Van Valkenburg",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|MT|republican|0": {
    name: "Bruce Crippen",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|NC|democrat|0": {
    name: "Henson Barnes",
    birthYear: 1934,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|NC|republican|0": {
    name: "Robert Shaw",
    birthYear: 1924,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|ND|democrat|0": {
    name: "William S. Heigaard",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|ND|republican|0": {
    name: "Gary J. Nelson",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|NH|democrat|0": {
    name: "Beverly Hollingworth",
    birthYear: 1935,
    gender: "female",
    ethnicity: "white",
  },
  "US|stateSenate|NH|republican|0": {
    name: "Gordon Humphrey",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|NJ|democrat|0": {
    name: "John A. Lynch Jr.",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|NJ|republican|0": {
    name: "John H. Dorsey",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|NM|democrat|0": {
    name: "Manny Aragon",
    birthYear: 1947,
    gender: "male",
    ethnicity: "hispanic",
  },
  "US|stateSenate|NM|republican|0": {
    name: "Stuart Ingle",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|NV|democrat|0": {
    name: "Jack Vergiels",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|NV|republican|0": {
    name: "Bill Raggio",
    birthYear: 1926,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|NY|democrat|0": {
    name: "Manfred Ohrenstein",
    birthYear: 1925,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|NY|republican|0": {
    name: "Ralph Marino",
    birthYear: 1928,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|OH|democrat|0": {
    name: "Harry Meshel",
    birthYear: 1924,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|OH|republican|0": {
    name: "Stanley Aronoff",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|OK|democrat|0": {
    name: "Robert V. Cullison",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|OK|republican|0": {
    name: "Howard Hendrick",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|OR|democrat|0": {
    name: "John Kitzhaber",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|OR|republican|0": {
    name: "Gene Timms",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|PA|democrat|0": {
    name: "Robert Jubelirer",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|PA|republican|0": {
    name: "Robert Mellow",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|RI|democrat|0": {
    name: "Rhoda Perry",
    birthYear: 1943,
    gender: "female",
    ethnicity: "white",
  },
  "US|stateSenate|RI|republican|0": {
    name: "John Lyle",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|SC|democrat|0": {
    name: "Marshall Burns Williams",
    birthYear: 1912,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|SC|republican|0": {
    name: "Glenn McConnell",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|SD|democrat|0": {
    name: "Paul Valandra",
    birthYear: 1953,
    gender: "male",
    ethnicity: "other",
  },
  "US|stateSenate|SD|republican|0": {
    name: "Mike Rounds",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|TN|democrat|0": {
    name: "John Wilder",
    birthYear: 1921,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|TN|republican|0": {
    name: "Ben Atchley",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|TX|democrat|0": {
    name: "John Montford",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|TX|republican|0": {
    name: "Bill Ratliff",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|UT|democrat|0": {
    name: "Arnold Christensen",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|UT|republican|0": {
    name: "Karen Shepherd",
    birthYear: 1940,
    gender: "female",
    ethnicity: "white",
  },
  "US|stateSenate|VA|democrat|0": {
    name: "Stanley C. Walker",
    birthYear: 1923,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|VA|republican|0": {
    name: "John Chichester",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|VT|democrat|0": {
    name: "Doug Racine",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|VT|republican|0": {
    name: "Stephen Webster",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|WA|democrat|0": {
    name: "Sid Snyder",
    birthYear: 1926,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|WA|republican|0": {
    name: "Jeannette Hayner",
    birthYear: 1919,
    gender: "female",
    ethnicity: "white",
  },
  "US|stateSenate|WI|democrat|0": {
    name: "David Helbach",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|WI|republican|0": {
    name: "Mike Ellis",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|WV|democrat|0": {
    name: "Keith Burdette",
    birthYear: 1955,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|WV|republican|0": {
    name: "Donna Boley",
    birthYear: 1935,
    gender: "female",
    ethnicity: "white",
  },
  "US|stateSenate|WY|democrat|0": {
    name: "John Vinich",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|WY|republican|0": {
    name: "Diemer True",
    birthYear: 1946,
    gender: "male",
    ethnicity: "white",
  },
};
