import type { RosterMap } from "../historicalRosters";

export const ROSTER_1991_BR: RosterMap = {
  "BR|chamber|CENTRO_OESTE|br_other|0": {
    name: "Mauro Borges",
    birthYear: 1920,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|CENTRO_OESTE|br_pds|0": {
    name: "Maria Valadão",
    birthYear: 1931,
    gender: "female",
    ethnicity: "white",
  },
  "BR|chamber|CENTRO_OESTE|br_pdt|0": {
    name: "José Augusto Curvo",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|CENTRO_OESTE|br_pfl|0": {
    name: "Vilmar Rocha",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|CENTRO_OESTE|br_pl|0": {
    name: "Welinton Fagundes",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|CENTRO_OESTE|br_pmdb|0": {
    name: "Lúcia Vânia",
    birthYear: 1944,
    gender: "female",
    ethnicity: "white",
  },
  "BR|chamber|CENTRO_OESTE|br_prn|0": {
    name: "Paulo Octávio",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|CENTRO_OESTE|br_psb|0": {
    name: "Eurides Brito",
    birthYear: 1937,
    gender: "female",
    ethnicity: "white",
  },
  "BR|chamber|CENTRO_OESTE|br_psd|0": {
    name: "Ronaldo Caiado",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|CENTRO_OESTE|br_ptb|0": {
    name: "Nelson Trad",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|CENTRO_OESTE|br_pt|0": {
    name: "Maria Laura",
    birthYear: 1941,
    gender: "female",
    ethnicity: "white",
  },
  "BR|chamber|NORDESTE|br_other|0": {
    name: "Moroni Torgan",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|NORDESTE|br_pcdob|0": {
    name: "Haroldo Lima",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|NORDESTE|br_pds|0": {
    name: "José Lourenço",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|NORDESTE|br_pdt|0": {
    name: "Waldir Pires",
    birthYear: 1926,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|NORDESTE|br_pfl|0": {
    name: "Luís Eduardo Magalhães",
    birthYear: 1955,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|NORDESTE|br_pl|0": {
    name: "Ribeiro Tavares",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|NORDESTE|br_pmdb|0": {
    name: "Genebaldo Correia",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|NORDESTE|br_prn|0": {
    name: "Cleto Falcão",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|NORDESTE|br_psb|0": {
    name: "Miguel Arraes",
    birthYear: 1916,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|NORDESTE|br_psd|0": {
    name: "Roberto Freire",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|NORDESTE|br_ptb|0": {
    name: "Félix Mendonça",
    birthYear: 1928,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|NORDESTE|br_pt|0": {
    name: "Jaques Wagner",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|NORTE|br_other|0": {
    name: "Pauderney Avelino",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|NORTE|br_pds|0": {
    name: "Gerson Peres",
    birthYear: 1931,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|NORTE|br_pdt|0": {
    name: "Beth Azize",
    birthYear: 1940,
    gender: "female",
    ethnicity: "white",
  },
  "BR|chamber|NORTE|br_pfl|0": {
    name: "Alacid Nunes",
    birthYear: 1924,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|NORTE|br_pl|0": {
    name: "Luciano Castro",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|NORTE|br_pmdb|0": {
    name: "Eliel Rodrigues",
    birthYear: 1925,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|NORTE|br_prn|0": {
    name: "Gilvam Borges",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
    portraitId: "br-gilvam-borges",
  },
  "BR|chamber|NORTE|br_psd|0": {
    name: "Avenir Rosa",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|NORTE|br_ptb|0": {
    name: "Hilário Coimbra",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|NORTE|br_pt|0": {
    name: "Paulo Rocha",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUDESTE|br_other|0": {
    name: "Jair Bolsonaro",
    birthYear: 1955,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUDESTE|br_pcdob|0": {
    name: "Aldo Rebelo",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUDESTE|br_pds|0": {
    name: "Roberto Campos",
    birthYear: 1917,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUDESTE|br_pdt|0": {
    name: "Miro Teixeira",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
    portraitId: "br-miro-teixeira",
  },
  "BR|chamber|SUDESTE|br_pfl|0": {
    name: "Francisco Dornelles",
    birthYear: 1935,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUDESTE|br_pl|0": {
    name: "Valdemar Costa Neto",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUDESTE|br_pmdb|0": {
    name: "Ulysses Guimarães",
    birthYear: 1916,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUDESTE|br_prn|0": {
    name: "Rubem Medina",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUDESTE|br_psb|0": {
    name: "Célio de Castro",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUDESTE|br_psd|0": {
    name: "Sérgio Arouca",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUDESTE|br_ptb|0": {
    name: "Roberto Jefferson",
    birthYear: 1953,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUDESTE|br_pt|0": {
    name: "José Genoíno",
    birthYear: 1946,
    gender: "male",
    ethnicity: "white",
    portraitId: "br-jose-genoino",
  },
  "BR|chamber|SUL|br_other|0": {
    name: "Rubens Bueno",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUL|br_pcdob|0": {
    name: "Edson Menezes Silva",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUL|br_pds|0": {
    name: "Victor Faccioni",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUL|br_pdt|0": {
    name: "Carlos Cardinal",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUL|br_pfl|0": {
    name: "Reinhold Stephanes",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUL|br_pl|0": {
    name: "Jarvis Gaidzinski",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUL|br_pmdb|0": {
    name: "Antônio Britto",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
    portraitId: "br-antonio-britto",
  },
  "BR|chamber|SUL|br_prn|0": {
    name: "Carlos Roberto Massa",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUL|br_psb|0": {
    name: "Flávio Arns",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUL|br_psd|0": {
    name: "Sérgio Spada",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUL|br_ptb|0": {
    name: "Ervin Bonkoski",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "BR|chamber|SUL|br_pt|0": {
    name: "Paulo Paim",
    birthYear: 1950,
    gender: "male",
    ethnicity: "black",
  },
  "BR|senate|CENTRO_OESTE|br_other|0": {
    name: "Maurício Corrêa",
    birthYear: 1934,
    gender: "male",
    ethnicity: "white",
    portraitId: "br-mauricio-jose-correa",
  },
  "BR|senate|CENTRO_OESTE|br_pds|0": {
    name: "Levy Dias",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|CENTRO_OESTE|br_pfl|0": {
    name: "Júlio Campos",
    birthYear: 1946,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|CENTRO_OESTE|br_pmdb|0": {
    name: "Onofre Quinan",
    birthYear: 1926,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|CENTRO_OESTE|br_prn|0": {
    name: "Zé Gomes da Rocha",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|NORDESTE|br_other|0": {
    name: "Beni Veras",
    birthYear: 1935,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|NORDESTE|br_pds|0": {
    name: "Lucídio Portella",
    birthYear: 1922,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|NORDESTE|br_pdt|0": {
    name: "Lavoisier Maia",
    birthYear: 1928,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|NORDESTE|br_pfl|0": {
    name: "Marco Maciel",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|NORDESTE|br_pmdb|0": {
    name: "Garibaldi Alves Filho",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|NORDESTE|br_prn|0": {
    name: "Ney Maranhão",
    birthYear: 1927,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|NORDESTE|br_ptb|0": {
    name: "Mauro Fecury",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|NORTE|br_other|0": {
    name: "Almir Gabriel",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|NORTE|br_pdt|0": {
    name: "Raquel Cândido",
    birthYear: 1951,
    gender: "female",
    ethnicity: "white",
  },
  "BR|senate|NORTE|br_pfl|0": {
    name: "Henrique Almeida",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|NORTE|br_pmdb|0": {
    name: "José Sarney",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|NORTE|br_ptb|0": {
    name: "Marluce Pinto",
    birthYear: 1938,
    gender: "female",
    ethnicity: "white",
  },
  "BR|senate|SUDESTE|br_other|0": {
    name: "Mário Covas",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|SUDESTE|br_pdt|0": {
    name: "Darcy Ribeiro",
    birthYear: 1922,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|SUDESTE|br_pfl|0": {
    name: "Élcio Álvares",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|SUDESTE|br_pmdb|0": {
    name: "Ronan Tito",
    birthYear: 1931,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|SUDESTE|br_prn|0": {
    name: "Júnia Marise",
    birthYear: 1945,
    gender: "female",
    ethnicity: "white",
  },
  "BR|senate|SUDESTE|br_pt|0": {
    name: "Eduardo Suplicy",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|SUL|br_pds|0": {
    name: "Esperidião Amin",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|SUL|br_pdt|0": {
    name: "Amaury Müller",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|SUL|br_pmdb|0": {
    name: "Pedro Simon",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
  },
  "BR|senate|SUL|br_ptb|0": {
    name: "Eduardo Andrade Vieira",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
  },
};
