import type { RosterMap } from "../historicalRosters";

export const ROSTER_1991_DE: RosterMap = {
  "DE|bundestag|BB|de_cdu|0": {
    name: "Lothar de Maizière",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BB|de_fdp|0": {
    name: "Jürgen Türk",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BB|de_greens|0": {
    name: "Konrad Weiß",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BB|de_pds|0": {
    name: "Dietmar Keller",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BB|de_spd|0": {
    name: "Markus Meckel",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BE|de_cdu|0": {
    name: "Sabine Bergmann-Pohl",
    birthYear: 1946,
    gender: "female",
    ethnicity: "white",
  },
  "DE|bundestag|BE|de_fdp|0": {
    name: "Wolfgang Lüder",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BE|de_greens|0": {
    name: "Gerd Poppe",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BE|de_pds|0": {
    name: "Gregor Gysi",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BE|de_spd|0": {
    name: "Wolfgang Thierse",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BRE|de_cdu|0": {
    name: "Bernd Neumann",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BRE|de_fdp|0": {
    name: "Manfred Richter",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BRE|de_spd|0": {
    name: "Hans Koschnick",
    birthYear: 1929,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BW|de_cdu|0": {
    name: "Wolfgang Schäuble",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BW|de_fdp|0": {
    name: "Helmut Haussmann",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BW|de_greens|0": {
    name: "Winfried Kretschmann",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BW|de_spd|0": {
    name: "Gert Weisskirchen",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BY|de_csu|0": {
    name: "Theo Waigel",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BY|de_fdp|0": {
    name: "Sabine Leutheusser-Schnarrenberger",
    birthYear: 1951,
    gender: "female",
    ethnicity: "white",
  },
  "DE|bundestag|BY|de_spd|0": {
    name: "Renate Schmidt",
    birthYear: 1943,
    gender: "female",
    ethnicity: "white",
  },
  "DE|bundestag|HE|de_cdu|0": {
    name: "Friedrich Bohl",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|HE|de_fdp|0": {
    name: "Hermann Otto Solms",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|HE|de_spd|0": {
    name: "Heidemarie Wieczorek-Zeul",
    birthYear: 1942,
    gender: "female",
    ethnicity: "white",
  },
  "DE|bundestag|HH|de_cdu|0": {
    name: "Volker Rühe",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|HH|de_fdp|0": {
    name: "Rainer Funke",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|HH|de_spd|0": {
    name: "Hans-Ulrich Klose",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|MV|de_cdu|0": {
    name: "Angela Merkel",
    birthYear: 1954,
    gender: "female",
    ethnicity: "white",
  },
  "DE|bundestag|MV|de_fdp|0": {
    name: "Rainer Ortleb",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|MV|de_greens|0": {
    name: "Klaus-Dieter Feige",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|MV|de_pds|0": {
    name: "Hans Modrow",
    birthYear: 1928,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|MV|de_spd|0": {
    name: "Hans-Joachim Hacker",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|NI|de_cdu|0": {
    name: "Rudolf Seiters",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|NI|de_fdp|0": {
    name: "Detlef Kleinert",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|NI|de_spd|0": {
    name: "Arne Börnsen",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|NW|de_cdu|0": {
    name: "Norbert Blüm",
    birthYear: 1935,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|NW|de_fdp|0": {
    name: "Jürgen Möllemann",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|NW|de_pds|0": {
    name: "Ulla Jelpke",
    birthYear: 1951,
    gender: "female",
    ethnicity: "white",
  },
  "DE|bundestag|NW|de_spd|0": {
    name: "Franz Müntefering",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|RP|de_cdu|0": {
    name: "Helmut Kohl",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|RP|de_fdp|0": {
    name: "Dieter Thomae",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|RP|de_spd|0": {
    name: "Eckhart Pick",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|SH|de_cdu|0": {
    name: "Gerhard Stoltenberg",
    birthYear: 1928,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|SH|de_fdp|0": {
    name: "Wolfgang Kubicki",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|SH|de_spd|0": {
    name: "Norbert Gansel",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|SL|de_cdu|0": {
    name: "Klaus Töpfer",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|SL|de_fdp|0": {
    name: "Uta Würfel",
    birthYear: 1944,
    gender: "female",
    ethnicity: "white",
  },
  "DE|bundestag|SL|de_spd|0": {
    name: "Ottmar Schreiner",
    birthYear: 1946,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|SN|de_cdu|0": {
    name: "Michael Luther",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|SN|de_fdp|0": {
    name: "Wolfgang Mischnick",
    birthYear: 1921,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|SN|de_greens|0": {
    name: "Werner Schulz",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|SN|de_pds|0": {
    name: "Barbara Höll",
    birthYear: 1957,
    gender: "female",
    ethnicity: "white",
  },
  "DE|bundestag|SN|de_spd|0": {
    name: "Rolf Schwanitz",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|ST|de_cdu|0": {
    name: "Clemens Schwalbe",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|ST|de_fdp|0": {
    name: "Uwe Lühr",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|ST|de_greens|0": {
    name: "Ingrid Köppe",
    birthYear: 1958,
    gender: "female",
    ethnicity: "white",
  },
  "DE|bundestag|ST|de_pds|0": {
    name: "Bernd Henn",
    birthYear: 1946,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|ST|de_spd|0": {
    name: "Uwe Küster",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|TH|de_cdu|0": {
    name: "Harald Kahl",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|TH|de_fdp|0": {
    name: "Karlheinz Guttmacher",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|TH|de_greens|0": {
    name: "Vera Wollenberger",
    birthYear: 1952,
    gender: "female",
    ethnicity: "white",
  },
  "DE|bundestag|TH|de_pds|0": {
    name: "Ruth Fuchs",
    birthYear: 1946,
    gender: "female",
    ethnicity: "white",
  },
  "DE|bundestag|TH|de_spd|0": {
    name: "Christoph Matschie",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BB|de_cdu|0": {
    name: "Peter Wagner",
    birthYear: 1946,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BB|de_fdp|0": {
    name: "Rainer Siebert",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BB|de_greens|0": {
    name: "Günter Nooke",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BB|de_pds|0": {
    name: "Lothar Bisky",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BB|de_spd|0": {
    name: "Herbert Knoblich",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BE|de_cdu|0": {
    name: "Hanna-Renate Laurien",
    birthYear: 1928,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|BE|de_fdp|0": {
    name: "Carola von Braun",
    birthYear: 1942,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|BE|de_greens|0": {
    name: "Renate Künast",
    birthYear: 1955,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|BE|de_pds|0": {
    name: "Harald Wolf",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BE|de_spd|0": {
    name: "Walter Momper",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BRE|de_cdu|0": {
    name: "Ulrich Nölle",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BRE|de_fdp|0": {
    name: "Axel Adamietz",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BRE|de_greens|0": {
    name: "Ralf Fücks",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BRE|de_spd|0": {
    name: "Dieter Klink",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BW|de_cdu|0": {
    name: "Gerhard Mayer-Vorfelder",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BW|de_fdp|0": {
    name: "Walter Döring",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BW|de_greens|0": {
    name: "Birgitt Bender",
    birthYear: 1956,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|BW|de_spd|0": {
    name: "Dieter Spöri",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BY|de_csu|0": {
    name: "Otto Wiesheu",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BY|de_greens|0": {
    name: "Sepp Daxenberger",
    birthYear: 1962,
    gender: "male",
    ethnicity: "white",
    portraitId: "de-sepp-daxenberger",
  },
  "DE|landtag|BY|de_spd|0": {
    name: "Karl-Heinz Hiersemann",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HE|de_cdu|0": {
    name: "Manfred Kanther",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HE|de_fdp|0": {
    name: "Wolfgang Gerhardt",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HE|de_greens|0": {
    name: "Joschka Fischer",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HE|de_spd|0": {
    name: "Ernst Welteke",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HH|de_cdu|0": {
    name: "Hartmut Perschau",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HH|de_fdp|0": {
    name: "Reinhard Soltau",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HH|de_greens|0": {
    name: "Krista Sager",
    birthYear: 1953,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|HH|de_independent|0": {
    name: "Jürgen Warmke",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HH|de_spd|0": {
    name: "Elisabeth Kiausch",
    birthYear: 1933,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|MV|de_cdu|0": {
    name: "Alfred Gomolka",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|MV|de_fdp|0": {
    name: "Walter Goldbeck",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|MV|de_greens|0": {
    name: "Harald Terpe",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|MV|de_pds|0": {
    name: "Helmut Holter",
    birthYear: 1953,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|MV|de_spd|0": {
    name: "Harald Ringstorff",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|NI|de_cdu|0": {
    name: "Jürgen Gansäuer",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|NI|de_greens|0": {
    name: "Thea Dückert",
    birthYear: 1950,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|NI|de_spd|0": {
    name: "Gerhard Glogowski",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|NW|de_cdu|0": {
    name: "Helmut Linssen",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|NW|de_fdp|0": {
    name: "Achim Rohde",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|NW|de_spd|0": {
    name: "Friedhelm Farthmann",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|RP|de_cdu|0": {
    name: "Carl-Ludwig Wagner",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|RP|de_fdp|0": {
    name: "Rainer Brüderle",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|RP|de_greens|0": {
    name: "Friedel Grützmacher",
    birthYear: 1942,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|RP|de_independent|0": {
    name: "Christoph Grimm",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|RP|de_spd|0": {
    name: "Kurt Beck",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SH|de_cdu|0": {
    name: "Heiko Hoffmann",
    birthYear: 1935,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SH|de_independent|0": {
    name: "Karl Otto Meyer",
    birthYear: 1928,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SH|de_spd|0": {
    name: "Gert Börnsen",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SL|de_cdu|0": {
    name: "Peter Müller",
    birthYear: 1955,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SL|de_fdp|0": {
    name: "Werner Klumpp",
    birthYear: 1928,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SL|de_spd|0": {
    name: "Reinhard Klimmt",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SN|de_cdu|0": {
    name: "Fritz Hähle",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SN|de_fdp|0": {
    name: "Axel Viehweger",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SN|de_greens|0": {
    name: "Martin Böttger",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SN|de_pds|0": {
    name: "Peter Porsch",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SN|de_spd|0": {
    name: "Karl-Heinz Kunckel",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|ST|de_cdu|0": {
    name: "Christoph Bergner",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|ST|de_fdp|0": {
    name: "Gerry Kley",
    birthYear: 1960,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|ST|de_greens|0": {
    name: "Hans-Jochen Tschiche",
    birthYear: 1929,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|ST|de_pds|0": {
    name: "Roland Claus",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|ST|de_spd|0": {
    name: "Reinhard Höppner",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|TH|de_cdu|0": {
    name: "Josef Duchač",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|TH|de_fdp|0": {
    name: "Andreas Kniepert",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|TH|de_greens|0": {
    name: "Christine Grabe",
    birthYear: 1948,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|TH|de_pds|0": {
    name: "Klaus Höpcke",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|TH|de_spd|0": {
    name: "Gerd Schuchardt",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
  },
  "DE|ministerPresident|BB|de_spd|0": {
    name: "Manfred Stolpe",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-manfred-stolpe-1991",
  },
  "DE|ministerPresident|BE|de_cdu|0": {
    name: "Eberhard Diepgen",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-eberhard-diepgen-1991",
  },
  "DE|ministerPresident|BRE|de_spd|0": {
    name: "Klaus Wedemeier",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-klaus-wedemeier-1991",
  },
  "DE|ministerPresident|BW|de_cdu|0": {
    name: "Erwin Teufel",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-erwin-teufel-1991",
  },
  "DE|ministerPresident|BY|de_csu|0": {
    name: "Max Streibl",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-max-streibl-1991",
  },
  "DE|ministerPresident|HE|de_spd|0": {
    name: "Hans Eichel",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-hans-eichel-1991",
  },
  "DE|ministerPresident|HH|de_spd|0": {
    name: "Henning Voscherau",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-henning-voscherau-1991",
  },
  "DE|ministerPresident|MV|de_cdu|0": {
    name: "Berndt Seite",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-berndt-seite-1991",
  },
  "DE|ministerPresident|NI|de_spd|0": {
    name: "Gerhard Schröder",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-gerhard-schr-der-1991",
  },
  "DE|ministerPresident|NW|de_spd|0": {
    name: "Johannes Rau",
    birthYear: 1931,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-johannes-rau-1991",
  },
  "DE|ministerPresident|RP|de_spd|0": {
    name: "Rudolf Scharping",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-rudolf-scharping-1991",
  },
  "DE|ministerPresident|SH|de_spd|0": {
    name: "Björn Engholm",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-bj-rn-engholm-1991",
  },
  "DE|ministerPresident|SL|de_spd|0": {
    name: "Oskar Lafontaine",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-oskar-lafontaine-1991",
  },
  "DE|ministerPresident|SN|de_cdu|0": {
    name: "Kurt Biedenkopf",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-kurt-biedenkopf-1991",
  },
  "DE|ministerPresident|ST|de_cdu|0": {
    name: "Gerd Gies",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-gerd-gies-1991",
  },
  "DE|ministerPresident|TH|de_cdu|0": {
    name: "Bernhard Vogel",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-bernhard-vogel-1991",
  },
};
