import type { RosterMap } from "../historicalRosters";

export const ROSTER_1991_UK: RosterMap = {
  "UK|commons|EAE|uk_conservative|0": {
    name: "John Major",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
    portraitId: "john-major",
  },
  "UK|commons|EAE|uk_labour|0": {
    name: "John Garrett",
    birthYear: 1931,
    gender: "male",
    ethnicity: "white",
  },
  "UK|commons|EMI|uk_conservative|0": {
    name: "Kenneth Clarke",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-kenneth-clarke-1991",
  },
  "UK|commons|EMI|uk_labour|0": {
    name: "Margaret Beckett",
    birthYear: 1943,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-margaret-beckett-1991",
  },
  "UK|commons|LON|uk_conservative|0": {
    name: "Michael Portillo",
    birthYear: 1953,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-michael-portillo-1991",
  },
  "UK|commons|LON|uk_labour|0": {
    name: "Harriet Harman",
    birthYear: 1950,
    gender: "female",
    ethnicity: "white",
    portraitId: "harriet-harman",
  },
  "UK|commons|LON|uk_libdem|0": {
    name: "Simon Hughes",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-simon-hughes-1991",
  },
  "UK|commons|NEE|uk_conservative|0": {
    name: "Neville Trotter",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
  },
  "UK|commons|NEE|uk_labour|0": {
    name: "Tony Blair",
    birthYear: 1953,
    gender: "male",
    ethnicity: "white",
    portraitId: "tony-blair",
  },
  "UK|commons|NEE|uk_libdem|0": {
    name: "Alan Beith",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-alan-beith-1991",
  },
  "UK|commons|NIR|uk_dup|0": {
    name: "Ian Paisley",
    birthYear: 1926,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-ian-paisley-1991",
  },
  "UK|commons|NIR|uk_independent|0": {
    name: "James Kilfedder",
    birthYear: 1928,
    gender: "male",
    ethnicity: "white",
  },
  "UK|commons|NIR|uk_sdlp|0": {
    name: "John Hume",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-john-hume-1991",
  },
  "UK|commons|NIR|uk_uup|0": {
    name: "James Molyneaux",
    birthYear: 1920,
    gender: "male",
    ethnicity: "white",
  },
  "UK|commons|NWE|uk_conservative|0": {
    name: "David Hunt",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-david-hunt-1991",
  },
  "UK|commons|NWE|uk_labour|0": {
    name: "Jack Straw",
    birthYear: 1946,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-jack-straw-1991",
  },
  "UK|commons|NWE|uk_libdem|0": {
    name: "David Alton",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-david-alton-1991",
  },
  "UK|commons|SCO|uk_conservative|0": {
    name: "Malcolm Rifkind",
    birthYear: 1946,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-malcolm-rifkind-1991",
  },
  "UK|commons|SCO|uk_labour|0": {
    name: "John Smith",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-john-smith-1991",
  },
  "UK|commons|SCO|uk_libdem|0": {
    name: "Menzies Campbell",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-menzies-campbell-1991",
  },
  "UK|commons|SCO|uk_snp|0": {
    name: "Alex Salmond",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
    portraitId: "alex-salmond",
  },
  "UK|commons|SEE|uk_conservative|0": {
    name: "Douglas Hurd",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-douglas-hurd-1991",
  },
  "UK|commons|SEE|uk_labour|0": {
    name: "Andrew Smith",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-andrew-smith-1991",
  },
  "UK|commons|SWE|uk_conservative|0": {
    name: "Tom King",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-tom-king-1991",
  },
  "UK|commons|SWE|uk_labour|0": {
    name: "Dawn Primarolo",
    birthYear: 1954,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-dawn-primarolo-1991",
  },
  "UK|commons|SWE|uk_libdem|0": {
    name: "Paddy Ashdown",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-paddy-ashdown-1991",
  },
  "UK|commons|WAL|uk_conservative|0": {
    name: "Wyn Roberts",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
  },
  "UK|commons|WAL|uk_labour|0": {
    name: "Neil Kinnock",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
    portraitId: "neil-kinnock",
  },
  "UK|commons|WAL|uk_libdem|0": {
    name: "Alex Carlile",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-alex-carlile-1991",
  },
  "UK|commons|WAL|uk_plaid|0": {
    name: "Dafydd Wigley",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-dafydd-wigley-1991",
  },
  "UK|commons|WMI|uk_conservative|0": {
    name: "Norman Fowler",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-norman-fowler-1991",
  },
  "UK|commons|WMI|uk_labour|0": {
    name: "Roy Hattersley",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-roy-hattersley-1991",
  },
  "UK|commons|YHU|uk_conservative|0": {
    name: "William Hague",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
    portraitId: "william-hague",
  },
  "UK|commons|YHU|uk_labour|0": {
    name: "John Prescott",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-john-prescott-1991",
  },
  "UK|governor|LON|uk_labour|0": {
    name: "Brian Jenkins",
    birthYear: 1935,
    gender: "male",
    ethnicity: "white",
  },
  "UK|governor|NIR|uk_uup|0": {
    name: "Patrick Mayhew",
    birthYear: 1929,
    gender: "male",
    ethnicity: "white",
  },
  "UK|governor|SCO|uk_labour|0": {
    name: "Ian Lang",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-ian-lang-1991",
  },
  "UK|governor|WAL|uk_labour|0": {
    name: "Ann Clwyd",
    birthYear: 1937,
    gender: "female",
    ethnicity: "white",
  },
  "UK|regionalCouncil|EAE|uk_conservative|0": {
    name: "Gillian Shephard",
    birthYear: 1940,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-gillian-shephard-1991",
  },
  "UK|regionalCouncil|EAE|uk_labour|0": {
    name: "Anne Campbell",
    birthYear: 1940,
    gender: "female",
    ethnicity: "white",
  },
  "UK|regionalCouncil|EAE|uk_libdem|0": {
    name: "Ros Scott",
    birthYear: 1957,
    gender: "female",
    ethnicity: "white",
  },
  "UK|regionalCouncil|EMI|uk_conservative|0": {
    name: "Edward Leigh",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-edward-leigh-1991",
  },
  "UK|regionalCouncil|EMI|uk_labour|0": {
    name: "Dennis Skinner",
    birthYear: 1932,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-dennis-skinner-1991",
  },
  "UK|regionalCouncil|EMI|uk_libdem|0": {
    name: "Paul Holmes",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-paul-holmes-1991",
  },
  "UK|regionalCouncil|LON|uk_conservative|0": {
    name: "David Mellor",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-david-mellor-1991",
  },
  "UK|regionalCouncil|LON|uk_labour|0": {
    name: "Diane Abbott",
    birthYear: 1953,
    gender: "female",
    ethnicity: "black",
    portraitId: "diane-abbott",
  },
  "UK|regionalCouncil|LON|uk_libdem|0": {
    name: "Graham Tope",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-graham-tope-1991",
  },
  "UK|regionalCouncil|NEE|uk_conservative|0": {
    name: "Tim Devlin",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
  },
  "UK|regionalCouncil|NEE|uk_labour|0": {
    name: "Peter Mandelson",
    birthYear: 1953,
    gender: "male",
    ethnicity: "white",
    portraitId: "peter-mandelson",
  },
  "UK|regionalCouncil|NIR|uk_alliance|0": {
    name: "Kieran McCarthy",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-kieran-mccarthy-1991",
  },
  "UK|regionalCouncil|NIR|uk_dup|0": {
    name: "Peter Robinson",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-peter-robinson-1991",
  },
  "UK|regionalCouncil|NIR|uk_independent|0": {
    name: "Gerry Fitt",
    birthYear: 1926,
    gender: "male",
    ethnicity: "white",
  },
  "UK|regionalCouncil|NIR|uk_sdlp|0": {
    name: "Seamus Mallon",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-seamus-mallon-1991",
  },
  "UK|regionalCouncil|NIR|uk_sf|0": {
    name: "Gerry Adams",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-gerry-adams-1991",
  },
  "UK|regionalCouncil|NIR|uk_uup|0": {
    name: "David Trimble",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-david-trimble-1991",
  },
  "UK|regionalCouncil|NWE|uk_conservative|0": {
    name: "Winston Churchill",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-winston-churchill-1991",
  },
  "UK|regionalCouncil|NWE|uk_labour|0": {
    name: "Gerald Kaufman",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-gerald-kaufman-1991",
  },
  "UK|regionalCouncil|NWE|uk_libdem|0": {
    name: "Mike Storey",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-mike-storey-1991",
  },
  "UK|regionalCouncil|SCO|uk_conservative|0": {
    name: "Michael Forsyth",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-michael-forsyth-1991",
  },
  "UK|regionalCouncil|SCO|uk_independent|0": {
    name: "John Farquhar Munro",
    birthYear: 1934,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-john-farquhar-munro-1991",
  },
  "UK|regionalCouncil|SCO|uk_labour|0": {
    name: "Gordon Brown",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
    portraitId: "gordon-brown",
  },
  "UK|regionalCouncil|SCO|uk_libdem|0": {
    name: "Charles Kennedy",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-charles-kennedy-1991",
  },
  "UK|regionalCouncil|SCO|uk_snp|0": {
    name: "Margaret Ewing",
    birthYear: 1945,
    gender: "female",
    ethnicity: "white",
  },
  "UK|regionalCouncil|SEE|uk_conservative|0": {
    name: "Michael Howard",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
    portraitId: "michael-howard",
  },
  "UK|regionalCouncil|SEE|uk_labour|0": {
    name: "John Denham",
    birthYear: 1953,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-john-denham-1991",
  },
  "UK|regionalCouncil|SEE|uk_libdem|0": {
    name: "Norman Baker",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-norman-baker-1991",
  },
  "UK|regionalCouncil|SWE|uk_conservative|0": {
    name: "David Heathcoat-Amory",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-david-heathcoat-amory-1991",
  },
  "UK|regionalCouncil|SWE|uk_labour|0": {
    name: "David Jamieson",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "UK|regionalCouncil|SWE|uk_libdem|0": {
    name: "Matthew Taylor",
    birthYear: 1963,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-matthew-taylor-1991",
  },
  "UK|regionalCouncil|WAL|uk_conservative|0": {
    name: "Gwilym Jones",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "UK|regionalCouncil|WAL|uk_independent|0": {
    name: "George Thomas",
    birthYear: 1909,
    gender: "male",
    ethnicity: "white",
  },
  "UK|regionalCouncil|WAL|uk_labour|0": {
    name: "Alan Williams",
    birthYear: 1930,
    gender: "male",
    ethnicity: "white",
  },
  "UK|regionalCouncil|WAL|uk_libdem|0": {
    name: "Jenny Randerson",
    birthYear: 1948,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-jenny-randerson-1991",
  },
  "UK|regionalCouncil|WAL|uk_plaid|0": {
    name: "Ieuan Wyn Jones",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-ieuan-wyn-jones-1991",
  },
  "UK|regionalCouncil|WMI|uk_conservative|0": {
    name: "Jill Knight",
    birthYear: 1923,
    gender: "female",
    ethnicity: "white",
  },
  "UK|regionalCouncil|WMI|uk_labour|0": {
    name: "Clare Short",
    birthYear: 1946,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-clare-short-1991",
  },
  "UK|regionalCouncil|WMI|uk_libdem|0": {
    name: "John Hemming",
    birthYear: 1960,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-john-hemming-1991",
  },
  "UK|regionalCouncil|YHU|uk_conservative|0": {
    name: "Elizabeth Peacock",
    birthYear: 1937,
    gender: "female",
    ethnicity: "white",
  },
  "UK|regionalCouncil|YHU|uk_labour|0": {
    name: "David Blunkett",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-david-blunkett-1991",
  },
  "UK|regionalCouncil|YHU|uk_libdem|0": {
    name: "David Shutt",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-david-shutt-1991",
  },
};
