import type { RosterMap } from "../historicalRosters";

export const ROSTER_1991_CN: RosterMap = {
  "CN|governor|DB|cn_ccp|0": {
    name: "Yue Qifeng",
    birthYear: 1931,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|governor|HB|cn_ccp|0": {
    name: "Cheng Weigao",
    birthYear: 1933,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|governor|HD|cn_ccp|0": {
    name: "Huang Ju",
    birthYear: 1938,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-huang-ju-1991",
  },
  "CN|governor|HN|cn_ccp|0": {
    name: "Zhu Senlin",
    birthYear: 1930,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|governor|HZ|cn_ccp|0": {
    name: "Li Changchun",
    birthYear: 1944,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-li-changchun-1991",
  },
  "CN|governor|XB|cn_ccp|0": {
    name: "Tömür Dawamat",
    birthYear: 1927,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-t-m-r-dawamat-1991",
  },
  "CN|governor|XN|cn_ccp|0": {
    name: "Zhang Haoruo",
    birthYear: 1932,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|DB|cn_ccp|0": {
    name: "Quan Shuren",
    birthYear: 1930,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|DB|cn_ccp|1": {
    name: "Li Tieying",
    birthYear: 1936,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|DB|cn_ccp|2": {
    name: "He Zhukang",
    birthYear: 1932,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|DB|cn_ccp|3": {
    name: "Wang Zhongyu",
    birthYear: 1933,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|DB|cn_ccp|4": {
    name: "Sun Weiben",
    birthYear: 1928,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|DB|cn_ccp|5": {
    name: "Shao Qihui",
    birthYear: 1934,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|DB|cn_ccp|6": {
    name: "Li Guixian",
    birthYear: 1937,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|DB|cn_cdl|0": {
    name: "Ding Shisun",
    birthYear: 1927,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|DB|cn_cndca|0": {
    name: "Bai Dahua",
    birthYear: 1942,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HB|cn_ccp|0": {
    name: "Li Ximing",
    birthYear: 1926,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HB|cn_ccp|1": {
    name: "Chen Xitong",
    birthYear: 1930,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HB|cn_ccp|2": {
    name: "Tan Shaowen",
    birthYear: 1929,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HB|cn_ccp|3": {
    name: "Nie Bichu",
    birthYear: 1928,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HB|cn_ccp|4": {
    name: "Xing Chongzhi",
    birthYear: 1927,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HB|cn_ccp|5": {
    name: "Gao Yang",
    birthYear: 1909,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HB|cn_ccp|6": {
    name: "Hao Jianxiu",
    birthYear: 1935,
    gender: "female",
    ethnicity: "asian",
    portraitId: "cn-hao-jianxiu",
  },
  "CN|npcDelegate|HB|cn_cdl|0": {
    name: "Lei Jieqiong",
    birthYear: 1905,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HB|cn_cndca|0": {
    name: "Wan Guoquan",
    birthYear: 1919,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HD|cn_ccp|0": {
    name: "Jiang Zemin",
    birthYear: 1926,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HD|cn_ccp|1": {
    name: "Zhu Rongji",
    birthYear: 1928,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HD|cn_ccp|2": {
    name: "Rui Xingwen",
    birthYear: 1927,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HD|cn_ccp|3": {
    name: "Wu Bangguo",
    birthYear: 1941,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HD|cn_ccp|4": {
    name: "Chen Huanyou",
    birthYear: 1934,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HD|cn_ccp|5": {
    name: "Shen Daren",
    birthYear: 1928,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HD|cn_ccp|6": {
    name: "Jiang Chunyun",
    birthYear: 1930,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HD|cn_cdl|0": {
    name: "Qian Weichang",
    birthYear: 1912,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HD|cn_cndca|0": {
    name: "Chen Suiheng",
    birthYear: 1915,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HN|cn_ccp|0": {
    name: "Ye Xuanping",
    birthYear: 1924,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HN|cn_ccp|1": {
    name: "Liang Xiang",
    birthYear: 1919,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HN|cn_ccp|2": {
    name: "Xie Fei",
    birthYear: 1932,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HN|cn_ccp|3": {
    name: "Lin Ruo",
    birthYear: 1924,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HN|cn_ccp|4": {
    name: "Cheng Kejie",
    birthYear: 1933,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HN|cn_ccp|5": {
    name: "Zhao Fulin",
    birthYear: 1932,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HN|cn_ccp|6": {
    name: "Liu Jianfeng",
    birthYear: 1936,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HN|cn_cdl|0": {
    name: "Fei Xiaotong",
    birthYear: 1910,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HN|cn_cndca|0": {
    name: "Rong Yiren",
    birthYear: 1916,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HZ|cn_ccp|0": {
    name: "Duan Junyi",
    birthYear: 1910,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HZ|cn_ccp|1": {
    name: "Hou Zongbin",
    birthYear: 1929,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HZ|cn_ccp|2": {
    name: "Guan Guangfu",
    birthYear: 1931,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HZ|cn_ccp|3": {
    name: "Guo Shuyan",
    birthYear: 1935,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HZ|cn_ccp|4": {
    name: "Xiong Qingquan",
    birthYear: 1927,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HZ|cn_ccp|5": {
    name: "Chen Bangzhu",
    birthYear: 1934,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HZ|cn_ccp|6": {
    name: "Li Xiannian",
    birthYear: 1909,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HZ|cn_cdl|0": {
    name: "Chu Tunan",
    birthYear: 1899,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HZ|cn_cndca|0": {
    name: "Li Chonghuai",
    birthYear: 1916,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XB|cn_ccp|0": {
    name: "Bai Qingcai",
    birthYear: 1932,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XB|cn_ccp|1": {
    name: "Zhang Boxing",
    birthYear: 1930,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XB|cn_ccp|2": {
    name: "Jia Zhijie",
    birthYear: 1935,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XB|cn_ccp|3": {
    name: "Gu Jinchi",
    birthYear: 1932,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XB|cn_ccp|4": {
    name: "Seypidin Azizi",
    birthYear: 1915,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XB|cn_ccp|5": {
    name: "Wang Enmao",
    birthYear: 1913,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XB|cn_ccp|6": {
    name: "Bai Lichen",
    birthYear: 1941,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XB|cn_cdl|0": {
    name: "Su Buqing",
    birthYear: 1902,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XB|cn_cndca|0": {
    name: "Sun Qimeng",
    birthYear: 1911,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XN|cn_ccp|0": {
    name: "Lu Dadong",
    birthYear: 1915,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XN|cn_ccp|1": {
    name: "Yang Rudai",
    birthYear: 1926,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XN|cn_ccp|2": {
    name: "Wang Chaowen",
    birthYear: 1930,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XN|cn_ccp|3": {
    name: "He Zhiqiang",
    birthYear: 1934,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XN|cn_ccp|4": {
    name: "Pu Chaozhu",
    birthYear: 1929,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XN|cn_ccp|5": {
    name: "Hu Jintao",
    birthYear: 1942,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XN|cn_ccp|6": {
    name: "Tian Jiyun",
    birthYear: 1929,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XN|cn_cdl|0": {
    name: "Feng Kexi",
    birthYear: 1922,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XN|cn_cndca|0": {
    name: "Feng Tiyun",
    birthYear: 1925,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|DB|cn_ccp|0": {
    name: "Wang Chonglun",
    birthYear: 1927,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|DB|cn_ccp|1": {
    name: "Gao Dezhan",
    birthYear: 1932,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|DB|cn_ccp|2": {
    name: "Gao Di",
    birthYear: 1927,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|DB|cn_ccp|3": {
    name: "Zhao Xiu",
    birthYear: 1921,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|DB|cn_ccp|4": {
    name: "Li Li'an",
    birthYear: 1920,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|DB|cn_ccp|5": {
    name: "Hou Jie",
    birthYear: 1931,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|DB|cn_ccp|6": {
    name: "Chen Lei",
    birthYear: 1917,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|DB|cn_cdl|0": {
    name: "Hu Yuzhi",
    birthYear: 1896,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|DB|cn_cndca|0": {
    name: "Hu Juewen",
    birthYear: 1895,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HB|cn_ccp|0": {
    name: "Zhao Pengfei",
    birthYear: 1920,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HB|cn_ccp|1": {
    name: "Zhang Baifa",
    birthYear: 1935,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HB|cn_ccp|2": {
    name: "Li Ruihuan",
    birthYear: 1934,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HB|cn_ccp|3": {
    name: "Zhang Lichang",
    birthYear: 1939,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HB|cn_ccp|4": {
    name: "Xie Feng",
    birthYear: 1922,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HB|cn_ccp|5": {
    name: "Liu Bingyan",
    birthYear: 1915,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HB|cn_ccp|6": {
    name: "Chen Muhua",
    birthYear: 1921,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HB|cn_cdl|0": {
    name: "Xu Deheng",
    birthYear: 1890,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HB|cn_cndca|0": {
    name: "Cheng Siyuan",
    birthYear: 1908,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HD|cn_ccp|0": {
    name: "Qiao Shi",
    birthYear: 1924,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HD|cn_ccp|1": {
    name: "Zou Jiahua",
    birthYear: 1926,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HD|cn_ccp|2": {
    name: "Hu Lijiao",
    birthYear: 1914,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HD|cn_ccp|3": {
    name: "Wang Daohan",
    birthYear: 1915,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HD|cn_ccp|4": {
    name: "Gu Xiulian",
    birthYear: 1936,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HD|cn_ccp|5": {
    name: "Han Peixin",
    birthYear: 1921,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HD|cn_ccp|6": {
    name: "Zhao Zhihao",
    birthYear: 1931,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HD|cn_cdl|0": {
    name: "Zhou Peiyuan",
    birthYear: 1902,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HD|cn_cndca|0": {
    name: "Zhu Xuefan",
    birthYear: 1905,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HN|cn_ccp|0": {
    name: "Liang Lingguang",
    birthYear: 1916,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HN|cn_ccp|1": {
    name: "Wu Nansheng",
    birthYear: 1922,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HN|cn_ccp|2": {
    name: "Ren Zhongyi",
    birthYear: 1914,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HN|cn_ccp|3": {
    name: "Luo Tian",
    birthYear: 1920,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HN|cn_ccp|4": {
    name: "Wei Guoqing",
    birthYear: 1913,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HN|cn_ccp|5": {
    name: "Qin Yingji",
    birthYear: 1915,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HN|cn_ccp|6": {
    name: "Deng Hongxun",
    birthYear: 1931,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HN|cn_cdl|0": {
    name: "Qu Wu",
    birthYear: 1898,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HN|cn_cndca|0": {
    name: "Lu Jiaxi",
    birthYear: 1915,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HZ|cn_ccp|0": {
    name: "Liu Jie",
    birthYear: 1915,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HZ|cn_ccp|1": {
    name: "Yang Xizong",
    birthYear: 1928,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HZ|cn_ccp|2": {
    name: "Huang Zhizhen",
    birthYear: 1920,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HZ|cn_ccp|3": {
    name: "Guo Zhenqian",
    birthYear: 1933,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HZ|cn_ccp|4": {
    name: "Liu Fusheng",
    birthYear: 1931,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HZ|cn_ccp|5": {
    name: "Liu Zheng",
    birthYear: 1929,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HZ|cn_ccp|6": {
    name: "Peng Zhen",
    birthYear: 1902,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HZ|cn_cdl|0": {
    name: "Ye Shengtao",
    birthYear: 1894,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HZ|cn_cndca|0": {
    name: "Shi Liang",
    birthYear: 1900,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XB|cn_ccp|0": {
    name: "Li Qingwei",
    birthYear: 1920,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XB|cn_ccp|1": {
    name: "Li Qiming",
    birthYear: 1915,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XB|cn_ccp|2": {
    name: "Li Ziqi",
    birthYear: 1923,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XB|cn_ccp|3": {
    name: "Song Ping",
    birthYear: 1917,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XB|cn_ccp|4": {
    name: "Song Hanliang",
    birthYear: 1934,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XB|cn_ccp|5": {
    name: "Ismail Amat",
    birthYear: 1935,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XB|cn_ccp|6": {
    name: "Ma Sizhong",
    birthYear: 1931,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XB|cn_cdl|0": {
    name: "Cai Xiao",
    birthYear: 1919,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XB|cn_cndca|0": {
    name: "Dong Yinchu",
    birthYear: 1915,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XN|cn_ccp|0": {
    name: "He Haoju",
    birthYear: 1922,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XN|cn_ccp|1": {
    name: "Jiang Minkuan",
    birthYear: 1930,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XN|cn_ccp|2": {
    name: "Zhu Houze",
    birthYear: 1931,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XN|cn_ccp|3": {
    name: "An Pingsheng",
    birthYear: 1917,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XN|cn_ccp|4": {
    name: "Liu Minghui",
    birthYear: 1914,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XN|cn_ccp|5": {
    name: "Ngapoi Ngawang Jigme",
    birthYear: 1910,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XN|cn_ccp|6": {
    name: "Yao Yilin",
    birthYear: 1917,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XN|cn_cdl|0": {
    name: "Jin Shanbao",
    birthYear: 1895,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XN|cn_cndca|0": {
    name: "Tang Yuanbing",
    birthYear: 1909,
    gender: "male",
    ethnicity: "asian",
  },
};
