import type { RosterMap } from "../historicalRosters";

/** Second half of the 2019 Bundestag roster; merged in p2019-de.ts. */
export const ROSTER_2019_DE_B: RosterMap = {
  "DE|landtag|BE|de_linke|0": {
    name: "Udo Wolf",
    birthYear: 1962,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BE|de_spd|0": {
    name: "Raed Saleh",
    birthYear: 1977,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BRE|de_afd|0": {
    name: "Frank Magnitz",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BRE|de_cdu|0": {
    name: "Thomas Röwekamp",
    birthYear: 1966,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BRE|de_fdp|0": {
    name: "Lencke Wischhusen",
    birthYear: 1985,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|BRE|de_greens|0": {
    name: "Maike Schaefer",
    birthYear: 1971,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|BRE|de_independent|0": {
    name: "Jan Timke",
    birthYear: 1971,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BRE|de_linke|0": {
    name: "Kristina Vogt",
    birthYear: 1965,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|BRE|de_spd|0": {
    name: "Mustafa Güngör",
    birthYear: 1978,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BW|de_afd|0": {
    name: "Bernd Gögel",
    birthYear: 1955,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BW|de_cdu|0": {
    name: "Wolfgang Reinhart",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BW|de_fdp|0": {
    name: "Hans-Ulrich Rülke",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BW|de_greens|0": {
    name: "Andreas Schwarz",
    birthYear: 1979,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BW|de_independent|0": {
    name: "Wolfgang Gedeon",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BW|de_spd|0": {
    name: "Andreas Stoch",
    birthYear: 1969,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BY|de_afd|0": {
    name: "Katrin Ebner-Steiner",
    birthYear: 1978,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|BY|de_csu|0": {
    name: "Thomas Kreuzer",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BY|de_fdp|0": {
    name: "Martin Hagen",
    birthYear: 1981,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BY|de_greens|0": {
    name: "Katharina Schulze",
    birthYear: 1985,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|BY|de_independent|0": {
    name: "Hubert Aiwanger",
    birthYear: 1971,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BY|de_spd|0": {
    name: "Horst Arnold",
    birthYear: 1962,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HE|de_afd|0": {
    name: "Robert Lambrou",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HE|de_cdu|0": {
    name: "Michael Boddenberg",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HE|de_fdp|0": {
    name: "René Rock",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HE|de_greens|0": {
    name: "Mathias Wagner",
    birthYear: 1974,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HE|de_linke|0": {
    name: "Janine Wissler",
    birthYear: 1981,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|HE|de_spd|0": {
    name: "Nancy Faeser",
    birthYear: 1970,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|HH|de_afd|0": {
    name: "Dirk Nockemann",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HH|de_cdu|0": {
    name: "André Trepoll",
    birthYear: 1977,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HH|de_fdp|0": {
    name: "Michael Kruse",
    birthYear: 1983,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HH|de_greens|0": {
    name: "Anjes Tjarks",
    birthYear: 1981,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HH|de_linke|0": {
    name: "Sabine Boeddinghaus",
    birthYear: 1957,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|HH|de_spd|0": {
    name: "Dirk Kienscherf",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|MV|de_afd|0": {
    name: "Nikolaus Kramer",
    birthYear: 1976,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|MV|de_cdu|0": {
    name: "Vincent Kokert",
    birthYear: 1978,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|MV|de_independent|0": {
    name: "Christel Weißig",
    birthYear: 1945,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|MV|de_linke|0": {
    name: "Simone Oldenburg",
    birthYear: 1969,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|MV|de_spd|0": {
    name: "Thomas Krüger",
    birthYear: 1969,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|NI|de_afd|0": {
    name: "Dana Guth",
    birthYear: 1970,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|NI|de_cdu|0": {
    name: "Dirk Toepffer",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|NI|de_fdp|0": {
    name: "Stefan Birkner",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|NI|de_greens|0": {
    name: "Anja Piel",
    birthYear: 1965,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|NI|de_spd|0": {
    name: "Johanne Modder",
    birthYear: 1960,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|NW|de_afd|0": {
    name: "Markus Wagner",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|NW|de_cdu|0": {
    name: "Bodo Löttgen",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|NW|de_fdp|0": {
    name: "Christof Rasche",
    birthYear: 1962,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|NW|de_greens|0": {
    name: "Monika Düker",
    birthYear: 1963,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|NW|de_independent|0": {
    name: "Marcus Pretzell",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|NW|de_spd|0": {
    name: "Thomas Kutschaty",
    birthYear: 1968,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|RP|de_afd|0": {
    name: "Uwe Junge",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|RP|de_cdu|0": {
    name: "Christian Baldauf",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|RP|de_fdp|0": {
    name: "Cornelia Willius-Senzer",
    birthYear: 1943,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|RP|de_greens|0": {
    name: "Bernhard Braun",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|RP|de_spd|0": {
    name: "Alexander Schweitzer",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SH|de_afd|0": {
    name: "Jörg Nobis",
    birthYear: 1975,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SH|de_cdu|0": {
    name: "Tobias Koch",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SH|de_fdp|0": {
    name: "Christopher Vogt",
    birthYear: 1984,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SH|de_greens|0": {
    name: "Eka von Kalben",
    birthYear: 1964,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|SH|de_independent|0": {
    name: "Lars Harms",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SH|de_spd|0": {
    name: "Ralf Stegner",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SL|de_afd|0": {
    name: "Josef Dörr",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SL|de_cdu|0": {
    name: "Klaus Meiser",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SL|de_linke|0": {
    name: "Oskar Lafontaine",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SL|de_spd|0": {
    name: "Anke Rehlinger",
    birthYear: 1976,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|SN|de_afd|0": {
    name: "Jörg Urban",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SN|de_cdu|0": {
    name: "Christian Hartmann",
    birthYear: 1974,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SN|de_greens|0": {
    name: "Franziska Schubert",
    birthYear: 1982,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|SN|de_independent|0": {
    name: "Ivo Teichmann",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SN|de_linke|0": {
    name: "Rico Gebhardt",
    birthYear: 1963,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SN|de_spd|0": {
    name: "Dirk Panter",
    birthYear: 1974,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|ST|de_afd|0": {
    name: "Oliver Kirchner",
    birthYear: 1966,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|ST|de_cdu|0": {
    name: "Siegfried Borgwardt",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|ST|de_greens|0": {
    name: "Cornelia Lüddemann",
    birthYear: 1968,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|ST|de_independent|0": {
    name: "Sarah Sauermann",
    birthYear: 1988,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|ST|de_linke|0": {
    name: "Thomas Lippmann",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|ST|de_spd|0": {
    name: "Katja Pähle",
    birthYear: 1977,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|TH|de_afd|0": {
    name: "Björn Höcke",
    birthYear: 1972,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|TH|de_cdu|0": {
    name: "Mike Mohring",
    birthYear: 1971,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|TH|de_fdp|0": {
    name: "Thomas Kemmerich",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|TH|de_greens|0": {
    name: "Astrid Rothe-Beinlich",
    birthYear: 1973,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|TH|de_linke|0": {
    name: "Susanne Hennig-Wellsow",
    birthYear: 1977,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|TH|de_spd|0": {
    name: "Matthias Hey",
    birthYear: 1970,
    gender: "male",
    ethnicity: "white",
  },
  "DE|ministerPresident|BB|de_spd|0": {
    name: "Dietmar Woidke",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-dietmar-woidke-2019",
  },
  "DE|ministerPresident|BE|de_spd|0": {
    name: "Michael Müller",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-michael-m-ller-2019",
  },
  "DE|ministerPresident|BRE|de_spd|0": {
    name: "Andreas Bovenschulte",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-andreas-bovenschulte-2019",
  },
  "DE|ministerPresident|BW|de_greens|0": {
    name: "Winfried Kretschmann",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-winfried-kretschmann-2019",
  },
  "DE|ministerPresident|BY|de_csu|0": {
    name: "Markus Söder",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-markus-s-der-2019",
  },
  "DE|ministerPresident|HE|de_cdu|0": {
    name: "Volker Bouffier",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-volker-bouffier-2019",
  },
  "DE|ministerPresident|HH|de_spd|0": {
    name: "Peter Tschentscher",
    birthYear: 1966,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-peter-tschentscher-2019",
  },
  "DE|ministerPresident|MV|de_spd|0": {
    name: "Manuela Schwesig",
    birthYear: 1974,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-manuela-schwesig-2019",
  },
  "DE|ministerPresident|NI|de_spd|0": {
    name: "Stephan Weil",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-stephan-weil-2019",
  },
  "DE|ministerPresident|NW|de_cdu|0": {
    name: "Armin Laschet",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-armin-laschet-2019",
  },
  "DE|ministerPresident|RP|de_spd|0": {
    name: "Malu Dreyer",
    birthYear: 1961,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-malu-dreyer-2019",
  },
  "DE|ministerPresident|SH|de_cdu|0": {
    name: "Daniel Günther",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-daniel-g-nther-2019",
  },
  "DE|ministerPresident|SL|de_cdu|0": {
    name: "Tobias Hans",
    birthYear: 1978,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-tobias-hans-2019",
  },
  "DE|ministerPresident|SN|de_cdu|0": {
    name: "Michael Kretschmer",
    birthYear: 1975,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-michael-kretschmer-2019",
  },
  "DE|ministerPresident|ST|de_cdu|0": {
    name: "Reiner Haseloff",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-reiner-haseloff-2019",
  },
  "DE|ministerPresident|TH|de_linke|0": {
    name: "Bodo Ramelow",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-bodo-ramelow-2019",
  },
};
