import type { RosterMap } from "../historicalRosters";

export const ROSTER_2019_US: RosterMap = {
  "US|governor|AK|republican|0": {
    name: "Mike Dunleavy",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-mike-dunleavy-2019",
  },
  "US|governor|AL|republican|0": {
    name: "Kay Ivey",
    birthYear: 1944,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-kay-ivey-2019",
  },
  "US|governor|AR|republican|0": {
    name: "Asa Hutchinson",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-asa-hutchinson-2019",
  },
  "US|governor|AZ|republican|0": {
    name: "Doug Ducey",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-doug-ducey-2019",
  },
  "US|governor|CA|democrat|0": {
    name: "Gavin Newsom",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
    portraitId: "gavin-newsom",
  },
  "US|governor|CO|democrat|0": {
    name: "Jared Polis",
    birthYear: 1975,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-jared-polis-2019",
  },
  "US|governor|CT|democrat|0": {
    name: "Ned Lamont",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-ned-lamont-2019",
  },
  "US|governor|DE|democrat|0": {
    name: "John Carney",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-john-carney-2019",
  },
  "US|governor|FL|republican|0": {
    name: "Ron DeSantis",
    birthYear: 1978,
    gender: "male",
    ethnicity: "white",
    portraitId: "ron-desantis",
  },
  "US|governor|GA|republican|0": {
    name: "Brian Kemp",
    birthYear: 1963,
    gender: "male",
    ethnicity: "white",
    portraitId: "brian-kemp",
  },
  "US|governor|HI|democrat|0": {
    name: "David Ige",
    birthYear: 1957,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-david-ige-2019",
  },
  "US|governor|IA|republican|0": {
    name: "Kim Reynolds",
    birthYear: 1959,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-kim-reynolds-2019",
  },
  "US|governor|ID|republican|0": {
    name: "Brad Little",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-brad-little-2019",
  },
  "US|governor|IL|democrat|0": {
    name: "J. B. Pritzker",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
    portraitId: "jb-pritzker",
  },
  "US|governor|IN|republican|0": {
    name: "Eric Holcomb",
    birthYear: 1968,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-eric-holcomb-2019",
  },
  "US|governor|KS|democrat|0": {
    name: "Laura Kelly",
    birthYear: 1950,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-laura-kelly-2019",
  },
  "US|governor|KY|democrat|0": {
    name: "Andy Beshear",
    birthYear: 1977,
    gender: "male",
    ethnicity: "white",
    portraitId: "andy-beshear",
  },
  "US|governor|LA|democrat|0": {
    name: "John Bel Edwards",
    birthYear: 1966,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-john-bel-edwards-2019",
  },
  "US|governor|MA|republican|0": {
    name: "Charlie Baker",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-charlie-baker-2019",
  },
  "US|governor|MD|republican|0": {
    name: "Larry Hogan",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
    portraitId: "larry-hogan",
  },
  "US|governor|ME|democrat|0": {
    name: "Janet Mills",
    birthYear: 1947,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-janet-mills-2019",
  },
  "US|governor|MI|democrat|0": {
    name: "Gretchen Whitmer",
    birthYear: 1971,
    gender: "female",
    ethnicity: "white",
    portraitId: "gretchen-whitmer",
  },
  "US|governor|MN|democrat|0": {
    name: "Tim Walz",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
    portraitId: "tim-walz",
  },
  "US|governor|MO|republican|0": {
    name: "Mike Parson",
    birthYear: 1955,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-mike-parson-2019",
  },
  "US|governor|MS|republican|0": {
    name: "Tate Reeves",
    birthYear: 1974,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-tate-reeves-2019",
  },
  "US|governor|MT|democrat|0": {
    name: "Steve Bullock",
    birthYear: 1966,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-steve-bullock-2019",
  },
  "US|governor|NC|democrat|0": {
    name: "Roy Cooper",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-roy-cooper-2019",
  },
  "US|governor|ND|republican|0": {
    name: "Doug Burgum",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-doug-burgum-2019",
  },
  "US|governor|NE|republican|0": {
    name: "Pete Ricketts",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-pete-ricketts-2019",
  },
  "US|governor|NH|republican|0": {
    name: "Chris Sununu",
    birthYear: 1974,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-chris-sununu-2019",
  },
  "US|governor|NJ|democrat|0": {
    name: "Phil Murphy",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-phil-murphy-2019",
  },
  "US|governor|NM|democrat|0": {
    name: "Michelle Lujan Grisham",
    birthYear: 1959,
    gender: "female",
    ethnicity: "hispanic",
    portraitId: "michelle-lujan-grisham",
  },
  "US|governor|NV|democrat|0": {
    name: "Steve Sisolak",
    birthYear: 1953,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-steve-sisolak-2019",
  },
  "US|governor|NY|democrat|0": {
    name: "Andrew Cuomo",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-andrew-cuomo-2019",
  },
  "US|governor|OH|republican|0": {
    name: "Mike DeWine",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-mike-dewine-2019",
  },
  "US|governor|OK|republican|0": {
    name: "Kevin Stitt",
    birthYear: 1972,
    gender: "male",
    ethnicity: "other",
    portraitId: "hist-kevin-stitt-2019",
  },
  "US|governor|OR|democrat|0": {
    name: "Kate Brown",
    birthYear: 1960,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-kate-brown-2019",
  },
  "US|governor|PA|democrat|0": {
    name: "Tom Wolf",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-tom-wolf-2019",
  },
  "US|governor|RI|democrat|0": {
    name: "Gina Raimondo",
    birthYear: 1971,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-gina-raimondo-2019",
  },
  "US|governor|SC|republican|0": {
    name: "Henry McMaster",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-henry-mcmaster-2019",
  },
  "US|governor|SD|republican|0": {
    name: "Kristi Noem",
    birthYear: 1971,
    gender: "female",
    ethnicity: "white",
    portraitId: "kristi-noem",
  },
  "US|governor|TN|republican|0": {
    name: "Bill Lee",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-bill-lee-2019",
  },
  "US|governor|TX|republican|0": {
    name: "Greg Abbott",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
    portraitId: "greg-abbott",
  },
  "US|governor|UT|republican|0": {
    name: "Gary Herbert",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-gary-herbert-2019",
  },
  "US|governor|VA|democrat|0": {
    name: "Ralph Northam",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-ralph-northam-2019",
  },
  "US|governor|VT|republican|0": {
    name: "Phil Scott",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-phil-scott-2019",
  },
  "US|governor|WA|democrat|0": {
    name: "Jay Inslee",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-jay-inslee-2019",
  },
  "US|governor|WI|democrat|0": {
    name: "Tony Evers",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
    portraitId: "tony-evers",
  },
  "US|governor|WV|republican|0": {
    name: "Jim Justice",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-jim-justice-2019",
  },
  "US|governor|WY|republican|0": {
    name: "Mark Gordon",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-mark-gordon-2019",
  },
  "US|house|AK|republican|0": {
    name: "Don Young",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|AL|democrat|0": {
    name: "Terri Sewell",
    birthYear: 1965,
    gender: "female",
    ethnicity: "black",
  },
  "US|house|AL|republican|0": {
    name: "Robert Aderholt",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|AR|republican|0": {
    name: "Steve Womack",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|AZ|democrat|0": {
    name: "Raúl Grijalva",
    birthYear: 1948,
    gender: "male",
    ethnicity: "hispanic",
    portraitId: "raul-grijalva",
  },
  "US|house|AZ|republican|0": {
    name: "Paul Gosar",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|CA|democrat|0": {
    name: "Nancy Pelosi",
    birthYear: 1940,
    gender: "female",
    ethnicity: "white",
    portraitId: "nancy-pelosi",
  },
  "US|house|CA|republican|0": {
    name: "Kevin McCarthy",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
    portraitId: "kevin-mccarthy",
  },
  "US|house|CO|democrat|0": {
    name: "Diana DeGette",
    birthYear: 1957,
    gender: "female",
    ethnicity: "white",
  },
  "US|house|CO|republican|0": {
    name: "Doug Lamborn",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|CT|democrat|0": {
    name: "Rosa DeLauro",
    birthYear: 1943,
    gender: "female",
    ethnicity: "white",
  },
  "US|house|DE|democrat|0": {
    name: "Lisa Blunt Rochester",
    birthYear: 1962,
    gender: "female",
    ethnicity: "black",
  },
  "US|house|FL|democrat|0": {
    name: "Alcee Hastings",
    birthYear: 1936,
    gender: "male",
    ethnicity: "black",
  },
  "US|house|FL|republican|0": {
    name: "Mario Díaz-Balart",
    birthYear: 1961,
    gender: "male",
    ethnicity: "hispanic",
  },
  "US|house|GA|democrat|0": {
    name: "John Lewis",
    birthYear: 1940,
    gender: "male",
    ethnicity: "black",
  },
  "US|house|GA|republican|0": {
    name: "Tom Graves",
    birthYear: 1970,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|HI|democrat|0": {
    name: "Ed Case",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|IA|democrat|0": {
    name: "Dave Loebsack",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|IA|republican|0": {
    name: "Steve King",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|ID|republican|0": {
    name: "Mike Simpson",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|IL|democrat|0": {
    name: "Bobby Rush",
    birthYear: 1946,
    gender: "male",
    ethnicity: "black",
    portraitId: "bobby-rush",
  },
  "US|house|IL|republican|0": {
    name: "John Shimkus",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|IN|democrat|0": {
    name: "Pete Visclosky",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|IN|republican|0": {
    name: "Larry Bucshon",
    birthYear: 1962,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|KS|democrat|0": {
    name: "Sharice Davids",
    birthYear: 1980,
    gender: "female",
    ethnicity: "other",
  },
  "US|house|KS|republican|0": {
    name: "Roger Marshall",
    birthYear: 1960,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|KY|democrat|0": {
    name: "John Yarmuth",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|KY|republican|0": {
    name: "Hal Rogers",
    birthYear: 1937,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|LA|democrat|0": {
    name: "Cedric Richmond",
    birthYear: 1973,
    gender: "male",
    ethnicity: "black",
    portraitId: "cedric-richmond",
  },
  "US|house|LA|republican|0": {
    name: "Steve Scalise",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|MA|democrat|0": {
    name: "Richard Neal",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|MD|democrat|0": {
    name: "Steny Hoyer",
    birthYear: 1939,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|MD|republican|0": {
    name: "Andy Harris",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|ME|democrat|0": {
    name: "Chellie Pingree",
    birthYear: 1955,
    gender: "female",
    ethnicity: "white",
  },
  "US|house|MI|democrat|0": {
    name: "Dan Kildee",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|MI|independent|0": {
    name: "Justin Amash",
    birthYear: 1980,
    gender: "male",
    ethnicity: "other",
  },
  "US|house|MI|republican|0": {
    name: "Fred Upton",
    birthYear: 1953,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|MN|democrat|0": {
    name: "Collin Peterson",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|MN|republican|0": {
    name: "Tom Emmer",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|MO|democrat|0": {
    name: "Lacy Clay",
    birthYear: 1956,
    gender: "male",
    ethnicity: "black",
  },
  "US|house|MO|republican|0": {
    name: "Sam Graves",
    birthYear: 1963,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|MS|democrat|0": {
    name: "Bennie Thompson",
    birthYear: 1948,
    gender: "male",
    ethnicity: "black",
  },
  "US|house|MS|republican|0": {
    name: "Steven Palazzo",
    birthYear: 1970,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|MT|republican|0": {
    name: "Greg Gianforte",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|NC|democrat|0": {
    name: "David Price",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|NC|republican|0": {
    name: "Virginia Foxx",
    birthYear: 1943,
    gender: "female",
    ethnicity: "white",
  },
  "US|house|ND|republican|0": {
    name: "Kelly Armstrong",
    birthYear: 1976,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|NE|republican|0": {
    name: "Jeff Fortenberry",
    birthYear: 1960,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|NH|democrat|0": {
    name: "Annie Kuster",
    birthYear: 1956,
    gender: "female",
    ethnicity: "white",
  },
  "US|house|NJ|democrat|0": {
    name: "Frank Pallone",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|NJ|republican|0": {
    name: "Chris Smith",
    birthYear: 1953,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|NM|democrat|0": {
    name: "Ben Ray Luján",
    birthYear: 1972,
    gender: "male",
    ethnicity: "hispanic",
    portraitId: "ben-ray-lujan",
  },
  "US|house|NV|democrat|0": {
    name: "Dina Titus",
    birthYear: 1950,
    gender: "female",
    ethnicity: "white",
  },
  "US|house|NV|republican|0": {
    name: "Mark Amodei",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|NY|democrat|0": {
    name: "Nita Lowey",
    birthYear: 1937,
    gender: "female",
    ethnicity: "white",
  },
  "US|house|NY|republican|0": {
    name: "Peter King",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|OH|democrat|0": {
    name: "Marcy Kaptur",
    birthYear: 1946,
    gender: "female",
    ethnicity: "white",
  },
  "US|house|OH|republican|0": {
    name: "Steve Chabot",
    birthYear: 1953,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|OK|democrat|0": {
    name: "Kendra Horn",
    birthYear: 1976,
    gender: "female",
    ethnicity: "white",
  },
  "US|house|OK|republican|0": {
    name: "Frank Lucas",
    birthYear: 1960,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|OR|democrat|0": {
    name: "Peter DeFazio",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|OR|republican|0": {
    name: "Greg Walden",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|PA|democrat|0": {
    name: "Mike Doyle",
    birthYear: 1953,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|PA|republican|0": {
    name: "Glenn Thompson",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|RI|democrat|0": {
    name: "Jim Langevin",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|SC|democrat|0": {
    name: "Jim Clyburn",
    birthYear: 1940,
    gender: "male",
    ethnicity: "black",
    portraitId: "james-clyburn",
  },
  "US|house|SC|republican|0": {
    name: "Joe Wilson",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|SD|republican|0": {
    name: "Dusty Johnson",
    birthYear: 1976,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|TN|democrat|0": {
    name: "Jim Cooper",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|TN|republican|0": {
    name: "Phil Roe",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|TX|democrat|0": {
    name: "Eddie Bernice Johnson",
    birthYear: 1935,
    gender: "female",
    ethnicity: "black",
  },
  "US|house|TX|republican|0": {
    name: "Kay Granger",
    birthYear: 1943,
    gender: "female",
    ethnicity: "white",
  },
  "US|house|UT|democrat|0": {
    name: "Ben McAdams",
    birthYear: 1974,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|UT|republican|0": {
    name: "Rob Bishop",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|VA|democrat|0": {
    name: "Bobby Scott",
    birthYear: 1947,
    gender: "male",
    ethnicity: "black",
  },
  "US|house|VA|republican|0": {
    name: "Rob Wittman",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|VT|democrat|0": {
    name: "Peter Welch",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|WA|democrat|0": {
    name: "Adam Smith",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|WA|republican|0": {
    name: "Cathy McMorris Rodgers",
    birthYear: 1969,
    gender: "female",
    ethnicity: "white",
  },
  "US|house|WI|democrat|0": {
    name: "Ron Kind",
    birthYear: 1963,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|WI|republican|0": {
    name: "Jim Sensenbrenner",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|WV|republican|0": {
    name: "David McKinley",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "US|house|WY|republican|0": {
    name: "Liz Cheney",
    birthYear: 1966,
    gender: "female",
    ethnicity: "white",
    portraitId: "liz-cheney",
  },
  "US|senate|AK|republican|0": {
    name: "Dan Sullivan",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|AK|republican|1": {
    name: "Lisa Murkowski",
    birthYear: 1957,
    gender: "female",
    ethnicity: "white",
    portraitId: "lisa-murkowski",
  },
  "US|senate|AL|democrat|0": {
    name: "Doug Jones",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|AL|republican|0": {
    name: "Richard Shelby",
    birthYear: 1934,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|AR|republican|0": {
    name: "Tom Cotton",
    birthYear: 1977,
    gender: "male",
    ethnicity: "white",
    portraitId: "tom-cotton",
  },
  "US|senate|AR|republican|1": {
    name: "John Boozman",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|AZ|democrat|0": {
    name: "Kyrsten Sinema",
    birthYear: 1976,
    gender: "female",
    ethnicity: "white",
    portraitId: "kyrsten-sinema",
  },
  "US|senate|AZ|republican|0": {
    name: "Martha McSally",
    birthYear: 1966,
    gender: "female",
    ethnicity: "white",
  },
  "US|senate|CA|democrat|0": {
    name: "Dianne Feinstein",
    birthYear: 1933,
    gender: "female",
    ethnicity: "white",
  },
  "US|senate|CA|democrat|1": {
    name: "Kamala Harris",
    birthYear: 1964,
    gender: "female",
    ethnicity: "black",
    portraitId: "kamala-harris",
  },
  "US|senate|CO|democrat|0": {
    name: "Michael Bennet",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|CO|republican|0": {
    name: "Cory Gardner",
    birthYear: 1974,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|CT|democrat|0": {
    name: "Chris Murphy",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
    portraitId: "chris-murphy",
  },
  "US|senate|CT|democrat|1": {
    name: "Richard Blumenthal",
    birthYear: 1946,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|DE|democrat|0": {
    name: "Tom Carper",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|DE|democrat|1": {
    name: "Chris Coons",
    birthYear: 1963,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|FL|republican|0": {
    name: "Marco Rubio",
    birthYear: 1971,
    gender: "male",
    ethnicity: "hispanic",
    portraitId: "marco-rubio",
  },
  "US|senate|FL|republican|1": {
    name: "Rick Scott",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|GA|republican|0": {
    name: "David Perdue",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|GA|republican|1": {
    name: "Kelly Loeffler",
    birthYear: 1970,
    gender: "female",
    ethnicity: "white",
  },
  "US|senate|HI|democrat|0": {
    name: "Mazie Hirono",
    birthYear: 1947,
    gender: "female",
    ethnicity: "asian",
    portraitId: "mazie-hirono",
  },
  "US|senate|HI|democrat|1": {
    name: "Brian Schatz",
    birthYear: 1972,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|IA|republican|0": {
    name: "Joni Ernst",
    birthYear: 1970,
    gender: "female",
    ethnicity: "white",
  },
  "US|senate|IA|republican|1": {
    name: "Chuck Grassley",
    birthYear: 1933,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|ID|republican|0": {
    name: "Jim Risch",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|ID|republican|1": {
    name: "Mike Crapo",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|IL|democrat|0": {
    name: "Dick Durbin",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|IL|democrat|1": {
    name: "Tammy Duckworth",
    birthYear: 1968,
    gender: "female",
    ethnicity: "asian",
    portraitId: "tammy-duckworth",
  },
  "US|senate|IN|republican|0": {
    name: "Mike Braun",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|IN|republican|1": {
    name: "Todd Young",
    birthYear: 1972,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|KS|republican|0": {
    name: "Pat Roberts",
    birthYear: 1936,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|KS|republican|1": {
    name: "Jerry Moran",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|KY|republican|0": {
    name: "Mitch McConnell",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
    portraitId: "mitch-mcconnell",
  },
  "US|senate|KY|republican|1": {
    name: "Rand Paul",
    birthYear: 1963,
    gender: "male",
    ethnicity: "white",
    portraitId: "rand-paul",
  },
  "US|senate|LA|republican|0": {
    name: "Bill Cassidy",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|LA|republican|1": {
    name: "John Kennedy",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MA|democrat|0": {
    name: "Elizabeth Warren",
    birthYear: 1949,
    gender: "female",
    ethnicity: "white",
    portraitId: "elizabeth-warren",
  },
  "US|senate|MA|democrat|1": {
    name: "Ed Markey",
    birthYear: 1946,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MD|democrat|0": {
    name: "Ben Cardin",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MD|democrat|1": {
    name: "Chris Van Hollen",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|ME|independent|0": {
    name: "Angus King",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|ME|republican|0": {
    name: "Susan Collins",
    birthYear: 1952,
    gender: "female",
    ethnicity: "white",
    portraitId: "susan-collins",
  },
  "US|senate|MI|democrat|0": {
    name: "Debbie Stabenow",
    birthYear: 1950,
    gender: "female",
    ethnicity: "white",
    portraitId: "debbie-stabenow",
  },
  "US|senate|MI|democrat|1": {
    name: "Gary Peters",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MN|democrat|0": {
    name: "Amy Klobuchar",
    birthYear: 1960,
    gender: "female",
    ethnicity: "white",
    portraitId: "amy-klobuchar",
  },
  "US|senate|MN|democrat|1": {
    name: "Tina Smith",
    birthYear: 1958,
    gender: "female",
    ethnicity: "white",
  },
  "US|senate|MO|republican|0": {
    name: "Josh Hawley",
    birthYear: 1979,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MO|republican|1": {
    name: "Roy Blunt",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MS|republican|0": {
    name: "Roger Wicker",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|MS|republican|1": {
    name: "Cindy Hyde-Smith",
    birthYear: 1959,
    gender: "female",
    ethnicity: "white",
  },
  "US|senate|MT|democrat|0": {
    name: "Jon Tester",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
    portraitId: "jon-tester",
  },
  "US|senate|MT|republican|0": {
    name: "Steve Daines",
    birthYear: 1962,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NC|republican|0": {
    name: "Thom Tillis",
    birthYear: 1960,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NC|republican|1": {
    name: "Richard Burr",
    birthYear: 1955,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|ND|republican|0": {
    name: "Kevin Cramer",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|ND|republican|1": {
    name: "John Hoeven",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NE|republican|0": {
    name: "Deb Fischer",
    birthYear: 1951,
    gender: "female",
    ethnicity: "white",
  },
  "US|senate|NE|republican|1": {
    name: "Ben Sasse",
    birthYear: 1972,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NH|democrat|0": {
    name: "Jeanne Shaheen",
    birthYear: 1947,
    gender: "female",
    ethnicity: "white",
  },
  "US|senate|NH|democrat|1": {
    name: "Maggie Hassan",
    birthYear: 1958,
    gender: "female",
    ethnicity: "white",
    portraitId: "maggie-hassan",
  },
  "US|senate|NJ|democrat|0": {
    name: "Bob Menendez",
    birthYear: 1954,
    gender: "male",
    ethnicity: "hispanic",
  },
  "US|senate|NJ|democrat|1": {
    name: "Cory Booker",
    birthYear: 1969,
    gender: "male",
    ethnicity: "black",
    portraitId: "cory-booker",
  },
  "US|senate|NM|democrat|0": {
    name: "Martin Heinrich",
    birthYear: 1971,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NM|democrat|1": {
    name: "Tom Udall",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|NV|democrat|0": {
    name: "Jacky Rosen",
    birthYear: 1957,
    gender: "female",
    ethnicity: "white",
    portraitId: "jacky-rosen",
  },
  "US|senate|NV|democrat|1": {
    name: "Catherine Cortez Masto",
    birthYear: 1964,
    gender: "female",
    ethnicity: "hispanic",
  },
  "US|senate|NY|democrat|0": {
    name: "Kirsten Gillibrand",
    birthYear: 1966,
    gender: "female",
    ethnicity: "white",
  },
  "US|senate|NY|democrat|1": {
    name: "Chuck Schumer",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
    portraitId: "chuck-schumer",
  },
  "US|senate|OH|democrat|0": {
    name: "Sherrod Brown",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|OH|republican|0": {
    name: "Rob Portman",
    birthYear: 1955,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|OK|republican|0": {
    name: "Jim Inhofe",
    birthYear: 1934,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|OK|republican|1": {
    name: "James Lankford",
    birthYear: 1968,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|OR|democrat|0": {
    name: "Jeff Merkley",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
    portraitId: "jeff-merkley",
  },
  "US|senate|OR|democrat|1": {
    name: "Ron Wyden",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
    portraitId: "ron-wyden",
  },
  "US|senate|PA|democrat|0": {
    name: "Bob Casey Jr.",
    birthYear: 1960,
    gender: "male",
    ethnicity: "white",
    portraitId: "bob-casey-jr",
  },
  "US|senate|PA|republican|0": {
    name: "Pat Toomey",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|RI|democrat|0": {
    name: "Sheldon Whitehouse",
    birthYear: 1955,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|RI|democrat|1": {
    name: "Jack Reed",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|SC|republican|0": {
    name: "Lindsey Graham",
    birthYear: 1955,
    gender: "male",
    ethnicity: "white",
    portraitId: "lindsey-graham",
  },
  "US|senate|SC|republican|1": {
    name: "Tim Scott",
    birthYear: 1965,
    gender: "male",
    ethnicity: "black",
    portraitId: "tim-scott",
  },
  "US|senate|SD|republican|0": {
    name: "Mike Rounds",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|SD|republican|1": {
    name: "John Thune",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|TN|republican|0": {
    name: "Marsha Blackburn",
    birthYear: 1952,
    gender: "female",
    ethnicity: "white",
  },
  "US|senate|TN|republican|1": {
    name: "Lamar Alexander",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|TX|republican|0": {
    name: "Ted Cruz",
    birthYear: 1970,
    gender: "male",
    ethnicity: "hispanic",
    portraitId: "ted-cruz",
  },
  "US|senate|TX|republican|1": {
    name: "John Cornyn",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
    portraitId: "john-cornyn",
  },
  "US|senate|UT|republican|0": {
    name: "Mitt Romney",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
    portraitId: "mitt-romney",
  },
  "US|senate|UT|republican|1": {
    name: "Mike Lee",
    birthYear: 1971,
    gender: "male",
    ethnicity: "white",
    portraitId: "mike-lee",
  },
  "US|senate|VA|democrat|0": {
    name: "Tim Kaine",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|VA|democrat|1": {
    name: "Mark Warner",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|VT|democrat|0": {
    name: "Patrick Leahy",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|VT|independent|0": {
    name: "Bernie Sanders",
    birthYear: 1941,
    gender: "male",
    ethnicity: "white",
    portraitId: "bernie-sanders",
  },
  "US|senate|WA|democrat|0": {
    name: "Maria Cantwell",
    birthYear: 1958,
    gender: "female",
    ethnicity: "white",
    portraitId: "maria-cantwell",
  },
  "US|senate|WA|democrat|1": {
    name: "Patty Murray",
    birthYear: 1950,
    gender: "female",
    ethnicity: "white",
    portraitId: "patty-murray",
  },
  "US|senate|WI|democrat|0": {
    name: "Tammy Baldwin",
    birthYear: 1962,
    gender: "female",
    ethnicity: "white",
    portraitId: "tammy-baldwin",
  },
  "US|senate|WI|republican|0": {
    name: "Ron Johnson",
    birthYear: 1955,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|WV|democrat|0": {
    name: "Joe Manchin",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
    portraitId: "joe-manchin",
  },
  "US|senate|WV|republican|0": {
    name: "Shelley Moore Capito",
    birthYear: 1953,
    gender: "female",
    ethnicity: "white",
  },
  "US|senate|WY|republican|0": {
    name: "John Barrasso",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
  },
  "US|senate|WY|republican|1": {
    name: "Mike Enzi",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|AK|democrat|0": {
    name: "Tom Begich",
    birthYear: 1960,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-tom-begich-2019",
  },
  "US|stateSenate|AK|republican|0": {
    name: "Cathy Giessel",
    birthYear: 1951,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-cathy-giessel-2019",
  },
  "US|stateSenate|AL|democrat|0": {
    name: "Bobby Singleton",
    birthYear: 1962,
    gender: "male",
    ethnicity: "black",
    portraitId: "hist-bobby-singleton-2019",
  },
  "US|stateSenate|AL|republican|0": {
    name: "Del Marsh",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|AR|democrat|0": {
    name: "Keith Ingram",
    birthYear: 1955,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|AR|republican|0": {
    name: "Jim Hendren",
    birthYear: 1963,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|AZ|democrat|0": {
    name: "David Bradley",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-david-bradley-2019",
  },
  "US|stateSenate|AZ|republican|0": {
    name: "Karen Fann",
    birthYear: 1954,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-karen-fann-2019",
  },
  "US|stateSenate|CA|democrat|0": {
    name: "Toni Atkins",
    birthYear: 1962,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-toni-atkins-2019",
  },
  "US|stateSenate|CA|republican|0": {
    name: "Shannon Grove",
    birthYear: 1965,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-shannon-grove-2019",
  },
  "US|stateSenate|CO|democrat|0": {
    name: "Leroy Garcia",
    birthYear: 1981,
    gender: "male",
    ethnicity: "hispanic",
    portraitId: "hist-leroy-garcia-2019",
  },
  "US|stateSenate|CO|republican|0": {
    name: "Chris Holbert",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-chris-holbert-2019",
  },
  "US|stateSenate|CT|democrat|0": {
    name: "Martin Looney",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-martin-looney-2019",
  },
  "US|stateSenate|CT|republican|0": {
    name: "Len Fasano",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|DE|democrat|0": {
    name: "David McBride",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-david-mcbride-2019",
  },
  "US|stateSenate|DE|republican|0": {
    name: "Gerald Hocker",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-gerald-hocker-2019",
  },
  "US|stateSenate|FL|democrat|0": {
    name: "Audrey Gibson",
    birthYear: 1956,
    gender: "female",
    ethnicity: "black",
    portraitId: "hist-audrey-gibson-2019",
  },
  "US|stateSenate|FL|republican|0": {
    name: "Bill Galvano",
    birthYear: 1966,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-bill-galvano-2019",
  },
  "US|stateSenate|GA|democrat|0": {
    name: "Steve Henson",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|GA|republican|0": {
    name: "Butch Miller",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|HI|democrat|0": {
    name: "Ron Kouchi",
    birthYear: 1957,
    gender: "male",
    ethnicity: "other",
    portraitId: "hist-ron-kouchi-2019",
  },
  "US|stateSenate|HI|republican|0": {
    name: "Kurt Fevella",
    birthYear: 1967,
    gender: "male",
    ethnicity: "other",
    portraitId: "hist-kurt-fevella-2019",
  },
  "US|stateSenate|IA|democrat|0": {
    name: "Janet Petersen",
    birthYear: 1970,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-janet-petersen-2019",
  },
  "US|stateSenate|IA|republican|0": {
    name: "Charles Schneider",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-charles-schneider-2019",
  },
  "US|stateSenate|ID|democrat|0": {
    name: "Michelle Stennett",
    birthYear: 1960,
    gender: "female",
    ethnicity: "white",
  },
  "US|stateSenate|ID|republican|0": {
    name: "Brent Hill",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|IL|democrat|0": {
    name: "Don Harmon",
    birthYear: 1966,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-don-harmon-2019",
  },
  "US|stateSenate|IL|republican|0": {
    name: "Bill Brady",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-bill-brady-2019",
  },
  "US|stateSenate|IN|democrat|0": {
    name: "Tim Lanane",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|IN|republican|0": {
    name: "Rodric Bray",
    birthYear: 1969,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-rodric-bray-2019",
  },
  "US|stateSenate|KS|democrat|0": {
    name: "Anthony Hensley",
    birthYear: 1953,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|KS|republican|0": {
    name: "Susan Wagle",
    birthYear: 1953,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-susan-wagle-2019",
  },
  "US|stateSenate|KY|democrat|0": {
    name: "Morgan McGarvey",
    birthYear: 1979,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-morgan-mcgarvey-2019",
  },
  "US|stateSenate|KY|republican|0": {
    name: "Robert Stivers",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-robert-stivers-2019",
  },
  "US|stateSenate|LA|democrat|0": {
    name: "Troy Carter",
    birthYear: 1963,
    gender: "male",
    ethnicity: "black",
    portraitId: "hist-troy-carter-2019",
  },
  "US|stateSenate|LA|republican|0": {
    name: "Page Cortez",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-page-cortez-2019",
  },
  "US|stateSenate|MA|democrat|0": {
    name: "Karen Spilka",
    birthYear: 1953,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-karen-spilka-2019",
  },
  "US|stateSenate|MA|republican|0": {
    name: "Bruce Tarr",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-bruce-tarr-2019",
  },
  "US|stateSenate|MD|democrat|0": {
    name: "Bill Ferguson",
    birthYear: 1983,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-bill-ferguson-2019",
  },
  "US|stateSenate|MD|republican|0": {
    name: "J. B. Jennings",
    birthYear: 1974,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-j-b-jennings-2019",
  },
  "US|stateSenate|ME|democrat|0": {
    name: "Troy Jackson",
    birthYear: 1968,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-troy-jackson-2019",
  },
  "US|stateSenate|ME|republican|0": {
    name: "Matthew Pouliot",
    birthYear: 1986,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-matthew-pouliot-2019",
  },
  "US|stateSenate|MI|democrat|0": {
    name: "Jim Ananich",
    birthYear: 1975,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|MI|republican|0": {
    name: "Mike Shirkey",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-mike-shirkey-2019",
  },
  "US|stateSenate|MN|democrat|0": {
    name: "Susan Kent",
    birthYear: 1963,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-susan-kent-2019",
  },
  "US|stateSenate|MN|republican|0": {
    name: "Paul Gazelka",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-paul-gazelka-2019",
  },
  "US|stateSenate|MO|democrat|0": {
    name: "Gina Walsh",
    birthYear: 1957,
    gender: "female",
    ethnicity: "white",
  },
  "US|stateSenate|MO|republican|0": {
    name: "Dave Schatz",
    birthYear: 1963,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|MS|democrat|0": {
    name: "Derrick Simmons",
    birthYear: 1976,
    gender: "male",
    ethnicity: "black",
  },
  "US|stateSenate|MS|republican|0": {
    name: "Dean Kirby",
    birthYear: 1946,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-dean-kirby-2019",
  },
  "US|stateSenate|MT|democrat|0": {
    name: "Jon Sesso",
    birthYear: 1953,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|MT|republican|0": {
    name: "Scott Sales",
    birthYear: 1960,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|NC|democrat|0": {
    name: "Dan Blue",
    birthYear: 1949,
    gender: "male",
    ethnicity: "black",
    portraitId: "hist-dan-blue-2019",
  },
  "US|stateSenate|NC|republican|0": {
    name: "Phil Berger",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-phil-berger-2019",
  },
  "US|stateSenate|ND|democrat|0": {
    name: "Joan Heckaman",
    birthYear: 1946,
    gender: "female",
    ethnicity: "white",
  },
  "US|stateSenate|ND|republican|0": {
    name: "Rich Wardner",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-rich-wardner-2019",
  },
  "US|stateSenate|NH|democrat|0": {
    name: "Donna Soucy",
    birthYear: 1967,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-donna-soucy-2019",
  },
  "US|stateSenate|NH|republican|0": {
    name: "Chuck Morse",
    birthYear: 1960,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|NJ|democrat|0": {
    name: "Steve Sweeney",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-steve-sweeney-2019",
  },
  "US|stateSenate|NJ|republican|0": {
    name: "Tom Kean Jr.",
    birthYear: 1968,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-tom-kean-jr-2019",
  },
  "US|stateSenate|NM|democrat|0": {
    name: "Mary Kay Papen",
    birthYear: 1932,
    gender: "female",
    ethnicity: "white",
  },
  "US|stateSenate|NM|republican|0": {
    name: "Stuart Ingle",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|NV|democrat|0": {
    name: "Nicole Cannizzaro",
    birthYear: 1983,
    gender: "female",
    ethnicity: "white",
  },
  "US|stateSenate|NV|republican|0": {
    name: "James Settelmeyer",
    birthYear: 1971,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|NY|democrat|0": {
    name: "Andrea Stewart-Cousins",
    birthYear: 1950,
    gender: "female",
    ethnicity: "black",
    portraitId: "hist-andrea-stewart-cousins-2019",
  },
  "US|stateSenate|NY|republican|0": {
    name: "John Flanagan",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-john-flanagan-2019",
  },
  "US|stateSenate|OH|democrat|0": {
    name: "Kenny Yuko",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-kenny-yuko-2019",
  },
  "US|stateSenate|OH|republican|0": {
    name: "Larry Obhof",
    birthYear: 1977,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-larry-obhof-2019",
  },
  "US|stateSenate|OK|democrat|0": {
    name: "Kay Floyd",
    birthYear: 1958,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-kay-floyd-2019",
  },
  "US|stateSenate|OK|republican|0": {
    name: "Greg Treat",
    birthYear: 1978,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-greg-treat-2019",
  },
  "US|stateSenate|OR|democrat|0": {
    name: "Peter Courtney",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-peter-courtney-2019",
  },
  "US|stateSenate|OR|republican|0": {
    name: "Tim Knopp",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-tim-knopp-2019",
  },
  "US|stateSenate|PA|democrat|0": {
    name: "Jay Costa",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-jay-costa-2019",
  },
  "US|stateSenate|PA|republican|0": {
    name: "Joe Scarnati",
    birthYear: 1962,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-joe-scarnati-2019",
  },
  "US|stateSenate|RI|democrat|0": {
    name: "Dominick Ruggerio",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|RI|republican|0": {
    name: "Dennis Algiere",
    birthYear: 1960,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|SC|democrat|0": {
    name: "Nikki Setzler",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|SC|republican|0": {
    name: "Harvey Peeler",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-harvey-peeler-2019",
  },
  "US|stateSenate|SD|democrat|0": {
    name: "Troy Heinert",
    birthYear: 1972,
    gender: "male",
    ethnicity: "other",
  },
  "US|stateSenate|SD|republican|0": {
    name: "Brock Greenfield",
    birthYear: 1975,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|TN|democrat|0": {
    name: "Jeff Yarbro",
    birthYear: 1977,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-jeff-yarbro-2019",
  },
  "US|stateSenate|TN|republican|0": {
    name: "Randy McNally",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-randy-mcnally-2019",
  },
  "US|stateSenate|TX|democrat|0": {
    name: "Carol Alvarado",
    birthYear: 1967,
    gender: "female",
    ethnicity: "hispanic",
    portraitId: "hist-carol-alvarado-2019",
  },
  "US|stateSenate|TX|republican|0": {
    name: "Joan Huffman",
    birthYear: 1956,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-joan-huffman-2019",
  },
  "US|stateSenate|UT|democrat|0": {
    name: "Karen Mayne",
    birthYear: 1946,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-karen-mayne-2019",
  },
  "US|stateSenate|UT|republican|0": {
    name: "Stuart Adams",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-stuart-adams-2019",
  },
  "US|stateSenate|VA|democrat|0": {
    name: "Dick Saslaw",
    birthYear: 1940,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-dick-saslaw-2019",
  },
  "US|stateSenate|VA|republican|0": {
    name: "Tommy Norment",
    birthYear: 1946,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-tommy-norment-2019",
  },
  "US|stateSenate|VT|democrat|0": {
    name: "Tim Ashe",
    birthYear: 1976,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-tim-ashe-2019",
  },
  "US|stateSenate|VT|republican|0": {
    name: "Joe Benning",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-joe-benning-2019",
  },
  "US|stateSenate|WA|democrat|0": {
    name: "Andy Billig",
    birthYear: 1968,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|WA|republican|0": {
    name: "Mark Schoesler",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-mark-schoesler-2019",
  },
  "US|stateSenate|WI|democrat|0": {
    name: "Janet Bewley",
    birthYear: 1951,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-janet-bewley-2019",
  },
  "US|stateSenate|WI|republican|0": {
    name: "Scott Fitzgerald",
    birthYear: 1963,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-scott-fitzgerald-2019",
  },
  "US|stateSenate|WV|democrat|0": {
    name: "Roman Prezioso",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-roman-prezioso-2019",
  },
  "US|stateSenate|WV|republican|0": {
    name: "Mitch Carmichael",
    birthYear: 1960,
    gender: "male",
    ethnicity: "white",
  },
  "US|stateSenate|WY|democrat|0": {
    name: "Chris Rothfuss",
    birthYear: 1972,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-chris-rothfuss-2019",
  },
  "US|stateSenate|WY|republican|0": {
    name: "Drew Perkins",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
  },
};
