import type { RosterMap } from "../historicalRosters";
import { ROSTER_2019_DE_B } from "./p2019-de-b";

const ROSTER_2019_DE_A: RosterMap = {
  "DE|bundestag|BB|de_afd|0": {
    name: "Norbert Kleinwächter",
    birthYear: 1986,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BB|de_cdu|0": {
    name: "Jana Schimke",
    birthYear: 1979,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-jana-schimke-2019",
  },
  "DE|bundestag|BB|de_fdp|0": {
    name: "Linda Teuteberg",
    birthYear: 1981,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-linda-teuteberg-2019",
  },
  "DE|bundestag|BB|de_greens|0": {
    name: "Annalena Baerbock",
    birthYear: 1980,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-annalena-baerbock-2019",
  },
  "DE|bundestag|BB|de_spd|0": {
    name: "Dagmar Ziegler",
    birthYear: 1960,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-dagmar-ziegler-2019",
  },
  "DE|bundestag|BE|de_afd|0": {
    name: "Beatrix von Storch",
    birthYear: 1971,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-beatrix-von-storch-2019",
  },
  "DE|bundestag|BE|de_cdu|0": {
    name: "Kai Wegner",
    birthYear: 1972,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-kai-wegner-2019",
  },
  "DE|bundestag|BE|de_fdp|0": {
    name: "Daniela Kluckert",
    birthYear: 1980,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-daniela-kluckert-2019",
  },
  "DE|bundestag|BE|de_greens|0": {
    name: "Renate Künast",
    birthYear: 1955,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-renate-k-nast-2019",
  },
  "DE|bundestag|BE|de_linke|0": {
    name: "Gregor Gysi",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-gregor-gysi-2019",
  },
  "DE|bundestag|BE|de_spd|0": {
    name: "Eva Högl",
    birthYear: 1969,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-eva-h-gl-2019",
  },
  "DE|bundestag|BRE|de_greens|0": {
    name: "Kirsten Kappert-Gonther",
    birthYear: 1966,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-kirsten-kappert-gonther-2019",
  },
  "DE|bundestag|BRE|de_spd|0": {
    name: "Uwe Schmidt",
    birthYear: 1966,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-uwe-schmidt-2019",
  },
  "DE|bundestag|BW|de_afd|0": {
    name: "Alice Weidel",
    birthYear: 1979,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-alice-weidel-2019",
  },
  "DE|bundestag|BW|de_cdu|0": {
    name: "Wolfgang Schäuble",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-wolfgang-sch-uble-2019",
  },
  "DE|bundestag|BW|de_fdp|0": {
    name: "Michael Theurer",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-michael-theurer-2019",
  },
  "DE|bundestag|BW|de_greens|0": {
    name: "Cem Özdemir",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-cem-zdemir-2019",
  },
  "DE|bundestag|BW|de_linke|0": {
    name: "Heike Hänsel",
    birthYear: 1966,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-heike-h-nsel-2019",
  },
  "DE|bundestag|BW|de_spd|0": {
    name: "Katja Mast",
    birthYear: 1971,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-katja-mast-2019",
  },
  "DE|bundestag|BY|de_afd|0": {
    name: "Stephan Protschka",
    birthYear: 1977,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BY|de_csu|0": {
    name: "Alexander Dobrindt",
    birthYear: 1970,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-alexander-dobrindt-2019",
  },
  "DE|bundestag|BY|de_fdp|0": {
    name: "Daniel Föst",
    birthYear: 1976,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-daniel-f-st-2019",
  },
  "DE|bundestag|BY|de_greens|0": {
    name: "Claudia Roth",
    birthYear: 1955,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-claudia-roth-2019",
  },
  "DE|bundestag|BY|de_spd|0": {
    name: "Bärbel Kofler",
    birthYear: 1967,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-b-rbel-kofler-2019",
  },
  "DE|bundestag|HE|de_afd|0": {
    name: "Albrecht Glaser",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-albrecht-glaser-2019",
  },
  "DE|bundestag|HE|de_cdu|0": {
    name: "Peter Tauber",
    birthYear: 1974,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-peter-tauber-2019",
  },
  "DE|bundestag|HE|de_fdp|0": {
    name: "Bettina Stark-Watzinger",
    birthYear: 1968,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-bettina-stark-watzinger-2019",
  },
  "DE|bundestag|HE|de_greens|0": {
    name: "Omid Nouripour",
    birthYear: 1975,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-omid-nouripour-2019",
  },
  "DE|bundestag|HE|de_linke|0": {
    name: "Christine Buchholz",
    birthYear: 1971,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-christine-buchholz-2019",
  },
  "DE|bundestag|HE|de_spd|0": {
    name: "Sören Bartol",
    birthYear: 1974,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-s-ren-bartol-2019",
  },
  "DE|bundestag|HH|de_cdu|0": {
    name: "Marcus Weinberg",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-marcus-weinberg-2019",
  },
  "DE|bundestag|HH|de_fdp|0": {
    name: "Katja Suding",
    birthYear: 1975,
    gender: "female",
    ethnicity: "white",
    portraitId: "de-katja-suding",
  },
  "DE|bundestag|HH|de_greens|0": {
    name: "Anja Hajduk",
    birthYear: 1963,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-anja-hajduk-2019",
  },
  "DE|bundestag|HH|de_spd|0": {
    name: "Metin Hakverdi",
    birthYear: 1969,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-metin-hakverdi-2019",
  },
  "DE|bundestag|MV|de_afd|0": {
    name: "Leif-Erik Holm",
    birthYear: 1970,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-leif-erik-holm-2019",
  },
  "DE|bundestag|MV|de_cdu|0": {
    name: "Philipp Amthor",
    birthYear: 1992,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-philipp-amthor-2019",
  },
  "DE|bundestag|MV|de_linke|0": {
    name: "Dietmar Bartsch",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-dietmar-bartsch-2019",
  },
  "DE|bundestag|MV|de_spd|0": {
    name: "Frank Junge",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-frank-junge-2019",
  },
  "DE|bundestag|NI|de_afd|0": {
    name: "Armin-Paul Hampel",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-armin-paul-hampel-2019",
  },
  "DE|bundestag|NI|de_cdu|0": {
    name: "Gitta Connemann",
    birthYear: 1964,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-gitta-connemann-2019",
  },
  "DE|bundestag|NI|de_fdp|0": {
    name: "Christian Dürr",
    birthYear: 1977,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-christian-d-rr-2019",
  },
  "DE|bundestag|NI|de_greens|0": {
    name: "Jürgen Trittin",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-j-rgen-trittin-2019",
  },
  "DE|bundestag|NI|de_linke|0": {
    name: "Victor Perli",
    birthYear: 1982,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-victor-perli-2019",
  },
  "DE|bundestag|NI|de_spd|0": {
    name: "Hubertus Heil",
    birthYear: 1972,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-hubertus-heil-2019",
  },
  "DE|bundestag|NW|de_afd|0": {
    name: "Jochen Haug",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-jochen-haug-2019",
  },
  "DE|bundestag|NW|de_cdu|0": {
    name: "Ralph Brinkhaus",
    birthYear: 1968,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-ralph-brinkhaus-2019",
  },
  "DE|bundestag|NW|de_fdp|0": {
    name: "Christian Lindner",
    birthYear: 1979,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-christian-lindner-2019",
  },
  "DE|bundestag|NW|de_greens|0": {
    name: "Britta Haßelmann",
    birthYear: 1961,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-britta-ha-elmann-2019",
  },
  "DE|bundestag|NW|de_linke|0": {
    name: "Sahra Wagenknecht",
    birthYear: 1969,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-sahra-wagenknecht-2019",
  },
  "DE|bundestag|NW|de_spd|0": {
    name: "Rolf Mützenich",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-rolf-m-tzenich-2019",
  },
  "DE|bundestag|RP|de_afd|0": {
    name: "Sebastian Münzenmaier",
    birthYear: 1989,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|RP|de_cdu|0": {
    name: "Julia Klöckner",
    birthYear: 1972,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-julia-kl-ckner-2019",
  },
  "DE|bundestag|RP|de_fdp|0": {
    name: "Manuel Höferlin",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-manuel-h-ferlin-2019",
  },
  "DE|bundestag|RP|de_greens|0": {
    name: "Tabea Rößner",
    birthYear: 1966,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-tabea-r-ner-2019",
  },
  "DE|bundestag|RP|de_linke|0": {
    name: "Alexander Ulrich",
    birthYear: 1971,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-alexander-ulrich-2019",
  },
  "DE|bundestag|RP|de_spd|0": {
    name: "Gustav Herzog",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-gustav-herzog-2019",
  },
  "DE|bundestag|SH|de_afd|0": {
    name: "Bruno Hollnagel",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|SH|de_cdu|0": {
    name: "Johann Wadephul",
    birthYear: 1963,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-johann-wadephul-2019",
  },
  "DE|bundestag|SH|de_fdp|0": {
    name: "Wolfgang Kubicki",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-wolfgang-kubicki-2019",
  },
  "DE|bundestag|SH|de_greens|0": {
    name: "Luise Amtsberg",
    birthYear: 1984,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-luise-amtsberg-2019",
  },
  "DE|bundestag|SH|de_spd|0": {
    name: "Sönke Rix",
    birthYear: 1975,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-s-nke-rix-2019",
  },
  "DE|bundestag|SL|de_cdu|0": {
    name: "Annegret Kramp-Karrenbauer",
    birthYear: 1962,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-annegret-kramp-karrenbauer-2019",
  },
  "DE|bundestag|SL|de_spd|0": {
    name: "Heiko Maas",
    birthYear: 1966,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-heiko-maas-2019",
  },
  "DE|bundestag|SN|de_afd|0": {
    name: "Tino Chrupalla",
    birthYear: 1975,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-tino-chrupalla-2019",
  },
  "DE|bundestag|SN|de_cdu|0": {
    name: "Marco Wanderwitz",
    birthYear: 1975,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-marco-wanderwitz-2019",
  },
  "DE|bundestag|SN|de_fdp|0": {
    name: "Torsten Herbst",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-torsten-herbst-2019",
  },
  "DE|bundestag|SN|de_greens|0": {
    name: "Stephan Kühn",
    birthYear: 1979,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-stephan-k-hn-2019",
  },
  "DE|bundestag|SN|de_linke|0": {
    name: "Caren Lay",
    birthYear: 1972,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-caren-lay-2019",
  },
  "DE|bundestag|SN|de_spd|0": {
    name: "Detlef Müller",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-detlef-m-ller-2019",
  },
  "DE|bundestag|ST|de_afd|0": {
    name: "Martin Reichardt",
    birthYear: 1969,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-martin-reichardt-2019",
  },
  "DE|bundestag|ST|de_cdu|0": {
    name: "Sepp Müller",
    birthYear: 1989,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|ST|de_fdp|0": {
    name: "Marcus Faber",
    birthYear: 1984,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-marcus-faber-2019",
  },
  "DE|bundestag|ST|de_linke|0": {
    name: "Petra Sitte",
    birthYear: 1960,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-petra-sitte-2019",
  },
  "DE|bundestag|ST|de_spd|0": {
    name: "Katrin Budde",
    birthYear: 1965,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-katrin-budde-2019",
  },
  "DE|bundestag|TH|de_afd|0": {
    name: "Stephan Brandner",
    birthYear: 1966,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-stephan-brandner-2019",
  },
  "DE|bundestag|TH|de_cdu|0": {
    name: "Tankred Schipanski",
    birthYear: 1976,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-tankred-schipanski-2019",
  },
  "DE|bundestag|TH|de_fdp|0": {
    name: "Gerald Ullrich",
    birthYear: 1962,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-gerald-ullrich-2019",
  },
  "DE|bundestag|TH|de_linke|0": {
    name: "Martina Renner",
    birthYear: 1967,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-martina-renner-2019",
  },
  "DE|bundestag|TH|de_spd|0": {
    name: "Elisabeth Kaiser",
    birthYear: 1987,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-elisabeth-kaiser-2019",
  },
  "DE|landtag|BB|de_afd|0": {
    name: "Andreas Kalbitz",
    birthYear: 1972,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BB|de_cdu|0": {
    name: "Jan Redmann",
    birthYear: 1979,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BB|de_greens|0": {
    name: "Petra Budke",
    birthYear: 1958,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|BB|de_independent|0": {
    name: "Péter Vida",
    birthYear: 1983,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BB|de_linke|0": {
    name: "Kathrin Dannenberg",
    birthYear: 1966,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|BB|de_spd|0": {
    name: "Erik Stohn",
    birthYear: 1983,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BE|de_afd|0": {
    name: "Georg Pazderski",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BE|de_cdu|0": {
    name: "Burkard Dregger",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BE|de_fdp|0": {
    name: "Sebastian Czaja",
    birthYear: 1983,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BE|de_greens|0": {
    name: "Antje Kapek",
    birthYear: 1976,
    gender: "female",
    ethnicity: "white",
  },
};

export const ROSTER_2019_DE: RosterMap = { ...ROSTER_2019_DE_A, ...ROSTER_2019_DE_B };
