import type { RosterMap } from "../historicalRosters";

export const ROSTER_2019_UK: RosterMap = {
  "UK|commons|EAE|uk_conservative|0": {
    name: "Priti Patel",
    birthYear: 1972,
    gender: "female",
    ethnicity: "asian",
    portraitId: "priti-patel",
  },
  "UK|commons|EAE|uk_labour|0": {
    name: "Clive Lewis",
    birthYear: 1971,
    gender: "male",
    ethnicity: "other",
    portraitId: "clive-lewis",
  },
  "UK|commons|EMI|uk_conservative|0": {
    name: "Robert Jenrick",
    birthYear: 1982,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-robert-jenrick-2019",
  },
  "UK|commons|EMI|uk_labour|0": {
    name: "Margaret Beckett",
    birthYear: 1943,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-margaret-beckett-1991",
  },
  "UK|commons|LON|uk_conservative|0": {
    name: "Boris Johnson",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
    portraitId: "boris-johnson",
  },
  "UK|commons|LON|uk_green|0": {
    name: "Caroline Lucas",
    birthYear: 1960,
    gender: "female",
    ethnicity: "white",
    portraitId: "caroline-lucas",
  },
  "UK|commons|LON|uk_labour|0": {
    name: "Jeremy Corbyn",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
    portraitId: "jeremy-corbyn",
  },
  "UK|commons|LON|uk_libdem|0": {
    name: "Ed Davey",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
    portraitId: "ed-davey",
  },
  "UK|commons|NEE|uk_conservative|0": {
    name: "Anne-Marie Trevelyan",
    birthYear: 1969,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-anne-marie-trevelyan-2019",
  },
  "UK|commons|NEE|uk_labour|0": {
    name: "Kevan Jones",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-kevan-jones-2019",
  },
  "UK|commons|NIR|uk_alliance|0": {
    name: "Stephen Farry",
    birthYear: 1971,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-stephen-farry-2019",
  },
  "UK|commons|NIR|uk_dup|0": {
    name: "Jeffrey Donaldson",
    birthYear: 1962,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-jeffrey-donaldson-2019",
  },
  "UK|commons|NIR|uk_sdlp|0": {
    name: "Colum Eastwood",
    birthYear: 1983,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-colum-eastwood-2019",
  },
  "UK|commons|NIR|uk_sf|0": {
    name: "Michelle Gildernew",
    birthYear: 1970,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-michelle-gildernew-2019",
  },
  "UK|commons|NWE|uk_conservative|0": {
    name: "Esther McVey",
    birthYear: 1967,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-esther-mcvey-2019",
  },
  "UK|commons|NWE|uk_labour|0": {
    name: "Angela Rayner",
    birthYear: 1980,
    gender: "female",
    ethnicity: "white",
    portraitId: "angela-rayner",
  },
  "UK|commons|SCO|uk_conservative|0": {
    name: "David Mundell",
    birthYear: 1962,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-david-mundell-2019",
  },
  "UK|commons|SCO|uk_labour|0": {
    name: "Ian Murray",
    birthYear: 1976,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-ian-murray-2019",
  },
  "UK|commons|SCO|uk_libdem|0": {
    name: "Alistair Carmichael",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-alistair-carmichael-2019",
  },
  "UK|commons|SCO|uk_snp|0": {
    name: "Ian Blackford",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
    portraitId: "ian-blackford",
  },
  "UK|commons|SEE|uk_conservative|0": {
    name: "Dominic Raab",
    birthYear: 1974,
    gender: "male",
    ethnicity: "white",
    portraitId: "dominic-raab",
  },
  "UK|commons|SEE|uk_independent|0": {
    name: "Neale Hanvey",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-neale-hanvey-2019",
  },
  "UK|commons|SEE|uk_labour|0": {
    name: "Peter Kyle",
    birthYear: 1970,
    gender: "male",
    ethnicity: "white",
    portraitId: "peter-kyle",
  },
  "UK|commons|SEE|uk_libdem|0": {
    name: "Layla Moran",
    birthYear: 1982,
    gender: "female",
    ethnicity: "other",
    portraitId: "hist-layla-moran-2019",
  },
  "UK|commons|SEE|uk_speaker|0": {
    name: "Lindsay Hoyle",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-lindsay-hoyle-2019",
  },
  "UK|commons|SWE|uk_conservative|0": {
    name: "Jacob Rees-Mogg",
    birthYear: 1969,
    gender: "male",
    ethnicity: "white",
    portraitId: "jacob-rees-mogg",
  },
  "UK|commons|SWE|uk_labour|0": {
    name: "Ben Bradshaw",
    birthYear: 1960,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-ben-bradshaw-2019",
  },
  "UK|commons|SWE|uk_libdem|0": {
    name: "Wera Hobhouse",
    birthYear: 1960,
    gender: "female",
    ethnicity: "white",
    portraitId: "wera-hobhouse",
  },
  "UK|commons|WAL|uk_conservative|0": {
    name: "Simon Hart",
    birthYear: 1963,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-simon-hart-2019",
  },
  "UK|commons|WAL|uk_labour|0": {
    name: "Nia Griffith",
    birthYear: 1956,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-nia-griffith-2019",
  },
  "UK|commons|WAL|uk_plaid|0": {
    name: "Liz Saville Roberts",
    birthYear: 1964,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-liz-saville-roberts-2019",
  },
  "UK|commons|WMI|uk_conservative|0": {
    name: "Sajid Javid",
    birthYear: 1969,
    gender: "male",
    ethnicity: "asian",
    portraitId: "sajid-javid",
  },
  "UK|commons|WMI|uk_labour|0": {
    name: "Valerie Vaz",
    birthYear: 1954,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-valerie-vaz-2019",
  },
  "UK|commons|YHU|uk_conservative|0": {
    name: "Rishi Sunak",
    birthYear: 1980,
    gender: "male",
    ethnicity: "asian",
    portraitId: "rishi-sunak",
  },
  "UK|commons|YHU|uk_labour|0": {
    name: "Hilary Benn",
    birthYear: 1953,
    gender: "male",
    ethnicity: "white",
    portraitId: "hilary-benn",
  },
  "UK|governor|LON|uk_labour|0": {
    name: "Sadiq Khan",
    birthYear: 1970,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-sadiq-khan-2019",
  },
  "UK|governor|NIR|uk_dup|0": {
    name: "Arlene Foster",
    birthYear: 1970,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-arlene-foster-2019",
  },
  "UK|governor|SCO|uk_snp|0": {
    name: "Nicola Sturgeon",
    birthYear: 1970,
    gender: "female",
    ethnicity: "white",
    portraitId: "nicola-sturgeon",
  },
  "UK|governor|WAL|uk_labour|0": {
    name: "Mark Drakeford",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
    portraitId: "mark-drakeford",
  },
  "UK|regionalCouncil|EAE|uk_conservative|0": {
    name: "Roger Hirst",
    birthYear: 1960,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-roger-hirst-2019",
  },
  "UK|regionalCouncil|EAE|uk_labour|0": {
    name: "Sharon Taylor",
    birthYear: 1956,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-sharon-taylor-2019",
  },
  "UK|regionalCouncil|EAE|uk_libdem|0": {
    name: "Dorothy Thornhill",
    birthYear: 1955,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-dorothy-thornhill-2019",
  },
  "UK|regionalCouncil|EMI|uk_conservative|0": {
    name: "Stephen Mold",
    birthYear: 1968,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-stephen-mold-2019",
  },
  "UK|regionalCouncil|EMI|uk_labour|0": {
    name: "Paddy Tipping",
    birthYear: 1949,
    gender: "male",
    ethnicity: "white",
  },
  "UK|regionalCouncil|EMI|uk_libdem|0": {
    name: "Parmjit Singh Gill",
    birthYear: 1966,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-parmjit-singh-gill-2019",
  },
  "UK|regionalCouncil|LON|uk_conservative|0": {
    name: "Gareth Bacon",
    birthYear: 1972,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-gareth-bacon-2019",
  },
  "UK|regionalCouncil|LON|uk_green|0": {
    name: "Siân Berry",
    birthYear: 1974,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-si-n-berry-2019",
  },
  "UK|regionalCouncil|LON|uk_labour|0": {
    name: "Andrew Dismore",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-andrew-dismore-2019",
  },
  "UK|regionalCouncil|LON|uk_libdem|0": {
    name: "Caroline Pidgeon",
    birthYear: 1972,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-caroline-pidgeon-2019",
  },
  "UK|regionalCouncil|NEE|uk_conservative|0": {
    name: "Ben Houchen",
    birthYear: 1986,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-ben-houchen-2019",
  },
  "UK|regionalCouncil|NEE|uk_labour|0": {
    name: "Kim McGuinness",
    birthYear: 1985,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-kim-mcguinness-2019",
  },
  "UK|regionalCouncil|NIR|uk_alliance|0": {
    name: "Naomi Long",
    birthYear: 1971,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-naomi-long-2019",
  },
  "UK|regionalCouncil|NIR|uk_dup|0": {
    name: "Diane Dodds",
    birthYear: 1958,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-diane-dodds-2019",
  },
  "UK|regionalCouncil|NIR|uk_independent|0": {
    name: "Claire Sugden",
    birthYear: 1986,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-claire-sugden-2019",
  },
  "UK|regionalCouncil|NIR|uk_sdlp|0": {
    name: "Nichola Mallon",
    birthYear: 1979,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-nichola-mallon-2019",
  },
  "UK|regionalCouncil|NIR|uk_sf|0": {
    name: "Michelle O'Neill",
    birthYear: 1977,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-michelle-o-neill-2019",
  },
  "UK|regionalCouncil|NWE|uk_conservative|0": {
    name: "Seema Kennedy",
    birthYear: 1974,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-seema-kennedy-2019",
  },
  "UK|regionalCouncil|NWE|uk_labour|0": {
    name: "Andy Burnham",
    birthYear: 1970,
    gender: "male",
    ethnicity: "white",
    portraitId: "andy-burnham",
  },
  "UK|regionalCouncil|NWE|uk_libdem|0": {
    name: "Tim Farron",
    birthYear: 1970,
    gender: "male",
    ethnicity: "white",
    portraitId: "tim-farron",
  },
  "UK|regionalCouncil|SCO|uk_conservative|0": {
    name: "Ruth Davidson",
    birthYear: 1978,
    gender: "female",
    ethnicity: "white",
    portraitId: "ruth-davidson",
  },
  "UK|regionalCouncil|SCO|uk_green|0": {
    name: "Patrick Harvie",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-patrick-harvie-2019",
  },
  "UK|regionalCouncil|SCO|uk_labour|0": {
    name: "Richard Leonard",
    birthYear: 1962,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-richard-leonard-2019",
  },
  "UK|regionalCouncil|SCO|uk_libdem|0": {
    name: "Willie Rennie",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-willie-rennie-2019",
  },
  "UK|regionalCouncil|SCO|uk_snp|0": {
    name: "John Swinney",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
    portraitId: "john-swinney",
  },
  "UK|regionalCouncil|SEE|uk_conservative|0": {
    name: "Katy Bourne",
    birthYear: 1964,
    gender: "female",
    ethnicity: "white",
  },
  "UK|regionalCouncil|SEE|uk_green|0": {
    name: "Phélim Mac Cafferty",
    birthYear: 1979,
    gender: "male",
    ethnicity: "white",
  },
  "UK|regionalCouncil|SEE|uk_labour|0": {
    name: "Peter Lamb",
    birthYear: 1986,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-peter-lamb-2019",
  },
  "UK|regionalCouncil|SEE|uk_libdem|0": {
    name: "Stephen Lloyd",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-stephen-lloyd-2019",
  },
  "UK|regionalCouncil|SWE|uk_conservative|0": {
    name: "Angus Macpherson",
    birthYear: 1953,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-angus-macpherson-2019",
  },
  "UK|regionalCouncil|SWE|uk_green|0": {
    name: "Carla Denyer",
    birthYear: 1985,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-carla-denyer-2019",
  },
  "UK|regionalCouncil|SWE|uk_labour|0": {
    name: "Marvin Rees",
    birthYear: 1972,
    gender: "male",
    ethnicity: "black",
    portraitId: "hist-marvin-rees-2019",
  },
  "UK|regionalCouncil|SWE|uk_libdem|0": {
    name: "Martin Horwood",
    birthYear: 1962,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-martin-horwood-2019",
  },
  "UK|regionalCouncil|WAL|uk_conservative|0": {
    name: "Paul Davies",
    birthYear: 1969,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-paul-davies-2019",
  },
  "UK|regionalCouncil|WAL|uk_green|0": {
    name: "Amelia Womack",
    birthYear: 1985,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-amelia-womack-2019",
  },
  "UK|regionalCouncil|WAL|uk_independent|0": {
    name: "Dafydd Elis-Thomas",
    birthYear: 1946,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-dafydd-elis-thomas-2019",
  },
  "UK|regionalCouncil|WAL|uk_labour|0": {
    name: "Eluned Morgan",
    birthYear: 1967,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-eluned-morgan-2019",
  },
  "UK|regionalCouncil|WAL|uk_libdem|0": {
    name: "Kirsty Williams",
    birthYear: 1971,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-kirsty-williams-2019",
  },
  "UK|regionalCouncil|WAL|uk_plaid|0": {
    name: "Adam Price",
    birthYear: 1968,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-adam-price-2019",
  },
  "UK|regionalCouncil|WMI|uk_conservative|0": {
    name: "Andy Street",
    birthYear: 1963,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-andy-street-2019",
  },
  "UK|regionalCouncil|WMI|uk_labour|0": {
    name: "David Jamieson",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "UK|regionalCouncil|WMI|uk_libdem|0": {
    name: "John Hemming",
    birthYear: 1960,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-john-hemming-1991",
  },
  "UK|regionalCouncil|YHU|uk_conservative|0": {
    name: "Julia Mulligan",
    birthYear: 1967,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-julia-mulligan-2019",
  },
  "UK|regionalCouncil|YHU|uk_labour|0": {
    name: "Dan Jarvis",
    birthYear: 1972,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-dan-jarvis-2019",
  },
  "UK|regionalCouncil|YHU|uk_libdem|0": {
    name: "Shaffaq Mohammed",
    birthYear: 1972,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-shaffaq-mohammed-2019",
  },
};
