import type { RosterMap } from "../historicalRosters";

export const ROSTER_2019_CN: RosterMap = {
  "CN|governor|DB|cn_ccp|0": {
    name: "Tang Yijun",
    birthYear: 1961,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|governor|HB|cn_ccp|0": {
    name: "Xu Qin",
    birthYear: 1961,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-xu-qin-2019",
  },
  "CN|governor|HD|cn_ccp|0": {
    name: "Gong Zheng",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-gong-zheng-2019",
  },
  "CN|governor|HN|cn_ccp|0": {
    name: "Ma Xingrui",
    birthYear: 1959,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-ma-xingrui-2019",
  },
  "CN|governor|HZ|cn_ccp|0": {
    name: "Wang Xiaodong",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|governor|XB|cn_ccp|0": {
    name: "Liu Guozhong",
    birthYear: 1962,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-liu-guozhong-2019",
  },
  "CN|governor|XN|cn_ccp|0": {
    name: "Yin Li",
    birthYear: 1962,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-yin-li-2019",
  },
  "CN|npcDelegate|DB|cn_ccp|0": {
    name: "Chen Qiufa",
    birthYear: 1954,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|DB|cn_ccp|1": {
    name: "Bayanqolu",
    birthYear: 1955,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|DB|cn_ccp|2": {
    name: "Zhang Qingwei",
    birthYear: 1961,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|DB|cn_ccp|3": {
    name: "Ling Huanxin",
    birthYear: 1962,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|DB|cn_ccp|4": {
    name: "Jing Junhai",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|DB|cn_ccp|5": {
    name: "Wang Wentao",
    birthYear: 1964,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|DB|cn_ccp|6": {
    name: "Zhao Leji",
    birthYear: 1957,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|DB|cn_cdl|0": {
    name: "Ding Zhongli",
    birthYear: 1957,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|DB|cn_cndca|0": {
    name: "Hao Mingjin",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HB|cn_ccp|0": {
    name: "Cai Qi",
    birthYear: 1955,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HB|cn_ccp|1": {
    name: "Li Hongzhong",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HB|cn_ccp|2": {
    name: "Wang Dongfeng",
    birthYear: 1958,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HB|cn_ccp|3": {
    name: "Xi Jinping",
    birthYear: 1953,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HB|cn_ccp|4": {
    name: "Wang Huning",
    birthYear: 1955,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HB|cn_ccp|5": {
    name: "Tan Chengxu",
    birthYear: 1963,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HB|cn_ccp|6": {
    name: "Bu Xiaolin",
    birthYear: 1958,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HB|cn_cdl|0": {
    name: "Chen Xiaoguang",
    birthYear: 1955,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HB|cn_cndca|0": {
    name: "Gu Shengzu",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HD|cn_ccp|0": {
    name: "Li Qiang",
    birthYear: 1959,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HD|cn_ccp|1": {
    name: "Lou Qinjian",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HD|cn_ccp|2": {
    name: "Che Jun",
    birthYear: 1955,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HD|cn_ccp|3": {
    name: "Liu Qi",
    birthYear: 1957,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HD|cn_ccp|4": {
    name: "Liu Jiayi",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HD|cn_ccp|5": {
    name: "Li Zhanshu",
    birthYear: 1950,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HD|cn_ccp|6": {
    name: "Chen Qiuhua",
    birthYear: 1964,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HD|cn_cdl|0": {
    name: "Ouyang Minggao",
    birthYear: 1958,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HD|cn_cndca|0": {
    name: "Zhang Shaoqin",
    birthYear: 1953,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HN|cn_ccp|0": {
    name: "Li Xi",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HN|cn_ccp|1": {
    name: "Lu Xinshe",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HN|cn_ccp|2": {
    name: "Liu Cigui",
    birthYear: 1955,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HN|cn_ccp|3": {
    name: "Zhao Dachun",
    birthYear: 1970,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HN|cn_ccp|4": {
    name: "Chen Wu",
    birthYear: 1954,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HN|cn_ccp|5": {
    name: "Shen Xiaoming",
    birthYear: 1963,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HN|cn_ccp|6": {
    name: "Li Keqiang",
    birthYear: 1955,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HN|cn_cdl|0": {
    name: "Wang Guangqian",
    birthYear: 1962,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HN|cn_cndca|0": {
    name: "Li Shijie",
    birthYear: 1957,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HZ|cn_ccp|0": {
    name: "Wang Guosheng",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HZ|cn_ccp|1": {
    name: "Jiang Chaoliang",
    birthYear: 1957,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HZ|cn_ccp|2": {
    name: "Du Jiahao",
    birthYear: 1955,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HZ|cn_ccp|3": {
    name: "Chen Run'er",
    birthYear: 1957,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HZ|cn_ccp|4": {
    name: "Cao Jie",
    birthYear: 1966,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HZ|cn_ccp|5": {
    name: "Xu Dazhe",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HZ|cn_ccp|6": {
    name: "Wang Qishan",
    birthYear: 1948,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HZ|cn_cdl|0": {
    name: "Tian Gang",
    birthYear: 1958,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|HZ|cn_cndca|0": {
    name: "Qin Boyong",
    birthYear: 1964,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XB|cn_ccp|0": {
    name: "Hu Heping",
    birthYear: 1962,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XB|cn_ccp|1": {
    name: "Lin Duo",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XB|cn_ccp|2": {
    name: "Chen Quanguo",
    birthYear: 1955,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XB|cn_ccp|3": {
    name: "Han Zheng",
    birthYear: 1954,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XB|cn_ccp|4": {
    name: "Xian Hui",
    birthYear: 1958,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XB|cn_ccp|5": {
    name: "Shohrat Zakir",
    birthYear: 1953,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XB|cn_ccp|6": {
    name: "Liu Ning",
    birthYear: 1962,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XB|cn_cdl|0": {
    name: "Deng Xiuxin",
    birthYear: 1961,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XB|cn_cndca|0": {
    name: "Sun Dongsheng",
    birthYear: 1964,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XN|cn_ccp|0": {
    name: "Chen Min'er",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XN|cn_ccp|1": {
    name: "Peng Qinghua",
    birthYear: 1957,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XN|cn_ccp|2": {
    name: "Sun Zhigang",
    birthYear: 1954,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XN|cn_ccp|3": {
    name: "Chen Hao",
    birthYear: 1954,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XN|cn_ccp|4": {
    name: "Wu Yingjie",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XN|cn_ccp|5": {
    name: "Tang Liangzhi",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XN|cn_ccp|6": {
    name: "Wang Yang",
    birthYear: 1955,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XN|cn_cdl|0": {
    name: "Cheng Hong",
    birthYear: 1957,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|npcDelegate|XN|cn_cndca|0": {
    name: "Chen Changzhi",
    birthYear: 1945,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|DB|cn_ccp|0": {
    name: "Xu Lili",
    birthYear: 1952,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|DB|cn_ccp|1": {
    name: "Li Yumei",
    birthYear: 1956,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|DB|cn_ccp|2": {
    name: "Liu Hui",
    birthYear: 1959,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|DB|cn_ccp|3": {
    name: "Du Meishuang",
    birthYear: 1965,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|DB|cn_ccp|4": {
    name: "Chen Wei",
    birthYear: 1966,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|DB|cn_ccp|5": {
    name: "Lu Zhangong",
    birthYear: 1952,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|DB|cn_ccp|6": {
    name: "Arken Imirbaki",
    birthYear: 1953,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|DB|cn_cdl|0": {
    name: "Q16907501",
    birthYear: 1950,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|DB|cn_cndca|0": {
    name: "Ton Gruochun",
    birthYear: 1948,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HB|cn_ccp|0": {
    name: "Qiang Wei",
    birthYear: 1953,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HB|cn_ccp|1": {
    name: "Yang Xiong",
    birthYear: 1953,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HB|cn_ccp|2": {
    name: "Yang Jing",
    birthYear: 1953,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HB|cn_ccp|3": {
    name: "You Quan",
    birthYear: 1954,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HB|cn_ccp|4": {
    name: "Wei Fenghe",
    birthYear: 1954,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HB|cn_ccp|5": {
    name: "Xie Fuzhan",
    birthYear: 1954,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HB|cn_ccp|6": {
    name: "Yu Weiguo",
    birthYear: 1955,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HB|cn_cdl|0": {
    name: "Guo Hongmei",
    birthYear: 1973,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HB|cn_cndca|0": {
    name: "Q11102274",
    birthYear: 1970,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HD|cn_ccp|0": {
    name: "Jiang Jiemin",
    birthYear: 1955,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HD|cn_ccp|1": {
    name: "Lin Jianhua",
    birthYear: 1955,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HD|cn_ccp|2": {
    name: "Chen Xuyuan",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HD|cn_ccp|3": {
    name: "Wang Yupu",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HD|cn_ccp|4": {
    name: "Liu Kun",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HD|cn_ccp|5": {
    name: "Wang Zhengwei",
    birthYear: 1957,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HD|cn_ccp|6": {
    name: "Li Jinbin",
    birthYear: 1958,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HD|cn_cdl|0": {
    name: "Bao Yizhi",
    birthYear: 1951,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HD|cn_cndca|0": {
    name: "Hu Zhenpeng",
    birthYear: 1948,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HN|cn_ccp|0": {
    name: "Wang Menghui",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HN|cn_ccp|1": {
    name: "Hao Peng",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HN|cn_ccp|2": {
    name: "Zhang Gong",
    birthYear: 1961,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HN|cn_ccp|3": {
    name: "Chen Daoxiang",
    birthYear: 1962,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HN|cn_ccp|4": {
    name: "Yang Xiaoming",
    birthYear: 1962,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HN|cn_ccp|5": {
    name: "Lai Xiaomin",
    birthYear: 1962,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HN|cn_ccp|6": {
    name: "Wang Xiangxi",
    birthYear: 1962,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HN|cn_cdl|0": {
    name: "Zheng Yongfei",
    birthYear: 1959,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HN|cn_cndca|0": {
    name: "Jin Zhanzhong",
    birthYear: 1962,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HZ|cn_ccp|0": {
    name: "Li Shangfu",
    birthYear: 1958,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HZ|cn_ccp|1": {
    name: "Q10895425",
    birthYear: 1958,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HZ|cn_ccp|2": {
    name: "Gong Shuguang",
    birthYear: 1959,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HZ|cn_ccp|3": {
    name: "Qurmaş Sırjanulı",
    birthYear: 1959,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HZ|cn_ccp|4": {
    name: "Li Xiaopeng",
    birthYear: 1959,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HZ|cn_ccp|5": {
    name: "Li Fengbiao",
    birthYear: 1959,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HZ|cn_ccp|6": {
    name: "Hou Jianguo",
    birthYear: 1959,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HZ|cn_cdl|0": {
    name: "Q16906840",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|HZ|cn_cndca|0": {
    name: "Q9209522",
    birthYear: 1957,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XB|cn_ccp|0": {
    name: "Q9365430",
    birthYear: 1963,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XB|cn_ccp|1": {
    name: "Zhao Huijie",
    birthYear: 1970,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XB|cn_ccp|2": {
    name: "Sun Jianguo",
    birthYear: 1955,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XB|cn_ccp|3": {
    name: "Q16906331",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XB|cn_ccp|4": {
    name: "Q11066789",
    birthYear: 1957,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XB|cn_ccp|5": {
    name: "Zhu Zhiyuan",
    birthYear: 1959,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XB|cn_ccp|6": {
    name: "Li Qilin",
    birthYear: 1961,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XB|cn_cdl|0": {
    name: "Q9204187",
    birthYear: 1970,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XB|cn_cndca|0": {
    name: "Q9321099",
    birthYear: 1979,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XN|cn_ccp|0": {
    name: "Wang Zhengpu",
    birthYear: 1963,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XN|cn_ccp|1": {
    name: "Zhou Xianwang",
    birthYear: 1963,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XN|cn_ccp|2": {
    name: "Zheng Xincong",
    birthYear: 1963,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XN|cn_ccp|3": {
    name: "Li Guoying",
    birthYear: 1963,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XN|cn_ccp|4": {
    name: "Lu Hao",
    birthYear: 1967,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XN|cn_ccp|5": {
    name: "Fei Dongbin",
    birthYear: 1970,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XN|cn_ccp|6": {
    name: "Fang Xin",
    birthYear: 1955,
    gender: "female",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XN|cn_cdl|0": {
    name: "Q16906164",
    birthYear: 1963,
    gender: "male",
    ethnicity: "asian",
  },
  "CN|peoplesCongress|XN|cn_cndca|0": {
    name: "Liu Hanyuan",
    birthYear: 1964,
    gender: "male",
    ethnicity: "asian",
  },
};
