import type { RosterMap } from "../historicalRosters";

export const ROSTER_2019_DE: RosterMap = {
  "DE|bundestag|BB|de_afd|0": {
    name: "Norbert Kleinwächter",
    birthYear: 1986,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BB|de_cdu|0": {
    name: "Jana Schimke",
    birthYear: 1979,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-jana-schimke-2019",
  },
  "DE|bundestag|BB|de_fdp|0": {
    name: "Linda Teuteberg",
    birthYear: 1981,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-linda-teuteberg-2019",
  },
  "DE|bundestag|BB|de_greens|0": {
    name: "Annalena Baerbock",
    birthYear: 1980,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-annalena-baerbock-2019",
  },
  "DE|bundestag|BB|de_spd|0": {
    name: "Dagmar Ziegler",
    birthYear: 1960,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-dagmar-ziegler-2019",
  },
  "DE|bundestag|BE|de_afd|0": {
    name: "Beatrix von Storch",
    birthYear: 1971,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-beatrix-von-storch-2019",
  },
  "DE|bundestag|BE|de_cdu|0": {
    name: "Kai Wegner",
    birthYear: 1972,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-kai-wegner-2019",
  },
  "DE|bundestag|BE|de_fdp|0": {
    name: "Daniela Kluckert",
    birthYear: 1980,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-daniela-kluckert-2019",
  },
  "DE|bundestag|BE|de_greens|0": {
    name: "Renate Künast",
    birthYear: 1955,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-renate-k-nast-2019",
  },
  "DE|bundestag|BE|de_linke|0": {
    name: "Gregor Gysi",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-gregor-gysi-2019",
  },
  "DE|bundestag|BE|de_spd|0": {
    name: "Eva Högl",
    birthYear: 1969,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-eva-h-gl-2019",
  },
  "DE|bundestag|BRE|de_greens|0": {
    name: "Kirsten Kappert-Gonther",
    birthYear: 1966,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-kirsten-kappert-gonther-2019",
  },
  "DE|bundestag|BRE|de_spd|0": {
    name: "Uwe Schmidt",
    birthYear: 1966,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-uwe-schmidt-2019",
  },
  "DE|bundestag|BW|de_afd|0": {
    name: "Alice Weidel",
    birthYear: 1979,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-alice-weidel-2019",
  },
  "DE|bundestag|BW|de_cdu|0": {
    name: "Wolfgang Schäuble",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-wolfgang-sch-uble-2019",
  },
  "DE|bundestag|BW|de_fdp|0": {
    name: "Michael Theurer",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-michael-theurer-2019",
  },
  "DE|bundestag|BW|de_greens|0": {
    name: "Cem Özdemir",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-cem-zdemir-2019",
  },
  "DE|bundestag|BW|de_linke|0": {
    name: "Heike Hänsel",
    birthYear: 1966,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-heike-h-nsel-2019",
  },
  "DE|bundestag|BW|de_spd|0": {
    name: "Katja Mast",
    birthYear: 1971,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-katja-mast-2019",
  },
  "DE|bundestag|BY|de_afd|0": {
    name: "Stephan Protschka",
    birthYear: 1977,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|BY|de_csu|0": {
    name: "Alexander Dobrindt",
    birthYear: 1970,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-alexander-dobrindt-2019",
  },
  "DE|bundestag|BY|de_fdp|0": {
    name: "Daniel Föst",
    birthYear: 1976,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-daniel-f-st-2019",
  },
  "DE|bundestag|BY|de_greens|0": {
    name: "Claudia Roth",
    birthYear: 1955,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-claudia-roth-2019",
  },
  "DE|bundestag|BY|de_spd|0": {
    name: "Bärbel Kofler",
    birthYear: 1967,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-b-rbel-kofler-2019",
  },
  "DE|bundestag|HE|de_afd|0": {
    name: "Albrecht Glaser",
    birthYear: 1942,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-albrecht-glaser-2019",
  },
  "DE|bundestag|HE|de_cdu|0": {
    name: "Peter Tauber",
    birthYear: 1974,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-peter-tauber-2019",
  },
  "DE|bundestag|HE|de_fdp|0": {
    name: "Bettina Stark-Watzinger",
    birthYear: 1968,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-bettina-stark-watzinger-2019",
  },
  "DE|bundestag|HE|de_greens|0": {
    name: "Omid Nouripour",
    birthYear: 1975,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-omid-nouripour-2019",
  },
  "DE|bundestag|HE|de_linke|0": {
    name: "Christine Buchholz",
    birthYear: 1971,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-christine-buchholz-2019",
  },
  "DE|bundestag|HE|de_spd|0": {
    name: "Sören Bartol",
    birthYear: 1974,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-s-ren-bartol-2019",
  },
  "DE|bundestag|HH|de_cdu|0": {
    name: "Marcus Weinberg",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-marcus-weinberg-2019",
  },
  "DE|bundestag|HH|de_fdp|0": {
    name: "Katja Suding",
    birthYear: 1975,
    gender: "female",
    ethnicity: "white",
    portraitId: "de-katja-suding",
  },
  "DE|bundestag|HH|de_greens|0": {
    name: "Anja Hajduk",
    birthYear: 1963,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-anja-hajduk-2019",
  },
  "DE|bundestag|HH|de_spd|0": {
    name: "Metin Hakverdi",
    birthYear: 1969,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-metin-hakverdi-2019",
  },
  "DE|bundestag|MV|de_afd|0": {
    name: "Leif-Erik Holm",
    birthYear: 1970,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-leif-erik-holm-2019",
  },
  "DE|bundestag|MV|de_cdu|0": {
    name: "Philipp Amthor",
    birthYear: 1992,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-philipp-amthor-2019",
  },
  "DE|bundestag|MV|de_linke|0": {
    name: "Dietmar Bartsch",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-dietmar-bartsch-2019",
  },
  "DE|bundestag|MV|de_spd|0": {
    name: "Frank Junge",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-frank-junge-2019",
  },
  "DE|bundestag|NI|de_afd|0": {
    name: "Armin-Paul Hampel",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-armin-paul-hampel-2019",
  },
  "DE|bundestag|NI|de_cdu|0": {
    name: "Gitta Connemann",
    birthYear: 1964,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-gitta-connemann-2019",
  },
  "DE|bundestag|NI|de_fdp|0": {
    name: "Christian Dürr",
    birthYear: 1977,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-christian-d-rr-2019",
  },
  "DE|bundestag|NI|de_greens|0": {
    name: "Jürgen Trittin",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-j-rgen-trittin-2019",
  },
  "DE|bundestag|NI|de_linke|0": {
    name: "Victor Perli",
    birthYear: 1982,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-victor-perli-2019",
  },
  "DE|bundestag|NI|de_spd|0": {
    name: "Hubertus Heil",
    birthYear: 1972,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-hubertus-heil-2019",
  },
  "DE|bundestag|NW|de_afd|0": {
    name: "Jochen Haug",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-jochen-haug-2019",
  },
  "DE|bundestag|NW|de_cdu|0": {
    name: "Ralph Brinkhaus",
    birthYear: 1968,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-ralph-brinkhaus-2019",
  },
  "DE|bundestag|NW|de_fdp|0": {
    name: "Christian Lindner",
    birthYear: 1979,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-christian-lindner-2019",
  },
  "DE|bundestag|NW|de_greens|0": {
    name: "Britta Haßelmann",
    birthYear: 1961,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-britta-ha-elmann-2019",
  },
  "DE|bundestag|NW|de_linke|0": {
    name: "Sahra Wagenknecht",
    birthYear: 1969,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-sahra-wagenknecht-2019",
  },
  "DE|bundestag|NW|de_spd|0": {
    name: "Rolf Mützenich",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-rolf-m-tzenich-2019",
  },
  "DE|bundestag|RP|de_afd|0": {
    name: "Sebastian Münzenmaier",
    birthYear: 1989,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|RP|de_cdu|0": {
    name: "Julia Klöckner",
    birthYear: 1972,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-julia-kl-ckner-2019",
  },
  "DE|bundestag|RP|de_fdp|0": {
    name: "Manuel Höferlin",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-manuel-h-ferlin-2019",
  },
  "DE|bundestag|RP|de_greens|0": {
    name: "Tabea Rößner",
    birthYear: 1966,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-tabea-r-ner-2019",
  },
  "DE|bundestag|RP|de_linke|0": {
    name: "Alexander Ulrich",
    birthYear: 1971,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-alexander-ulrich-2019",
  },
  "DE|bundestag|RP|de_spd|0": {
    name: "Gustav Herzog",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-gustav-herzog-2019",
  },
  "DE|bundestag|SH|de_afd|0": {
    name: "Bruno Hollnagel",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|SH|de_cdu|0": {
    name: "Johann Wadephul",
    birthYear: 1963,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-johann-wadephul-2019",
  },
  "DE|bundestag|SH|de_fdp|0": {
    name: "Wolfgang Kubicki",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-wolfgang-kubicki-2019",
  },
  "DE|bundestag|SH|de_greens|0": {
    name: "Luise Amtsberg",
    birthYear: 1984,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-luise-amtsberg-2019",
  },
  "DE|bundestag|SH|de_spd|0": {
    name: "Sönke Rix",
    birthYear: 1975,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-s-nke-rix-2019",
  },
  "DE|bundestag|SL|de_cdu|0": {
    name: "Annegret Kramp-Karrenbauer",
    birthYear: 1962,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-annegret-kramp-karrenbauer-2019",
  },
  "DE|bundestag|SL|de_spd|0": {
    name: "Heiko Maas",
    birthYear: 1966,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-heiko-maas-2019",
  },
  "DE|bundestag|SN|de_afd|0": {
    name: "Tino Chrupalla",
    birthYear: 1975,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-tino-chrupalla-2019",
  },
  "DE|bundestag|SN|de_cdu|0": {
    name: "Marco Wanderwitz",
    birthYear: 1975,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-marco-wanderwitz-2019",
  },
  "DE|bundestag|SN|de_fdp|0": {
    name: "Torsten Herbst",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-torsten-herbst-2019",
  },
  "DE|bundestag|SN|de_greens|0": {
    name: "Stephan Kühn",
    birthYear: 1979,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-stephan-k-hn-2019",
  },
  "DE|bundestag|SN|de_linke|0": {
    name: "Caren Lay",
    birthYear: 1972,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-caren-lay-2019",
  },
  "DE|bundestag|SN|de_spd|0": {
    name: "Detlef Müller",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-detlef-m-ller-2019",
  },
  "DE|bundestag|ST|de_afd|0": {
    name: "Martin Reichardt",
    birthYear: 1969,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-martin-reichardt-2019",
  },
  "DE|bundestag|ST|de_cdu|0": {
    name: "Sepp Müller",
    birthYear: 1989,
    gender: "male",
    ethnicity: "white",
  },
  "DE|bundestag|ST|de_fdp|0": {
    name: "Marcus Faber",
    birthYear: 1984,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-marcus-faber-2019",
  },
  "DE|bundestag|ST|de_linke|0": {
    name: "Petra Sitte",
    birthYear: 1960,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-petra-sitte-2019",
  },
  "DE|bundestag|ST|de_spd|0": {
    name: "Katrin Budde",
    birthYear: 1965,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-katrin-budde-2019",
  },
  "DE|bundestag|TH|de_afd|0": {
    name: "Stephan Brandner",
    birthYear: 1966,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-stephan-brandner-2019",
  },
  "DE|bundestag|TH|de_cdu|0": {
    name: "Tankred Schipanski",
    birthYear: 1976,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-tankred-schipanski-2019",
  },
  "DE|bundestag|TH|de_fdp|0": {
    name: "Gerald Ullrich",
    birthYear: 1962,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-gerald-ullrich-2019",
  },
  "DE|bundestag|TH|de_linke|0": {
    name: "Martina Renner",
    birthYear: 1967,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-martina-renner-2019",
  },
  "DE|bundestag|TH|de_spd|0": {
    name: "Elisabeth Kaiser",
    birthYear: 1987,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-elisabeth-kaiser-2019",
  },
  "DE|landtag|BB|de_afd|0": {
    name: "Andreas Kalbitz",
    birthYear: 1972,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BB|de_cdu|0": {
    name: "Jan Redmann",
    birthYear: 1979,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BB|de_greens|0": {
    name: "Petra Budke",
    birthYear: 1958,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|BB|de_independent|0": {
    name: "Péter Vida",
    birthYear: 1983,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BB|de_linke|0": {
    name: "Kathrin Dannenberg",
    birthYear: 1966,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|BB|de_spd|0": {
    name: "Erik Stohn",
    birthYear: 1983,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BE|de_afd|0": {
    name: "Georg Pazderski",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BE|de_cdu|0": {
    name: "Burkard Dregger",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BE|de_fdp|0": {
    name: "Sebastian Czaja",
    birthYear: 1983,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BE|de_greens|0": {
    name: "Antje Kapek",
    birthYear: 1976,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|BE|de_linke|0": {
    name: "Udo Wolf",
    birthYear: 1962,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BE|de_spd|0": {
    name: "Raed Saleh",
    birthYear: 1977,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BRE|de_afd|0": {
    name: "Frank Magnitz",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BRE|de_cdu|0": {
    name: "Thomas Röwekamp",
    birthYear: 1966,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BRE|de_fdp|0": {
    name: "Lencke Wischhusen",
    birthYear: 1985,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|BRE|de_greens|0": {
    name: "Maike Schaefer",
    birthYear: 1971,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|BRE|de_independent|0": {
    name: "Jan Timke",
    birthYear: 1971,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BRE|de_linke|0": {
    name: "Kristina Vogt",
    birthYear: 1965,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|BRE|de_spd|0": {
    name: "Mustafa Güngör",
    birthYear: 1978,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BW|de_afd|0": {
    name: "Bernd Gögel",
    birthYear: 1955,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BW|de_cdu|0": {
    name: "Wolfgang Reinhart",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BW|de_fdp|0": {
    name: "Hans-Ulrich Rülke",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BW|de_greens|0": {
    name: "Andreas Schwarz",
    birthYear: 1979,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BW|de_independent|0": {
    name: "Wolfgang Gedeon",
    birthYear: 1947,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BW|de_spd|0": {
    name: "Andreas Stoch",
    birthYear: 1969,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BY|de_afd|0": {
    name: "Katrin Ebner-Steiner",
    birthYear: 1978,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|BY|de_csu|0": {
    name: "Thomas Kreuzer",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BY|de_fdp|0": {
    name: "Martin Hagen",
    birthYear: 1981,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BY|de_greens|0": {
    name: "Katharina Schulze",
    birthYear: 1985,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|BY|de_independent|0": {
    name: "Hubert Aiwanger",
    birthYear: 1971,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|BY|de_spd|0": {
    name: "Horst Arnold",
    birthYear: 1962,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HE|de_afd|0": {
    name: "Robert Lambrou",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HE|de_cdu|0": {
    name: "Michael Boddenberg",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HE|de_fdp|0": {
    name: "René Rock",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HE|de_greens|0": {
    name: "Mathias Wagner",
    birthYear: 1974,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HE|de_linke|0": {
    name: "Janine Wissler",
    birthYear: 1981,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|HE|de_spd|0": {
    name: "Nancy Faeser",
    birthYear: 1970,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|HH|de_afd|0": {
    name: "Dirk Nockemann",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HH|de_cdu|0": {
    name: "André Trepoll",
    birthYear: 1977,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HH|de_fdp|0": {
    name: "Michael Kruse",
    birthYear: 1983,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HH|de_greens|0": {
    name: "Anjes Tjarks",
    birthYear: 1981,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|HH|de_linke|0": {
    name: "Sabine Boeddinghaus",
    birthYear: 1957,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|HH|de_spd|0": {
    name: "Dirk Kienscherf",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|MV|de_afd|0": {
    name: "Nikolaus Kramer",
    birthYear: 1976,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|MV|de_cdu|0": {
    name: "Vincent Kokert",
    birthYear: 1978,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|MV|de_independent|0": {
    name: "Christel Weißig",
    birthYear: 1945,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|MV|de_linke|0": {
    name: "Simone Oldenburg",
    birthYear: 1969,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|MV|de_spd|0": {
    name: "Thomas Krüger",
    birthYear: 1969,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|NI|de_afd|0": {
    name: "Dana Guth",
    birthYear: 1970,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|NI|de_cdu|0": {
    name: "Dirk Toepffer",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|NI|de_fdp|0": {
    name: "Stefan Birkner",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|NI|de_greens|0": {
    name: "Anja Piel",
    birthYear: 1965,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|NI|de_spd|0": {
    name: "Johanne Modder",
    birthYear: 1960,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|NW|de_afd|0": {
    name: "Markus Wagner",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|NW|de_cdu|0": {
    name: "Bodo Löttgen",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|NW|de_fdp|0": {
    name: "Christof Rasche",
    birthYear: 1962,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|NW|de_greens|0": {
    name: "Monika Düker",
    birthYear: 1963,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|NW|de_independent|0": {
    name: "Marcus Pretzell",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|NW|de_spd|0": {
    name: "Thomas Kutschaty",
    birthYear: 1968,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|RP|de_afd|0": {
    name: "Uwe Junge",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|RP|de_cdu|0": {
    name: "Christian Baldauf",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|RP|de_fdp|0": {
    name: "Cornelia Willius-Senzer",
    birthYear: 1943,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|RP|de_greens|0": {
    name: "Bernhard Braun",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|RP|de_spd|0": {
    name: "Alexander Schweitzer",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SH|de_afd|0": {
    name: "Jörg Nobis",
    birthYear: 1975,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SH|de_cdu|0": {
    name: "Tobias Koch",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SH|de_fdp|0": {
    name: "Christopher Vogt",
    birthYear: 1984,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SH|de_greens|0": {
    name: "Eka von Kalben",
    birthYear: 1964,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|SH|de_independent|0": {
    name: "Lars Harms",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SH|de_spd|0": {
    name: "Ralf Stegner",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SL|de_afd|0": {
    name: "Josef Dörr",
    birthYear: 1938,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SL|de_cdu|0": {
    name: "Klaus Meiser",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SL|de_linke|0": {
    name: "Oskar Lafontaine",
    birthYear: 1943,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SL|de_spd|0": {
    name: "Anke Rehlinger",
    birthYear: 1976,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|SN|de_afd|0": {
    name: "Jörg Urban",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SN|de_cdu|0": {
    name: "Christian Hartmann",
    birthYear: 1974,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SN|de_greens|0": {
    name: "Franziska Schubert",
    birthYear: 1982,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|SN|de_independent|0": {
    name: "Ivo Teichmann",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SN|de_linke|0": {
    name: "Rico Gebhardt",
    birthYear: 1963,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|SN|de_spd|0": {
    name: "Dirk Panter",
    birthYear: 1974,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|ST|de_afd|0": {
    name: "Oliver Kirchner",
    birthYear: 1966,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|ST|de_cdu|0": {
    name: "Siegfried Borgwardt",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|ST|de_greens|0": {
    name: "Cornelia Lüddemann",
    birthYear: 1968,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|ST|de_independent|0": {
    name: "Sarah Sauermann",
    birthYear: 1988,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|ST|de_linke|0": {
    name: "Thomas Lippmann",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|ST|de_spd|0": {
    name: "Katja Pähle",
    birthYear: 1977,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|TH|de_afd|0": {
    name: "Björn Höcke",
    birthYear: 1972,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|TH|de_cdu|0": {
    name: "Mike Mohring",
    birthYear: 1971,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|TH|de_fdp|0": {
    name: "Thomas Kemmerich",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
  },
  "DE|landtag|TH|de_greens|0": {
    name: "Astrid Rothe-Beinlich",
    birthYear: 1973,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|TH|de_linke|0": {
    name: "Susanne Hennig-Wellsow",
    birthYear: 1977,
    gender: "female",
    ethnicity: "white",
  },
  "DE|landtag|TH|de_spd|0": {
    name: "Matthias Hey",
    birthYear: 1970,
    gender: "male",
    ethnicity: "white",
  },
  "DE|ministerPresident|BB|de_spd|0": {
    name: "Dietmar Woidke",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-dietmar-woidke-2019",
  },
  "DE|ministerPresident|BE|de_spd|0": {
    name: "Michael Müller",
    birthYear: 1964,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-michael-m-ller-2019",
  },
  "DE|ministerPresident|BRE|de_spd|0": {
    name: "Andreas Bovenschulte",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-andreas-bovenschulte-2019",
  },
  "DE|ministerPresident|BW|de_greens|0": {
    name: "Winfried Kretschmann",
    birthYear: 1948,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-winfried-kretschmann-2019",
  },
  "DE|ministerPresident|BY|de_csu|0": {
    name: "Markus Söder",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-markus-s-der-2019",
  },
  "DE|ministerPresident|HE|de_cdu|0": {
    name: "Volker Bouffier",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-volker-bouffier-2019",
  },
  "DE|ministerPresident|HH|de_spd|0": {
    name: "Peter Tschentscher",
    birthYear: 1966,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-peter-tschentscher-2019",
  },
  "DE|ministerPresident|MV|de_spd|0": {
    name: "Manuela Schwesig",
    birthYear: 1974,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-manuela-schwesig-2019",
  },
  "DE|ministerPresident|NI|de_spd|0": {
    name: "Stephan Weil",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-stephan-weil-2019",
  },
  "DE|ministerPresident|NW|de_cdu|0": {
    name: "Armin Laschet",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-armin-laschet-2019",
  },
  "DE|ministerPresident|RP|de_spd|0": {
    name: "Malu Dreyer",
    birthYear: 1961,
    gender: "female",
    ethnicity: "white",
    portraitId: "hist-malu-dreyer-2019",
  },
  "DE|ministerPresident|SH|de_cdu|0": {
    name: "Daniel Günther",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-daniel-g-nther-2019",
  },
  "DE|ministerPresident|SL|de_cdu|0": {
    name: "Tobias Hans",
    birthYear: 1978,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-tobias-hans-2019",
  },
  "DE|ministerPresident|SN|de_cdu|0": {
    name: "Michael Kretschmer",
    birthYear: 1975,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-michael-kretschmer-2019",
  },
  "DE|ministerPresident|ST|de_cdu|0": {
    name: "Reiner Haseloff",
    birthYear: 1954,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-reiner-haseloff-2019",
  },
  "DE|ministerPresident|TH|de_linke|0": {
    name: "Bodo Ramelow",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
    portraitId: "hist-bodo-ramelow-2019",
  },
};
