import type { RosterMap } from "../historicalRosters";

export const ROSTER_2019_JP: RosterMap = {
  "JP|governor|CGK|jp_ldp|0": {
    name: "Hidehiko Yuzaki",
    birthYear: 1965,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-hidehiko-yuzaki-2019",
  },
  "JP|governor|CHU|jp_ldp|0": {
    name: "Hideaki Omura",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-hideaki-omura-2019",
  },
  "JP|governor|HOK|jp_ldp|0": {
    name: "Naomichi Suzuki",
    birthYear: 1981,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-naomichi-suzuki-2019",
  },
  "JP|governor|KAN|jp_ldp|0": {
    name: "Yuriko Koike",
    birthYear: 1952,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-yuriko-koike-2019",
  },
  "JP|governor|KNS|jp_ldp|0": {
    name: "Hirofumi Yoshimura",
    birthYear: 1975,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-hirofumi-yoshimura-2019",
  },
  "JP|governor|KYU|jp_ldp|0": {
    name: "Hiroshi Ogawa",
    birthYear: 1949,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-hiroshi-ogawa-2019",
  },
  "JP|governor|SHI|jp_ldp|0": {
    name: "Kamon Iizumi",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|governor|TOH|jp_ldp|0": {
    name: "Yoshihiro Murai",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-yoshihiro-murai-2019",
  },
  "JP|regionalCouncil|CGK|jp_cdp|0": {
    name: "Takashi Takai",
    birthYear: 1969,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CGK|jp_dpfp|0": {
    name: "Michiyoshi Yunoki",
    birthYear: 1972,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CGK|jp_ishin|0": {
    name: "Takeshi Yoshimura",
    birthYear: 1946,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CGK|jp_jcp|0": {
    name: "Sohei Nihi",
    birthYear: 1963,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CGK|jp_komeito|0": {
    name: "Kanae Yamamoto",
    birthYear: 1971,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CGK|jp_ldp|0": {
    name: "Shizuka Kamei",
    birthYear: 1936,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CHU|jp_cdp|0": {
    name: "Chinami Nishimura",
    birthYear: 1967,
    gender: "female",
    ethnicity: "asian",
    portraitId: "jp-chinami-nishimura",
  },
  "JP|regionalCouncil|CHU|jp_dpfp|0": {
    name: "Azuma Koshiishi",
    birthYear: 1936,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CHU|jp_ishin|0": {
    name: "Hiroshi Yamada",
    birthYear: 1958,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CHU|jp_jcp|0": {
    name: "Toru Miyamoto",
    birthYear: 1972,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CHU|jp_komeito|0": {
    name: "Yoshinori Ohguchi",
    birthYear: 1955,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|CHU|jp_ldp|0": {
    name: "Takashi Kawamura",
    birthYear: 1948,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|HOK|jp_cdp|0": {
    name: "Yoshio Hachiro",
    birthYear: 1948,
    gender: "male",
    ethnicity: "asian",
    portraitId: "jp-yoshio-hachiro",
  },
  "JP|regionalCouncil|HOK|jp_jcp|0": {
    name: "Noriko Mashita",
    birthYear: 1956,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|HOK|jp_komeito|0": {
    name: "Toshiko Hamayotsu",
    birthYear: 1945,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|HOK|jp_ldp|0": {
    name: "Tsutomu Takebe",
    birthYear: 1941,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KAN|jp_cdp|0": {
    name: "Yoko Komiyama",
    birthYear: 1948,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KAN|jp_dpfp|0": {
    name: "Shinji Tarutoko",
    birthYear: 1959,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KAN|jp_ishin|0": {
    name: "Yoshimi Watanabe",
    birthYear: 1952,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KAN|jp_jcp|0": {
    name: "Yasuo Ogata",
    birthYear: 1947,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KAN|jp_komeito|0": {
    name: "Akihiro Ota",
    birthYear: 1945,
    gender: "male",
    ethnicity: "asian",
    portraitId: "jp-akihiro-ota",
  },
  "JP|regionalCouncil|KAN|jp_ldp|0": {
    name: "Takashi Fukaya",
    birthYear: 1935,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KNS|jp_cdp|0": {
    name: "Sumio Mabuchi",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KNS|jp_dpfp|0": {
    name: "Hirofumi Hirano",
    birthYear: 1949,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KNS|jp_ishin|0": {
    name: "Toru Hashimoto",
    birthYear: 1969,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KNS|jp_jcp|0": {
    name: "Hidekatsu Yoshii",
    birthYear: 1942,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KNS|jp_komeito|0": {
    name: "Shigeki Sato",
    birthYear: 1959,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KNS|jp_ldp|0": {
    name: "Naokazu Takemoto",
    birthYear: 1940,
    gender: "male",
    ethnicity: "asian",
    portraitId: "jp-naokazu-takemoto",
  },
  "JP|regionalCouncil|KYU|jp_cdp|0": {
    name: "Hiroshi Ogushi",
    birthYear: 1965,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KYU|jp_dpfp|0": {
    name: "Kenji Kitahashi",
    birthYear: 1953,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KYU|jp_ishin|0": {
    name: "Hideo Higashikokubaru",
    birthYear: 1957,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KYU|jp_jcp|0": {
    name: "Denny Tamaki",
    birthYear: 1959,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KYU|jp_komeito|0": {
    name: "Kiyohiko Toyama",
    birthYear: 1969,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|KYU|jp_ldp|0": {
    name: "Taku Yamasaki",
    birthYear: 1936,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|SHI|jp_cdp|0": {
    name: "Takako Nagae",
    birthYear: 1960,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|SHI|jp_dpfp|0": {
    name: "Yorihisa Matsuno",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|SHI|jp_ishin|0": {
    name: "Seiji Hamada",
    birthYear: 1963,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|SHI|jp_jcp|0": {
    name: "Saori Ikeuchi",
    birthYear: 1982,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|SHI|jp_komeito|0": {
    name: "Daisaku Hiraki",
    birthYear: 1974,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|SHI|jp_ldp|0": {
    name: "Yuji Yamamoto",
    birthYear: 1952,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|TOH|jp_cdp|0": {
    name: "Kazuko Kori",
    birthYear: 1957,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|TOH|jp_dpfp|0": {
    name: "Shinji Oguma",
    birthYear: 1968,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|TOH|jp_ishin|0": {
    name: "Atsushi Hayasaka",
    birthYear: 1971,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|TOH|jp_jcp|0": {
    name: "Akira Kasai",
    birthYear: 1952,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|TOH|jp_komeito|0": {
    name: "Noriko Furuya",
    birthYear: 1956,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|regionalCouncil|TOH|jp_ldp|0": {
    name: "Masashi Nakano",
    birthYear: 1948,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|CGK|jp_cdp|0": {
    name: "Shinji Morimoto",
    birthYear: 1973,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|CGK|jp_cdp|1": {
    name: "Genki Sudo",
    birthYear: 1978,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-genki-sudo-2019",
  },
  "JP|sangiin|CGK|jp_dpfp|0": {
    name: "Masao Kobayashi",
    birthYear: 1947,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-masao-kobayashi-2019",
  },
  "JP|sangiin|CGK|jp_jcp|0": {
    name: "Satoshi Inoue",
    birthYear: 1958,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-satoshi-inoue-2019",
  },
  "JP|sangiin|CGK|jp_komeito|0": {
    name: "Kozo Akino",
    birthYear: 1967,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-kozo-akino-2019",
  },
  "JP|sangiin|CGK|jp_komeito|1": {
    name: "Masayoshi Hamada",
    birthYear: 1957,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-masayoshi-hamada-2019",
  },
  "JP|sangiin|CGK|jp_ldp|0": {
    name: "Yoichi Miyazawa",
    birthYear: 1950,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-yoichi-miyazawa-2019",
  },
  "JP|sangiin|CGK|jp_ldp|1": {
    name: "Yoshimasa Hayashi",
    birthYear: 1961,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-yoshimasa-hayashi-2019",
  },
  "JP|sangiin|CHU|jp_cdp|0": {
    name: "Hideya Sugio",
    birthYear: 1957,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-hideya-sugio-2019",
  },
  "JP|sangiin|CHU|jp_cdp|1": {
    name: "Maiko Tajima",
    birthYear: 1976,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-maiko-tajima-2019",
  },
  "JP|sangiin|CHU|jp_dpfp|0": {
    name: "Kohei Otsuka",
    birthYear: 1959,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-kohei-otsuka-2019",
  },
  "JP|sangiin|CHU|jp_dpfp|1": {
    name: "Kazuya Shimba",
    birthYear: 1967,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-kazuya-shimba-2019",
  },
  "JP|sangiin|CHU|jp_independent|0": {
    name: "Shizuka Terata",
    birthYear: 1975,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-shizuka-terata-2019",
  },
  "JP|sangiin|CHU|jp_ishin|0": {
    name: "Satoshi Umemura",
    birthYear: 1975,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-satoshi-umemura-2019",
  },
  "JP|sangiin|CHU|jp_ishin|1": {
    name: "Takumi Shibata",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-takumi-shibata-2019",
  },
  "JP|sangiin|CHU|jp_jcp|0": {
    name: "Tadayoshi Ichida",
    birthYear: 1942,
    gender: "male",
    ethnicity: "asian",
    portraitId: "jp-tadayoshi-ichida",
  },
  "JP|sangiin|CHU|jp_jcp|1": {
    name: "Akira Koike",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-akira-koike-2019",
  },
  "JP|sangiin|CHU|jp_komeito|0": {
    name: "Ryuji Satomi",
    birthYear: 1967,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-ryuji-satomi-2019",
  },
  "JP|sangiin|CHU|jp_komeito|1": {
    name: "Nobuo Yasue",
    birthYear: 1987,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-nobuo-yasue-2019",
  },
  "JP|sangiin|CHU|jp_ldp|0": {
    name: "Masahito Fujikawa",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-masahito-fujikawa-2019",
  },
  "JP|sangiin|CHU|jp_ldp|1": {
    name: "Yasuyuki Sakai",
    birthYear: 1952,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-yasuyuki-sakai-2019",
  },
  "JP|sangiin|HOK|jp_cdp|0": {
    name: "Saori Yoshikawa",
    birthYear: 1976,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-saori-yoshikawa-2019",
  },
  "JP|sangiin|HOK|jp_cdp|1": {
    name: "Kenji Katsube",
    birthYear: 1959,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-kenji-katsube-2019",
  },
  "JP|sangiin|HOK|jp_jcp|0": {
    name: "Tomoko Kami",
    birthYear: 1955,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-tomoko-kami-2019",
  },
  "JP|sangiin|HOK|jp_komeito|0": {
    name: "Shin'ichi Yokoyama",
    birthYear: 1959,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-shin-ichi-yokoyama-2019",
  },
  "JP|sangiin|HOK|jp_ldp|0": {
    name: "Gaku Hasegawa",
    birthYear: 1971,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-gaku-hasegawa-2019",
  },
  "JP|sangiin|HOK|jp_ldp|1": {
    name: "Harumi Takahashi",
    birthYear: 1954,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-harumi-takahashi-2019",
  },
  "JP|sangiin|KAN|jp_cdp|0": {
    name: "Hiroto Kumagai",
    birthYear: 1962,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-hiroto-kumagai-2019",
  },
  "JP|sangiin|KAN|jp_cdp|1": {
    name: "Hiroe Makiyama",
    birthYear: 1964,
    gender: "female",
    ethnicity: "asian",
    portraitId: "jp-hiroe-makiyama",
  },
  "JP|sangiin|KAN|jp_dpfp|0": {
    name: "Mami Tamura",
    birthYear: 1976,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-mami-tamura-2019",
  },
  "JP|sangiin|KAN|jp_dpfp|1": {
    name: "Tetsuji Isozaki",
    birthYear: 1969,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KAN|jp_independent|0": {
    name: "Kiyoshi Ueda",
    birthYear: 1948,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-kiyoshi-ueda-2019",
  },
  "JP|sangiin|KAN|jp_ishin|0": {
    name: "Shun Otokita",
    birthYear: 1983,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-shun-otokita-2019",
  },
  "JP|sangiin|KAN|jp_ishin|1": {
    name: "Shigefumi Matsuzawa",
    birthYear: 1958,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-shigefumi-matsuzawa-2019",
  },
  "JP|sangiin|KAN|jp_jcp|0": {
    name: "Yoshiko Kira",
    birthYear: 1982,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|sangiin|KAN|jp_jcp|1": {
    name: "Gaku Ito",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-gaku-ito-2019",
  },
  "JP|sangiin|KAN|jp_komeito|0": {
    name: "Toshiko Takeya",
    birthYear: 1969,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-toshiko-takeya-2019",
  },
  "JP|sangiin|KAN|jp_komeito|1": {
    name: "Natsuo Yamaguchi",
    birthYear: 1952,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-natsuo-yamaguchi-2019",
  },
  "JP|sangiin|KAN|jp_ldp|0": {
    name: "Masaharu Nakagawa",
    birthYear: 1947,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-masaharu-nakagawa-2019",
  },
  "JP|sangiin|KAN|jp_ldp|1": {
    name: "Tamayo Marukawa",
    birthYear: 1971,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-tamayo-marukawa-2019",
  },
  "JP|sangiin|KAN|jp_reiwa|0": {
    name: "Yasuhiko Funago",
    birthYear: 1957,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-yasuhiko-funago-2019",
  },
  "JP|sangiin|KAN|jp_reiwa|1": {
    name: "Eiko Kimura",
    birthYear: 1965,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|sangiin|KNS|jp_cdp|0": {
    name: "Tetsuro Fukuyama",
    birthYear: 1962,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-tetsuro-fukuyama-2019",
  },
  "JP|sangiin|KNS|jp_cdp|1": {
    name: "Masahito Ozawa",
    birthYear: 1965,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-masahito-ozawa-2019",
  },
  "JP|sangiin|KNS|jp_dpfp|0": {
    name: "Yoshifumi Hamano",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-yoshifumi-hamano-2019",
  },
  "JP|sangiin|KNS|jp_dpfp|1": {
    name: "Takanori Kawai",
    birthYear: 1964,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-takanori-kawai-2019",
  },
  "JP|sangiin|KNS|jp_independent|0": {
    name: "Yukiko Kada",
    birthYear: 1950,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-yukiko-kada-2019",
  },
  "JP|sangiin|KNS|jp_independent|1": {
    name: "Akira Gunji",
    birthYear: 1949,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-akira-gunji-2019",
  },
  "JP|sangiin|KNS|jp_ishin|0": {
    name: "Mizuho Umemura",
    birthYear: 1978,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-mizuho-umemura-2019",
  },
  "JP|sangiin|KNS|jp_ishin|1": {
    name: "Toru Azuma",
    birthYear: 1966,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KNS|jp_jcp|0": {
    name: "Akiko Kurabayashi",
    birthYear: 1960,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-akiko-kurabayashi-2019",
  },
  "JP|sangiin|KNS|jp_jcp|1": {
    name: "Yoshiki Yamashita",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-yoshiki-yamashita-2019",
  },
  "JP|sangiin|KNS|jp_komeito|0": {
    name: "Hirotaka Ishikawa",
    birthYear: 1973,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-hirotaka-ishikawa-2019",
  },
  "JP|sangiin|KNS|jp_komeito|1": {
    name: "Hisatake Sugi",
    birthYear: 1976,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-hisatake-sugi-2019",
  },
  "JP|sangiin|KNS|jp_ldp|0": {
    name: "Rui Matsukawa",
    birthYear: 1971,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-rui-matsukawa-2019",
  },
  "JP|sangiin|KNS|jp_ldp|1": {
    name: "Fusae Ota",
    birthYear: 1951,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-fusae-ota-2019",
  },
  "JP|sangiin|KNS|jp_sdp|0": {
    name: "Seiji Mataichi",
    birthYear: 1944,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KNS|jp_sdp|1": {
    name: "Tadatomo Yoshida",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-tadatomo-yoshida-2019",
  },
  "JP|sangiin|KYU|jp_cdp|0": {
    name: "Kuniyoshi Noda",
    birthYear: 1958,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-kuniyoshi-noda-2019",
  },
  "JP|sangiin|KYU|jp_cdp|1": {
    name: "Masako Kishi",
    birthYear: 1976,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-masako-kishi-2019",
  },
  "JP|sangiin|KYU|jp_dpfp|0": {
    name: "Yukihito Koga",
    birthYear: 1959,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KYU|jp_dpfp|1": {
    name: "Shinya Adachi",
    birthYear: 1957,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-shinya-adachi-2019",
  },
  "JP|sangiin|KYU|jp_independent|0": {
    name: "Yoichi Iha",
    birthYear: 1952,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-yoichi-iha-2019",
  },
  "JP|sangiin|KYU|jp_ishin|0": {
    name: "Kunihiko Muroi",
    birthYear: 1947,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-kunihiko-muroi-2019",
  },
  "JP|sangiin|KYU|jp_jcp|0": {
    name: "Tomoko Tamura",
    birthYear: 1965,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-tomoko-tamura-2019",
  },
  "JP|sangiin|KYU|jp_jcp|1": {
    name: "Ryosuke Takeda",
    birthYear: 1979,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|KYU|jp_komeito|0": {
    name: "Hiromi Takase",
    birthYear: 1981,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|sangiin|KYU|jp_komeito|1": {
    name: "Rokuta Shimono",
    birthYear: 1964,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-rokuta-shimono-2019",
  },
  "JP|sangiin|KYU|jp_ldp|0": {
    name: "Satoshi Oie",
    birthYear: 1967,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-satoshi-oie-2019",
  },
  "JP|sangiin|KYU|jp_ldp|1": {
    name: "Masaji Matsuyama",
    birthYear: 1959,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-masaji-matsuyama-2019",
  },
  "JP|sangiin|KYU|jp_nhk|0": {
    name: "Takashi Tachibana",
    birthYear: 1967,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-takashi-tachibana-2019",
  },
  "JP|sangiin|SHI|jp_cdp|0": {
    name: "Taiga Ishikawa",
    birthYear: 1974,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-taiga-ishikawa-2019",
  },
  "JP|sangiin|SHI|jp_dpfp|0": {
    name: "Makoto Hamaguchi",
    birthYear: 1966,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|sangiin|SHI|jp_jcp|0": {
    name: "Mikishi Daimon",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-mikishi-daimon-2019",
  },
  "JP|sangiin|SHI|jp_komeito|0": {
    name: "Hiroaki Nagasawa",
    birthYear: 1958,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-hiroaki-nagasawa-2019",
  },
  "JP|sangiin|SHI|jp_ldp|0": {
    name: "Yoshihiko Isozaki",
    birthYear: 1957,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-yoshihiko-isozaki-2019",
  },
  "JP|sangiin|SHI|jp_ldp|1": {
    name: "Shingo Miyake",
    birthYear: 1961,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-shingo-miyake-2019",
  },
  "JP|sangiin|TOH|jp_cdp|0": {
    name: "Takashi Moriya",
    birthYear: 1967,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-takashi-moriya-2019",
  },
  "JP|sangiin|TOH|jp_cdp|1": {
    name: "Noriko Ishigaki",
    birthYear: 1974,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-noriko-ishigaki-2019",
  },
  "JP|sangiin|TOH|jp_dpfp|0": {
    name: "Teruhiko Mashiko",
    birthYear: 1947,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-teruhiko-mashiko-2019",
  },
  "JP|sangiin|TOH|jp_dpfp|1": {
    name: "Mitsuru Sakurai",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-mitsuru-sakurai-2019",
  },
  "JP|sangiin|TOH|jp_ishin|0": {
    name: "Hirofumi Yanagase",
    birthYear: 1974,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-hirofumi-yanagase-2019",
  },
  "JP|sangiin|TOH|jp_jcp|0": {
    name: "Tomo Iwabuchi",
    birthYear: 1976,
    gender: "female",
    ethnicity: "asian",
    portraitId: "hist-tomo-iwabuchi-2019",
  },
  "JP|sangiin|TOH|jp_komeito|0": {
    name: "Seishi Kumano",
    birthYear: 1965,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-seishi-kumano-2019",
  },
  "JP|sangiin|TOH|jp_komeito|1": {
    name: "Masaaki Taniai",
    birthYear: 1973,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-masaaki-taniai-2019",
  },
  "JP|sangiin|TOH|jp_ldp|0": {
    name: "Hiroo Ishii",
    birthYear: 1964,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-hiroo-ishii-2019",
  },
  "JP|sangiin|TOH|jp_ldp|1": {
    name: "Motome Takisawa",
    birthYear: 1958,
    gender: "male",
    ethnicity: "asian",
    portraitId: "hist-motome-takisawa-2019",
  },
  "JP|shugiin|CGK|jp_cdp|0": {
    name: "Akiko Kamei",
    birthYear: 1965,
    gender: "female",
    ethnicity: "asian",
    portraitId: "jp-akiko-kamei",
  },
  "JP|shugiin|CGK|jp_dpfp|0": {
    name: "Shu Watanabe",
    birthYear: 1961,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CGK|jp_jcp|0": {
    name: "Yoshinobu Ohira",
    birthYear: 1978,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CGK|jp_komeito|0": {
    name: "Tetsuo Saito",
    birthYear: 1952,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CGK|jp_ldp|0": {
    name: "Shinzo Abe",
    birthYear: 1954,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CHU|jp_cdp|0": {
    name: "Tsunehiko Yoshida",
    birthYear: 1974,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CHU|jp_dpfp|0": {
    name: "Motohisa Furukawa",
    birthYear: 1965,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CHU|jp_independent|0": {
    name: "Katsuya Okada",
    birthYear: 1953,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CHU|jp_ishin|0": {
    name: "Kazumi Sugimoto",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CHU|jp_jcp|0": {
    name: "Nobuko Motomura",
    birthYear: 1972,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|shugiin|CHU|jp_komeito|0": {
    name: "Yoshinori Oguchi",
    birthYear: 1955,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|CHU|jp_ldp|0": {
    name: "Seiko Noda",
    birthYear: 1960,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|shugiin|HOK|jp_cdp|0": {
    name: "Hiroshi Kamiya",
    birthYear: 1968,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|HOK|jp_dpfp|0": {
    name: "Tatsumaru Yamaoka",
    birthYear: 1979,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|HOK|jp_jcp|0": {
    name: "Tetsuya Shiokawa",
    birthYear: 1961,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|HOK|jp_komeito|0": {
    name: "Hidemichi Sato",
    birthYear: 1960,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|HOK|jp_ldp|0": {
    name: "Takamori Yoshikawa",
    birthYear: 1950,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KAN|jp_cdp|0": {
    name: "Yukio Edano",
    birthYear: 1964,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KAN|jp_dpfp|0": {
    name: "Atsushi Oshima",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KAN|jp_independent|0": {
    name: "Jin Matsubara",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KAN|jp_ishin|0": {
    name: "Seiichi Kushida",
    birthYear: 1958,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KAN|jp_jcp|0": {
    name: "Kazuo Shii",
    birthYear: 1954,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KAN|jp_komeito|0": {
    name: "Keiichi Ishii",
    birthYear: 1958,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KAN|jp_ldp|0": {
    name: "Yoshihide Suga",
    birthYear: 1948,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KAN|jp_sdp|0": {
    name: "Mizuho Fukushima",
    birthYear: 1955,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|shugiin|KNS|jp_cdp|0": {
    name: "Kiyomi Tsujimoto",
    birthYear: 1960,
    gender: "female",
    ethnicity: "asian",
  },
  "JP|shugiin|KNS|jp_dpfp|0": {
    name: "Seiji Maehara",
    birthYear: 1962,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KNS|jp_independent|0": {
    name: "Takaya Muto",
    birthYear: 1979,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KNS|jp_ishin|0": {
    name: "Nobuyuki Baba",
    birthYear: 1965,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KNS|jp_jcp|0": {
    name: "Keiji Kokuta",
    birthYear: 1947,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KNS|jp_komeito|0": {
    name: "Yuzuru Takeuchi",
    birthYear: 1958,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KNS|jp_ldp|0": {
    name: "Toshihiro Nikai",
    birthYear: 1939,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KYU|jp_cdp|0": {
    name: "Katsuhiko Yokomitsu",
    birthYear: 1943,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KYU|jp_dpfp|0": {
    name: "Shuji Inatomi",
    birthYear: 1970,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KYU|jp_independent|0": {
    name: "Toshinobu Nakasato",
    birthYear: 1937,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KYU|jp_ishin|0": {
    name: "Mikio Shimoji",
    birthYear: 1961,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KYU|jp_jcp|0": {
    name: "Seiken Akamine",
    birthYear: 1947,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KYU|jp_komeito|0": {
    name: "Yasuyuki Eda",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KYU|jp_ldp|0": {
    name: "Taro Aso",
    birthYear: 1940,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KYU|jp_nhk|0": {
    name: "Hodaka Maruyama",
    birthYear: 1984,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|KYU|jp_sdp|0": {
    name: "Kantoku Teruya",
    birthYear: 1945,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|SHI|jp_cdp|0": {
    name: "Junya Ogawa",
    birthYear: 1971,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|SHI|jp_dpfp|0": {
    name: "Yuichiro Tamaki",
    birthYear: 1969,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|SHI|jp_komeito|0": {
    name: "Noritoshi Ishida",
    birthYear: 1951,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|SHI|jp_ldp|0": {
    name: "Takuya Hirai",
    birthYear: 1958,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|TOH|jp_cdp|0": {
    name: "Yukihiko Akutsu",
    birthYear: 1956,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|TOH|jp_dpfp|0": {
    name: "Ichiro Ozawa",
    birthYear: 1942,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|TOH|jp_ishin|0": {
    name: "Yasushi Adachi",
    birthYear: 1965,
    gender: "male",
    ethnicity: "asian",
  },
  "JP|shugiin|TOH|jp_jcp|0": {
    name: "Chizuko Takahashi",
    birthYear: 1959,
    gender: "female",
    ethnicity: "asian",
    portraitId: "jp-chizuko-takahashi",
  },
  "JP|shugiin|TOH|jp_komeito|0": {
    name: "Yoshihisa Inoue",
    birthYear: 1947,
    gender: "male",
    ethnicity: "asian",
    portraitId: "jp-yoshihisa-inoue",
  },
  "JP|shugiin|TOH|jp_ldp|0": {
    name: "Masayoshi Yoshino",
    birthYear: 1948,
    gender: "male",
    ethnicity: "asian",
    portraitId: "jp-masayoshi-yoshino",
  },
};
