import type { RosterMap } from "../historicalRosters";

export const ROSTER_2019_IE: RosterMap = {
  "IE|dail|COR|ie_ff|0": {
    name: "Micheál Martin",
    birthYear: 1960,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|COR|ie_fg|0": {
    name: "Simon Coveney",
    birthYear: 1972,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|COR|ie_green|0": {
    name: "Catherine Martin",
    birthYear: 1972,
    gender: "female",
    ethnicity: "white",
  },
  "IE|dail|COR|ie_ind|0": {
    name: "Michael Collins",
    birthYear: 1968,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|COR|ie_labour|0": {
    name: "Seán Sherlock",
    birthYear: 1972,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|COR|ie_sf|0": {
    name: "Donnchadh Ó Laoghaire",
    birthYear: 1989,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|DON|ie_ff|0": {
    name: "Charlie McConalogue",
    birthYear: 1977,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|DON|ie_fg|0": {
    name: "Joe McHugh",
    birthYear: 1971,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|DON|ie_green|0": {
    name: "Ossian Smyth",
    birthYear: 1971,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|DON|ie_ind|0": {
    name: "Thomas Pringle",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|DON|ie_sf|0": {
    name: "Pearse Doherty",
    birthYear: 1977,
    gender: "male",
    ethnicity: "white",
    portraitId: "ie-pearse-doherty",
  },
  "IE|dail|DUB|ie_ff|0": {
    name: "Darragh O'Brien",
    birthYear: 1974,
    gender: "male",
    ethnicity: "white",
    portraitId: "ie-darragh-o-brien",
  },
  "IE|dail|DUB|ie_fg|0": {
    name: "Leo Varadkar",
    birthYear: 1979,
    gender: "male",
    ethnicity: "asian",
  },
  "IE|dail|DUB|ie_green|0": {
    name: "Eamon Ryan",
    birthYear: 1963,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|DUB|ie_ind|0": {
    name: "Joan Collins",
    birthYear: 1961,
    gender: "female",
    ethnicity: "white",
  },
  "IE|dail|DUB|ie_labour|0": {
    name: "Aodhán Ó Ríordáin",
    birthYear: 1976,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|DUB|ie_sf|0": {
    name: "Mary Lou McDonald",
    birthYear: 1969,
    gender: "female",
    ethnicity: "white",
  },
  "IE|dail|GAL|ie_ff|0": {
    name: "Éamon Ó Cuív",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|GAL|ie_fg|0": {
    name: "Ciarán Cannon",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
    portraitId: "ie-ciaran-cannon",
  },
  "IE|dail|GAL|ie_green|0": {
    name: "Roderic O'Gorman",
    birthYear: 1981,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|GAL|ie_ind|0": {
    name: "Catherine Connolly",
    birthYear: 1957,
    gender: "female",
    ethnicity: "white",
  },
  "IE|dail|GAL|ie_sf|0": {
    name: "Mairéad Farrell",
    birthYear: 1990,
    gender: "female",
    ethnicity: "white",
  },
  "IE|dail|KIL|ie_ff|0": {
    name: "James Lawless",
    birthYear: 1976,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|KIL|ie_fg|0": {
    name: "Helen McEntee",
    birthYear: 1986,
    gender: "female",
    ethnicity: "white",
  },
  "IE|dail|KIL|ie_green|0": {
    name: "Malcolm Noonan",
    birthYear: 1966,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|KIL|ie_ind|0": {
    name: "Peter Fitzpatrick",
    birthYear: 1962,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|KIL|ie_labour|0": {
    name: "Ged Nash",
    birthYear: 1975,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|KIL|ie_sf|0": {
    name: "Ruairí Ó Murchú",
    birthYear: 1978,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|LIM|ie_ff|0": {
    name: "Willie O'Dea",
    birthYear: 1952,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|LIM|ie_fg|0": {
    name: "Patrick O'Donovan",
    birthYear: 1977,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|LIM|ie_green|0": {
    name: "Brian Leddin",
    birthYear: 1979,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|LIM|ie_ind|0": {
    name: "Michael Lowry",
    birthYear: 1953,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|LIM|ie_sf|0": {
    name: "Maurice Quinlivan",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|MID|ie_ff|0": {
    name: "Barry Cowen",
    birthYear: 1967,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|MID|ie_fg|0": {
    name: "Charlie Flanagan",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|MID|ie_ind|0": {
    name: "Carol Nolan",
    birthYear: 1978,
    gender: "female",
    ethnicity: "white",
  },
  "IE|dail|MID|ie_labour|0": {
    name: "Alan Kelly",
    birthYear: 1975,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|MID|ie_sf|0": {
    name: "Brian Stanley",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|WEX|ie_ff|0": {
    name: "James Browne",
    birthYear: 1975,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|WEX|ie_fg|0": {
    name: "Paul Kehoe",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|WEX|ie_green|0": {
    name: "Marc Ó Cathasaigh",
    birthYear: 1977,
    gender: "male",
    ethnicity: "white",
  },
  "IE|dail|WEX|ie_ind|0": {
    name: "Verona Murphy",
    birthYear: 1971,
    gender: "female",
    ethnicity: "white",
  },
  "IE|dail|WEX|ie_sf|0": {
    name: "Johnny Mythen",
    birthYear: 1959,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|COR|ie_ff|0": {
    name: "Denis O'Donovan",
    birthYear: 1955,
    gender: "male",
    ethnicity: "white",
    portraitId: "ie-denis-o-donovan",
  },
  "IE|seanad|COR|ie_fg|0": {
    name: "Colm Burke",
    birthYear: 1957,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|COR|ie_ind|0": {
    name: "Colette Kelleher",
    birthYear: 1962,
    gender: "female",
    ethnicity: "white",
  },
  "IE|seanad|COR|ie_sf|0": {
    name: "Niall Ó Donnghaile",
    birthYear: 1985,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|DON|ie_ff|0": {
    name: "Robbie Gallagher",
    birthYear: 1968,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|DON|ie_fg|0": {
    name: "Joe O'Reilly",
    birthYear: 1955,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|DON|ie_ind|0": {
    name: "David Norris",
    birthYear: 1944,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|DON|ie_labour|0": {
    name: "Brendan Howlin",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|DON|ie_sf|0": {
    name: "Pádraig Mac Lochlainn",
    birthYear: 1973,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|DUB|ie_ff|0": {
    name: "Catherine Ardagh",
    birthYear: 1982,
    gender: "female",
    ethnicity: "white",
  },
  "IE|seanad|DUB|ie_fg|0": {
    name: "Catherine Noone",
    birthYear: 1976,
    gender: "female",
    ethnicity: "white",
    portraitId: "ie-catherine-noone",
  },
  "IE|seanad|DUB|ie_green|0": {
    name: "Ciarán Cuffe",
    birthYear: 1963,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|DUB|ie_ind|0": {
    name: "Michael McDowell",
    birthYear: 1951,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|DUB|ie_labour|0": {
    name: "Ivana Bacik",
    birthYear: 1968,
    gender: "female",
    ethnicity: "white",
  },
  "IE|seanad|DUB|ie_sf|0": {
    name: "Máire Devine",
    birthYear: 1972,
    gender: "female",
    ethnicity: "white",
  },
  "IE|seanad|GAL|ie_ff|0": {
    name: "Terry Leyden",
    birthYear: 1945,
    gender: "male",
    ethnicity: "white",
    portraitId: "ie-terry-leyden",
  },
  "IE|seanad|GAL|ie_fg|0": {
    name: "Paddy Burke",
    birthYear: 1955,
    gender: "male",
    ethnicity: "white",
    portraitId: "ie-paddy-burke",
  },
  "IE|seanad|GAL|ie_green|0": {
    name: "Grace O'Sullivan",
    birthYear: 1962,
    gender: "female",
    ethnicity: "white",
  },
  "IE|seanad|GAL|ie_ind|0": {
    name: "Rónán Mullen",
    birthYear: 1970,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|KIL|ie_ff|0": {
    name: "Jennifer Murnane O'Connor",
    birthYear: 1966,
    gender: "female",
    ethnicity: "white",
  },
  "IE|seanad|KIL|ie_fg|0": {
    name: "Ray Butler",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|KIL|ie_green|0": {
    name: "Pippa Hackett",
    birthYear: 1974,
    gender: "female",
    ethnicity: "white",
  },
  "IE|seanad|KIL|ie_ind|0": {
    name: "Victor Boyhan",
    birthYear: 1961,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|LIM|ie_ff|0": {
    name: "Ned O'Sullivan",
    birthYear: 1950,
    gender: "male",
    ethnicity: "white",
    portraitId: "ie-ned-o-sullivan",
  },
  "IE|seanad|LIM|ie_fg|0": {
    name: "Kieran O'Donnell",
    birthYear: 1963,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|LIM|ie_ind|0": {
    name: "Gerard Craughwell",
    birthYear: 1953,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|MID|ie_ff|0": {
    name: "Diarmuid Wilson",
    birthYear: 1965,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|MID|ie_fg|0": {
    name: "Gabrielle McFadden",
    birthYear: 1967,
    gender: "female",
    ethnicity: "white",
  },
  "IE|seanad|MID|ie_ind|0": {
    name: "John Dolan",
    birthYear: 1956,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|WEX|ie_ff|0": {
    name: "Aidan Davitt",
    birthYear: 1978,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|WEX|ie_fg|0": {
    name: "Paudie Coffey",
    birthYear: 1969,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|WEX|ie_ind|0": {
    name: "Frances Black",
    birthYear: 1960,
    gender: "female",
    ethnicity: "white",
  },
  "IE|seanad|WEX|ie_labour|0": {
    name: "Kevin Humphreys",
    birthYear: 1958,
    gender: "male",
    ethnicity: "white",
  },
  "IE|seanad|WEX|ie_sf|0": {
    name: "Fintan Warfield",
    birthYear: 1992,
    gender: "male",
    ethnicity: "white",
  },
};
