import type { Member } from "./orgForces";

/** One international organization in the West directory. */
export type Org = {
  id: string;
  name: string;
  short: string;
  seal: string;
  sealBig: string;
  cat: string;
  catLabel: string;
  founded: string;
  posture: string;
  ac: string;
  acBg: string;
  acBd: string;
  acSoft: string;
  sealBg: string;
  postureColor: string;
  desc: string;
  stats: [string, string, string][];
  resTitle: string;
  resBlurb: string;
  hasMilitary: boolean;
  viewer?: string;
  viewerRole?: string;
  baseCohesion?: number;
  vBudget?: number;
  treatyFloor?: number;
  vReact?: [string, string, string][];
  noForceNote?: string;
  members: Member[];
};

export const ORG_ORDER = ["nato", "warsaw", "nam", "eec", "un"];

export const ORGS: Record<string, Org> = {
  nato: {
    id: "nato",
    name: "North Atlantic Treaty Organization",
    short: "NATO",
    seal: "NATO",
    sealBig: "NATO",
    cat: "SECURITY",
    catLabel: "SECURITY ALLIANCE",
    founded: "1949",
    posture: "POSTURE: HEIGHTENED",
    ac: "#3b82f6",
    acBg: "rgba(59,130,246,.12)",
    acBd: "rgba(59,130,246,.4)",
    acSoft: "rgba(59,130,246,.3)",
    sealBg: "rgba(59,130,246,.1)",
    postureColor: "#ff7849",
    desc: "Collective defense of the free world. An attack on one is an attack on all — Article 5 binds members to mutual military response under a unified Atlantic command.",
    stats: [
      ["MEMBERS", "14", "#f3f1ea"],
      ["BLOC GDP", "$7.1T", "#f3f1ea"],
      ["COMMON FUND", "$340M", "#f3f1ea"],
      ["ARTICLE 5", "ARMED", "#86d978"],
    ],
    resTitle: "🇪🇸 Spain applies to accede",
    resBlurb:
      "Madrid petitions for membership. Domestic ratification passed — the members' vote is open and requires unanimity.",
    hasMilitary: true,
    viewer: "FRG",
    viewerRole: "Minister of Defense",
    baseCohesion: 72,
    vBudget: 48.2,
    treatyFloor: 50,
    vReact: [
      ["WASHINGTON", "#6fa8dc", "Welcomes a strong central front in Europe."],
      ["PARIS", "#d4af37", "Questions burden-sharing within the integrated command."],
    ],
    members: [
      {
        flag: "🇺🇸",
        name: "United States",
        short: "USA",
        status: "founding",
        year: 1949,
        pct: 4.7,
        commit: 35,
        troops: 2022,
        div: 16,
        air: 3400,
        tanks: 11000,
        ships: 530,
        warheads: 9200,
      },
      {
        flag: "🇩🇪",
        name: "West Germany",
        short: "FRG",
        status: "active",
        year: 1955,
        pct: 3.3,
        commit: 95,
        troops: 495,
        div: 12,
        air: 600,
        tanks: 4100,
        ships: 40,
        warheads: 0,
      },
      {
        flag: "🇬🇧",
        name: "United Kingdom",
        short: "UK",
        status: "founding",
        year: 1949,
        pct: 4.9,
        commit: 62,
        troops: 330,
        div: 4,
        air: 600,
        tanks: 900,
        ships: 180,
        warheads: 350,
      },
      {
        flag: "🇹🇷",
        name: "Türkiye",
        short: "TUR",
        status: "active",
        year: 1952,
        pct: 4.0,
        commit: 80,
        troops: 470,
        div: 14,
        air: 290,
        tanks: 3500,
        ships: 90,
        warheads: 0,
      },
      {
        flag: "🇫🇷",
        name: "France",
        short: "FRA",
        status: "founding",
        year: 1949,
        pct: 3.9,
        commit: 0,
        troops: 500,
        div: 8,
        air: 450,
        tanks: 1200,
        ships: 70,
        warheads: 250,
      },
      {
        flag: "🇮🇹",
        name: "Italy",
        short: "ITA",
        status: "founding",
        year: 1949,
        pct: 1.7,
        commit: 70,
        troops: 366,
        div: 8,
        air: 310,
        tanks: 1400,
        ships: 100,
        warheads: 0,
      },
      {
        flag: "🇳🇱",
        name: "Netherlands",
        short: "NLD",
        status: "founding",
        year: 1949,
        pct: 3.1,
        commit: 90,
        troops: 115,
        div: 3,
        air: 160,
        tanks: 900,
        ships: 40,
        warheads: 0,
      },
      {
        flag: "🇨🇦",
        name: "Canada",
        short: "CAN",
        status: "founding",
        year: 1949,
        pct: 1.9,
        commit: 20,
        troops: 80,
        div: 3,
        air: 240,
        tanks: 120,
        ships: 24,
        warheads: 0,
      },
    ],
  },
  warsaw: {
    id: "warsaw",
    name: "Warsaw Treaty Organization",
    short: "Warsaw Pact",
    seal: "☭",
    sealBig: "☭",
    cat: "SECURITY",
    catLabel: "SECURITY ALLIANCE",
    founded: "1955",
    posture: "POSTURE: MOBILIZING",
    ac: "#dc2626",
    acBg: "rgba(220,38,38,.12)",
    acBd: "rgba(220,38,38,.4)",
    acSoft: "rgba(220,38,38,.3)",
    sealBg: "rgba(220,38,38,.1)",
    postureColor: "#ff7849",
    desc: "Unified command of the socialist fraternal states under Moscow. The Brezhnev Doctrine permits intervention to preserve any member state’s socialist order.",
    stats: [
      ["MEMBERS", "7", "#f3f1ea"],
      ["BLOC GDP", "$3.4T", "#f3f1ea"],
      ["COMMON FUND", "₽410M", "#f3f1ea"],
      ["DOCTRINE", "ACTIVE", "#ff7849"],
    ],
    resTitle: "⚠ Fraternal Intervention — Afghanistan",
    resBlurb:
      "The Politburo moves to authorize the 40th Army to install a fraternal government in Kabul, forcibly aligning Afghanistan to the Eastern bloc.",
    hasMilitary: true,
    viewer: "POL",
    viewerRole: "Minister of Defense",
    baseCohesion: 84,
    vBudget: 12.6,
    treatyFloor: 60,
    vReact: [
      ["MOSCOW", "#ff7849", "Expects full fraternal commitment to the joint command."],
      ["BUCHAREST", "#d4af37", "Reserves the right to national command of its forces."],
    ],
    members: [
      {
        flag: "🚩",
        name: "Soviet Union",
        short: "SUN",
        status: "founding",
        year: 1955,
        pct: 12.0,
        commit: 100,
        troops: 3658,
        div: 168,
        air: 4500,
        tanks: 50000,
        ships: 480,
        warheads: 10000,
      },
      {
        flag: "🇵🇱",
        name: "Poland",
        short: "POL",
        status: "founding",
        year: 1955,
        pct: 3.0,
        commit: 90,
        troops: 320,
        div: 15,
        air: 700,
        tanks: 3100,
        ships: 40,
        warheads: 0,
      },
      {
        flag: "🚩",
        name: "East Germany",
        short: "DDR",
        status: "founding",
        year: 1955,
        pct: 6.0,
        commit: 98,
        troops: 170,
        div: 6,
        air: 360,
        tanks: 2500,
        ships: 30,
        warheads: 0,
      },
      {
        flag: "🇨🇿",
        name: "Czechoslovakia",
        short: "CSK",
        status: "founding",
        year: 1955,
        pct: 4.0,
        commit: 88,
        troops: 200,
        div: 10,
        air: 470,
        tanks: 3400,
        ships: 0,
        warheads: 0,
      },
      {
        flag: "🇧🇬",
        name: "Bulgaria",
        short: "BGR",
        status: "founding",
        year: 1955,
        pct: 3.5,
        commit: 85,
        troops: 150,
        div: 8,
        air: 260,
        tanks: 1900,
        ships: 30,
        warheads: 0,
      },
      {
        flag: "🇭🇺",
        name: "Hungary",
        short: "HUN",
        status: "founding",
        year: 1955,
        pct: 2.4,
        commit: 70,
        troops: 105,
        div: 6,
        air: 140,
        tanks: 1300,
        ships: 0,
        warheads: 0,
      },
      {
        flag: "🇷🇴",
        name: "Romania",
        short: "ROU",
        status: "founding",
        year: 1955,
        pct: 1.7,
        commit: 30,
        troops: 180,
        div: 8,
        air: 330,
        tanks: 1900,
        ships: 20,
        warheads: 0,
      },
    ],
  },
  nam: {
    id: "nam",
    name: "Non-Aligned Movement",
    short: "Non-Aligned Mvt.",
    seal: "🕊",
    sealBig: "🕊",
    cat: "DIPLOMATIC",
    catLabel: "DIPLOMATIC BLOC",
    founded: "1961",
    posture: "POSTURE: NEUTRAL",
    ac: "#d4af37",
    acBg: "rgba(212,175,55,.1)",
    acBd: "rgba(212,175,55,.35)",
    acSoft: "rgba(212,175,55,.25)",
    sealBg: "rgba(212,175,55,.08)",
    postureColor: "#86d978",
    desc: "A bloc of states refusing alignment with either superpower — pursuing sovereignty, decolonization, and a third path between Washington and Moscow.",
    stats: [
      ["MEMBERS", "31", "#f3f1ea"],
      ["COMBINED GDP", "$1.2T", "#f3f1ea"],
      ["SWING STATES", "9", "#d9bd6b"],
      ["POSTURE", "NEUTRAL", "#86d978"],
    ],
    resTitle: "Havana Declaration",
    resBlurb:
      "The summit debates a resolution condemning superpower intervention in the developing world — a test of the movement’s neutrality.",
    hasMilitary: false,
    noForceNote:
      "The Non-Aligned Movement maintains no unified military command. Members coordinate diplomatically and retain full sovereignty over their forces.",
    members: [
      {
        flag: "🇮🇳",
        name: "India",
        short: "IND",
        status: "founding",
        year: 1961,
        pct: 3.0,
        commit: 0,
        troops: 1100,
        div: 0,
        air: 0,
        tanks: 0,
        ships: 0,
        warheads: 0,
      },
      {
        flag: "🇪🇬",
        name: "Egypt",
        short: "EGY",
        status: "founding",
        year: 1961,
        pct: 0,
        commit: 0,
        troops: 0,
        div: 0,
        air: 0,
        tanks: 0,
        ships: 0,
        warheads: 0,
      },
      {
        flag: "🇳🇬",
        name: "Nigeria",
        short: "NGA",
        status: "active",
        year: 1964,
        pct: 0,
        commit: 0,
        troops: 0,
        div: 0,
        air: 0,
        tanks: 0,
        ships: 0,
        warheads: 0,
      },
      {
        flag: "🏳",
        name: "Yugoslavia",
        short: "YUG",
        status: "founding",
        year: 1961,
        pct: 0,
        commit: 0,
        troops: 0,
        div: 0,
        air: 0,
        tanks: 0,
        ships: 0,
        warheads: 0,
      },
    ],
  },
  eec: {
    id: "eec",
    name: "European Economic Community",
    short: "European Community",
    seal: "EEC",
    sealBig: "EEC",
    cat: "ECONOMIC",
    catLabel: "ECONOMIC UNION",
    founded: "1957",
    posture: "POSTURE: STABLE",
    ac: "#6fa8dc",
    acBg: "rgba(111,168,220,.12)",
    acBd: "rgba(111,168,220,.4)",
    acSoft: "rgba(111,168,220,.3)",
    sealBg: "rgba(111,168,220,.1)",
    postureColor: "#86d978",
    desc: "A common market binding Western European economies — customs union, shared agricultural policy, and the first steps toward monetary coordination.",
    stats: [
      ["MEMBERS", "9", "#f3f1ea"],
      ["COMBINED GDP", "$2.4T", "#f3f1ea"],
      ["COMMON FUND", "₠14B", "#f3f1ea"],
      ["TARIFFS", "ZERO", "#86d978"],
    ],
    resTitle: "European Monetary System",
    resBlurb:
      "Members vote on entering the new exchange-rate mechanism, pegging currencies to a common unit of account.",
    hasMilitary: false,
    noForceNote:
      "The European Community is an economic union with no military command. Security is handled through NATO and national forces.",
    members: [
      {
        flag: "🇩🇪",
        name: "West Germany",
        short: "FRG",
        status: "founding",
        year: 1957,
        pct: 0,
        commit: 0,
        troops: 0,
        div: 0,
        air: 0,
        tanks: 0,
        ships: 0,
        warheads: 0,
      },
      {
        flag: "🇫🇷",
        name: "France",
        short: "FRA",
        status: "founding",
        year: 1957,
        pct: 0,
        commit: 0,
        troops: 0,
        div: 0,
        air: 0,
        tanks: 0,
        ships: 0,
        warheads: 0,
      },
      {
        flag: "🇬🇧",
        name: "United Kingdom",
        short: "UK",
        status: "active",
        year: 1973,
        pct: 0,
        commit: 0,
        troops: 0,
        div: 0,
        air: 0,
        tanks: 0,
        ships: 0,
        warheads: 0,
      },
    ],
  },
  un: {
    id: "un",
    name: "United Nations",
    short: "United Nations",
    seal: "UN",
    sealBig: "UN",
    cat: "DIPLOMATIC",
    catLabel: "UNIVERSAL BODY",
    founded: "1945",
    posture: "POSTURE: STANDING",
    ac: "#4d8cff",
    acBg: "rgba(77,140,255,.12)",
    acBd: "rgba(77,140,255,.4)",
    acSoft: "rgba(77,140,255,.3)",
    sealBg: "rgba(77,140,255,.1)",
    postureColor: "#86d978",
    desc: "The universal forum of nations. The Security Council — where both superpowers hold a veto — is the one table where East and West must speak directly.",
    stats: [
      ["MEMBERS", "152", "#f3f1ea"],
      ["SECURITY COUNCIL", "15", "#f3f1ea"],
      ["VETO POWERS", "5", "#d9bd6b"],
      ["POSTURE", "STANDING", "#86d978"],
    ],
    resTitle: "UNSC: Afghanistan",
    resBlurb:
      "A resolution deploring the foreign intervention in Afghanistan reaches the Security Council — where a single veto can sink it.",
    hasMilitary: false,
    noForceNote:
      "The United Nations fields peacekeepers by mandate but commands no standing army. Enforcement rests with the Security Council and its five vetoes.",
    members: [
      {
        flag: "🇺🇸",
        name: "United States",
        short: "USA",
        status: "P5",
        year: 1945,
        pct: 0,
        commit: 0,
        troops: 0,
        div: 0,
        air: 0,
        tanks: 0,
        ships: 0,
        warheads: 0,
      },
      {
        flag: "🚩",
        name: "Soviet Union",
        short: "SUN",
        status: "P5",
        year: 1945,
        pct: 0,
        commit: 0,
        troops: 0,
        div: 0,
        air: 0,
        tanks: 0,
        ships: 0,
        warheads: 0,
      },
    ],
  },
};
