import type { Member } from "./orgForces";

export const WP_BASE_COHESION = 84;
export const WP_TREATY_FLOOR = 70;

/** Warsaw Pact members; the Soviet Union is the viewer (`you`). */
export const WP_MEMBERS: Member[] = [
  {
    flag: "🚩",
    name: "Soviet Union",
    short: "SUN",
    troops: 3658,
    commit: 85,
    div: 168,
    air: 4500,
    tanks: 50000,
    ships: 480,
    warheads: 10000,
    you: true,
  },
  {
    flag: "🇵🇱",
    name: "Poland",
    short: "POL",
    troops: 320,
    commit: 90,
    div: 15,
    air: 700,
    tanks: 3100,
    ships: 40,
    warheads: 0,
  },
  {
    flag: "🚩",
    name: "East Germany",
    short: "DDR",
    troops: 170,
    commit: 98,
    div: 6,
    air: 360,
    tanks: 2500,
    ships: 30,
    warheads: 0,
  },
  {
    flag: "🇨🇿",
    name: "Czechoslovakia",
    short: "CSK",
    troops: 200,
    commit: 88,
    div: 10,
    air: 470,
    tanks: 3400,
    ships: 0,
    warheads: 0,
  },
  {
    flag: "🇧🇬",
    name: "Bulgaria",
    short: "BGR",
    troops: 150,
    commit: 85,
    div: 8,
    air: 260,
    tanks: 1900,
    ships: 30,
    warheads: 0,
  },
  {
    flag: "🇭🇺",
    name: "Hungary",
    short: "HUN",
    troops: 105,
    commit: 70,
    div: 6,
    air: 140,
    tanks: 1300,
    ships: 0,
    warheads: 0,
  },
  {
    flag: "🇷🇴",
    name: "Romania",
    short: "ROU",
    troops: 180,
    commit: 30,
    div: 8,
    air: 330,
    tanks: 1900,
    ships: 20,
    warheads: 0,
  },
];
