/**
 * Per-macro-region voter-archetype population shares (%) for an independent
 * Wales, by reset era. Uses the shared 12 `uk_voterGroups` archetypes (see
 * ukDemographicCategories). Each region's shares sum to exactly 100.
 *
 * These are *patterns*, not absolute demographics: at secession they are layered
 * onto the live aggregate Wales split as per-region tilts so the
 * population-weighted average still matches the (evolved) aggregate — see
 * `apportionDemographicShares`. Region character: CDF capital/professional/
 * diverse, VAL post-industrial Valleys heartland, MWA/NWW rural Welsh-speaking,
 * NEW post-industrial/populist border, SWA mixed.
 */
export const WAL_REGION_DEMOGRAPHIC_PATTERNS: Record<
  "1991" | "2019",
  Record<string, Record<string, number>>
> = {
  "2019": {
    CDF: {
      post_industrial_workers: 14,
      urban_progressives: 15,
      suburban_homeowners: 12,
      young_renters: 11,
      rural_traditionalists: 4,
      retirees: 9,
      public_sector: 12,
      moderate_centrists: 9,
      populist_right: 4,
      green_activists: 5,
      small_business: 3,
      new_britons: 2,
    },
    SWA: {
      post_industrial_workers: 18,
      urban_progressives: 8,
      suburban_homeowners: 9,
      young_renters: 8,
      rural_traditionalists: 14,
      retirees: 13,
      public_sector: 14,
      moderate_centrists: 5,
      populist_right: 5,
      green_activists: 3,
      small_business: 2,
      new_britons: 1,
    },
    VAL: {
      post_industrial_workers: 28,
      urban_progressives: 4,
      suburban_homeowners: 6,
      young_renters: 7,
      rural_traditionalists: 7,
      retirees: 14,
      public_sector: 19,
      moderate_centrists: 3,
      populist_right: 7,
      green_activists: 2,
      small_business: 2,
      new_britons: 1,
    },
    MWA: {
      post_industrial_workers: 8,
      urban_progressives: 5,
      suburban_homeowners: 8,
      young_renters: 6,
      rural_traditionalists: 28,
      retirees: 19,
      public_sector: 11,
      moderate_centrists: 4,
      populist_right: 6,
      green_activists: 3,
      small_business: 2,
      new_britons: 0,
    },
    NWW: {
      post_industrial_workers: 11,
      urban_progressives: 5,
      suburban_homeowners: 8,
      young_renters: 7,
      rural_traditionalists: 24,
      retirees: 16,
      public_sector: 15,
      moderate_centrists: 4,
      populist_right: 6,
      green_activists: 2,
      small_business: 2,
      new_britons: 0,
    },
    NEW: {
      post_industrial_workers: 22,
      urban_progressives: 6,
      suburban_homeowners: 11,
      young_renters: 8,
      rural_traditionalists: 11,
      retirees: 12,
      public_sector: 9,
      moderate_centrists: 4,
      populist_right: 13,
      green_activists: 2,
      small_business: 1,
      new_britons: 1,
    },
  },
  "1991": {
    CDF: {
      post_industrial_workers: 21,
      urban_progressives: 11,
      suburban_homeowners: 12,
      young_renters: 10,
      rural_traditionalists: 5,
      retirees: 9,
      public_sector: 13,
      moderate_centrists: 8,
      populist_right: 2,
      green_activists: 2,
      small_business: 5,
      new_britons: 2,
    },
    SWA: {
      post_industrial_workers: 24,
      urban_progressives: 6,
      suburban_homeowners: 9,
      young_renters: 7,
      rural_traditionalists: 15,
      retirees: 12,
      public_sector: 15,
      moderate_centrists: 5,
      populist_right: 1,
      green_activists: 1,
      small_business: 4,
      new_britons: 1,
    },
    VAL: {
      post_industrial_workers: 37,
      urban_progressives: 3,
      suburban_homeowners: 6,
      young_renters: 6,
      rural_traditionalists: 7,
      retirees: 12,
      public_sector: 19,
      moderate_centrists: 3,
      populist_right: 1,
      green_activists: 1,
      small_business: 4,
      new_britons: 1,
    },
    MWA: {
      post_industrial_workers: 12,
      urban_progressives: 4,
      suburban_homeowners: 8,
      young_renters: 5,
      rural_traditionalists: 29,
      retirees: 18,
      public_sector: 12,
      moderate_centrists: 4,
      populist_right: 1,
      green_activists: 1,
      small_business: 6,
      new_britons: 0,
    },
    NWW: {
      post_industrial_workers: 15,
      urban_progressives: 4,
      suburban_homeowners: 8,
      young_renters: 6,
      rural_traditionalists: 25,
      retirees: 15,
      public_sector: 16,
      moderate_centrists: 4,
      populist_right: 1,
      green_activists: 1,
      small_business: 5,
      new_britons: 0,
    },
    NEW: {
      post_industrial_workers: 29,
      urban_progressives: 5,
      suburban_homeowners: 11,
      young_renters: 7,
      rural_traditionalists: 12,
      retirees: 11,
      public_sector: 10,
      moderate_centrists: 4,
      populist_right: 3,
      green_activists: 1,
      small_business: 6,
      new_britons: 1,
    },
  },
};
