import type { Db } from "mongodb";
import { ensureIndex } from "./helpers";

/**
 * Indexes for the crises collection:
 *
 *   - `status + autoGenerated` — the per-turn auto-disaster query filters on
 *     both fields: `crises.find({ status: "active", autoGenerated: true })`.
 */
export async function seedCrisisIndexes(db: Db, log: (msg: string) => void) {
  log("Crisis indexes:");

  await ensureIndex(
    db,
    "crises",
    { status: 1, autoGenerated: 1 },
    { name: "crises_status_autoGenerated" },
    log
  );

  await ensureIndex(
    db,
    "crises",
    { livingConflictEventId: 1 },
    { name: "crises_living_event", unique: true, sparse: true },
    log
  );

  await ensureIndex(
    db,
    "crises",
    { "globalResponse.conflictKey": 1, status: 1 },
    { name: "crises_global_response_active", sparse: true },
    log
  );

  await ensureIndex(
    db,
    "livingConflicts",
    { defKey: 1 },
    { name: "living_conflicts_def", unique: true },
    log
  );

  log("Crisis indexes ensured");
}
