import type { PartySeed } from "@/lib/seeds/reference/politicalParties";

/**
 * Finland default political parties.
 *
 *  - 1953: SDP + Agrarian League (Maalaisliitto, Kekkonen's party) + SKDL
 *    (the communist front, polling ~22%) + National Coalition — the fractious
 *    multiparty field of the postwar red-earth coalitions.
 *  - 1979: SDP (Koivisto/Sorsa) + Centre Party (renamed 1965) + National
 *    Coalition (rising but kept from office by Moscow's shadow) + SKDL.
 *  - 1991: SDP + Kesk (Holkeri/Aho era, continuous) + Kok, plus
 *    Vasemmistoliitto — SKDL's 1990 dissolution-and-refounding as a broader
 *    left alliance ahead of the March 1991 election.
 *
 * Positions -5..+5. Each entry is gated via `validForPresets`.
 */
export const fiParties: PartySeed[] = [
  // ─── 1979 late Kekkonen era (continuous into 1991) ─────────────────────
  {
    seedOrder: 1,
    countryId: "FI",
    name: "Suomen Sosialidemokraattinen Puolue",
    abbreviation: "SDP",
    color: "#E11931",
    economicPosition: -2,
    socialPosition: -1,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1979-default", "1991-default"],
    regimeStatus: "approved",
    treasury: 800_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 2,
    countryId: "FI",
    name: "Keskustapuolue",
    abbreviation: "Kesk",
    color: "#01954B",
    economicPosition: 0, // agrarian center; smallholder subsidies + regional policy
    socialPosition: 2,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1979-default", "1991-default"],
    regimeStatus: "approved",
    treasury: 700_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 3,
    countryId: "FI",
    name: "Kansallinen Kokoomus",
    abbreviation: "Kok",
    color: "#006288",
    economicPosition: 3,
    socialPosition: 2,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1979-default", "1991-default"],
    regimeStatus: "approved",
    treasury: 600_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 4,
    countryId: "FI",
    name: "Suomen Kansan Demokraattinen Liitto",
    abbreviation: "SKDL",
    color: "#B5121B",
    economicPosition: -4,
    socialPosition: -1,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1979-default"],
    regimeStatus: "approved",
    treasury: 450_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  // ─── 1953 postwar republic ────────────────────────────────────────────
  {
    seedOrder: 10,
    countryId: "FI",
    name: "Maalaisliitto",
    abbreviation: "ML",
    color: "#01954B",
    economicPosition: 0,
    socialPosition: 3, // smallholder-agrarian, church-adjacent countryside
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default"],
    regimeStatus: "approved",
    treasury: 650_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 11,
    countryId: "FI",
    name: "Suomen Sosialidemokraattinen Puolue",
    abbreviation: "SDP",
    color: "#E11931",
    economicPosition: -2,
    socialPosition: -1,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default"],
    regimeStatus: "approved",
    treasury: 650_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 12,
    countryId: "FI",
    name: "Suomen Kansan Demokraattinen Liitto",
    abbreviation: "SKDL",
    color: "#B5121B",
    economicPosition: -4,
    socialPosition: -1,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default"],
    regimeStatus: "approved",
    treasury: 500_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  {
    seedOrder: 13,
    countryId: "FI",
    name: "Kansallinen Kokoomus",
    abbreviation: "Kok",
    color: "#006288",
    economicPosition: 3,
    socialPosition: 2,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1953-default"],
    regimeStatus: "approved",
    treasury: 450_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
  // ─── 1991 successor to SKDL ─────────────────────────────────────────────
  {
    // SKDL dissolved and refounded as Vasemmistoliitto in April 1990,
    // broadening the old communist front ahead of the March 1991 election.
    seedOrder: 5,
    countryId: "FI",
    name: "Vasemmistoliitto",
    abbreviation: "Vas",
    color: "#B5121B",
    economicPosition: -4,
    socialPosition: -1,
    memberCount: 0,
    isDefault: true,
    validForPresets: ["1991-default"],
    regimeStatus: "approved",
    treasury: 350_000,
    nationalTaxRate: 0,
    politicalStrength: 0,
    chairId: null,
    viceChairId: null,
    treasurerId: null,
    committeeIds: [],
    createdBy: null,
  },
];

export default fiParties;
