/**
 * Landesliste management helpers for German AMS (Bundestag) elections.
 *
 * A Landesliste is an ordered list of party candidates per Bundesland.
 * When a party wins list seats in a Land (computed by germanyAMS.ts), the
 * top N candidates on the list fill those seats in order.
 *
 * Lists can be auto-generated by ranking party characters by national
 * influence (NPI), and party chairs can reorder or replace entries via
 * dedicated actions until the list locks at cycle start.
 */

import type { Db, ObjectId as MongoObjectId } from "mongodb";
import { ObjectId } from "mongodb";
import type { Character, Landesliste } from "@/lib/db/types";

const COLLECTION = "landeslisten";

/**
 * Auto-generate a Landesliste for a party + Land by ranking party members
 * resident in that Land by nationalInfluence descending. Characters without
 * NPI fall to the bottom in ObjectId order.
 *
 * Idempotent: upserts by (countryId, partyId, landId, cycle). If the list
 * is already `lockedAt`, this is a no-op and returns the existing doc.
 */
export async function autoGenerateLandesliste(
  db: Db,
  params: {
    partyId: string;
    landId: string;
    cycle: number;
    /** When true, do not overwrite an existing unlocked list (preserves chair edits). */
    preserveExisting?: boolean;
  }
): Promise<Landesliste> {
  const { partyId, landId, cycle, preserveExisting = false } = params;

  const existing = await db.collection<Landesliste>(COLLECTION).findOne({
    countryId: "DE",
    partyId,
    landId,
    cycle,
  });

  if (existing?.lockedAt) return existing;
  if (existing && preserveExisting) return existing;

  // Rank party members in this Land by NPI descending; tie-break by ObjectId
  // (stable-ish ordering across runs).
  const members = await db
    .collection<Character>("characters")
    .find(
      { countryId: "DE", party: partyId, homeState: landId },
      { projection: { _id: 1, nationalInfluence: 1 } }
    )
    .toArray();

  const orderedIds = members
    .slice()
    .sort((a, b) => {
      const aNpi = a.nationalInfluence ?? 0;
      const bNpi = b.nationalInfluence ?? 0;
      if (bNpi !== aNpi) return bNpi - aNpi;
      return a._id.toString().localeCompare(b._id.toString());
    })
    .map((c) => c._id);

  const now = new Date();
  if (existing) {
    await db.collection<Landesliste>(COLLECTION).updateOne(
      { _id: existing._id },
      {
        $set: {
          candidates: orderedIds,
          updatedAt: now,
        },
      }
    );
    return { ...existing, candidates: orderedIds, updatedAt: now };
  }

  const doc: Landesliste = {
    _id: new ObjectId(),
    countryId: "DE",
    partyId,
    landId,
    cycle,
    candidates: orderedIds,
    createdAt: now,
    updatedAt: now,
  };
  await db.collection<Landesliste>(COLLECTION).insertOne(doc);
  return doc;
}

/**
 * Reorder or replace the candidates on an existing unlocked Landesliste.
 * Throws if the list is locked, doesn't exist, or the new candidate list
 * contains anyone who is not a party member in the Land.
 *
 * Returns the updated doc.
 */
export async function reorderLandesliste(
  db: Db,
  params: {
    partyId: string;
    landId: string;
    cycle: number;
    candidates: MongoObjectId[];
    authoredBy?: MongoObjectId;
  }
): Promise<Landesliste> {
  const { partyId, landId, cycle, candidates, authoredBy } = params;

  const existing = await db.collection<Landesliste>(COLLECTION).findOne({
    countryId: "DE",
    partyId,
    landId,
    cycle,
  });

  if (!existing) {
    throw new Error(`No Landesliste for ${partyId} in ${landId} (cycle ${cycle})`);
  }
  if (existing.lockedAt) {
    throw new Error(`Landesliste is locked (${landId}/${partyId}/cycle ${cycle})`);
  }

  // Guard: deduplicate + confirm every candidate is a party member in this Land.
  const dedup = Array.from(new Set(candidates.map((id) => id.toString()))).map(
    (s) => new ObjectId(s)
  );
  if (dedup.length !== candidates.length) {
    throw new Error("Landesliste cannot contain duplicate candidates");
  }

  const validMembers = await db
    .collection<Character>("characters")
    .find(
      { countryId: "DE", party: partyId, homeState: landId, _id: { $in: dedup } },
      { projection: { _id: 1 } }
    )
    .toArray();
  const validIds = new Set(validMembers.map((c) => c._id.toString()));
  for (const id of dedup) {
    if (!validIds.has(id.toString())) {
      throw new Error(`Character ${id.toString()} is not a ${partyId} member in ${landId}`);
    }
  }

  const now = new Date();
  await db.collection<Landesliste>(COLLECTION).updateOne(
    { _id: existing._id },
    {
      $set: {
        candidates: dedup,
        updatedAt: now,
        ...(authoredBy ? { authoredBy } : {}),
      },
    }
  );

  return {
    ...existing,
    candidates: dedup,
    updatedAt: now,
    authoredBy: authoredBy ?? existing.authoredBy,
  };
}

/**
 * Lock a Landesliste, preventing further chair edits. Called at cycle start.
 */
export async function lockLandesliste(
  db: Db,
  params: { partyId: string; landId: string; cycle: number }
): Promise<void> {
  const { partyId, landId, cycle } = params;
  await db
    .collection<Landesliste>(COLLECTION)
    .updateOne({ countryId: "DE", partyId, landId, cycle }, { $set: { lockedAt: new Date() } });
}

/**
 * Auto-generate Landeslisten for every (party, Land) that has resident DE
 * members, for the given cycle. Idempotent and preserves existing chair edits
 * (`preserveExisting`). Called at Bundestag spawn so chairs have an edit window
 * before the list is consumed by the AMS resolver.
 */
export async function generateLandeslistenForCycle(db: Db, cycle: number): Promise<void> {
  const members = await db
    .collection<Character>("characters")
    .find({ countryId: "DE" }, { projection: { _id: 1, party: 1, homeState: 1 } })
    .toArray();

  const seen = new Set<string>();
  for (const m of members) {
    if (!m.party || !m.homeState) continue;
    const key = `${m.party}:${m.homeState}`;
    if (seen.has(key)) continue;
    seen.add(key);
    await autoGenerateLandesliste(db, {
      partyId: m.party,
      landId: m.homeState,
      cycle,
      preserveExisting: true,
    });
  }
}

/**
 * Fetch a single Landesliste. Returns null if not found.
 */
export async function getLandesliste(
  db: Db,
  params: { partyId: string; landId: string; cycle: number }
): Promise<Landesliste | null> {
  const { partyId, landId, cycle } = params;
  return db.collection<Landesliste>(COLLECTION).findOne({
    countryId: "DE",
    partyId,
    landId,
    cycle,
  });
}
