export const parties = [
  {
    _id: "spd",
    name: "Social Democratic Party",
    color: "#E3000F",
    economicPosition: -2,
    socialPosition: -1,
    description: "Centre-left social democratic party.",
  },
  {
    _id: "cdu",
    name: "Christian Democratic Union",
    color: "#000000",
    economicPosition: 1,
    socialPosition: 1,
    description: "Centre-right Christian democratic party.",
  },
  {
    _id: "greens",
    name: "Alliance 90/The Greens",
    color: "#64A12D",
    economicPosition: -1,
    socialPosition: -3,
    description: "Green politics and environmentalism.",
  },
  {
    _id: "fdp",
    name: "Free Democratic Party",
    color: "#FFED00",
    economicPosition: 3,
    socialPosition: -1,
    description: "Classical liberal party supporting free markets.",
  },
  {
    _id: "linke",
    name: "The Left",
    color: "#BE3075",
    economicPosition: -4,
    socialPosition: -2,
    description: "Democratic socialist party.",
  },
  {
    _id: "afd",
    name: "Alternative for Germany",
    color: "#009EE0",
    economicPosition: 2,
    socialPosition: 3,
    description: "Right-wing to far-right party.",
  },
];
