/**
 * Africa — 1953 Tier-3 registry (#3728).
 *
 * Already classified: NG (Tier-1 full-autonomous), GC (Gold Coast tracer), GH (emergent).
 * French West / Equatorial Africa listed as constituent territories under FR
 * (AOF/AEF federation wrappers are approximated by parenting each colony to FR).
 * Rhodesias keep colonial names; Southwest Africa is a SA mandate.
 *
 * Tier-2 candidates ET/ZA listed as Tier-3 until #3721.
 */
import type { WorldEntityManifestEntry } from "@/lib/world/worldEntityManifest";
import {
  dependentRecognition,
  recognized,
  tier3Entry,
  unEligible,
  unIneligible,
  unMember,
} from "./builders";

export function africa1953Entries(presetId: string): WorldEntityManifestEntry[] {
  return [
    // Sovereigns
    tier3Entry(presetId, {
      entityId: "ET",
      displayName: "Ethiopia",
      region: "africa",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["231"],
      notes: "Tier-2 sphere-macro candidate; includes Eritrea federation (1952).",
    }),
    tier3Entry(presetId, {
      entityId: "ZA",
      displayName: "South Africa",
      region: "africa",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["710"],
      notes: "Tier-2 sphere-macro candidate.",
    }),
    tier3Entry(presetId, {
      entityId: "LR",
      displayName: "Liberia",
      region: "africa",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["430"],
    }),
    tier3Entry(presetId, {
      entityId: "EG",
      displayName: "Egypt",
      region: "africa",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["818"],
      notes: "Tier-1 full-autonomous target; Tier-3 until country seed lands.",
    }),
    tier3Entry(presetId, {
      entityId: "LY",
      displayName: "Libya",
      region: "africa",
      status: "sovereign",
      recognition: recognized("Independent kingdom since 1951."),
      un: unEligible(1955),
      mapFeatureIds: ["434"],
      notes: "UN admission Dec 1955; sovereign in 1953.",
    }),
    // Gold Coast tracer (must remain GC — never display as Ghana)
    tier3Entry(presetId, {
      entityId: "GC",
      displayName: "Gold Coast",
      region: "africa",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition(),
      un: unIneligible(1957),
      transitionRuleIds: ["gold-coast-to-ghana"],
      lifecycle: { earliestYear: 1954, expectedYear: 1957, latestYear: 1962 },
      mapFeatureIds: ["288"],
    }),
    // Anglo-Egyptian Sudan — condominium
    tier3Entry(presetId, {
      entityId: "SD",
      displayName: "Anglo-Egyptian Sudan",
      region: "africa",
      status: "dependent",
      parentEntityId: "UK",
      exceptionalStatus: "condominium",
      recognition: dependentRecognition("Anglo-Egyptian condominium."),
      un: unIneligible(1956),
      lifecycle: { earliestYear: 1954, expectedYear: 1956, latestYear: 1960 },
      mapFeatureIds: ["729"],
      notes: "Parent UK for attribution; Egypt is co-condominium partner.",
    }),
    // North Africa protectorates / Algeria
    tier3Entry(presetId, {
      entityId: "MA",
      displayName: "French Morocco",
      region: "africa",
      status: "dependent",
      parentEntityId: "FR",
      recognition: dependentRecognition("French protectorate (Sultanate)."),
      un: unIneligible(1956),
      lifecycle: { earliestYear: 1955, expectedYear: 1956, latestYear: 1960 },
      mapFeatureIds: ["504"],
      notes: "Spanish Morocco / Tangier handled as sibling entries.",
    }),
    tier3Entry(presetId, {
      entityId: "ESH",
      displayName: "Spanish Morocco",
      region: "africa",
      status: "dependent",
      parentEntityId: "ES",
      recognition: dependentRecognition("Spanish protectorate zone."),
      un: unIneligible(1956),
      lifecycle: { earliestYear: 1955, expectedYear: 1956, latestYear: 1960 },
      mapFeatureIds: ["ESH"],
    }),
    tier3Entry(presetId, {
      entityId: "TNG",
      displayName: "Tangier International Zone",
      region: "africa",
      status: "dependent",
      exceptionalStatus: "international-zone",
      recognition: { status: "partial", notes: "International zone; reintegrated 1956." },
      un: unIneligible(),
      lifecycle: { earliestYear: 1956, expectedYear: 1956, latestYear: 1957 },
      mapFeatureIds: ["TNG"],
    }),
    tier3Entry(presetId, {
      entityId: "TN",
      displayName: "Tunisia",
      region: "africa",
      status: "dependent",
      parentEntityId: "FR",
      recognition: dependentRecognition("French protectorate."),
      un: unIneligible(1956),
      lifecycle: { earliestYear: 1955, expectedYear: 1956, latestYear: 1960 },
      mapFeatureIds: ["788"],
    }),
    tier3Entry(presetId, {
      entityId: "DZ",
      displayName: "Algeria",
      region: "africa",
      status: "dependent",
      parentEntityId: "FR",
      exceptionalStatus: "integral-overseas",
      recognition: dependentRecognition("French départements d'Algérie."),
      un: unIneligible(1962),
      lifecycle: { earliestYear: 1958, expectedYear: 1962, latestYear: 1968 },
      mapFeatureIds: ["012"],
      notes: "Independence path on #3727 roster.",
    }),
    // French West Africa constituents (parent FR; AOF is administrative wrapper)
    tier3Entry(presetId, {
      entityId: "SN",
      displayName: "Senegal",
      region: "africa",
      status: "dependent",
      parentEntityId: "FR",
      recognition: dependentRecognition("French West Africa territory."),
      un: unIneligible(1960),
      lifecycle: { earliestYear: 1958, expectedYear: 1960, latestYear: 1965 },
      mapFeatureIds: ["686"],
    }),
    tier3Entry(presetId, {
      entityId: "FSD",
      displayName: "French Sudan",
      region: "africa",
      status: "dependent",
      parentEntityId: "FR",
      recognition: dependentRecognition("French West Africa territory (later Mali)."),
      un: unIneligible(1960),
      lifecycle: { earliestYear: 1958, expectedYear: 1960, latestYear: 1965 },
      mapFeatureIds: ["466"],
      notes: "Not 'Mali' in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "MR",
      displayName: "Mauritania",
      region: "africa",
      status: "dependent",
      parentEntityId: "FR",
      recognition: dependentRecognition("French West Africa territory."),
      un: unIneligible(1960),
      lifecycle: { earliestYear: 1958, expectedYear: 1960, latestYear: 1965 },
      mapFeatureIds: ["478"],
    }),
    tier3Entry(presetId, {
      entityId: "GN",
      displayName: "French Guinea",
      region: "africa",
      status: "dependent",
      parentEntityId: "FR",
      recognition: dependentRecognition("French West Africa territory."),
      un: unIneligible(1958),
      lifecycle: { earliestYear: 1958, expectedYear: 1958, latestYear: 1962 },
      mapFeatureIds: ["324"],
    }),
    tier3Entry(presetId, {
      entityId: "CI",
      displayName: "Ivory Coast",
      region: "africa",
      status: "dependent",
      parentEntityId: "FR",
      recognition: dependentRecognition("French West Africa territory."),
      un: unIneligible(1960),
      lifecycle: { earliestYear: 1958, expectedYear: 1960, latestYear: 1965 },
      mapFeatureIds: ["384"],
      notes: "Prefer 'Ivory Coast' over modern Côte d'Ivoire branding in 1953 copy.",
    }),
    tier3Entry(presetId, {
      entityId: "UV",
      displayName: "Upper Volta",
      region: "africa",
      status: "dependent",
      parentEntityId: "FR",
      recognition: dependentRecognition("French West Africa territory (later Burkina Faso)."),
      un: unIneligible(1960),
      lifecycle: { earliestYear: 1958, expectedYear: 1960, latestYear: 1965 },
      mapFeatureIds: ["854"],
      notes: "Not 'Burkina Faso' in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "DY",
      displayName: "Dahomey",
      region: "africa",
      status: "dependent",
      parentEntityId: "FR",
      recognition: dependentRecognition("French West Africa territory (later Benin)."),
      un: unIneligible(1960),
      lifecycle: { earliestYear: 1958, expectedYear: 1960, latestYear: 1965 },
      mapFeatureIds: ["204"],
      notes: "Not 'Benin' in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "NE",
      displayName: "Niger",
      region: "africa",
      status: "dependent",
      parentEntityId: "FR",
      recognition: dependentRecognition("French West Africa territory."),
      un: unIneligible(1960),
      lifecycle: { earliestYear: 1958, expectedYear: 1960, latestYear: 1965 },
      mapFeatureIds: ["562"],
    }),
    // French Equatorial Africa
    tier3Entry(presetId, {
      entityId: "TD",
      displayName: "Chad",
      region: "africa",
      status: "dependent",
      parentEntityId: "FR",
      recognition: dependentRecognition("French Equatorial Africa territory."),
      un: unIneligible(1960),
      lifecycle: { earliestYear: 1958, expectedYear: 1960, latestYear: 1965 },
      mapFeatureIds: ["148"],
    }),
    tier3Entry(presetId, {
      entityId: "UB",
      displayName: "Ubangi-Shari",
      region: "africa",
      status: "dependent",
      parentEntityId: "FR",
      recognition: dependentRecognition(
        "French Equatorial Africa (later Central African Republic)."
      ),
      un: unIneligible(1960),
      lifecycle: { earliestYear: 1958, expectedYear: 1960, latestYear: 1965 },
      mapFeatureIds: ["140"],
      notes: "Not 'Central African Republic' in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "MCG",
      displayName: "Middle Congo",
      region: "africa",
      status: "dependent",
      parentEntityId: "FR",
      recognition: dependentRecognition("French Equatorial Africa (later Congo-Brazzaville)."),
      un: unIneligible(1960),
      lifecycle: { earliestYear: 1958, expectedYear: 1960, latestYear: 1965 },
      mapFeatureIds: ["178"],
    }),
    tier3Entry(presetId, {
      entityId: "GA",
      displayName: "Gabon",
      region: "africa",
      status: "dependent",
      parentEntityId: "FR",
      recognition: dependentRecognition("French Equatorial Africa territory."),
      un: unIneligible(1960),
      lifecycle: { earliestYear: 1958, expectedYear: 1960, latestYear: 1965 },
      mapFeatureIds: ["266"],
    }),
    tier3Entry(presetId, {
      entityId: "MG",
      displayName: "Madagascar",
      region: "africa",
      status: "dependent",
      parentEntityId: "FR",
      recognition: dependentRecognition("French overseas territory."),
      un: unIneligible(1960),
      lifecycle: { earliestYear: 1958, expectedYear: 1960, latestYear: 1965 },
      mapFeatureIds: ["450"],
    }),
    // Trust territories
    tier3Entry(presetId, {
      entityId: "CMF",
      displayName: "French Cameroun",
      region: "africa",
      status: "dependent",
      parentEntityId: "FR",
      exceptionalStatus: "un-trust-territory",
      recognition: dependentRecognition("UN trust territory under France."),
      un: unIneligible(1960),
      lifecycle: { earliestYear: 1958, expectedYear: 1960, latestYear: 1965 },
      mapFeatureIds: ["120"],
    }),
    tier3Entry(presetId, {
      entityId: "CMB",
      displayName: "British Cameroons",
      region: "africa",
      status: "dependent",
      parentEntityId: "UK",
      exceptionalStatus: "un-trust-territory",
      recognition: dependentRecognition("UN trust territory under UK."),
      un: unIneligible(1961),
      lifecycle: { earliestYear: 1959, expectedYear: 1961, latestYear: 1965 },
      mapFeatureIds: ["CMB"],
    }),
    tier3Entry(presetId, {
      entityId: "TGF",
      displayName: "French Togoland",
      region: "africa",
      status: "dependent",
      parentEntityId: "FR",
      exceptionalStatus: "un-trust-territory",
      recognition: dependentRecognition("UN trust territory under France."),
      un: unIneligible(1960),
      lifecycle: { earliestYear: 1958, expectedYear: 1960, latestYear: 1965 },
      mapFeatureIds: ["768"],
    }),
    tier3Entry(presetId, {
      entityId: "TGB",
      displayName: "British Togoland",
      region: "africa",
      status: "dependent",
      parentEntityId: "UK",
      exceptionalStatus: "un-trust-territory",
      recognition: dependentRecognition("UN trust territory; union with Gold Coast path."),
      un: unIneligible(1957),
      lifecycle: { earliestYear: 1956, expectedYear: 1957, latestYear: 1960 },
      mapFeatureIds: ["TGB"],
    }),
    // British East / Central / Southern Africa
    tier3Entry(presetId, {
      entityId: "KE",
      displayName: "Kenya",
      region: "africa",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British crown colony / protectorate."),
      un: unIneligible(1963),
      lifecycle: { earliestYear: 1960, expectedYear: 1963, latestYear: 1968 },
      mapFeatureIds: ["404"],
    }),
    tier3Entry(presetId, {
      entityId: "UG",
      displayName: "Uganda",
      region: "africa",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British protectorate."),
      un: unIneligible(1962),
      lifecycle: { earliestYear: 1960, expectedYear: 1962, latestYear: 1968 },
      mapFeatureIds: ["800"],
    }),
    tier3Entry(presetId, {
      entityId: "TANG",
      displayName: "Tanganyika",
      region: "africa",
      status: "dependent",
      parentEntityId: "UK",
      exceptionalStatus: "un-trust-territory",
      recognition: dependentRecognition("UN trust territory under UK."),
      un: unIneligible(1961),
      lifecycle: { earliestYear: 1959, expectedYear: 1961, latestYear: 1965 },
      mapFeatureIds: ["834"],
      notes: "Not 'Tanzania' (union with Zanzibar is 1964).",
    }),
    tier3Entry(presetId, {
      entityId: "ZNZ",
      displayName: "Zanzibar",
      region: "africa",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British protectorate sultanate."),
      un: unIneligible(1963),
      lifecycle: { earliestYear: 1961, expectedYear: 1963, latestYear: 1965 },
      mapFeatureIds: ["ZNZ"],
    }),
    tier3Entry(presetId, {
      entityId: "SL",
      displayName: "Sierra Leone",
      region: "africa",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition(),
      un: unIneligible(1961),
      lifecycle: { earliestYear: 1958, expectedYear: 1961, latestYear: 1965 },
      mapFeatureIds: ["694"],
    }),
    tier3Entry(presetId, {
      entityId: "GM",
      displayName: "Gambia",
      region: "africa",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition(),
      un: unIneligible(1965),
      lifecycle: { earliestYear: 1962, expectedYear: 1965, latestYear: 1970 },
      mapFeatureIds: ["270"],
    }),
    tier3Entry(presetId, {
      entityId: "NRH",
      displayName: "Northern Rhodesia",
      region: "africa",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("Federation of Rhodesia and Nyasaland (1953)."),
      un: unIneligible(1964),
      lifecycle: { earliestYear: 1962, expectedYear: 1964, latestYear: 1968 },
      mapFeatureIds: ["894"],
      notes: "Not 'Zambia' in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "SRH",
      displayName: "Southern Rhodesia",
      region: "africa",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("Self-governing colony within the Federation."),
      un: unIneligible(1980),
      lifecycle: { earliestYear: 1965, expectedYear: 1980, latestYear: 1985 },
      mapFeatureIds: ["716"],
      notes: "Not 'Zimbabwe' in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "NYA",
      displayName: "Nyasaland",
      region: "africa",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("Protectorate within the Federation."),
      un: unIneligible(1964),
      lifecycle: { earliestYear: 1962, expectedYear: 1964, latestYear: 1968 },
      mapFeatureIds: ["454"],
      notes: "Not 'Malawi' in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "BCU",
      displayName: "Bechuanaland",
      region: "africa",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British protectorate (later Botswana)."),
      un: unIneligible(1966),
      lifecycle: { earliestYear: 1963, expectedYear: 1966, latestYear: 1970 },
      mapFeatureIds: ["072"],
    }),
    tier3Entry(presetId, {
      entityId: "BAS",
      displayName: "Basutoland",
      region: "africa",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British protectorate (later Lesotho)."),
      un: unIneligible(1966),
      lifecycle: { earliestYear: 1963, expectedYear: 1966, latestYear: 1970 },
      mapFeatureIds: ["426"],
    }),
    tier3Entry(presetId, {
      entityId: "SWZ",
      displayName: "Swaziland",
      region: "africa",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British protectorate."),
      un: unIneligible(1968),
      lifecycle: { earliestYear: 1965, expectedYear: 1968, latestYear: 1972 },
      mapFeatureIds: ["748"],
      notes: "Not 'eSwatini' branding in 1953.",
    }),
    // Belgian / Portuguese / Spanish / Italian / SA mandate
    tier3Entry(presetId, {
      entityId: "BCO",
      displayName: "Belgian Congo",
      region: "africa",
      status: "dependent",
      parentEntityId: "BE",
      recognition: dependentRecognition(),
      un: unIneligible(1960),
      lifecycle: { earliestYear: 1958, expectedYear: 1960, latestYear: 1965 },
      mapFeatureIds: ["180"],
      notes: "Independence → Congo path on #3727; not modern DRC name alone.",
    }),
    tier3Entry(presetId, {
      entityId: "RUA",
      displayName: "Ruanda-Urundi",
      region: "africa",
      status: "dependent",
      parentEntityId: "BE",
      exceptionalStatus: "un-trust-territory",
      recognition: dependentRecognition("UN trust territory under Belgium."),
      un: unIneligible(1962),
      lifecycle: { earliestYear: 1960, expectedYear: 1962, latestYear: 1966 },
      // The trust territory is exactly the two modern states it split into, so the
      // pair of present-day features is its own border — no historical shape needed.
      mapFeatureIds: ["646", "108"],
      notes: "Splits to Rwanda and Burundi; single trust entity in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "AO",
      displayName: "Portuguese Angola",
      region: "africa",
      status: "dependent",
      parentEntityId: "PT",
      recognition: dependentRecognition("Portuguese overseas province."),
      un: unIneligible(1975),
      lifecycle: { earliestYear: 1970, expectedYear: 1975, latestYear: 1980 },
      mapFeatureIds: ["024"],
    }),
    tier3Entry(presetId, {
      entityId: "MZ",
      displayName: "Portuguese Mozambique",
      region: "africa",
      status: "dependent",
      parentEntityId: "PT",
      recognition: dependentRecognition("Portuguese overseas province."),
      un: unIneligible(1975),
      lifecycle: { earliestYear: 1970, expectedYear: 1975, latestYear: 1980 },
      mapFeatureIds: ["508"],
    }),
    tier3Entry(presetId, {
      entityId: "GW",
      displayName: "Portuguese Guinea",
      region: "africa",
      status: "dependent",
      parentEntityId: "PT",
      recognition: dependentRecognition("Portuguese overseas province (later Guinea-Bissau)."),
      un: unIneligible(1974),
      lifecycle: { earliestYear: 1970, expectedYear: 1974, latestYear: 1978 },
      mapFeatureIds: ["624"],
    }),
    tier3Entry(presetId, {
      entityId: "CV",
      displayName: "Cape Verde",
      region: "africa",
      status: "dependent",
      parentEntityId: "PT",
      recognition: dependentRecognition("Portuguese overseas province."),
      un: unIneligible(1975),
      mapFeatureIds: ["132"],
    }),
    tier3Entry(presetId, {
      // STP — not ST (HEAD #3727 uses ST for the combined Somalia Trust tracer).
      entityId: "STP",
      displayName: "São Tomé and Príncipe",
      region: "africa",
      status: "dependent",
      parentEntityId: "PT",
      recognition: dependentRecognition("Portuguese overseas province."),
      un: unIneligible(1975),
      mapFeatureIds: ["678"],
    }),
    tier3Entry(presetId, {
      entityId: "EQG",
      displayName: "Spanish Guinea",
      region: "africa",
      status: "dependent",
      parentEntityId: "ES",
      recognition: dependentRecognition("Spanish overseas territory (later Equatorial Guinea)."),
      un: unIneligible(1968),
      lifecycle: { earliestYear: 1965, expectedYear: 1968, latestYear: 1972 },
      mapFeatureIds: ["226"],
    }),
    tier3Entry(presetId, {
      entityId: "ESH2",
      displayName: "Spanish Sahara",
      region: "africa",
      status: "dependent",
      parentEntityId: "ES",
      recognition: dependentRecognition("Spanish overseas province."),
      un: unIneligible(),
      mapFeatureIds: ["732"],
      notes: "Western Sahara dispute is post-1975; colonial dependency in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "ITS",
      displayName: "Trust Territory of Somaliland",
      region: "africa",
      status: "dependent",
      parentEntityId: "IT",
      exceptionalStatus: "un-trust-territory",
      recognition: dependentRecognition("UN trust under Italy (former Italian Somaliland)."),
      un: unIneligible(1960),
      lifecycle: { earliestYear: 1958, expectedYear: 1960, latestYear: 1965 },
      notes: "Merges with British Somaliland → Somalia 1960 (#3727).",
    }),
    tier3Entry(presetId, {
      entityId: "BSL",
      displayName: "British Somaliland",
      region: "africa",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition(),
      un: unIneligible(1960),
      lifecycle: { earliestYear: 1958, expectedYear: 1960, latestYear: 1965 },
      mapFeatureIds: ["706"],
    }),
    tier3Entry(presetId, {
      entityId: "FSOM",
      displayName: "French Somaliland",
      region: "africa",
      status: "dependent",
      parentEntityId: "FR",
      recognition: dependentRecognition("French overseas territory (later Djibouti)."),
      un: unIneligible(1977),
      lifecycle: { earliestYear: 1975, expectedYear: 1977, latestYear: 1982 },
      mapFeatureIds: ["262"],
    }),
    tier3Entry(presetId, {
      entityId: "SWA",
      displayName: "South West Africa",
      region: "africa",
      status: "dependent",
      parentEntityId: "ZA",
      exceptionalStatus: "international-mandate",
      recognition: dependentRecognition("League mandate administered by South Africa."),
      un: unIneligible(1990),
      lifecycle: { earliestYear: 1966, expectedYear: 1990, latestYear: 1995 },
      mapFeatureIds: ["516"],
      notes: "Not 'Namibia' in 1953.",
    }),
  ];
}
