/**
 * Americas — 1953 Tier-3 registry (#3728).
 *
 * Already classified: US, BR (CountryConfig). Tier-2 candidates (MX, CU, GT, PA,
 * NI, CL, AR, VE) are listed here as Tier-3 until sphere-macro seeding (#3721).
 *
 * Dominions: Canada is a sovereign Commonwealth realm (Statute of Westminster).
 * Caribbean/South American colonies keep 1953 names (British Guiana, British
 * Honduras, Dutch Guiana).
 */
import type { WorldEntityManifestEntry } from "@/lib/world/worldEntityManifest";
import { dependentRecognition, recognized, tier3Entry, unIneligible, unMember } from "./builders";

export function americas1953Entries(presetId: string): WorldEntityManifestEntry[] {
  return [
    // Sovereigns
    tier3Entry(presetId, {
      entityId: "CA",
      displayName: "Canada",
      region: "americas",
      status: "sovereign",
      recognition: recognized("Commonwealth realm."),
      un: unMember(1945),
      mapFeatureIds: ["124"],
    }),
    tier3Entry(presetId, {
      entityId: "MX",
      displayName: "Mexico",
      region: "americas",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["484"],
      notes: "Tier-2 sphere-macro candidate.",
    }),
    tier3Entry(presetId, {
      entityId: "CU",
      displayName: "Cuba",
      region: "americas",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["192"],
      notes: "Tier-2 sphere-macro candidate.",
    }),
    tier3Entry(presetId, {
      entityId: "GT",
      displayName: "Guatemala",
      region: "americas",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["320"],
      notes: "Tier-2 sphere-macro candidate.",
    }),
    tier3Entry(presetId, {
      entityId: "PA",
      displayName: "Panama",
      region: "americas",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["591"],
      notes: "Tier-2 sphere-macro candidate; Canal Zone remains US-controlled separately.",
    }),
    tier3Entry(presetId, {
      entityId: "NI",
      displayName: "Nicaragua",
      region: "americas",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["558"],
      notes: "Tier-2 sphere-macro candidate.",
    }),
    tier3Entry(presetId, {
      entityId: "CL",
      displayName: "Chile",
      region: "americas",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["152"],
      notes: "Tier-2 sphere-macro candidate.",
    }),
    tier3Entry(presetId, {
      entityId: "AR",
      displayName: "Argentina",
      region: "americas",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["032"],
      notes: "Tier-2 sphere-macro candidate.",
    }),
    tier3Entry(presetId, {
      entityId: "VE",
      displayName: "Venezuela",
      region: "americas",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["862"],
      notes: "Tier-2 sphere-macro candidate.",
    }),
    tier3Entry(presetId, {
      entityId: "CO",
      displayName: "Colombia",
      region: "americas",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["170"],
    }),
    tier3Entry(presetId, {
      entityId: "EC",
      displayName: "Ecuador",
      region: "americas",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["218"],
    }),
    tier3Entry(presetId, {
      entityId: "PE",
      displayName: "Peru",
      region: "americas",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["604"],
    }),
    tier3Entry(presetId, {
      entityId: "BO",
      displayName: "Bolivia",
      region: "americas",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["068"],
    }),
    tier3Entry(presetId, {
      entityId: "PY",
      displayName: "Paraguay",
      region: "americas",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["600"],
    }),
    tier3Entry(presetId, {
      entityId: "UY",
      displayName: "Uruguay",
      region: "americas",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["858"],
    }),
    tier3Entry(presetId, {
      entityId: "CR",
      displayName: "Costa Rica",
      region: "americas",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["188"],
    }),
    tier3Entry(presetId, {
      entityId: "SV",
      displayName: "El Salvador",
      region: "americas",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["222"],
    }),
    tier3Entry(presetId, {
      entityId: "HN",
      displayName: "Honduras",
      region: "americas",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["340"],
    }),
    tier3Entry(presetId, {
      entityId: "DO",
      displayName: "Dominican Republic",
      region: "americas",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["214"],
    }),
    tier3Entry(presetId, {
      entityId: "HT",
      displayName: "Haiti",
      region: "americas",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["332"],
    }),
    // Dependencies
    tier3Entry(presetId, {
      entityId: "BGY",
      displayName: "British Guiana",
      region: "americas",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition(),
      un: unIneligible(1966),
      lifecycle: { earliestYear: 1961, expectedYear: 1966, latestYear: 1970 },
      mapFeatureIds: ["328"],
      notes: "Independence → Guyana 1966 (#3727 roster). Not 'Guyana' in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "BHN",
      displayName: "British Honduras",
      region: "americas",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition(),
      un: unIneligible(1981),
      lifecycle: { earliestYear: 1964, expectedYear: 1981, latestYear: 1985 },
      mapFeatureIds: ["084"],
      notes: "Later Belize; keep 1953 colonial name.",
    }),
    tier3Entry(presetId, {
      entityId: "JM",
      displayName: "Jamaica",
      region: "americas",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition(),
      un: unIneligible(1962),
      lifecycle: { earliestYear: 1958, expectedYear: 1962, latestYear: 1966 },
      mapFeatureIds: ["388"],
    }),
    tier3Entry(presetId, {
      entityId: "TT",
      displayName: "Trinidad and Tobago",
      region: "americas",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition(),
      un: unIneligible(1962),
      lifecycle: { earliestYear: 1958, expectedYear: 1962, latestYear: 1966 },
      mapFeatureIds: ["780"],
    }),
    tier3Entry(presetId, {
      entityId: "BB",
      displayName: "Barbados",
      region: "americas",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition(),
      un: unIneligible(1966),
      lifecycle: { earliestYear: 1961, expectedYear: 1966, latestYear: 1970 },
      mapFeatureIds: ["052"],
    }),
    tier3Entry(presetId, {
      entityId: "BS",
      displayName: "Bahamas",
      region: "americas",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition(),
      un: unIneligible(1973),
      mapFeatureIds: ["044"],
    }),
    tier3Entry(presetId, {
      entityId: "BM",
      displayName: "Bermuda",
      region: "americas",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition(),
      un: unIneligible(),
      mapFeatureIds: ["060"],
    }),
    tier3Entry(presetId, {
      entityId: "FK",
      displayName: "Falkland Islands",
      region: "americas",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition(),
      un: unIneligible(),
      mapFeatureIds: ["238"],
    }),
    tier3Entry(presetId, {
      entityId: "PR",
      displayName: "Puerto Rico",
      region: "americas",
      status: "dependent",
      parentEntityId: "US",
      recognition: dependentRecognition("US commonwealth (1952 constitution)."),
      un: unIneligible(),
      mapFeatureIds: ["630"],
    }),
    tier3Entry(presetId, {
      entityId: "VI",
      displayName: "US Virgin Islands",
      region: "americas",
      status: "dependent",
      parentEntityId: "US",
      recognition: dependentRecognition(),
      un: unIneligible(),
      mapFeatureIds: ["850"],
    }),
    tier3Entry(presetId, {
      entityId: "CZ",
      displayName: "Panama Canal Zone",
      region: "americas",
      status: "dependent",
      parentEntityId: "US",
      exceptionalStatus: "integral-overseas",
      recognition: dependentRecognition("US-administered Canal Zone."),
      un: unIneligible(),
      notes: "Distinct from sovereign Panama; returned under Torrijos–Carter path.",
      mapFeatureIds: ["CZ"],
    }),
    tier3Entry(presetId, {
      entityId: "SUR",
      displayName: "Dutch Guiana",
      region: "americas",
      status: "dependent",
      parentEntityId: "NL",
      recognition: dependentRecognition(
        "Suriname as constituent of the Kingdom (1954 charter pending)."
      ),
      un: unIneligible(1975),
      lifecycle: { earliestYear: 1970, expectedYear: 1975, latestYear: 1980 },
      mapFeatureIds: ["740"],
      notes: "Not 'Suriname' as an independent state in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "GF",
      displayName: "French Guiana",
      region: "americas",
      status: "dependent",
      parentEntityId: "FR",
      exceptionalStatus: "integral-overseas",
      recognition: dependentRecognition("French overseas département (1946)."),
      un: unIneligible(),
      mapFeatureIds: ["254"],
    }),
    tier3Entry(presetId, {
      entityId: "GP",
      displayName: "Guadeloupe",
      region: "americas",
      status: "dependent",
      parentEntityId: "FR",
      exceptionalStatus: "integral-overseas",
      recognition: dependentRecognition("French overseas département."),
      un: unIneligible(),
      mapFeatureIds: ["312"],
    }),
    tier3Entry(presetId, {
      entityId: "MQ",
      displayName: "Martinique",
      region: "americas",
      status: "dependent",
      parentEntityId: "FR",
      exceptionalStatus: "integral-overseas",
      recognition: dependentRecognition("French overseas département."),
      un: unIneligible(),
      mapFeatureIds: ["474"],
    }),
  ];
}
