/**
 * Asia / Middle East — 1953 Tier-3 registry (#3728).
 *
 * Already classified: CN, JP (CountryConfig). Taiwan and Israel are explicit
 * status records even though outside the expanded Tier-1/2 candidate slate.
 *
 * Historical names: Ceylon (not Sri Lanka), Federation of Malaya, Burma,
 * South Vietnam / North Vietnam as separate polities, Aden Colony.
 * USSR union republics are NOT separate sovereigns — covered by RU.
 */
import type { WorldEntityManifestEntry } from "@/lib/world/worldEntityManifest";
import {
  contestedRecognition,
  dependentRecognition,
  partialRecognition,
  recognized,
  tier3Entry,
  unEligible,
  unIneligible,
  unMember,
} from "./builders";

export function asia1953Entries(presetId: string): WorldEntityManifestEntry[] {
  return [
    // Explicit out-of-slate status records
    tier3Entry(presetId, {
      entityId: "IL",
      displayName: "Israel",
      region: "asia",
      status: "sovereign",
      recognition: partialRecognition(
        "UN member; recognition contested by several Arab League states."
      ),
      un: unMember(1949),
      mapFeatureIds: ["376"],
      notes: "Explicit Tier-3 record outside the expanded candidate slate (#3728).",
    }),
    tier3Entry(presetId, {
      entityId: "TW",
      displayName: "Taiwan",
      region: "asia",
      status: "sovereign",
      exceptionalStatus: "disputed-sovereignty",
      recognition: contestedRecognition(
        "ROC on Taiwan; holds China's UN seat in 1953. PRC contests sovereignty."
      ),
      un: unMember(1945),
      mapFeatureIds: ["158"],
      notes:
        "Explicit status record outside the expanded candidate slate. UN seat is ROC until 1971; map proxy is Taiwan feature.",
    }),
    // Middle East / South Asia sovereigns
    tier3Entry(presetId, {
      entityId: "LB",
      displayName: "Lebanon",
      region: "asia",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["422"],
    }),
    tier3Entry(presetId, {
      entityId: "SY",
      displayName: "Syria",
      region: "asia",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["760"],
      notes: "Tier-1 full-autonomous target; Tier-3 until country seed lands.",
    }),
    tier3Entry(presetId, {
      entityId: "IQ",
      displayName: "Iraq",
      region: "asia",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["368"],
      notes: "Tier-1 full-autonomous target; Tier-3 until country seed lands.",
    }),
    tier3Entry(presetId, {
      entityId: "IR",
      displayName: "Iran",
      region: "asia",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["364"],
      notes: "Tier-1 full-autonomous target; Tier-3 until country seed lands.",
    }),
    tier3Entry(presetId, {
      entityId: "SA",
      displayName: "Saudi Arabia",
      region: "asia",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["682"],
      notes: "Tier-1 full-autonomous target; Tier-3 until country seed lands.",
    }),
    tier3Entry(presetId, {
      entityId: "JO",
      displayName: "Jordan",
      region: "asia",
      status: "sovereign",
      recognition: recognized(),
      un: unEligible(1955),
      mapFeatureIds: ["400"],
      notes: "Tier-2 candidate; UN admission 1955 — eligible sovereign in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "YE",
      displayName: "Yemen",
      region: "asia",
      status: "sovereign",
      recognition: recognized("Mutawakkilite Kingdom of Yemen (North Yemen)."),
      un: unMember(1947),
      mapFeatureIds: ["887"],
      notes: "Tier-2 North Yemen candidate; Aden/South Arabia is a separate dependency.",
    }),
    tier3Entry(presetId, {
      entityId: "AF",
      displayName: "Afghanistan",
      region: "asia",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1946),
      mapFeatureIds: ["004"],
      notes: "Tier-2 sphere-macro candidate.",
    }),
    tier3Entry(presetId, {
      entityId: "IN",
      displayName: "India",
      region: "asia",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["356"],
      notes: "Tier-1 full-autonomous target; Tier-3 until country seed lands.",
    }),
    tier3Entry(presetId, {
      entityId: "PK",
      displayName: "Pakistan",
      region: "asia",
      status: "sovereign",
      recognition: recognized("Includes East Bengal / East Pakistan."),
      un: unMember(1947),
      mapFeatureIds: ["586"],
      notes: "Tier-1 target. East Pakistan is not a separate 1953 sovereign (no Bangladesh).",
    }),
    tier3Entry(presetId, {
      entityId: "CE",
      displayName: "Ceylon",
      region: "asia",
      status: "sovereign",
      recognition: recognized("Dominion of Ceylon."),
      un: unEligible(1955),
      mapFeatureIds: ["144"],
      notes: "Not 'Sri Lanka' in 1953. UN admission 1955.",
    }),
    tier3Entry(presetId, {
      entityId: "NP",
      displayName: "Nepal",
      region: "asia",
      status: "sovereign",
      recognition: recognized(),
      un: unEligible(1955),
      mapFeatureIds: ["524"],
    }),
    tier3Entry(presetId, {
      entityId: "BT",
      displayName: "Bhutan",
      region: "asia",
      status: "sovereign",
      recognition: partialRecognition("Sovereign; Indian guidance treaty 1949."),
      un: unIneligible(),
      mapFeatureIds: ["064"],
    }),
    tier3Entry(presetId, {
      entityId: "MN",
      displayName: "Mongolia",
      region: "asia",
      status: "sovereign",
      recognition: partialRecognition("Widely unrecognized in the West until later UN entry."),
      un: unEligible(1961),
      mapFeatureIds: ["496"],
      notes: "UN admission 1961; sovereign Mongolian People's Republic in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "PH",
      displayName: "Philippines",
      region: "asia",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["608"],
    }),
    tier3Entry(presetId, {
      entityId: "TH",
      displayName: "Thailand",
      region: "asia",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1946),
      mapFeatureIds: ["764"],
      notes: "Tier-2 sphere-macro candidate.",
    }),
    tier3Entry(presetId, {
      entityId: "BU",
      displayName: "Burma",
      region: "asia",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1948),
      mapFeatureIds: ["104"],
      notes: "Not 'Myanmar' in 1953. Tier-2 candidate.",
    }),
    tier3Entry(presetId, {
      entityId: "KH",
      displayName: "Cambodia",
      region: "asia",
      status: "sovereign",
      recognition: recognized("Independent from France 1953."),
      un: unEligible(1955),
      mapFeatureIds: ["116"],
      notes: "Tier-2 candidate. Independence Nov 1953 — treated sovereign at era start.",
    }),
    tier3Entry(presetId, {
      entityId: "LA",
      displayName: "Laos",
      region: "asia",
      status: "sovereign",
      recognition: recognized("Associated state / independence path 1953–54."),
      un: unEligible(1955),
      mapFeatureIds: ["418"],
      notes:
        "Tier-2 candidate. Approx.: sovereign by Geneva 1954; listed sovereign for 1953 slice.",
    }),
    tier3Entry(presetId, {
      entityId: "ID",
      displayName: "Indonesia",
      region: "asia",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1950),
      mapFeatureIds: ["360"],
      notes: "Tier-1 full-autonomous target; Tier-3 until country seed lands.",
    }),
    tier3Entry(presetId, {
      entityId: "KP",
      displayName: "North Korea",
      region: "asia",
      status: "sovereign",
      recognition: partialRecognition("DPRK; recognition split by Cold War camps."),
      un: unIneligible(),
      mapFeatureIds: ["408"],
      notes: "Tier-1 target; not a UN member in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "KR",
      displayName: "South Korea",
      region: "asia",
      status: "sovereign",
      recognition: partialRecognition("ROK; recognition split by Cold War camps."),
      un: unIneligible(),
      mapFeatureIds: ["410"],
      notes: "Tier-1 target; not a UN member in 1953 (admitted 1991).",
    }),
    tier3Entry(presetId, {
      entityId: "NVN",
      displayName: "North Vietnam",
      region: "asia",
      status: "sovereign",
      recognition: partialRecognition("DRVN; recognition contested."),
      un: unIneligible(),
      mapFeatureIds: ["704"],
      notes: "Tier-1 target. Shares modern Vietnam geometry as proxy.",
    }),
    tier3Entry(presetId, {
      entityId: "SVN",
      displayName: "South Vietnam",
      region: "asia",
      status: "sovereign",
      recognition: partialRecognition("State of Vietnam → Republic of Vietnam path."),
      un: unIneligible(),
      notes: "Tier-1 target. No separate Natural Earth feature; unmapped until authored.",
    }),
    // Dependencies / protected states
    tier3Entry(presetId, {
      entityId: "MLY",
      displayName: "Federation of Malaya",
      region: "asia",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British-protected federation (1948)."),
      un: unIneligible(1957),
      lifecycle: { earliestYear: 1955, expectedYear: 1957, latestYear: 1962 },
      mapFeatureIds: ["458"],
      notes: "Not modern 'Malaysia' (1963 enlargement).",
    }),
    tier3Entry(presetId, {
      entityId: "SG",
      displayName: "Singapore",
      region: "asia",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British crown colony."),
      un: unIneligible(1965),
      lifecycle: { earliestYear: 1959, expectedYear: 1965, latestYear: 1970 },
      mapFeatureIds: ["702"],
    }),
    tier3Entry(presetId, {
      entityId: "BN",
      displayName: "Brunei",
      region: "asia",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British protected sultanate."),
      un: unIneligible(1984),
      mapFeatureIds: ["096"],
    }),
    tier3Entry(presetId, {
      entityId: "HK",
      displayName: "Hong Kong",
      region: "asia",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British crown colony."),
      un: unIneligible(),
      mapFeatureIds: ["344"],
    }),
    tier3Entry(presetId, {
      entityId: "MO",
      displayName: "Macau",
      region: "asia",
      status: "dependent",
      parentEntityId: "PT",
      recognition: dependentRecognition("Portuguese overseas province."),
      un: unIneligible(),
      mapFeatureIds: ["446"],
    }),
    tier3Entry(presetId, {
      entityId: "TP",
      displayName: "Portuguese Timor",
      region: "asia",
      status: "dependent",
      parentEntityId: "PT",
      recognition: dependentRecognition("Portuguese overseas province."),
      un: unIneligible(1975),
      mapFeatureIds: ["626"],
      notes: "Not 'Timor-Leste' in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "ADN",
      displayName: "Aden Colony",
      region: "asia",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British crown colony and protectorates."),
      un: unIneligible(1967),
      lifecycle: { earliestYear: 1963, expectedYear: 1967, latestYear: 1972 },
      notes: "South Arabia → South Yemen path on #3727.",
    }),
    tier3Entry(presetId, {
      entityId: "KW",
      displayName: "Kuwait",
      region: "asia",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British protected sheikhdom."),
      un: unIneligible(1961),
      lifecycle: { earliestYear: 1959, expectedYear: 1961, latestYear: 1965 },
      mapFeatureIds: ["414"],
    }),
    tier3Entry(presetId, {
      entityId: "BH",
      displayName: "Bahrain",
      region: "asia",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British protected sheikhdom."),
      un: unIneligible(1971),
      mapFeatureIds: ["048"],
    }),
    tier3Entry(presetId, {
      entityId: "QA",
      displayName: "Qatar",
      region: "asia",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British protected sheikhdom."),
      un: unIneligible(1971),
      mapFeatureIds: ["634"],
    }),
    tier3Entry(presetId, {
      entityId: "TRE",
      displayName: "Trucial States",
      region: "asia",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British-protected Gulf sheikhdoms (later UAE)."),
      un: unIneligible(1971),
      lifecycle: { earliestYear: 1968, expectedYear: 1971, latestYear: 1975 },
      mapFeatureIds: ["784"],
      notes: "Not 'United Arab Emirates' in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "OM",
      displayName: "Muscat and Oman",
      region: "asia",
      status: "sovereign",
      recognition: partialRecognition("Independent sultanate; limited diplomatic footprint."),
      un: unIneligible(),
      mapFeatureIds: ["512"],
      notes:
        "Approx.: treated sovereign; British influence without formal protectorate after 1951.",
    }),
    tier3Entry(presetId, {
      entityId: "PS",
      displayName: "Palestinian territories",
      region: "asia",
      status: "dependent",
      exceptionalStatus: "disputed-sovereignty",
      recognition: contestedRecognition(
        "Former Mandate territory; West Bank under Jordanian admin, Gaza under Egyptian admin in 1953."
      ),
      un: unIneligible(),
      notes: "No single sovereign parent; exceptional disputed/post-Mandate record.",
    }),
  ];
}
