/**
 * Europe / North Atlantic — 1953 Tier-3 registry (#3728).
 *
 * CountryConfig / sphere-macro pilots already cover: UK, FR, DE, DD, IT, ES, SE,
 * TR, IE, AT, HU, PL, RO, YU, BG, CS, RU. This file adds the remaining sovereigns,
 * microstates, and European dependencies.
 *
 * Assumptions: Saar listed as French-administered exceptional territory (not yet
 * returned to FRG); Trieste Free Territory dissolving 1954; Malta/Cyprus remain
 * British colonies; Vatican/monacos recognized sovereigns without UN membership.
 */
import type { WorldEntityManifestEntry } from "@/lib/world/worldEntityManifest";
import {
  dependentRecognition,
  recognized,
  tier3Entry,
  unEligible,
  unIneligible,
  unMember,
} from "./builders";

export function europe1953Entries(presetId: string): WorldEntityManifestEntry[] {
  return [
    tier3Entry(presetId, {
      entityId: "AL",
      displayName: "Albania",
      region: "europe",
      status: "sovereign",
      recognition: recognized("People's Republic; limited Western recognition."),
      un: unEligible(1955),
      mapFeatureIds: ["008"],
      notes: "UN admission Dec 1955; eligible sovereign in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "BE",
      displayName: "Belgium",
      region: "europe",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["056"],
    }),
    tier3Entry(presetId, {
      entityId: "NL",
      displayName: "Netherlands",
      region: "europe",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["528"],
    }),
    tier3Entry(presetId, {
      entityId: "LU",
      displayName: "Luxembourg",
      region: "europe",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["442"],
    }),
    tier3Entry(presetId, {
      entityId: "DK",
      displayName: "Denmark",
      region: "europe",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["208"],
    }),
    tier3Entry(presetId, {
      entityId: "NO",
      displayName: "Norway",
      region: "europe",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["578"],
    }),
    tier3Entry(presetId, {
      entityId: "IS",
      displayName: "Iceland",
      region: "europe",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1946),
      mapFeatureIds: ["352"],
    }),
    tier3Entry(presetId, {
      entityId: "PT",
      displayName: "Portugal",
      region: "europe",
      status: "sovereign",
      recognition: recognized(),
      un: unEligible(1955),
      mapFeatureIds: ["620"],
      notes: "UN admission Dec 1955; sovereign in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "CH",
      displayName: "Switzerland",
      region: "europe",
      status: "sovereign",
      recognition: recognized(),
      un: unEligible(), // joined 2002; deliberately not a 1950s UN actor
      mapFeatureIds: ["756"],
      notes: "Neutral; not a UN member in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "FI",
      displayName: "Finland",
      region: "europe",
      status: "sovereign",
      recognition: recognized(),
      un: unEligible(1955),
      mapFeatureIds: ["246"],
      notes: "Tier-2 sphere-macro candidate; Tier-3 until macro roster lands.",
    }),
    tier3Entry(presetId, {
      entityId: "GR",
      displayName: "Greece",
      region: "europe",
      status: "sovereign",
      recognition: recognized(),
      un: unMember(1945),
      mapFeatureIds: ["300"],
      notes: "Tier-2 sphere-macro candidate; Tier-3 until macro roster lands.",
    }),
    // Microstates
    tier3Entry(presetId, {
      entityId: "VA",
      displayName: "Vatican City",
      region: "europe",
      status: "sovereign",
      recognition: recognized("Holy See; observer diplomacy."),
      un: unIneligible(),
      mapFeatureIds: ["336"],
    }),
    tier3Entry(presetId, {
      entityId: "MC",
      displayName: "Monaco",
      region: "europe",
      status: "sovereign",
      recognition: recognized(),
      un: unIneligible(),
      mapFeatureIds: ["492"],
    }),
    tier3Entry(presetId, {
      entityId: "AD",
      displayName: "Andorra",
      region: "europe",
      status: "sovereign",
      recognition: recognized("Co-principality under French/Spanish episcopal arrangement."),
      un: unIneligible(),
      mapFeatureIds: ["020"],
    }),
    tier3Entry(presetId, {
      entityId: "SM",
      displayName: "San Marino",
      region: "europe",
      status: "sovereign",
      recognition: recognized(),
      un: unIneligible(),
      mapFeatureIds: ["674"],
    }),
    tier3Entry(presetId, {
      entityId: "LI",
      displayName: "Liechtenstein",
      region: "europe",
      status: "sovereign",
      recognition: recognized(),
      un: unIneligible(),
      mapFeatureIds: ["438"],
    }),
    // Dependencies / special European territories
    tier3Entry(presetId, {
      entityId: "MT",
      displayName: "Malta",
      region: "europe",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British crown colony."),
      un: unIneligible(1964),
      lifecycle: { earliestYear: 1961, expectedYear: 1964, latestYear: 1970 },
      mapFeatureIds: ["470"],
    }),
    tier3Entry(presetId, {
      entityId: "CY",
      displayName: "Cyprus",
      region: "europe",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British crown colony."),
      un: unIneligible(1960),
      lifecycle: { earliestYear: 1958, expectedYear: 1960, latestYear: 1965 },
      mapFeatureIds: ["196"],
    }),
    tier3Entry(presetId, {
      entityId: "GI",
      displayName: "Gibraltar",
      region: "europe",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British overseas fortress colony."),
      un: unIneligible(),
      mapFeatureIds: ["292"],
    }),
    tier3Entry(presetId, {
      entityId: "FO",
      displayName: "Faroe Islands",
      region: "europe",
      status: "dependent",
      parentEntityId: "DK",
      recognition: dependentRecognition("Danish autonomous territory (home rule 1948)."),
      un: unIneligible(),
      mapFeatureIds: ["234"],
    }),
    tier3Entry(presetId, {
      entityId: "GL",
      displayName: "Greenland",
      region: "europe",
      status: "dependent",
      parentEntityId: "DK",
      recognition: dependentRecognition("Danish county after 1953 constitutional reform."),
      un: unIneligible(),
      mapFeatureIds: ["304"],
      notes: "1953 reform integrated Greenland as a Danish county; still parented to DK.",
    }),
    tier3Entry(presetId, {
      entityId: "SAAR",
      displayName: "Saar Protectorate",
      region: "europe",
      status: "dependent",
      parentEntityId: "FR",
      exceptionalStatus: "international-zone",
      recognition: dependentRecognition("French-administered Saar; referendum path to FRG."),
      un: unIneligible(),
      lifecycle: { earliestYear: 1955, expectedYear: 1957, latestYear: 1959 },
      notes: "Approx.: treated as FR-dependent protectorate pending 1955 Saar Statute vote.",
    }),
    tier3Entry(presetId, {
      entityId: "FTT",
      displayName: "Free Territory of Trieste",
      region: "europe",
      status: "dependent",
      exceptionalStatus: "international-zone",
      recognition: {
        status: "partial",
        notes: "UN-authorized Free Territory; Zone A/B under Allied/Yugoslav admin.",
      },
      un: unIneligible(),
      lifecycle: { earliestYear: 1954, expectedYear: 1954, latestYear: 1955 },
      notes: "Dissolves via London Memorandum 1954; no single metropolitan parent.",
    }),
  ];
}
