/**
 * Pacific — 1953 Tier-3 registry (#3728).
 *
 * Australia and New Zealand are sovereign Dominions. Remaining entries are
 * trust territories, colonies, and condominiums. The Trust Territory of the
 * Pacific Islands is the key US strategic trusteeship.
 */
import type { WorldEntityManifestEntry } from "@/lib/world/worldEntityManifest";
import { dependentRecognition, recognized, tier3Entry, unIneligible, unMember } from "./builders";

export function pacific1953Entries(presetId: string): WorldEntityManifestEntry[] {
  return [
    tier3Entry(presetId, {
      entityId: "AU",
      displayName: "Australia",
      region: "pacific",
      status: "sovereign",
      recognition: recognized("Commonwealth realm."),
      un: unMember(1945),
      mapFeatureIds: ["036"],
    }),
    tier3Entry(presetId, {
      entityId: "NZ",
      displayName: "New Zealand",
      region: "pacific",
      status: "sovereign",
      recognition: recognized("Commonwealth realm."),
      un: unMember(1945),
      mapFeatureIds: ["554"],
    }),
    tier3Entry(presetId, {
      entityId: "TTPI",
      displayName: "Trust Territory of the Pacific Islands",
      region: "pacific",
      status: "dependent",
      parentEntityId: "US",
      exceptionalStatus: "un-trust-territory",
      recognition: dependentRecognition("UN strategic trust under the United States."),
      un: unIneligible(),
      notes: "Covers Mariana, Caroline, and Marshall Islands groups.",
    }),
    tier3Entry(presetId, {
      entityId: "PNG",
      displayName: "Territory of Papua and New Guinea",
      region: "pacific",
      status: "dependent",
      parentEntityId: "AU",
      exceptionalStatus: "un-trust-territory",
      recognition: dependentRecognition("Australian-administered UN trust + Papua territory."),
      un: unIneligible(1975),
      lifecycle: { earliestYear: 1970, expectedYear: 1975, latestYear: 1980 },
      mapFeatureIds: ["598"],
      notes: "Approx.: Papua and New Guinea administered jointly by Australia from 1949.",
    }),
    tier3Entry(presetId, {
      entityId: "FJ",
      displayName: "Fiji",
      region: "pacific",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British crown colony."),
      un: unIneligible(1970),
      lifecycle: { earliestYear: 1965, expectedYear: 1970, latestYear: 1975 },
      mapFeatureIds: ["242"],
    }),
    tier3Entry(presetId, {
      entityId: "SB",
      displayName: "British Solomon Islands",
      region: "pacific",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition(),
      un: unIneligible(1978),
      mapFeatureIds: ["090"],
    }),
    tier3Entry(presetId, {
      entityId: "NC",
      displayName: "New Caledonia",
      region: "pacific",
      status: "dependent",
      parentEntityId: "FR",
      recognition: dependentRecognition("French overseas territory."),
      un: unIneligible(),
      mapFeatureIds: ["540"],
    }),
    tier3Entry(presetId, {
      entityId: "PF",
      displayName: "French Polynesia",
      region: "pacific",
      status: "dependent",
      parentEntityId: "FR",
      recognition: dependentRecognition("French overseas territory."),
      un: unIneligible(),
      mapFeatureIds: ["258"],
    }),
    tier3Entry(presetId, {
      entityId: "WS",
      displayName: "Western Samoa",
      region: "pacific",
      status: "dependent",
      parentEntityId: "NZ",
      exceptionalStatus: "un-trust-territory",
      recognition: dependentRecognition("UN trust territory under New Zealand."),
      un: unIneligible(1962),
      lifecycle: { earliestYear: 1960, expectedYear: 1962, latestYear: 1966 },
      mapFeatureIds: ["882"],
    }),
    tier3Entry(presetId, {
      entityId: "TO",
      displayName: "Tonga",
      region: "pacific",
      status: "dependent",
      parentEntityId: "UK",
      recognition: dependentRecognition("British protected kingdom."),
      un: unIneligible(1970),
      mapFeatureIds: ["776"],
    }),
    tier3Entry(presetId, {
      entityId: "NH",
      displayName: "New Hebrides",
      region: "pacific",
      status: "dependent",
      parentEntityId: "UK",
      exceptionalStatus: "condominium",
      recognition: dependentRecognition("Anglo-French condominium (later Vanuatu)."),
      un: unIneligible(1980),
      lifecycle: { earliestYear: 1975, expectedYear: 1980, latestYear: 1985 },
      mapFeatureIds: ["548"],
      notes: "Parent UK for attribution; France is condominium partner. Not 'Vanuatu' in 1953.",
    }),
    tier3Entry(presetId, {
      entityId: "GU",
      displayName: "Guam",
      region: "pacific",
      status: "dependent",
      parentEntityId: "US",
      exceptionalStatus: "integral-overseas",
      recognition: dependentRecognition("US unincorporated territory."),
      un: unIneligible(),
      mapFeatureIds: ["316"],
    }),
    tier3Entry(presetId, {
      entityId: "AS",
      displayName: "American Samoa",
      region: "pacific",
      status: "dependent",
      parentEntityId: "US",
      exceptionalStatus: "integral-overseas",
      recognition: dependentRecognition("US unincorporated territory."),
      un: unIneligible(),
      mapFeatureIds: ["016"],
    }),
    tier3Entry(presetId, {
      entityId: "CK",
      displayName: "Cook Islands",
      region: "pacific",
      status: "dependent",
      parentEntityId: "NZ",
      recognition: dependentRecognition("New Zealand dependency."),
      un: unIneligible(),
      mapFeatureIds: ["184"],
    }),
    tier3Entry(presetId, {
      entityId: "NAU",
      displayName: "Nauru",
      region: "pacific",
      status: "dependent",
      parentEntityId: "AU",
      exceptionalStatus: "un-trust-territory",
      recognition: dependentRecognition("UN trust under Australia (with UK/NZ)."),
      un: unIneligible(1968),
      lifecycle: { earliestYear: 1965, expectedYear: 1968, latestYear: 1972 },
      mapFeatureIds: ["520"],
    }),
  ];
}
