/**
 * NPP name pools, part two of nameLists4: YU, BLR, the BAL composite, Soviet
 * minority sub-pools for RU, and the GDR-era first names for DD. See nameLists4.ts
 * for the conventions.
 */

// ─── Yugoslavia ─────────────────────────────────────────────────────────────
// Pan-Yugoslav mix: predominantly the -ic patronymics shared across
// Serbia/Croatia/Bosnia/Montenegro, with Slovene and Macedonian entries.
// The -ic surnames do not inflect for gender.

export const YU_SURNAMES = [
  "Jovanovic",
  "Petrovic",
  "Nikolic",
  "Markovic",
  "Djordjevic",
  "Stojanovic",
  "Ilic",
  "Stankovic",
  "Pavlovic",
  "Todorovic",
  "Popovic",
  "Ristic",
  "Kovacevic",
  "Babic",
  "Horvat",
  "Kovacic",
  "Knezevic",
  "Vukovic",
  "Radovanovic",
  "Simic",
  "Zivkovic",
  "Lukic",
  "Mitrovic",
  "Kostic",
  "Savic",
  "Jankovic",
  "Maric",
  "Tomic",
  "Bogdanovic",
  "Lazic",
  "Mihajlovic",
  "Filipovic",
  "Radic",
  "Matic",
  "Milic",
  "Nedeljkovic",
  "Obradovic",
  "Perisic",
  "Rakic",
  "Simovic",
  "Stevanovic",
  "Vasic",
  "Vidovic",
  "Zoric",
  "Bozic",
  "Cvetkovic",
  "Dimitrijevic",
  "Gajic",
  "Zupan",
  "Kranjc",
  "Stojanovski",
  "Trajanovski",
  "Begic",
  "Hodzic",
  "Delic",
] as const;

export const YU_FIRST_NAMES_MALE = [
  "Dragan",
  "Zoran",
  "Milan",
  "Dusan",
  "Petar",
  "Ivan",
  "Josip",
  "Branko",
  "Milorad",
  "Nikola",
  "Djordje",
  "Aleksandar",
  "Ante",
  "Bogdan",
  "Bojan",
  "Boris",
  "Borislav",
  "Bozidar",
  "Branislav",
  "Damir",
  "Danilo",
  "Davor",
  "Dejan",
  "Dimitrije",
  "Dragoljub",
  "Dragutin",
  "Goran",
  "Ilija",
  "Janez",
  "Jovan",
  "Lazar",
  "Ljubomir",
  "Marko",
  "Mate",
  "Milenko",
  "Milos",
  "Miodrag",
  "Mirko",
  "Miroslav",
  "Mladen",
  "Nebojsa",
  "Nenad",
  "Predrag",
  "Ranko",
  "Sava",
  "Sinisa",
  "Slavko",
  "Srdjan",
  "Stevan",
  "Stjepan",
  "Tomislav",
  "Velimir",
  "Vladimir",
  "Zeljko",
  "Zivorad",
] as const;

export const YU_FIRST_NAMES_FEMALE = [
  "Marija",
  "Ana",
  "Milica",
  "Jelena",
  "Dragica",
  "Zorica",
  "Vesna",
  "Ljubica",
  "Gordana",
  "Radmila",
  "Slavica",
  "Snezana",
  "Mirjana",
  "Verica",
  "Danica",
  "Dusanka",
  "Grozdana",
  "Jasmina",
  "Jelica",
  "Jovanka",
  "Katarina",
  "Ljiljana",
  "Milena",
  "Mira",
  "Nada",
  "Nevenka",
  "Olga",
  "Olivera",
  "Radojka",
  "Ruzica",
  "Sanja",
  "Senka",
  "Slobodanka",
  "Smilja",
  "Sofija",
  "Stana",
  "Stanislava",
  "Svetlana",
  "Vera",
  "Vidosava",
  "Zagorka",
  "Zdenka",
  "Zlata",
  "Branka",
  "Biljana",
  "Bosiljka",
  "Cvijeta",
] as const;

// ─── Belarus ────────────────────────────────────────────────────────────────
// Belarusian patronymic surnames (-vich) and nature names do not inflect;
// the russified -ov/-sky minority share does, via the shared Slavic feminizer.
// Given names use Belarusian forms in plain transliteration.

export const BLR_SURNAMES = [
  "Abramovich",
  "Adamovich",
  "Bogdanovich",
  "Klimovich",
  "Makarevich",
  "Mitskevich",
  "Senkevich",
  "Stankevich",
  "Yushkevich",
  "Dashkevich",
  "Zhdanovich",
  "Naumovich",
  "Yurkevich",
  "Filipovich",
  "Karpovich",
  "Danilovich",
  "Gurinovich",
  "Sidorovich",
  "Borisevich",
  "Lukashevich",
  "Voitovich",
  "Matusevich",
  "Tarasevich",
  "Yatskevich",
  "Zinkevich",
  "Kazakevich",
  "Zhuk",
  "Maroz",
  "Kazak",
  "Shpak",
  "Kulik",
  "Dubovik",
  "Savitsky",
  "Kaminsky",
  "Novikov",
  "Kovalyov",
  "Drazdou",
  "Sakalou",
  "Lebedz",
  "Verabei",
  "Halavach",
  "Krupenka",
  "Sauko",
  "Tsyhanok",
  "Charnyak",
] as const;

export const BLR_FIRST_NAMES_MALE = [
  "Ales",
  "Aleh",
  "Andrei",
  "Anatol",
  "Anton",
  "Arseni",
  "Barys",
  "Bronislau",
  "Dzmitry",
  "Eduard",
  "Fyodar",
  "Henadz",
  "Ihar",
  "Ivan",
  "Kanstantsin",
  "Kastus",
  "Kiryl",
  "Leanid",
  "Maksim",
  "Mikalai",
  "Mikhas",
  "Pavel",
  "Pyotr",
  "Ryhor",
  "Siarhei",
  "Stanislau",
  "Stsiapan",
  "Uladzimir",
  "Vasil",
  "Viktar",
  "Vital",
  "Yanka",
  "Yauhen",
  "Yazep",
  "Yury",
  "Zmitser",
  "Alyaksandr",
  "Alyaksei",
  "Valery",
  "Mikola",
] as const;

export const BLR_FIRST_NAMES_FEMALE = [
  "Alena",
  "Aksana",
  "Alesia",
  "Ala",
  "Anastasiya",
  "Hanna",
  "Halina",
  "Iryna",
  "Katsiaryna",
  "Larysa",
  "Lidziya",
  "Lyudmila",
  "Maryna",
  "Maryya",
  "Nadzeya",
  "Natallia",
  "Nina",
  "Volha",
  "Palina",
  "Raisa",
  "Sviatlana",
  "Tamara",
  "Tatsiana",
  "Valiantsina",
  "Vera",
  "Veranika",
  "Viktoryia",
  "Yadviha",
  "Yanina",
  "Yauheniya",
  "Zinaida",
  "Zoya",
  "Sofiya",
  "Regina",
  "Danuta",
  "Vanda",
  "Alina",
  "Darya",
  "Klaudziya",
  "Stanislava",
] as const;

// ─── Baltics (BAL composite: Estonia / Latvia / Lithuania) ──────────────────
// BAL is a composite macro-country, so the pool is three national sub-pools;
// the generator picks one nationality per politician so given name and
// surname always come from the same tradition. Latvian and Lithuanian
// surnames inflect for gender; Estonian ones do not.

export const BAL_EE_SURNAMES = [
  "Tamm",
  "Saar",
  "Sepp",
  "Magi",
  "Kask",
  "Kukk",
  "Rebane",
  "Lepik",
  "Oja",
  "Luik",
  "Raudsepp",
  "Vaher",
  "Parn",
  "Koppel",
  "Laur",
  "Toom",
  "Uibo",
  "Valk",
  "Kuusk",
  "Mets",
  "Kivi",
  "Allik",
  "Kangur",
  "Karu",
  "Lill",
  "Nurk",
  "Ots",
  "Pold",
  "Raag",
  "Sikk",
  "Susi",
  "Teder",
  "Vares",
] as const;

export const BAL_EE_FIRST_NAMES_MALE = [
  "Jaan",
  "Juhan",
  "Peeter",
  "Andres",
  "Toomas",
  "Mart",
  "Mati",
  "Rein",
  "Tiit",
  "Enn",
  "Ants",
  "Arvo",
  "Eino",
  "Endel",
  "Heino",
  "Jaak",
  "Kalev",
  "Lembit",
  "Olev",
  "Priit",
  "Raivo",
  "Tarmo",
  "Urmas",
  "Vello",
  "Villem",
] as const;

export const BAL_EE_FIRST_NAMES_FEMALE = [
  "Aino",
  "Anne",
  "Ene",
  "Helgi",
  "Helle",
  "Hilja",
  "Kai",
  "Katrin",
  "Krista",
  "Leida",
  "Liia",
  "Linda",
  "Maie",
  "Mall",
  "Mare",
  "Merike",
  "Reet",
  "Salme",
  "Silvi",
  "Sirje",
  "Tiina",
  "Tiiu",
  "Ulle",
  "Virve",
  "Maret",
] as const;

export const BAL_LV_SURNAMES = [
  "Berzins",
  "Kalnins",
  "Ozolins",
  "Ozols",
  "Liepins",
  "Krumins",
  "Balodis",
  "Eglitis",
  "Vitols",
  "Zarins",
  "Sprogis",
  "Vanags",
  "Dzenis",
  "Purins",
  "Rozitis",
  "Strazdins",
  "Zvirbulis",
  "Lacis",
  "Vilks",
  "Briedis",
  "Celms",
  "Klavins",
  "Priede",
  "Roze",
  "Skuja",
  "Zeltins",
  "Auzins",
  "Dumins",
] as const;

export const BAL_LV_FIRST_NAMES_MALE = [
  "Janis",
  "Andris",
  "Juris",
  "Peteris",
  "Karlis",
  "Aivars",
  "Gunars",
  "Imants",
  "Ivars",
  "Maris",
  "Ojars",
  "Uldis",
  "Valdis",
  "Vilis",
  "Ziedonis",
  "Arturs",
  "Edgars",
  "Guntis",
  "Raimonds",
  "Visvaldis",
] as const;

export const BAL_LV_FIRST_NAMES_FEMALE = [
  "Anna",
  "Ilze",
  "Inese",
  "Maija",
  "Mara",
  "Aina",
  "Ausma",
  "Biruta",
  "Dzidra",
  "Elza",
  "Gaida",
  "Inta",
  "Laima",
  "Lidija",
  "Ligita",
  "Mirdza",
  "Rasma",
  "Skaidrite",
  "Velta",
  "Vija",
  "Zenta",
] as const;

export const BAL_LT_SURNAMES = [
  "Kazlauskas",
  "Jankauskas",
  "Petrauskas",
  "Stankevicius",
  "Vasiliauskas",
  "Zukauskas",
  "Butkus",
  "Paulauskas",
  "Urbonas",
  "Kavaliauskas",
  "Balciunas",
  "Rimkus",
  "Navickas",
  "Zilinskas",
  "Adomaitis",
  "Norkus",
  "Petraitis",
  "Ramanauskas",
  "Sakalauskas",
  "Simkus",
  "Vaitkus",
  "Venckus",
  "Zemaitis",
  "Gudaitis",
  "Jonaitis",
] as const;

export const BAL_LT_FIRST_NAMES_MALE = [
  "Jonas",
  "Antanas",
  "Juozas",
  "Petras",
  "Vytautas",
  "Kazys",
  "Algirdas",
  "Vincas",
  "Stasys",
  "Povilas",
  "Bronius",
  "Kestutis",
  "Gediminas",
  "Rimantas",
  "Algimantas",
  "Vladas",
  "Zenonas",
  "Saulius",
  "Mindaugas",
  "Romualdas",
] as const;

export const BAL_LT_FIRST_NAMES_FEMALE = [
  "Ona",
  "Aldona",
  "Birute",
  "Danute",
  "Elena",
  "Genovaite",
  "Irena",
  "Janina",
  "Jadvyga",
  "Regina",
  "Vida",
  "Nijole",
  "Ruta",
  "Laima",
  "Grazina",
  "Rasa",
  "Vitalija",
  "Zita",
  "Egle",
  "Audrone",
] as const;

// ─── RU minority sub-pools ──────────────────────────────────────────────────
// The RU country spans the whole Union, but name generation has no per-region
// hook (the generator receives only a countryId). These sub-pools give the
// non-Russian republics a weighted share of the single RU pool instead.
// Belarusian, Baltic, and Moldovan/Romanian shares reuse the pools above.

export const RU_UA_SURNAMES = [
  "Shevchenko",
  "Kovalenko",
  "Bondarenko",
  "Boyko",
  "Tkachenko",
  "Kravchenko",
  "Oliynyk",
  "Shevchuk",
  "Polishchuk",
  "Lysenko",
  "Savchenko",
  "Rudenko",
  "Marchenko",
  "Melnyk",
  "Kravets",
  "Sydorenko",
  "Havrylyuk",
  "Petrenko",
  "Klymenko",
  "Pavlenko",
] as const;

export const RU_UA_FIRST_NAMES_MALE = [
  "Taras",
  "Bohdan",
  "Ostap",
  "Mykola",
  "Petro",
  "Vasyl",
  "Oleksandr",
  "Oleh",
  "Yaroslav",
  "Volodymyr",
  "Dmytro",
  "Andriy",
  "Serhiy",
  "Mykhailo",
  "Ihor",
] as const;

export const RU_UA_FIRST_NAMES_FEMALE = [
  "Oksana",
  "Halyna",
  "Lesya",
  "Kateryna",
  "Olena",
  "Iryna",
  "Nadiya",
  "Natalka",
  "Solomiya",
  "Yaryna",
  "Zoryana",
  "Larysa",
  "Maryana",
  "Svitlana",
  "Tetyana",
] as const;

// Georgian (-dze/-shvili) and Armenian (-yan) surnames do not inflect;
// the russified Azerbaijani -ov forms do, correctly, via the shared feminizer.
export const RU_CAUCASUS_SURNAMES = [
  "Beridze",
  "Lomidze",
  "Gelashvili",
  "Kapanadze",
  "Tsiklauri",
  "Maisuradze",
  "Japaridze",
  "Chkheidze",
  "Abashidze",
  "Petrosyan",
  "Hakobyan",
  "Grigoryan",
  "Harutyunyan",
  "Vardanyan",
  "Avagyan",
  "Mammadov",
  "Hasanov",
  "Huseynov",
  "Ismayilov",
  "Guliyev",
] as const;

export const RU_CAUCASUS_FIRST_NAMES_MALE = [
  "Giorgi",
  "Levan",
  "Zurab",
  "Davit",
  "Irakli",
  "Armen",
  "Ashot",
  "Tigran",
  "Vahan",
  "Suren",
  "Rustam",
  "Elchin",
  "Farid",
  "Vugar",
  "Anar",
] as const;

export const RU_CAUCASUS_FIRST_NAMES_FEMALE = [
  "Nino",
  "Tamar",
  "Ketevan",
  "Natela",
  "Anush",
  "Gayane",
  "Siranush",
  "Lusine",
  "Anahit",
  "Leyla",
  "Aygun",
  "Sevinj",
  "Gulnara",
  "Nigar",
  "Manana",
] as const;

// Soviet-era Central Asian surnames carry the russified -ov/-ev endings and
// inflect for gender the Russian way (Akhmetov → Akhmetova).
export const RU_CENTRAL_ASIA_SURNAMES = [
  "Akhmetov",
  "Omarov",
  "Suleimenov",
  "Iskakov",
  "Yusupov",
  "Saidov",
  "Mirzayev",
  "Abdullayev",
  "Nurmatov",
  "Sultanov",
  "Alimov",
  "Ergashev",
  "Kasymov",
  "Zhumagulov",
  "Bekbolatov",
] as const;

export const RU_CENTRAL_ASIA_FIRST_NAMES_MALE = [
  "Serik",
  "Bolat",
  "Marat",
  "Askar",
  "Timur",
  "Bakhyt",
  "Yerlan",
  "Ulugbek",
  "Farrukh",
  "Aibek",
  "Daniyar",
  "Kairat",
  "Sanzhar",
  "Nurlan",
] as const;

export const RU_CENTRAL_ASIA_FIRST_NAMES_FEMALE = [
  "Aigul",
  "Gulnar",
  "Dinara",
  "Saule",
  "Zarina",
  "Madina",
  "Aliya",
  "Botagoz",
  "Dilnoza",
  "Feruza",
  "Gulmira",
  "Nargiza",
  "Zhanna",
  "Zulfiya",
] as const;

// ─── DD (GDR-era first names) ───────────────────────────────────────────────
// East Germany reuses the DE surname pool (the names are German either side
// of the wall) but draws first names from the 1950s-1980s cohorts that
// actually sat in the Volkskammer — no post-1990 fashions.

export const DD_FIRST_NAMES_MALE = [
  "Hans",
  "Werner",
  "Heinz",
  "Horst",
  "Klaus",
  "Guenter",
  "Gerhard",
  "Manfred",
  "Wolfgang",
  "Dieter",
  "Helmut",
  "Herbert",
  "Kurt",
  "Walter",
  "Karl",
  "Erich",
  "Rolf",
  "Siegfried",
  "Rudolf",
  "Wilhelm",
  "Otto",
  "Paul",
  "Ernst",
  "Fritz",
  "Willi",
  "Alfred",
  "Harry",
  "Joachim",
  "Lothar",
  "Rainer",
  "Reinhard",
  "Bernd",
  "Detlef",
  "Eberhard",
  "Egon",
  "Frank",
  "Gerd",
  "Hartmut",
  "Juergen",
  "Norbert",
  "Peter",
  "Uwe",
  "Volker",
  "Winfried",
  "Wolfram",
] as const;

export const DD_FIRST_NAMES_FEMALE = [
  "Ursula",
  "Helga",
  "Ingrid",
  "Gisela",
  "Christa",
  "Renate",
  "Monika",
  "Karin",
  "Erika",
  "Elke",
  "Hannelore",
  "Brigitte",
  "Gudrun",
  "Sigrid",
  "Barbara",
  "Marianne",
  "Ingeborg",
  "Edith",
  "Ilse",
  "Irmgard",
  "Hildegard",
  "Ruth",
  "Elfriede",
  "Gertrud",
  "Margot",
  "Anneliese",
  "Annemarie",
  "Baerbel",
  "Christel",
  "Dagmar",
  "Doris",
  "Edeltraud",
  "Gerda",
  "Hanna",
  "Heidrun",
  "Inge",
  "Jutta",
  "Katrin",
  "Kerstin",
  "Petra",
  "Regina",
  "Sabine",
  "Sieglinde",
  "Waltraud",
  "Ute",
] as const;
