/**
 * NPP economic (forex) account helpers.
 *
 * The full-wall separation: an NPP's `funds` field is its CAMPAIGN war chest
 * (political money — generated by nppFundGeneration, spent only on campaigns /
 * party org). All REAL-ECONOMY activity — buying shares, bonds, founding
 * corporations, index-fund investing, and every return they throw off — lives
 * in `nppInvestmentCashAnchor`, a ₳ (anchor) denominated personal forex account
 * fed by the NPP's GDP-per-capita personal income (see computeNPPInvestable
 * Budget). Campaign money never crosses into it, and it never funds a campaign.
 *
 * Market instruments (shares/bonds) are priced in the NPP's LOCAL home currency
 * (NPPs only transact home-currency paper), so the economic account converts at
 * the FX boundary: `anchor = local / homeRate`, matching the convention used by
 * nppActionProcessing's sweeps and corpLiquidCapitalToAnchor (homeRate = local
 * units per 1 ₳).
 */
import type { Db } from "mongodb";
import type { CountryId } from "@/lib/constants/countries";
import type { CurrencyCode } from "@/lib/constants/currencies";
import { COUNTRY_CURRENCY_MAP } from "@/lib/constants/currencies";
import { loadFxRatesByCurrency } from "@/lib/currency/corporationCapital";

/** Home-currency FX rate in LOCAL units per 1 ₳. `anchor = local / rate`. */
export async function nppHomeFxRate(
  db: Db,
  countryId: string | undefined,
  preloaded?: ReadonlyMap<CurrencyCode, number>
): Promise<number> {
  const code = (COUNTRY_CURRENCY_MAP[(countryId ?? "US") as CountryId] ?? "USD") as CurrencyCode;
  const fx = preloaded ?? (await loadFxRatesByCurrency(db));
  const r = fx.get(code);
  return r && r > 0 ? r : 1;
}

/** Convert a LOCAL home-currency amount to ₳ (anchor), rounded to cents. */
export function localToAnchor(local: number, homeRate: number): number {
  const rate = homeRate > 0 ? homeRate : 1;
  return Math.round((local / rate) * 100) / 100;
}
