import { it, expect, beforeEach, vi } from "vitest";
import type { Db } from "mongodb";
import { createMockDb, type MockDb } from "@/lib/test-utils/mockDb";

// Enumeration is exercised in countryAccess.test.ts; here we mock it so the
// phase test isolates the per-country spawn loop on a single enabled country.
vi.mock("@/lib/countryAccess", () => ({
  getSimulatedCountryIds: vi.fn().mockResolvedValue(["BR"]),
}));

import { processAutoDisasterTurn } from "./autoDisasterTurn";
import { getSimulatedCountryIds } from "@/lib/countryAccess";

let db: MockDb;

beforeEach(() => {
  db = createMockDb();
  ["countryGameStates", "crises", "states"].forEach((c) => db.collection(c));
  vi.clearAllMocks();
  vi.mocked(getSimulatedCountryIds).mockResolvedValue(["BR"]);
});

it("no-ops when the flag is off", async () => {
  await processAutoDisasterTurn(db as unknown as Db, 72, { autoDisastersEnabled: false });
  expect(getSimulatedCountryIds).not.toHaveBeenCalled();
  expect(db.collectionMocks["crises"]!.insertOne).not.toHaveBeenCalled();
});

it("spawns for a due country when the flag is on", async () => {
  // countryGameStates.findOne (called inside processAutoDisasterSpawn) returns the country doc
  // Turn 144 is exactly the cadence boundary from lastDisasterTurn=0 (144-turn cadence)
  db.collectionMocks["countryGameStates"]!.findOne.mockResolvedValue({
    _id: "BR",
    lastDisasterTurn: 0,
  });
  // crises.findOne: no existing active auto-disaster
  db.collectionMocks["crises"]!.findOne.mockResolvedValue(null);
  // states.find: one region
  db.collectionMocks["states"]!.find.mockReturnValue({
    toArray: vi.fn().mockResolvedValue([{ _id: "S1", countryId: "BR", regionType: "region" }]),
  });

  await processAutoDisasterTurn(db as unknown as Db, 144, { autoDisastersEnabled: true });

  expect(db.collectionMocks["crises"]!.insertOne).toHaveBeenCalledWith(
    expect.objectContaining({ autoGenerated: true, status: "active", countryIds: ["BR"] })
  );
});
