import type { StrategicRegion } from "./types";

// The 19 strategic regions, ported verbatim from the design mockup's DCLogic REGIONS.
export const STRATEGIC_REGIONS: StrategicRegion[] = [
  {
    id: "arc",
    name: "Arctic",
    short: "ARCTIC",
    macro: "Polar",
    terrain: "Ice / tundra",
    infra: 18,
    port: 2,
    air: 2,
    value: "Medium",
    threat: "Rising",
    instab: "Low",
    alliance: "Low",
    resource: "Growing",
    logi: "Severe",
    type: "naval",
  },
  {
    id: "noa",
    name: "North America",
    short: "N. AMERICA",
    macro: "Western Hemisphere",
    terrain: "Continental",
    infra: 92,
    port: 9,
    air: 10,
    value: "Very High",
    threat: "Low",
    instab: "Low",
    alliance: "Core",
    resource: "High",
    logi: "Low",
    type: "land",
  },
  {
    id: "nat",
    name: "North Atlantic",
    short: "N. ATLANTIC",
    macro: "Atlantic Basin",
    terrain: "Open ocean",
    infra: 60,
    port: 7,
    air: 4,
    value: "High",
    threat: "Medium",
    instab: "Low",
    alliance: "Core",
    resource: "Medium",
    logi: "Medium",
    type: "naval",
  },
  {
    id: "cac",
    name: "Central America & Caribbean",
    short: "CARIBBEAN",
    macro: "Western Hemisphere",
    terrain: "Jungle / littoral",
    infra: 44,
    port: 5,
    air: 4,
    value: "Medium",
    threat: "Medium",
    instab: "High",
    alliance: "Partial",
    resource: "Medium",
    logi: "Medium",
    type: "mixed",
  },
  {
    id: "sam",
    name: "South America",
    short: "S. AMERICA",
    macro: "Western Hemisphere",
    terrain: "Andes / rainforest",
    infra: 48,
    port: 5,
    air: 4,
    value: "Medium",
    threat: "Low",
    instab: "Medium",
    alliance: "Partial",
    resource: "High",
    logi: "High",
    type: "land",
  },
  {
    id: "sat",
    name: "South Atlantic",
    short: "S. ATLANTIC",
    macro: "Atlantic Basin",
    terrain: "Open ocean",
    infra: 30,
    port: 3,
    air: 2,
    value: "Low",
    threat: "Low",
    instab: "Low",
    alliance: "Low",
    resource: "Low",
    logi: "High",
    type: "naval",
  },
  {
    id: "weu",
    name: "Western Europe",
    short: "W. EUROPE",
    macro: "European Theater",
    terrain: "Developed plain",
    infra: 95,
    port: 8,
    air: 9,
    value: "Very High",
    threat: "High",
    instab: "Low",
    alliance: "Core",
    resource: "Medium",
    logi: "Low",
    type: "land",
  },
  {
    id: "eeu",
    name: "Eastern Europe",
    short: "E. EUROPE",
    macro: "European Theater",
    terrain: "Plain / forest",
    infra: 70,
    port: 4,
    air: 6,
    value: "Very High",
    threat: "Severe",
    instab: "Medium",
    alliance: "Contested",
    resource: "Medium",
    logi: "Medium",
    type: "land",
  },
  {
    id: "med",
    name: "Mediterranean",
    short: "MED",
    macro: "Southern Flank",
    terrain: "Sea / littoral",
    infra: 62,
    port: 8,
    air: 6,
    value: "High",
    threat: "High",
    instab: "Medium",
    alliance: "Partial",
    resource: "Medium",
    logi: "Medium",
    type: "naval",
  },
  {
    id: "naf",
    name: "North Africa",
    short: "N. AFRICA",
    macro: "Greater Central Region",
    terrain: "Desert / coast",
    infra: 42,
    port: 5,
    air: 5,
    value: "Medium",
    threat: "High",
    instab: "High",
    alliance: "Partial",
    resource: "High",
    logi: "High",
    type: "mixed",
  },
  {
    id: "ssa",
    name: "Sub-Saharan Africa",
    short: "SUB-SAHARAN",
    macro: "African Theater",
    terrain: "Savanna / jungle",
    infra: 34,
    port: 4,
    air: 3,
    value: "Medium",
    threat: "Medium",
    instab: "High",
    alliance: "Partial",
    resource: "Critical",
    logi: "High",
    type: "land",
  },
  {
    id: "mea",
    name: "Middle East",
    short: "MIDDLE EAST",
    macro: "Greater Central Region",
    terrain: "Desert / urban",
    infra: 54,
    port: 6,
    air: 8,
    value: "Very High",
    threat: "Severe",
    instab: "High",
    alliance: "Partial",
    resource: "Critical",
    logi: "High",
    type: "mixed",
  },
  {
    id: "cas",
    name: "Central Asia",
    short: "C. ASIA",
    macro: "Greater Central Region",
    terrain: "Steppe / mountain",
    infra: 30,
    port: 0,
    air: 4,
    value: "High",
    threat: "High",
    instab: "Medium",
    alliance: "Low",
    resource: "High",
    logi: "Severe",
    type: "land",
  },
  {
    id: "sas",
    name: "South Asia",
    short: "S. ASIA",
    macro: "Indo-Pacific",
    terrain: "Subcontinent",
    infra: 52,
    port: 6,
    air: 6,
    value: "High",
    threat: "High",
    instab: "Medium",
    alliance: "Partial",
    resource: "High",
    logi: "Medium",
    type: "mixed",
  },
  {
    id: "eas",
    name: "East Asia",
    short: "E. ASIA",
    macro: "Indo-Pacific",
    terrain: "Developed / coastal",
    infra: 88,
    port: 9,
    air: 9,
    value: "Very High",
    threat: "High",
    instab: "Low",
    alliance: "Contested",
    resource: "High",
    logi: "Medium",
    type: "mixed",
  },
  {
    id: "sea",
    name: "Southeast Asia",
    short: "SE ASIA",
    macro: "Indo-Pacific",
    terrain: "Archipelago / jungle",
    infra: 50,
    port: 7,
    air: 5,
    value: "High",
    threat: "Medium",
    instab: "Medium",
    alliance: "Partial",
    resource: "High",
    logi: "High",
    type: "mixed",
  },
  {
    id: "ior",
    name: "Indian Ocean",
    short: "INDIAN OCEAN",
    macro: "Indo-Pacific",
    terrain: "Open ocean",
    infra: 40,
    port: 5,
    air: 3,
    value: "High",
    threat: "Medium",
    instab: "Low",
    alliance: "Partial",
    resource: "High",
    logi: "Medium",
    type: "naval",
  },
  {
    id: "wpa",
    name: "Western Pacific",
    short: "W. PACIFIC",
    macro: "Indo-Pacific",
    terrain: "Island chains / sea",
    infra: 76,
    port: 9,
    air: 8,
    value: "Very High",
    threat: "High",
    instab: "Medium",
    alliance: "Contested",
    resource: "High",
    logi: "Medium",
    type: "naval",
  },
  {
    id: "spa",
    name: "South Pacific",
    short: "S. PACIFIC",
    macro: "Pacific Basin",
    terrain: "Scattered islands",
    infra: 28,
    port: 3,
    air: 2,
    value: "Low",
    threat: "Low",
    instab: "Low",
    alliance: "Partial",
    resource: "Low",
    logi: "High",
    type: "naval",
  },
];

const byId = new Map<string, StrategicRegion>(STRATEGIC_REGIONS.map((r) => [r.id, r]));

export function getRegion(id: string): StrategicRegion | undefined {
  return byId.get(id);
}

/** Group regions by macro (theater), preserving first-seen order. */
export function groupRegionsByTheater(
  regions: StrategicRegion[]
): { theater: string; regions: StrategicRegion[] }[] {
  const order: string[] = [];
  const map = new Map<string, StrategicRegion[]>();
  for (const r of regions) {
    if (!map.has(r.macro)) {
      map.set(r.macro, []);
      order.push(r.macro);
    }
    map.get(r.macro)!.push(r);
  }
  return order.map((theater) => ({ theater, regions: map.get(theater)! }));
}
