"use client";

import { useState } from "react";
import type { WorldTradeLedger } from "@/lib/trade/queries/worldTradeLedger";
import LedgerMasthead from "./components/LedgerMasthead";
import NationsView from "./components/NationsView";
import CommoditiesView from "./components/CommoditiesView";
import BilateralView from "./components/BilateralView";
import MatrixView from "./components/MatrixView";
import MapView from "./components/MapView";
import RestrictionsView from "./components/RestrictionsView";

/**
 * World Trade Ledger panel.
 *
 * ─── KNOWN EARLY-GAME LIMITATION (future-rework candidate) ───────────────────
 * This panel can look near-empty on a fresh world (e.g. turn 2 of a reset):
 * few or no commodities trade. That is NOT a trade-engine bug — the engine
 * faithfully clears whatever surplus/deficit exists. The root cause is upstream
 * in the COMMODITY system: per-country commodity SUPPLY is generated by *owned*
 * corporate sectors, and on a fresh world nobody owns sectors yet, so
 * `globalSupply` sits at the `BASE_COMMODITY_SUPPLY_DEMAND` stabilizer (~50k)
 * for almost every good — i.e. real production ≈ 0. With no producers, most
 * commodities have no exporting country, so nothing clears. (Unowned sectors
 * exist and carry revenue but do NOT feed commodity S/D.) The handful of goods
 * that do trade early are an artifact of rate-sensitive demand deltas going
 * negative, not real production. Trade fills in naturally as players buy/build
 * sectors — verified against a live world (turn 414), which shows rich, varied
 * flows.
 *
 * If a future maintainer wants the ledger to feel alive from turn 1, the fix is
 * in the commodity system (e.g. have unowned sectors contribute baseline supply),
 * NOT here — and it needs its own pricing/margin balance pass. See
 * scripts/debug/trade-turn2-flow-diag.ts for the diagnostic. Decision (2026-06):
 * leave as-is; trade ramps with the economy.
 * ─────────────────────────────────────────────────────────────────────────────
 */

type View = "nations" | "commodities" | "bilateral" | "matrix" | "map" | "restrictions";

const TABS: Array<{ id: View; label: string }> = [
  { id: "nations", label: "By Nation" },
  { id: "commodities", label: "By Commodity" },
  { id: "bilateral", label: "Bilateral" },
  { id: "matrix", label: "Trade Matrix" },
  { id: "map", label: "World Map" },
  { id: "restrictions", label: "Restrictions" },
];

const NOTES: Record<View, string> = {
  nations: "Net exports per nation · all markets · settled per the viewer's currency",
  commodities: "Tradeable goods · ranked by world traded volume",
  bilateral: "Pick a reporter and partner to settle their account",
  matrix: "Each cell: row nation's net balance vs. the column nation",
  map: "Click any market to isolate its trade flows · click again to release",
  restrictions: "Active embargoes and tariffs in force · grouped by the nation imposing them",
};

export default function WorldTradeClient({ ledger }: { ledger: WorldTradeLedger | null }) {
  const [view, setView] = useState<View>("nations");

  if (!ledger) {
    return (
      <div className="min-h-screen bg-background">
        <main className="mx-auto max-w-6xl px-4 py-16 text-center text-muted">
          No trade data yet — the first ledger publishes after the next turn.
        </main>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background pb-20">
      <main className="mx-auto max-w-6xl space-y-6 px-4 py-8 sm:px-6 lg:px-8">
        <LedgerMasthead ledger={ledger} />

        <div className="flex flex-wrap items-center justify-between gap-3">
          <div
            role="tablist"
            aria-label="Trade views"
            className="inline-flex flex-wrap gap-1 rounded-lg border border-card-border bg-card p-1"
          >
            {TABS.map((t) => (
              <button
                key={t.id}
                role="tab"
                aria-selected={view === t.id}
                onClick={() => setView(t.id)}
                className={`rounded-md px-4 py-2 text-sm font-semibold transition-colors ${
                  view === t.id
                    ? "bg-primary/15 text-foreground"
                    : "text-muted hover:text-foreground"
                }`}
              >
                {t.label}
              </button>
            ))}
          </div>
          <span className="text-[11.5px] text-muted">{NOTES[view]}</span>
        </div>

        {view === "nations" && <NationsView ledger={ledger} />}
        {view === "commodities" && <CommoditiesView ledger={ledger} />}
        {view === "bilateral" && <BilateralView ledger={ledger} />}
        {view === "matrix" && <MatrixView ledger={ledger} />}
        {view === "map" && <MapView ledger={ledger} />}
        {view === "restrictions" && <RestrictionsView ledger={ledger} />}
      </main>
    </div>
  );
}
