import { describe, it, expect, vi, beforeEach } from "vitest";
import { ObjectId } from "mongodb";
import type { Db } from "mongodb";
import { createMockDb, type MockDb } from "@/lib/test-utils/mockDb";
import type { WikiPage } from "@/lib/db/types";
import { seedWikiPages } from "./seeder";
import type { WikiSeedPage } from "./types";

const ADMIN_ID = new ObjectId("000000000000000000000001");

const seedPage: WikiSeedPage = {
  slug: "getting-started",
  title: "Getting Started",
  description: "Welcome to A House Divided",
  content: "# Getting Started\n\nSome body.",
  category: "getting-started",
  featured: true,
  difficulty: "beginner",
  contentType: "guide",
  estimatedReadTime: 5,
  lastUpdated: "2026-08-11",
};

function existingPage(overrides: Partial<WikiPage> = {}): WikiPage {
  return {
    _id: new ObjectId(),
    slug: seedPage.slug,
    title: "Old title",
    description: "Old desc",
    content: "Old content",
    status: "published",
    tags: ["getting-started"],
    featured: false,
    isAutoGenerated: false,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
    editHistory: [
      {
        userId: ADMIN_ID,
        timestamp: new Date("2026-01-01"),
        action: "created",
        note: "Reseed: initial insert",
      },
    ],
    ...overrides,
  };
}

describe("seedWikiPages", () => {
  let db: MockDb;

  beforeEach(() => {
    db = createMockDb();
  });

  it("inserts a new page when none exists", async () => {
    db.collectionMocks.wikiPages = db.collection("wikiPages");
    db.collectionMocks.wikiPages.findOne.mockResolvedValue(null);

    const result = await seedWikiPages(db as unknown as Db, ADMIN_ID, { pages: [seedPage] });

    expect(result.inserted).toEqual([seedPage.slug]);
    expect(result.updated).toEqual([]);
    expect(result.skipped).toEqual([]);
    expect(db.collectionMocks.wikiPages.insertOne).toHaveBeenCalledOnce();
    const inserted = db.collectionMocks.wikiPages.insertOne.mock.calls[0][0];
    expect(inserted.slug).toBe(seedPage.slug);
    expect(inserted.tags).toContain("getting-started");
    expect(inserted.status).toBe("published");
    expect(inserted.editHistory).toHaveLength(1);
    expect(inserted.lastUpdated).toEqual(new Date("2026-08-11T00:00:00.000Z"));
  });

  it("overwrites an existing seed-owned page when no human edits", async () => {
    db.collectionMocks.wikiPages = db.collection("wikiPages");
    db.collectionMocks.wikiPages.findOne.mockResolvedValue(existingPage());

    const result = await seedWikiPages(db as unknown as Db, ADMIN_ID, { pages: [seedPage] });

    expect(result.inserted).toEqual([]);
    expect(result.updated).toEqual([seedPage.slug]);
    expect(result.skipped).toEqual([]);
    expect(db.collectionMocks.wikiPages.updateOne).toHaveBeenCalledOnce();
  });

  it("skips pages with human edits unless force is set", async () => {
    db.collectionMocks.wikiPages = db.collection("wikiPages");
    const page = existingPage({
      editHistory: [
        { userId: ADMIN_ID, timestamp: new Date(), action: "created", note: "Reseed: initial" },
        { userId: ADMIN_ID, timestamp: new Date(), action: "edited", note: "manual tweak" },
      ],
    });
    db.collectionMocks.wikiPages.findOne.mockResolvedValue(page);

    const soft = await seedWikiPages(db as unknown as Db, ADMIN_ID, { pages: [seedPage] });
    expect(soft.updated).toEqual([]);
    expect(soft.skipped).toHaveLength(1);
    expect(soft.skipped[0].reason).toMatch(/human edits/);

    db.collectionMocks.wikiPages.findOne.mockResolvedValue(page);
    const hard = await seedWikiPages(db as unknown as Db, ADMIN_ID, {
      pages: [seedPage],
      force: true,
    });
    expect(hard.updated).toEqual([seedPage.slug]);
  });

  it("never touches auto-generated pages", async () => {
    db.collectionMocks.wikiPages = db.collection("wikiPages");
    db.collectionMocks.wikiPages.findOne.mockResolvedValue(existingPage({ isAutoGenerated: true }));

    const result = await seedWikiPages(db as unknown as Db, ADMIN_ID, {
      pages: [seedPage],
      force: true,
    });

    expect(result.updated).toEqual([]);
    expect(result.skipped).toHaveLength(1);
    expect(result.skipped[0].reason).toMatch(/Auto-generated/);
    expect(db.collectionMocks.wikiPages.updateOne).not.toHaveBeenCalled();
  });

  it("filters by slugs when provided", async () => {
    db.collectionMocks.wikiPages = db.collection("wikiPages");
    db.collectionMocks.wikiPages.findOne.mockResolvedValue(null);

    const other: WikiSeedPage = {
      ...seedPage,
      slug: "other-page",
      title: "Other",
      category: "reference",
    };

    const result = await seedWikiPages(db as unknown as Db, ADMIN_ID, {
      pages: [seedPage, other],
      slugs: [other.slug],
    });

    expect(result.inserted).toEqual([other.slug]);
    expect(db.collectionMocks.wikiPages.findOne).toHaveBeenCalledExactlyOnceWith({
      slug: other.slug,
    });
    // No mocking needed: vi falls through to the original mock for other call shapes
    vi.clearAllMocks();
  });

  it("resolves a lastUpdated date (YYYY-MM-DD) for every seed page", async () => {
    const { WIKI_SEED_PAGES } = await import("./pages");
    const { WIKI_LAST_UPDATED } = await import("./lastUpdated.generated");
    expect(WIKI_SEED_PAGES.length).toBeGreaterThan(50);
    for (const page of WIKI_SEED_PAGES) {
      const date = page.lastUpdated ?? WIKI_LAST_UPDATED[page.slug];
      expect(date, page.slug).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    }
  });
});
