import type { Db, ObjectId } from "mongodb";
import type { WikiPage } from "@/lib/db/types";
import type { WikiSeedPage } from "./types";
import { WIKI_SEED_PAGES } from "./pages";

export interface WikiSeedSkipped {
  slug: string;
  reason: string;
}

export interface WikiSeedResult {
  inserted: string[];
  updated: string[];
  skipped: WikiSeedSkipped[];
}

export interface WikiSeedOptions {
  /** When true, overwrite pages that have human edit history. */
  force?: boolean;
  /** When set, limit seeding to these slugs. */
  slugs?: string[];
  /** Override the seed list (tests). */
  pages?: readonly WikiSeedPage[];
}

/**
 * Treat a page as human-edited if anyone other than the seed author has edited
 * it, or if the edit history contains a non-"reseed" edit. Seed runs append
 * "Reseed" notes; anything else counts as a human edit and blocks non-force
 * overwrites.
 */
function hasHumanEdits(page: WikiPage): boolean {
  const history = page.editHistory ?? [];
  if (history.length === 0) return false;
  return history.some((h) => h.action !== "created" && !h.note?.startsWith("Reseed"));
}

function parseSeedDate(isoDate: string): Date {
  const parsed = new Date(`${isoDate}T00:00:00.000Z`);
  return Number.isNaN(parsed.getTime()) ? new Date() : parsed;
}

function pageDocForSeed(
  seed: WikiSeedPage,
  adminUserId: ObjectId,
  now: Date
): Omit<WikiPage, "_id"> {
  const tags = Array.from(new Set([seed.category, ...(seed.extraTags ?? [])]));
  const lastUpdated = parseSeedDate(seed.lastUpdated);
  return {
    slug: seed.slug,
    title: seed.title,
    description: seed.description,
    content: seed.content,
    status: "published",
    submittedBy: adminUserId,
    tags,
    featured: seed.featured ?? false,
    category: seed.category,
    contentType: seed.contentType,
    difficulty: seed.difficulty,
    estimatedReadTime: seed.estimatedReadTime,
    private: seed.private,
    countryId: seed.countryId,
    lastUpdated,
    designDocUrl: seed.designDocUrl,
    isAutoGenerated: false,
    createdAt: now,
    updatedAt: now,
    editHistory: [
      {
        userId: adminUserId,
        timestamp: now,
        action: "created",
        note: "Reseed: initial insert",
      },
    ],
  };
}

/**
 * Upsert seed pages into the `wikiPages` collection. Non-destructive by default:
 * pages with human edits are skipped unless `options.force` is set. Never touches
 * auto-generated pages (`isAutoGenerated: true`).
 */
export async function seedWikiPages(
  db: Db,
  adminUserId: ObjectId,
  options: WikiSeedOptions = {}
): Promise<WikiSeedResult> {
  const wikiPages = db.collection<WikiPage>("wikiPages");
  const list = options.pages ?? WIKI_SEED_PAGES;
  const filterSet = options.slugs?.length ? new Set(options.slugs) : null;
  const now = new Date();

  const inserted: string[] = [];
  const updated: string[] = [];
  const skipped: WikiSeedSkipped[] = [];

  for (const seed of list) {
    if (filterSet && !filterSet.has(seed.slug)) continue;

    const existing = await wikiPages.findOne({ slug: seed.slug });

    if (!existing) {
      await wikiPages.insertOne(pageDocForSeed(seed, adminUserId, now) as never);
      inserted.push(seed.slug);
      continue;
    }

    if (existing.isAutoGenerated) {
      skipped.push({ slug: seed.slug, reason: "Auto-generated page; not managed by seed" });
      continue;
    }

    if (hasHumanEdits(existing) && !options.force) {
      skipped.push({
        slug: seed.slug,
        reason: "Page has human edits (use --force to overwrite)",
      });
      continue;
    }

    const tags = Array.from(new Set([seed.category, ...(seed.extraTags ?? [])]));
    const lastUpdated = parseSeedDate(seed.lastUpdated);
    await wikiPages.updateOne(
      { slug: seed.slug },
      {
        $set: {
          title: seed.title,
          description: seed.description,
          content: seed.content,
          tags,
          category: seed.category,
          featured: seed.featured ?? false,
          contentType: seed.contentType,
          difficulty: seed.difficulty,
          estimatedReadTime: seed.estimatedReadTime,
          private: seed.private,
          countryId: seed.countryId,
          lastUpdated,
          designDocUrl: seed.designDocUrl,
          status: "published",
          updatedAt: now,
        },
        $push: {
          editHistory: {
            userId: adminUserId,
            timestamp: now,
            action: "edited",
            note: "Reseed: overwrite",
          },
        },
      }
    );
    updated.push(seed.slug);
  }

  return { inserted, updated, skipped };
}
