/** Country election phase names for progress displays, without engine imports.
 * Registry agreement is checked by countryElectionPhaseNames.test.ts.
 */
export const COUNTRY_ELECTION_PHASE_NAMES = [
  "ukElections",
  "ukRegionalCouncilElections",
  "ukGovernorElections",
  "jpElections",
  "jpRegionalCouncilElections",
  "jpCouncillorElections",
  "jpGovernorElections",
  "ieElections",
  "ieUachtaranElections",
  "ieLocalCouncilElections",
  "ieCathaoirleachElections",
  "deElections",
  "deLandtagElections",
  "deMinisterPresidentElections",
  "cnElections",
  "cnPeoplesCongressElections",
  "cnGovernorElections",
  "brElections",
  "brSenateElections",
  "ruSupremeSovietElections",
  "ruNationalitiesElections",
  "ruRepublicSovietElections",
  "ruGovernorElections",
  "ddVolkskammerElections",
  "ddLandAssemblyElections",
  "ddGovernorElections",
  "plSejmElections",
  "csChamberOfThePeopleElections",
  "huNationalAssemblyElections",
  "roGrandNationalAssemblyElections",
  "bgNationalAssemblyElections",
  "yuFederalAssemblyElections",
  "ukrSupremeSovietElections",
  "blrSupremeSovietElections",
  "balSupremeSovietElections",
  "ngElections",
  "ngSenateElections",
  "ngGovernorElections",
  "ngRegionalCouncilElections",
  "ngPresidentialElection",
  "scoElections",
  "scoGovernorElections",
  "scoRegionalCouncilElections",
  "walElections",
  "walGovernorElections",
  "walRegionalCouncilElections",
  "frElections",
  "frSenateElections",
  "itElections",
  "itSenateElections",
  "esElections",
  "esSenateElections",
  "seElections",
  "trElections",
  "trSenateElections",
  "grElections",
  "atElections",
  "fiElections",
] as const;

export type CountryElectionPhaseName = (typeof COUNTRY_ELECTION_PHASE_NAMES)[number];
