/**
 * Regenerates src/lib/seeds/wiki/lastUpdated.generated.ts: a slug -> YYYY-MM-DD map
 * derived from the git history of each wiki page's content file, so the "Updated"
 * badge always reflects the last real content change instead of a hand-maintained date.
 *
 * Run: npx tsx scripts/generate-wiki-last-updated.ts
 * Re-run whenever wiki content changes (wired into lint-staged for src/lib/seeds/wiki).
 */
import { execFileSync } from "child_process";
import { createRequire } from "module";
import { readFileSync, readdirSync, writeFileSync } from "fs";
import path from "path";

const ROOT = path.resolve(__dirname, "..");
const WIKI_DIR = path.join(ROOT, "src/lib/seeds/wiki");
const PAGES_DIR = path.join(WIKI_DIR, "pages");
const CONTENT_DIR = path.join(WIKI_DIR, "content");
const OUT_FILE = path.join(WIKI_DIR, "lastUpdated.generated.ts");

// Map exported content const name -> content file path
const exportToFile = new Map<string, string>();
for (const file of readdirSync(CONTENT_DIR)) {
  if (!file.endsWith(".ts") || file.endsWith(".test.ts")) continue;
  const src = readFileSync(path.join(CONTENT_DIR, file), "utf8");
  for (const m of src.matchAll(/export const (\w+)/g)) {
    exportToFile.set(m[1], path.join("src/lib/seeds/wiki/content", file));
  }
}

function lastCommitDate(repoRelPath: string): string | null {
  try {
    const out = execFileSync(
      "git",
      ["log", "-1", "--format=%ad", "--date=format:%Y-%m-%d", "--", repoRelPath],
      { cwd: ROOT, encoding: "utf8" }
    ).trim();
    return out || null;
  } catch {
    return null;
  }
}

const dateCache = new Map<string, string | null>();
const slugToDate: Record<string, string> = {};
let missing = 0;

for (const file of readdirSync(PAGES_DIR)) {
  if (!file.endsWith(".ts") || file.endsWith(".test.ts")) continue;
  const src = readFileSync(path.join(PAGES_DIR, file), "utf8");
  // Pair each slug with the content identifier in the same page object literal.
  for (const m of src.matchAll(/slug:\s*"([^"]+)"[\s\S]*?content:\s*(\w+)/g)) {
    const [, slug, contentVar] = m;
    const contentFile = exportToFile.get(contentVar);
    if (!contentFile) {
      missing++;
      console.warn(`no content file resolved for slug ${slug} (${contentVar})`);
      continue;
    }
    if (!dateCache.has(contentFile)) dateCache.set(contentFile, lastCommitDate(contentFile));
    const date = dateCache.get(contentFile);
    if (date) slugToDate[slug] = date;
    else {
      missing++;
      console.warn(`no git date for slug ${slug} (${contentFile})`);
    }
  }
}

// Programmatically generated pages (e.g. commodity-*) have no per-slug content
// file. Import the real page list and date any slug the static scan missed from
// the registration file that declares it (matched by slug literal or, failing
// that, the commodities builder file).
import { WIKI_SEED_PAGES } from "../src/lib/seeds/wiki/pages";
const pageFiles = readdirSync(PAGES_DIR)
  .filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts"))
  .map((f) => path.join("src/lib/seeds/wiki/pages", f));
for (const page of WIKI_SEED_PAGES) {
  if (slugToDate[page.slug]) continue;
  const declaring =
    pageFiles.find((f) => readFileSync(path.join(ROOT, f), "utf8").includes(`"${page.slug}"`)) ??
    "src/lib/seeds/wiki/pages/commodities.ts";
  if (!dateCache.has(declaring)) dateCache.set(declaring, lastCommitDate(declaring));
  const date = dateCache.get(declaring);
  if (date) slugToDate[page.slug] = date;
  else missing++;
}

const entries = Object.entries(slugToDate)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([slug, date]) => `  "${slug}": "${date}",`)
  .join("\n");

writeFileSync(
  OUT_FILE,
  `// AUTO-GENERATED by scripts/generate-wiki-last-updated.ts. Do not edit by hand.\n` +
    `// slug -> date of the last git commit that touched the page's content file.\n` +
    `export const WIKI_LAST_UPDATED: Record<string, string> = {\n${entries}\n};\n`
);

// `npx` on Windows is `npx.cmd`, which `execFileSync` cannot spawn without a
// shell — so this threw ENOENT and failed the pre-commit hook for anyone
// editing a wiki page on Windows. Resolve prettier's own entry point and run it
// through the SAME node binary instead: no shell, no PATH lookup, no
// platform-specific extension, and no shell-quoting question about a repo path
// containing spaces.
execFileSync(
  process.execPath,
  [createRequire(import.meta.url).resolve("prettier/bin/prettier.cjs"), "--write", OUT_FILE],
  { cwd: ROOT }
);

console.log(
  `wrote ${Object.keys(slugToDate).length} slugs to ${path.relative(ROOT, OUT_FILE)}${missing ? `, ${missing} unresolved` : ""}`
);
