import { NextResponse } from "next/server";
import { getDb } from "@/lib/mongodb";
import { requireModerator } from "@/lib/api/requireModerator";
import { parseJsonBody } from "@/lib/api/validate";
import { handleRouteError, errorResponse } from "@/lib/api/errors";
import { createWikiPageSchema } from "@/lib/api/schemas/wiki";
import type { WikiPage } from "@/lib/db/types";
import { getGameStamp } from "@/lib/wiki/gameConfig";
import { revalidatePath } from "next/cache";
import { ObjectId } from "mongodb";

// POST /api/admin/wiki — Creates and immediately publishes a new wiki page, bypassing the review queue.
// Auth: requireModerator (admins and moderators may publish directly)
// Errors: 400, 403
export async function POST(request: Request) {
  try {
    const auth = await requireModerator();
    if (!auth.ok) return auth.response;

    const parsed = await parseJsonBody(request, createWikiPageSchema);
    if (!parsed.success) {
      return errorResponse(parsed.status, parsed.error);
    }

    const db = await getDb();
    const wikiPages = db.collection<WikiPage>("wikiPages");

    // Check slug uniqueness
    const existing = await wikiPages.findOne({ slug: parsed.data.slug });
    if (existing) {
      return errorResponse(400, "A page with this slug already exists");
    }

    const now = new Date();
    const adminId = new ObjectId(auth.user.userId);
    const wikiPage: Omit<WikiPage, "_id"> = {
      ...parsed.data,
      status: "published", // Admin bypass review
      submittedBy: adminId,
      tags: parsed.data.tags || [],
      isAutoGenerated: false,
      ...getGameStamp(),
      createdAt: now,
      updatedAt: now,
      editHistory: [
        {
          userId: adminId,
          timestamp: now,
          action: "created",
        },
      ],
    };

    const result = await wikiPages.insertOne(wikiPage as unknown as WikiPage);
    const created = await wikiPages.findOne({ _id: result.insertedId });

    revalidatePath("/wiki");
    revalidatePath(`/wiki/${created?.slug}`);

    return NextResponse.json({ success: true, page: created, slug: created?.slug });
  } catch (error) {
    return handleRouteError(error);
  }
}
