import type { State } from "@/lib/db/types";
/** Poland regions (1979; Gierek era, Solidarity imminent) — eight historic
 *  macro-regions grouping the voivodeships. pop ≈ 35.5M; gdp in millions of
 *  złoty. houseDistricts = Sejm seats, apportioned by population (sum = 460,
 *  matching the country config's lowerChamber seats). */
export const plRegions: State[] = [
  {
    _id: "PL_MAZ",
    countryId: "PL",
    regionType: "state",
    name: "Mazovia",
    population: 4_900_000,
    gdp: 480_000,
    houseDistricts: 63,
    stateSenateSeats: 0,
    region: "Mazovia",
    votingSystem: "fptp",
  },
  {
    _id: "PL_LOD",
    countryId: "PL",
    regionType: "state",
    name: "Łódź & Holy Cross",
    population: 3_800_000,
    gdp: 320_000,
    houseDistricts: 49,
    stateSenateSeats: 0,
    region: "Łódź",
    votingSystem: "fptp",
  },
  {
    _id: "PL_MAL",
    countryId: "PL",
    regionType: "state",
    name: "Lesser Poland",
    population: 4_900_000,
    gdp: 380_000,
    houseDistricts: 63,
    stateSenateSeats: 0,
    region: "Lesser Poland",
    votingSystem: "fptp",
  },
  {
    _id: "PL_SLK",
    countryId: "PL",
    regionType: "state",
    name: "Silesia",
    population: 5_500_000,
    gdp: 620_000,
    houseDistricts: 71,
    stateSenateSeats: 0,
    region: "Silesia",
    votingSystem: "fptp",
  },
  {
    _id: "PL_DSL",
    countryId: "PL",
    regionType: "state",
    name: "Lower Silesia",
    population: 3_700_000,
    gdp: 340_000,
    houseDistricts: 48,
    stateSenateSeats: 0,
    region: "Lower Silesia",
    votingSystem: "fptp",
  },
  {
    _id: "PL_WLK",
    countryId: "PL",
    regionType: "state",
    name: "Greater Poland",
    population: 5_100_000,
    gdp: 400_000,
    houseDistricts: 66,
    stateSenateSeats: 0,
    region: "Greater Poland",
    votingSystem: "fptp",
  },
  {
    _id: "PL_POM",
    countryId: "PL",
    regionType: "state",
    name: "Pomerania & Masuria",
    population: 4_400_000,
    gdp: 300_000,
    houseDistricts: 57,
    stateSenateSeats: 0,
    region: "Pomerania",
    votingSystem: "fptp",
  },
  {
    _id: "PL_EAS",
    countryId: "PL",
    regionType: "state",
    name: "Eastern Poland",
    population: 3_200_000,
    gdp: 160_000,
    houseDistricts: 43,
    stateSenateSeats: 0,
    region: "Eastern Poland",
    votingSystem: "fptp",
  },
];
export default plRegions;
