import { describe, it, expect, beforeEach, vi } from "vitest";
import { MongoServerError, ObjectId } from "mongodb";
import { createMockDb, type MockDb, assertSetFields } from "@/lib/test-utils/mockDb";
import {
  resetGameWorld,
  PRESERVED_ACTIVITY_LOG_TYPES,
  RUNTIME_WIPE_SPECIAL_CASES,
} from "@/lib/admin/resetGameWorld";
import { retireCharacter } from "@/lib/retireCharacter";
import { getRuntimeCollectionNames } from "@/lib/admin/seed/seedManifest";
import { archiveOutgoingOfficeHistory } from "@/lib/wiki/autoGeneratedPages";

vi.mock("@/lib/admin/bootstrapGameWorld", () => ({
  seedAllCountryData: vi.fn().mockResolvedValue(undefined),
}));
vi.mock("@/lib/npp/seedHistorical", () => ({
  seedHistoricalOfficials: vi.fn().mockResolvedValue({ nppsCreated: 0, officialsCreated: 0 }),
}));

vi.mock("@/lib/constants/historicalSeats", () => ({
  getPresetById: vi.fn().mockReturnValue({ deleteDefaultParties: true }),
}));

vi.mock("@/lib/seeds/ensureDefaultParties", () => ({
  ensureDefaultParties: vi.fn().mockResolvedValue(undefined),
}));

vi.mock("@/lib/db/sequentialId", () => ({
  resetPartyCounters: vi.fn().mockResolvedValue(undefined),
  realignPartyCountersToExisting: vi.fn().mockResolvedValue(undefined),
  // ensureImfInstitutionPlaceholder calls getNextSequentialId during reset.
  getNextSequentialId: vi.fn().mockResolvedValue(1),
}));

vi.mock("@/lib/retireCharacter", () => ({
  retireCharacter: vi.fn().mockResolvedValue(undefined),
}));

vi.mock("@/lib/admin/seed/seedBudgets", () => ({
  seedBudgets: vi.fn().mockResolvedValue(undefined),
}));

vi.mock("@/lib/admin/seed/seedUkBudgets", () => ({
  seedUkBudgets: vi.fn().mockResolvedValue(undefined),
}));

vi.mock("@/lib/admin/seed/seedJpBudgets", () => ({
  seedJpBudgets: vi.fn().mockResolvedValue(undefined),
}));

vi.mock("@/lib/admin/seed/seedStatePolicies", () => ({
  seedStatePolicies: vi.fn().mockResolvedValue(undefined),
}));

vi.mock("@/lib/wiki/autoGeneratedPages", () => ({
  archiveOutgoingOfficeHistory: vi.fn().mockResolvedValue(0),
}));

describe("resetGameWorld", () => {
  it("wipes indexFunds with the rest of the world-bound fund ledger", () => {
    expect(getRuntimeCollectionNames()).toContain("indexFunds");
  });
  let db: MockDb;

  beforeEach(() => {
    db = createMockDb();
  });

  it("aborts before cleanup when reset recap source reads fail", async () => {
    const sourceReadError = new Error("timeline source unavailable");
    const characterId = new ObjectId();
    db.collection("gameState");
    db.collectionMocks.gameState.findOne.mockResolvedValue({
      _id: "current",
      seasonRecapEnabled: true,
      iteration: 4,
      currentTurn: 100,
      startingYear: 1991,
    });
    db.collection("characters");
    db.collectionMocks.characters.find.mockReturnValue({
      toArray: vi.fn().mockResolvedValue([
        {
          _id: characterId,
          name: "Test character",
          countryId: "US",
          party: "independent",
          createdTurn: 1,
        },
      ]),
    });
    db.collection("actionLogs");
    db.collectionMocks.actionLogs.aggregate.mockImplementation((pipeline) => {
      if (pipeline[0]?.$match?.turn) {
        return { toArray: vi.fn().mockRejectedValue(sourceReadError) };
      }
      return { toArray: vi.fn().mockResolvedValue([]) };
    });

    await expect(
      resetGameWorld(db as never, {
        deleteProfiles: false,
        preset: "1991-default",
        seedHistorical: false,
      })
    ).rejects.toBe(sourceReadError);

    expect(db.collectionMocks.actionLogs.deleteMany).not.toHaveBeenCalled();
    expect(db.collectionMocks.gameState.updateOne).not.toHaveBeenCalled();
    expect(archiveOutgoingOfficeHistory).not.toHaveBeenCalled();
  });

  it("captures complete recaps before cleanup when reset source reads succeed", async () => {
    const characterId = new ObjectId();
    const character = {
      _id: characterId,
      name: "Test character",
      countryId: "US",
      party: "independent",
      currentOffice: null,
      careerHistory: [],
      createdTurn: 1,
      nationalInfluence: 10,
      favorability: 50,
      infamy: 0,
    };
    db.collection("gameState");
    db.collectionMocks.gameState.findOne.mockResolvedValue({
      _id: "current",
      seasonRecapEnabled: true,
      iteration: { type: "Iteration", number: 4 },
      currentTurn: 100,
      startingYear: 1991,
    });
    db.collection("characters");
    db.collectionMocks.characters.find.mockReturnValue({
      toArray: vi.fn().mockResolvedValue([character]),
    });
    vi.mocked(retireCharacter).mockClear();

    await resetGameWorld(db as never, {
      deleteProfiles: false,
      preset: "1991-default",
      seedHistorical: false,
    });

    expect(retireCharacter).toHaveBeenCalledOnce();
    expect(vi.mocked(retireCharacter).mock.calls[0]?.[4]?.recap).toMatchObject({
      schemaVersion: 2,
      countryName: "United States",
    });
    expect(db.collectionMocks.actionLogs.deleteMany).toHaveBeenCalled();
  });

  it("preserves account join dates while retiring profiles for a new iteration", async () => {
    db.collection("characters");
    db.collectionMocks.characters.find.mockReturnValue({ toArray: async () => [] });
    await resetGameWorld(db as never, {
      deleteProfiles: false,
      seedHistorical: false,
      preset: "1991-default",
    });

    const users = db.collectionMocks.users;
    expect(users.deleteMany).not.toHaveBeenCalled();
    expect(users.replaceOne).not.toHaveBeenCalled();
    for (const [, update] of users.updateMany.mock.calls) {
      expect(update.$set ?? {}).not.toHaveProperty("createdAt");
      expect(update.$unset ?? {}).not.toHaveProperty("createdAt");
    }
    // The surviving history boundary must also stay fixed across resets.
    for (const [, update] of db.collectionMocks.gameState.updateOne.mock.calls) {
      expect(update.$set ?? {}).not.toHaveProperty("createdAt");
      expect(update.$unset ?? {}).not.toHaveProperty("createdAt");
    }
    expect(db.collectionMocks.gameConfig.updateOne).toHaveBeenCalledWith(
      { _id: "default" },
      { $unset: { fresh1991VehicleModelSeed: "", fresh1991MediaTaxonomySeed: "" } }
    );
  });

  it.each(["none", "default"] as const)(
    "overwrites the previous starting-party mode with %s",
    async (startingParties) => {
      db.collection("gameState");
      db.collectionMocks.gameState.findOne.mockResolvedValue({
        _id: "current",
        currentYear: 1991,
        iteration: 1,
        startingPartiesMode: startingParties === "none" ? "default" : "none",
      });
      await resetGameWorld(db as never, {
        deleteProfiles: true,
        preset: "1991-default",
        startingParties,
        seedHistorical: false,
        preIteration: true,
      });
      assertSetFields(db.collectionMocks.gameState.updateOne, {
        startingPartiesMode: startingParties,
        preset: "1991-default",
      });
      if (startingParties === "none") {
        const updates = db.collectionMocks.gameState.updateOne.mock.calls;
        expect(updates.some((call) => call[1].$unset?.preIteration === "")).toBe(true);
      }
    }
  );

  it("clears corporation world collections before resetting counters", async () => {
    await resetGameWorld(db as never, {
      deleteProfiles: true,
      preset: "2019-default",
      seedHistorical: false,
    });

    const clearedCollections = [
      "bondHistory",
      "bonds",
      "capitalActionLogs",
      "coalitions",
      "caucuses",
      "caucusMemberships",
      "caucusPolicyPositions",
      "corporationCeoVotes",
      "corporationHistory",
      "corporateSectors",
      "corporations",
      "countryState",
      "regimeEscalation",
      "extractionContracts",
      "investorRankingSnapshots",
      "marketCapHistory",
      "nppVoteCommitments",
      "nppVotePredictions",
      "politicalCapitalBalances",
      "recruitmentSlates",
      "slateCandidates",
      "shareListings",
      "shareOrders",
      "shareTradeHistory",
      "stockExchangeSnapshots",
      "treasuryTransactions",
    ];

    for (const name of clearedCollections) {
      expect(db.collectionMocks[name]?.drop).toHaveBeenCalled();
    }

    // Counters are wiped except for the party_<country> ones, which track
    // surviving default parties' sequentialIds — wiping them would make
    // ensureDefaultParties hand out a colliding seqId for a newly-added
    // preset-specific party (e.g. UUP when switching to 1991-default).
    expect(db.collectionMocks.counters?.deleteMany).toHaveBeenCalledWith({
      _id: { $not: { $regex: /^party_/ } },
    });
  });

  it("freezes outgoing office history and appends the new iteration to the registry", async () => {
    // Outgoing game state: currently Beta 2 with a known registry.
    db.collection("gameState"); // instantiate the lazy mock
    db.collectionMocks.gameState.findOne.mockResolvedValue({
      _id: "current",
      iteration: { type: "Beta", number: 2 },
      iterationHistory: [
        { type: "Alpha", number: 1 },
        { type: "Beta", number: 1 },
        { type: "Beta", number: 2 },
      ],
      currentTurn: 100,
      lastTurnProcessed: new Date("2020-01-01T00:00:00Z"),
      startingYear: 2019,
    });
    // One unstamped country-history event should be frozen under Beta 2.
    db.collection("countryHistory"); // instantiate the lazy mock
    db.collectionMocks.countryHistory.find.mockReturnValue({
      toArray: vi.fn().mockResolvedValue([{ _id: "c1", turn: 5 }]),
    });

    await resetGameWorld(db as never, {
      deleteProfiles: true,
      preset: "2019-default",
      seedHistorical: false,
      iteration: { type: "Beta", number: 3 },
    });

    // Freeze stamped the unstamped event with the OUTGOING iteration (Beta 2).
    assertSetFields(db.collectionMocks.countryHistory.updateOne, {
      iteration: { type: "Beta", number: 2 },
      iterationStartingYear: 2019,
    });

    // gameState updated with the registry extended by the new iteration (Beta 3).
    assertSetFields(db.collectionMocks.gameState.updateOne, {
      iterationHistory: [
        { type: "Alpha", number: 1 },
        { type: "Beta", number: 1 },
        { type: "Beta", number: 2 },
        { type: "Beta", number: 3 },
      ],
    });

    // The wiki archive ran against the OUTGOING world's clock.
    expect(archiveOutgoingOfficeHistory).toHaveBeenCalledWith(
      db,
      expect.objectContaining({
        iteration: { type: "Beta", number: 2 },
        currentTurn: 100,
        startingYear: 2019,
      }),
      expect.any(Date)
    );
  });

  it("freezes and archives office history before the sweep drops the office tables", async () => {
    vi.mocked(archiveOutgoingOfficeHistory).mockClear();
    db.collection("gameState");
    db.collectionMocks.gameState.findOne.mockResolvedValue({
      _id: "current",
      iteration: { type: "Beta", number: 2 },
      currentTurn: 100,
      lastTurnProcessed: new Date("2020-01-01T00:00:00Z"),
      startingYear: 2019,
    });
    for (const name of ["countryHistory", "cabinetNominations", "electedOfficials"]) {
      db.collection(name);
    }
    db.collectionMocks.countryHistory.find.mockReturnValue({
      toArray: vi.fn().mockResolvedValue([{ _id: "c1", turn: 5 }]),
    });

    await resetGameWorld(db as never, {
      deleteProfiles: false,
      preset: "2019-default",
      seedHistorical: false,
    });

    const archivedAt = vi.mocked(archiveOutgoingOfficeHistory).mock.invocationCallOrder[0];
    const frozenAt = db.collectionMocks.countryHistory.updateOne.mock.invocationCallOrder[0];
    expect(frozenAt).toBeLessThan(archivedAt);
    // Every table the office pages read is still intact when the archive runs.
    expect(archivedAt).toBeLessThan(
      db.collectionMocks.countryHistory.drop.mock.invocationCallOrder[0]
    );
    expect(archivedAt).toBeLessThan(
      db.collectionMocks.cabinetNominations.drop.mock.invocationCallOrder[0]
    );
    expect(archivedAt).toBeLessThan(
      db.collectionMocks.electedOfficials.deleteMany.mock.invocationCallOrder[0]
    );
  });

  // ── Reset / manifest contract ──────────────────────────────────────────────
  // The reset wipe is driven by getRuntimeCollectionNames(). These tests pin the
  // contract so a runtime collection can never again silently survive a reset
  // (the bug class this replaced): every runtime collection is either wiped by
  // the blanket sweep or explicitly listed in RUNTIME_WIPE_SPECIAL_CASES.
  it("wipes every runtime collection not handled as a special case", async () => {
    await resetGameWorld(db as never, {
      deleteProfiles: true,
      preset: "2019-default",
      seedHistorical: false,
    });

    for (const name of getRuntimeCollectionNames()) {
      if (RUNTIME_WIPE_SPECIAL_CASES.has(name)) continue;
      expect(
        db.collectionMocks[name]?.drop,
        `runtime collection "${name}" was not wiped on reset — add it to the sweep or to RUNTIME_WIPE_SPECIAL_CASES`
      ).toHaveBeenCalled();
    }
  });

  it("wipes product projects and their corporation-embedded paid receipts on reset", async () => {
    await resetGameWorld(db as never, {
      deleteProfiles: true,
      preset: "1991-default",
      seedHistorical: false,
    });

    expect(db.collectionMocks.manufacturingProductProjectsV2.drop).toHaveBeenCalled();
    expect(db.collectionMocks.corporations.drop).toHaveBeenCalled();
  });

  it("allows missing runtime collections on clean and repeat resets", async () => {
    db.collection("conflicts");
    db.collectionMocks.conflicts.drop.mockRejectedValue(
      new MongoServerError({ message: "namespace not found", code: 26 })
    );
    for (let attempt = 0; attempt < 2; attempt++) {
      await resetGameWorld(db as never, {
        deleteProfiles: true,
        preset: "1991-default",
        seedHistorical: false,
      });
    }
    expect(db.collectionMocks.conflicts.drop).toHaveBeenCalledTimes(2);
    expect(db.collectionMocks.gameState.updateOne).toHaveBeenCalled();
  });

  it.each([
    new MongoServerError({ message: "not authorized to drop collection", code: 13 }),
    new Error("connection interrupted"),
  ])("refuses a successful reset when required conflict cleanup fails: %s", async (error) => {
    db.collection("conflicts");
    db.collection("gameState");
    db.collectionMocks.conflicts.drop.mockRejectedValue(error);
    const log = vi.fn();
    await expect(
      resetGameWorld(db as never, {
        deleteProfiles: true,
        preset: "1991-default",
        seedHistorical: false,
        log,
      })
    ).rejects.toThrow("Required reset cleanup failed for: conflicts");
    expect(db.collectionMocks.gameState.updateOne).not.toHaveBeenCalled();
    expect(log.mock.calls.some(([message]) => String(message).includes("Wiped "))).toBe(false);
  });

  it("waits for all cleanup operations and reports every failed collection", async () => {
    for (const name of ["conflicts", "peaceOffers", "navairChannels"]) db.collection(name);
    const first = new Error("conflict drop denied");
    const second = new Error("peace offer drop denied");
    db.collectionMocks.conflicts.drop.mockRejectedValue(first);
    db.collectionMocks.peaceOffers.drop.mockRejectedValue(second);
    let cleanupFinished = false;
    db.collectionMocks.navairChannels.drop.mockImplementation(async () => {
      await Promise.resolve();
      cleanupFinished = true;
    });
    const failure = await resetGameWorld(db as never, {
      deleteProfiles: true,
      preset: "1991-default",
      seedHistorical: false,
    }).catch((error: unknown) => error);
    expect(cleanupFinished).toBe(true);
    expect(failure).toBeInstanceOf(AggregateError);
    expect(failure).toHaveProperty(
      "message",
      "Required reset cleanup failed for: conflicts, peaceOffers"
    );
    expect(failure).toHaveProperty("errors", [first, second]);
  });

  it("handles every special-cased runtime collection explicitly", async () => {
    // Instantiate BEFORE the call — a lazy mock created afterwards has no
    // recorded calls, so the `not.toHaveBeenCalled()` below would pass no
    // matter what the sweep did.
    db.collection("partyCharters");

    await resetGameWorld(db as never, {
      deleteProfiles: true,
      preset: "2019-default",
      seedHistorical: false,
    });

    // The eight counted collections are deleted with {} so we can report counts.
    for (const name of [
      "electedOfficials",
      "elections",
      "electionCandidates",
      "npps",
      "actionLogs",
      "bills",
      "stateBills",
      "statePartyElections",
    ]) {
      expect(db.collectionMocks[name]?.deleteMany).toHaveBeenCalledWith({});
    }

    // counters: partial delete that spares party_<country> counters.
    expect(db.collectionMocks.counters?.deleteMany).toHaveBeenCalledWith({
      _id: { $not: { $regex: /^party_/ } },
    });

    // gameState: `current` is re-initialized in place, never blanket-deleted.
    // Only non-`current` squatter documents are removed (see the dedicated test
    // below) — a `deleteMany({})` here would destroy the world's own state doc.
    expect(db.collectionMocks.gameState?.updateOne).toHaveBeenCalled();
    expect(db.collectionMocks.gameState?.deleteMany).not.toHaveBeenCalledWith({});

    // partyCharters: excluded from the sweep because the preset-aware charter
    // cleanup owns it — that cleanup now runs in `finalizeResetGameWorld`,
    // after bootstrap, where the surviving parties' sequentialIds are the new
    // world's rather than the dead world's. What this test pins is the half
    // that stayed here: the blanket sweep must NOT drop it.
    expect(db.collectionMocks.partyCharters.drop).not.toHaveBeenCalled();

    // activityLog: partial delete that keeps the account history rows.
    expect(db.collectionMocks.activityLog?.deleteMany).toHaveBeenCalledWith({
      type: { $nin: ["login", "logout", "character_deleted"] },
    });
  });

  it.each([true, false])(
    "keeps login IP history and deletion markers in activityLog (deleteProfiles: %s)",
    async (deleteProfiles) => {
      db.collection("activityLog");
      db.collection("characters");
      db.collectionMocks.characters.find.mockReturnValue({ toArray: async () => [] });

      await resetGameWorld(db as never, {
        deleteProfiles,
        preset: "1991-default",
        seedHistorical: false,
      });

      const activityLog = db.collectionMocks.activityLog;
      expect(activityLog.drop).not.toHaveBeenCalled();
      expect(activityLog.deleteMany).toHaveBeenCalledTimes(1);
      const [filter] = activityLog.deleteMany.mock.calls[0];
      for (const kept of PRESERVED_ACTIVITY_LOG_TYPES) {
        expect(filter.type.$nin).toContain(kept);
      }
      for (const worldType of ["turn_summary", "game_action", "fund_event", "party_change"]) {
        expect(filter.type.$nin).not.toContain(worldType);
      }
    }
  );

  it("keeps staff and banned accounts through a full reset", async () => {
    db.collection("users");

    await resetGameWorld(db as never, {
      deleteProfiles: true,
      preset: "1991-default",
      seedHistorical: false,
    });

    const users = db.collectionMocks.users;
    expect(users.deleteMany).toHaveBeenCalledTimes(1);
    expect(users.deleteMany).toHaveBeenCalledWith({
      isAdmin: { $ne: true },
      role: { $nin: ["admin", "moderator"] },
      isBanned: { $ne: true },
    });
    // Survivors lost every character, so the one-character limit must not
    // still count the deleted ones.
    expect(users.updateMany).toHaveBeenCalledWith(
      {},
      { $set: { hasCompletedSetup: false, activeCharacterCount: 0 } }
    );
    // The surviving counter reset runs after the delete, so it only ever
    // touches the kept accounts.
    expect(users.deleteMany.mock.invocationCallOrder[0]).toBeLessThan(
      users.updateMany.mock.invocationCallOrder.at(-1)!
    );
  });

  it("clears the previous world's per-world progress guards from gameState", async () => {
    // Outgoing world: a 2010s world whose turn phases have all fired. Every
    // field here is a "last time this fired" guard read by the NEW world.
    db.collection("gameState");
    db.collectionMocks.gameState.findOne.mockResolvedValue({
      _id: "current",
      currentTurn: 944,
      startingYear: 2019,
      lastCensusYear: 2010,
      lastAutoSeedTurn: 944,
      lastBundestagReconciledCycle: 6,
      currentEraId: "2010s",
      lastEraCrossedYear: 2010,
      lastMetricActivationYear: 2015,
    });

    await resetGameWorld(db as never, {
      deleteProfiles: true,
      preset: "2019-default",
      seedHistorical: false,
    });

    const currentUpdate = db.collectionMocks.gameState.updateOne.mock.calls.find(
      (c) => (c[0] as { _id?: string })?._id === "current"
    );
    expect(currentUpdate).toBeDefined();
    const unset = (currentUpdate![1] as { $unset?: Record<string, string> }).$unset;

    // Each of these left a real, confirmed regression on a live 1953 world:
    //  - lastCensusYear 2010 → no census fires until game-year 2020
    //  - lastAutoSeedTurn 944 vs currentTurn 1 → auto sector seeding never fires
    //  - lastBundestagReconciledCycle 6 → German AMS skipped for cycles 0-6
    for (const key of [
      "lastCensusYear",
      "lastCensus",
      "lastAutoSeedTurn",
      "lastExtractionAutoStrategyTurn",
      "lastBundestagReconciledCycle",
      "lastCabinetYearProcessed",
      "huAssemblyReformedAtYear",
      "currentEraId",
      "lastEraCrossedYear",
      "lastMetricActivationYear",
      "eraGdpPerCapitaBaseline",
      "incomeBandIndexByCountry",
      "presidentialTenureByCountry",
    ]) {
      expect(unset?.[key], `gameState.${key} must be unset by the reset`).toBe("");
    }

    // The $set and $unset must never share a key — MongoDB rejects that update.
    const set = (currentUpdate![1] as { $set?: Record<string, unknown> }).$set ?? {};
    expect(Object.keys(set).filter((k) => k in (unset ?? {}))).toEqual([]);
  });

  it("removes squatter documents from gameState without touching `current`", async () => {
    await resetGameWorld(db as never, {
      deleteProfiles: true,
      preset: "2019-default",
      seedHistorical: false,
    });

    // `triggerDebtCeilingCrisis` writes `_id: "debt_ceiling_crisis"` into the
    // gameState collection. gameState is exempt from the runtime sweep and the
    // reset's update is filtered to `_id: "current"`, so before this purge no
    // reset could ever remove it — a 1993 crisis was still `active: true` on a
    // live 1953 world.
    expect(db.collectionMocks.gameState?.deleteMany).toHaveBeenCalledWith({
      _id: { $ne: "current" },
    });
    // Never a blanket wipe — that would delete the world's own state document.
    expect(db.collectionMocks.gameState?.deleteMany).not.toHaveBeenCalledWith({});
  });

  // ── Observability ─────────────────────────────────────────────────────────
  // The reset phase used to run entirely silently: `ResetGameWorldOptions` had
  // no `log`, and the call to `seedAllCountryData` passed `() => {}`. An admin
  // watching a reset saw nothing at all until the bootstrap phase began — which
  // is roughly half the wall time — and every seeder line that DID appear was
  // unattributable, because the bootstrap phase re-runs many of the same
  // seeders and logs identical text.
  describe("logging", () => {
    async function linesFrom(): Promise<string[]> {
      const lines: string[] = [];
      await resetGameWorld(db as never, {
        deleteProfiles: true,
        preset: "2019-default",
        seedHistorical: false,
        log: (msg) => lines.push(msg),
      });
      return lines;
    }

    it("sends its progress to the caller's sink", async () => {
      expect((await linesFrom()).length).toBeGreaterThan(0);
    });

    it("tags every line so the teardown is distinguishable from the bootstrap that follows", async () => {
      // `resetAndBootstrapGameWorld` runs bootstrapGameWorld straight after this
      // function and pipes both into one stream. Without the tag the two phases
      // are indistinguishable in the admin log.
      const lines = await linesFrom();
      expect(lines.every((l) => l.startsWith("[reset] "))).toBe(true);
    });

    it("does not throw when no logger is supplied", async () => {
      await expect(
        resetGameWorld(db as never, {
          deleteProfiles: true,
          preset: "2019-default",
          seedHistorical: false,
        })
      ).resolves.toBeTruthy();
    });

    it("reports the runtime wipe with a collection count", async () => {
      expect(
        (await linesFrom()).some((l) => /^\[reset] Wiped \d+ runtime collections/.test(l))
      ).toBe(true);
    });

    it("reports character retirement, which is a silent per-character loop", async () => {
      db.collection("characters");
      db.collectionMocks.characters.find.mockReturnValue({
        toArray: async () => [
          { _id: { toString: () => "c1" }, userId: "u1" },
          { _id: { toString: () => "c2" }, userId: "u1" },
        ],
      });
      const lines: string[] = [];

      await resetGameWorld(db as never, {
        deleteProfiles: false,
        preset: "2019-default",
        seedHistorical: false,
        log: (msg) => lines.push(msg),
      });

      expect(lines.some((l) => /^\[reset] Retired 2 character\(s\)/.test(l))).toBe(true);
    });

    it("signs off by naming what comes next, so a truncated log is legible", async () => {
      // A reset that dies mid-run leaves the admin with a partial transcript.
      // The closing line is how they tell "teardown finished, bootstrap was
      // running" from "teardown itself died".
      expect((await linesFrom()).some((l) => l.includes("Teardown complete"))).toBe(true);
    });
  });
});
