// State name mapping
export const STATE_NAMES: Record<string, string> = {
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
  DC: "District of Columbia",
};

// State regions for regional breakdown
export const STATE_REGIONS: Record<string, string> = {
  CT: "Northeast",
  DE: "Northeast",
  MA: "Northeast",
  MD: "Northeast",
  ME: "Northeast",
  NH: "Northeast",
  NJ: "Northeast",
  NY: "Northeast",
  PA: "Northeast",
  RI: "Northeast",
  VT: "Northeast",
  AL: "South",
  AR: "South",
  FL: "South",
  GA: "South",
  KY: "South",
  LA: "South",
  MS: "South",
  NC: "South",
  SC: "South",
  TN: "South",
  VA: "South",
  WV: "South",
  IA: "Midwest",
  IL: "Midwest",
  IN: "Midwest",
  KS: "Midwest",
  MI: "Midwest",
  MN: "Midwest",
  MO: "Midwest",
  ND: "Midwest",
  NE: "Midwest",
  OH: "Midwest",
  SD: "Midwest",
  WI: "Midwest",
  AZ: "West",
  AK: "West",
  CA: "West",
  CO: "West",
  HI: "West",
  ID: "West",
  MT: "West",
  NM: "West",
  NV: "West",
  OK: "West",
  OR: "West",
  TX: "West",
  UT: "West",
  WA: "West",
  WY: "West",
};

export interface StateResult {
  stateId: string;
  stateName: string;
  ev: number;
  winnerId: string;
  winnerName: string;
  winnerColor: string;
  margin: number;
  winnerPct: number;
  totalVotes: number;
}
